src/core-crm/objects/Engagement_List_Configuration__c/Engagement_List_Configuration__c.object-meta.xml
<CustomObject>
    <description>Contains the details of a call/outreach campaign.</description>
    <label>Engagement List Configuration</label>
    <nameField>
        <label>Engagement List Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement List Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Engagement_List_Configuration__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>The date the engagement list configuration was deactivated</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Engagement_List_Configuration__c/fields/Engagement_List_Configuration_Status__c.field-meta.xml
<CustomField>
    <fullName>Engagement_List_Configuration_Status__c</fullName>
    <description>The status of engagement list configuration in its life cycle</description>
    <label>Engagement List Configuration  Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft (Default)</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Engagement_List_Configuration__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>The date the engagement list configuration comes into effect</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Engagement_List_Criteria__c/Engagement_List_Criteria__c.object-meta.xml
<CustomObject>
    <description>Contains the entry or exit criteria or ad hoc import information for an engagement list configuration.</description>
    <label>Engagement List Criteria</label>
    <nameField>
        <label>Engagement List Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement List Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/Engagement_List_Criteria__c/fields/Citizenship_Status__c.field-meta.xml
<CustomField>
    <fullName>Citizenship_Status__c</fullName>
    <description>Citizenship status to filter contact for criteria</description>
    <label>Citizenship Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Citizenship_Status</valueSetName>
    </valueSet>
</CustomField>

src/core-crm/objects/Engagement_List_Criteria__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End date of the engagement list criteria</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Engagement_List_Criteria__c/fields/Engagement_List_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Engagement_List_Configuration__c</fullName>
    <description>The engagement list configuration the engagement list criteria belongs to</description>
    <label>Engagement List Configuration</label>
    <referenceTo>Engagement_List_Configuration__c</referenceTo>
    <relationshipLabel>Engagement List Criteria</relationshipLabel>
    <relationshipName>Engagement_List_Criteria</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/core-crm/objects/Engagement_List_Criteria__c/fields/Engagement_List_Criteria_Title__c.field-meta.xml
<CustomField>
    <fullName>Engagement_List_Criteria_Title__c</fullName>
    <description>A short title describing the Engagement List Criteria.</description>
    <label>Engagement List Criteria Title</label>
    <length>160</length>
    <type>Text</type>
</CustomField> 

src/core-crm/objects/Engagement_List_Criteria__c/fields/Preview_Result_Attachment_Id__c.field-meta.xml
<CustomField>
    <fullName>Preview_Result_Attachment_Id__c</fullName>
    <description>The attachment ID of the generated CSV file</description>
    <label>Preview Result Attachment ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Engagement_List_Criteria__c/fields/Preview_Status__c.field-meta.xml
<CustomField>
    <fullName>Preview_Status__c</fullName>
    <description>The status of the preview generation process</description>
    <label>Preview Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Generated</fullName>
                <default>true</default>
                <label>Not Generated</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Engagement_List_Criteria__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>The start date of the engagement list criteria</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/globalValueSets/Citizenship_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Domestic</fullName>
    </customValue>
    <customValue>
        <fullName>International</fullName>
    </customValue>
    <masterLabel>Citizenship Status</masterLabel>
</GlobalValueSet>

src/core-crm/classes/EngagementListCriteriaTriggerHelperTest.cls
/**
 * @description Test class for EngagementListCriteriaTriggerHelper
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | roy.nino.s.regala              | May 24, 2024          | DEPP-8745              | Created file                 |
 */
@isTest
private class EngagementListCriteriaTriggerHelperTest {
    @testSetup
    static void testSetup() {
        Test.startTest();
        TestDataFactoryUser.generateUserQUTESB();
        Test.stopTest();
    }

    @isTest
    static void fastFieldUpdateAndValidationTest() {
        System.runAs(TestDataFactoryUser.selectUserQUTESB) {
            List<Engagement_List_Configuration__c> configs = new List<Engagement_List_Configuration__c>();
            Engagement_List_Configuration__c config = new Engagement_List_Configuration__c();
            config.Name = 'ELConfig Test';
            config.Engagement_List_Configuration_Status__c = 'Active';
            config.Start_Date__c = Date.today().addDays(-1);
            config.End_Date__c = Date.today().addDays(1);
            configs.add(config);
            EngagementListConfigurationsDAO.newInstance()
                .insertRecords(configs, true, AccessLevel.SYSTEM_MODE);

            Engagement_List_Criteria__c criteria = new Engagement_List_Criteria__c(
                Engagement_List_Criteria_Title__c = 'Test',
                Citizenship_Status__c = 'International',
                Preview_Status__c = 'Completed',
                Engagement_List_Configuration__c = configs[0].Id
            );

            EngagementListCriteriasDAO.newInstance()
                .insertRecords(
                    new List<Engagement_List_Criteria__c>{ criteria },
                    true,
                    AccessLevel.SYSTEM_MODE
                );
            
            Engagement_List_Criteria__c insertedCriteria = EngagementListCriteriasDAO.newInstance()
            .getEntryCriteriaById(criteria.Id, AccessLevel.SYSTEM_MODE);

            Attachment csvAttachment = new Attachment(
                ParentId = criteria.Id,
                Name = insertedCriteria.Name + '_Preview_Result.csv',
                Body = Blob.valueOf('test'),
                ContentType = 'text/csv'
            );

            //Create attachment records related to the criteria
            AttachmentsDAO.newInstance()
                .insertRecords(new List<Attachment>{ csvAttachment }, true, AccessLevel.USER_MODE);

            criteria.Preview_Result_Attachment_Id__c = csvAttachment.Id;
            criteria.Citizenship_Status__c = 'Domestic';

            Test.startTest();
            EngagementListCriteriasDAO.newInstance()
                .updateRecords(
                    new List<Engagement_List_Criteria__c>{ criteria },
                    true,
                    AccessLevel.SYSTEM_MODE
                );
            Test.stopTest();

            // Assert that when criteria field is updated
            // Preview_Result_Attachment_Id__c is nullfied
            // Preview_Status__c is Not Generated
            Engagement_List_Criteria__c updateCriteria = EngagementListCriteriasDAO.newInstance()
                .getEntryCriteriaById(criteria.Id, AccessLevel.SYSTEM_MODE);

            System.assertEquals(
                'Domestic',
                updateCriteria.Citizenship_Status__c,
                'Citizenship status should be updated'
            );
            System.assertEquals(
                null,
                updateCriteria.Preview_Result_Attachment_Id__c,
                'Preview_Result_Attachment_Id__c status should be updated'
            );
            System.assertEquals(
                'Not Generated',
                updateCriteria.Preview_Status__c,
                'Preview_Status__c status should be updated'
            );
            // assert that attachments are deleted
            System.assert(
                AttachmentsDAO.newInstance()
                    .findAttachmentsByNames(
                        new Set<String>{ csvAttachment.Name },
                        AccessLevel.SYSTEM_MODE
                    )
                    .isEmpty(),
                'Attachments should be deleted'
            );
        }
    }
}