src/core-crm/objects/Case/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <description>The classification of the case based on business processes.</description>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic Future Student Enquiry</fullName>
            </value>
            <value>
                <fullName>International Future Student Enquiry</fullName>
            </value>
            <value>
                <fullName>Student Success - Retention</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>The type of Case being tracked.</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Student_LifeCycle_Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acceptance process</fullName>
            </value>
            <value>
                <fullName>Agent matters</fullName>
            </value>
            <value>
                <fullName>Application process</fullName>
            </value>
            <value>
                <fullName>Application status</fullName>
            </value>
            <value>
                <fullName>Change application</fullName>
            </value>
            <value>
                <fullName>Compliance documentation</fullName>
            </value>
            <value>
                <fullName>Course information</fullName>
            </value>
            <value>
                <fullName>Enrolment</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>Orientation and onboarding</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Progression</fullName>
            </value>
            <value>
                <fullName>Scholarships</fullName>
            </value>
            <value>
                <fullName>Student life</fullName>
            </value>
            <value>
                <fullName>Technical issues</fullName>
            </value>
            <value>
                <fullName>Why QUT</fullName>
            </value>
            <value>
                <fullName>School Code of Conduct</fullName>
                <isActive>false</isActive>
                <label>School Code of Conduct</label>
            </value>
            <value>
                <fullName>School Violation</fullName>
                <isActive>false</isActive>
                <label>School Violation</label>
            </value>
            <value>
                <fullName>State Offense</fullName>
                <isActive>false</isActive>
                <label>State Offense</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Case/fields/Initial_Communication_Status__c.field-meta.xml
<CustomField>
    <fullName>Initial_Communication_Status__c</fullName>
    <description>The state of the initial communication sent on case creation</description>
    <label>Initial Communication Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Case/fields/Qualtrics_Survey__c.field-meta.xml
<CustomField>
    <fullName>Qualtrics_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to a related Qualtrics Survey where applicable</description>
    <label>Qualtrics Survey</label>
    <referenceTo>Qualtrics_Survey__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Communication_Processed__e/Communication_Processed__e.object-meta.xml
<CustomObject>
    <description>Event published when the Communication Queue finish processing a Communication Queue record and the Status is Sent or Failed</description>
    <label>Communication Processed</label>
    <pluralLabel>Communications Processed</pluralLabel>
</CustomObject>

src/core-crm/objects/Communication_Processed__e/fields/Business_Process__c.field-meta.xml
<CustomField>
    <fullName>Business_Process__c</fullName>
    <description>Business Process of the corresponding Communication Queue record generating the event</description>
    <label>Business Process</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Communication_Processed__e/fields/Success__c.field-meta.xml
<CustomField>
    <fullName>Success__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Was the Communication Queue record processed successfully</description>
    <label>Success</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Communication_Processed__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of the corresponding Communication Queue record generating the event</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Communication_Processed__e/fields/What_Id__c.field-meta.xml
<CustomField>
    <fullName>What_Id__c</fullName>
    <description>What Id of the corresponding Communication Queue record generating the event</description>
    <label>What Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Qualtrics_Survey__c/Qualtrics_Survey__c.object-meta.xml
<CustomObject>
    <description>Contains an instance of a Qualtrics survey.</description>
    <label>Qualtrics Survey</label>
    <nameField>
        <displayFormat>QS-{000000}</displayFormat>
        <label>Qualtrics Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualtrics Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Qualtrics_Survey__c/fields/Survey_Status__c.field-meta.xml
<CustomField>
    <fullName>Survey_Status__c</fullName>
    <description>Driven from email send and or presence of Completed Survey URL</description>
    <label>Survey Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/classes/OutreachCommunicationProcessedHandTest.cls
/**
 * @description Test class for OutreachCommunicationProcessedHandler
 * 
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | mark.j.mahilum                 | May 21, 2024          | DEPP-8823              | Created file                 |
 */
@isTest
public class OutreachCommunicationProcessedHandTest {
    
	private static final String EMAIL = 'testmail@mail.test';
    
    @testSetup
    static void setupTestData() {
        TestDataFactoryUser.generateUserSystemAdministrator();
    }

    @isTest
    static void testAfterInsertCaseCommunicationStatusSent() {
        System.runAs(TestDataFactoryUser.selectUserSystemAdministrator) {
            // Create test Cases
            List<Contact> contactList = TestDataFactory.createTestContactRecords(1, '');          
            for(Integer i = 0; i < contactList.size(); i++){
                contactList[i].RecordTypeId = ContactsDAO.PERSON_RECORDTYPE_ID;
                contactList[i].Email = 'work' + i + EMAIL;
            }         
            ContactsDAO.newInstance().insertRecords(contactList, false, AccessLevel.USER_MODE);          

            List<Qualtrics_Survey__c> qualtricsSurveyList = TestDataFactory.createQualtricsSurveyRecord(1);
            QualtricsSurveysDAO.newInstance().insertRecords(qualtricsSurveyList, false, AccessLevel.SYSTEM_MODE);

            List<Case> caseList = TestDataFactory.createTestCaseRecords(contactList.size(),null,contactList);
            Id studentRetentionId = GroupsDAO.newInstance().getQueueByName(GroupsDAO.STUDENT_RETENTION_QUEUE);
            for(Case caseRec: caseList) {
                caseRec.Case_Type__c = CasesDAO.CASE_TYPE_STUDENT_SUCCESS_RETENTION;
                caseRec.Origin = CommunicationQueuesDAO.TYPE_EMAIL;
                caseRec.Priority = 'Low';
                caseRec.Category__c = 'Student life';
                caseRec.Status = 'Created';
                caseRec.SuppliedEmail = 'test333111CaseRec@mailinator.com';
                caseRec.recordTypeId = CasesDAO.OUTREACH_RECTYPE_ID;
                caseRec.OwnerId = studentRetentionId;
                caseRec.Qualtrics_Survey__c = qualtricsSurveyList[0].Id;
            }
            CasesDAO.newInstance().insertRecords(caseList, false, AccessLevel.SYSTEM_MODE);  
            
            // Create test outeach Communication_Processed__e events
            List<Communication_Processed__e> testEvents = new List<Communication_Processed__e>();
            for (Case c : caseList) {
                testEvents.add(new Communication_Processed__e(
                    What_Id__c = c.Id,
                    Business_Process__c = CommunicationQueuesDAO.BUSINESS_PROCESS_OUTREACH,
                    Type__c = CommunicationQueuesDAO.TYPE_EMAIL,
                    Success__c = true
                ));
            }
            
            // Publish the platform events
            Test.startTest();
            EventBus.publish(testEvents);
            Test.stopTest();
            
            // Retrieve the test Cases to use their Ids
            List<Case> testCases = [SELECT Id, Initial_Communication_Status__c, Qualtrics_Survey__c FROM Case WHERE RecordTypeId =: CasesDAO.OUTREACH_RECTYPE_ID];
            Set<Id> qualtricsSurveyIds = new Set<Id>();
            for (Case c : testCases) {
                System.assertEquals(CasesDAO.INITIAL_COMMUNICATION_STATUS_SENT, c.Initial_Communication_Status__c, 'Initial Communication Status should be "Sent"');
                qualtricsSurveyIds.add(c.Qualtrics_Survey__c);
            }

            List<Qualtrics_Survey__c> updatedQualtricSurvey = [SELECT Survey_Status__c FROM Qualtrics_Survey__c WHERE Id IN : qualtricsSurveyIds];
            for(Qualtrics_Survey__c qualtricSurvey : updatedQualtricSurvey){
                System.Assert.areEqual(QualtricsSurveysDAO.SURVEY_STATUS_SENT, qualtricSurvey.Survey_Status__c, 'Qualtric Survey Status should be "Sent"');
            }
        }
    }
    
    @isTest
    static void testAfterInsertCaseCommunicationStatusFailed() {
        System.runAs(TestDataFactoryUser.selectUserSystemAdministrator) {
            // Create test Cases
            List<Contact> contactList = TestDataFactory.createTestContactRecords(3, '');          
            for(Integer i = 0; i < contactList.size(); i++){
                contactList[i].RecordTypeId = ContactsDAO.PERSON_RECORDTYPE_ID;
                contactList[i].Email = 'work' + i + EMAIL;
            }         
            ContactsDAO.newInstance().insertRecords(contactList, false, AccessLevel.USER_MODE);          
            List<EmailTemplate> emailTemplates = EmailTemplatesDAO.newInstance().getEmailTemplatesByNameSet(new Set<String>{'Test Email Temp'}, AccessLevel.USER_MODE);
            List<Case> caseList = TestDataFactory.createTestCaseRecords(contactList.size(),null,contactList);
            for(Case caseRec: caseList) {
                caseRec.Case_Type__c = CasesDAO.CASE_TYPE_STUDENT_SUCCESS_RETENTION;
                caseRec.Origin = CommunicationQueuesDAO.TYPE_EMAIL;
                caseRec.Priority = 'Low';
                caseRec.Category__c = 'Student life';
                caseRec.Status = 'Created';
                caseRec.Initial_Communication_Status__c = CasesDAO.INITIAL_COMMUNICATION_STATUS_PENDING;
                caseRec.SuppliedEmail = 'test333111CaseRec@mailinator.com';
                caseRec.recordTypeId = CasesDAO.OUTREACH_RECTYPE_ID;
            }
            CasesDAO.newInstance().insertRecords(caseList, false, AccessLevel.SYSTEM_MODE);  
            
            // Create test Communication_Processed__e events
            List<Communication_Processed__e> testEvents = new List<Communication_Processed__e>();
            for (Case c : caseList) {
                testEvents.add(new Communication_Processed__e(
                    What_Id__c = c.Id,
                    Business_Process__c = CommunicationQueuesDAO.BUSINESS_PROCESS_OUTREACH,
                    Type__c = CommunicationQueuesDAO.TYPE_EMAIL,
                    Success__c = false
                ));
            }
            
            // Publish the platform events
            Test.startTest();
            EventBus.publish(testEvents);
            Test.stopTest();
            
            // Retrieve the test Cases to use their Ids
            List<Case> testCases = [SELECT Id, Initial_Communication_Status__c FROM Case WHERE RecordTypeId =: CasesDAO.OUTREACH_RECTYPE_ID];
            for (Case c : testCases) {
                System.assertEquals(CasesDAO.INITIAL_COMMUNICATION_STATUS_PENDING, c.Initial_Communication_Status__c, 'Initial Communication Status should be "Pending"');
            }
        }
    }
}