src/core-crm/objects/Case/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <description>The classification of the case based on business processes.</description>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic Future Student Enquiry</fullName>
            </value>
            <value>
                <fullName>International Future Student Enquiry</fullName>
            </value>
            <value>
                <fullName>Student Success - Retention</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>The type of Case being tracked.</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Student_LifeCycle_Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acceptance process</fullName>
            </value>
            <value>
                <fullName>Agent matters</fullName>
            </value>
            <value>
                <fullName>Application process</fullName>
            </value>
            <value>
                <fullName>Application status</fullName>
            </value>
            <value>
                <fullName>Change application</fullName>
            </value>
            <value>
                <fullName>Compliance documentation</fullName>
            </value>
            <value>
                <fullName>Course information</fullName>
            </value>
            <value>
                <fullName>Enrolment</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>Orientation and onboarding</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Progression</fullName>
            </value>
            <value>
                <fullName>Scholarships</fullName>
            </value>
            <value>
                <fullName>Student life</fullName>
            </value>
            <value>
                <fullName>Technical issues</fullName>
            </value>
            <value>
                <fullName>Why QUT</fullName>
            </value>
            <value>
                <fullName>School Code of Conduct</fullName>
                <isActive>false</isActive>
                <label>School Code of Conduct</label>
            </value>
            <value>
                <fullName>School Violation</fullName>
                <isActive>false</isActive>
                <label>School Violation</label>
            </value>
            <value>
                <fullName>State Offense</fullName>
                <isActive>false</isActive>
                <label>State Offense</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/classes/InboundEnquiryCaseSetCaseType_FlowTest.cls
/**
 * @description Test Class for Inbound Enquiry Case Set Case Type Flow
 *
 * @see ../flows/Inbound_Enquiry_Case_Set_Case_Type
 *
 * @author Accenture
 *
 * @history
 *    | Developer                 | Date                  | JIRA         | Change Summary                              |
      |---------------------------|-----------------------|--------------|---------------------------------------------|
      | eccarius.munoz            | April 22, 2024        | DEPP-8542    | Created file                                |
      |                           |                       |              |                                             |
*/
@isTest
public with sharing class InboundEnquiryCaseSetCaseType_FlowTest {
    
    @testSetup
    static void makeData(){
        TestDataFactoryUser.generateUserFutureStudentAgentInternational();
        TestDataFactoryUser.generateUserFutureStudentAgentDomestic();
    }
    
    @IsTest
    static void domesticCaseTypeTest(){
        System.runAs(TestDataFactoryUser.selectUserFutureStudentAgentDomestic) {
            
            List<Group> groupList = [SELECT Id, Name FROM Group WHERE  Type = 'Queue' and Name = 'Future Student Domestic Queue'];
            List<Case> domesticCases = TestDataFactory.createTestCaseRecords(CasesDAO.INBOUND_ENQUIRY_RECTYPE_ID, 'Test Domestic Case', 1);           
            List<Case> caseList = new List<Case>();
            caseList.addAll(domesticCases);
            
            for(Case c : caseList){
                c.Origin = 'Email';
                c.Priority = 'Low';
                c.Category__c = 'Student life';
                c.Status = 'Created';
                c.SuppliedEmail = 'test333111CaseRec@mailinator.com';
                c.OwnerId = groupList[0].Id;
            }

            Test.startTest();
            CasesDAO.newInstance().insertRecords(caseList, false, AccessLevel.SYSTEM_MODE);  
            Test.stopTest();

            List<Case> caseListWithCaseType = CasesDAO.newInstance().getCasesByIds(new Set<Id>{caseList[0].Id}, AccessLevel.SYSTEM_MODE);
            System.assertEquals(CasesDAO.CASE_TYPE_DOMESTIC, caseListWithCaseType[0].Case_Type__c,'Case Type must be Domestic Future Student Enquiry.');
        }
    }

    @IsTest
    static void internationalCaseTypeTest(){
        System.runAs(TestDataFactoryUser.selectUserFutureStudentAgentInternational) {
            
            List<Group> groupList = [SELECT Id, Name FROM Group WHERE  Type = 'Queue' and Name = 'Future Student International Queue'];
            List<Case> internationalCases = TestDataFactory.createTestCaseRecords(CasesDAO.INBOUND_ENQUIRY_RECTYPE_ID, 'Test International Case', 1);           
            List<Case> caseList = new List<Case>();
            caseList.addAll(internationalCases);
            
            for(Case c : caseList){
                c.Origin = 'Email';
                c.Priority = 'Low';
                c.Category__c = 'Student life';
                c.Status = 'Created';
                c.SuppliedEmail = 'test333111CaseRec@mailinator.com';
                c.OwnerId = groupList[0].Id;
            }

            Test.startTest();
            CasesDAO.newInstance().insertRecords(caseList, false, AccessLevel.SYSTEM_MODE);  
            Test.stopTest();
            
            List<Case> caseListWithCaseType = CasesDAO.newInstance().getCasesByIds(new Set<Id>{caseList[0].Id}, AccessLevel.SYSTEM_MODE);
            System.assertEquals(CasesDAO.CASE_TYPE_INTERNATIONAL, caseListWithCaseType[0].Case_Type__c,'Case Type must be International Future Student Enquiry.');
        }
    }
}