src/core-crm/objects/Case/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <description>The classification of the case based on business processes.</description>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic Future Student Enquiry</fullName>
            </value>
            <value>
                <fullName>International Future Student Enquiry</fullName>
            </value>
            <value>
                <fullName>Student Success - Retention</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Case/fields/Engagement_List_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Engagement_List_Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The related engagement list configuration that lead to the creation of this case.</description>
    <label>Engagement List Configuration</label>
    <referenceTo>Engagement_List_Configuration__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Case/fields/Qualtrics_Survey__c.field-meta.xml
<CustomField>
    <fullName>Qualtrics_Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to a related Qualtrics Survey where applicable</description>
    <label>Qualtrics Survey</label>
    <referenceTo>Qualtrics_Survey__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Engagement_List_Configuration__c/Engagement_List_Configuration__c.object-meta.xml
<CustomObject>
    <description>Contains the details of a call/outreach campaign.</description>
    <label>Engagement List Configuration</label>
    <nameField>
        <label>Engagement List Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement List Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Engagement_List_Configuration__c/fields/Qualtrics_Instrument_ID__c.field-meta.xml
<CustomField>
    <fullName>Qualtrics_Instrument_ID__c</fullName>
    <description>An external identifier of the Qualtrics instrument (survey ID) to be used by integration</description>
    <label>Qualtrics Instrument ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Engagement_List_Configuration__c/fields/Qualtrics_Instrument_Name__c.field-meta.xml
<CustomField>
    <fullName>Qualtrics_Instrument_Name__c</fullName>
    <description>The name of the Qualtrics instrument to be included with engagement list configuration for easy reference</description>
    <label>Instrument</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Qualtrics_Survey__c/Qualtrics_Survey__c.object-meta.xml
<CustomObject>
    <description>Contains an instance of a Qualtrics survey.</description>
    <label>Qualtrics Survey</label>
    <nameField>
        <displayFormat>QS-{000000}</displayFormat>
        <label>Qualtrics Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Qualtrics Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/classes/OutreachCasePostCreationQueuableTest.cls
/**
 * @description OutreachCasePostCreationQueuable testclass.
 * @see ../class/OutreachCasePostCreationQueuable
 *
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary                                        |
 *    |--------------------------------|-----------------------|------------------------|-------------------------------------------------------|
 *    | arsenio.jr.dayrit              | May 22, 2024          | DEPP-8821              | Created file                                          |
 */
@isTest
public class OutreachCasePostCreationQueuableTest {

    @testSetup
    static void testSetup() {
        TestDataFactoryUser.generateUserStudentSuccessOutreachManager();
    }

    @isTest
    private static void testExecute() {
        System.runAs(TestDataFactoryUser.selectUserStudentSuccessOutreachManager) {
            List<Engagement_List_Configuration__c> elcList = new List<Engagement_List_Configuration__c>();
            Engagement_List_Configuration__c elcRec = new Engagement_List_Configuration__c();
            elcRec.Qualtrics_Instrument_Id__c = 'test';
            elcRec.Qualtrics_Instrument_Name__c = 'test';
            elcList.add(elcRec);
            EngagementListConfigurationsDAO.newInstance().insertRecords(elcList, true, AccessLevel.USER_MODE);

            List<Case> cases = new List<Case>();
            Case caseRec = new Case();
            caseRec.RecordTypeId = CasesDAO.OUTREACH_RECTYPE_ID;
            caseRec.Case_Type__c = CasesDAO.CASE_TYPE_STUDENT_SUCCESS_RETENTION;
            caseRec.Engagement_List_Configuration__c = elcRec.Id;
            cases.add(caseRec);
            CasesDAO.newInstance().insertRecords(cases, true, AccessLevel.USER_MODE);

            List<Case> caseList = CasesDAO.newInstance().getCasesByIds(new Set<Id>{cases[0].Id},AccessLevel.SYSTEM_MODE);
            QualtricsSurveyService.doQueueableJob = false;
            // Enqueue the queueable class
            Test.startTest();
            System.enqueueJob(new OutreachCasePostCreationQueuable(caseList));
            Test.stopTest();
            List<Case> caseListUpdated = CasesDAO.newInstance().getCasesByIds(new Set<Id>{cases[0].Id},AccessLevel.SYSTEM_MODE);
            System.assert(!String.isBlank(caseListUpdated[0].Qualtrics_Survey__c), ' No Qualtrics Survey record created.');
        }
    }
}