src/core-crm/objects/Case/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <description>The classification of the case based on business processes.</description>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic Future Student Enquiry</fullName>
            </value>
            <value>
                <fullName>International Future Student Enquiry</fullName>
            </value>
            <value>
                <fullName>Student Success - Retention</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>The type of Case being tracked.</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Student_LifeCycle_Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acceptance process</fullName>
            </value>
            <value>
                <fullName>Agent matters</fullName>
            </value>
            <value>
                <fullName>Application process</fullName>
            </value>
            <value>
                <fullName>Application status</fullName>
            </value>
            <value>
                <fullName>Change application</fullName>
            </value>
            <value>
                <fullName>Compliance documentation</fullName>
            </value>
            <value>
                <fullName>Course information</fullName>
            </value>
            <value>
                <fullName>Enrolment</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>Orientation and onboarding</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Progression</fullName>
            </value>
            <value>
                <fullName>Scholarships</fullName>
            </value>
            <value>
                <fullName>Student life</fullName>
            </value>
            <value>
                <fullName>Technical issues</fullName>
            </value>
            <value>
                <fullName>Why QUT</fullName>
            </value>
            <value>
                <fullName>School Code of Conduct</fullName>
                <isActive>false</isActive>
                <label>School Code of Conduct</label>
            </value>
            <value>
                <fullName>School Violation</fullName>
                <isActive>false</isActive>
                <label>School Violation</label>
            </value>
            <value>
                <fullName>State Offense</fullName>
                <isActive>false</isActive>
                <label>State Offense</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/classes/CaseEmailInternationalAck_FlowTest.cls
/**
 * @description Test Class for Case Email International Ack  Flow
 *
 * @see ../flows/Case_Email_International_Ack
 *
 * @author Accenture
 *
 * @history
 *    | Developer                 | Date                  | JIRA         | Change Summary                              |
      |---------------------------|-----------------------|--------------|---------------------------------------------|
      | eccarius.munoz            | March 19, 2024        | DEPP-8297    | Created file                                |
      |                           |                       |              |                                             |
*/
@isTest
public with sharing class CaseEmailInternationalAck_FlowTest {
    private static final String STR_EMAIL_TEMPLATE = 'Test Email Template';
    
    @testSetup
    static void makeData(){
        TestDataFactoryUser.generateUserFutureStudentAgentInternational();
    }
    
    @IsTest
    static void caseOriginWebsiteInternationalCaseTest(){
        System.runAs(TestDataFactoryUser.selectUserFutureStudentAgentInternational) {
            EmailTemplate template = TestDataFactory.createTestEmailTemplateRecords(1,new Map<String,String>{
                STR_EMAIL_TEMPLATE => 'FS International Email Template Test'
            }).iterator().next();
            insert template;
            
            List<Case> internationalCases = TestDataFactory.createTestCaseRecords(CasesDAO.INBOUND_ENQUIRY_RECTYPE_ID, 'Test International Case', 1);           
            List<Case> caseList = new List<Case>();
            caseList.addAll(internationalCases);
            
            for(Case c : caseList){
                c.Origin = 'Website';
                c.Priority = 'Low';
                c.Category__c = 'Student life';
                c.Status = 'Created';
                c.SuppliedEmail = 'test333111CaseRec@mailinator.com';
                c.Case_Type__c = CasesDAO.CASE_TYPE_INTERNATIONAL;
            }
            
            CasesDAO.newInstance().insertRecords(caseList, false, AccessLevel.SYSTEM_MODE);    
            
            FlowEmailMergeField mergeFields = new FlowEmailMergeField();
            mergeFields.mergeField = '{{{Case.SuppliedMail}}}';
            mergeFields.mergeFieldValue = caseList[0].SuppliedEmail;
            
            CaseEmailFlowHelper.EmailParameters emailParams = new CaseEmailFlowHelper.EmailParameters();
            emailParams.recipientEmailAddresses= new List<String>{'test@test.com.invalid'};
            emailParams.emailTemplateDeveloperName = template.DeveloperName;
            emailParams.mergeFields = new List<FlowEmailMergeField>{mergeFields};
            emailParams.emailSubject = '';
            emailParams.orgWideEmailAddressId = '';
            emailParams.recordId = caseList[0].Id;

            Test.startTest();
            CaseEmailFlowHelper.sendCustomEmail(new List<CaseEmailFlowHelper.EmailParameters>{emailParams});
            System.assertEquals(1, Limits.getEmailInvocations(),'Number of email invocations not as expected');
            Test.stopTest();

            
        }
    }
}