src/core-crm/objects/Case/fields/Lead_Score_Reset__c.field-meta.xml
<CustomField>
    <fullName>Lead_Score_Reset__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lead Score Reset</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Contact/fields/Lead_Score_Detail__c.field-meta.xml
<CustomField>
    <fullName>Lead_Score_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The breakdown of lead scoring by category aggregates.</description>
    <label>Lead Score Detail</label>
    <referenceTo>Lead_Score_Detail__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/et4ae5__IndividualEmailResult__c/et4ae5__IndividualEmailResult__c.object-meta.xml
<CustomObject>
    <label>Individual Email Result</label>
    <nameField>
        <label>Email Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individual Email Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/et4ae5__IndividualEmailResult__c/fields/Lead_Score_Reset__c.field-meta.xml
<CustomField>
    <fullName>Lead_Score_Reset__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lead Score Reset</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/hed__Program_Enrollment__c/hed__Program_Enrollment__c.object-meta.xml
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Lead/fields/Lead_Score_Detail__c.field-meta.xml
<CustomField>
    <fullName>Lead_Score_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The breakdown of lead scoring by category aggregates.</description>
    <label>Lead Score Detail</label>
    <referenceTo>Lead_Score_Detail__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Lead_Score_Detail__c/Lead_Score_Detail__c.object-meta.xml
<CustomObject>
    <label>Lead Score Detail</label>
    <nameField>
        <displayFormat>LSD-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Score Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Lead_Score_Detail__c/fields/Country_Tier__c.field-meta.xml
<CustomField>
    <fullName>Country_Tier__c</fullName>
    <description>The priority tiering applied by QUT to student intake</description>
    <label>Country Tier</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Lead_Score_Detail__c/fields/Course_Level__c.field-meta.xml
<CustomField>
    <fullName>Course_Level__c</fullName>
    <description>The component score attributed due to populating study level for study interest for marketing preferences</description>
    <label>Course Level</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Lead_Score_Detail__c/fields/Download__c.field-meta.xml
<CustomField>
    <fullName>Download__c</fullName>
    <description>The component score attributed due to course Pdf downloads</description>
    <label>Downloaded PDF</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Lead_Score_Detail__c/fields/Email_Interaction__c.field-meta.xml
<CustomField>
    <fullName>Email_Interaction__c</fullName>
    <description>The component score attributed due to clicking on a marketing email link</description>
    <label>Email Interaction</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Lead_Score_Detail__c/fields/Enquiries__c.field-meta.xml
<CustomField>
    <fullName>Enquiries__c</fullName>
    <description>The component score attributed due to enquiries</description>
    <label>Enquiries</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Lead_Score_Detail__c/fields/Event_Registration_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration_Attendance__c</fullName>
    <description>The component score attributed toward Open day registration</description>
    <label>Event Registration and Attendance</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Lead_Score_Detail__c/fields/Funding__c.field-meta.xml
<CustomField>
    <fullName>Funding__c</fullName>
    <description>The component score attributed due company funding option being selected</description>
    <label>Funding</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Lead_Score_Detail__c/fields/Interested_In_Double_Degrees__c.field-meta.xml
<CustomField>
    <fullName>Interested_In_Double_Degrees__c</fullName>
    <description>The component score attributed due to declaration on of interest in double degrees</description>
    <label>Interested In Double Degrees</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Lead_Score_Detail__c/fields/Interested_In_English_Pathway_Programs__c.field-meta.xml
<CustomField>
    <fullName>Interested_In_English_Pathway_Programs__c</fullName>
    <description>The component score attributed due to declaration on of interest in English pathway programs</description>
    <label>Interested in English Pathway Programs</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Lead_Score_Detail__c/fields/Manual_Assessment__c.field-meta.xml
<CustomField>
    <fullName>Manual_Assessment__c</fullName>
    <description>The applied manual override score component</description>
    <label>Manual Assessment</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Lead_Score_Detail__c/fields/Marketing_Consent__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Consent__c</fullName>
    <description>The component score attributed due to giving marketing consent</description>
    <label>Marketing Consent</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Lead_Score_Detail__c/fields/Match_My_Skills__c.field-meta.xml
<CustomField>
    <fullName>Match_My_Skills__c</fullName>
    <description>The component score attributed due to completing Match My Skills</description>
    <label>Match My Skills</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Lead_Score_Detail__c/fields/Preferred_Intake__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Intake__c</fullName>
    <description>The component score attributed due to populating expected intake year.</description>
    <label>Preferred Intake</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Lead_Score_Detail__c/fields/Primary_BSA__c.field-meta.xml
<CustomField>
    <fullName>Primary_BSA__c</fullName>
    <description>The component score attributed due to populating BSA for study interest for marketing preferences</description>
    <label>Primary BSA</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Lead_Score_Detail__c/fields/Primary_NSA__c.field-meta.xml
<CustomField>
    <fullName>Primary_NSA__c</fullName>
    <description>The component Score attributed due to populating NSA for study interest for marketing preferences</description>
    <label>Primary NSA</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Lead_Score_Detail__c/fields/Program_Engagement__c.field-meta.xml
<CustomField>
    <fullName>Program_Engagement__c</fullName>
    <description>The component score attributed due to participation on university or faculty programs such as

START QUT, STEM Camp</description>
    <label>Program Engagement</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Lead_Score_Detail__c/fields/Residence__c.field-meta.xml
<CustomField>
    <fullName>Residence__c</fullName>
    <description>The score allocation due to country of residence</description>
    <label>Residence</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Marketing_Interaction__c/Marketing_Interaction__c.object-meta.xml
<CustomObject>
    <label>Marketing Interaction</label>
    <nameField>
        <displayFormat>MI - {000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Marketing_Interaction__c/fields/Lead_Score_Reset__c.field-meta.xml
<CustomField>
    <fullName>Lead_Score_Reset__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lead Score Reset</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/classes/LeadScoreResetService.cls
/**
 * @description holds the common methods for reseting a lead score
 * @see ProgramEnrollmentTriggerHelper and ApplicationTriggerHelper
 *
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | roy.nino.s.regala		       | November 03, 2023     | DEPP-7145              | Created file                 |
 */

public with sharing class LeadScoreResetService {
    
    public static void updateLeadScoreResetForMktgInt(Set<Id> contactLeadIdSet) {
        List<Marketing_Interaction__c> mktIntListToUpdate = new List<Marketing_Interaction__c>();
        if (!contactLeadIdSet.isEmpty()) {
            List<Marketing_Interaction__c> mktInList = MarketingInteractionsDAO.newInstance()
                .getMarketingInteractionsByContactOrLeadIds(
                    contactLeadIdSet,
                    AccessLevel.SYSTEM_MODE
                );
            for (Marketing_Interaction__c mktInt : mktInList) {
                mktInt.Lead_Score_Reset__c = true;
                mktIntListToUpdate.add(mktInt);
            }
        }

        if (!mktIntListToUpdate.isEmpty()) {
            MarketingInteractionsDAO.newInstance()
                .updateRecords(mktIntListToUpdate, false, AccessLevel.SYSTEM_MODE);
        }
    }

    public static void updateLeadScoreResetForIndivEmail(Set<Id> contactLeadIdSet) {
        List<et4ae5__IndividualEmailResult__c> indivEmailListToUpdate = new List<et4ae5__IndividualEmailResult__c>();
        if (!contactLeadIdSet.isEmpty()) {
            List<et4ae5__IndividualEmailResult__c> indivEmailList = IndividualEmailResultsDAO.newInstance()
                .getIndivEmailResultsByContactOrLeadIds(contactLeadIdSet, AccessLevel.SYSTEM_MODE);
            for (et4ae5__IndividualEmailResult__c indivEmail : indivEmailList) {
                indivEmail.Lead_Score_Reset__c = true;
                indivEmailListToUpdate.add(indivEmail);
            }
        }

        if (!indivEmailListToUpdate.isEmpty()) {
            IndividualEmailResultsDAO.newInstance()
                .updateRecords(indivEmailListToUpdate, false, AccessLevel.SYSTEM_MODE);
        }
    }

    public static void updateLeadScoreResetForCase(Set<Id> contactLeadIdSet) {
        List<Case> caseListToUpdate = new List<Case>();
        if (!contactLeadIdSet.isEmpty()) {
            List<Case> caseList = CasesDAO.newInstance()
                .getCasesByContactOrLeadIds(contactLeadIdSet, AccessLevel.SYSTEM_MODE);
            for (Case caseRec : caseList) {
                caseRec.Lead_Score_Reset__c = true;
                caseListToUpdate.add(caseRec);
            }
        }
        if (!caseListToUpdate.isEmpty()) {
            CasesDAO.newInstance().updateRecords(caseListToUpdate, false, AccessLevel.SYSTEM_MODE);
        }
    }

    public static void updateLeadScoreResetForProgEng(Set<Id> contactLeadIdSet) {
        List<hed__Program_Enrollment__c> progEngListToUpdate = new List<hed__Program_Enrollment__c>();
        if (!contactLeadIdSet.isEmpty()) {
            List<hed__Program_Enrollment__c> progEngList = ProgramEnrollmentsDAO.newInstance()
                .getAllProgramEnrollmentsByContactId(contactLeadIdSet, AccessLevel.SYSTEM_MODE);
            for (hed__Program_Enrollment__c progEng : progEngList) {
                progEng.Lead_Score_Reset__c = true;
                progEngListToUpdate.add(progEng);
            }
        }

        if (!progEngListToUpdate.isEmpty()) {
            ProgramEnrollmentsDAO.newInstance()
                .updateRecords(progEngListToUpdate, false, AccessLevel.SYSTEM_MODE);
        }
    }

    /**
     * Retrieves the lead score details by contact/lead and sets all categories to 0
     */
    public static List<Lead_Score_Detail__c> getLeadScoreDetailsToUpdate(Set<Id> contactLeadIdSet) {
        List<Lead_Score_Detail__c> leadScoreDetailsToUpdate = new List<Lead_Score_Detail__c>();
        if (!contactLeadIdSet.isEmpty()) {
            List<Lead_Score_Detail__c> leadScoreDetailsList = LeadScoreDetailsDAO.newInstance()
                .getLeadScoreDetailsByContactOrLeadId(contactLeadIdSet, AccessLevel.SYSTEM_MODE);
            for (Lead_Score_Detail__c detail : leadScoreDetailsList) {
                leadScoreDetailsToUpdate.add(
                    new Lead_Score_Detail__c(
                        Id = detail.Id,
                        Country_Tier__c = 0,
                        Course_Level__c = 0,
                        Download__c = 0,
                        Email_Interaction__c = 0,
                        Enquiries__c = 0,
                        Event_Registration_Attendance__c = 0,
                        Funding__c = 0,
                        Interested_In_Double_Degrees__c = 0,
                        Interested_In_English_Pathway_Programs__c = 0,
                        Manual_Assessment__c = 0,
                        Marketing_Consent__c = 0,
                        Match_My_Skills__c = 0,
                        Preferred_Intake__c = 0,
                        Primary_NSA__c = 0,
                        Primary_BSA__c = 0,
                        Program_Engagement__c = 0,
                        Residence__c = 0
                    )
                );
            }
        }

        return leadScoreDetailsToUpdate;
    }
}