src/core-crm/objects/Case/fields/My_Country_of_Citizenship__c.field-meta.xml
<CustomField>
    <fullName>My_Country_of_Citizenship__c</fullName>
    <description>The country of citizenship of the enquirer</description>
    <label>My Country of Citizenship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

src/core-crm/objects/Case/fields/My_Country_of_Residency__c.field-meta.xml
<CustomField>
    <fullName>My_Country_of_Residency__c</fullName>
    <description>The country the enquirer currently resides in</description>
    <label>My Country of Residency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

src/core-crm/objects/Case/recordTypes/International_Enquiry.recordType-meta.xml
<RecordType>
    <fullName>International_Enquiry</fullName>
    <active>true</active>
    <businessProcess>International Enquiry</businessProcess>
    <description>International Enquiry is used for the International Student Recruitment Team</description>
    <label>International Enquiry</label>
</RecordType>

src/core-crm/objects/Contact/fields/Marketing_Segmentation__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Segmentation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Preferences</label>
    <referenceTo>Marketing_Segmentation__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Lead/fields/Marketing_Segmentation__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Segmentation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Segmentation</label>
    <referenceTo>Marketing_Segmentation__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Marketing_Segmentation__c/Marketing_Segmentation__c.object-meta.xml
<CustomObject>
    <label>Marketing Segmentation</label>
    <nameField>
        <displayFormat>MS - {000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Segmentations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Marketing_Segmentation__c/fields/My_Country_Of_Citizenship__c.field-meta.xml
<CustomField>
    <fullName>My_Country_Of_Citizenship__c</fullName>
    <description>Profile Type = Myself

Indicates the country the international student is a citizen of.</description>
    <label>My Country Of Citizenship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

src/core-crm/objects/Marketing_Segmentation__c/fields/My_Country_Of_Residency__c.field-meta.xml
<CustomField>
    <fullName>My_Country_Of_Residency__c</fullName>
    <description>Profile Type = Myself

Indicates the country an international student is living in.</description>
    <label>My Country Of Residency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

src/core-crm/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Åland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas (the)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia (Plurinational State of)</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Indonesia</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

src/core-crm/classes/Update_Case_Priority_FlowTest.cls
/**
 * @description Test Class for Update Case Priority Flow
 *
 * @see ../flows/Update_Case_Priority_Flow
 *
 * @author Accenture
 *
 * @history
 *    | Developer                 | Date                  | JIRA         | Change Summary                              |
      |---------------------------|-----------------------|--------------|---------------------------------------------|
      | arsenio.jr.dayrit         | October 27, 2022      | DEPP-4250    | Created File                                |
      |                           |                       |              |                                             |
*/
@isTest
private class Update_Case_Priority_FlowTest{


    private static final Id recordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('International_Enquiry').getRecordTypeId();
   
    @TestSetup
    static void setupMethod(){
        Test.startTest();
        TestDataFactory.generateTestUsers();
        Test.stopTest();
        

    }

    @isTest
    private static void createCaseRecordPriotyByContactTest(){
        Test.startTest(); 
        System.runAs(TestDataFactory.getISRStudentEnquiriesCommunicationOfficer()){
            Database.DMLOptions dmo = new Database.DMLOptions();
            dmo.assignmentRuleHeader.useDefaultRule= true;

            Marketing_Segmentation__c marketingSeg = new Marketing_Segmentation__c();
            marketingSeg.My_Country_Of_Citizenship__c = 'Indonesia';
            marketingSeg.My_Country_Of_Residency__c = 'Australia';
            insert marketingSeg;

            List<Contact> cont = TestDataFactory.createTestContactRecords(1);
            for(Integer i = 0 ; i < cont.size() ; i++){
                cont[i].Marketing_Segmentation__c = marketingSeg.Id;

            }
            insert cont;

            
            List<Case> caseList = TestDataFactory.createTestCaseRecords(1, null, cont);
            for(Integer i = 0 ; i < caseList.size() ; i++){
                caseList[i].setOptions(dmo);
            }
           
            insert caseList;
    
            

            List<Case> resultList = [SELECT Id, Priority FROM Case];
            for(Case resultCase : resultList){
                System.assertEquals('High', resultCase.Priority, 'Priority not updated');
            }
            
        }
        Test.stopTest(); 
    }

    @isTest
    private static void createCaseRecordPriotyByLeadTest(){
        Test.startTest(); 
        System.runAs(TestDataFactory.getISRStudentEnquiriesCommunicationOfficer()){
            Database.DMLOptions dmo = new Database.DMLOptions();
            dmo.assignmentRuleHeader.useDefaultRule= true;

            Account acc = TestDataFactory.createTestAccount(true);

            Marketing_Segmentation__c marketingSeg = new Marketing_Segmentation__c();
            marketingSeg.My_Country_Of_Citizenship__c = 'Indonesia';
            marketingSeg.My_Country_Of_Residency__c = 'Australia';
            insert marketingSeg;

            List<Lead> lead = TestDataFactory.createTestLeadRecords(1);
            for(Integer i = 0 ; i < lead.size() ; i++){
                lead[i].Marketing_Segmentation__c = marketingSeg.Id;

            }
            insert lead;

            
            List<Case> caseList = TestDataFactory.createTestCaseRecords(1, lead, null);
            for(Integer i = 0 ; i < caseList.size() ; i++){
                caseList[i].setOptions(dmo);
            }
           
            insert caseList;
    
            

            List<Case> resultList = [SELECT Id, Priority FROM Case];
            for(Case resultCase : resultList){
                System.assertEquals('High', resultCase.Priority, 'Priority not updated');
            }
            
        }
        Test.stopTest(); 
    }
}