src/core-crm/objects/Case/fields/My_Primary_Study_Level__c.field-meta.xml
<CustomField>
    <fullName>My_Primary_Study_Level__c</fullName>
    <description>The Study Level the enquirer is enquiring about</description>
    <label>My Primary Study Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Undergraduate</fullName>
            </value>
            <value>
                <fullName>Postgraduate</fullName>
            </value>
            <value>
                <fullName>Higher Degree Research</fullName>
            </value>
            <value>
                <fullName>Short Courses and Professional Development</fullName>
            </value>
            <value>
                <fullName>Exchange and Study Abroad (1 or 2 Semesters Only)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Contact/fields/Consent_Source_Category__c.field-meta.xml
<CustomField>
    <fullName>Consent_Source_Category__c</fullName>
    <description>Identifies where the marketing person&apos;s consent came from. This should reuse the business values from the Lead Source Category</description>
    <label>Consent Source Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enquiry</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Lead Ad</fullName>
            </value>
            <value>
                <fullName>Web Form</fullName>
            </value>
            <value>
                <fullName>Outreach Activity</fullName>
            </value>
            <value>
                <fullName>Referral Partner</fullName>
            </value>
            <value>
                <fullName>Strategic Partner</fullName>
            </value>
            <value>
                <fullName>Study Application</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Contact/fields/Email_Opt_In_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Email_Opt_In_DateTime__c</fullName>
    <description>The date/time the marketing person opted in to receive marketing comms via Email.</description>
    <label>Email Opt In DateTime</label>
    <type>DateTime</type>
</CustomField>

src/core-crm/objects/Contact/fields/hed__SMS_Opt_Out__c.field-meta.xml
<CustomField>
    <fullName>hed__SMS_Opt_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether a person wants to receive SMS communications.</description>
    <inlineHelpText>Indicates whether a person wants to receive SMS communications.</inlineHelpText>
    <label>SMS Opt Out</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Contact/fields/Marketing_Segmentation__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Segmentation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Preferences</label>
    <referenceTo>Marketing_Segmentation__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/main/objects/Contact/fields/QUT_Learner_Email__c.field-meta.xml
<CustomField>
    <fullName>QUT_Learner_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>QUT Learner Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

src/core-crm/main/objects/Contact/fields/QUT_Staff_Email__c.field-meta.xml
<CustomField>
    <fullName>QUT_Staff_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>QUT Staff Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

src/core-crm/objects/Contact/fields/Registered_Email__c.field-meta.xml
<CustomField>
    <fullName>Registered_Email__c</fullName>
    <description>All automated email communications will be sent to this email address.</description>
    <label>Registered Email</label>
    <type>Email</type>
</CustomField>

src/core-crm/objects/Contact/fields/SMS_Opt_In_DateTime__c.field-meta.xml
<CustomField>
    <fullName>SMS_Opt_In_DateTime__c</fullName>
    <description>The date/time the marketing person opted in to receive marketing comms via SMS.</description>
    <label>SMS Opt In DateTime</label>
    <type>DateTime</type>
</CustomField>

src/core-crm/objects/Contact/fields/Work_Email__c.field-meta.xml
<CustomField>
    <fullName>Work_Email__c</fullName>
    <description>The work email for this person</description>
    <externalId>true</externalId>
    <inlineHelpText>This field captures the work email of the contact.</inlineHelpText>
    <label>Work Email</label>
    <type>Email</type>
</CustomField>

src/core-crm/objects/Contact/fields/Work_SMS_Opt_In_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Work_SMS_Opt_In_DateTime__c</fullName>
    <description>The date and time that the mobile opted in</description>
    <label>Work SMS Opt In DateTime</label>
    <type>DateTime</type>
</CustomField>

src/core-crm/objects/Contact/fields/Work_SMS_Opt_Out__c.field-meta.xml
<CustomField>
    <fullName>Work_SMS_Opt_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Marketing should not sms this mobile number</description>
    <label>Work SMS Opt Out</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Contact/fields/Work_SMS_Opt_Out_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Work_SMS_Opt_Out_DateTime__c</fullName>
    <description>The date and time that the mobile opted out</description>
    <label>Work SMS Opt Out DateTime</label>
    <type>DateTime</type>
</CustomField>

src/core-crm/objects/Lead/fields/Consent_Source_Category__c.field-meta.xml
<CustomField>
    <fullName>Consent_Source_Category__c</fullName>
    <description>Identifies where the marketing person&apos;s consent came from. This should reuse the business values from the Lead Source Category</description>
    <label>Consent Source Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enquiry</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Lead Ad</fullName>
            </value>
            <value>
                <fullName>Web Form</fullName>
            </value>
            <value>
                <fullName>Outreach Activity</fullName>
            </value>
            <value>
                <fullName>Referral Partner</fullName>
            </value>
            <value>
                <fullName>Strategic Partner</fullName>
            </value>
            <value>
                <fullName>Study Application</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Partner Sourced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Lead/fields/Email_Opt_Out_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Email_Opt_Out_DateTime__c</fullName>
    <description>The date/time the marketing person opted out of receiving marketing comms via Email.</description>
    <label>Email Opt Out DateTime</label>
    <type>DateTime</type>
</CustomField>

src/core-crm/objects/Lead/fields/hed__SMS_Opt_Out__c.field-meta.xml
<CustomField>
    <fullName>hed__SMS_Opt_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If selected, indicates the person doesn&apos;t want to receive SMS.</description>
    <label>SMS Opt Out</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Lead/fields/Marketing_Segmentation__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Segmentation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Segmentation</label>
    <referenceTo>Marketing_Segmentation__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Lead/fields/SMS_Opt_In_DateTime__c.field-meta.xml
<CustomField>
    <fullName>SMS_Opt_In_DateTime__c</fullName>
    <description>The date/time the marketing person opted in to receive marketing comms via SMS.</description>
    <label>SMS Opt In DateTime</label>
    <type>DateTime</type>
</CustomField>

src/core-crm/objects/Lead/fields/SMS_Opt_Out_DateTime__c.field-meta.xml
<CustomField>
    <fullName>SMS_Opt_Out_DateTime__c</fullName>
    <description>The date/time the marketing person opted out of receiving marketing comms via SMS.</description>
    <label>SMS Opt Out DateTime</label>
    <type>DateTime</type>
</CustomField>

src/core-crm/objects/Lead/fields/Work_Email__c.field-meta.xml
<CustomField>
    <fullName>Work_Email__c</fullName>
    <inlineHelpText>This field captures the work email of the contact.</inlineHelpText>
    <label>Work Email</label>
    <type>Email</type>
</CustomField>

src/core-crm/objects/Lead/fields/Work_SMS_Opt_Out__c.field-meta.xml
<CustomField>
    <fullName>Work_SMS_Opt_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Marketing should not sms this mobile number</description>
    <label>Work SMS Opt Out</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Lead/fields/Work_SMS_Opt_Out_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Work_SMS_Opt_Out_DateTime__c</fullName>
    <description>The date and time that the mobile opted out</description>
    <label>Work SMS Opt Out DateTime</label>
    <type>DateTime</type>
</CustomField>

src/core-crm/objects/Marketing_Segmentation__c/Marketing_Segmentation__c.object-meta.xml
<CustomObject>
    <label>Marketing Segmentation</label>
    <nameField>
        <displayFormat>MS - {000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Segmentations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Marketing_Segmentation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Marketing Segmentations</relationshipLabel>
    <relationshipName>Marketing_Segmentations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/classes/MarketingConsentHelper.cls
/**
* @description Helper Class to update marketing segmentation records for marketing consent
* @see .. ContactTriggerHanlder
*
* @author Accenture
*
* @history
*
| Developer Email                | Date                  | JIRA                   | Change Summary                                                                |
|--------------------------------|-----------------------|------------------------|-------------------------------------------------------------------------------|
| roy.nino.s.regala              | Feb 06, 2023          | DEPP-4866              | Created File                                                                  |
| roy.nino.s.regala              | Feb 20, 2023          | DEPP-5221              | added opt out and in dates                                                    |
| roy.nino.s.regala              | Oct 31, 2023          | DEPP-7060              | made sure to email opt in date to now only if it is not directly updated      |
|								 |                       |                        | this happens on lead convert or case creation                                 |
| johanna.a.gibas                | Jan 04, 2024          | ApexCRUDViolationFix   | Fixed CRUD Violation                                                          |
| sebastianne.k.trias            | June 06, 2024         | DEPP-8474              | Modify method setOptOutAndInDates                                             |
*/
public without sharing class MarketingConsentHelper {

	public static Map<Id, Boolean> runSetOptOutAndInDates = new Map<Id, Boolean>();

	private static final Map<String,Map<String,String>> setOptOutAndInFields = new Map<String,Map<String,String>>{
		'hasOptOutEmail' => new Map<String,String>{
			'optedOutField' => 'HasOptedOutOfEmail',
			'optInDateTimeField' => 'Email_Opt_In_DateTime__c',
			'optOutDateTimeField' => 'Email_Opt_Out_DateTime__c'
		},
		'smsOptOut' => new Map<String,String>{
			'optedOutField' => 'hed__SMS_Opt_Out__c',
			'optInDateTimeField' => 'SMS_Opt_In_DateTime__c',
			'optOutDateTimeField' => 'SMS_Opt_Out_DateTime__c'
		},
		'workSMSOptOut' => new Map<String,String>{
			'optedOutField' => 'Work_SMS_Opt_Out__c',
			'optInDateTimeField' => 'Work_SMS_Opt_In_DateTime__c',
			'optOutDateTimeField' => 'Work_SMS_Opt_Out_DateTime__c'
		}
	};

	public static void setOptOutAndInDates(List<SObject> newItems, Map<Id, SObject> oldMap, String objectName ) {
		Boolean isInsert = oldMap == null;

		Map<String, Boolean> booleanParams = new Map<String, Boolean>();
		Map<String, Datetime> dateTimeFieldsValue = new Map<String, Datetime>();

		for (SObject item : newItems) {

			booleanParams.put('isInsert', isInsert);

			if(objectName == 'Contact'){
				item = (Contact) item;
			}
			else if(objectName == 'Lead'){
				item = (Lead) item;
			}

			if( !isInsert && runSetOptOutAndInDates.containsKey((Id) item.get('Id'))){
				continue;
			}

			else{
				if( !isInsert && !runSetOptOutAndInDates.containsKey((Id) item.get('Id')) ){
					runSetOptOutAndInDates.put((Id) item.get('Id'), false);
				}
				
				for(Map<String,String> optOutFields : setOptOutAndInFields.values()){
					if( isInsert && item.get(optOutFields.get('optedOutField')) == false && item.get(optOutFields.get('optInDateTimeField')) == null ){
						continue;
					}
					boolean isHasOptedOutOfEmailChanged = !isInsert && ( item.get(optOutFields.get('optedOutField')) != oldMap.get( (Id) item.get('Id') ).get(optOutFields.get('optedOutField')) );
					booleanParams.put('isFieldOptOutOfEmailChanged', isHasOptedOutOfEmailChanged); // to get if hasoptedout is changed
					booleanParams.put('optedOutOfEmailNewValue', (Boolean) item.get(optOutFields.get('optedOutField'))); // to get the new value of optedoutofemail field
	
					dateTimeFieldsValue.put('newOptInValue', (Datetime) item.get(optOutFields.get('optInDateTimeField')) );
					dateTimeFieldsValue.put('newOptOutValue', (Datetime) item.get(optOutFields.get('optOutDateTimeField')) );
					
					if(!isInsert){
						dateTimeFieldsValue.put('oldOptInValue', (Datetime) oldMap.get( (Id) item.get('Id') ).get(optOutFields.get('optInDateTimeField')) );
						dateTimeFieldsValue.put('oldOptOutValue', (Datetime) oldMap.get( (Id) item.get('Id') ).get(optOutFields.get('optOutDateTimeField')) );
					}
	
					item.put(optOutFields.get('optInDateTimeField'), validateOptOutAndInFields(booleanParams, dateTimeFieldsValue).get('optInValue'));
					item.put(optOutFields.get('optOutDateTimeField'), validateOptOutAndInFields(booleanParams, dateTimeFieldsValue).get('optOutValue'));
				}
			}
		}
    }

	public static void processMarketingConsent(List<Contact> newItems, Map<Id,Contact> oldMap){

		Map<String, Contact> emailToContactMap = new Map<String,Contact>();
		Map<String, List<Marketing_Segmentation__c>> marketingSegMap =  new Map<String,List<Marketing_Segmentation__c>>();

		for(Contact con: newItems){
			//only process contacts with below condition
			//registered email is populated
			//from study portal     
			if( con.Registered_Email__c != null && con.Consent_Source_Category__c == 'Study Application' && ((oldMap == null && con.HasOptedOutOfEmail == false) || 
			(oldMap != null && (oldMap.get(con.Id).Email_Opt_In_DateTime__c != con.Email_Opt_In_DateTime__c || oldMap.get(con.Id).HasOptedOutOfEmail != con.HasOptedOutOfEmail)))){
				//contact is new or old that is opt in -> opt in or opt out -> opt in or opt in -> opt out
				emailToContactMap.put(con.Registered_Email__c,con);
				marketingSegMap.put(con.Registered_Email__c,new List<Marketing_Segmentation__c>());
			}
		}

		upsertMarketingSegmentation(getExistingMarketingSegmentations(marketingSegMap,emailToContactMap),emailToContactMap);

	}

	private static Map<String, Datetime> validateOptOutAndInFields(
		Map<String, Boolean> booleanParams,
		Map<String, Datetime> datetimeValues
	){
		Map<String, Datetime> returnValues = new Map<String, Datetime>();
		Boolean isInsert = booleanParams.get('isInsert');
		Boolean isFieldOptOutOfEmailChanged = booleanParams.get('isFieldOptOutOfEmailChanged');
		Boolean optedOutOfEmailValue = booleanParams.get('optedOutOfEmailNewValue');

		Datetime newOptInValue = datetimeValues.get('newOptInValue');
		Datetime oldOptInValue = datetimeValues.containsKey('oldOptInValue') ? datetimeValues.get('oldOptInValue') : null;

		Datetime newOptOutValue = datetimeValues.get('newOptOutValue');
		Datetime oldOptOutValue = datetimeValues.containsKey('oldOptOutValue') ? datetimeValues.get('oldOptOutValue') : null;

		Boolean isOptInDatetimeChanged = !isInsert && newOptInValue != oldOptInValue;
		Boolean isOptOutDatetimeChanged = !isInsert && newOptOutValue != oldOptOutValue;

		Datetime emailOptInDateTimeValue = null;
		Datetime emailOptOutDateTimeValue = null;

		if( isInsert && optedOutOfEmailValue == false && newOptInValue != null ){
			emailOptInDateTimeValue = newOptInValue;
			emailOptOutDateTimeValue = null;
		}
		else if( isInsert && optedOutOfEmailValue == true && newOptOutValue != null ){
			emailOptInDateTimeValue = null;
			emailOptOutDateTimeValue = newOptOutValue;
		}

		if( !isInsert && !isFieldOptOutOfEmailChanged ){
			emailOptInDateTimeValue = oldOptInValue;
			emailOptOutDateTimeValue = oldOptOutValue;
		}
		else if ( optedOutOfEmailValue == false && isFieldOptOutOfEmailChanged && isOptInDatetimeChanged ){
			emailOptInDateTimeValue = newOptInValue;
			emailOptOutDateTimeValue = oldOptOutValue;
		}
		else if ( optedOutOfEmailValue == true && isFieldOptOutOfEmailChanged && isOptOutDatetimeChanged ){
			emailOptInDateTimeValue = oldOptInValue;
			emailOptOutDateTimeValue = newOptOutValue;
		}
		else if( optedOutOfEmailValue == false && isFieldOptOutOfEmailChanged && !isOptInDatetimeChanged ){
			emailOptInDateTimeValue = System.now();
			emailOptOutDateTimeValue = oldOptOutValue;
		}
		else if( optedOutOfEmailValue == true && isFieldOptOutOfEmailChanged && !isOptOutDatetimeChanged ){
			emailOptInDateTimeValue = oldOptInValue;
			emailOptOutDateTimeValue = System.now();
		}

		returnValues.put('optInValue', emailOptInDateTimeValue);
		returnValues.put('optOutValue', emailOptOutDateTimeValue);

		return returnValues;
	}

	private static Map<String, List<Marketing_Segmentation__c>> getExistingMarketingSegmentations(Map<String, List<Marketing_Segmentation__c>> marketingSegMap, Map<String, Contact> emailToContactMap ){

		if(!emailToContactMap.keySet().isEmpty()){
			
			for(Marketing_Segmentation__c marSeg: MarketingSegmentationsDAO.newInstance().getExistingMarketingSegmentations(emailToContactMap,AccessLevel.SYSTEM_MODE)){

				//create email to marketing segmentation map
				//this groups marketing segmentation agains a person and mc persona with the same registered email
				if(emailToContactMap.containsKey(marSeg.Contact__r.Email)){
					marketingSegMap.get(marSeg.Contact__r.Email).add(marSeg);
				}else if(emailToContactMap.containsKey(marSeg.Contact__r.Work_Email__c)){
					marketingSegMap.get(marSeg.Contact__r.Work_Email__c).add(marSeg);
				}else if(emailToContactMap.containsKey(marSeg.Contact__r.QUT_Staff_Email__c)){
					marketingSegMap.get(marSeg.Contact__r.QUT_Staff_Email__c).add(marSeg);
				}else if(emailToContactMap.containsKey(marSeg.Contact__r.QUT_Learner_Email__c)){
					marketingSegMap.get(marSeg.Contact__r.QUT_Learner_Email__c).add(marSeg);
				}
			}
		}
		

		return marketingSegMap;

	}

	private static void upsertMarketingSegmentation(Map<String,List<Marketing_Segmentation__c>> marketingSegMap, Map<String,Contact> emailToContactMap){

		Marketing_Segmentation__c newMarketingSeg;
		List<Marketing_Segmentation__c> segmentationsToUpsert = new List<Marketing_Segmentation__c>();

		for(String emailKey: marketingSegMap.keySet()){
			//has existing marketing segmentations
			for(Marketing_Segmentation__c marSeg: marketingSegMap.get(emailKey)){
			if( emailToContactMap.get(emailKey).HasOptedOutOfEmail == false){
				//if opt in 
				marSeg.My_Profile_Persona__c = 'Open Professional Education';
				marSeg = processContactOptIn(marSeg);
			}else{
				//if opt out
				//nullify fields if equal to specified values
				marSeg = processContactOptOut(marSeg);
			}
			segmentationsToUpsert.add(marSeg);
			}

			//no existing marketing segmentation and contact is opt in
			if(marketingSegMap.get(emailKey).isEmpty() && emailToContactMap.get(emailKey).HasOptedOutOfEmail == false){
			//create new marketing segmentation
			newMarketingSeg = new Marketing_Segmentation__c(
				My_Profile_Persona__c = 'Open Professional Education',
				My_Primary_Study_Level__c = 'Short Courses and Professional Development',
				Contact__c = emailToContactMap.get(emailKey).Id
			);
			marketingSegMap.get(emailKey).add(newMarketingSeg);
			segmentationsToUpsert.addAll(marketingSegMap.get(emailKey));
			}
		}

		if(!segmentationsToUpsert.isEmpty()){
			MarketingSegmentationsDAO.newInstance().upsertRecords(segmentationsToUpsert, false, AccessLevel.SYSTEM_MODE);
		}
	}

	private static Marketing_Segmentation__c processContactOptIn(Marketing_Segmentation__c marSeg){
	
		if(   	marSeg.My_Primary_Study_Level__c != 'Short Courses and Professional Development' &&
				marSeg.My_Secondary_Study_Level__c != 'Short Courses and Professional Development' && 
				marSeg.My_Primary_Study_Level__c != null){
				//if both primary and study level is not short courses and professional development 
				//And primary study level is populated
				//update the secondary study level
				marSeg.My_Secondary_Study_Level__c = 'Short Courses and Professional Development';

		}else if(   marSeg.My_Primary_Study_Level__c != 'Short Courses and Professional Development' && 
					marSeg.My_Secondary_Study_Level__c != 'Short Courses and Professional Development' && 
					marSeg.My_Primary_Study_Level__c == null){
					//if both primary and study level is not short courses and professional development 
					//And primary study level is not populated
					//update the secondary study level
					marSeg.My_Primary_Study_Level__c = 'Short Courses and Professional Development';
		}

		return marSeg;
	}

	private static Marketing_Segmentation__c processContactOptOut(Marketing_Segmentation__c marSeg){
	
		marSeg.My_Profile_Persona__c = marSeg.My_Profile_Persona__c == 'Open Professional Education'?null:marSeg.My_Profile_Persona__c;
		marSeg.My_Primary_Study_Level__c = marSeg.My_Primary_Study_Level__c == 'Short Courses and Professional Development'?null:marSeg.My_Primary_Study_Level__c;
		marSeg.My_Secondary_Study_Level__c = marSeg.My_Secondary_Study_Level__c == 'Short Courses and Professional Development'?null:marSeg.My_Secondary_Study_Level__c;

		return marSeg;
	}
}