src/core-crm/objects/List__c/List__c.object-meta.xml
<CustomObject>
    <description>List supports information capture about a request to compile a list of Contacts for a defined business reason.</description>
    <label>List</label>
    <nameField>
        <displayFormat>LIST-{000000}</displayFormat>
        <label>List Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/List_Member__c/List_Member__c.object-meta.xml
<CustomObject>
    <description>List Member contains information about the Contacts who have been included in a Contact List and details about the staff member who contributed to compiling the list of contacts.</description>
    <label>List Member</label>
    <nameField>
        <displayFormat>LM-{0000000}</displayFormat>
        <label>List Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>List Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/List_Member__c/fields/Activity_Status__c.field-meta.xml
<CustomField>
    <fullName>Activity_Status__c</fullName>
    <description>The status of the Activity process.</description>
    <label>Activity Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Unable to contact</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/List_Member__c/fields/List__c.field-meta.xml
<CustomField>
    <fullName>List__c</fullName>
    <description>Lookup to the List record.</description>
    <label>List Id</label>
    <referenceTo>List__c</referenceTo>
    <relationshipLabel>List Members</relationshipLabel>
    <relationshipName>List_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/core-crm/objects/List_Member__c/fields/List_Member__c.field-meta.xml
<CustomField>
    <fullName>List_Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A Contact who has met the criteria to be included in the list.</description>
    <inlineHelpText>Contact who has met criteria for inclusion in the list.</inlineHelpText>
    <label>List Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>List Members</relationshipLabel>
    <relationshipName>List_Members</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/core-crm/classes/ListMemberImportModalCtrlTest.cls
/**
 * @description Test class for CustomHeaderDatatableCtrl
 *
 * @see ListMemberImportModalCtrl
 *
 * @author Accenture
 *
 * @history
 *    | Developer                           | Date                  | JIRA                 | Change Summary                                         |
      |-------------------------------------|-----------------------|----------------------|--------------------------------------------------------|
      | neil.s.h.lesidan@accenture.com      | December 20, 2023     | DEPP-7005            | Created file                                           |
*/
@isTest
public with sharing class ListMemberImportModalCtrlTest {
    @testSetup
    static void testSetup() {
        TestDataFactory.generateTestUsers(new List<String>{ 'QUT_IE_Partnership_Manager' });
        List<List__c> newListRecords = TestDataFactory.createListRecords(1);
        List<Contact> newContacts = TestDataFactory.createTestContactRecords(1);
        ListsDAO.newInstance().insertRecords(newListRecords, false, AccessLevel.USER_MODE);
        ContactsDAO.newInstance().insertRecords(newContacts, false, AccessLevel.USER_MODE);
    }

    @isTest
    static void getContactByIdTest(){
        Contact con = ContactsDAO.getPersonContactsWithLimit(1).iterator().next();

        System.runAs(TestDataFactory.getQUTIEPartnershipManager()) {
            Test.startTest();
            List<Contact> contactsList = ListMemberImportModalCtrl.getContactById((String) con.Id);
            System.assert(!contactsList.isEmpty(), 'No Contact found');

            Test.stopTest();
        }
    }

    @isTest
    static void bulkSaveListMemberTest(){
        Contact con = ContactsDAO.getPersonContactsWithLimit(1).iterator().next();
        List__c listRec = ListsDAO.newInstance().getListRecords(1).iterator().next();
        System.runAs(TestDataFactory.getQUTIEPartnershipManager()) {
            Test.startTest();
            String record = '[{ "List_Member__c": "' + con.Id  + '", "Activity_Status__c": "Accepted" }]';
            Boolean isBulkSave = ListMemberImportModalCtrl.bulkSaveListMember((String) listRec.Id, record);
            System.assert(isBulkSave, 'Error upon saving');

            Test.stopTest();
        }
    }
}