src/core-crm/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>The Opportunity Start Date.</description>
    <inlineHelpText>The Opportunity Start Date.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Opportunity_Outcome__c/Opportunity_Outcome__c.object-meta.xml
<CustomObject>
    <description>Opportunity Outcome captures the outcome of a given Opportunity. Each Opportunity can have many Opportunity Outcomes.</description>
    <label>Opportunity Outcome</label>
    <nameField>
        <displayFormat>OO-{00000}</displayFormat>
        <label>Opportunity Outcome Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Outcomes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/core-crm/objects/Opportunity_Outcome__c/fields/Decommissioned_Date__c.field-meta.xml
<CustomField>
    <fullName>Decommissioned_Date__c</fullName>
    <description>The date the project is/was decommissioned.</description>
    <label>Decommissioned Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Opportunity_Outcome__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Project end date.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Opportunity_Outcome__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to associated Opportunity.</description>
    <inlineHelpText>Lookup to associated Opportunity.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Outcomes</relationshipLabel>
    <relationshipName>Opportunity_Outcomes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Opportunity_Outcome__c/fields/Outcome_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Outcome_Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Identifies if the outcome has been formally agreed to and written into the finalised contract.</description>
    <inlineHelpText>Identifies if the outcome has been formally agreed to and written into the finalised contract.</inlineHelpText>
    <label>Outcome Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Opportunity_Outcome__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Project start date.</description>
    <inlineHelpText>Project start date.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/classes/OpportunityOutcomesDAOMock.cls
/**
 * @description Mock DAO Class for Opportunity Object. 
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | alexander.cadalin              | May 17, 2023          | DEPP-5594              | created file
      | carl.alvin.cabiles             | May 25, 2023          | DEPP-5410              | added methods
      | carl.alvin.cabiles             | June 13, 2023         | DEPP-5409              | added methods
      | kenneth.f.alsay                | June 19, 2023         | DEPP-5434,5399         | added getRecordsWithOpportunity method
      | kenneth.f.alsay                | February 1, 2024      | DEPP-6938              | added getActiveCorporateOutcomes method
*/
@isTest
public inherited sharing class OpportunityOutcomesDAOMock extends DmlBaseMock implements IOpportunityOutcomesDAO {
    public Map<Id, Opportunity_Outcome__c> opportunityOutcomesMap;

    public Schema.SObjectType getSObjectType() {
        return Opportunity_Outcome__c.SObjectType;
    }

    public OpportunityOutcomesDAOMock() {
        super(new Map<Id, Opportunity_Outcome__c>(), Schema.Opportunity_Outcome__c.SObjectType);
        this.opportunityOutcomesMap = (Map<Id, Opportunity_Outcome__c>) super.records;
    }

    public List<Opportunity_Outcome__c> getRecordsSortByCodeAsc() {
        return opportunityOutcomesMap.values();
    }

    public List<Opportunity_Outcome__c> getRecordsWithLikeCodeSortAsc(String codeIsLike) {
        return opportunityOutcomesMap.values();
    }
    public List<Opportunity_Outcome__c> getRecordsWithEqualEndDate(Date endDate){
        List<Opportunity_Outcome__c> opportunityOutcomeList = new List<Opportunity_Outcome__c>();
        for (Opportunity_Outcome__c record: opportunityOutcomesMap.values()){
            if(endDate == record.End_Date__c){
                opportunityOutcomeList.add(record);
            }
        }
        return opportunityOutcomeList;
    }
    public List<Opportunity_Outcome__c> getRecordsWithNotEqualEndDate(Date endDate){
        List<Opportunity_Outcome__c> opportunityOutcomeList = new List<Opportunity_Outcome__c>();
        for (Opportunity_Outcome__c record: opportunityOutcomesMap.values()){
            if(endDate != record.End_Date__c){
                opportunityOutcomeList.add(record);
            }
        }
        return opportunityOutcomeList;
    }
    public List<Opportunity_Outcome__c> getRecordsWithStartDate(Date startDate){
        List<Opportunity_Outcome__c> opportunityOutcomeList = new List<Opportunity_Outcome__c>();
        for (Opportunity_Outcome__c record: opportunityOutcomesMap.values()){
            if(startDate == record.Start_Date__c){
                opportunityOutcomeList.add(record);
            }
        }
        return opportunityOutcomeList;
    }

    public List<Opportunity_Outcome__c> getRecordsWithOpportunity(List<Id> opportunityList) {
        List<Opportunity_Outcome__c> opportunityOutcomeList = new List<Opportunity_Outcome__c>();
        for (Opportunity_Outcome__c record: opportunityOutcomesMap.values()){
            if(opportunityList.contains(record.Opportunity__c)){
                opportunityOutcomeList.add(record);
            }
        }
        return opportunityOutcomeList;
    }

    public List<Opportunity_Outcome__c> getRecordsWithPastDateAsDecommissionedDate(){
        List<Opportunity_Outcome__c> opportunityOutcomeList = new List<Opportunity_Outcome__c>();
        for (Opportunity_Outcome__c record: opportunityOutcomesMap.values()){
            if(record.Decommissioned_Date__c <= System.today()){
                opportunityOutcomeList.add(record);
            }
        }
        return opportunityOutcomeList;
    }
    public List<Opportunity_Outcome__c> getRecordsWithFutureDateAsDecommissionedDate(){
        List<Opportunity_Outcome__c> opportunityOutcomeList = new List<Opportunity_Outcome__c>();
        for (Opportunity_Outcome__c record: opportunityOutcomesMap.values()){
            if(record.Decommissioned_Date__c > System.today()){
                opportunityOutcomeList.add(record);
            }
        }
        return opportunityOutcomeList;
    }
    public List<Opportunity_Outcome__c> getActiveCorporateOutcomes(AccessLevel accessLevel){
        List<Opportunity_Outcome__c> opportunityOutcomeList = new List<Opportunity_Outcome__c>();
        for (Opportunity_Outcome__c record: opportunityOutcomesMap.values()){
            if(record.Outcome_Is_Active__c = true){
                opportunityOutcomeList.add(record);
            }
        }
        return opportunityOutcomeList;
    }
}