src/core-crm/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>The Opportunity Start Date.</description>
    <inlineHelpText>The Opportunity Start Date.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Opportunity_Code_Auto_Number__c/Opportunity_Code_Auto_Number__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom setting contains the auto-numbers used for the Opportunity object&apos;s Opportunity Code.</description>
    <label>Opportunity Code Auto Number</label>
</CustomObject>

src/core-crm/objects/Opportunity_Code_Auto_Number__c/fields/Commercialisation__c.field-meta.xml
<CustomField>
    <fullName>Commercialisation__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Auto-number used for Commercialisation Opportunity records.</description>
    <label>Commercialisation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Opportunity_Code_Auto_Number__c/fields/International_Projects_Unit__c.field-meta.xml
<CustomField>
    <fullName>International_Projects_Unit__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Auto-number used for International Projects Unit Opportunity records.</description>
    <label>International Projects Unit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Opportunity_Code_Auto_Number__c/fields/Research_Partnership__c.field-meta.xml
<CustomField>
    <fullName>Research_Partnership__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Auto-number used for Research Partnership Opportunity records.</description>
    <label>Research Partnership</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Opportunity_Outcome__c/Opportunity_Outcome__c.object-meta.xml
<CustomObject>
    <description>Opportunity Outcome captures the outcome of a given Opportunity. Each Opportunity can have many Opportunity Outcomes.</description>
    <label>Opportunity Outcome</label>
    <nameField>
        <displayFormat>OO-{00000}</displayFormat>
        <label>Opportunity Outcome Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Outcomes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/core-crm/objects/Opportunity_Outcome__c/fields/Stage_Name__c.field-meta.xml
<CustomField>
    <fullName>Stage_Name__c</fullName>
    <description>The business process stages that Opportunity Outcomes progress through.</description>
    <inlineHelpText>The business process stages that Opportunity Outcomes progress through.</inlineHelpText>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Deregistered</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Opportunity_Outcome__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Project start date.</description>
    <inlineHelpText>Project start date.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Opportunity_Outcome_Code_Auto_Number__c/Opportunity_Outcome_Code_Auto_Number__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom setting contains the auto-numbers used for the Opportunity Outcome object&apos;s Code field.</description>
    <label>Opportunity Outcome Code Auto Number</label>
</CustomObject>

src/core-crm/objects/Opportunity_Outcome_Code_Auto_Number__c/fields/IPU_Project__c.field-meta.xml
<CustomField>
    <fullName>IPU_Project__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Auto-number used for IPU Project Opportunity Outcome records.</description>
    <label>IPU Project</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Opportunity_Outcome_Code_Auto_Number__c/fields/Research_Commercialisation_Project__c.field-meta.xml
<CustomField>
    <fullName>Research_Commercialisation_Project__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Auto-number used for Research Commercialisation Project Opportunity Outcome records.</description>
    <label>Research Commercialisation Project</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Opportunity_Outcome_Code_Auto_Number__c/fields/Research_Partnership_Project__c.field-meta.xml
<CustomField>
    <fullName>Research_Partnership_Project__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Auto-number used for Research Partnership Project Opportunity Outcome records.</description>
    <label>Research Partnership Project</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Opportunity_Outcome_Code_Auto_Number__c/fields/Start_Up__c.field-meta.xml
<CustomField>
    <fullName>Start_Up__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Auto-number used for Start-Up Opportunity Outcome records.</description>
    <label>Start-Up</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/classes/Update_Opp_Outcome_to_New_or_ActiveTest.cls
/**
 * @description Test class to test coverage of Update_Opp_Outcome_to_New_or_Active_Flow
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
 *    |--------------------------------|-----------------------|------------------------|------------------------------|
 *    | ryan.j.a.dela.cruz             | July 06, 2023         | DEPP-5995              | Created file
 */
@isTest
public class Update_Opp_Outcome_to_New_or_ActiveTest {
    private static string companyName = 'TestCompany';
    private static string projectName = 'project';
    private static string code = '0';
    private static Id recordTypeId = OpportunityOutcomesDAO.IPUPROJECT_RECTYPE_ID;
    private static Integer numOfOppOutcome = 5;
    private static Date currentDate = System.today();

    @testSetup
    static void testSetup() {
        TestDataFactory.generateTestUsers(new List<String>{ 'Industry_Partnership_Manager' });

        Opportunity_Code_Auto_Number__c opptyCodeAutoNum = OpportunityCodeAutoNumbersDAO.newInstance()
            .getOrganizationalDefaults();
        opptyCodeAutoNum.Commercialisation__c = 1;
        opptyCodeAutoNum.International_Projects_Unit__c = 1;
        opptyCodeAutoNum.Research_Partnership__c = 1;
        OpportunityCodeAutoNumbersDAO.newInstance()
            .upsertRecords(
                new List<Opportunity_Code_Auto_Number__c>{ opptyCodeAutoNum },
                false,
                AccessLevel.USER_MODE
            );

        Opportunity_Outcome_Code_Auto_Number__c oppOutcomeCodeAutoNum = OpportunityOutcomeCodeAutoNumbersDAO.newInstance()
            .getOrganizationalDefaults();
        oppOutcomeCodeAutoNum.Research_Partnership_Project__c = 1;
        oppOutcomeCodeAutoNum.IPU_Project__c = 1;
        oppOutcomeCodeAutoNum.Research_Commercialisation_Project__c = 1;
        oppOutcomeCodeAutoNum.Start_Up__c = 1;
        OpportunityOutcomeCodeAutoNumbersDAO.newInstance()
            .upsertRecords(
                new List<Opportunity_Outcome_Code_Auto_Number__c>{ oppOutcomeCodeAutoNum },
                false,
                AccessLevel.USER_MODE
            );

        List<Opportunity> opportunities = TestDataFactory.createOpportunityRecords(
            1,
            'OpportunityTest',
            OpportunitiesDAO.IDENTIFY_STAGE
        );
        OpportunitiesDAO.newInstance().insertRecords(opportunities, false, AccessLevel.USER_MODE);

        List<Opportunity_Outcome__c> opportunityList = TestDataFactory.createOpportunityOutcome(
            numOfOppOutcome,
            recordTypeId,
            opportunities[0].Id
        );
        OpportunityOutcomesDAO.newInstance()
            .insertRecords(opportunityList, false, AccessLevel.USER_MODE);
    }

    @isTest
    private static void updateOpportunityOutcomeStartDateToCurrentTest() {
        System.runAs(TestDataFactory.getQUTIEPartnershipManager()) {
            List<Opportunity_Outcome__c> opportunityOutcomeListToUpdate = OpportunityOutcomesDAO.newInstance()
                .getRecordsWithStartDate(currentDate + 10); // from future date

            Test.startTest();
            updateStartDate(opportunityOutcomeListToUpdate, 0); // update to current date
            Test.stopTest();
            List<Opportunity_Outcome__c> oppOutcomes = OpportunityOutcomesDAO.newInstance()
                .getRecordsWithStartDate(currentDate - 10); // compare with current date

            for (Opportunity_Outcome__c oppOutcome : oppOutcomes) {
                System.assertEquals(
                    OpportunityOutcomesDAO.ACTIVE_STAGE,
                    oppOutcome.Stage_Name__c,
                    'Stage should be Active.'
                );
            }
        }
    }

    @isTest
    private static void updateOpportunityOutcomeStartDateToFutureTest() {
        System.runAs(TestDataFactory.getQUTIEPartnershipManager()) {
            List<Opportunity_Outcome__c> opportunityOutcomeListToUpdate = OpportunityOutcomesDAO.newInstance()
                .getRecordsWithStartDate(currentDate + 10); // from future date

            Test.startTest();
            updateStartDate(opportunityOutcomeListToUpdate, 10); // add 10 more days (Still future)
            Test.stopTest();
            List<Opportunity_Outcome__c> oppOutcomes = OpportunityOutcomesDAO.newInstance()
                .getRecordsWithStartDate(currentDate + 10); // compare with current date

            for (Opportunity_Outcome__c oppOutcome : oppOutcomes) {
                System.assertEquals(
                    OpportunityOutcomesDAO.NEW_STAGE,
                    oppOutcome.Stage_Name__c,
                    'Stage should be New.'
                );
            }
        }
    }

    @isTest
    private static void updateOpportunityOutcomeStartDateToPreviousTest() {
        System.runAs(TestDataFactory.getQUTIEPartnershipManager()) {
            List<Opportunity_Outcome__c> opportunityOutcomeListToUpdate = OpportunityOutcomesDAO.newInstance()
                .getRecordsWithStartDate(currentDate + 10); // from future date

            Test.startTest();
            updateStartDate(opportunityOutcomeListToUpdate, -10); // decrease 10 more days (previous date)
            Test.stopTest();

            List<Opportunity_Outcome__c> oppOutcomes = OpportunityOutcomesDAO.newInstance()
                .getRecordsWithStartDate(currentDate - 10); // compare with current date

            for (Opportunity_Outcome__c oppOutcome : oppOutcomes) {
                System.assertEquals(
                    OpportunityOutcomesDAO.ACTIVE_STAGE,
                    oppOutcome.Stage_Name__c,
                    'Stage should be Active.'
                );
            }
        }
    }

    private static void updateStartDate(
        List<Opportunity_Outcome__c> opportunityOutcomes,
        Integer increment
    ) {
        for (Opportunity_Outcome__c opp_outcome : opportunityOutcomes) {
            opp_outcome.Start_Date__c = currentDate + increment;
        }
        update opportunityOutcomes;
    }
}