src/core-crm/objects/Distribution_Management__c/Distribution_Management__c.object-meta.xml
<CustomObject>
    <description>Distribution Management records enable users to setup and control how donation payments will be distributed for each Designation.</description>
    <label>Distribution Management</label>
    <nameField>
        <displayFormat>DM-{000000}</displayFormat>
        <label>Distribution Management Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Distribution Managements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Distribution_Split__c/Distribution_Split__c.object-meta.xml
<CustomObject>
    <description>Distribution Split stores the information about how donation payments will be distributed to Finance GL Account(s).</description>
    <label>Distribution Split</label>
    <nameField>
        <displayFormat>DS-{000000}</displayFormat>
        <label>Distribution Split Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Distributions Split</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/core-crm/objects/Distribution_Split__c/fields/Distribution_Management__c.field-meta.xml
<CustomField>
    <fullName>Distribution_Management__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the associated Distribution Management record.</description>
    <inlineHelpText>Lookup to the associated Distribution Management record.</inlineHelpText>
    <label>Distribution Management</label>
    <referenceTo>Distribution_Management__c</referenceTo>
    <relationshipLabel>Distributions Split</relationshipLabel>
    <relationshipName>Distributions_Split</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Distribution_Split__c/fields/Finance_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>Finance_GL_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to the associated GL Account record.</description>
    <inlineHelpText>Lookup to the associated GL Account record.</inlineHelpText>
    <label>Finance GL Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Finance_GL_Account__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Finance_GL_Account__c</referenceTo>
    <relationshipLabel>Distributions Split</relationshipLabel>
    <relationshipName>Distributions_Split</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Distribution_Split__c/fields/GL_Account_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Code__c</fullName>
    <description>19-digit account code represents QUT’s Finance Chart of Accounts.</description>
    <formula>Finance_GL_Account__r.GL_Account_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>19-digit account code represents QUT’s Finance Chart of Accounts.</inlineHelpText>
    <label>GL Account Code</label>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Distribution_Split__c/fields/Is_Soft_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Is_Soft_Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the record is hidden from users in the DEP UI.</description>
    <inlineHelpText>Indicates if the record is hidden from users in the DEP UI.</inlineHelpText>
    <label>Is Soft Deleted</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Distribution_Split__c/fields/Participating_Group__c.field-meta.xml
<CustomField>
    <fullName>Participating_Group__c</fullName>
    <description>The name of the group the split applies to.</description>
    <inlineHelpText>The name of the group the split applies to.</inlineHelpText>
    <label>Participating Group</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Distribution_Split__c/fields/Percentage_Split__c.field-meta.xml
<CustomField>
    <fullName>Percentage_Split__c</fullName>
    <description>The percentage amount for the split.</description>
    <inlineHelpText>The percentage amount for the split.</inlineHelpText>
    <label>Percentage Split</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

src/core-crm/objects/Finance_GL_Account__c/Finance_GL_Account__c.object-meta.xml
<CustomObject>
    <description>Ledger Account reference data from QUT Finance System.</description>
    <label>Finance GL Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Finance_GL_Account__c/fields/GL_Account_Code__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Code__c</fullName>
    <description>19-digit account code represents QUT’s Finance Chart of Accounts</description>
    <inlineHelpText>19-digit account code represents QUT’s Finance Chart of Accounts</inlineHelpText>
    <label>GL Account Code</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/core-crm/classes/DistributionSplitsDAO.cls
/**
 * @description Mock DAO Class for Distribution Split Object.
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary                                 |
      |--------------------------------|-----------------------|------------------------|------------------------------------------------|
      | neil.s.h.lesidan               | April 12, 2024        | DEPP-8392              | Created file                                   |
*/
public inherited sharing class DistributionSplitsDAO extends DmlBase implements IDistributionSplitsDAO {
    public static IDistributionSplitsDAO newInstance() {
        return (IDistributionSplitsDAO) ImplementationSelector.DAO.newInstance(
            Distribution_Split__c.SObjectType
        );
    }

    public Schema.SObjectType getSObjectType() {
        return Distribution_Split__c.SObjectType;
    }

    public List<Distribution_Split__c> getDistributionSplitByDistributionManagement(
        Set<Id> ids,
        AccessLevel accessLevel
    ){
        if(ids.isEmpty()){
            return new List<Distribution_Split__c>();
        }

        return Database.query(
            'SELECT Id, Name, GL_Account_Code__c, Participating_Group__c, Percentage_Split__c, Distribution_Management__r.Name, Finance_GL_Account__r.Name, Is_Soft_Deleted__c ' +
            'FROM Distribution_Split__c ' +
            'WHERE Distribution_Management__c IN :ids ',
            accessLevel
        );
    }
}