src/core-crm/objects/Communication_Queue__c/Communication_Queue__c.object-meta.xml
<CustomObject>
    <label>Communication Queue</label>
    <nameField>
        <displayFormat>CQ-{00000000}</displayFormat>
        <label>Communication Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Communication_Queue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Retry Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Contact/fields/Calculated_Cadence__c.field-meta.xml
<CustomField>
    <fullName>Calculated_Cadence__c</fullName>
    <externalId>true</externalId>
    <label>Calculated Cadence</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/main/objects/Contact/fields/hed__Citizenship_Status__c.field-meta.xml
<CustomField>
    <fullName>hed__Citizenship_Status__c</fullName>
    <description>The Contact&apos;s citizenship status.</description>
    <inlineHelpText>The Contact&apos;s citizenship status.</inlineHelpText>
    <label>Citizenship Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>U.S. Citizen or U.S. National</fullName>
            </value>
            <value>
                <fullName>U.S. Dual Citizen</fullName>
            </value>
            <value>
                <fullName>U.S. Permanent Resident</fullName>
            </value>
            <value>
                <fullName>U.S. Refugee or Asylee</fullName>
            </value>
            <value>
                <fullName>Temporary Resident</fullName>
            </value>
            <value>
                <fullName>Other (Non-U.S.)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Contact/fields/Lead_Score_Detail__c.field-meta.xml
<CustomField>
    <fullName>Lead_Score_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The breakdown of lead scoring by category aggregates.</description>
    <label>Lead Score Detail</label>
    <referenceTo>Lead_Score_Detail__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Lead_Score_Detail__c/Lead_Score_Detail__c.object-meta.xml
<CustomObject>
    <label>Lead Score Detail</label>
    <nameField>
        <displayFormat>LSD-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Score Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Lead_Score_Detail__c/fields/Total_Lead_Score__c.field-meta.xml
<CustomField>
    <fullName>Total_Lead_Score__c</fullName>
    <description>The total aggregate score for all categories</description>
    <label>Total Lead Score</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Nurture_Track_Configuration__c/Nurture_Track_Configuration__c.object-meta.xml
<CustomObject>
    <label>Nurture Track Configuration</label>
    <nameField>
        <displayFormat>NTC-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nurture Track Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Nurture_Track_Configuration__c/fields/Cadence_Name__c.field-meta.xml
<CustomField>
    <fullName>Cadence_Name__c</fullName>
    <description>The Name of the Cadence the Configuration is for</description>
    <label>Cadence Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Nurture_Track_Configuration__c/fields/Lead_Score_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Lead_Score_Threshold__c</fullName>
    <description>The Lead Score Threshold for inclusion in the Track

Note: This value needs to be replicated to all cadences in the track</description>
    <label>Lead Score Threshold</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Nurture_Track_Configuration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Cadence Status is used to activate or deactivate the cadence</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/classes/SalesCadenceEmailRequestCommandTest.cls
/**
 * @description Test class for SalesCadenceEmailRequestCommand
 * 
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | eccarius.munoz      	       | September 2, 2023     | DEPP-6138              | Created file                 | 
 */

@isTest
public with sharing class SalesCadenceEmailRequestCommandTest {

    @TestSetup
    static void setupData(){
        TestDataFactory.generateTestUsers(new List<String>{ 'QUT_System_Administrator' });
        System.runAs(TestDataFactory.getSystemAdminUser()) { 

            List<Nurture_Track_Configuration__c> initialNurtureList = TestDataFactory.createNurtureTrackConfigRecords(1);
            List<Nurture_Track_Configuration__c> nurtureList = new List<Nurture_Track_Configuration__c>();
            for(Nurture_Track_Configuration__c nurtureTrackConfig : initialNurtureList){
                nurtureList.add(
                    new Nurture_Track_Configuration__c(
                        Id = nurtureTrackConfig.Id,
                        Cadence_Name__c = 'International Application Submission - Direct Applicant (Automated)',
                        Lead_Score_Threshold__c = 3,
                        Status__c = 'Active'
                    )
                );
            }
            NurtureTrackConfigurationsDAO.newInstance().insertRecords(nurtureList, false, AccessLevel.SYSTEM_MODE);  
            
        }
    }

    @isTest
    private static void sendEmailWithSentStatusTest() {
        System.runAs(TestDataFactory.getSystemAdminUser()) {
            Lead_Score_Detail__c lsd = new Lead_Score_Detail__c();
            lsd.Total_Lead_Score__c = 350;
            insert lsd;

            List<Contact> contactList = TestDataFactory.createTestContactRecords(1,2);
            for(Contact c :contactList ){
                c.Calculated_Cadence__c = 'International Application Submission - Direct Applicant (Automated)';
                c.hed__Citizenship_Status__c = 'Domestic';
                c.Lead_Score_Detail__c = lsd.Id;
            }
            ContactsDAO.newInstance().insertRecords(contactList, false, AccessLevel.USER_MODE);

            Set<Id> resultIds = (new Map<Id,SObject>(contactList)).keySet();
            List<Communication_Queue__c> commsQueueList = TestDataFactory.createCommunicationQueuePerContactOrLead(
                resultIds, 
                CommunicationQueuesDAO.STATUS_SCHEDULED
            );
            CommunicationQueuesDAO.newInstance().insertRecords(commsQueueList, false, AccessLevel.USER_MODE);
            
            List<Communication_Queue__c> communicationQueueList = CommunicationQueuesDAO.newInstance().getComminicationQueueRecordsByStatus(
                new Set<String>{CommunicationQueuesDAO.STATUS_SCHEDULED},
                AccessLevel.USER_MODE
            );
            Test.startTest();
            RequestCommand cmd = new RequestCommand();
            cmd.setCommand(new SalesCadenceEmailRequestCommand(communicationQueueList));
            cmd.executeCommand();     
            Test.stopTest();
        }

        List<Communication_Queue__c> commsQueue = CommunicationQueuesDAO.newInstance().getComminicationQueueRecordsByStatus(
            new Set<String>{CommunicationQueuesDAO.STATUS_SENT},
            AccessLevel.USER_MODE
        );

        System.assert(!commsQueue.isEmpty(), 'List should not be empty.');
    }

}