src/core-crm/objects/Communication_Queue__c/Communication_Queue__c.object-meta.xml
<CustomObject>
    <label>Communication Queue</label>
    <nameField>
        <displayFormat>CQ-{00000000}</displayFormat>
        <label>Communication Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Communication_Queue__c/fields/Business_Process__c.field-meta.xml
<CustomField>
    <fullName>Business_Process__c</fullName>
    <description>The Business process and Communication Type</description>
    <label>Business Process</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic Automated Cadence Email</fullName>
            </value>
            <value>
                <fullName>International Automated Cadence Email</fullName>
            </value>
            <value>
                <fullName>International Automated Cadence SMS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Communication_Queue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Retry Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/classes/DomesticNoAnswerSMSBatchTest.cls
/**
 * @description Test class for DomesticNoAnswerSMSBatch
 * 
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | alexander.cadalin              | March 07 2024         | DEPP-8035              | Created file                 |
 */
@isTest
public with sharing class DomesticNoAnswerSMSBatchTest {
    @testSetup
    static void setup() {
        Test.startTest();
        TestDataFactoryUser.generateUserSystemAdministrator();
        Test.stopTest();
        System.runAs(TestDataFactoryUser.selectUserSystemAdministrator) {
            List<Communication_Queue__c> commQueues = new List<Communication_Queue__c>();
            commQueues.add(new Communication_Queue__c(
                Status__c = CommunicationQueuesDAO.STATUS_SCHEDULED,
                Business_Process__c = CommunicationQueuesDAO.BUSINESS_PROCESS_DOMESTIC_NO_ANSWER_SMS
            ));
            CommunicationQueuesDAO.newInstance().insertRecords(commQueues, false, AccessLevel.SYSTEM_MODE);
        }
    }

    @isTest
    private static void executeBatchTest() {
        Id batchableId;
        System.runAs(TestDataFactoryUser.selectUserSystemAdministrator) {
            Test.startTest();
            DomesticNoAnswerSMSBatch batchable = new DomesticNoAnswerSMSBatch();
            batchableId = Database.executeBatch(batchable);            
            Test.stopTest();
        }

        System.assert(
            batchableId != null,
            'The batch job failed to execute.'
        );
    }
}