src/core-crm/objects/Communication_Queue__c/Communication_Queue__c.object-meta.xml
<CustomObject>
    <label>Communication Queue</label>
    <nameField>
        <displayFormat>CQ-{00000000}</displayFormat>
        <label>Communication Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Communication_Queue__c/fields/Business_Process__c.field-meta.xml
<CustomField>
    <fullName>Business_Process__c</fullName>
    <description>The Business process and Communication Type</description>
    <label>Business Process</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic Automated Cadence Email</fullName>
            </value>
            <value>
                <fullName>International Automated Cadence Email</fullName>
            </value>
            <value>
                <fullName>International Automated Cadence SMS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Communication_Queue__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The content of the message to be sent.</description>
    <label>Message</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

src/core-crm/objects/Communication_Queue__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <description>Mobile Number that the SMS will be sent to for the related contact or lead</description>
    <label>Mobile</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Communication_Queue__c/fields/Retry_Count__c.field-meta.xml
<CustomField>
    <fullName>Retry_Count__c</fullName>
    <label>Retry Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Communication_Queue__c/fields/Sender__c.field-meta.xml
<CustomField>
    <fullName>Sender__c</fullName>
    <label>Sender</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Communication_Queue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Retry Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Communication_Queue__c/fields/WhoId__c.field-meta.xml
<CustomField>
    <fullName>WhoId__c</fullName>
    <label>Who Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Communication_Queue_Configuration__mdt/Communication_Queue_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>To set a maximum retry on the email</description>
    <label>Communication Queue Configuration</label>
    <pluralLabel>Communication Queue Configurations</pluralLabel>
</CustomObject>

src/core-crm/objects/Communication_Queue_Configuration__mdt/fields/SMS_Messaging_Channel__c.field-meta.xml
<CustomField>
    <fullName>SMS_Messaging_Channel__c</fullName>
    <label>SMS Messaging Channel</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Communication_Queue_Configuration__mdt/fields/SMS_Retry_Count__c.field-meta.xml
<CustomField>
    <fullName>SMS_Retry_Count__c</fullName>
    <label>SMS Retry Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Communication_Queue_Configuration__mdt/fields/SMS_Send_Hours_End__c.field-meta.xml
<CustomField>
    <fullName>SMS_Send_Hours_End__c</fullName>
    <label>SMS Send Hours End</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Communication_Queue_Configuration__mdt/fields/SMS_Send_Hours_Start__c.field-meta.xml
<CustomField>
    <fullName>SMS_Send_Hours_Start__c</fullName>
    <label>SMS Send Hours Start</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Communication_Queue_Configuration__mdt/fields/Supress_SMS__c.field-meta.xml
<CustomField>
    <fullName>Supress_SMS__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When the field is set to truth, the processing of the queue records for SMS should NOT HAPPEN. In that case, the batch job should ignore the execution of all the SMS sending.</description>
    <label>Supress SMS</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Task/recordTypes/Nurture.recordType-meta.xml
<RecordType>
    <fullName>Nurture</fullName>
    <active>true</active>
    <label>Nurture</label>
</RecordType>

src/core-crm/objects/Task/recordTypes/SMS.recordType-meta.xml
<RecordType>
    <fullName>SMS</fullName>
    <active>true</active>
    <label>SMS</label>
</RecordType>

src/core-crm/classes/SalesCadenceSMSRequestCommand.cls
/**
 * @description Command Class for SMS Request
 * 
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary                                    |
      |--------------------------------|-----------------------|------------------------|---------------------------------------------------|
      | mark.j.mahilum                 | October 25, 2023      | DEPP-6985              | Created file                                      |
 */
public with sharing class SalesCadenceSMSRequestCommand implements IRequestCommand{
    
    private List<Communication_Queue__c> communicationQueueList;
    private static final String SMS_SUBJECT = 'Nurture Track SMS';
    private static final String NO_ANSWER_SMS_SUBJECT = 'Service Appt No Answer SMS';

    public SalesCadenceSMSRequestCommand(List<Communication_Queue__c> communicationQueueList) {
        this.communicationQueueList = communicationQueueList;
    }      

    public void execute() {
        		
        if(stopSendingSMS()){
            Logger.info('SalesCadenceSMSRequest Stop SMS Sending ');
            return;
        }
        
        Set<Id> failedCommsQueueIds = new Set<Id>();
        
        for(Communication_Queue__c commsQueue : communicationQueueList){
            Map<String, Object> flowParameters = new Map<String, Object>();
            flowParameters.put('CommunicationQueueRecordId',commsQueue.Id);
            flowParameters.put('MessagingChannel',getCommsQueueConfig().SMS_Messaging_Channel__c);
            flowParameters.put('MobilePhoneNumber',commsQueue.Mobile__c);
            flowParameters.put('RecipientRecordID',commsQueue.WhoId__c);
            
            String flowResult = callFlow('Communication_Queue_Send_SMS',flowParameters);
            
            if(flowResult =='Success'){
                Logger.info('Sucess FlowResult ' + flowResult);
            }else{
                Logger.info('Failed FlowResult ' + flowResult);
                failedCommsQueueIds.add(commsQueue.Id);
            }
        }

        List<Communication_Queue__c> commsQueueListToUpdate = setupCommunicationQueueListToUpdate(communicationQueueList, failedCommsQueueIds);
        CommunicationQueuesDAO.newInstance().updateRecords(commsQueueListToUpdate, false, AccessLevel.SYSTEM_MODE);
        createTaskRecords(commsQueueListToUpdate);

    }    
    
    /**
     * Sets the record status of communication queue list to update
     */
    private static List<Communication_Queue__c> setupCommunicationQueueListToUpdate(List<Communication_Queue__c> commsQueueMapValues, Set<Id> failedCommsQueueIds){
        List<Communication_Queue__c> commsQueueListToUpdate = new List<Communication_Queue__c>();
        for(Communication_Queue__c commsQueue : commsQueueMapValues){
            commsQueue.Status__c = CommunicationQueuesDAO.STATUS_FAILED;
            
            if(!failedCommsQueueIds.contains(commsQueue.Id)){
                commsQueue.Status__c = CommunicationQueuesDAO.STATUS_SENT; 

            }else if(commsQueue.Retry_Count__c == null || commsQueue.Retry_Count__c < getCommsQueueConfig().SMS_Retry_Count__c){
                commsQueue.Retry_Count__c = commsQueue.Retry_Count__c == null ? 1 : commsQueue.Retry_Count__c + 1;
                commsQueue.Status__c = CommunicationQueuesDAO.STATUS_RETRY;

            }
            commsQueueListToUpdate.add(commsQueue);
        }
        return commsQueueListToUpdate;
    }

    /**
     * Retrieves Max Retry from Communication Queue Config Metadata
     */
    private static Communication_Queue_Configuration__mdt getCommsQueueConfig(){
        Communication_Queue_Configuration__mdt commQueueMetadata;        
		commQueueMetadata = Communication_Queue_Configuration__mdt.getInstance('Sales_Cadence');
        return commQueueMetadata; 
    }
    
    /**
     * call flow and get the return value
     */    
    private static String callFlow(String flowName, Map <String, Object> flowParameters) {
        if(Test.isRunningTest()){
            return '';
        }
		Flow.Interview smsFlow = Flow.Interview.createInterview(flowName, flowParameters);
        smsFlow.start();
        return (String) smsFlow?.getVariableValue('FlowResult');
    }
    
    /**
     * check if SMS needs to be stop sending
     */     
    private static Boolean stopSendingSMS() {        
        Integer startHour = (Integer) getCommsQueueConfig().SMS_Send_Hours_Start__c;
        Integer endHour = (Integer) getCommsQueueConfig().SMS_Send_Hours_End__c;
        Time currentTime = DateTime.now().time();
        Time startTime = Time.newInstance(startHour, 0, 0, 0);
        Time endTime = Time.newInstance(endHour, 0, 0, 0);
        
        if(Test.isRunningTest()){
            return false;
        }
        
        return getCommsQueueConfig().Supress_SMS__c || !(currentTime >= startTime && currentTime <= endTime);
    }

   /**
    * create Tasks for SMS
    */    
    private static void createTaskRecords(List<Communication_Queue__c> commsQueueListToUpdate ) {
        
        List<Task> insertTaskRecords = new List<Task>();   
        Id userId = UserInfo.getUserId();
        String senderNumber = getCommsQueueConfig().SMS_Messaging_Channel__c;
        senderNumber = senderNumber?.replace('TEXT_AU_', '');  

        for(Communication_Queue__c commsQueue : commsQueueListToUpdate){    
            if(commsQueue.Status__c == 'Retry Scheduled') {
                continue;
            }
            if(commsQueue.Business_Process__c == CommunicationQueuesDAO.BUSINESS_PROCESS_DOMESTIC_NO_ANSWER_SMS) {
                insertTaskRecords.add(
                    new Task(
                        Subject = NO_ANSWER_SMS_SUBJECT,
                        OwnerId = userId,
                        SMS_Outcome__c = commsQueue.Status__c,
                        Status = 'Completed',
                        WhoId = commsQueue.WhoId__c,
                        RecordTypeId = TasksDAO.SMS_RECTYPE_ID,
                        Message_Content__c =  commsQueue.Message__c,
                        ActivityDate = System.today(),
                        Sender__c = senderNumber,
                        Receiver__c = commsQueue.Mobile__c,
                        Priority = 'Normal'
                    )
                );
            } else {
                insertTaskRecords.add(
                    new Task(
                        Subject = SMS_SUBJECT,
                        OwnerId = userId,
                        SMS_Outcome__c = commsQueue.Status__c,
                        Status = 'Completed',
                        WhoId = commsQueue.WhoId__c,
                        RecordTypeId = TasksDAO.SMS_RECTYPE_ID,
                        Message_Content__c =  commsQueue.Message__c,
                        ActivityDate = System.today(),
                        Sender__c = senderNumber,
                        Receiver__c = commsQueue.Mobile__c,
                        Priority = 'Normal'
                    )
                );
            }
        }
        
        if(!insertTaskRecords.isEmpty()){
            TasksDAO.newInstance().insertRecords(insertTaskRecords, false, AccessLevel.SYSTEM_MODE);  
        }
    }
}