src/core-crm/objects/Completed_Cadence__c/Completed_Cadence__c.object-meta.xml
<CustomObject>
    <label>Completed Cadence</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Completed Cadence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Completed Cadences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/Course_Connection_Assessment__c/Course_Connection_Assessment__c.object-meta.xml
<CustomObject>
    <description>Contains the relationship between an assessment and course connection.</description>
    <label>Course Connection Assessment</label>
    <nameField>
        <displayFormat>CCA-{000000}</displayFormat>
        <label>Course Connection Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Connection Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Course_Connection_Assessment__c/fields/Course_Connection__c.field-meta.xml
<CustomField>
    <fullName>Course_Connection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The unit enrollment the assessment is associated to</description>
    <label>Course Connection</label>
    <referenceTo>hed__Course_Enrollment__c</referenceTo>
    <relationshipLabel>Course Connection Assessments</relationshipLabel>
    <relationshipName>Course_Connection_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Engagement_List_Criteria__c/Engagement_List_Criteria__c.object-meta.xml
<CustomObject>
    <description>Contains the entry or exit criteria or ad hoc import information for an engagement list configuration.</description>
    <label>Engagement List Criteria</label>
    <nameField>
        <label>Engagement List Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement List Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/Engagement_List_Criteria__c/fields/Academic_Status__c.field-meta.xml
<CustomField>
    <fullName>Academic_Status__c</fullName>
    <description>The academic status of the student to include in the criteria</description>
    <label>Academic Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Academic_Status</valueSetName>
    </valueSet>
</CustomField>

src/core-crm/objects/Engagement_List_Criteria__c/fields/Completed_Cadence__c.field-meta.xml
<CustomField>
    <fullName>Completed_Cadence__c</fullName>
    <description>Completed cadence that engagement list criteria follows</description>
    <label>Completed Cadence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic Accepted</fullName>
            </value>
            <value>
                <fullName>Admitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Engagement_List_Criteria__c/fields/Has_Domestic_Phone__c.field-meta.xml
<CustomField>
    <fullName>Has_Domestic_Phone__c</fullName>
    <description>Whether the mobile phone number is populated with phone local set to Australia</description>
    <label>Has Domestic Phone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Engagement_List_Criteria__c/fields/Key_Date__c.field-meta.xml
<CustomField>
    <fullName>Key_Date__c</fullName>
    <description>The name of the key date field used to offset from to define a time period</description>
    <label>Key Date</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enrollment Date</fullName>
            </value>
            <value>
                <fullName>Leave Of Absence End Date</fullName>
            </value>
            <value>
                <fullName>Completed Cadence Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Engagement_List_Criteria__c/fields/Previous_Academic_Status__c.field-meta.xml
<CustomField>
    <fullName>Previous_Academic_Status__c</fullName>
    <description>The previous academic status of the student to include in the criteria</description>
    <label>Previous Academic Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Academic_Status</valueSetName>
    </valueSet>
</CustomField>

src/core-crm/objects/Engagement_List_Event__c/Engagement_List_Event__c.object-meta.xml
<CustomObject>
    <description>Contains a list of events that show the criteria in which a case was created based on the related Engagement List Criteria.</description>
    <label>Engagement List Event</label>
    <nameField>
        <displayFormat>ELE-{000000}</displayFormat>
        <label>Engagement List Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement List Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/Engagement_List_Event__c/fields/Academic_Status__c.field-meta.xml
<CustomField>
    <fullName>Academic_Status__c</fullName>
    <description>The Academic Status of the student at the time of the event</description>
    <label>Academic Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Academic_Status</valueSetName>
    </valueSet>
</CustomField>

src/core-crm/objects/Engagement_List_Event__c/fields/Completed_Cadence__c.field-meta.xml
<CustomField>
    <fullName>Completed_Cadence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Cadence that generated the event</description>
    <label>Completed Cadence</label>
    <referenceTo>Completed_Cadence__c</referenceTo>
    <relationshipLabel>Engagement List Events</relationshipLabel>
    <relationshipName>Engagement_List_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Engagement_List_Event__c/fields/Course_Connection__c.field-meta.xml
<CustomField>
    <fullName>Course_Connection__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Course Connection record related to the event</description>
    <label>Course Connection</label>
    <referenceTo>hed__Course_Enrollment__c</referenceTo>
    <relationshipLabel>Engagement List Events</relationshipLabel>
    <relationshipName>Engagement_List_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Engagement_List_Event__c/fields/Course_Connection_Assessment__c.field-meta.xml
<CustomField>
    <fullName>Course_Connection_Assessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Course Connection Assessment record related to event</description>
    <label>Course Connection Assessment</label>
    <referenceTo>Course_Connection_Assessment__c</referenceTo>
    <relationshipLabel>Engagement List Events</relationshipLabel>
    <relationshipName>Engagement_List_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Engagement_List_Event__c/fields/Course_Enrollment_Status__c.field-meta.xml
<CustomField>
    <fullName>Course_Enrollment_Status__c</fullName>
    <description>The Course Enrollment Status at the time of the event</description>
    <label>Course Enrollment Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Engagement_List_Event__c/fields/Engagement_List_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Engagement_List_Criteria__c</fullName>
    <description>The Engagement List Criteria that generated the event</description>
    <label>Engagement List Criteria</label>
    <referenceTo>Engagement_List_Criteria__c</referenceTo>
    <relationshipLabel>Engagement List Events</relationshipLabel>
    <relationshipName>Engagement_List_Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/core-crm/objects/Engagement_List_Event__c/fields/Has_Domestic_Phone__c.field-meta.xml
<CustomField>
    <fullName>Has_Domestic_Phone__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicating that at the time of the event, the student had a domestic mobile number populated</description>
    <label>Has Domestic Phone</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Engagement_List_Event__c/fields/Key_Date__c.field-meta.xml
<CustomField>
    <fullName>Key_Date__c</fullName>
    <description>The date and time of the key date</description>
    <label>Key Date</label>
    <type>DateTime</type>
</CustomField>

src/core-crm/objects/Engagement_List_Event__c/fields/Leave_of_Absence__c.field-meta.xml
<CustomField>
    <fullName>Leave_of_Absence__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Leave of Absence related to the event</description>
    <label>Leave of Absence</label>
    <referenceTo>Leave_of_Absence__c</referenceTo>
    <relationshipLabel>Engagement List Events</relationshipLabel>
    <relationshipName>Engagement_List_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Engagement_List_Event__c/fields/Previous_Academic_Status__c.field-meta.xml
<CustomField>
    <fullName>Previous_Academic_Status__c</fullName>
    <description>The previous academic status of the student at the time of the event</description>
    <label>Previous Academic Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Academic_Status</valueSetName>
    </valueSet>
</CustomField>

src/core-crm/objects/Engagement_List_Event__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment record related to the event</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Engagement List Events</relationshipLabel>
    <relationshipName>Engagement_List_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Engagement_List_Event__c/fields/Program_Enrollment_Breach__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment_Breach__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Program Enrollment Breach record related to the event</description>
    <label>Program Enrollment Breach</label>
    <referenceTo>Program_Enrollment_Breach__c</referenceTo>
    <relationshipLabel>Engagement List Events</relationshipLabel>
    <relationshipName>Engagement_List_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Engagement_List_Event__c/fields/Program_Enrollment_Status__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment_Status__c</fullName>
    <description>The Program Enrollment status at the time of the event</description>
    <label>Program Enrollment Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/hed__Course_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Represents a connection to a Course Offering.</description>
    <label>Course Connection</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Course Connection ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Enrollment__c/fields/hed__Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>hed__Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For students, their primary Program Enrollment. In Higher Ed, this typically represents a student&apos;s academic major.</description>
    <inlineHelpText>For students, their primary Program Enrollment. In Higher Ed, this typically represents a student&apos;s academic major.</inlineHelpText>
    <label>Program Enrollment ID</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Course Connections</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Program_Enrollment__c/hed__Program_Enrollment__c.object-meta.xml
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Program_Enrollment__c/fields/Academic_Status__c.field-meta.xml
<CustomField>
    <fullName>Academic_Status__c</fullName>
    <description>The student’s current academic status</description>
    <label>Academic Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Academic_Status</valueSetName>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Program_Enrollment__c/fields/Previous_Academic_Status__c.field-meta.xml
<CustomField>
    <fullName>Previous_Academic_Status__c</fullName>
    <description>The student’s previous academic status</description>
    <label>Previous Academic Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Academic_Status</valueSetName>
    </valueSet>
</CustomField>

src/core-crm/objects/Leave_of_Absence__c/Leave_of_Absence__c.object-meta.xml
<CustomObject>
    <label>Leave of Absence</label>
    <nameField>
        <displayFormat>LOA-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave of Absences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Program_Enrollment_Breach__c/Program_Enrollment_Breach__c.object-meta.xml
<CustomObject>
    <description>Contains a list of student breaches, i.e. relationship between a breach and a contact.</description>
    <label>Program Enrollment Breach</label>
    <nameField>
        <displayFormat>PEB-{00000}</displayFormat>
        <label>Program Enrollment Breach Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollment Breaches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Program_Enrollment_Breach__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The program in breach</description>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Program Enrollment Breaches</relationshipLabel>
    <relationshipName>Program_Enrollment_Breaches</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/globalValueSets/Academic_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Excluded</fullName>
    </customValue>
    <customValue>
        <fullName>Under consideration</fullName>
    </customValue>
    <customValue>
        <fullName>Intern&apos;l Exclusion</fullName>
    </customValue>
    <customValue>
        <fullName>Conditional</fullName>
    </customValue>
    <customValue>
        <fullName>Good Standing</fullName>
    </customValue>
    <customValue>
        <fullName>Showcause</fullName>
    </customValue>
    <customValue>
        <fullName>Probation</fullName>
    </customValue>
    <customValue>
        <fullName>At Risk</fullName>
    </customValue>
    <customValue>
        <fullName>Probation Conversion</fullName>
    </customValue>
    <customValue>
        <fullName>Held Show cause</fullName>
    </customValue>
    <customValue>
        <fullName>Intern&apos;l Ext Appeal</fullName>
    </customValue>
    <description>The student’s current academic status</description>
    <masterLabel>Academic Status</masterLabel>
</GlobalValueSet>

src/core-crm/classes/EngagementListEventKeyTest.cls
/**
 * @description Test Class for EngagementListEventKey
 * 
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | eccarius.munoz                 |  May 15, 2024         | DEPP-8484              | Created file                 |
 */
@isTest
public with sharing class EngagementListEventKeyTest {
    
    @testSetup
    static void testSetup() {
        TestDataFactoryUser.generateUserQUTESB();
    }

    @isTest
    static void equalsTest() {
        Test.startTest();
        System.runAs(TestDataFactoryUser.selectUserQUTESB) {

            Id contactId = new MockIdGenerator(Contact.SObjectType).getMockId();
            Id criteriaId = new MockIdGenerator(Engagement_List_Criteria__c.SObjectType).getMockId();
            Id programEnrollmentId = new MockIdGenerator(hed__Program_Enrollment__c.SObjectType).getMockId();
            Id completedCadenceId = new MockIdGenerator(Completed_Cadence__c.SObjectType).getMockId();
            Id courseConnectionId = new MockIdGenerator(hed__Course_Enrollment__c.SObjectType).getMockId();
            Id courseConnectionAssessmentId = new MockIdGenerator(Course_Connection_Assessment__c.SObjectType).getMockId();
            Id programEnrollmentBreachId = new MockIdGenerator(Program_Enrollment_Breach__c.SObjectType).getMockId();
            Id leaveOfAbsenceId = new MockIdGenerator(Leave_of_Absence__c.SObjectType).getMockId();
            Date keyDate = Date.today();
            
            Engagement_List_Event__c eventCandidate = new Engagement_List_Event__c();
            eventCandidate.Program_Enrollment__c = programEnrollmentId;
            eventCandidate.Completed_Cadence__c = completedCadenceId;
            eventCandidate.Course_Connection__c = courseConnectionId;
            eventCandidate.Course_Connection_Assessment__c = courseConnectionAssessmentId;
            eventCandidate.Program_Enrollment_Breach__c = programEnrollmentBreachId;
            eventCandidate.Leave_of_Absence__c = leaveOfAbsenceId;
            eventCandidate.Academic_Status__c = 'Showcause';
            eventCandidate.Previous_Academic_Status__c = 'Showcause';
            eventCandidate.Course_Enrollment_Status__c = 'Enrolled';
            eventCandidate.Key_Date__c = keyDate;
            eventCandidate.Program_Enrollment_Status__c = 'Active';
            eventCandidate.Has_Domestic_Phone__c = true;
            EngagementListEventKey eventCandidateKey = new EngagementListEventKey(eventCandidate, contactId, criteriaId);
            
            Engagement_List_Event__c existingEvent = new Engagement_List_Event__c();
            existingEvent.Program_Enrollment__c = programEnrollmentId;
            existingEvent.Completed_Cadence__c = completedCadenceId;
            existingEvent.Course_Connection__c = courseConnectionId;
            existingEvent.Course_Connection_Assessment__c = courseConnectionAssessmentId;
            existingEvent.Program_Enrollment_Breach__c = programEnrollmentBreachId;
            existingEvent.Leave_of_Absence__c = leaveOfAbsenceId;
            existingEvent.Academic_Status__c = 'Showcause';
            existingEvent.Previous_Academic_Status__c = 'Showcause';
            existingEvent.Course_Enrollment_Status__c = 'Enrolled';
            existingEvent.Key_Date__c = keyDate;
            existingEvent.Program_Enrollment_Status__c = 'Active';
            existingEvent.Has_Domestic_Phone__c = true;
            EngagementListEventKey existingEventKey = new EngagementListEventKey(existingEvent, contactId, criteriaId);

            System.assert(eventCandidateKey.equals(existingEventKey), 'Event Candidate Key must be equal to Existing Event Key.');
        }    

        Test.stopTest();
    }

    @isTest
    static void notEqualsTest() {
        Test.startTest();
        System.runAs(TestDataFactoryUser.selectUserQUTESB) {

            Id contactId = new MockIdGenerator(Contact.SObjectType).getMockId();
            Id criteriaId = new MockIdGenerator(Engagement_List_Criteria__c.SObjectType).getMockId();
            Id programEnrollmentId = new MockIdGenerator(hed__Program_Enrollment__c.SObjectType).getMockId();
            Date keyDate = Date.today();
            
            Engagement_List_Event__c eventCandidate = new Engagement_List_Event__c();
            eventCandidate.Program_Enrollment__c = programEnrollmentId;
            eventCandidate.Course_Enrollment_Status__c = 'Enrolled';
            eventCandidate.Key_Date__c = keyDate;
            eventCandidate.Program_Enrollment_Status__c = 'Active';
            EngagementListEventKey eventCandidateKey = new EngagementListEventKey(eventCandidate, contactId, criteriaId);
            
            Engagement_List_Event__c existingEvent = new Engagement_List_Event__c();
            existingEvent.Program_Enrollment__c = new MockIdGenerator(hed__Program_Enrollment__c.SObjectType).getMockId();
            existingEvent.Course_Enrollment_Status__c = 'Enrolled';
            existingEvent.Key_Date__c = keyDate;
            existingEvent.Program_Enrollment_Status__c = 'Test';
            existingEvent.Has_Domestic_Phone__c = true;
            EngagementListEventKey existingEventKey = new EngagementListEventKey(existingEvent, contactId, criteriaId);

            System.assert(!eventCandidateKey.equals(existingEventKey), 'Event Candidate Key must not be equal to Existing Event Key.');
        }    
         
        Test.stopTest();
    }

    @isTest
    static void testHashCode() {
        Test.startTest();
        System.runAs(TestDataFactoryUser.selectUserQUTESB) {

            Id contactId = new MockIdGenerator(Contact.SObjectType).getMockId();
            Id criteriaId = new MockIdGenerator(Engagement_List_Criteria__c.SObjectType).getMockId();

            Engagement_List_Event__c eventCandidate = new Engagement_List_Event__c();
            eventCandidate.Program_Enrollment_Status__c = 'Active';
            eventCandidate.Has_Domestic_Phone__c = true;

            EngagementListEventKey eventKey = new EngagementListEventKey(eventCandidate, contactId, criteriaId);
            Integer hashCode = eventKey.hashCode();       
            
            System.assert(hashCode!=null, 'Hash code should not be null.');
        }
    }
}