src/core-crm/objects/Completed_Cadence__c/Completed_Cadence__c.object-meta.xml
<CustomObject>
    <label>Completed Cadence</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Completed Cadence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Completed Cadences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/Engagement_List_Criteria__c/Engagement_List_Criteria__c.object-meta.xml
<CustomObject>
    <description>Contains the entry or exit criteria or ad hoc import information for an engagement list configuration.</description>
    <label>Engagement List Criteria</label>
    <nameField>
        <label>Engagement List Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement List Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/Engagement_List_Criteria__c/fields/Completed_Cadence__c.field-meta.xml
<CustomField>
    <fullName>Completed_Cadence__c</fullName>
    <description>Completed cadence that engagement list criteria follows</description>
    <label>Completed Cadence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic Accepted</fullName>
            </value>
            <value>
                <fullName>Admitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Engagement_List_Criteria__c/fields/Key_Date__c.field-meta.xml
<CustomField>
    <fullName>Key_Date__c</fullName>
    <description>The name of the key date field used to offset from to define a time period</description>
    <label>Key Date</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enrollment Date</fullName>
            </value>
            <value>
                <fullName>Leave Of Absence End Date</fullName>
            </value>
            <value>
                <fullName>Completed Cadence Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Engagement_List_Criteria__c/fields/Key_Date_Offset_Lower_Boundary__c.field-meta.xml
<CustomField>
    <fullName>Key_Date_Offset_Lower_Boundary__c</fullName>
    <description>The number of days to offset from key date field. Positive numbers indicate days after while the negative indicate days prior to date in Key date field.</description>
    <label>Key Date Offset Lower Boundary</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Engagement_List_Criteria__c/fields/Key_Date_Offset_Upper_Boundary__c.field-meta.xml
<CustomField>
    <fullName>Key_Date_Offset_Upper_Boundary__c</fullName>
    <description>The number of days to offset from key date field. Positive numbers indicate days after while the negative indicate days prior to date in Key date field.</description>
    <label>Key Date Offset Upper Boundary</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/classes/ELCCompletedCadenceParserTest.cls
/**
 * @description Test class for ELCCompletedCadenceParser
 * @ELCCompletedCadenceParser
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | eccarius.munoz                 | May 2, 2024           | DEPP-7528              | Created file                 |
 */
@isTest
public with sharing class ELCCompletedCadenceParserTest {

    @TestSetup
    static void setupMethod(){
        TestDataFactory.generateTestUsers(new List<String>{ 'QUT_ESB' });
    }

    @isTest
    static void parseCompletedCadenceTest() {
        System.runAs(TestDataFactory.getESBIntegrationUser()) {            
            
            Test.startTest();
            String completedCadenceName = 'Domestic Accepted and Admitted';
            Date executionDate = Date.today();
            Engagement_List_Criteria__c engagementListCriteria = new Engagement_List_Criteria__c();
            engagementListCriteria.Completed_Cadence__c = completedCadenceName;
            
            ELCCompletedCadenceParser parser = new ELCCompletedCadenceParser(engagementListCriteria, executionDate);
            Test.stopTest();

            System.assertEquals(parser.getCompletedCadenceCriteria().getCompletedCadence(), completedCadenceName, 'Incorrect Completed Cadence');
            System.assertEquals(parser.getCompletedCadenceCriteria().getStatus(), CompletedCadencesDAO.SUCCESSFUL_STATUS, 'Status should be set to Succesful'); 
        }
    }

    @isTest
    static void parseNoCompletedCadenceCriteriaTest() {
        System.runAs(TestDataFactory.getESBIntegrationUser()) {

            Test.startTest();
            ELCCompletedCadenceParser parser = new ELCCompletedCadenceParser(new Engagement_List_Criteria__c(), Date.today());
            Test.stopTest();

            System.assert(parser.getCompletedCadenceCriteria().isEmpty(), 'No Criteria should be parsed.'); 
        }
    }

    @isTest
    static void parseprocessKeyDateOffsetsTest() {
        System.runAs(TestDataFactory.getESBIntegrationUser()) {
            Date executionDate = Date.today();
            Date execDateLower = executionDate.addDays(-10);
            Date execDateUpper = executionDate.addDays(10);

            Test.startTest();
            Engagement_List_Criteria__c engagementListCriteria = new Engagement_List_Criteria__c();
            engagementListCriteria.Key_Date__c = 'Completed Cadence Date';
            engagementListCriteria.Key_Date_Offset_Lower_Boundary__c = -10;
            engagementListCriteria.Key_Date_Offset_Upper_Boundary__c = 10;

            ELCCompletedCadenceParser parser = new ELCCompletedCadenceParser(engagementListCriteria, executionDate);
            Test.stopTest();

            System.assertEquals(execDateLower, parser.getCompletedCadenceCriteria().getCompletedCadanceDateFrom(), 'Incorrect Key Date Offset Lower');
            System.assertEquals(execDateUpper, parser.getCompletedCadenceCriteria().getCompletedCadanceDateTo(), 'Incorrect Key Date Offset Upper');
        }
    }
}