src/core-crm/objects/Completed_Cadence__c/Completed_Cadence__c.object-meta.xml
<CustomObject>
    <label>Completed Cadence</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Completed Cadence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Completed Cadences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/Completed_Cadence__c/fields/Cadence_Name__c.field-meta.xml
<CustomField>
    <fullName>Cadence_Name__c</fullName>
    <formula>Nurture_Track_Configuration__r.Cadence_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cadence Name</label>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Completed_Cadence__c/fields/Calculated_Cadence__c.field-meta.xml
<CustomField>
    <fullName>Calculated_Cadence__c</fullName>
    <formula>IF( NOT( ISBLANK( Contact__c ) )  ,  Contact__r.Calculated_Cadence__c  ,  Lead__r.Calculated_Cadence__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calculated Cadence</label>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Completed_Cadence__c/fields/Completed_Cadence_Status__c.field-meta.xml
<CustomField>
    <fullName>Completed_Cadence_Status__c</fullName>
    <label>Completed Cadence Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Completed_Cadence__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Completed Cadences</relationshipLabel>
    <relationshipName>Completed_Cadences</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Completed_Cadence__c/fields/Nurture_Track_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Nurture_Track_Configuration__c</fullName>
    <label>Nurture Track Configuration</label>
    <referenceTo>Nurture_Track_Configuration__c</referenceTo>
    <relationshipLabel>Completed Cadences</relationshipLabel>
    <relationshipName>Completed_Cadences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/core-crm/objects/Lead/fields/Lead_Source_Category__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Category__c</fullName>
    <description>Indicates the original lead source channel category for the Lead Source Channel that a Marketing Person interacted with/via.</description>
    <label>Lead Source Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Source_Category</valueSetName>
    </valueSet>
</CustomField>

src/core-crm/objects/Lead/fields/Marketing_Segmentation__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Segmentation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Segmentation</label>
    <referenceTo>Marketing_Segmentation__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Lead/fields/Work_Email__c.field-meta.xml
<CustomField>
    <fullName>Work_Email__c</fullName>
    <inlineHelpText>This field captures the work email of the contact.</inlineHelpText>
    <label>Work Email</label>
    <type>Email</type>
</CustomField>

src/core-crm/objects/Marketing_Segmentation__c/Marketing_Segmentation__c.object-meta.xml
<CustomObject>
    <label>Marketing Segmentation</label>
    <nameField>
        <displayFormat>MS - {000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Segmentations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Marketing_Segmentation__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Marketing Segmentations</relationshipLabel>
    <relationshipName>Marketing_Segmentations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Nurture_Track_Configuration__c/Nurture_Track_Configuration__c.object-meta.xml
<CustomObject>
    <label>Nurture Track Configuration</label>
    <nameField>
        <displayFormat>NTC-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nurture Track Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Nurture_Track_Configuration__c/fields/Cadence_Name__c.field-meta.xml
<CustomField>
    <fullName>Cadence_Name__c</fullName>
    <description>The Name of the Cadence the Configuration is for</description>
    <label>Cadence Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Nurture_Track_Configuration__c/fields/Lead_Score_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Lead_Score_Threshold__c</fullName>
    <description>The Lead Score Threshold for inclusion in the Track

Note: This value needs to be replicated to all cadences in the track</description>
    <label>Lead Score Threshold</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Nurture_Track_Configuration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Cadence Status is used to activate or deactivate the cadence</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/globalValueSets/Lead_Source_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Event</fullName>
    </customValue>
    <customValue>
        <fullName>Lead Ad</fullName>
    </customValue>
    <customValue>
        <fullName>Web Form</fullName>
        <label>Online Interaction</label>
    </customValue>
    <customValue>
        <fullName>Outreach Activity</fullName>
        <label>Engagement/Partnership</label>
    </customValue>
    <customValue>
        <fullName>Referral Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Partner Sourced</fullName>
    </customValue>
    <customValue>
        <fullName>Strategic Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Study Application</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <description>Indicates the original lead source channel category for the Lead Source Channel that a Marketing Person interacted with/via.</description>
    <masterLabel>Lead Source Category</masterLabel>
</GlobalValueSet>

src/core-crm/classes/LeadSourceCanNurtureFlagBatchTest.cls
/**
 * @description Batch class to LeadSourceCanNurtureFlagBatchTest
 * 
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | arsenio.jr.dayrit              | March 06, 2024        | DEPP-8069              | Created file                 |
      |                                |                       |                        |                              |
 */
@isTest
public with sharing class LeadSourceCanNurtureFlagBatchTest {
    private static final String FIRSTNAME = 'TestfirstName';
    private static final String LASTNAME = 'Testlastname';
    private static final String EMAIL = 'testmail@mail.test';
    private static final String BIRTHDAY = '2000-06-28';
    private static Integer recordsCount = 20;
    
    @testSetup
    static void testSetup() {
        TestDataFactory.generateTestUsers(new List<String>{ 'QUT_Program_Administrator' });
        System.runAs(TestDataFactory.getProgramAdminUser()) {           
            
            List<Nurture_Track_Configuration__c> nurtureList = new List<Nurture_Track_Configuration__c>();
            Nurture_Track_Configuration__c nurtureConfig = new Nurture_Track_Configuration__c();
            nurtureConfig.Cadence_Name__c = NurtureTrackConfigurationsDAO.INTERNATIONAL_PRE_APPLICATION_PARTNER_SOURCE_AUTOMATED;
            nurtureConfig.Lead_Score_Threshold__c = 3;
            nurtureConfig.Status__c = 'Active';
            nurtureList.add(nurtureConfig);
            NurtureTrackConfigurationsDAO.newInstance().insertRecords(nurtureList, false, AccessLevel.SYSTEM_MODE);   
        }
    }

    @isTest
    private static void testAutomaticInternationalPreApplicationPartnerSourcedEntry() {
        System.runAs(TestDataFactory.getProgramAdminUser()) {
            // create marketing segmentation
            Marketing_Segmentation__c internationalMS = new Marketing_Segmentation__c(My_Citizenship_Status__c = 'International Student');
            insert internationalMS;
            // create lead
            List<Lead> newLeads = createTestLeadRecords(0, 1);
            newLeads[0].Marketing_Segmentation__c = internationalMS.Id;
            newLeads[0].Lead_Source_Category__c = 'Partner Sourced';
            newLeads[0].Calculated_Cadence__c = NurtureTrackConfigurationsDAO.INTERNATIONAL_PRE_APPLICATION_PARTNER_SOURCE_AUTOMATED;
            LeadsDAO.newInstance().insertRecords(newLeads, false, AccessLevel.SYSTEM_MODE);
            // SOQL the lead so it includes Marketing_Segmentation__r.My_Citizenship_Status__c
            newLeads[0] = [
                SELECT Id, Marketing_Segmentation__r.My_Citizenship_Status__c, 
                Can_Nurture__c, Calculated_Cadence__c 
                FROM Lead LIMIT 1];

            List<Nurture_Track_Configuration__c> nt = [SELECT Id FROM Nurture_Track_Configuration__c LIMIT 1];
            Completed_cadence__c cadence1 = new Completed_Cadence__c();
            cadence1.Lead__c = newLeads[0].Id;
            cadence1.Nurture_Track_Configuration__c = nt[0].Id;
            cadence1.Completed_Cadence_Status__c ='';
            insert cadence1;
            
            Datetime todaysDate = Datetime.now().addYears(-4);
            Test.setCreatedDate(cadence1.Id, todaysDate);

        }
    	Test.startTest();
        // call method
        LeadSourceCanNurtureFlagBatch batchable = new LeadSourceCanNurtureFlagBatch();
        Id batchableId = Database.executeBatch(batchable);
        Test.stopTest();
        // assert
        System.assert(
            batchableId != null,
            'The batch job failed to execute.'
        );
        
         List<Lead> leadList = [SELECT Id,Can_Nurture__c FROM Lead WHERE Lead_Source_Category__c = 'Partner Sourced'];
        System.assert(!leadList[0].Can_Nurture__c,'is can_nurture not false');
    }

    // Test method for exception handling
    @isTest
    static void testExceptionHandling() {
        System.runAs(TestDataFactory.getProgramAdminUser()) {
            Test.startTest();
            // Call the batch class execute method
            NurturingTrackLeadBatch batchable = new NurturingTrackLeadBatch();
            batchable.execute(null,null);
            Test.stopTest();
        }       
        //Perform assertions that the batch didn't execute
        System.assert([SELECT Id FROM AsyncApexJob WHERE ApexClass.Name = 'NurturingTrackLeadBatch'].isEmpty() , 'NurturingTrackLeadBatch Job is not empty');
    }

    
    private static List<Lead> createTestLeadRecords(Integer startAtCount, Integer endBeforeCount) {
        List<Lead> newLeads = new List<Lead>();
        for (Integer i = startAtCount; i < endBeforeCount; i++) {
            newLeads.add(
                new Lead(
                    FirstName = FIRSTNAME,
                    LastName = LASTNAME + i,
                    Email = i + EMAIL,
                    Can_Nurture__c = TRUE,
                    Work_Email__c = 'work' + i + EMAIL,
                    Company = 'Learner' + i
                )
            );
        }
        return newLeads;
    }
}