src/core-crm/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Engagement captures business information about an ‘Engagement’ QUT staff are having with a person or organisation, or a contact at a particular organisation.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Engagement__c/fields/Engagement_Code__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Code__c</fullName>
    <description>A unique, business formatted code to identify an Opportunity record in the system.</description>
    <label>Engagement Code</label>
    <type>AutoNumber</type>
</CustomField>

src/core-crm/objects/Engagement__c/fields/Engagement_Summary__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Summary__c</fullName>
    <description>A summary/description of the Engagement being undertaken.</description>
    <inlineHelpText>A summary/description of the Engagement being undertaken.</inlineHelpText>
    <label>Engagement Summary</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

src/core-crm/objects/Engagement_Code_Auto_Number__c/Engagement_Code_Auto_Number__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Engagement Code Auto Number</label>
</CustomObject>

src/core-crm/objects/Engagement_Code_Auto_Number__c/fields/Commercialisation__c.field-meta.xml
<CustomField>
    <fullName>Commercialisation__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Auto-number used for Commercialisation Engagement records.</description>
    <label>Commercialisation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Engagement_Code_Auto_Number__c/fields/Research_Partnership__c.field-meta.xml
<CustomField>
    <fullName>Research_Partnership__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Auto-number used for Research Partnership Engagement records.</description>
    <label>Research Partnership</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Opportunity/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to associated Engagement.</description>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Opportunity/fields/Opportunity_Code__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Code__c</fullName>
    <description>A unique, business formatted code to identify an Opportunity record in the system.</description>
    <inlineHelpText>System to auto-generate a unique code in the below pattern. The number should increment sequentially starting from 00001.
Where Opportunity Record Type = ‘Research Partnership’ THEN RPO:00001
Where Opportunity Record Type = ‘International Projects Unit’ THEN INPO:00001
Where Opportunity Record Type = ‘Commercialisation&apos; THEN RCO:00001</inlineHelpText>
    <label>Opportunity Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Opportunity_Code_Auto_Number__c/Opportunity_Code_Auto_Number__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom setting contains the auto-numbers used for the Opportunity object&apos;s Opportunity Code.</description>
    <label>Opportunity Code Auto Number</label>
</CustomObject>

src/core-crm/objects/Opportunity_Code_Auto_Number__c/fields/Commercialisation__c.field-meta.xml
<CustomField>
    <fullName>Commercialisation__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Auto-number used for Commercialisation Opportunity records.</description>
    <label>Commercialisation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Opportunity_Code_Auto_Number__c/fields/International_Projects_Unit__c.field-meta.xml
<CustomField>
    <fullName>International_Projects_Unit__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Auto-number used for International Projects Unit Opportunity records.</description>
    <label>International Projects Unit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Opportunity_Code_Auto_Number__c/fields/Research_Partnership__c.field-meta.xml
<CustomField>
    <fullName>Research_Partnership__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Auto-number used for Research Partnership Opportunity records.</description>
    <label>Research Partnership</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Opportunity_Outcome__c/Opportunity_Outcome__c.object-meta.xml
<CustomObject>
    <description>Opportunity Outcome captures the outcome of a given Opportunity. Each Opportunity can have many Opportunity Outcomes.</description>
    <label>Opportunity Outcome</label>
    <nameField>
        <displayFormat>OO-{00000}</displayFormat>
        <label>Opportunity Outcome Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Outcomes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/core-crm/objects/Opportunity_Outcome__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>A unique, business formatted code to identify a Project being managed under an Opportunity Outcome.</description>
    <label>Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Opportunity_Outcome__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <description>The name of the Start-Up Company.</description>
    <inlineHelpText>The name of the Startup Company.</inlineHelpText>
    <label>Company Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Opportunity_Outcome__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to associated Opportunity.</description>
    <inlineHelpText>Lookup to associated Opportunity.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Outcomes</relationshipLabel>
    <relationshipName>Opportunity_Outcomes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Opportunity_Outcome__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <description>The business entered name/title for the Project Opportunity Outcome. The field value has a business defined format.</description>
    <inlineHelpText>Field value to be copied from associated Opportunity, with the exception of the 1st three characters.</inlineHelpText>
    <label>Project Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Opportunity_Outcome_Code_Auto_Number__c/Opportunity_Outcome_Code_Auto_Number__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom setting contains the auto-numbers used for the Opportunity Outcome object&apos;s Code field.</description>
    <label>Opportunity Outcome Code Auto Number</label>
</CustomObject>

src/core-crm/objects/Opportunity_Outcome_Code_Auto_Number__c/fields/IPU_Project__c.field-meta.xml
<CustomField>
    <fullName>IPU_Project__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Auto-number used for IPU Project Opportunity Outcome records.</description>
    <label>IPU Project</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Opportunity_Outcome_Code_Auto_Number__c/fields/Research_Commercialisation_Project__c.field-meta.xml
<CustomField>
    <fullName>Research_Commercialisation_Project__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Auto-number used for Research Commercialisation Project Opportunity Outcome records.</description>
    <label>Research Commercialisation Project</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Opportunity_Outcome_Code_Auto_Number__c/fields/Research_Partnership_Project__c.field-meta.xml
<CustomField>
    <fullName>Research_Partnership_Project__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Auto-number used for Research Partnership Project Opportunity Outcome records.</description>
    <label>Research Partnership Project</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Opportunity_Outcome_Code_Auto_Number__c/fields/Start_Up__c.field-meta.xml
<CustomField>
    <fullName>Start_Up__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Auto-number used for Start-Up Opportunity Outcome records.</description>
    <label>Start-Up</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/classes/CodeGeneratorServiceTest.cls
/**
 * @description Test class for CodeGeneratorService.cls
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | alexander.cadalin              | May 22, 2023          | DEPP-5594              | created file
 */
@isTest
public class CodeGeneratorServiceTest {
	@testSetup
    static void setup() {
        TestDataFactory.generateTestUsers(new List<String>{ 'QUT_IE_Partnership_Manager' });
        Opportunity_Code_Auto_Number__c opptyCodeAutoNum = Opportunity_Code_Auto_Number__c.getOrgDefaults();
        opptyCodeAutoNum.Commercialisation__c = 1;
        opptyCodeAutoNum.International_Projects_Unit__c = 1;
        opptyCodeAutoNum.Research_Partnership__c = 1;
        OpportunityCodeAutoNumbersDAO.newInstance().upsertRecords(
            new List<Opportunity_Code_Auto_Number__c>{opptyCodeAutoNum}, 
            false, 
            AccessLevel.USER_MODE
            );
        Opportunity_Outcome_Code_Auto_Number__c oppOutcomeCodeAutoNum = Opportunity_Outcome_Code_Auto_Number__c.getOrgDefaults();
        oppOutcomeCodeAutoNum.Research_Partnership_Project__c = 1;
        oppOutcomeCodeAutoNum.IPU_Project__c = 1;
        oppOutcomeCodeAutoNum.Research_Commercialisation_Project__c = 1;
        oppOutcomeCodeAutoNum.Start_Up__c = 1;
        OpportunityOutcomeCodeAutoNumbersDAO.newInstance().upsertRecords(
            new List<Opportunity_Outcome_Code_Auto_Number__c>{oppOutcomeCodeAutoNum}, 
            false, 
            AccessLevel.USER_MODE
            );
        Engagement_Code_Auto_Number__c engCodeAutoNum = Engagement_Code_Auto_Number__c.getOrgDefaults();
        engCodeAutoNum.Commercialisation__c = 1;
        engCodeAutoNum.Research_Partnership__c = 1;
        EngagementCodeAutoNumbersDAO.newInstance().upsertRecords(
            new List<Engagement_Code_Auto_Number__c>{engCodeAutoNum}, 
            false, 
            AccessLevel.USER_MODE
            );
    }
    
    /** 
     * TEST START: CodeGeneratorService.generateOpportunityCodeForOpportunityRecords()
     * Various test cases of differing record types and record counts per transaction
     */
    @isTest
    private static void createOpptyRCORecords() {
        System.runAs(TestDataFactory.getQUTIEPartnershipManager()) {
            List<Opportunity> newItems = generateBatchOpportunityRecords(100, 'RCO', OpportunitiesDAO.RT_OPPTY_RCO_ID);
            Test.startTest();
            CodeGeneratorService.generateOpportunityCodeForOpportunityRecords(newItems);
            Opportunity_Code_Auto_Number__c opptyCodeAutoNum = Opportunity_Code_Auto_Number__c.getOrgDefaults();
            Test.stopTest();
            Integer count = 1;
            for(Opportunity newItem : newItems) {
                System.assertEquals(
                    'RCO:' + String.valueOf(count).leftPad(5, '0'),
                    newItem.Opportunity_Code__c,
                    'Incorrect code.');
                count++;
            }
            System.assertEquals(101, opptyCodeAutoNum.Commercialisation__c, 'Incorrect final auto-number value.');
        }
    }
    
    @isTest
    private static void createOpptyINPORecords() {
        System.runAs(TestDataFactory.getQUTIEPartnershipManager()) {
            List<Opportunity> newItems = generateBatchOpportunityRecords(100, 'RCO', OpportunitiesDAO.RT_OPPTY_INPO_ID);
            Test.startTest();
            CodeGeneratorService.generateOpportunityCodeForOpportunityRecords(newItems);
            Opportunity_Code_Auto_Number__c opptyCodeAutoNum = Opportunity_Code_Auto_Number__c.getOrgDefaults();
            Test.stopTest();
            Integer count = 1;
            for(Opportunity newItem : newItems) {
                System.assertEquals(
                    'INPO:' + String.valueOf(count).leftPad(5, '0'),
                    newItem.Opportunity_Code__c,
                    'Incorrect code.');
                count++;
            }
            System.assertEquals(101, opptyCodeAutoNum.International_Projects_Unit__c, 'Incorrect final auto-number value.');
        }
    }

	@isTest
    private static void createOpptyRPORecords() {
        System.runAs(TestDataFactory.getQUTIEPartnershipManager()) {
            List<Opportunity> newItems = generateBatchOpportunityRecords(100, 'RCO', OpportunitiesDAO.RT_OPPTY_RPO_ID);
            Test.startTest();
            CodeGeneratorService.generateOpportunityCodeForOpportunityRecords(newItems);
            Opportunity_Code_Auto_Number__c opptyCodeAutoNum = Opportunity_Code_Auto_Number__c.getOrgDefaults();
            Test.stopTest();
            Integer count = 1;
            for(Opportunity newItem : newItems) {
                System.assertEquals(
                    'RPO:' + String.valueOf(count).leftPad(5, '0'),
                    newItem.Opportunity_Code__c,
                    'Incorrect code.');
                count++;
            }
            System.assertEquals(101, opptyCodeAutoNum.Research_Partnership__c, 'Incorrect final auto-number value.');
        }
    }
    /**
     * TEST STOP: CodeGeneratorService.generateOpportunityCodeForOpportunityRecords()
     */

    /** 
     * TEST START: CodeGeneratorService.generateCodeForOpportunityOutcomeRecords()
     * Various test cases of differing record types and record counts per transaction
     */
    @isTest
    private static void createOpptyOutcRPPORecords() {
        System.runAs(TestDataFactory.getQUTIEPartnershipManager()) {
            List<Opportunity_Outcome__c> newItems = generateBatchOpportunityOutcomeRecords(100, 'RPP', OpportunityOutcomesDAO.RT_OPPTYOC_RPP_ID);
            Test.startTest();
            CodeGeneratorService.generateCodeForOpportunityOutcomeRecords(newItems);
            Opportunity_Outcome_Code_Auto_Number__c opptyOutcCodeAutoNum = Opportunity_Outcome_Code_Auto_Number__c.getOrgDefaults();
            Test.stopTest();
            Integer count = 1;
            for(Opportunity_Outcome__c newItem : newItems) {
                System.assertEquals(
                    'RPP:' + String.valueOf(count).leftPad(5, '0'),
                    newItem.Code__c,
                    'Incorrect code.');
                count++;
            }
            System.assertEquals(101, opptyOutcCodeAutoNum.Research_Partnership_Project__c, 'Incorrect final auto-number value.');
        }
    }

    @isTest
    private static void createOpptyOutcINPRecords() {
        System.runAs(TestDataFactory.getQUTIEPartnershipManager()) {
            List<Opportunity_Outcome__c> newItems = generateBatchOpportunityOutcomeRecords(100, 'INP', OpportunityOutcomesDAO.RT_OPPTYOC_INP_ID);
            Test.startTest();
            CodeGeneratorService.generateCodeForOpportunityOutcomeRecords(newItems);
            Opportunity_Outcome_Code_Auto_Number__c opptyOutcCodeAutoNum = Opportunity_Outcome_Code_Auto_Number__c.getOrgDefaults();
            Test.stopTest();
            Integer count = 1;
            for(Opportunity_Outcome__c newItem : newItems) {
                System.assertEquals(
                    'INP:' + String.valueOf(count).leftPad(5, '0'),
                    newItem.Code__c,
                    'Incorrect code.');
                count++;
            }
            System.assertEquals(101, opptyOutcCodeAutoNum.IPU_Project__c, 'Incorrect final auto-number value.');
        }
    }

    @isTest
    private static void createOpptyOutcRCPRecords() {
        System.runAs(TestDataFactory.getQUTIEPartnershipManager()) {
            List<Opportunity_Outcome__c> newItems = generateBatchOpportunityOutcomeRecords(100, 'RCP', OpportunityOutcomesDAO.RT_OPPTYOC_RCP_ID);
            Test.startTest();
            CodeGeneratorService.generateCodeForOpportunityOutcomeRecords(newItems);
            Opportunity_Outcome_Code_Auto_Number__c opptyOutcCodeAutoNum = Opportunity_Outcome_Code_Auto_Number__c.getOrgDefaults();
            Test.stopTest();
            Integer count = 1;
            for(Opportunity_Outcome__c newItem : newItems) {
                System.assertEquals(
                    'RCP:' + String.valueOf(count).leftPad(5, '0'),
                    newItem.Code__c,
                    'Incorrect code.');
                count++;
            }
            System.assertEquals(101, opptyOutcCodeAutoNum.Research_Commercialisation_Project__c, 'Incorrect final auto-number value.');
        }
    }

    @isTest
    private static void createOpptyOutcRCCRecords() {
        System.runAs(TestDataFactory.getQUTIEPartnershipManager()) {
            List<Opportunity_Outcome__c> newItems = generateBatchOpportunityOutcomeRecords(100, 'RCC', OpportunityOutcomesDAO.RT_OPPTYOC_RCC_ID);
            Test.startTest();
            CodeGeneratorService.generateCodeForOpportunityOutcomeRecords(newItems);
            Opportunity_Outcome_Code_Auto_Number__c opptyOutcCodeAutoNum = Opportunity_Outcome_Code_Auto_Number__c.getOrgDefaults();
            Test.stopTest();
            Integer count = 1;
            for(Opportunity_Outcome__c newItem : newItems) {
                System.assertEquals(
                    'RCC:' + String.valueOf(count).leftPad(5, '0'),
                    newItem.Code__c,
                    'Incorrect code.');
                count++;
            }
            System.assertEquals(101, opptyOutcCodeAutoNum.Start_Up__c, 'Incorrect final auto-number value.');
        }
    }
    /**
     * TEST STOP: CodeGeneratorService.generateCodeForOpportunityOutcomeRecords()
     */
    /** 
     * TEST START: CodeGeneratorService.generateEngagementCodeForEngagementRecords()
     * Various test cases of differing record types and record counts per transaction
     */
    @isTest
    private static void createEngagementRCERecords() {
        System.runAs(TestDataFactory.getQUTIEPartnershipManager()) {
            List<Engagement__c> newItems = generateBatchEngagementRecords(100, 'RCE', EngagementsDAO.RT_ENG_RCE_ID);
            Test.startTest();
            CodeGeneratorService.generateEngagementCodeForEngagementRecords(newItems);
            Engagement_Code_Auto_Number__c engCodeAutoNum = Engagement_Code_Auto_Number__c.getOrgDefaults();
            Test.stopTest();
            Integer count = 1;
            for(Engagement__c newItem : newItems) {
                System.assertEquals(
                    'RCE:' + String.valueOf(count).leftPad(5, '0'),
                    newItem.Engagement_Code__c,
                    'Incorrect code.');
                count++;
            }
            System.assertEquals(101, engCodeAutoNum.Commercialisation__c, 'Incorrect final auto-number value.');
        }
    }

    @isTest
    private static void createEngagementRPERecords() {
        System.runAs(TestDataFactory.getQUTIEPartnershipManager()) {
            List<Engagement__c> newItems = generateBatchEngagementRecords(100, 'RPE', EngagementsDAO.RT_ENG_RPE_ID);
            Test.startTest();
            CodeGeneratorService.generateEngagementCodeForEngagementRecords(newItems);
            Engagement_Code_Auto_Number__c engCodeAutoNum = Engagement_Code_Auto_Number__c.getOrgDefaults();
            Test.stopTest();
            Integer count = 1;
            for(Engagement__c newItem : newItems) {
                System.assertEquals(
                    'RPE:' + String.valueOf(count).leftPad(5, '0'),
                    newItem.Engagement_Code__c,
                    'Incorrect code.');
                count++;
            }
            System.assertEquals(101, engCodeAutoNum.Research_Partnership__c, 'Incorrect final auto-number value.');
        }
    }
    /**
     * TEST STOP: CodeGeneratorService.generateCodeForOpportunityOutcomeRecords()
     */

    /**
     * Generate a list of opportunity records based on the amount of records needed, the general name to be used, and the record type.
     */
    private static List<Opportunity> generateBatchOpportunityRecords(Integer size, String name, Id recordTypeId) {
        List<Opportunity> oppties = new List<Opportunity>();
        for(Integer i = 1; i <= size; i++) {
            oppties.add(
                new Opportunity(
                    Name = name + ' ' + String.valueOf(i), 
                    StageName = 'Qualify', 
                    CloseDate = System.today() + 50, 
                    RecordTypeId = recordTypeId
                )
            );
        }
        return oppties;
    }

    /**
     * Generate a list of opportunity outcome records based on the amount of records needed, the general name to be used, and record type
     */
    private static List<Opportunity_Outcome__c> generateBatchOpportunityOutcomeRecords(Integer size, String name, Id recordTypeId) {
        List<Opportunity> oppty = new List<Opportunity>();
        oppty.add(new Opportunity(
            Name = 'Sample Opportunity ' + System.now(),
            StageName = 'Qualify',
            CloseDate = System.today() + 50
        ));
        OpportunitiesDAO.newInstance().insertRecords(oppty, false, AccessLevel.USER_MODE);
        List<Opportunity_Outcome__c> oppOutcomes = new List<Opportunity_Outcome__c>();
        for(Integer i = 1; i <= size; i++) {
            oppOutcomes.add(
                new Opportunity_Outcome__c(
                    Company_Name__c = 'Sample Company', 
                    Opportunity__c = oppty[0].Id, 
                    Project_Name__c = oppty[0].Name,
                    RecordTypeId = recordTypeId
                )
            );
        }
        return oppOutcomes;
    }

    /**
     * Generate a list of engagement records based on the amount of records needed, summary, and record type
     */
    private static List<Engagement__c> generateBatchEngagementRecords(Integer size, String summary, Id recordTypeId) {
        List<Engagement__c> engs = new List<Engagement__c>();
        for(Integer i = 1; i <= size; i++) {
            engs.add(
                new Engagement__c(Engagement_Summary__c = summary + i, RecordTypeId = recordTypeId)
            );
        }
        return engs;
    }
}