src/core-crm/objects/Engagement__c/Engagement__c.object-meta.xml
<CustomObject>
    <description>Engagement captures business information about an ‘Engagement’ QUT staff are having with a person or organisation, or a contact at a particular organisation.</description>
    <label>Engagement</label>
    <nameField>
        <label>Engagement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Engagement_Code_Auto_Number__c/Engagement_Code_Auto_Number__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Engagement Code Auto Number</label>
</CustomObject>

src/core-crm/objects/Engagement_Code_Auto_Number__c/fields/Commercialisation__c.field-meta.xml
<CustomField>
    <fullName>Commercialisation__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Auto-number used for Commercialisation Engagement records.</description>
    <label>Commercialisation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Engagement_Code_Auto_Number__c/fields/Research_Partnership__c.field-meta.xml
<CustomField>
    <fullName>Research_Partnership__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Auto-number used for Research Partnership Engagement records.</description>
    <label>Research Partnership</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Opportunity/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to associated Engagement.</description>
    <label>Engagement</label>
    <referenceTo>Engagement__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Opportunity_Code_Auto_Number__c/Opportunity_Code_Auto_Number__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom setting contains the auto-numbers used for the Opportunity object&apos;s Opportunity Code.</description>
    <label>Opportunity Code Auto Number</label>
</CustomObject>

src/core-crm/objects/Opportunity_Code_Auto_Number__c/fields/Commercialisation__c.field-meta.xml
<CustomField>
    <fullName>Commercialisation__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Auto-number used for Commercialisation Opportunity records.</description>
    <label>Commercialisation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Opportunity_Code_Auto_Number__c/fields/International_Projects_Unit__c.field-meta.xml
<CustomField>
    <fullName>International_Projects_Unit__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Auto-number used for International Projects Unit Opportunity records.</description>
    <label>International Projects Unit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Opportunity_Code_Auto_Number__c/fields/Research_Partnership__c.field-meta.xml
<CustomField>
    <fullName>Research_Partnership__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Auto-number used for Research Partnership Opportunity records.</description>
    <label>Research Partnership</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/classes/DynamicDatatableEventServiceTest.cls
/**
 * @description Service Class for Publishing DynamicDatatableEvent
 *
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary                 |
 *    |--------------------------------|-----------------------|------------------------|--------------------------------|
 *    | roy.nino.s.regala              | July 06, 2023         | DEPP-5474              | Created file                   |
 */
@isTest
private class DynamicDatatableEventServiceTest {

    @isTest
    private static void publishPlatformEvent() {
        TestDataFactory.generateTestUsers(new List<String>{ 'QUT_IE_Partnership_Manager' });
        Opportunity_Code_Auto_Number__c opptyCodeAutoNum = OpportunityCodeAutoNumbersDAO.newInstance()
            .getOrganizationalDefaults();
        opptyCodeAutoNum.Commercialisation__c = 1;
        opptyCodeAutoNum.International_Projects_Unit__c = 1;
        opptyCodeAutoNum.Research_Partnership__c = 1;
        OpportunityCodeAutoNumbersDAO.newInstance()
            .upsertRecords(
                new List<Opportunity_Code_Auto_Number__c>{ opptyCodeAutoNum },
                false,
                AccessLevel.USER_MODE
            );

        Engagement_Code_Auto_Number__c engCodeAutoNum = EngagementCodeAutoNumbersDAO.newInstance()
            .getOrganizationalDefaults();
        engCodeAutoNum.Commercialisation__c = 1;
        engCodeAutoNum.Research_Partnership__c = 1;
        EngagementCodeAutoNumbersDAO.newInstance()
            .upsertRecords(
                new List<Engagement_Code_Auto_Number__c>{ engCodeAutoNum },
                false,
                AccessLevel.USER_MODE
            );

        System.runAs(testDataFactory.getQUTIEPartnershipManager()) {
            List<Engagement__c> engagementList = TestDataFactory.createTestEngagementRecords(
                1,
                'RCE',
                EngagementsDAO.COMMERCIALISATION_RECTYPE_ID
            );
            EngagementsDAO.newInstance()
                .insertRecords(engagementList, false, AccessLevel.USER_MODE);

            Test.startTest();
            List<Opportunity> ipuOpportunityList = TestDataFactory.createOpportunityRecords(
                1,
                'test',
                'Qualify'
            );
            ipuOpportunityList[0].Engagement__c = engagementList[0].Id;
            System.assert(
                OpportunitiesDAO.newInstance()
                        .insertRecords(ipuOpportunityList, false, AccessLevel.USER_MODE)[0]
                    .isSuccess(),
                'Opportunity is not created'
            );
            Test.stopTest();
        }
    }
}