src/core-crm/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <description>The Document data object stores metadata relating to documents stored outside the system. The object does not store the document itself.</description>
    <label>Document</label>
    <nameField>
        <displayFormat>DOC-{0000000}</displayFormat>
        <label>Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Document__c/fields/IP_Management__c.field-meta.xml
<CustomField>
    <fullName>IP_Management__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to related IP Management record.</description>
    <label>IP Management</label>
    <referenceTo>IP_Management__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/IP_Management__c/IP_Management__c.object-meta.xml
<CustomObject>
    <description>This object will be used to track/record administrative information relating to Intellectual Property.</description>
    <label>IP Management</label>
    <nameField>
        <displayFormat>IPM-{00000}</displayFormat>
        <label>IP Management Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IP Managements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/core-crm/classes/IPManagementsDAOMock.cls
/**
 * @description Mock DAO Class for IP Management Object. 
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | eugene.andrew.abuan            | July 10, 2023         | DEPP-5483              | Created file                 |                                                     |
 */
@isTest
public inherited sharing class IPManagementsDAOMock extends DmlBaseMock implements IIPManagementsDAO {

	public Map<Id, IP_Management__c> ipManagements;

    public Schema.SObjectType getSObjectType()
	{
		return IP_Management__c.SObjectType;
	}

	public IPManagementsDAOMock() {
		super(new Map<Id, Document__c>(), Schema.Document__c.SObjectType);
		this.ipManagements = (Map<Id, IP_Management__c>) super.records;
	}
}