src/core-crm/objects/hed__Course__c/hed__Course__c.object-meta.xml
<CustomObject>
    <description>Academic Course offered by a Department or School, for example, English 101 or Ancient History.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course__c/fields/Course_Code__c.field-meta.xml
<CustomField>
    <fullName>Course_Code__c</fullName>
    <description>Course code is the QUT unique business identifier assigned to a Course.

For SAMS units it is combination of Course Code and Course Version
Format &lt;Course_Code&gt;-&lt;Version no&gt;
eg MAB522-3</description>
    <inlineHelpText>Course code is the QUT unique business identifier assigned to a Course.

For SAMS units it is combination of Course Code and Course Version
Format &lt;Course_Code&gt;-&lt;Version no&gt;
eg MAB522-3</inlineHelpText>
    <label>Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/core-crm/objects/hed__Course__c/fields/LMS_Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>LMS_Integration_Status__c</fullName>
    <label>LMS Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Course__c/fields/Mark_Content_as_Complete__c.field-meta.xml
<CustomField>
    <fullName>Mark_Content_as_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mark Content as Complete</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/hed__Course__c/fields/Primary_Delivery_Platform__c.field-meta.xml
<CustomField>
    <fullName>Primary_Delivery_Platform__c</fullName>
    <label>Primary Delivery Platform</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Blackboard</fullName>
            </value>
            <value>
                <fullName>Blackboard Engage (Custom Program)</fullName>
            </value>
            <value>
                <fullName>Canvas (QUT Online)</fullName>
            </value>
            <value>
                <fullName>FutureLearn</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/hed__Course_Offering__c.object-meta.xml
<CustomObject>
    <description>Joins Courses and Terms to contain information related to a single occurrence of a Course.</description>
    <label>Course Offering</label>
    <nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Offering__c/fields/Course_Code__c.field-meta.xml
<CustomField>
    <fullName>Course_Code__c</fullName>
    <description>Code of related course</description>
    <formula>hed__Course__r.Course_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Course Code</label>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Course__c.field-meta.xml
<CustomField>
    <fullName>hed__Course__c</fullName>
    <description>Lookup to the Course record that this Course Offering is associated with.</description>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>
 

src/core-crm/objects/hed__Course_Offering__c/fields/hed__End_Date__c.field-meta.xml
<CustomField>
    <fullName>hed__End_Date__c</fullName>
    <description>The date of the last session for this Course Offering.</description>
    <inlineHelpText>The date of the last session for this Course Offering.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>hed__Start_Date__c</fullName>
    <description>The date of the first session for this Course Offering.</description>
    <inlineHelpText>The date of the first session for this Course Offering.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This will be used to deactivate Offering.</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/fields/LMS_Creation_Date__c.field-meta.xml
<CustomField>
    <fullName>LMS_Creation_Date__c</fullName>
    <description>Enter the date for LMS integration</description>
    <inlineHelpText>Enter the date for LMS integration</inlineHelpText>
    <label>LMS Creation Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/fields/LMS_Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>LMS_Integration_Status__c</fullName>
    <label>LMS Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/fields/Primary_Delivery_Platform__c.field-meta.xml
<CustomField>
    <fullName>Primary_Delivery_Platform__c</fullName>
    <description>Primary delivery platform of related course</description>
    <formula>TEXT(hed__Course__r.Primary_Delivery_Platform__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Delivery Platform</label>
    <type>Text</type>
</CustomField>

src/core-crm/classes/LMSCourseOfferingBatchHandler.cls
/**
 * @description Batch handler and schduler for the LMS Course Offering Callouts.
 * To be ran in 15 mins interval.
 *
 * @author wli
 *
 * @date 08/05/2022
 * 
 *  * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary                            |
      |--------------------------------|-----------------------|------------------------|-------------------------------------------|
  	  | kenneth.f.alsay                | September 25, 2023    | DEPP-6629 - AC1        | Updated Schedule to 15 mins               |
      |                                |                       |                        | Updated WHERE clause to match criteria    |
 */



public without sharing class LMSCourseOfferingBatchHandler implements Database.Batchable<SObject>, Database.AllowsCallouts, Schedulable {

    private static final String PRIMARY_DELIVERY_PLATFORM = 'QUT Canvas';
    private static final String SUCCESS = 'Success';
    private static final String IS_CHANGED = 'isChanged';
    private static final Date TODAY = System.today();

    public Database.QueryLocator start(Database.BatchableContext param1) {
        return Database.getQueryLocator(
            'SELECT Id, Course_Code__c, Name, hed__Start_Date__c, hed__End_Date__c, LMS_Integration_Status__c, hed__Course__r.Name,' +
            ' hed__Course__r.LMS_Integration_Status__c, hed__Course__r.Primary_Delivery_Platform__c, hed__Course__r.Mark_Content_as_Complete__c' +
            ' FROM hed__Course_Offering__c' +
            ' WHERE (LMS_Integration_Status__c = NULL OR LMS_Integration_Status__c = :IS_CHANGED)' +
            ' AND LMS_Creation_Date__c <= :TODAY' +
            ' AND hed__Course__r.Primary_Delivery_Platform__c = :PRIMARY_DELIVERY_PLATFORM' +
            ' AND IsActive__c = TRUE'
        );
    }

    /**
     * @description Executes the process and calls the relevant classes.
     *
     * @param context The batch context.
     * @param batchObjects The objects to process.
     */
    public void execute(Database.BatchableContext context, List<hed__Course_Offering__c> courseOfferings) {
        LMSIntegrationManager.calloutLMSCourseOffering(courseOfferings);
    }

    /**
     * @description Finalizer method for the batch process.
     *
     * @param param1 The batch context.
     */
    public void finish(Database.BatchableContext param1) {
        try {
            System.scheduleBatch(new LMSCourseOfferingBatchHandler(), 'LMS Course Offering Batch Job', 15, 200);
        } catch(Exception e) {
            Logger.error('Exception caught in method finish in class LMSCourseOfferingBatchHandler.')
                .setExceptionDetails(e);
        } finally {
            if(Logger.getBufferSize() > 0) {
                Logger.saveLog();
            }
        }
    }

    /**
     * @description Executes the Batch Handler class.
     *
     * @param param1 The schedulable context.
     */
    public void execute(SchedulableContext param1) {
        Database.executeBatch(new LMSCourseOfferingBatchHandler(), 200);
    }

}