src/core-crm/objects/hed__Course__c/hed__Course__c.object-meta.xml
<CustomObject>
    <description>Academic Course offered by a Department or School, for example, English 101 or Ancient History.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course__c/fields/ProductRequestID__c.field-meta.xml
<CustomField>
    <fullName>ProductRequestID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Program_Plan__c/hed__Program_Plan__c.object-meta.xml
<CustomObject>
    <description>Links Courses to an Academic Program to create a path for students to follow. An Academic Program can list multiple Courses, and a Course can be associated with multiple Academic Programs.</description>
    <label>Program Plan</label>
    <nameField>
        <label>Program Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Program_Plan__c/fields/Product_Request__c.field-meta.xml
<CustomField>
    <fullName>Product_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the related Product Request record of the Program Plan.</description>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Program_Plan__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <description>This record type will be used to create a Program. This can be a combination of a Unit, a Module, a Short Course, or an Activity.</description>
    <label>Program</label>
</RecordType>

src/core-crm/objects/Product2/fields/Available_on_Cart__c.field-meta.xml
<CustomField>
    <fullName>Available_on_Cart__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This will drive the product visibility in Product Catalogue and Corporate Portal</description>
    <label>Available on Cart</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Product2/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Product2/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Plan</label>
    <referenceTo>hed__Program_Plan__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Product_Request__c/Product_Request__c.object-meta.xml
<CustomObject>
    <label>Product Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Product Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Product_Request__c/fields/OPE_Program_Plan_Type__c.field-meta.xml
<CustomField>
    <fullName>OPE_Program_Plan_Type__c</fullName>
    <description>This is a hidden field that stores the Program Type of a Program Plan if the Product Request is Program. This will be used in tab visibilities of the flexipage.</description>
    <label>OPE Program Plan Type</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Product_Request__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <description>This record type will be used to create a Program. This can be a combination of a Unit, a Module, a Short Course, or an Activity.</description>
    <label>Program</label>
</RecordType>

src/core-crm/objects/Product_Request__c/recordTypes/Standing_Offer_Arrangement.recordType-meta.xml
<RecordType>
    <fullName>Standing_Offer_Arrangement</fullName>
    <active>true</active>
    <description>This record type will be used to create Standing Offer Arrangement within Corporate Portal</description>
    <label>Standing Offer Arrangement</label>
</RecordType>

src/core-crm/objects/Related_Product_Request__c/Related_Product_Request__c.object-meta.xml
<CustomObject>
    <label>Related Product Request</label>
    <nameField>
        <label>Related Product Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Related Product Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Related_Product_Request__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Related Product Requests</relationshipLabel>
    <relationshipName>Course</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Related_Product_Request__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Related Product Requests</relationshipLabel>
    <relationshipName>Program</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/classes/ProductManagementCtrl.cls
/**
 * @description Controller Class for productmanagement LWC
 * @see ../lwc/productmanagement
 * @author Accenture
 * @history
 *    | Developer                 | Date                  | JIRA                 | Change Summary                                       |
      |---------------------------|-----------------------|----------------------|------------------------------------------------------|
      | roy.nino.s.regala         | March 10, 2022        | DEPP-1747            | Created file                                         |
      | roy.nino.s.regala         | May 23, 2022          | DEPP-2663            | Added checking of Availabl on Cart field of Product  |
      | alexander.cadalin         | July 26, 2022         | DEPP-2500            | Added checking if parent PR is Standing Offer Arr.   |
 */
public with sharing class ProductManagementCtrl {
    /**
     * @description do callout to loqate
     * @param productRequestId - id of product request
     * @return boolean that tells  whether a parent is prescribed or not
     */
    @AuraEnabled(cacheable=true)    
    public static boolean checkParentProgramType(Id productRequestId){
        if(
            [
            SELECT Id, Program__r.OPE_Program_Plan_Type__c 
            FROM Related_Product_Request__c 
            WHERE Course__c =: productRequestId 
            AND Program__r.OPE_Program_Plan_Type__c = 'Prescribed Program'
            LIMIT 1
            ].isEmpty()
        ){
            return true;
        } else{
            return false;
        }
    }


    /**
     * @description do callout to loqate
     * @param productRequestId - id of product request
     * @return boolean that tells  whether a parent is prescribed or not
     */
    @AuraEnabled(cacheable=true)
    public static boolean checkAvailableOnCart(Id productRequestId){
        if(
            ![
            SELECT Id
            FROM Product2
            WHERE Available_on_Cart__c = true
            AND (Course__r.ProductRequestID__c =: productRequestId
            OR Program_Plan__r.Product_Request__c =: productRequestId)
            LIMIT 1
            ].isEmpty()
        ){
            return true;
        } else{
            return false;
        }
    }

    /**
     * @description do callout to loqate
     * @param productRequestId - id of product request
     * @return boolean that tells whether a parent is SOA or not
     */
    @AuraEnabled(cacheable=true)    
    public static boolean checkParentIsSOA(Id productRequestId){
        if(
            ![
            SELECT Id
            FROM Related_Product_Request__c 
            WHERE Course__c =: productRequestId 
            AND Program__r.RecordType.DeveloperName = 'Standing_Offer_Arrangement'
            LIMIT 1
            ].isEmpty()
        ){
            return true;
        } else {
            return false;
        }
    }
}