src/core-crm/objects/hed__Course__c/hed__Course__c.object-meta.xml
<CustomObject>
    <description>Academic Course offered by a Department or School, for example, English 101 or Ancient History.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course__c/fields/isLMSTriggered__c.field-meta.xml
<CustomField>
    <fullName>isLMSTriggered__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used in LMSCourseBatchHandler to identify if record has been previous processed</description>
    <label>isLMSTriggered</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/hed__Course__c/fields/Mark_Content_as_Complete__c.field-meta.xml
<CustomField>
    <fullName>Mark_Content_as_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mark Content as Complete</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/hed__Course__c/fields/Primary_Delivery_Platform__c.field-meta.xml
<CustomField>
    <fullName>Primary_Delivery_Platform__c</fullName>
    <label>Primary Delivery Platform</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Blackboard</fullName>
            </value>
            <value>
                <fullName>Blackboard Engage (Custom Program)</fullName>
            </value>
            <value>
                <fullName>Canvas (QUT Online)</fullName>
            </value>
            <value>
                <fullName>FutureLearn</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/hed__Course_Offering__c.object-meta.xml
<CustomObject>
    <description>Joins Courses and Terms to contain information related to a single occurrence of a Course.</description>
    <label>Course Offering</label>
    <nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Course__c.field-meta.xml
<CustomField>
    <fullName>hed__Course__c</fullName>
    <description>Lookup to the Course record that this Course Offering is associated with.</description>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>
 

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Term__c.field-meta.xml
<CustomField>
    <fullName>hed__Term__c</fullName>
    <description>Lookup to the Term record that represents when this Course Offering takes place.</description>
    <label>Term</label>
    <referenceTo>hed__Term__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>
 

src/core-crm/objects/hed__Course_Offering__c/fields/isLMSTriggered__c.field-meta.xml
<CustomField>
    <fullName>isLMSTriggered__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used in LMSCourseOfferingBatchHandler to identify if record has been previously processed</description>
    <label>isLMSTriggered</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/fields/Primary_Delivery_Platform__c.field-meta.xml
<CustomField>
    <fullName>Primary_Delivery_Platform__c</fullName>
    <description>Primary delivery platform of related course</description>
    <formula>TEXT(hed__Course__r.Primary_Delivery_Platform__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Delivery Platform</label>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Term__c/hed__Term__c.object-meta.xml
<CustomObject>
    <description>Unit of time in which academic activities are taking place.</description>
    <label>Term</label>
    <nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/Product_Request__c/Product_Request__c.object-meta.xml
<CustomObject>
    <label>Product Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Product Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/classes/LMSCourseBatchHandlerTest.cls
@isTest 
public class LMSCourseBatchHandlerTest {

    @testSetup static void setup() {
        List<Account> accounts = TestDataFactory.createTestAccountRecords(1);
        insert accounts;
    
        List<Contact> contacts = TestDataFactory.createTestContactRecords(1);
        insert contacts;
    
        List<hed__Term__c> terms = TestDataFactory.createTestTermRecords(1, accounts[0].Id);
        insert terms;
    
        List<Product_Request__c> prodRequest = TestDataFactory.createTestProductRequestRecords(1);
        insert prodRequest;
    
        List<hed__Course__c> courses = TestDataFactory.createTestCourseRecords(1, accounts[0].Id, prodRequest[0].Id);
        insert courses;
    
        List<hed__Course_Offering__c> courseOfferings = TestDataFactory.createTestCourseOfferingRecord(1, courses, terms);
        insert courseOfferings;      
    }

    @isTest
    static void testCourseLMSUpdate() 
    {
        hed__Course__c course = [SELECT Id, Mark_Content_as_Complete__c, Primary_Delivery_Platform__c FROM hed__Course__c LIMIT 1];
        course.Mark_Content_as_Complete__c = true;
        course.Primary_Delivery_Platform__c = 'Blackboard';
        update course;
        
        Test.startTest();
        LMSCourseBatchHandler job = new LMSCourseBatchHandler();
        DataBase.executeBatch(job, 1); 
        Test.stopTest();

        hed__Course__c courseAfterUpdate = [SELECT Id, isLMSTriggered__c FROM hed__Course__c LIMIT 1];
        System.assertEquals(true, courseAfterUpdate.isLMSTriggered__c, 'LMS Course Callout is completed.');
    }
}