src/core-crm/objects/hed__Course__c/hed__Course__c.object-meta.xml
<CustomObject>
    <description>Academic Course offered by a Department or School, for example, English 101 or Ancient History.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course__c/fields/ProductRequestID__c.field-meta.xml
<CustomField>
    <fullName>ProductRequestID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/hed__Course_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Represents a connection to a Course Offering.</description>
    <label>Course Connection</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Course Connection ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Enrollment__c/fields/hed__Contact__c.field-meta.xml
<CustomField>
    <fullName>hed__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student or faculty member participating in this Course Offering.</description>
    <inlineHelpText>The student or faculty member participating in this Course Offering.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Connections</relationshipLabel>
    <relationshipName>Student_Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/hed__Course_Offering__c.field-meta.xml
<CustomField>
    <fullName>hed__Course_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Course Offering the student or faculty member is involved with.</description>
    <inlineHelpText>The Course Offering the student or faculty member is involved with.</inlineHelpText>
    <label>Course Offering ID</label>
    <referenceTo>hed__Course_Offering__c</referenceTo>
    <relationshipLabel>Course Connection</relationshipLabel>
    <relationshipName>Course_Enrollment</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <description>A Student Course Connection</description>
    <label>Student</label>
</RecordType>

src/core-crm/objects/hed__Course_Offering__c/hed__Course_Offering__c.object-meta.xml
<CustomObject>
    <description>Joins Courses and Terms to contain information related to a single occurrence of a Course.</description>
    <label>Course Offering</label>
    <nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Course__c.field-meta.xml
<CustomField>
    <fullName>hed__Course__c</fullName>
    <description>Lookup to the Course record that this Course Offering is associated with.</description>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>
 

src/core-crm/objects/Product_Request__c/Product_Request__c.object-meta.xml
<CustomObject>
    <label>Product Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Product Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Product_Request__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <description>This record type will be used to create a Program. This can be a combination of a Unit, a Module, a Short Course, or an Activity.</description>
    <label>Program</label>
</RecordType>

src/core-crm/objects/Questionnaire__c/Questionnaire__c.object-meta.xml
<CustomObject>
    <description>This will capture the list of questions/answers against a record.</description>
    <label>Questionnaire</label>
    <nameField>
        <displayFormat>QN-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Questionnaire__c/fields/Questionnaire_Type__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire_Type__c</fullName>
    <description>Types of questionnaire the users can create.</description>
    <label>Questionnaire Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registration Criteria</fullName>
            </value>
            <value>
                <fullName>Registration Questions</fullName>
            </value>
            <value>
                <fullName>Application Questions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Questionnaire_Response_Summary__c/Questionnaire_Response_Summary__c.object-meta.xml
<CustomObject>
    <description>This will summarise the response of leaner to a questionnaire per offering.</description>
    <label>Questionnaire Response Summary</label>
    <nameField>
        <displayFormat>QRS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questionnaire Response Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Questionnaire_Response_Summary__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <description>This will determine the eligibility status of the Application.</description>
    <label>Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Questionnaire_Response_Summary__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the contact answering the questionnaire.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Questionnaire Response Summaries</relationshipLabel>
    <relationshipName>Questionnaire_Response_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Questionnaire_Response_Summary__c/fields/Course_Offering__c.field-meta.xml
<CustomField>
    <fullName>Course_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the course offering the responses answered from.</description>
    <label>Course Offering</label>
    <referenceTo>hed__Course_Offering__c</referenceTo>
    <relationshipLabel>Questionnaire Response Summaries</relationshipLabel>
    <relationshipName>Questionnaire_Response_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Questionnaire_Response_Summary__c/fields/Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the questionnaire containing questions.</description>
    <label>Questionnaire</label>
    <referenceTo>Questionnaire__c</referenceTo>
    <relationshipLabel>Questionnaire Response Summaries</relationshipLabel>
    <relationshipName>Questionnaire_Response_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Questionnaire_Response_Summary__c/fields/Reason_for_Rejection__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Rejection__c</fullName>
    <description>This field is an explanation to the learner advising why the application has been rejected.</description>
    <label>Reason for Rejection</label>
    <length>32000</length>
    <type>Html</type>
</CustomField>

src/core-crm/classes/ManageApplicationSectionCtrl.cls
/**
 * @description Controller Class for manageApplicationSection LWC
 * @see ../lwc/manageApplicationSection
 * 
 * @author Accenture
 * 
 * @history
 *    | Developer                 | Date                  | JIRA                 | Change Summary               |
      |---------------------------|-----------------------|----------------------|------------------------------|
      | eccarius.karl.munoz       | February 08, 2022     | DEPP-1483            | Created file                 | 
      | eccarius.karl.munoz       | February 28, 2022     | DEPP-1819            | Removed handling for Program | 
      |                           |                       |                      | Plan due to program offering | 
      |                           |                       |                      | id removal.                  | 
      |                           |                       |                      |                              | 
 */
public with sharing class ManageApplicationSectionCtrl {

     private static string studentRT = System.Label.RT_CourseConnection_Student;
     private static Id studentRecTypeId = Schema.SObjectType.hed__Course_Enrollment__c.getRecordTypeInfosByDeveloperName().get(studentRT).getRecordTypeId();
     
     /**
      * @description Retrieves list of Application details of students
      * @param prodReqId - Record ID from record page
      * @return List of ManageApplicationDetails
      */
     @AuraEnabled(cacheable=true)
     public static List<ManageApplicationDetails> getStudentApplications(String prodReqId){
          List<ManageApplicationDetails> response = new List<ManageApplicationDetails>();
          Product_Request__c productRequest = [SELECT RecordTypeId FROM Product_Request__c WHERE Id =: prodReqId LIMIT 1];                 
          response = getNonProgPlanApplications(prodReqId);
          return response;
     }

     /**
      * @description Retrieves list of Application details of students for Non Program Plan
      * @param prodReqId - Record ID from record page
      * @return List of ManageApplicationDetails
      */
     private static List<ManageApplicationDetails> getNonProgPlanApplications(String prodReqId){
          List<ManageApplicationDetails> response = new List<ManageApplicationDetails>();
          
          Id courseOfferingId = [SELECT Id FROM hed__Course_Offering__c WHERE hed__Course__c IN (
                                   SELECT Id FROM hed__Course__c WHERE ProductRequestID__c =: prodReqId)]?.Id;
          if(courseOfferingId == null){
               return new List<ManageApplicationDetails>();
          }
          List<Questionnaire_Response_Summary__c> questionnaireResponseList = [
               SELECT Id, Name, Contact__c, Questionnaire__r.Questionnaire_Type__c, Application_Status__c, Reason_for_Rejection__c 
                 FROM Questionnaire_Response_Summary__c 
                WHERE Course_Offering__c =: courseOfferingId 
          ];
          List<hed__Course_Enrollment__c > courseConnections = [
               SELECT Id, hed__Contact__c, hed__Contact__r.Name 
                 FROM hed__Course_Enrollment__c 
                WHERE hed__Course_Offering__c =: courseOfferingId AND RecordTypeId =: studentRecTypeId
          ];

          for(hed__Course_Enrollment__c student : courseConnections){
               for(Questionnaire_Response_Summary__c question : questionnaireResponseList){
                    if(question.Contact__c == student.hed__Contact__c){
                         ManageApplicationDetails appDetails = new ManageApplicationDetails();
                         appDetails.id = question.Id;
                         appDetails.contactFullName = student.hed__Contact__r.Name;
                         appDetails.applicationStatus = question.Application_Status__c;
                         appDetails.reasonForRejection = question.Reason_for_Rejection__c;
                         if(question.Questionnaire__r.Questionnaire_Type__c == 'Application Questions'){
                              appDetails.applicationURL = '/' + question.Id;
                              appDetails.applicationName = question.Name;
                         }                         
                         response.add(appDetails);
                    }                    
               }
          }
          return response;
     }

     /**
      * @description Updates Application details of students
      * @param id
      * @param applicationStatus
      * @param reasonForRejection 
      * @return String
      */
     @AuraEnabled
     public static String updateStudentApplication(String id, String applicationStatus, String reasonForRejection){ 
          Questionnaire_Response_Summary__c questionnaire = new Questionnaire_Response_Summary__c();
          questionnaire.Id = id;
          questionnaire.Application_Status__c = applicationStatus;
          questionnaire.Reason_for_Rejection__c = reasonForRejection;
          try {
               update questionnaire;
               return 'Success';
          }
          catch (Exception e) {
               return 'The following exception has occurred: ' + e.getMessage();
          }
     }   
     
     @AuraEnabled(cacheable=true)
     public static List<String> getApplicationStatusValues(){
          List<String> response = new List<String>();
          String strObjectName = 'Questionnaire_Response_Summary__c';
          String strPicklistField = 'Application_Status__c';
          Map<String, String> mapPickListValues = new Map<String, String>();
          Schema.SObjectType objSobjectType = Schema.getGlobalDescribe().get(strObjectName);
          Schema.DescribeSObjectResult objDescribeSobject = objSobjectType.getDescribe();
          Map<String, Schema.SObjectField> mapFields = objDescribeSobject.fields.getMap();
          List<Schema.PicklistEntry> lstPickListValues = mapFields.get(strPicklistField).getDescribe().getPickListValues();
          for (Schema.PicklistEntry objPickList : lstPickListValues) {
               String val = objPickList.getValue();
               response.add(val);
          }
          return response;
     }

     /**
      * @description Wrapper class that holds data to be displayed
      */
     public class ManageApplicationDetails{
          @AuraEnabled
          public String id;
          @AuraEnabled
          public String contactFullName;
          @AuraEnabled
          public String applicationURL;
          @AuraEnabled
          public String applicationName;
          @AuraEnabled
          public String applicationStatus;
          @AuraEnabled
          public String reasonForRejection;          
      }

}