src/core-crm/objects/hed__Course__c/hed__Course__c.object-meta.xml
<CustomObject>
    <description>Academic Course offered by a Department or School, for example, English 101 or Ancient History.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Offering__c/hed__Course_Offering__c.object-meta.xml
<CustomObject>
    <description>Joins Courses and Terms to contain information related to a single occurrence of a Course.</description>
    <label>Course Offering</label>
    <nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Course__c.field-meta.xml
<CustomField>
    <fullName>hed__Course__c</fullName>
    <description>Lookup to the Course record that this Course Offering is associated with.</description>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>
 

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Term__c.field-meta.xml
<CustomField>
    <fullName>hed__Term__c</fullName>
    <description>Lookup to the Term record that represents when this Course Offering takes place.</description>
    <label>Term</label>
    <referenceTo>hed__Term__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>
 

src/core-crm/objects/hed__Program_Plan__c/hed__Program_Plan__c.object-meta.xml
<CustomObject>
    <description>Links Courses to an Academic Program to create a path for students to follow. An Academic Program can list multiple Courses, and a Course can be associated with multiple Academic Programs.</description>
    <label>Program Plan</label>
    <nameField>
        <label>Program Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Program_Plan__c/fields/Product_Request__c.field-meta.xml
<CustomField>
    <fullName>Product_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the related Product Request record of the Program Plan.</description>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Program_Plan__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <description>This record type will be used to create a Program. This can be a combination of a Unit, a Module, a Short Course, or an Activity.</description>
    <label>Program</label>
</RecordType>

src/core-crm/objects/hed__Term__c/hed__Term__c.object-meta.xml
<CustomObject>
    <description>Unit of time in which academic activities are taking place.</description>
    <label>Term</label>
    <nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/Product2/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Plan</label>
    <referenceTo>hed__Program_Plan__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Product_Request__c/Product_Request__c.object-meta.xml
<CustomObject>
    <label>Product Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Product Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Product_Request__c/fields/Product_Request_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Request_Name__c</fullName>
    <label>Product Request Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/product-request-management/main/objects/Product_Request__c/fields/Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Name__c</fullName>
    <label>Program Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Product_Request__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <description>This record type will be used to create a Program. This can be a combination of a Unit, a Module, a Short Course, or an Activity.</description>
    <label>Program</label>
</RecordType>

src/core-crm/classes/CreateProductsAndOfferingsCtrlTest.cls
/**
 * @description Tests the Create Product and Offering Controller Test Class
 *
 * @see createProductsAndOfferingsCtrl
 *
 * @author Accenture
 *
 * @history
 *    | Developer                 | Date                  | JIRA             | Change Summary                                                                                                              |
      |---------------------------|-----------------------|------------------|-----------------------------------------------------------------------------------------------------------------------------|
      | adrian.c.habasa           | October 18, 2021      | DEPP-476         | Created file                                                                                                                | 
      | eugene.andrew.abuan       | November 9, 2021      | DEPP-35          | Added method testGetProductRequests                                                                                         | 
      | roy.nino.s.regala         | November 25, 2021     | DEPP-362,38,37   | Added method testGetRelatedCourseProgramRequestRecordType, testUpdateProductRequests,testUpsertProgramPlanAndPlanRequirement| 
*/

@isTest
public with sharing class CreateProductsAndOfferingsCtrlTest {
   
   private static User  currentUser = TestDataFactory.createUserRecords(1,'QUTeX').iterator().next();
   private static Map <String,Schema.RecordTypeInfo> productRequestRecordTypes = Product_Request__c.sObjectType.getDescribe().getRecordTypeInfosByName();
   private static Id programRequestRTId = productRequestRecordTypes.get('Program Request').getRecordTypeId();
   
   @testSetup static void setupMethod()
   {
       List<Account> accounts;
       List<hed__Course__c> courses;
       List<hed__Course__c> coursesProgramRequest;
       List<hed__Course_Offering__c> courseOfferings;
       List<Product2> products;
       List<Product_Request__c> prodRequest;
       List<Product_Request__c> prodRequestProgramRequest;
       List<hed__Program_Plan__c> programPlanList;
       List<hed__Term__c> terms;
       accounts = TestDataFactory.createTestAccountRecords(1);
       insert accounts;
       terms = TestDataFactory.createTestTermRecords(100,accounts[0].Id);
       insert terms;
       prodRequest = TestDataFactory.createTestProductRequestRecords(1);
       insert prodRequest;

       prodRequestProgramRequest = TestDataFactory.createTestProductRequestRecords(1);
       prodRequestProgramRequest[0].Product_Request_Name__c = 'Program Request';
       prodRequestProgramRequest[0].RecordTypeId = programRequestRTId;
       insert prodRequestProgramRequest;

       Test.startTest();
       courses = TestDataFactory.createTestCourseRecords(50,accounts[0].Id,prodRequest[0].Id);
       insert courses;
       coursesProgramRequest = TestDataFactory.createTestCourseRecords(50,accounts[0].Id,prodRequestProgramRequest[0].Id);
       insert coursesProgramRequest;
       programPlanList = TestDataFactory.createTestProgramPlanRecords(1);
       programPlanList[0].Product_Request__c = prodRequestProgramRequest[0].Id;
       insert programPlanList;
       products = TestDataFactory.createTestProductRecords(50,courses);
       insert products;
       products = TestDataFactory.createTestProductRecords(50);
       for(Product2 product: products){
           product.Program_Plan__c = programPlanList[0].Id;
       }
       insert products;
       courseOfferings = TestDataFactory.createTestCourseOfferingRecord(50,courses,terms);
       insert courseOfferings;
       Test.stopTest();
    }

    @isTest
    static void testGetRelatedCourse()
    {
        Test.startTest();
        System.runAs(currentUser)
        {   
            CreateProductsAndOfferingsCtrl.CourseWithOfferings getCourses = new CreateProductsAndOfferingsCtrl.CourseWithOfferings();
            getCourses = CreateProductsAndOfferingsCtrl.getRelatedCourse(string.valueOf([SELECT Id FROM Product_Request__c LIMIT 1].Id));  
            System.assert(!getCourses.courseList.isEmpty(),'Error while getting data');
        }
        Test.stopTest();
    }

    @isTest
    static void testGetRelatedCourseProgramRequestRecordType()
    {
        Test.startTest();
        System.runAs(currentUser)
        {   
            CreateProductsAndOfferingsCtrl.CourseWithOfferings getCourses = new CreateProductsAndOfferingsCtrl.CourseWithOfferings();
            getCourses = CreateProductsAndOfferingsCtrl.getRelatedCourse(string.valueOf([SELECT Id FROM Product_Request__c WHERE RecordTypeId =:programRequestRTId LIMIT 1].Id));  
            System.assert(!getCourses.courseList.isEmpty(),'Error while getting data');
        }
        Test.stopTest();
    }

    @isTest
    static void testUpdateProductRequests()
    {
        Test.startTest();
        System.runAs(currentUser)
        {   
            List<Product_Request__c> productRequestToUpdate = new List<Product_Request__c>();
            List<Product_Request__c> productRequestList  = new List<Product_Request__c>([SELECT Id FROM Product_Request__c WHERE RecordTypeId =:programRequestRTId]);
            for(Product_Request__c productRequest: productRequestList){
                productRequest.Program_Name__c = 'TESTUPDATE';
                productRequestToUpdate.add(productRequest);
            }
            CreateProductsAndOfferingsCtrl.updateProductRequests(productRequestToUpdate);  
            System.assert(![SELECT Id FROM Product_Request__c WHERE Program_Name__c = 'TESTUPDATE'].isEmpty(),'Error Updating product requests');
        }
        Test.stopTest();
    }
}