src/core-crm/objects/hed__Course__c/hed__Course__c.object-meta.xml
<CustomObject>
    <description>Academic Course offered by a Department or School, for example, English 101 or Ancient History.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Offering__c/hed__Course_Offering__c.object-meta.xml
<CustomObject>
    <description>Joins Courses and Terms to contain information related to a single occurrence of a Course.</description>
    <label>Course Offering</label>
    <nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Offering__c/fields/Available_Seats__c.field-meta.xml
<CustomField>
    <fullName>Available_Seats__c</fullName>
    <formula>hed__Capacity__c -  Total_Number_of_Registered_Learners__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Course__c.field-meta.xml
<CustomField>
    <fullName>hed__Course__c</fullName>
    <description>Lookup to the Course record that this Course Offering is associated with.</description>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>
 

src/core-crm/objects/hed__Course_Offering__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This will be used to deactivate Offering.</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/fields/Registration_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_End_Date__c</fullName>
    <label>Registration End Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/fields/Registration_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Start_Date__c</fullName>
    <label>Registration Start Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Product2/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Product2/fields/Do_not_Show_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Do_not_Show_Start_Date__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Hide the available start date from the Product Catalogue</description>
    <label>Do not Show Start Date</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/classes/CourseOfferingTriggerHandler.cls
/**
 * @description Calls the helper method when triggered to update the External Id
 * @see CourseOfferingTrigger
 *
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary                                                |
      |--------------------------------|-----------------------|------------------------|---------------------------------------------------------------|
      | eugene.andrew.abuan            | March 22, 2022        | DEPP-1991              | Created file                                                  |
      | eugene.andrew.abuan            | March 22, 2022        | DEPP-3534              | Update                                                        |
      | eugene.andrew.abuan            | July 29, 2022         | DEPP-3534              | Added Do no show start date logic                             |
      | kenneth.f.alsay                | September 22, 2023    | DEPP-6299              | Added setLMSIntegrationStatusToIsChanged to before update     |
      |                                |                       |                        |                                                               |
 */

public without sharing class CourseOfferingTriggerHandler implements Disableable, BeforeInsert, BeforeUpdate, AfterInsert, AfterUpdate {
    /**
     * @description calls Validate Related Product & ExternalIdHelper function to update the External Id
     * @param newItems - List of hed__Course_Offering__c.Trigger.new
     */
    public void beforeInsert(List<SObject> newItems) {
        validateRelatedProduct((List<hed__Course_Offering__c>) newItems , null);
        SetExternalIdHelper.updateExternalId(newItems);
        SetOfferingName.setName(newItems);
    }

    /**
     * @description calls Validate Related Product
     * @param newItems - List of hed__Course_Offering__c.Trigger.new
     * @param oldItems - List of hed__Course_Offering__c.Trigger.old
     */
    public void beforeUpdate(
        Map<Id, SObject> newItems,
        Map<Id, SObject> oldItems
    ) {
        validateRelatedProduct((List<hed__Course_Offering__c>) newItems.values(),(Map<Id, hed__Course_Offering__c>) oldItems );
        CourseOfferingTriggerHelper.setLMSIntegrationStatusToIsChanged((List<hed__Course_Offering__c>) newItems.values(), (Map<Id, hed__Course_Offering__c>) oldItems);
    }

    /**
     * @description performs afterinsert event for hed__Course_Offering object
     * @param newItems - List of hed__Course_Offering__c.Trigger.new
     */
    public void afterInsert(Map<Id, SObject> newItems) {
        Map<Id, hed__Course_Offering__c> newItemsMap = (Map<Id, hed__Course_Offering__c>) newItems;
        //only create 1:1 since email will be sent once per offering and createddate is identical
        Map<Id, hed__Course_Offering__c> courseToOfferinMap = new Map<Id, hed__Course_Offering__c>();

        for (Id offeringId : newItems.keySet()) {
            //check if offering is updated to be available for registration
            if (
                newItemsMap.get(offeringId).IsActive__c == true &&
                newItemsMap.get(offeringId).Available_Seats__c > 0 &&
                newItemsMap.get(offeringId).Registration_Start_Date__c <=
                Date.today() &&
                newItemsMap.get(offeringId).hed__Course__c != null &&
                (newItemsMap.get(offeringId).Registration_End_Date__c >
                Date.today() ||
                newItemsMap.get(offeringId).Registration_End_Date__c == null)
            ) {
                courseToOfferinMap.put(
                    newItemsMap.get(offeringId).hed__Course__c,
                    newItemsMap.get(offeringId)
                );
            }
        }
        if (!courseToOfferinMap.keySet().isEmpty()) {
            SendNewOfferingNotificationHelper.sendCourseOfferingAvailabiltyNotification(
                courseToOfferinMap
            );
        }
    }

    /**
     * @description performs afterinsert event for hed__Course_Offering object
     * @param newItems - List of hed__Course_Offering__c.Trigger.new
     */
    public void afterUpdate(
        Map<Id, SObject> newItems,
        Map<Id, SObject> oldItems
    ) {
        //only create 1:1 since email will be sent once per offering and createddate is identical
        Map<Id, hed__Course_Offering__c> courseToOfferinMap = new Map<Id, hed__Course_Offering__c>();

        Map<Id, hed__Course_Offering__c> newItemsMap = (Map<Id, hed__Course_Offering__c>) newItems;
        Map<Id, hed__Course_Offering__c> oldItemsMap = (Map<Id, hed__Course_Offering__c>) oldItems;

        for (Id offeringId : newItems.keySet()) {
            //check if offering is updated to be available for registration
            if (
                ((oldItemsMap.get(offeringId).Available_Seats__c !=
                newItemsMap.get(offeringId).Available_Seats__c &&
                oldItemsMap.get(offeringId).Available_Seats__c == 0) ||
                (oldItemsMap.get(offeringId).Registration_Start_Date__c !=
                newItemsMap.get(offeringId).Registration_Start_Date__c &&
                oldItemsMap.get(offeringId).Registration_Start_Date__c >
                Date.today()) ||
                oldItemsMap.get(offeringId).IsActive__c !=
                newItemsMap.get(offeringId).IsActive__c) &&
                newItemsMap.get(offeringId).IsActive__c == true &&
                newItemsMap.get(offeringId).Available_Seats__c > 0 &&
                newItemsMap.get(offeringId).Registration_Start_Date__c <=
                Date.today() &&
                newItemsMap.get(offeringId).hed__Course__c != null &&
                (newItemsMap.get(offeringId).Registration_End_Date__c >
                Date.today() ||
                newItemsMap.get(offeringId).Registration_End_Date__c == null)
            ) {
                courseToOfferinMap.put(
                    newItemsMap.get(offeringId).hed__Course__c,
                    newItemsMap.get(offeringId)
                );
            }
        }
        if (!courseToOfferinMap.keySet().isEmpty()) {
            SendNewOfferingNotificationHelper.sendCourseOfferingAvailabiltyNotification(
                courseToOfferinMap
            );
        }
    }

    /**
     * @description validate related Product
     * @param crseOfferNew - List of hed__Course_Offering__c.Trigger.new
     * @param crseOfferOld - List of hed__Course_Offering__c.Trigger.old
     */
    public void validateRelatedProduct(
        List<hed__Course_Offering__c> crseOfferNew,
        Map<Id, hed__Course_Offering__c> crseOfferOld
    ) {
        // Get Courses
        Set<Id> courseSetId = new Set<Id>();
        for (hed__Course_Offering__c cOff : crseOfferNew) {
            if(crseOfferOld == null &&  cOff.IsActive__c == true ){
                courseSetId.add(cOff.hed__Course__c);
            }else if(crseOfferOld != null && cOff.IsActive__c != crseOfferOld.get(cOff.Id).IsActive__c && cOff.IsActive__c == true){
                courseSetId.add(cOff.hed__Course__c);
            }else if(crseOfferOld != null && cOff.IsActive__c != crseOfferOld.get(cOff.Id).IsActive__c && cOff.IsActive__c == false){
                courseSetId.add(cOff.hed__Course__c);
            }
        }

        // Get Active Course Offering Count per Course
        Map<Id, Integer> cCounterMap = new Map<Id, Integer>();
        for (AggregateResult cOffCounter : [
            SELECT hed__Course__c, Count(Id) counter
            FROM hed__Course_Offering__c
            WHERE hed__Course__c IN :courseSetId AND IsActive__c = TRUE
            GROUP BY hed__Course__c
        ]) {
            cCounterMap.put(
                (Id) cOffCounter.get('hed__Course__c'),
                (Integer) cOffCounter.get('counter')
            );
        }

        // Get Related Products for Courses
        Map<Id, Boolean> cProdDoNotDisplayDate = new Map<Id, Boolean>();
        for (Product2 prod : [
            SELECT Id, Course__c, Do_not_Show_Start_Date__c
            FROM Product2
            WHERE Course__c IN :courseSetId
        ]) {
            cProdDoNotDisplayDate.put(
                prod.Course__c,
                prod.Do_not_Show_Start_Date__c
            );
        }

        // Process
        if(!courseSetId.isEmpty()){
            for (hed__Course_Offering__c cOffVal : crseOfferNew) {
                Boolean doNotDisplayDate = (Boolean) cProdDoNotDisplayDate.get(
                    cOffVal.hed__Course__c
                );
                Integer cOffCount = (Integer) cCounterMap.get(
                    cOffVal.hed__Course__c
                );
                
                //Check if Active Course Offering Count is 1
                Boolean cOffCountIsOne = cOffCount >= 1? true: false;
                // If Related Product Do Not Display Date is True
                Boolean isActiveCOfferingDoNotDisplayDate = (doNotDisplayDate == true && cOffCountIsOne == true && cOffVal.IsActive__c == true);
                Boolean isNotActiveCOfferingDoNotDisplayDate = (doNotDisplayDate == true && cOffCountIsOne == true && cOffVal.IsActive__c == false && String.isNotBlank(cOffVal.Id));
                if (isActiveCOfferingDoNotDisplayDate) {
                    cOffVal.IsActive__c.addError(
                        'An active offering is already existing'
                    );
                }
                if (isNotActiveCOfferingDoNotDisplayDate) {
                    cOffVal.IsActive__c.addError(
                        '"Do not show start date" needs to be false before this offering can be deactivated.'
                    );
                }
            }
        }
    }
    

    /**
     * @description indicates it the trigger is disabled
     * @return disabled bypass
     */
    public Boolean isDisabled() {
        final TriggerBypassStrategy bypass = new TriggerBypassStrategy();
        return bypass.isDisabled();
    }
}