src/core-crm/objects/Contact_Matching_Service_Configuration__mdt/Contact_Matching_Service_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>Contact Matching Service Configuration</label>
    <pluralLabel>Contact Matching Service Configurations</pluralLabel>
</CustomObject>

src/core-crm/objects/Contact_Matching_Service_Configuration__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To indicate the batch job is currently enabled</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Contact_Matching_Service_Configuration__mdt/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <description>Indicate batch size per job</description>
    <label>Size</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Student_Sanction__c/Student_Sanction__c.object-meta.xml
<CustomObject>
    <description>Contains Sanction data applied to student or student program</description>
    <label>Student Sanction</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student Sanction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Sanctions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/core-crm/objects/Student_Sanction__c/fields/Batch_Process__c.field-meta.xml
<CustomField>
    <fullName>Batch_Process__c</fullName>
    <description>Indicating the record&apos;s state whether to be actioned with insert, update or processed</description>
    <label>Batch Process</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Batch_Process</valueSetName>
    </valueSet>
</CustomField>

src/core-crm/objects/Student_Sanction__c/fields/QUT_Student_ID__c.field-meta.xml
<CustomField>
    <fullName>QUT_Student_ID__c</fullName>
    <description>Unique student Id assigned by student administration system.</description>
    <label>QUT Student ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Student_Sanction__c/fields/Sanction_Code__c.field-meta.xml
<CustomField>
    <fullName>Sanction_Code__c</fullName>
    <description>The Sanction Code for the associated Sanction</description>
    <label>Sanction Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

src/core-crm/globalValueSets/Batch_Process.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Processed</fullName>
    </customValue>
    <customValue>
        <fullName>Insert</fullName>
    </customValue>
    <customValue>
        <fullName>Update</fullName>
    </customValue>
    <description>Indicating the record&apos;s state whether to be actioned with insert, update or processed</description>
    <masterLabel>Batch Process</masterLabel>
</GlobalValueSet>

src/core-crm/classes/StudentSanctionTriggerHelper.cls
/**
 * Handles the processing of duplicate sanctions triggered by changes to the Student Sanction object.
 * This class triggers the execution of a batch job for processing duplicate sanctions if applicable.
 *
 * @author Accenture
 *
 * @history
 *    | Developer                 | Date                  | JIRA         | Change Summary                                                        								|
 *    |---------------------------|-----------------------|--------------|------------------------------------------------------------------------------------------------------|
 *    | roy.nino.s.regala         | April 16, 2024        | DEPP-7984    | Created File
 */
public inherited sharing class StudentSanctionTriggerHelper {
    private static boolean isBatchJobRunning = false;

    /**
     * Processes the given list of new student sanction records to identify duplicate sanctions and trigger the execution of a batch job if necessary.
     *
     * @param newItems The list of new student sanction records.
     */
    public static void processDuplicateSanctionIntegration(List<Student_Sanction__c> newItems) {
        try {
            // Flag to determine whether to run the batch job
            Boolean runBatchJob = false;

            // Iterate through the new student sanction records
            for (Student_Sanction__c studentSanction : newItems) {
                // Check if the sanction is valid for processing
                boolean isSanctionValid =
                    String.isNotBlank(studentSanction.Sanction_Code__c) &&
                    studentSanction.Sanction_Code__c.toUpperCase() == 'DUP' &&
                    String.isNotBlank(studentSanction.QUT_Student_ID__c);
                if (isSanctionValid) {
                    // Set the batch process status to 'Insert'
                    studentSanction.Batch_Process__c = 'Insert';
                    // Set the flag to true to run the batch job
                    runBatchJob = true;
                }
            }

            Contact_Matching_Service_Configuration__mdt cmsConfig = ConMatchingServiceConfigurationsDAO.newInstance()
                .getInstanceByDeveloperName(ConMatchingServiceConfigurationsDAO.STUDENT_SANCTION_BATCH);

            // If no batch job needs to be run,
            // or batch is already running
            // or batch job is not active 
            // return (skip the soql and dont execute the batch)
            if (!runBatchJob || isBatchJobRunning || !cmsConfig.IsActive__c) {
                return;
            }

            // Check if there are any existing running jobs for the DuplicateSanctionBatch
            List<AsyncApexJob> jobs = AsyncApexJobsDAO.newInstance()
                .getRunningJobsByNameAndIdExemption(
                    new Set<String>{ ConMatchingServiceConfigurationsDAO.STUDENT_SANCTION_BATCH },
                    new Set<Id>(),
                    AccessLevel.SYSTEM_MODE
                );

            // If no running jobs exist, execute the batch job
            if (jobs.isEmpty()) {
                isBatchJobRunning = true;
                Database.executeBatch(new DuplicateSanctionBatch(), (Integer) cmsConfig.Size__c);
            }
        } catch (Exception e) {
            NebulaLoggerService.logExceptionDetails(
                'Exception caught in method processDuplicateSanctionIntegration in class StudentSanctionTriggerHelper.',
                e
            );
        }
    }
}