src/core-crm/objects/Plan_Activity__c/Plan_Activity__c.object-meta.xml
<CustomObject>
    <description>Plan Activity captures business interactions staff have with a Contact or Organisation.</description>
    <label>Plan Activity</label>
    <nameField>
        <label>Plan Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Activities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/core-crm/objects/Plan_Activity__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to an associated Opportunity record.</description>
    <inlineHelpText>Lookup to an associated Opportunity record.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Plan Activities</relationshipLabel>
    <relationshipName>Plan_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Plan_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the Activity.</description>
    <inlineHelpText>The status of the Activity.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/classes/PlanActivitiesDAO.cls
/**
 * @description DAO Class for Plan Activity Object.
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | kenneth.f.alsay                | February 29, 2024     | DEPP-7883              | Created file                 |
      | jerlyn.esparas                 | February 29, 2024     | DEPP-7890              |                              |

*/

 public inherited sharing class PlanActivitiesDAO extends DmlBase implements IPlanActivitiesDAO {
    public Schema.SObjectType getSObjectType() {
        return Plan_Activity__c.SObjectType;
    }

    public List<Plan_Activity__c> getPlanActivityRecordsWithOpportunityIds(
        Set<Id> opptyIds,
        AccessLevel accessLevel
    ) {
        return Database.query(
            'SELECT Id, Status__c, Opportunity__c ' +
                'FROM Plan_Activity__c ' +
                'WHERE Opportunity__c IN :opptyIds ',
				accessLevel
        );
    }

    public static IPlanActivitiesDAO newInstance() {
        return (IPlanActivitiesDAO) ImplementationSelector.DAO.newInstance(
            Plan_Activity__c.SObjectType
        );
    }
}