src-env-specific-pre/objects/Contact/fields/hed__AlternateEmail__c.field-meta.xml
<CustomField>
    <fullName>hed__AlternateEmail__c</fullName>
    <description>An optional email address not captured in other email fields.</description>
    <inlineHelpText>An optional email address not captured in other email fields.</inlineHelpText>
    <label>Alternate Email</label>
    <type>Email</type>
</CustomField>

src/core-crm/main/objects/Contact/fields/hed__Preferred_Email__c.field-meta.xml
<CustomField>
    <fullName>hed__Preferred_Email__c</fullName>
    <description>The email (University, Work, Alternate) that this Contact prefers you to use.</description>
    <inlineHelpText>The email (University, Work, Alternate) that this Contact prefers you to use.</inlineHelpText>
    <label>Preferred Email</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>University Email</fullName>
            </value>
            <value>
                <fullName>Work Email</fullName>
            </value>
            <value>
                <fullName>Alternate Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/main/objects/Contact/fields/QUT_Staff_Email__c.field-meta.xml
<CustomField>
    <fullName>QUT_Staff_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>QUT Staff Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

src/core-crm/objects/Flow_Automation_Settings__c/Flow_Automation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Flow Automation Settings</label>
</CustomObject>

src/core-crm/objects/Flow_Automation_Settings__c/fields/New_Idea_To_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>New_Idea_To_Email_Address__c</fullName>
    <label>New Idea To Email Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Opportunity/fields/Financial_Viability__c.field-meta.xml
<CustomField>
    <fullName>Financial_Viability__c</fullName>
    <inlineHelpText>Financial Viability: Respective price points have been discussed</inlineHelpText>
    <label>Financial Viability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Opportunity/fields/QUTeX_Capacity__c.field-meta.xml
<CustomField>
    <fullName>QUTeX_Capacity__c</fullName>
    <inlineHelpText>Do we have QUTeX capacity?</inlineHelpText>
    <label>QUTeX Capacity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Product_Specification__c/Product_Specification__c.object-meta.xml
<CustomObject>
    <label>Product Specification</label>
    <nameField>
        <displayFormat>PS-{00000}</displayFormat>
        <label>Product Specification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Specifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Product_Specification__c/fields/Endorsed_by__c.field-meta.xml
<CustomField>
    <fullName>Endorsed_by__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Endorsed by</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Product Specifications (Endorsed by)</relationshipLabel>
    <relationshipName>Product_Specifications1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Product_Specification__c/fields/Existing_Product__c.field-meta.xml
<CustomField>
    <fullName>Existing_Product__c</fullName>
    <label>Existing Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Not Sure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Product_Specification__c/fields/Financial_Viability__c.field-meta.xml
<CustomField>
    <fullName>Financial_Viability__c</fullName>
    <label>Financial Viability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Not Sure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Product_Specification__c/fields/Idea_Summary__c.field-meta.xml
<CustomField>
    <fullName>Idea_Summary__c</fullName>
    <label>Idea Summary</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

src/core-crm/objects/Product_Specification__c/fields/Market_Need__c.field-meta.xml
<CustomField>
    <fullName>Market_Need__c</fullName>
    <label>Market Need</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Not Sure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Product_Specification__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Program</fullName>
            </value>
            <value>
                <fullName>Unit</fullName>
                <isActive>false</isActive>
                <label>Unit</label>
            </value>
            <value>
                <fullName>Module</fullName>
            </value>
            <value>
                <fullName>Short Course</fullName>
            </value>
            <value>
                <fullName>Activity</fullName>
            </value>
            <value>
                <fullName>Single Product</fullName>
                <isActive>false</isActive>
                <label>Single Product</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Product_Specification__c/fields/QUT_Faculty_Capacity__c.field-meta.xml
<CustomField>
    <fullName>QUT_Faculty_Capacity__c</fullName>
    <label>QUT Faculty Capacity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Not Sure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Product_Specification__c/fields/QUT_Staff_Email__c.field-meta.xml
<CustomField>
    <fullName>QUT_Staff_Email__c</fullName>
    <formula>Requestor_Name__r.QUT_Staff_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>QUT Staff Email</label>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Product_Specification__c/fields/QUTeX_Capacity__c.field-meta.xml
<CustomField>
    <fullName>QUTeX_Capacity__c</fullName>
    <label>QUTeX Capacity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Not Sure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Product_Specification__c/fields/Requestor_Internal_External__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Internal_External__c</fullName>
    <label>Requestor Internal/External</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Product_Specification__c/fields/Requestor_Name__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requestor Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Product Specifications (Requestor Name)</relationshipLabel>
    <relationshipName>Product_Specifications</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Product_Specification__c/fields/Requires_Director_Endorsement__c.field-meta.xml
<CustomField>
    <fullName>Requires_Director_Endorsement__c</fullName>
    <label>Requires Director Endorsement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Product_Specification__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Idea</fullName>
                <default>true</default>
                <label>Idea</label>
            </value>
            <value>
                <fullName>Define</fullName>
            </value>
            <value>
                <fullName>Qualify</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Not Proceeding</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Product_Specification__c/fields/Supporting_Comments__c.field-meta.xml
<CustomField>
    <fullName>Supporting_Comments__c</fullName>
    <label>Supporting Comments</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

src/core-crm/objects/Product_Specification__c/recordTypes/OPE.recordType-meta.xml
<RecordType>
    <fullName>OPE</fullName>
    <active>true</active>
    <description>Used to Design products which are the result of an idea request from a faculty.</description>
    <label>OPE</label>
</RecordType>

src/core-crm/classes/Prod_Specs_Send_EmailTest.cls
/**
 * @description Tests the Product Specs Send Email to Requestor flow
 *
 * @see Prod_Specs_Send_EmailTest
 *
 * @author Accenture
 *
 * @history
 *    | Developer                 | Date                  | JIRA     | Change Summary                  |
      |---------------------------|-----------------------|----------|---------------------------------|
      | arsenio.dayrit@qut.edu.au | December 09, 2021     | DEPP-1359| Created file                    | 
      | cadalin@qut.edu.au        | June 12, 2022         | DEPP-2485| Renamed refs to OPE record-type |
      |                           |                       |          |                                 |
*/
@isTest
public with sharing class Prod_Specs_Send_EmailTest {

    private static Id opeProdSpecId = Schema.SObjectType.Product_Specification__c.getRecordTypeInfosByDeveloperName().get('OPE').getRecordTypeId();

    @TestSetup
    static void makeData(){
        TestDataFactoryUser.generateUserQUTeXProgramAdministrator();
    }

    @isTest
    private static void updateProdSpecsFromQualifyToDesignInternal()
    {
        System.runAs(TestDataFactoryUser.selectUserQUTeXProgramAdministrator){
            Flow_Automation_Settings__c customEmail = new Flow_Automation_Settings__c(Name='test',New_Idea_To_Email_Address__c = 'test-qutex@yopmail.com');
            insert customEmail;
            
            Account acc = TestDataFactory.createTestAccountRecords(1).iterator().next();
            insert acc;
    
            List<Contact> conList = TestDataFactory.createTestContactRecords(5);
            for(Integer i =0;i<conList.size();i++){
                conList[i].Email = 'testIdeaFormUser'+i+'@mailinator.com';
                conList[i].QUT_Staff_Email__c = 'testIdeaFormUserQUT'+i+'@mailinator.com';
                conList[i].hed__Preferred_Email__c = 'Alternate Email';
                conList[i].hed__AlternateEmail__c = 'testIdeaFormUser'+i+'@mailinator.com';
            }
            insert conList;
    
            List<Opportunity> oppList = TestDataFactory.createTestOpportunityRecords(5,acc?.Id,conList.iterator().next()?.Id);
            insert oppList;
            

            List<Product_Specification__c> prodSpec = TestDataFactory.createTestProductSpecsRecords(5,conList,oppList);
            for(Integer i =0;i<prodSpec.size();i++){
                prodSpec[i].Requestor_Name__c = conList[i].Id;
                prodSpec[i].Endorsed_by__c = conList[i].Id;
                prodSpec[i].Idea_Summary__c = 'Test';
                prodSpec[i].Requestor_Internal_External__c = 'Internal';
                prodSpec[i].RecordTypeId = opeProdSpecId;
                prodSpec[i].Stage__c = 'Idea';
            }
            insert prodSpec;
            
               
            Test.startTest();
            
            List<Product_Specification__c> getProductSpecsRecord = new List<Product_Specification__c>();
            List<Product_Specification__c> productSpecsRec = new List<Product_Specification__c>([SELECT Id, Stage__c  FROM Product_Specification__c LIMIT 100]);

            for(Product_Specification__c prodSpecs : productSpecsRec){
                prodSpecs.RecordTypeId = opeProdSpecId;
                prodSpecs.Stage__c = 'Qualify';
                prodSpecs.Requestor_Name__c = conList[0].Id;
                getProductSpecsRecord.add(prodSpecs);
            }
            update getProductSpecsRecord;

            List<Product_Specification__c> getUpdatedProductSpecsRecord = new List<Product_Specification__c>();
            List<Product_Specification__c> updatedProductSpecsRec = new List<Product_Specification__c>([SELECT Id, Stage__c  FROM Product_Specification__c LIMIT 100]);

            for(Product_Specification__c uProdSpecs : updatedProductSpecsRec){
                uProdSpecs.Stage__c = 'Design';
                uProdSpecs.Requires_Director_Endorsement__c = 'Yes';
                uProdSpecs.Financial_Viability__c = 'Yes';
                uProdSpecs.Existing_Product__c = 'No';
                uProdSpecs.Market_Need__c = 'Yes';
                uProdSpecs.QUTeX_Capacity__c = 'Yes';
                uProdSpecs.QUT_Faculty_Capacity__c = 'Yes';
                uProdSpecs.Product_Type__c = 'Module';
                uProdSpecs.Endorsed_by__c = conList[0].Id;
                uProdSpecs.Idea_Summary__c = 'Idea Summary Details';
                uProdSpecs.Supporting_Comments__c = 'Supporting Comments';
                getUpdatedProductSpecsRecord.add(uProdSpecs);
            }
            update getUpdatedProductSpecsRecord;

        }
        Test.stopTest();
        System.assertEquals(0, Limits.getEmailInvocations(),'Email invocations is not 0');
    }

    @isTest
    private static void updateProdSpecsFromQualifyToDesignExternal()
    {
        System.runAs(TestDataFactoryUser.selectUserQUTeXProgramAdministrator){
            Flow_Automation_Settings__c customEmail = new Flow_Automation_Settings__c(Name='test',New_Idea_To_Email_Address__c = 'test-qutex@yopmail.com');
            insert customEmail;
            
            Account acc = TestDataFactory.createTestAccountRecords(1).iterator().next();
            insert acc;
    
            List<Contact> conList = TestDataFactory.createTestContactRecords(5);
            for(Integer i =0;i<conList.size();i++){
                conList[i].Email = 'testIdeaFormUser'+i+'@mailinator.com';
                conList[i].QUT_Staff_Email__c = 'testIdeaFormUserQUT'+i+'@mailinator.com';
                conList[i].hed__Preferred_Email__c = 'Alternate Email';
                conList[i].hed__AlternateEmail__c = 'testIdeaFormUser'+i+'@mailinator.com';
            }
            insert conList;
    
            List<Opportunity> oppList = TestDataFactory.createTestOpportunityRecords(5,acc?.Id,conList.iterator().next()?.Id);
            insert oppList;
            

            List<Product_Specification__c> prodSpec = TestDataFactory.createTestProductSpecsRecords(5,conList,oppList);
            for(Integer i =0;i<prodSpec.size();i++){
                prodSpec[i].Requestor_Name__c = conList[i].Id;
                prodSpec[i].Endorsed_by__c = conList[i].Id;
                prodSpec[i].Idea_Summary__c = 'Test';
                prodSpec[i].Requestor_Internal_External__c = 'External';
                prodSpec[i].RecordTypeId = opeProdSpecId;
                prodSpec[i].Stage__c = 'Idea';
            }
            insert prodSpec;
            
               
            Test.startTest();
            
            List<Product_Specification__c> getProductSpecsRecord = new List<Product_Specification__c>();
            List<Product_Specification__c> productSpecsRec = new List<Product_Specification__c>([SELECT Id, Stage__c  FROM Product_Specification__c LIMIT 100]);

            for(Product_Specification__c prodSpecs : productSpecsRec){
                prodSpecs.RecordTypeId = opeProdSpecId;
                prodSpecs.Stage__c = 'Qualify';
                prodSpecs.Requestor_Name__c = conList[0].Id;
                getProductSpecsRecord.add(prodSpecs);
            }
            update getProductSpecsRecord;

            List<Product_Specification__c> getUpdatedProductSpecsRecord = new List<Product_Specification__c>();
            List<Product_Specification__c> updatedProductSpecsRec = new List<Product_Specification__c>([SELECT Id, Stage__c  FROM Product_Specification__c LIMIT 100]);

            for(Product_Specification__c uProdSpecs : updatedProductSpecsRec){
                uProdSpecs.Stage__c = 'Design';
                uProdSpecs.Requires_Director_Endorsement__c = 'Yes';
                uProdSpecs.Financial_Viability__c = 'Yes';
                uProdSpecs.Existing_Product__c = 'No';
                uProdSpecs.Market_Need__c = 'Yes';
                uProdSpecs.QUTeX_Capacity__c = 'Yes';
                uProdSpecs.QUT_Faculty_Capacity__c = 'Yes';
                uProdSpecs.Product_Type__c = 'Module';
                uProdSpecs.Endorsed_by__c = conList[0].Id;
                uProdSpecs.Idea_Summary__c = 'Idea Summary Details';
                uProdSpecs.Supporting_Comments__c = 'Supporting Comments';
                getUpdatedProductSpecsRecord.add(uProdSpecs);
            }
            update getUpdatedProductSpecsRecord;

        }
        Test.stopTest();
        System.assertEquals(0, Limits.getEmailInvocations(),'Email invocations is not 0');
    }
   
}