src-env-specific-pre/objects/Contact/fields/hed__AlternateEmail__c.field-meta.xml
<CustomField>
    <fullName>hed__AlternateEmail__c</fullName>
    <description>An optional email address not captured in other email fields.</description>
    <inlineHelpText>An optional email address not captured in other email fields.</inlineHelpText>
    <label>Alternate Email</label>
    <type>Email</type>
</CustomField>

src/core-crm/main/objects/Contact/fields/hed__Preferred_Email__c.field-meta.xml
<CustomField>
    <fullName>hed__Preferred_Email__c</fullName>
    <description>The email (University, Work, Alternate) that this Contact prefers you to use.</description>
    <inlineHelpText>The email (University, Work, Alternate) that this Contact prefers you to use.</inlineHelpText>
    <label>Preferred Email</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>University Email</fullName>
            </value>
            <value>
                <fullName>Work Email</fullName>
            </value>
            <value>
                <fullName>Alternate Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/main/objects/Contact/fields/QUT_Learner_Email__c.field-meta.xml
<CustomField>
    <fullName>QUT_Learner_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>QUT Learner Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

src/core-crm/main/objects/Contact/fields/QUT_Staff_Email__c.field-meta.xml
<CustomField>
    <fullName>QUT_Staff_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>QUT Staff Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

src/core-crm/objects/Contact/fields/Work_Email__c.field-meta.xml
<CustomField>
    <fullName>Work_Email__c</fullName>
    <description>The work email for this person</description>
    <externalId>true</externalId>
    <inlineHelpText>This field captures the work email of the contact.</inlineHelpText>
    <label>Work Email</label>
    <type>Email</type>
</CustomField>

src/core-crm/objects/hed__Affiliation__c/hed__Affiliation__c.object-meta.xml
<CustomObject>
    <description>Connection between a Contact and an Account.</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>AF-{000000}</displayFormat>
        <label>Affiliation Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/classes/AffiliationTriggerHandlerTest.cls
/**
 * @description Test Class for AffiliationTriggerHander
 *
 * @see AffiliationTriggerHander
 *
 * @author Accenture
 *
 * @history
 *    | Developer                 | Date                  | JIRA         | Change Summary                              |
      |---------------------------|-----------------------|--------------|---------------------------------------------|
      | mark.j.mahilum            | July 18,2023          | DEPP-5799    | Created file                                |
*/
@isTest
private class AffiliationTriggerHandlerTest {
    private static final String FIRSTNAME = 'TestfirstName';
    private static final String LASTNAME = 'Testlastname';
    private static final String EMAIL = 'testmail@mail.test';
    private static final String BIRTHDAY = '2000-06-28';
    private static Integer recordsCount = 20;
    
    @testSetup
    static void testSetup() {
        TestDataFactory.generateTestUsers(new List<String>{ 'QUTeX_Program_Administrator' });      
        System.runAs(TestDataFactory.getProgramAdminUser()) {  
            Account acc = TestDataFactory.createTestAccount(false);
            acc.RecordTypeId = AccountsDAO.ACCT_BUSINESS_ORG_ID;
            insert acc;
            
            List<hed__Affiliation__c> affliatedContacts = TestDataFactory.createTestAffliatedContactRecords(1, acc.Id);           
            insert affliatedContacts;
        }
    }
    
    @isTest
    private static void testAffiliationWithContact() {
        System.runAs(TestDataFactory.getProgramAdminUser()) {            
            Account acc = TestDataFactory.createTestAccount(false);
            acc.RecordTypeId = AccountsDAO.ACCT_BUSINESS_ORG_ID;
            insert acc;
            
            List<Contact> newContacts = createTestContactRecords(0, 1);     
            newContacts[0].AccountId = acc.Id;
            ContactsDAO.newInstance().insertRecords(newContacts, false, AccessLevel.SYSTEM_MODE);

            List<hed__Affiliation__c> affliatedContacts = TestDataFactory.createTestAffliatedContactRecords(1, acc.Id);
            affliatedContacts[0].hed__Contact__c = newContacts[0].Id;
            
            Test.startTest();
            Database.SaveResult[] srList = Database.insert(affliatedContacts);
            Test.stopTest();
            for (Database.SaveResult sr : srList) {
                System.assert(sr.isSuccess(), 'A record was not saved.');
            }
        }
    }    
    
    @isTest
    private static void testUpdateAffiliationWithContact() {
        System.runAs(TestDataFactory.getProgramAdminUser()) {   
            
            List<Contact> newContacts = createTestContactRecords(0, 1);     
            ContactsDAO.newInstance().insertRecords(newContacts, false, AccessLevel.SYSTEM_MODE);
            
			List<hed__Affiliation__c> updateAffliatedContacts = [SELECT Id FROM hed__Affiliation__c]; 	
            updateAffliatedContacts[0].hed__Contact__c = newContacts[0].Id;
            
            Test.startTest();
            Database.SaveResult[] srList = Database.update(updateAffliatedContacts);
            Test.stopTest();
            
            for (Database.SaveResult sr : srList) {
                System.assert(sr.isSuccess(), 'A record was not updated.');
            }
        }
    }  
    
    @isTest
    private static void testAffiliationWithOutContact() {
        System.runAs(TestDataFactory.getProgramAdminUser()) {            
            Account acc = TestDataFactory.createTestAccount(false);
            acc.RecordTypeId = AccountsDAO.ACCT_BUSINESS_ORG_ID;
            insert acc;
            
            List<hed__Affiliation__c> affliatedContacts = TestDataFactory.createTestAffliatedContactRecords(1, acc.Id);            
            insert affliatedContacts;
            
            Test.startTest();
            Database.SaveResult[] srList = Database.update(affliatedContacts);
            Test.stopTest();
            
            for (Database.SaveResult sr : srList) {
                System.assert(sr.isSuccess(), 'A record was not updated.');
            }
        }
    }  
    
    private static List<Contact> createTestContactRecords(
        Integer startAtCount,
        Integer endBeforeCount
    ) {
        List<Contact> newContacts = new List<Contact>();
        for (Integer i = startAtCount; i < endBeforeCount; i++) {
            newContacts.add(
                new Contact(
                    FirstName = FIRSTNAME + i,
                    LastName = i + LASTNAME,
                    BirthDate = Date.valueOf(BIRTHDAY),
                    Email = i + EMAIL,
                    QUT_Learner_Email__c = 'learner' + i + EMAIL,
                    QUT_Staff_Email__c = 'staff' + i + EMAIL,
                    Work_Email__c = 'work' + i + EMAIL,
                    hed__Preferred_Email__c = 'Alternate Email',
                    hed__AlternateEmail__c = i + EMAIL,
                    RecordTypeId = ContactsDAO.PERSON_RECORDTYPE_ID 
                )
            );
        }
        return newContacts;
    }
}