src/core-crm/objects/SMS_Template__c/SMS_Template__c.object-meta.xml
<CustomObject>
    <label>SMS Template</label>
    <nameField>
        <label>SMS Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/SMS_Template__c/fields/Cadence_Step_Name__c.field-meta.xml
<CustomField>
    <fullName>Cadence_Step_Name__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>This field is unique</description>
    <label>Cadence Step Name</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/core-crm/objects/SMS_Template__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to maintain records if they are active</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/SMS_Template__c/fields/Message_Content__c.field-meta.xml
<CustomField>
    <fullName>Message_Content__c</fullName>
    <description>The content of the message</description>
    <label>Message Content</label>
    <length>160</length>
    <type>Text</type>
</CustomField>

src/core-crm/classes/SMSTemplatesDAO.cls
/**
 * @description DAO class for SMS_Template__c
 * 
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | mark.j.mahilum                 | Oct 25, 2023          | DEPP-6985              | Created file                 |
 */
public with sharing class SMSTemplatesDAO extends DmlBase implements ISMSTemplatesDAO {
    
  public Schema.SObjectType getSObjectType(){
    return SMS_Template__c.SObjectType;
  }
    
  public static ISMSTemplatesDAO newInstance(){
    return (ISMSTemplatesDAO) ImplementationSelector.DAO.newInstance(SMS_Template__c.SObjectType);
  }
    
  public List<SMS_Template__c> getActiveSMSTemplates(AccessLevel accessLevel) {
      return Database.query(
          'SELECT Id, Cadence_Step_Name__c, Message_Content__c ' + 
          'FROM SMS_Template__c ' + 
          'WHERE IsActive__c = TRUE', accessLevel
      );        
  }   
}