src/core-crm/objects/Donation_Cause__c/Donation_Cause__c.object-meta.xml
<CustomObject>
    <description>Donation Cause stores the donation cause (or ‘designation’) data that a donor can donate to as well as data relating to setting up a new donation cause and publishing the cause on the QUT website.</description>
    <label>Donation Cause</label>
    <nameField>
        <label>Donation Cause</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Donation Causes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Donation_Cause__c/fields/Donation_Cause__c.field-meta.xml
<CustomField>
    <fullName>Donation_Cause__c</fullName>
    <description>The Donation Cause name.</description>
    <inlineHelpText>The Donation Cause name.</inlineHelpText>
    <label>Donation Cause</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Donation_Cause__c/fields/Is_For_Public_Giving__c.field-meta.xml
<CustomField>
    <fullName>Is_For_Public_Giving__c</fullName>
    <description>Identifies whether the Donation Cause is intended to be published on the QUT Giving webpage.</description>
    <inlineHelpText>Identifies whether the Donation Cause is intended to be published on the QUT Giving webpage.</inlineHelpText>
    <label>Is For Public Giving</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Product2/fields/Donation_Cause__c.field-meta.xml
<CustomField>
    <fullName>Donation_Cause__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Donation Cause record.</description>
    <label>Donation Cause</label>
    <referenceTo>Donation_Cause__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/classes/Donation_Cause_Create_Child_Product_Test.cls
/**
 * @description test class for Donation_Cause_Create_Child_Product Flow
 * 
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | kathleen.mae.caceres           | March, 20, 2024       | DEPP-8201              | Created file                 | 
 */
@isTest
private class Donation_Cause_Create_Child_Product_Test {
    public static final String DC_PUBLICGIVING = 'Yes';
    
    @testSetup
    static void setupData() {
        Test.startTest();
        TestDataFactory.generateTestUsers(new List<String>{ 'QUT_Donor_Engagement_Manager' });
        Test.stopTest();
    }

    @isTest
    private static void createDonCauseChildProd() {
        System.runAs(TestDataFactory.getDonorEngagementManager()) {
            List<Donation_Cause__c> donationCauseList = TestDataFactory.createDonationCauseRecords(
                100
            );

            DonationCausesDAO.newInstance()
                .insertRecords(donationCauseList, false, AccessLevel.USER_MODE);

            for (Donation_Cause__c dc : donationCauseList) {
                dc.Is_For_Public_Giving__c = DC_PUBLICGIVING;
            }

            Test.startTest();
            DonationCausesDAO.newInstance()
                .updateRecords(donationCauseList, false, AccessLevel.USER_MODE);
            Test.stopTest();

            List <Product2> prodList =  ProductsDAO.newInstance().getProductById(new Map<Id, Donation_Cause__c>(donationCauseList).keySet(), AccessLevel.USER_MODE);
            
            for (Donation_Cause__c donCauseRec: donationCauseList) {
                Boolean isCreated = checkDonationCauseId (donCauseRec.Id, prodList);

                if(!isCreated){
                    System.AssertEquals(
                        donCauseRec.Is_For_Public_Giving__c,
                        DC_PUBLICGIVING,
                        'Product has been created for Donation Cause Record'
                    );
                } else {
                    System.AssertEquals(
                        donCauseRec.Is_For_Public_Giving__c,
                        DC_PUBLICGIVING,
                        'Product should be created'
                    );
                }     
            }
        }
    }

    private static Boolean checkDonationCauseId (Id donationCauseId, List<Product2> productList){
        Boolean isCreated = False;
        for (Product2 eachProd : productList) {
            if (eachProd.Donation_Cause__c == donationCauseId) {
                isCreated = true;
            } 
        } return isCreated;
    }
}