src/core-crm/main/objects/Account/fields/ABN__c.field-meta.xml
<CustomField>
    <fullName>ABN__c</fullName>
    <description>ABN (Australian Business Number) validated against the Australian Business Register</description>
    <label>ABN</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

src/core-crm/main/objects/Account/fields/AccountABNEntity_Validation__c.field-meta.xml
<CustomField>
    <fullName>AccountABNEntity_Validation__c</fullName>
    <label>AccountABNEntity Validation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Loqate_Validation</valueSetName>
    </valueSet>
</CustomField>

src/core-crm/objects/Lead/fields/ABN__c.field-meta.xml
<CustomField>
    <fullName>ABN__c</fullName>
    <description>Australian Business Number</description>
    <label>ABN</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Loqate_Component__mdt/Loqate_Component__mdt.object-meta.xml
<CustomObject>
    <label>Loqate Component</label>
    <pluralLabel>Loqate Components</pluralLabel>
</CustomObject>

src-env-specific-pre/objects/Loqate_Component__mdt/fields/Company_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Company_Mapping__c</fullName>
    <inlineHelpText>Value should be in JSON format with the following attributes:  label, apiName, statusValidationField, loqateRequest, and loqateResponse</inlineHelpText>
    <label>Company Mapping</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/core-crm/main/globalValueSets/Loqate_Validation.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>Valid</fullName>
    </customValue>
    <customValue>
        <fullName>Not Valid</fullName>
    </customValue>
    <description>Confirming that this has been validated from Loqate</description>
    <masterLabel>Loqate Validation</masterLabel>
</GlobalValueSet>

src/core-crm/classes/ContactInformationValidationCtrlTest.cls
/**
 * @description Tests the Contact Information Validation Controller class 
 *
 * @see ContactInformationValidationCtrl
 *
 * @author Accenture
 *
 * @history
 *    | Developer                 | Date                  | JIRA     | Change Summary                  |
      |---------------------------|-----------------------|----------|---------------------------------|
      | angelika.j.s.galang       | September 3, 2021     | DEP1-156 | Created file                    | 
      | angelika.j.s.galang       | September 8, 2021     | DEP1-157 | Added test methods for callouts | 
*/
@isTest
private class ContactInformationValidationCtrlTest {
    
    private static final String ACCOUNT_API_NAME = Account.SObjectType.getDescribe(SObjectDescribeOptions.DEFERRED).getLocalName();
	private static final String OPP_API_NAME = Opportunity.SObjectType.getDescribe(SObjectDescribeOptions.DEFERRED).getLocalName();
    private static final String AURA_EX_MSG = 'Error while getting field mapping.';
    private static final String ACCOUNT_MAPPING = '{"label": "ABN","apiName":"ABN__c","statusValidationField":"AccountABNEntity_Validation__c","loqateRequest":"name","loqateResponse":"status"}';
    private static final String STR_COMPANY_MAPPING = 'Company_Mapping__c';

    @TestSetup
    static void makeData(){
        TestDataFactoryUser.generateUserQUTeXProgramAdministrator();
    }

    @isTest
    private static void getMappingSuccessTest(){
        Test.startTest();
        System.runAs(TestDataFactoryUser.selectUserQUTeXProgramAdministrator){
            String mappingTest = ContactInformationValidationCtrl.getMapping(ACCOUNT_API_NAME,STR_COMPANY_MAPPING);
            Loqate_Component__mdt loqate = (Loqate_Component__mdt) JSON.deserialize(mappingTest,Loqate_Component__mdt.class); 
            System.assertEquals(ACCOUNT_MAPPING, loqate.get(STR_COMPANY_MAPPING), 'Mapping did not match expected.');
        }
        Test.stopTest();
    }

    @isTest
    private static void getMappingErrorTest(){
        Test.startTest();
        System.runAs(TestDataFactoryUser.selectUserQUTeXProgramAdministrator){
            try{
                ContactInformationValidationCtrl.getMapping(OPP_API_NAME,STR_COMPANY_MAPPING);
            }catch(AuraHandledException ex){
                System.assert(ex.getMessage().contains(AURA_EX_MSG), 'Exception did not match expected.');
            }
        }
        Test.stopTest();
    }

    @isTest
    private static void validatePhoneFieldsTest(){
        Test.startTest();
        System.runAs(TestDataFactoryUser.selectUserQUTeXProgramAdministrator){
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
            String phoneValidateRequest = '[{"loqateRequest":"fullPhone","loqateResponse":"","locale":"AU","statusValidationField":"","value":"1234"}]';
            ContactInformationValidationCtrl.PayloadResponse phonePayloadResponse = getPayloadResponse(phoneValidateRequest);
            System.assertEquals('1234', phonePayloadResponse.fullPhone, 'phone doesnt match');
            System.assertEquals('AU', phonePayloadResponse.country, 'country doesnt match');
            System.assertEquals('connected|Network confirmed connection', phonePayloadResponse.phoneStatus, 'phoneStatus doesnt match');
        }
        Test.stopTest();
    }

    @isTest
    private static void validateCompanyFieldsTest(){
        Test.startTest();
        System.runAs(TestDataFactoryUser.selectUserQUTeXProgramAdministrator){
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
            String companyValidateRequest = '[{"loqateRequest":"name","loqateResponse":"","locale":null,"statusValidationField":"","value":"54321"}]';
            ContactInformationValidationCtrl.PayloadResponse companyPayloadResponse = getPayloadResponse(companyValidateRequest);
            System.assertEquals('54321', companyPayloadResponse.abn, 'abn doesnt match');
            System.assertEquals('testEntityName', companyPayloadResponse.name, 'entity name doesnt match');
        }
        Test.stopTest();
    }

    @isTest
    private static void allowDmlWithDuplicatesTest(){
        Test.startTest();
        System.runAs(TestDataFactoryUser.selectUserQUTeXProgramAdministrator){
            Lead leadRecord = TestDataFactory.createTestLeadRecords(1).iterator().next();
            leadRecord.Phone = '123';
            ContactInformationValidationCtrl.allowDmlWithDuplicates(leadRecord);
            System.assertEquals('123', leadRecord.Phone, 'Update was not successful as expected');
        }
        Test.stopTest();
    }

    private static ContactInformationValidationCtrl.PayloadResponse getPayloadResponse(String validateRequest){
        String payloadResponseList = ContactInformationValidationCtrl.validateFields(validateRequest);
        List<ContactInformationValidationCtrl.PayloadResponse> payloadResponseListParsed = 
            (List<ContactInformationValidationCtrl.PayloadResponse>) JSON.deserialize(payloadResponseList, List<ContactInformationValidationCtrl.PayloadResponse>.class);

        return payloadResponseListParsed.iterator().next();
    }
}