src/core-crm/main/objects/Account/fields/Company_Category__c.field-meta.xml
<CustomField>
    <fullName>Company_Category__c</fullName>
    <description>Business specific set of categories used for classifying companies to assist with automating work allocation.</description>
    <label>Company Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Education Provider</fullName>
            </value>
            <value>
                <fullName>Government Body - Commonwealth</fullName>
            </value>
            <value>
                <fullName>Government Body - International</fullName>
            </value>
            <value>
                <fullName>Government Body - Local</fullName>
            </value>
            <value>
                <fullName>Government Body - State/Territory</fullName>
            </value>
            <value>
                <fullName>Not For Profit</fullName>
            </value>
            <value>
                <fullName>Professional Association</fullName>
            </value>
            <value>
                <fullName>Trust or Foundation</fullName>
            </value>
            <value>
                <fullName>University</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/main/objects/Contact/fields/LinkedIn_Profile_URL__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn_Profile_URL__c</fullName>
    <label>LinkedIn Profile URL</label>
    <type>Url</type>
</CustomField>

src/core-crm/objects/Lead/fields/Company_Category__c.field-meta.xml
<CustomField>
    <fullName>Company_Category__c</fullName>
    <label>Company Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Education Provider</fullName>
            </value>
            <value>
                <fullName>Government Body - Commonwealth</fullName>
            </value>
            <value>
                <fullName>Government Body - International</fullName>
            </value>
            <value>
                <fullName>Government Body - Local</fullName>
            </value>
            <value>
                <fullName>Government Body - State/Territory</fullName>
            </value>
            <value>
                <fullName>Not For Profit</fullName>
            </value>
            <value>
                <fullName>Professional Association</fullName>
            </value>
            <value>
                <fullName>Trust or Foundation</fullName>
            </value>
            <value>
                <fullName>University</fullName>
            </value>
            <value>
                <fullName>Test Value 1</fullName>
                <isActive>false</isActive>
                <label>Test Value 1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/lead-management/main/objects/Lead/fields/LinkedIn_Profile_URL__c.field-meta.xml
<CustomField>
    <fullName>LinkedIn_Profile_URL__c</fullName>
    <description>The Lead&apos;s LinkedIn Profile address</description>
    <label>LinkedIn Profile URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Potential_Duplicate__c/Potential_Duplicate__c.object-meta.xml
<CustomObject>
    <label>Potential Duplicate</label>
    <nameField>
        <displayFormat>PD-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Potential Duplicates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Potential_Duplicate__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to existing contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Potential Duplicates</relationshipLabel>
    <relationshipName>Potential_Duplicates</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Potential_Duplicate__c/fields/Duplicate_Lead__c.field-meta.xml
<CustomField>
    <fullName>Duplicate_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to newly created lead</description>
    <label>Duplicate Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Potential Duplicates (Duplicate Lead)</relationshipLabel>
    <relationshipName>Potential_Duplicates1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Potential_Duplicate__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to existing lead</description>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Potential Duplicates</relationshipLabel>
    <relationshipName>Potential_Duplicates</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/classes/LeadPotentialDuplicateCtrlTest.cls
/**
 * @description Test Class for Lead Potential Duplicate Ctrl
 *
 * @see ../class/LeadPotentialDuplicateCtrl
 *
 * @author Accenture
 *
 * @history
 *    | Developer                 | Date                  | JIRA         | Change Summary                              |
      |---------------------------|-----------------------|--------------|---------------------------------------------|
      | eccarius.munoz            | May 27, 2022          | DEPP-1778    | Created file                                |
      |                           |                       |              |                                             |
      |                           |                       |              |                                             |
*/
@isTest
private class LeadPotentialDuplicateCtrlTest {
    private @testSetup
    static void makeData(){
        List<Account> accounts = TestDataFactory.createTestAccountRecords(2);          
        List<Lead> leads = TestDataFactory.createTestLeadRecords(2);
        for(Lead lead : leads){   
            lead.Company_Category__c = 'Corporate';
            lead.LinkedIn_Profile_URL__c = 'test@test.com';
        }        
        insert accounts;
        insert leads;

        List<Contact> contacts = TestDataFactory.createTestContactRecords(1);        
        insert contacts;

        List<Potential_Duplicate__c> potentialDuplicates = new List<Potential_Duplicate__c>();
        potentialDuplicates.add(new Potential_Duplicate__c(Lead__c  = leads[0].Id, Duplicate_Lead__c = leads[1].Id));
        potentialDuplicates.add(new Potential_Duplicate__c(Duplicate_Lead__c = leads[0].Id, Contact__c = contacts[0].Id));
        insert potentialDuplicates;

        TestDataFactoryUser.generateUserSystemAdministrator();
    }

    @isTest
    static void getSelectedLeadTest(){
    final User PORTAL_SYS_ADMIN = TestDataFactoryUser.selectUserSystemAdministrator;
		System.runAs(PORTAL_SYS_ADMIN) {
            List<Lead> leads = [SELECT Id FROM Lead];
            Id recordId = leads[0].Id;
            Test.startTest();
            List<LeadPotentialDuplicateCtrl.LeadContactWrapper> leadList = LeadPotentialDuplicateCtrl.getSelectedLead(recordId);
            Test.stopTest();
            System.assertEquals(true, leadList.size()>0, 'No lead record retrieved.');
        }
    }

    @isTest
    static void getLeadPotentialDuplicateTest(){
    final User PORTAL_SYS_ADMIN = TestDataFactoryUser.selectUserSystemAdministrator;
		System.runAs(PORTAL_SYS_ADMIN) {
            List<Lead> leads = [SELECT Id FROM Lead];
            Id recordId = leads[0].Id;
            Test.startTest();
            List<LeadPotentialDuplicateCtrl.LeadContactWrapper> leadList = LeadPotentialDuplicateCtrl.getLeadPotentialDuplicate(recordId);
            Test.stopTest();
            System.assertEquals(true, leadList.size() > 0, 'No dupllicate record(s) retrieved.');
        }
    }

    @isTest
    static void mergeLeadsTest(){
    final User PORTAL_SYS_ADMIN = TestDataFactoryUser.selectUserSystemAdministrator;
		System.runAs(PORTAL_SYS_ADMIN) {
            List<Lead> leads = [SELECT Id FROM Lead];
            Id recordId = leads[0].Id;
            List<LeadPotentialDuplicateCtrl.LeadContactWrapper> leadList = LeadPotentialDuplicateCtrl.getLeadPotentialDuplicate(recordId);
            Test.startTest();
            String response = LeadPotentialDuplicateCtrl.mergeLeads(leadList);
            Test.stopTest();
            System.assertEquals('Success', response, 'Failed to save records.');
        }
    }
}