src/core-crm/main/objects/Account/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Account/fields/Organization_Unit_Level__c.field-meta.xml
<CustomField>
    <fullName>Organization_Unit_Level__c</fullName>
    <description>The level (1,2,3) of the organizational unit within the QUT Organizational hierarchy.</description>
    <label>Organization Unit Level</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Account/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Facilitator_Bio__c/Facilitator_Bio__c.object-meta.xml
<CustomObject>
    <label>Facilitator Bio</label>
    <nameField>
        <displayFormat>FN-{00000}</displayFormat>
        <label>Facilitator Bio Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Facilitator Bios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Facilitator_Bio__c/fields/Facilitator__c.field-meta.xml
<CustomField>
    <fullName>Facilitator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facilitator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Facilitator Bios</relationshipLabel>
    <relationshipName>Facilitator_Bios</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course__c/hed__Course__c.object-meta.xml
<CustomObject>
    <description>Academic Course offered by a Department or School, for example, English 101 or Ancient History.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course__c/fields/Delivery_Type__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Type__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Face to Face</fullName>
            </value>
            <value>
                <fullName>Virtual Classroom</fullName>
            </value>
            <value>
                <fullName>Blended</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Course__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/hed__Course__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <description>The department (Account record) that offers this Course.</description>
    <inlineHelpText>The department (Account record) that offers this Course.</inlineHelpText>
    <label>Department</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/core-crm/objects/hed__Course__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/hed__Course_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Represents a connection to a Course Offering.</description>
    <label>Course Connection</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Course Connection ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Enrollment__c/fields/Facilitator_Bio__c.field-meta.xml
<CustomField>
    <fullName>Facilitator_Bio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facilitator Bio</label>
    <referenceTo>Facilitator_Bio__c</referenceTo>
    <relationshipLabel>Course Connections</relationshipLabel>
    <relationshipName>Course_Connections</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Academic Program that the student or faculty member is associated with.</description>
    <inlineHelpText>The Academic Program that the student or faculty member is associated with.</inlineHelpText>
    <label>Contact&apos;s Academic Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Course Connections</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/hed__Course_Offering__c.field-meta.xml
<CustomField>
    <fullName>hed__Course_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Course Offering the student or faculty member is involved with.</description>
    <inlineHelpText>The Course Offering the student or faculty member is involved with.</inlineHelpText>
    <label>Course Offering ID</label>
    <referenceTo>hed__Course_Offering__c</referenceTo>
    <relationshipLabel>Course Connection</relationshipLabel>
    <relationshipName>Course_Enrollment</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/hed__Course_Offering__c.object-meta.xml
<CustomObject>
    <description>Joins Courses and Terms to contain information related to a single occurrence of a Course.</description>
    <label>Course Offering</label>
    <nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Offering__c/fields/Delivery_Type__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Type__c</fullName>
    <description>This will be how the course will be delivered and location for face-to-face.</description>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online Classroom</fullName>
            </value>
            <value>
                <fullName>Online Self-paced</fullName>
            </value>
            <value>
                <fullName>Brisbane Classroom</fullName>
            </value>
            <value>
                <fullName>Canberra Classroom</fullName>
            </value>
            <value>
                <fullName>Melbourne Classroom</fullName>
            </value>
            <value>
                <fullName>Sydney Classroom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Course__c.field-meta.xml
<CustomField>
    <fullName>hed__Course__c</fullName>
    <description>Lookup to the Course record that this Course Offering is associated with.</description>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>
 

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Term__c.field-meta.xml
<CustomField>
    <fullName>hed__Term__c</fullName>
    <description>Lookup to the Term record that represents when this Course Offering takes place.</description>
    <label>Term</label>
    <referenceTo>hed__Term__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>
 

src/core-crm/objects/hed__Course_Offering__c/fields/Registration_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_End_Date__c</fullName>
    <label>Registration End Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/fields/Registration_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Start_Date__c</fullName>
    <label>Registration Start Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/hed__Program_Plan__c/hed__Program_Plan__c.object-meta.xml
<CustomObject>
    <description>Links Courses to an Academic Program to create a path for students to follow. An Academic Program can list multiple Courses, and a Course can be associated with multiple Academic Programs.</description>
    <label>Program Plan</label>
    <nameField>
        <label>Program Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Program_Plan__c/fields/Delivery_Type__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Type__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Face To Face</fullName>
            </value>
            <value>
                <fullName>Virtual Classroom</fullName>
            </value>
            <value>
                <fullName>Blended</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Program_Plan__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Academic Program this Program Plan is for, for example, BA in Philosophy.</description>
    <inlineHelpText>The Academic Program this Program Plan is for, for example, BA in Philosophy.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Program_Plan__c/fields/Product_Request__c.field-meta.xml
<CustomField>
    <fullName>Product_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the related Product Request record of the Program Plan.</description>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Program_Plan__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <description>This record type will be used to create a Program. This can be a combination of a Unit, a Module, a Short Course, or an Activity.</description>
    <label>Program</label>
</RecordType>

src/core-crm/objects/hed__Term__c/hed__Term__c.object-meta.xml
<CustomObject>
    <description>Unit of time in which academic activities are taking place.</description>
    <label>Term</label>
    <nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Term__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <description>The Academic Program, Department, or entire Educational Institution this Term applies to. Select the Account that represents your Educational Institution if Terms are consistent across all Programs and Departments in your school.</description>
    <inlineHelpText>The Academic Program, Department, or entire Educational Institution this Term applies to. Select the Account that represents your Educational Institution if Terms are consistent across all Programs and Departments in your school.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Terms</relationshipLabel>
    <relationshipName>Terms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/core-crm/objects/Program_Offering__c/Program_Offering__c.object-meta.xml
<CustomObject>
    <label>Program Offering</label>
    <nameField>
        <label>Program Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/Program_Offering__c/fields/Delivery_Type__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Type__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online Classroom</fullName>
            </value>
            <value>
                <fullName>Online Self-paced</fullName>
            </value>
            <value>
                <fullName>Brisbane Classroom</fullName>
            </value>
            <value>
                <fullName>Canberra Classroom</fullName>
            </value>
            <value>
                <fullName>Cairns Classroom</fullName>
            </value>
            <value>
                <fullName>NSW Classroom</fullName>
            </value>
            <value>
                <fullName>Melbourne Classroom</fullName>
                <isActive>false</isActive>
                <label>Melbourne Classroom</label>
            </value>
            <value>
                <fullName>Sydney Classroom</fullName>
                <isActive>false</isActive>
                <label>Sydney Classroom</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Program_Offering__c/fields/Registration_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_End_Date__c</fullName>
    <label>Registration End Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/classes/ProductOfferingCtrlTest.cls
/**
 * @description Test class for Product Offering Controller
 *
 * @see ProductOfferingCtrl
 *
 * @author Accenture
 *
 * @history
 *    | Developer                 | Date                  | JIRA         | Change Summary                                               |
      |---------------------------|-----------------------|--------------|--------------------------------------------------------------|
      | aljohn.motas              | February 8, 2022      | DEPP-1258    | Created file                                                 |
      | kenneth.f.alsay           | December 19, 2023     | DEPP-7447    | Updated courseOffering creation in updateCourseOfferingsTest |
      |                           |                       |              |                                                              |
*/
@isTest
public class ProductOfferingCtrlTest {
    private static final String STR_QUTEXPROD = 'QUTeX Products';
    private static final String STR_QUTEX = 'QUTeX';
    private static final String STR_QUTEX_TERM = STR_QUTEX + ' Term';
    private static final String ACCT_UNIV_DEP = System.Label.RT_Account_University_Department;
    private static final String ACCT_BUSI_ORG = System.Label.RT_Account_Business_Org;
    private static final Id ACCT_UNIV_DEP_ID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(ACCT_UNIV_DEP).getRecordTypeId();
    private static final Id ACCT_BUSI_ORG_ID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(ACCT_BUSI_ORG).getRecordTypeId();
    private static final Id PERSON_RECORDTYPE_ID = ContactsDAO.PERSON_RECORDTYPE_ID;

    @testSetup static void setup() {
        TestDataFactoryUser.generateUserSystemAdministrator();
    }
    
    @isTest
    static void getTermIdTest() {
        System.runAs(TestDataFactoryUser.selectUserSystemAdministrator){
            Account acc = TestDataFactory.createTestAccountRecords(1).iterator().next();
            acc.Name = STR_QUTEXPROD;
            acc.RecordTypeId = ACCT_BUSI_ORG_ID;
            insert acc;

            Test.startTest();
            String termId = ProductOfferingCtrl.getTermId();
            Test.stopTest();
            System.assertNotEquals(null, termId,'Term ID not as expected');
        }
    }

    @isTest
    static void getSearchedFacilitatorTest() {
        System.runAs(TestDataFactoryUser.selectUserSystemAdministrator){
            Contact con = TestDataFactory.createTestContactRecords(1).iterator().next();
            con.FirstName = 'Test';
            con.LastName = 'Contact';
            insert con;
            Facilitator_Bio__c faciBio = new Facilitator_Bio__c(
                Facilitator__c = con?.Id
            );
            insert faciBio;

            Test.startTest();
            List<Map<String,String>> facilitators = ProductOfferingCtrl.getSearchedFacilitator('test',new List<Id>{});
            Test.stopTest();

            System.assertEquals('Test Contact', facilitators[0].get('label'),'Facilitator Name did not match as expected');
        }
    }

    @isTest
    static void getSearchedContactTest() {
        System.runAs(TestDataFactoryUser.selectUserSystemAdministrator){
            Contact con = TestDataFactory.createTestContactRecords(1).iterator().next();
            con.FirstName = 'Test';
            con.LastName = 'Contact';
            con.RecordTypeId = PERSON_RECORDTYPE_ID;
            insert con;

            Test.startTest();
            Id [] fixedSearchResults= new Id[1];
            fixedSearchResults[0] = con.Id;
            Test.setFixedSearchResults(fixedSearchResults);
            List<Map<String,String>> contacts = ProductOfferingCtrl.getSearchContacts('test');
            Test.stopTest();

            System.assertEquals('Test Contact', contacts[0].get('label'),'Contact Name did not match as expected');
        }
    }

    @isTest
    static void updateFacilitatorDataTest() {
        System.runAs(TestDataFactoryUser.selectUserSystemAdministrator){
            Contact con = TestDataFactory.createTestContactRecords(1).iterator().next();
            insert con;
            List<Product_Request__c> prodRequest = TestDataFactory.createTestProductRequestRecords(1);
            insert prodRequest;
            List<Account> accounts = TestDataFactory.createTestAccountRecords(1);
            for(Account acc : accounts){
                acc.RecordTypeId = ACCT_UNIV_DEP_ID;
                acc.Organization_Unit_Level__c = '2';
            }
            insert accounts;
            List<hed__Course__c> courses = TestDataFactory.createTestCourseRecords(25,accounts[0].Id,prodRequest[0].Id);
            insert courses;
            List<hed__Term__c> terms = TestDataFactory.createTestTermRecords(25,accounts[0].Id);
            insert terms;
            List<hed__Course_Offering__c> courseOfferings = TestDataFactory.createTestCourseOfferingRecord(25,courses,terms);
            insert courseOfferings;
            List<hed__Program_Plan__c> programPlans = TestDataFactory.createTestProgramPlanRecords(25);
            insert programPlans;
            List<hed__Course_Enrollment__c> courseConnections =  TestDataFactory.createTestCourseConnectionRecord(25,con?.Id,courseOfferings);
            insert courseConnections;
            courseConnections[0].hed__Account__c = accounts[0]?.Id;
            List<Facilitator_Bio__c> faciBios = new List<Facilitator_Bio__c>();
            Map<String,List<SObject>> faciData = new Map<String,List<SObject>>();
            faciData.put('courseConnections',courseConnections);
            faciData.put('facilitatorBios',faciBios);
            Test.startTest();
            ProductOfferingCtrl.updateFacilitatorData(faciData);
            Test.stopTest();
            List<hed__Course_Enrollment__c> updatedCourseConnections = [Select hed__Account__c From hed__Course_Enrollment__c Where hed__Account__c =: accounts[0].Id];
            System.assertEquals(1, updatedCourseConnections.size(), 'updatedCourseConnections is not equal to 1');
        }
    }


    @isTest
    static void getProductOfferingDataTest() {
        System.runAs(TestDataFactoryUser.selectUserSystemAdministrator){
            Test.startTest();
            List<Product_Request__c> prodRequest =new List<Product_Request__c>();

            final String PROGRAM_OFFERING_FIELDS = 'Id,Delivery_Type__c,Start_Date__c,Registration_Start_Date__c,'+
                'Registration_End_Date__c,End_Date__c,hed_Program_Plan__c';
            String productRequestId;
            Map<String,String> parentInfo = new Map<String,String>();
            parentInfo.put('objectType','hed__Program_Plan__c');
            parentInfo.put('field','Product_Request__c');
            Map<String,String> childInfo = new Map<String,String>();
            childInfo.put('objectType','Program_Offering__c');
            childInfo.put('fields',PROGRAM_OFFERING_FIELDS);
            childInfo.put('conditionField','hed_Program_Plan__c');

            List<Program_Offering__c> programOfferings = new List<Program_Offering__c>();

            prodRequest = TestDataFactory.createTestProductRequestRecords(1);
            insert prodRequest;

            List<hed__Program_Plan__c> programPlanList = new List<hed__Program_Plan__c>();
            programPlanList.add(new hed__Program_Plan__c(Name = 'Test Program Plan',Product_Request__c=prodRequest[0].Id));
            insert programPlanList;
            productRequestId = prodRequest[0].Id;
            programOfferings.add(
                new Program_Offering__c(
                Name = 'Test Program Offering',
                hed_Program_Plan__c = programPlanList[0].id,
                hed_Capacity__c = 10,
                Start_Date__c = system.today() + 1
                )
            );
            insert programOfferings;

            ProductOfferingCtrl.ProductOfferingData pod = ProductOfferingCtrl.getProductOfferingData(productRequestId,parentInfo,childInfo);
            Test.stopTest();

            System.assert(pod.relatedFacilitators != null, 'No related facilitators');
            System.assert(pod.relatedSessions != null, 'No related sessions');
        }
    }

    @isTest
    static void getOfferingLayoutTest() {
        System.runAs(TestDataFactoryUser.selectUserSystemAdministrator){
            Test.startTest();
            Map<String,List<Field_Layout_Setting__mdt>> layoutMap = ProductOfferingCtrl.getOfferingLayout();
            Test.stopTest();
            System.assertEquals(2, layoutMap.keySet().size(),'Layout map not as expected');
        }
    }

    @isTest
    static void updateCourseOfferingsTest() {
        System.runAs(TestDataFactoryUser.selectUserSystemAdministrator){
            List<Product_Request__c> prodRequest = TestDataFactory.createTestProductRequestRecords(1);
            insert prodRequest;
            List<Account> accounts = TestDataFactory.createTestAccountRecords(1);
            for(Account acc : accounts){
                acc.RecordTypeId = ACCT_UNIV_DEP_ID;
                acc.Organization_Unit_Level__c = '2';
            }
            insert accounts;
            List<hed__Course__c> courses = TestDataFactory.createTestCourseRecords(25,accounts[0].Id,prodRequest[0].Id);
            insert courses;
            List<hed__Term__c> terms = TestDataFactory.createTestTermRecords(25,accounts[0].Id);
            insert terms;
            List<hed__Course_Offering__c> courseOfferings = TestDataFactory.createTestCourseOfferingRecord(25,courses,terms);
            for(hed__Course_Offering__c courseOffering : courseOfferings){
                courseOffering.hed__Start_Date__c = System.today();
                courseOffering.LMS_Creation_Date__c = System.today()-10;
            }
            insert courseOfferings;
            for(hed__Course_Offering__c offering : courseOfferings){
                offering.IsActive__c = false;
            }
            Test.startTest();
            ProductOfferingCtrl.updateCourseOfferings(courseOfferings);
            Test.stopTest();
            for(hed__Course_Offering__c offering : [
                SELECT IsActive__c 
                FROM hed__Course_Offering__c 
                WHERE Id IN :courseOfferings
            ])
            {
                System.assertEquals(false, offering.IsActive__c,'Course Offering not updated as expected');
            }
        }
    }

    @isTest static void getFacilitatorBiosTest() {
        System.runAs(TestDataFactoryUser.selectUserSystemAdministrator) {
            List<Id> idList = new List<Id>();
            Contact con = new Contact( LastName = 'Test' );
            insert con;
            Boolean isException = false;
            String errorMsg;
            Test.startTest();
            try{
            	ProductOfferingCtrl.getFacilitatorBios(con.Id, idList);                
            } catch(Exception e) {
                isException = true;
                errorMsg = e.getMessage();
            }
            Test.stopTest();
            System.assert(!isException, 'Exception: ' + errorMsg);
        }
    }
    
    @isTest static void isNewFacilitatorTest() {
        System.runAs(TestDataFactoryUser.selectUserSystemAdministrator) {
            Boolean isException = false;
            String errorMsg;
            Test.startTest();
            try {
                ProductOfferingCtrl.isNewFacilitator(null, null);
            } catch(Exception e) {
                isException = true;
                errorMsg = e.getMessage();
            }
            Test.stopTest();
            System.assert(!isException, 'Exception: ' + errorMsg);
        }
    }
}