src/core-crm/main/objects/Account/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Account/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/hed__Course__c/hed__Course__c.object-meta.xml
<CustomObject>
    <description>Academic Course offered by a Department or School, for example, English 101 or Ancient History.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course__c/fields/Core_Concepts__c.field-meta.xml
<CustomField>
    <fullName>Core_Concepts__c</fullName>
    <description>From Courseloop - can&apos;t be overwritten for Curriculum record types</description>
    <label>Core Concepts</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

src/core-crm/objects/hed__Course__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/hed__Course__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>hed__Facility__c.Name</field>
            <operation>contains</operation>
            <value>&apos;QUT Kelvin Grove&apos;, &apos;QUT Gardens Point&apos;, &apos;QUT Canberra&apos;, &apos;QUT Sydney&apos;, &apos;QUT Melbourne&apos;, &apos;Web Conference&apos;, &apos;Externals&apos;, &apos;QUT Cairns&apos;, &apos;QUT NSW Classroom&apos;</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>hed__Facility__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course__c/fields/More_Details__c.field-meta.xml
<CustomField>
    <fullName>More_Details__c</fullName>
    <label>More Details</label>
    <length>4000</length>
    <type>Html</type>
</CustomField>

src/core-crm/objects/hed__Course__c/fields/Overview__c.field-meta.xml
<CustomField>
    <fullName>Overview__c</fullName>
    <label>Overview</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

src/core-crm/objects/hed__Course__c/fields/ProductRequestID__c.field-meta.xml
<CustomField>
    <fullName>ProductRequestID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/hed__Course__c/fields/Who_Should_Participate__c.field-meta.xml
<CustomField>
    <fullName>Who_Should_Participate__c</fullName>
    <description>From Courseloop - can&apos;t be overwritten for Curriculum record types</description>
    <inlineHelpText>Who should participate? By attending participants will gain what new knowledge and skills</inlineHelpText>
    <label>Who Should Participate?</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

src/core-crm/objects/hed__Course__c/recordTypes/Short_Course.recordType-meta.xml
<RecordType>
    <fullName>Short_Course</fullName>
    <active>true</active>
    <label>Short Course</label>
</RecordType>

src/core-crm/objects/hed__Facility__c/hed__Facility__c.object-meta.xml
<CustomObject>
    <description>A school property asset. For example, a classroom, lecture hall, or laboratory.</description>
    <label>Facility</label>
    <nameField>
        <label>Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Product2/fields/Core_Concepts__c.field-meta.xml
<CustomField>
    <fullName>Core_Concepts__c</fullName>
    <label>Core Concepts</label>
    <length>75000</length>
    <type>Html</type>
</CustomField>

src/core-crm/objects/Product2/fields/More_Details__c.field-meta.xml
<CustomField>
    <fullName>More_Details__c</fullName>
    <label>More Details</label>
    <length>75000</length>
    <type>Html</type>
</CustomField>

src/core-crm/objects/Product2/fields/Overview__c.field-meta.xml
<CustomField>
    <fullName>Overview__c</fullName>
    <label>Overview</label>
    <length>75000</length>
    <type>Html</type>
</CustomField>

src/core-crm/objects/Product2/fields/Publishing_End_date__c.field-meta.xml
<CustomField>
    <fullName>Publishing_End_date__c</fullName>
    <description>This is the date the Product will be removed from online product catalogue</description>
    <label>Publishing End Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Product2/fields/Who_Should_Participate__c.field-meta.xml
<CustomField>
    <fullName>Who_Should_Participate__c</fullName>
    <label>Who Should Participate?</label>
    <length>75000</length>
    <type>Html</type>
</CustomField>

src/core-crm/objects/Product_Request__c/Product_Request__c.object-meta.xml
<CustomObject>
    <label>Product Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Product Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Product_Request__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>hed__Facility__c</referenceTo>
    <relationshipLabel>Product Requests</relationshipLabel>
    <relationshipName>Product_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Product_Request__c/fields/Product_Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Product_Request_Status__c</fullName>
    <label>Product Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Define</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Release</fullName>
            </value>
            <value>
                <fullName>In Delivery</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Product_Request__c/recordTypes/Short_Course.recordType-meta.xml
<RecordType>
    <fullName>Short_Course</fullName>
    <active>true</active>
    <description>This record type will be used to request a Product without learning outcomes.</description>
    <label>Short Course</label>
</RecordType>

src/core-crm/classes/PublishingEndDateSchedulerTest.cls
/**
 * @description Tests the PublishingEndDateScheduler
 *
 * @see PublishingEndDateScheduler
 *
 * @author Accenture
 *
 * @history
 *    | Developer                 | Date                  | JIRA         | Change Summary                              |
      |---------------------------|-----------------------|--------------|---------------------------------------------|
      | eugene.andrew.abuan       | February 15, 2022     | DEPP-1256    | Created file                                | 
      |                           |                       |              |                                             | 
*/

@IsTest(SeeAllData=false)
public class PublishingEndDateSchedulerTest {
    
    private static User currentUser = TestDataFactory.createUserRecords(1, 'QUTeX').iterator().next();
    private static Id opeShortProdReqId = Schema.SObjectType.Product_Request__c.getRecordTypeInfosByDeveloperName().get('Short_Course').getRecordTypeId();
    private static Id opeShortCourseId = Schema.SObjectType.hed__Course__c.getRecordTypeInfosByDeveloperName().get('Short_Course').getRecordTypeId();
    private static Integer numberOfRecords = 100;         
	
    @TestSetup
    static void setupMethod(){
        List<Account> accounts = TestDataFactory.createTestAccountRecords(1);
        insert accounts;

        List<Product_Request__c> productRequests = TestDataFactory.createTestProductRequestRecords(numberOfRecords);
        for(Product_Request__c productRequest : productRequests){
            productRequest.RecordTypeId = opeShortProdReqId;
        }
        insert productRequests;

        hed__Facility__c facility = new hed__Facility__c();
        facility.Name = 'test';
        insert facility;                

        List<hed__Course__c> courses = TestDataFactory.createTestCourseRecords(numberOfRecords, accounts[0].Id, productRequests[0].Id);
        for(Integer i = 0 ; i < courses.size() ; i++){
            courses[i].ProductRequestID__c = productRequests[i].Id;
            courses[i].RecordTypeId = opeShortCourseId;
            courses[i].Location__c = facility.Id;             
        }
        insert courses;
    }

    @IsTest
    static void testPublishingEndDateScheduler(){
          System.runAs(currentUser){              
            String cronExpression = Label.Publishing_End_Date_Cron_Expression;
              
            List<Product_Request__c> productRequests = [SELECT Id, Product_Request_Status__c FROM Product_Request__c LIMIT 100];
            for(Product_Request__c productRequest : productRequests){
                productRequest.Product_Request_Status__c = 'Release';
            }
            update productRequests;
            
            Test.startTest();
            List<Product2> products = [SELECT Id, Core_Concepts__c, Description, End_Date__c, More_Details__c, 
                    Name, Overview__c, Start_Date__c, Who_Should_Participate__c, Publishing_End_date__c,IsActive
                    FROM Product2 LIMIT 100];
            for(Product2 product : products){
                 product.Publishing_End_date__c = date.today();
            }
            update products;
              
           String jobId = System.Schedule('Test PublishingEndDateTest daily at 12AM', cronExpression, new PublishingEndDateScheduler());
           Test.stopTest();
             
         	List<CronTrigger> cts = [SELECT Id, TimesTriggered, NextFireTime FROM CronTrigger WHERE ID =: jobId ];
            
            DateTime midnight = Datetime.newInstance(date.today(), time.newInstance(0, 0, 0, 0));
            String dayToday = midnight.format('EEEE');

            if(dayToday == 'Friday'){
                System.assertEquals(midnight.addDays(3),cts[0].NextFireTime, 'Error, Next fire is Not Monday');
            }else if(dayToday =='Saturday'){
                System.assertEquals(midnight.addDays(2),cts[0].NextFireTime, 'Error, Next fire is Not Monday');
            }else if(dayToday == 'Sunday'){
                System.assertEquals(midnight.addDays(1),cts[0].NextFireTime, 'Error, Next fire is Not Monday');
            }
            else{
                System.assertEquals(midnight.addHours(24),cts[0].NextFireTime, 'Error Not Scheduled in Midnight');
            }
        }
    }
}