src/core-crm/main/objects/Account/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Account/fields/Organization_Unit_Level__c.field-meta.xml
<CustomField>
    <fullName>Organization_Unit_Level__c</fullName>
    <description>The level (1,2,3) of the organizational unit within the QUT Organizational hierarchy.</description>
    <label>Organization Unit Level</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Account/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Contextual_Role__c/Contextual_Role__c.object-meta.xml
<CustomObject>
    <description>The Contextual Role object stores data about the participants (both people and organisations) and the role/s they have played or are playing in a business process. Contextual Role object data differs from Affiliation Object data as it captures: a) data about each participant and the role they’re playing in given a business process and b) it can also support capturing where a contact has a relationship with an organisation within the context of the given business process. It differs from Affiliation Object records in that Affiliation does not support capturing any context around the business process that might have applied to the Affiliation record.</description>
    <label>Contextual Role</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Contextual Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contextual Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Contextual_Role__c/fields/Contextual_Role__c.field-meta.xml
<CustomField>
    <fullName>Contextual_Role__c</fullName>
    <description>The role the participant is playing in the context of the business process.</description>
    <label>Contextual Role</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Contextual_Role_Group__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Academic</fullName>
            </value>
            <value>
                <fullName>Board Chairman</fullName>
            </value>
            <value>
                <fullName>Board Vice-Chairman</fullName>
            </value>
            <value>
                <fullName>Chief Investigator</fullName>
            </value>
            <value>
                <fullName>Co-Investigator</fullName>
            </value>
            <value>
                <fullName>Faculty</fullName>
            </value>
            <value>
                <fullName>Finance Manager</fullName>
            </value>
            <value>
                <fullName>Funding Body</fullName>
            </value>
            <value>
                <fullName>Inventor</fullName>
            </value>
            <value>
                <fullName>Lead Researcher</fullName>
            </value>
            <value>
                <fullName>Lead Trainer</fullName>
            </value>
            <value>
                <fullName>ORS Contact</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Partner Contact</fullName>
            </value>
            <value>
                <fullName>Primary Partner Contact</fullName>
            </value>
            <value>
                <fullName>Public Officer</fullName>
            </value>
            <value>
                <fullName>Relationship Manager</fullName>
            </value>
            <value>
                <fullName>Research Centre</fullName>
            </value>
            <value>
                <fullName>Researcher</fullName>
            </value>
            <value>
                <fullName>School</fullName>
            </value>
            <value>
                <fullName>Secondary Investigator</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>Training Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Contextual_Role__c/fields/Role_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Role_Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Identifies if a participant is currently playing the specified role in the business process.</description>
    <label>Role Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>The Opportunity Start Date.</description>
    <inlineHelpText>The Opportunity Start Date.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/classes/OpportunityCheckPrimaryContactFlowTest.cls
/**
 * @description Test Class for Opportunity Check Primary Contact flow
 *
 * @see ../flows/Opportunity Check Primary Contact
 *
 * @author Accenture
 *
 * @history
 *    | Developer                 | Date                  | JIRA         | Change Summary         |
      |---------------------------|-----------------------|--------------|------------------------|
      | nicole.genon    	      | February 29, 2024     | DEPP-7905    | Created file           |
*/
@isTest
public with sharing class OpportunityCheckPrimaryContactFlowTest {
    public static final String CONTRIBUTORS_CONTEXTUAL_ROLE_GROUP = 'Contributors';
    public static final String PRIMARY_CONTACT_CONTEXTUAL_ROLE = 'Primary Contact';

    @testSetup
    static void makeData(){
        TestDataFactory.generateTestUsers(new List<String>{'QUT_Advancement_Manager'});
    	System.runAs(TestDataFactory.getAdvancementManager()) {
            List<Account> accountRecord = TestDataFactory.createTestAccountRecordsWithRecordType(1, AccountsDAO.ACCT_UNIV_DEP_ID);
            accountRecord[0].Organization_Unit_Level__c ='2';
            accountRecord[0].End_Date__c = null;
            AccountsDAO.newInstance().insertRecords(accountRecord, false, AccessLevel.SYSTEM_MODE);
        
            List<Opportunity> newOpportunityRecords = TestDataFactory.createTestOpportunityRecords(
                1,'OppTest',OpportunitiesDAO.ORGANISATIONGIVING_RECTYPE_ID);
            List<Contact> newContacts = TestDataFactory.createTestContactRecords(1);
            newOpportunityRecords[0].AccountId = accountRecord[0].Id;
            newOpportunityRecords[0].StageName = OpportunitiesDAO.IDENTIFY_STAGE;
            newContacts[0].RecordTypeId = ContactsDAO.PERSON_RECORDTYPE_ID;
            newContacts[0].AccountId = accountRecord[0].Id;

            OpportunitiesDAO.newInstance().insertRecords(newOpportunityRecords, false, AccessLevel.USER_MODE);
            ContactsDAO.newInstance().insertRecords(newContacts, false, AccessLevel.USER_MODE);

            List<Contextual_Role__c> contextualRoleRecords = new List<Contextual_Role__c>();
            List<Contextual_Role__c> newContextualRoleRecords = TestDataFactory.createContextualRolesForOpportunity(10,ContextualRolesDAO.ADVANCEMENT_OPPORTUNITY_ROLE_RECTYPE_ID,newOpportunityRecords[0].id,accountRecord[0].Id,CONTRIBUTORS_CONTEXTUAL_ROLE_GROUP);

            for(Contextual_Role__c con : newContextualRoleRecords){
                con.Contextual_Role__c = PRIMARY_CONTACT_CONTEXTUAL_ROLE;
                con.Role_Is_Active__c = true;
                contextualRoleRecords.add(con);
            }
            ContextualRolesDAO.newInstance().insertRecords(contextualRoleRecords, false, AccessLevel.USER_MODE);  
        }
    }

    @isTest
    private static void checkStageUpdateWithActivePrimaryContact() {
        System.runAs(TestDataFactory.getAdvancementManager()) {
            Test.startTest();
            List<Opportunity> oppRecords = OpportunitiesDAO.getOpportunityByRecordTypeIds(new Set<Id>{OpportunitiesDAO.ORGANISATIONGIVING_RECTYPE_ID},AccessLevel.USER_MODE);

            oppRecords[0].Start_Date__c = System.today() + 10 ;
            oppRecords[0].Description = 'Opp Test';
            oppRecords[0].StageName = 'Qualify';
            OpportunitiesDAO.newInstance().updateRecords(oppRecords, false, AccessLevel.USER_MODE);
            Test.stopTest();

            List<Opportunity> oppUpdatedRecords = OpportunitiesDAO.getRecordsBySetIds(new Set<Id>{oppRecords[0].Id});
            System.assert(oppUpdatedRecords[0].StageName.equals('Qualify'), 'Stage is successfully changed to Qualify.');
        }
    }

    @isTest
    private static void checkStageUpdateWithInActivePrimaryContact() {
        System.runAs(TestDataFactory.getAdvancementManager()) {
            Test.startTest();
            List<Opportunity> oppRecords = OpportunitiesDAO.getOpportunityByRecordTypeIds(new Set<Id>{OpportunitiesDAO.ORGANISATIONGIVING_RECTYPE_ID},AccessLevel.USER_MODE);
            List<Contextual_Role__c> contextualRoleRecordsToUpdate = new List<Contextual_Role__c>();
            List<Contextual_Role__c> contextualRoleRecords = ContextualRolesDAO.newInstance().getActiveOpportunityContextualRolesRecords(new Set<Id>{oppRecords[0].Id}, new List<String>{CONTRIBUTORS_CONTEXTUAL_ROLE_GROUP});

            for(Contextual_Role__c con : contextualRoleRecords){
                con.Role_Is_Active__c = false;
                contextualRoleRecordsToUpdate.add(con);
            }
            ContextualRolesDAO.newInstance().updateRecords(contextualRoleRecordsToUpdate, false, AccessLevel.USER_MODE);

            oppRecords[0].Start_Date__c = System.today() + 10 ;
            oppRecords[0].Description = 'Opp Test';
            oppRecords[0].StageName = 'Qualify';
            Database.SaveResult[] srList = OpportunitiesDAO.newInstance().updateRecords(oppRecords, false, AccessLevel.USER_MODE);
            Test.stopTest();

            List<Opportunity> oppUpdatedRecords = OpportunitiesDAO.getRecordsBySetIds(new Set<Id>{oppRecords[0].Id});
            for (Database.SaveResult sr : srList) {
                System.assert(!sr.isSuccess(), 'A record was saved.');
            }
            System.assert(oppUpdatedRecords[0].StageName.equals('Identify'), 'Stage value is Identify.');
        }
    }
}