src/core-crm/main/objects/Account/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Account/fields/Organization_Unit_Level__c.field-meta.xml
<CustomField>
    <fullName>Organization_Unit_Level__c</fullName>
    <description>The level (1,2,3) of the organizational unit within the QUT Organizational hierarchy.</description>
    <label>Organization Unit Level</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Account/recordTypes/Business_Organization.recordType-meta.xml
<RecordType>
    <fullName>Business_Organization</fullName>
    <active>true</active>
    <description>A business organization.</description>
    <label>Business Organization</label>
</RecordType>

src/core-crm/objects/Associated_Products__c/Associated_Products__c.object-meta.xml
<CustomObject>
    <label>Associated Products</label>
    <nameField>
        <displayFormat>AP - {000000}</displayFormat>
        <label>Associated Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/Associated_Products__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Determine if the Associated Product is active or not.</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Associated_Products__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Associated Products</relationshipLabel>
    <relationshipName>Associated_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Associated_Products__c/fields/Product_Request__c.field-meta.xml
<CustomField>
    <fullName>Product_Request__c</fullName>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Associated Products</relationshipLabel>
    <relationshipName>Associated_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/core-crm/objects/BuyerGroup/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End date of the product</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/BuyerGroup/fields/Product_Request__c.field-meta.xml
<CustomField>
    <fullName>Product_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the parent Standing Offer Arrangement Product request</description>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Buyer Groups</relationshipLabel>
    <relationshipName>Buyer_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course__c/hed__Course__c.object-meta.xml
<CustomObject>
    <description>Academic Course offered by a Department or School, for example, English 101 or Ancient History.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/hed__Course__c/recordTypes/Activity.recordType-meta.xml
<RecordType>
    <fullName>Activity</fullName>
    <active>true</active>
    <label>Activity</label>
    <picklistValues>
        <!-- Renamed from Collaboation_External__c-->
        <picklist>Collaboration_with_External_Organisation__c</picklist>
        <values>
            <fullName>No</fullName>
        </values>
        <values>
            <fullName>Yes</fullName>
        </values>
    </picklistValues>
</RecordType>

src/core-crm/objects/hed__Program_Plan__c/hed__Program_Plan__c.object-meta.xml
<CustomObject>
    <description>Links Courses to an Academic Program to create a path for students to follow. An Academic Program can list multiple Courses, and a Course can be associated with multiple Academic Programs.</description>
    <label>Program Plan</label>
    <nameField>
        <label>Program Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Program_Plan__c/fields/Product_Request__c.field-meta.xml
<CustomField>
    <fullName>Product_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the related Product Request record of the Program Plan.</description>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Program_Plan__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <description>This record type will be used to create a Program. This can be a combination of a Unit, a Module, a Short Course, or an Activity.</description>
    <label>Program</label>
</RecordType>

src/core-crm/objects/Product2/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Product_Request__c/Product_Request__c.object-meta.xml
<CustomObject>
    <label>Product Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Product Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Product_Request__c/fields/Product_Request_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Request_Name__c</fullName>
    <label>Product Request Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Product_Request__c/fields/Product_Specification__c.field-meta.xml
<CustomField>
    <fullName>Product_Specification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Specification</label>
    <referenceTo>Product_Specification__c</referenceTo>
    <relationshipLabel>Product Requests</relationshipLabel>
    <relationshipName>Product_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Product_Request__c/recordTypes/Activity.recordType-meta.xml
<RecordType>
    <fullName>Activity</fullName>
    <active>true</active>
    <description>This record type will be used to create an Event, Discussion Forum, or workshop.</description>
    <label>Activity</label>
</RecordType>

src/core-crm/objects/Product_Request__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <description>This record type will be used to create a Program. This can be a combination of a Unit, a Module, a Short Course, or an Activity.</description>
    <label>Program</label>
</RecordType>

src/core-crm/objects/Product_Request__c/recordTypes/Standing_Offer_Arrangement.recordType-meta.xml
<RecordType>
    <fullName>Standing_Offer_Arrangement</fullName>
    <active>true</active>
    <description>This record type will be used to create Standing Offer Arrangement within Corporate Portal</description>
    <label>Standing Offer Arrangement</label>
</RecordType>

src/core-crm/objects/Product_Specification__c/Product_Specification__c.object-meta.xml
<CustomObject>
    <label>Product Specification</label>
    <nameField>
        <displayFormat>PS-{00000}</displayFormat>
        <label>Product Specification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Specifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Product_Specification__c/recordTypes/CCE.recordType-meta.xml
<RecordType>
    <fullName>CCE</fullName>
    <active>true</active>
    <description>Used to Design products which are the result of a closed won Opportunity in Salesforce.</description>
    <label>CCE</label>
</RecordType>

src/core-crm/objects/Related_Product_Request__c/Related_Product_Request__c.object-meta.xml
<CustomObject>
    <label>Related Product Request</label>
    <nameField>
        <label>Related Product Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Related Product Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Related_Product_Request__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Related Product Requests</relationshipLabel>
    <relationshipName>Course</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Related_Product_Request__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Related Product Requests</relationshipLabel>
    <relationshipName>Program</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/classes/BuyerGroupToCompleteBatchTest.cls
/**
 * @description Batch class complete SOA product requests
 * 
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | roy.nino.s.regala   	       | August 8, 2022        | DEPP-2498              | Created file                 |
      | alexander.cadalin   	       | August 18, 2022       | ST Fix                 | Changed BuyerGroup Name      |
 */
@isTest
public with sharing class BuyerGroupToCompleteBatchTest {
    private static final String PR_COMPLETED = System.Label.PL_ProductRequest_Completed;
    private static final Id SOA_ID = Schema.SObjectType.Product_Request__c.getRecordTypeInfosByDeveloperName().get('Standing_Offer_Arrangement').getRecordTypeId();
    private static final Id ACTIVITY_ID = Schema.SObjectType.Product_Request__c.getRecordTypeInfosByDeveloperName().get('Activity').getRecordTypeId();
    private static final Id PROGRAM_ID = Schema.SObjectType.Product_Request__c.getRecordTypeInfosByDeveloperName().get('Program').getRecordTypeId();
    private static final Id ACTIVITY_COURSE_ID = Schema.SObjectType.hed__Course__c.getRecordTypeInfosByDeveloperName().get('Activity').getRecordTypeId();
    private static final Id BUSINESS_ACC_RECTYPEID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business_Organization').getRecordTypeId();
    private static Id cceProdSpecId = Schema.SObjectType.Product_Specification__c.getRecordTypeInfosByDeveloperName().get('CCE').getRecordTypeId();
    private static final String ACCT_UNIV_DEP = System.Label.RT_Account_University_Department;
    private static final Id ACCT_UNIV_DEP_ID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
      .get(ACCT_UNIV_DEP)
      .getRecordTypeId();

    @testSetup 
    static void setupMethod() {
        Test.startTest();
        TestDataFactoryUser.generateUserSystemAdministrator();
        Test.stopTest();

    }
        
    @isTest
    private static void runToCompleteTest() {
        System.runAs(TestDataFactoryUser.selectUserSystemAdministrator) {

            List<Account> accountList = TestDataFactory.createTestAccountRecords(2);
            for(Account acc: accountList){
                acc.RecordTypeId = BUSINESS_ACC_RECTYPEID;
            }
            insert accountList;
    
            List<Account> accounts;
            accounts = TestDataFactory.createTestAccountRecords(1);
            for(Account acc : accounts){
                acc.RecordTypeId = ACCT_UNIV_DEP_ID;
                acc.Organization_Unit_Level__c = '2';
            }
            insert accounts;
            List<Contact> conList;
            conList = TestDataFactory.createTestContactRecords(1);
            insert conList;
    
            List<Opportunity> oppList = TestDataFactory.createClosedWonOpportunities(1,accounts[0].Id,conList.iterator().next()?.Id);
            insert oppList;
    
            List<Product_Specification__c> prodSpecList = TestDataFactory.retrieveCCEProductSpecifications();
    
            List<Product_Request__c> soaRequest = TestDataFactory.createTestProductRequestRecords(1,prodSpecList[0].Id);
            for(Product_Request__c pr : soaRequest){
                pr.RecordTypeId = SOA_ID;        
            }
            insert soaRequest;
    
            BuyerGroup bgInsert = new BuyerGroup();
            bgInsert.Name = soaRequest[0].Product_Request_Name__c;
            bgInsert.Product_Request__c = soaRequest[0].Id;
            bgInsert.End_Date__c = Date.Today();
            insert bgInsert;
            
            List<Product_Request__c> courseRequest = TestDataFactory.createTestProductRequestRecords(1,prodSpecList[0].Id);
            for(Product_Request__c pr : courseRequest){
                pr.RecordTypeId = ACTIVITY_ID;        
            }
            insert courseRequest;

            List<hed__Course__c> courses;
            courses = TestDataFactory.createTestCourseRecords(1,accounts[0].Id,courseRequest[0].Id);
            for(hed__Course__c c: courses){
                c.RecordTypeId = ACTIVITY_COURSE_ID;
            }
            insert courses;

            List<Product_Request__c> programRequest;
            programRequest = TestDataFactory.createTestProductRequestRecords(1,prodSpecList[0].Id);
            programRequest[0].Product_Request_Name__c = 'PROGRAM REQUEST';
            programRequest[0].RecordTypeId = PROGRAM_ID;
            insert programRequest;

            List<hed__Program_Plan__c> programPlanList;
            programPlanList = TestDataFactory.createTestProgramPlanRecords(1);
            for(hed__Program_Plan__c prog: programPlanList){
                prog.Product_Request__c = programRequest[0].Id;
            }
            insert programPlanList;

            List<Related_Product_Request__c> relatedPRInsert = new List<Related_Product_Request__c>();
            relatedPRInsert.add(new Related_Product_Request__c(Program__c = soaRequest[0].Id, Course__c = programRequest[0].Id));
            insert relatedPRInsert;

            List<Associated_Products__c> assocProdList = new List<Associated_Products__c>();
            List<Product2> prod = new List<Product2>([SELECT Id From Product2 WHERE Course__c IN: courses]);
            assocProdList.add(new Associated_Products__c(Product__c = prod[0].Id, Product_Request__c = soaRequest[0].Id, IsActive__c = true));
            insert assocProdList;

            Test.startTest();

            BuyerGroupToCompleteBatch batch = new BuyerGroupToCompleteBatch();
            Database.executeBatch(batch);

            Test.stopTest();

            System.assert(![SELECT Id FROM AsyncApexJob WHERE ApexClass.Name = 'BuyerGroupToCompleteBatch'].isEmpty() , 'BuyerGroupToCompleteBatch Job was not executed');

        }
    }
}