src/core-crm/main/objects/Account/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Account/fields/Organization_Unit_Level__c.field-meta.xml
<CustomField>
    <fullName>Organization_Unit_Level__c</fullName>
    <description>The level (1,2,3) of the organizational unit within the QUT Organizational hierarchy.</description>
    <label>Organization Unit Level</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Account/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Contextual_Role__c/Contextual_Role__c.object-meta.xml
<CustomObject>
    <description>The Contextual Role object stores data about the participants (both people and organisations) and the role/s they have played or are playing in a business process. Contextual Role object data differs from Affiliation Object data as it captures: a) data about each participant and the role they’re playing in given a business process and b) it can also support capturing where a contact has a relationship with an organisation within the context of the given business process. It differs from Affiliation Object records in that Affiliation does not support capturing any context around the business process that might have applied to the Affiliation record.</description>
    <label>Contextual Role</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Contextual Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contextual Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Contextual_Role__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Provides a lookup to the Contact Object to capture an Organisation playing a role in the business process.

Note that a Contextual Role record can ONLY be about a Contact OR about an Account. No record should ever have both Contact_Id__c and Organisation_Account_Id__c populated on the same row.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contextual Roles</relationshipLabel>
    <relationshipName>Contextual_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Contextual_Role__c/fields/Contextual_Role__c.field-meta.xml
<CustomField>
    <fullName>Contextual_Role__c</fullName>
    <description>The role the participant is playing in the context of the business process.</description>
    <label>Contextual Role</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Contextual_Role_Group__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Academic</fullName>
            </value>
            <value>
                <fullName>Board Chairman</fullName>
            </value>
            <value>
                <fullName>Board Vice-Chairman</fullName>
            </value>
            <value>
                <fullName>Chief Investigator</fullName>
            </value>
            <value>
                <fullName>Co-Investigator</fullName>
            </value>
            <value>
                <fullName>Faculty</fullName>
            </value>
            <value>
                <fullName>Finance Manager</fullName>
            </value>
            <value>
                <fullName>Funding Body</fullName>
            </value>
            <value>
                <fullName>Inventor</fullName>
            </value>
            <value>
                <fullName>Lead Researcher</fullName>
            </value>
            <value>
                <fullName>Lead Trainer</fullName>
            </value>
            <value>
                <fullName>ORS Contact</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Partner Contact</fullName>
            </value>
            <value>
                <fullName>Primary Partner Contact</fullName>
            </value>
            <value>
                <fullName>Public Officer</fullName>
            </value>
            <value>
                <fullName>Relationship Manager</fullName>
            </value>
            <value>
                <fullName>Research Centre</fullName>
            </value>
            <value>
                <fullName>Researcher</fullName>
            </value>
            <value>
                <fullName>School</fullName>
            </value>
            <value>
                <fullName>Secondary Investigator</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>Training Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Contextual_Role__c/fields/Role_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Role_Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Identifies if a participant is currently playing the specified role in the business process.</description>
    <label>Role Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Donation__c/Donation__c.object-meta.xml
<CustomObject>
    <description>Donation stores information about expected and/or completed donations made to the university. Donations arise out of Opportunities. Donation can either be a financial transaction linked to a payment or it can record the donation of a tangible object such as a piece of art.</description>
    <label>Donation</label>
    <nameField>
        <displayFormat>DN-{000000}</displayFormat>
        <label>Donation Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Donations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/core-crm/objects/Donation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Donor’s Contact record.</description>
    <inlineHelpText>Lookup to the Donor’s Contact record.</inlineHelpText>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Person</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Donations</relationshipLabel>
    <relationshipName>Donations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Donation__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>The stage the Donation is at in its lifecycle.</description>
    <inlineHelpText>The stage the Donation is at in its lifecycle.</inlineHelpText>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Proposed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Opportunity/fields/Donor_Ability_Rank__c.field-meta.xml
<CustomField>
    <fullName>Donor_Ability_Rank__c</fullName>
    <description>Captures the Contact’s or Organisation’s ‘Ability’ to donate with regard to a specific Opportunity.</description>
    <inlineHelpText>Captures the Contact’s or Organisation’s ‘Ability’ to donate with regard to a specific Opportunity.</inlineHelpText>
    <label>Donor Ability Rank</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>$1K - $10K</fullName>
            </value>
            <value>
                <fullName>$10K - $25K</fullName>
            </value>
            <value>
                <fullName>$25K - $250K</fullName>
            </value>
            <value>
                <fullName>$250K - $500K</fullName>
            </value>
            <value>
                <fullName>$500K - $1Million</fullName>
            </value>
            <value>
                <fullName>$1 Million +</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Opportunity/fields/Donor_Interest_Rank__c.field-meta.xml
<CustomField>
    <fullName>Donor_Interest_Rank__c</fullName>
    <description>Captures the Contact’s or Organisation’s ‘Interest’ in donating with regard to a specific Opportunity.</description>
    <inlineHelpText>Captures the Contact’s or Organisation’s ‘Interest’ in donating with regard to a specific Opportunity.</inlineHelpText>
    <label>Donor Interest Rank</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Interest</fullName>
            </value>
            <value>
                <fullName>Unknown or not assessed</fullName>
            </value>
            <value>
                <fullName>Low Level of Interest</fullName>
            </value>
            <value>
                <fullName>Moderate Interest</fullName>
            </value>
            <value>
                <fullName>High Level of Interest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Opportunity/fields/Donor_Linkage_Rank__c.field-meta.xml
<CustomField>
    <fullName>Donor_Linkage_Rank__c</fullName>
    <description>Captures the Contact’s or Organisation’s ‘Linkages’ (i.e. their personal and professional connections), in relation to donating with regard to a specific Opportunity.</description>
    <inlineHelpText>Captures the Contact’s or Organisation’s ‘Linkages’ (i.e. their personal and professional connections), in relation to donating with regard to a specific Opportunity.</inlineHelpText>
    <label>Donor Linkage Rank</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Link</fullName>
            </value>
            <value>
                <fullName>Low Level of Connection</fullName>
            </value>
            <value>
                <fullName>Moderate Level of Connection</fullName>
            </value>
            <value>
                <fullName>High Level of Connection</fullName>
            </value>
            <value>
                <fullName>Very Highly Connected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Opportunity/fields/Due_Diligence_Completed__c.field-meta.xml
<CustomField>
    <fullName>Due_Diligence_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the Due Diligence processes have been completed.</description>
    <inlineHelpText>Indicates if the Due Diligence processes have been completed.</inlineHelpText>
    <label>Due Diligence Complete</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Opportunity/fields/Due_Diligence_Summary__c.field-meta.xml
<CustomField>
    <fullName>Due_Diligence_Summary__c</fullName>
    <description>Summary of the processes completed as part of due diligence checks.</description>
    <inlineHelpText>Summary of the processes completed as part of due diligence checks.</inlineHelpText>
    <label>Due Diligence Summary</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Opportunity/fields/Is_Agreement_Signed__c.field-meta.xml
<CustomField>
    <fullName>Is_Agreement_Signed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the Agreement has been signed.</description>
    <inlineHelpText>Indicates if the Agreement has been signed.</inlineHelpText>
    <label>Is Agreement Signed</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Opportunity/fields/Is_Qualified__c.field-meta.xml
<CustomField>
    <fullName>Is_Qualified__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the Opportunity has been qualified.</description>
    <inlineHelpText>Indicates if the Opportunity has been qualified.</inlineHelpText>
    <label>Is Qualified</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Opportunity/fields/Probability_Of_Success__c.field-meta.xml
<CustomField>
    <fullName>Probability_Of_Success__c</fullName>
    <description>The probability, (expressed as a percentage) of the Opportunity being won.</description>
    <inlineHelpText>The probability, (expressed as a percentage) of the Opportunity being won.</inlineHelpText>
    <label>Probability Of Success</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

src/core-crm/objects/Opportunity/fields/Qualification_Summary__c.field-meta.xml
<CustomField>
    <fullName>Qualification_Summary__c</fullName>
    <label>Qualification Summary</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

src/core-crm/objects/Opportunity/fields/Solicitation_Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Solicitation_Sub_Stage__c</fullName>
    <description>Solicitation sub-process stage.</description>
    <inlineHelpText>Solicitation sub-process stage.</inlineHelpText>
    <label>Solicitation Sub Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Near Ask</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
            <value>
                <fullName>Agreement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>The Opportunity Start Date.</description>
    <inlineHelpText>The Opportunity Start Date.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/classes/OpportunityUpdateCustomValidationTest.cls
/**
 * @description Test Class for Opportunity Update - Custom Validation flow
 *
 * @see ../flows/Opportunity Update - Custom Validation
 *
 * @author Accenture
 *
 * @history
 *    | Developer                 | Date                  | JIRA         | Change Summary         |
      |---------------------------|-----------------------|--------------|------------------------|
      | nicole.genon    	      | February 29, 2024     | DEPP-7905    | Created file           |
*/
@isTest
public with sharing class OpportunityUpdateCustomValidationTest {
    public static final String CONTRIBUTORS_CONTEXTUAL_ROLE_GROUP = 'Contributors';
    public static final String PRIMARY_CONTACT_CONTEXTUAL_ROLE = 'Primary Contact';

    @testSetup
    static void makeData(){
        TestDataFactory.generateTestUsers(new List<String>{ 'QUT_Sys_Admin', 'QUT_Advancement_Manager'});
    	System.runAs(TestDataFactory.getAdvancementManager()) {
            List<Account> accountRecord = TestDataFactory.createTestAccountRecordsWithRecordType(1, AccountsDAO.ACCT_UNIV_DEP_ID);
            accountRecord[0].Organization_Unit_Level__c ='2';
            accountRecord[0].End_Date__c = null;
            AccountsDAO.newInstance().insertRecords(accountRecord, false, AccessLevel.SYSTEM_MODE);
        
            List<Opportunity> newOpportunityRecords = TestDataFactory.createTestOpportunityRecords(
                1,'OppTest',OpportunitiesDAO.ORGANISATION_GIVING_RECTYPE_ID);
            List<Contact> newContacts = TestDataFactory.createTestContactRecords(1);
            newOpportunityRecords[0].AccountId = accountRecord[0].Id;
            newOpportunityRecords[0].StageName = OpportunitiesDAO.IDENTIFY_STAGE;
            newContacts[0].RecordTypeId = ContactsDAO.PERSON_RECORDTYPE_ID;
            newContacts[0].AccountId = accountRecord[0].Id;

            OpportunitiesDAO.newInstance().insertRecords(newOpportunityRecords, false, AccessLevel.USER_MODE);
            ContactsDAO.newInstance().insertRecords(newContacts, false, AccessLevel.USER_MODE);

            List<Contextual_Role__c> contextualRoleRecords = new List<Contextual_Role__c>();
            List<Contextual_Role__c> newContextualRoleRecords = TestDataFactory.createContextualRolesForOpportunity(10,ContextualRolesDAO.ADVANCEMENT_OPPORTUNITY_ROLE_RECTYPE_ID,newOpportunityRecords[0].id,accountRecord[0].Id,CONTRIBUTORS_CONTEXTUAL_ROLE_GROUP);

            for(Contextual_Role__c con : newContextualRoleRecords){
                con.Contextual_Role__c = PRIMARY_CONTACT_CONTEXTUAL_ROLE;
                con.Role_Is_Active__c = true;
                contextualRoleRecords.add(con);
            }
            ContextualRolesDAO.newInstance().insertRecords(contextualRoleRecords, false, AccessLevel.USER_MODE);

            List<Opportunity> individualOpportunityRecords = TestDataFactory.createTestOpportunityRecords(
                1,'OppTest',OpportunitiesDAO.INDIVIDUAL_GIVING_RECTYPE_ID);
            individualOpportunityRecords[0].Description = 'Test';
            individualOpportunityRecords[0].ContactId = newContacts[0].Id;
            individualOpportunityRecords[0].Contact__c = newContacts[0].Id;
            individualOpportunityRecords[0].Donor_Linkage_Rank__c = 'Low Level of Connection';
            individualOpportunityRecords[0].Donor_Interest_Rank__c = 'Unknown or not assessed';
            individualOpportunityRecords[0].Donor_Ability_Rank__c = '$250K - $500K';
            individualOpportunityRecords[0].Probability_Of_Success__c = '60%';
            individualOpportunityRecords[0].Qualification_Summary__c = 'Test';
            individualOpportunityRecords[0].Is_Qualified__c = true;
            individualOpportunityRecords[0].Solicitation_Sub_Stage__c = 'Agreement';
            individualOpportunityRecords[0].Due_Diligence_Summary__c = 'Test';
            individualOpportunityRecords[0].Due_Diligence_Completed__c = true;
            individualOpportunityRecords[0].Is_Agreement_Signed__c = true;
            individualOpportunityRecords[0].StageName = OpportunitiesDAO.SOLICITATION_STAGE;

            OpportunitiesDAO.newInstance().insertRecords(individualOpportunityRecords, false, AccessLevel.USER_MODE);
        }

        System.runAs(TestDataFactory.getPortalSysAdminUser()) {
            List<Opportunity> oppRecords = OpportunitiesDAO.getOpportunityByRecordTypeIds(new Set<Id>{OpportunitiesDAO.INDIVIDUAL_GIVING_RECTYPE_ID},AccessLevel.USER_MODE);

            List<Donation__c> donationRecords = TestDataFactory.createDonationRecordsWithOpportunity(10,oppRecords[0].Id);

            DonationsDAO.newInstance().insertRecords(donationRecords, false, AccessLevel.USER_MODE);
        }
    }

    @isTest
    private static void checkStageUpdateWithActivePrimaryContact() {
        System.runAs(TestDataFactory.getAdvancementManager()) {
            Test.startTest();
            List<Opportunity> oppRecords = OpportunitiesDAO.getOpportunityByRecordTypeIds(new Set<Id>{OpportunitiesDAO.ORGANISATION_GIVING_RECTYPE_ID},AccessLevel.USER_MODE);

            oppRecords[0].Start_Date__c = System.today() + 10 ;
            oppRecords[0].Description = 'Opp Test';
            oppRecords[0].StageName = 'Qualify';
            OpportunitiesDAO.newInstance().updateRecords(oppRecords, false, AccessLevel.USER_MODE);
            Test.stopTest();

            List<Opportunity> oppUpdatedRecords = OpportunitiesDAO.getRecordsBySetIds(new Set<Id>{oppRecords[0].Id});
            System.assert(oppUpdatedRecords[0].StageName.equals('Qualify'), 'Stage is successfully changed to Qualify.');
        }
    }

    @isTest
    private static void checkStageUpdateWithInActivePrimaryContact() {
        System.runAs(TestDataFactory.getAdvancementManager()) {
            Test.startTest();
            List<Opportunity> oppRecords = OpportunitiesDAO.getOpportunityByRecordTypeIds(new Set<Id>{OpportunitiesDAO.ORGANISATION_GIVING_RECTYPE_ID},AccessLevel.USER_MODE);
            List<Contextual_Role__c> contextualRoleRecordsToUpdate = new List<Contextual_Role__c>();
            List<Contextual_Role__c> contextualRoleRecords = ContextualRolesDAO.newInstance().getActiveOpportunityContextualRolesRecords(new Set<Id>{oppRecords[0].Id}, new List<String>{CONTRIBUTORS_CONTEXTUAL_ROLE_GROUP});

            for(Contextual_Role__c con : contextualRoleRecords){
                con.Role_Is_Active__c = false;
                contextualRoleRecordsToUpdate.add(con);
            }
            ContextualRolesDAO.newInstance().updateRecords(contextualRoleRecordsToUpdate, false, AccessLevel.USER_MODE);

            oppRecords[0].Start_Date__c = System.today() + 10 ;
            oppRecords[0].Description = 'Opp Test';
            oppRecords[0].StageName = 'Qualify';
            Database.SaveResult[] srList = OpportunitiesDAO.newInstance().updateRecords(oppRecords, false, AccessLevel.USER_MODE);
            Test.stopTest();

            List<Opportunity> oppUpdatedRecords = OpportunitiesDAO.getRecordsBySetIds(new Set<Id>{oppRecords[0].Id});
            for (Database.SaveResult sr : srList) {
                System.assert(!sr.isSuccess(), 'A record was saved.');
            }
            System.assert(oppUpdatedRecords[0].StageName.equals('Identify'), 'Stage value is Identify.');
        }
    }

    @isTest
    static void opportunityWithPendingPlanActivityStatusTest(){
        System.runAs(TestDataFactory.getAdvancementManager()){
            List<Opportunity> oppRecords = OpportunitiesDAO.getOpportunityByRecordTypeIds(new Set<Id>{OpportunitiesDAO.ORGANISATION_GIVING_RECTYPE_ID},AccessLevel.USER_MODE);
            List<Plan_Activity__c> planActivityRecords = PlanActivitiesDAO.newInstance().getPlanActivityRecordsWithOpportunityIds(new Set<Id>{oppRecords[0].id}, AccessLevel.SYSTEM_MODE);
            
            Test.startTest();
            for( Plan_Activity__c planActivity: planActivityRecords){
                planActivity.Status__c = 'Pending';
            }
            PlanActivitiesDAO.newInstance().updateRecords(planActivityRecords, false, AccessLevel.USER_MODE);
            Test.stopTest();
            oppRecords[0].StageName = 'Solicitation';
            Database.SaveResult[] srList = OpportunitiesDAO.newInstance().updateRecords(oppRecords, false, AccessLevel.USER_MODE);
            for (Database.SaveResult sr : srList) {
                System.assert(!sr.isSuccess(), 'A record was saved.'); 
            }
        }
    }

    @isTest
    private static void checkStageUpdateWithProposedDonations() {
        System.runAs(TestDataFactory.getAdvancementManager()) {
            Test.startTest();
            List<Opportunity> oppRecords = OpportunitiesDAO.getOpportunityByRecordTypeIds(new Set<Id>{OpportunitiesDAO.INDIVIDUAL_GIVING_RECTYPE_ID},AccessLevel.USER_MODE);

            oppRecords[0].StageName = 'Executed' ;
            OpportunitiesDAO.newInstance().updateRecords(oppRecords, false, AccessLevel.USER_MODE);
            Test.stopTest();

            List<Opportunity> oppUpdatedRecords = OpportunitiesDAO.getRecordsBySetIds(new Set<Id>{oppRecords[0].Id});
            System.assert(oppUpdatedRecords[0].StageName.equals('Solicitation'), 'Stage value is Solicitation.');
        }
    }

    @isTest
    private static void checkStageUpdateWithNoAcceptedOrCompletedDonations() {
        System.runAs(TestDataFactory.getPortalSysAdminUser()) {
            List<Opportunity> oppList = OpportunitiesDAO.getOpportunityByRecordTypeIds(new Set<Id>{OpportunitiesDAO.INDIVIDUAL_GIVING_RECTYPE_ID},AccessLevel.USER_MODE);
            List<Donation__c> relatedDonations = DonationsDAO.getDonationsByOpportunityIds(new Set<Id>{oppList[0].Id},AccessLevel.USER_MODE);

            for(Donation__c don : relatedDonations){
                don.Stage__c = 'Active';
            }

            DonationsDAO.newInstance().updateRecords(relatedDonations, false, AccessLevel.USER_MODE);
        }
        System.runAs(TestDataFactory.getAdvancementManager()) {

            Test.startTest();
            List<Opportunity> oppRecords = OpportunitiesDAO.getOpportunityByRecordTypeIds(new Set<Id>{OpportunitiesDAO.INDIVIDUAL_GIVING_RECTYPE_ID},AccessLevel.USER_MODE);

            oppRecords[0].StageName = 'Executed' ;
            OpportunitiesDAO.newInstance().updateRecords(oppRecords, false, AccessLevel.USER_MODE);
            Test.stopTest();

            List<Opportunity> oppUpdatedRecords = OpportunitiesDAO.getRecordsBySetIds(new Set<Id>{oppRecords[0].Id});
            System.assert(oppUpdatedRecords[0].StageName.equals('Solicitation'), 'Stage value is Solicitation.');
        }
    }

    @isTest
    private static void checkStageUpdateWithAcceptedOrCompletedDonations() {
        System.runAs(TestDataFactory.getPortalSysAdminUser()) {
            List<Opportunity> oppList = OpportunitiesDAO.getOpportunityByRecordTypeIds(new Set<Id>{OpportunitiesDAO.INDIVIDUAL_GIVING_RECTYPE_ID},AccessLevel.USER_MODE);
            List<Donation__c> relatedDonations = DonationsDAO.getDonationsByOpportunityIds(new Set<Id>{oppList[0].Id},AccessLevel.USER_MODE);

            for(Donation__c don : relatedDonations){
                don.Stage__c = 'Accepted';
            }

            DonationsDAO.newInstance().updateRecords(relatedDonations, false, AccessLevel.USER_MODE);
        }
        System.runAs(TestDataFactory.getAdvancementManager()) {

            Test.startTest();
            List<Opportunity> oppRecords = OpportunitiesDAO.getOpportunityByRecordTypeIds(new Set<Id>{OpportunitiesDAO.INDIVIDUAL_GIVING_RECTYPE_ID},AccessLevel.USER_MODE);

            oppRecords[0].StageName = 'Executed' ;
            OpportunitiesDAO.newInstance().updateRecords(oppRecords, false, AccessLevel.USER_MODE);
            Test.stopTest();

            List<Opportunity> oppUpdatedRecords = OpportunitiesDAO.getRecordsBySetIds(new Set<Id>{oppRecords[0].Id});
            System.assert(oppUpdatedRecords[0].StageName.equals('Executed'), 'Stage value is successfully changed to Executed.');
        }
    }
}