src/core-crm/main/objects/Account/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Foreign Key for Integration and Data Migration.</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/core-crm/objects/Account/fields/Organization_Unit_Level__c.field-meta.xml
<CustomField>
    <fullName>Organization_Unit_Level__c</fullName>
    <description>The level (1,2,3) of the organizational unit within the QUT Organizational hierarchy.</description>
    <label>Organization Unit Level</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Contact/fields/Contact_Image__c.field-meta.xml
<CustomField>
    <fullName>Contact_Image__c</fullName>
    <label>Contact Image</label>
    <length>75768</length>
    <type>Html</type>
</CustomField>

src/core-crm/objects/Contact/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Foreign Key for Integration and Data Migration</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/core-crm/objects/hed__Course__c/hed__Course__c.object-meta.xml
<CustomObject>
    <description>Academic Course offered by a Department or School, for example, English 101 or Ancient History.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course__c/fields/Delivery_Type__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Type__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Face to Face</fullName>
            </value>
            <value>
                <fullName>Virtual Classroom</fullName>
            </value>
            <value>
                <fullName>Blended</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/hed__Course_Offering__c.object-meta.xml
<CustomObject>
    <description>Joins Courses and Terms to contain information related to a single occurrence of a Course.</description>
    <label>Course Offering</label>
    <nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Offering__c/fields/Delivery_Type__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Type__c</fullName>
    <description>This will be how the course will be delivered and location for face-to-face.</description>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online Classroom</fullName>
            </value>
            <value>
                <fullName>Online Self-paced</fullName>
            </value>
            <value>
                <fullName>Brisbane Classroom</fullName>
            </value>
            <value>
                <fullName>Canberra Classroom</fullName>
            </value>
            <value>
                <fullName>Melbourne Classroom</fullName>
            </value>
            <value>
                <fullName>Sydney Classroom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>External ID used for integration</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Capacity__c.field-meta.xml
<CustomField>
    <fullName>hed__Capacity__c</fullName>
    <description>The maximum number of students for this Course Offering.</description>
    <inlineHelpText>The maximum number of students for this Course Offering.</inlineHelpText>
    <label>Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Course__c.field-meta.xml
<CustomField>
    <fullName>hed__Course__c</fullName>
    <description>Lookup to the Course record that this Course Offering is associated with.</description>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>
 

src/core-crm/objects/hed__Course_Offering__c/fields/hed__End_Date__c.field-meta.xml
<CustomField>
    <fullName>hed__End_Date__c</fullName>
    <description>The date of the last session for this Course Offering.</description>
    <inlineHelpText>The date of the last session for this Course Offering.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>hed__Start_Date__c</fullName>
    <description>The date of the first session for this Course Offering.</description>
    <inlineHelpText>The date of the first session for this Course Offering.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Term__c.field-meta.xml
<CustomField>
    <fullName>hed__Term__c</fullName>
    <description>Lookup to the Term record that represents when this Course Offering takes place.</description>
    <label>Term</label>
    <referenceTo>hed__Term__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>
 

src/core-crm/objects/hed__Course_Offering__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This will be used to deactivate Offering.</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/fields/Registration_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_End_Date__c</fullName>
    <label>Registration End Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/fields/Registration_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Start_Date__c</fullName>
    <label>Registration Start Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/fields/Total_Number_of_Registered_Learners__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_of_Registered_Learners__c</fullName>
    <description>This is the total number of Enrolments where status != Cancelled.</description>
    <label>Total Number of Registered Learners</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/hed__Term__c/hed__Term__c.object-meta.xml
<CustomObject>
    <description>Unit of time in which academic activities are taking place.</description>
    <label>Term</label>
    <nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Term__c/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <description>The External ID used for integration</description>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Term__c/fields/hed__End_Date__c.field-meta.xml
<CustomField>
    <fullName>hed__End_Date__c</fullName>
    <description>The date this Term ends.</description>
    <inlineHelpText>The date this Term ends.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/hed__Term__c/fields/hed__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>hed__Start_Date__c</fullName>
    <description>The date this Term starts.</description>
    <inlineHelpText>The date this Term starts.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Product_Request__c/Product_Request__c.object-meta.xml
<CustomObject>
    <label>Product Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Product Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/classes/CourseOfferingTriggerHandlerTest.cls
/**
 * @description CourseOfferingTriggerHandler Test Class
 * @see CourseOfferingTriggerHandler
 *
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | eugene.andrew.abuan            | March 22, 2022        | DEPP-1991              | Created file                 |
      | roy.nino.s.regala              | June 04, 2022         | DEPP-2876              | Created file                 |
      | eugene.andrew.abuan            | July 31 , 2022        | DEPP-3534              | Added Before Update          |

 */
@isTest
public with sharing class CourseOfferingTriggerHandlerTest {
    private static User currentUser = TestDataFactory.createUserRecords(1,'QUTeX').iterator().next();
    private static final String ACCT_UNIV_DEP = System.Label.RT_Account_University_Department;
    private static final Id ACCT_UNIV_DEP_ID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(ACCT_UNIV_DEP).getRecordTypeId();

    @testSetup
    static void setupMethod() {
        TestDataFactoryUser.generateUserQUTeXProgramAdministrator();
    }

    @isTest
    private static void insertCourseConnectionTest() {
        System.runAs(currentUser) {
            Test.startTest();

            List<Account> accounts = TestDataFactory.createTestAccountRecords(1);
            for(Account account : accounts){
                account.RecordTypeId = ACCT_UNIV_DEP_ID;
                account.Organization_Unit_Level__c = '2';
            }            
            insert accounts;
    
            List<Contact> contacts = TestDataFactory.createTestContactRecords(1);
            insert contacts;
    
            List<hed__Term__c> terms = TestDataFactory.createTestTermRecords(10,accounts[0].Id);
            insert terms;
    
            List<Product_Request__c> prodRequest = TestDataFactory.createTestProductRequestRecords(1);
            insert prodRequest;
    
            List<hed__Course__c> courses = TestDataFactory.createTestCourseRecords(10,accounts[0].Id,prodRequest[0].Id);
            insert courses;
    
            List<hed__Course_Offering__c> courseOfferings = TestDataFactory.createTestCourseOfferingRecord(10,courses,terms);
            for(hed__Course_Offering__c cc : courseOfferings){
                cc.Registration_Start_Date__c = Date.today();
                cc.Registration_End_Date__c = Date.today()+2;
            }
            insert courseOfferings;

            Test.stopTest();
            List<hed__Course_Offering__c> courseOfferingsList = new List<hed__Course_Offering__c>();
            courseOfferingsList = [SELECT ID, External_Id__c FROM hed__Course_Offering__c];

            System.assert(courseOfferingsList[0].External_Id__c != null, 'External Id is not populated');
        }
    }

    @isTest
    private static void validateRelatedProductBeforeUpdateTest() {
        System.runAs(TestDataFactoryUser.selectUserQUTeXProgramAdministrator) {
            Test.startTest();

            List<Account> accounts = TestDataFactory.createTestAccountRecords(100);
            for (Account account : accounts) {
              account.RecordTypeId = ACCT_UNIV_DEP_ID;
              account.Organization_Unit_Level__c = '2';
            }
            insert accounts;
      
            List<Contact> contacts = TestDataFactory.createTestContactRecords(100);
            contacts[0].Contact_Image__c = 'test';
            insert contacts;
      
            List<hed__Term__c> terms = TestDataFactory.createTestTermRecords(100,accounts[0].Id);
            insert terms;
      
            List<Product_Request__c> prodRequest = TestDataFactory.createTestProductRequestRecords(100);
            insert prodRequest;
      
            List<hed__Course__c> courses = TestDataFactory.createTestCourseRecords(100,accounts[0].Id,prodRequest[0].Id);
            insert courses;
            
            List<Product2> products = TestDataFactory.createTestProductRecords(100,courses);
            insert products;

            List<hed__Course_Offering__c> courseOfferings = TestDataFactory.createTestCourseOfferingRecord(100,courses,terms);
            for(hed__Course_Offering__c courseOffering : courseOfferings){
                courseOffering.hed__Start_Date__c = Date.today()+1;
                courseOffering.hed__End_Date__c = Date.today()+2;
                
            }
            insert courseOfferings;
            
            Integer cCount = 0;
            List<hed__Course_Offering__c> cOffToUpdate = new List<hed__Course_Offering__c>();
            cOffToUpdate = [SELECT Id, IsActive__c FROM hed__Course_Offering__c];
            for(hed__Course_Offering__c cOff1 : cOffToUpdate){
                cOff1.Delivery_Type__c = 'Online Self-paced';
                cOff1.IsActive__c = true;
                cCount++;
                if(cCount > 90){
                    cOff1.Registration_Start_Date__c = system.today() + 1;
                    cOff1.Registration_End_Date__c = null;
                    cOff1.IsActive__c = false;
                }
                cOff1.hed__Capacity__c = 100;
                cOff1.Total_Number_of_Registered_Learners__c = 50;
            }
            update cOffToUpdate;

            Test.stopTest();
            System.assert(cOffToUpdate.size() > 0,'Course Offering records wer');
        }
    }

}