src/core-crm/objects/Contact/fields/Accessibility_Requirement__c.field-meta.xml
<CustomField>
    <fullName>Accessibility_Requirement__c</fullName>
    <label>Accessibility Requirement</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

src-env-specific-pre/objects/Contact/fields/ContactMobile_Locale__c.field-meta.xml
<CustomField>
    <fullName>ContactMobile_Locale__c</fullName>
    <label>ContactMobile Locale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Loqate_Locale</valueSetName>
    </valueSet>
</CustomField>

src/core-crm/objects/Contact/fields/Dietary_Requirement__c.field-meta.xml
<CustomField>
    <fullName>Dietary_Requirement__c</fullName>
    <description>Capture details for learner’s dietary requirements</description>
    <label>Dietary Requirement</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

src/core-crm/objects/Contact/fields/Mobile_No_Locale__c.field-meta.xml
<CustomField>
    <fullName>Mobile_No_Locale__c</fullName>
    <description>Captures the Mobile with no Locale</description>
    <externalId>true</externalId>
    <label>Mobile (No Locale)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Contact/fields/Registered_Email__c.field-meta.xml
<CustomField>
    <fullName>Registered_Email__c</fullName>
    <description>All automated email communications will be sent to this email address.</description>
    <label>Registered Email</label>
    <type>Email</type>
</CustomField>

src/core-crm/objects/User/fields/Birthdate__c.field-meta.xml
<CustomField>
    <fullName>Birthdate__c</fullName>
    <label>Birthdate</label>
    <type>Date</type>
</CustomField>

src/core-crm/globalValueSets/Loqate_Locale.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Australia (+61)</fullName>
        <default>true</default>
        <label>Australia (+61)</label>
    </customValue>
    <customValue>
        <fullName>New Zealand (+64)</fullName>
    </customValue>
    <customValue>
        <fullName>International</fullName>
    </customValue>
    <customValue>
        <fullName>Afghanistan (93)</fullName>
    </customValue>
    <customValue>
        <fullName>Åland Islands (358)</fullName>
    </customValue>
    <customValue>
        <fullName>Albania (355)</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria (213)</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa (1-684)</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra (376)</fullName>
    </customValue>
    <customValue>
        <fullName>Angola (244)</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla (1-264)</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica (672)</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda (1-268)</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina (54)</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia (374)</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba (297)</fullName>
    </customValue>
    <customValue>
        <fullName>Austria (43)</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan (994)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas (the) (1-242)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain (973)</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh (880)</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados (1-246)</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus (375)</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium (32)</fullName>
    </customValue>
    <customValue>
        <fullName>Belize (501)</fullName>
    </customValue>
    <customValue>
        <fullName>Benin (229)</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda (1-441)</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan (975)</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia (Plurinational State of) (591)</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba (599)</fullName>
    </customValue>
    <masterLabel>Loqate Locale</masterLabel>
</GlobalValueSet>

src/core-crm/classes/PortalUsernameFormatFlowTest.cls
/**
 * @description Test Class for Portal_Username_Format Flow
 * @see ..Portal_Username_Format Flow
 * @author Accenture
 * @history
 *    | Developer                 | Date                  | JIRA                 | Change Summary               |
      |---------------------------|-----------------------|----------------------|------------------------------|
      | kenneth.f.alsay           | July 26, 2024         | DEPP-9231            | Created file                 |
 */

 @isTest
 public with sharing class PortalUsernameFormatFlowTest {
 
   public static final Id PERSON = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName()
     .get('Person')
     .getRecordTypeId();
 
   @testSetup
   public static void setUp() {
     Test.startTest();
         TestDataFactoryUser.generateUserSystemAdministrator();
 
         BuyerGroup opeBuyerGroup = new BuyerGroup(Name = 'OPE BuyerGroup');
         insert opeBuyerGroup;
 
     Test.stopTest();
   }
 
   @isTest
   static void registerOPEUserTest() {
     Test.startTest();
     System.runAs(TestDataFactoryUser.selectUserSystemAdministrator) {
       Account testAccount = new Account();
       testAccount.Name = 'OPE Catalogue';
       insert testAccount;
       
       String uniqueID = GenerateUniqueId.getUUID();
       String emailTest = 'testUser' + uniqueID + '@test.com';
          
       Contact contactRecord = new Contact();
       contactRecord.FirstName = 'Test';
       contactRecord.LastName = 'User';
       contactRecord.Registered_Email__c = emailTest;
       contactRecord.MobilePhone = '611234567890';
       contactRecord.Dietary_Requirement__c = 'testDietary Req';
       contactRecord.Accessibility_Requirement__c = 'access Req';
       contactRecord.Mobile_No_Locale__c = '1234567890';
       contactRecord.ContactMobile_Locale__c = 'Australia (+61)';
 
       RegistrationFormCtrl.RegistrationDataWrapper registrationData = new RegistrationFormCtrl.RegistrationDataWrapper();   
       registrationData.startURL = '/study/s/';
       registrationData.isOptIn = true;
       registrationData.contactRecord = contactRecord;
 
       RegistrationFormCtrl.BirthDateWrapper birthDateData = new RegistrationFormCtrl.BirthDateWrapper();
       birthDateData.day = 1;
       birthDateData.month = 1;
       birthDateData.year = 1999;
 
       String page = RegistrationFormCtrl.registerUser(
           JSON.serialize(registrationData),
           JSON.serialize(birthDateData)
       );
 
       System.assert(page == null, 'Page must not be null');
     }
     Test.stopTest();
   }
 
   @isTest
   static void registerCCEUserTest() {
     Test.startTest();
     System.runAs(TestDataFactoryUser.selectUserSystemAdministrator) {
       Account testAccount = new Account();
       testAccount.Name = 'OPE Catalogue';
       insert testAccount;
 
       String uniqueID = GenerateUniqueId.getUUID();
       String emailTest = 'testUser' + uniqueID + '@test.com';
 
       Date birthdate = Date.newInstance(1999, 1, 1);
 
       //Set fields from the form to the Contact Object
       Contact c = new Contact();
       c.AccountId = testAccount.Id;
       c.FirstName = 'Test';
       c.lastName = 'User';
       c.Email = emailTest;
       c.MobilePhone = '12345';
       c.Birthdate = birthdate;
       c.Dietary_Requirement__c = 'testDietary Req';
       c.Accessibility_Requirement__c = 'access Req';
       insert (c);
 
 
 
       //Query Ecommerece Learner Profile
       Profile p = [
         SELECT Id
         FROM Profile
         WHERE Name = 'Corporate Partner'
       ];
 
       //Create User
       User u = new User();
       u.FirstName = c.FirstName;
       u.LastName = c.lastName;
       u.Email = c.Email;
       u.MobilePhone = c.MobilePhone;
       u.Birthdate__c = c.Birthdate;
       String alias = c.FirstName;
       if (alias.length() > 8) {
         alias = alias.substring(0, 8);
       }
       u.Username = emailTest+'.ope';
       u.alias = alias;
       u.LanguageLocaleKey = 'en_US';
       u.localesidkey = UserInfo.getLocale();
       u.emailEncodingKey = 'UTF-8';
       u.timeZoneSidKey = 'Australia/Brisbane';
       u.ContactId = c.Id;
       u.profileId = p.Id;
       insert (u);
     }
     System.assert(
       ![SELECT Id FROM User WHERE Profile.Name = 'Corporate Partner']
         .isEmpty(),
       'User must be created'
     );
     Test.stopTest();
   }
 
 }