src/core-crm/objects/Contact/fields/Do_Not_Sync_To_MC_Override__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Sync_To_MC_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When this is true, this will mark Sync to MC as false and this will not be synced to Marketing Cloud</description>
    <label>Do Not Sync To MC (Override)</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Contact/fields/Email_Opt_In_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Email_Opt_In_DateTime__c</fullName>
    <description>The date/time the marketing person opted in to receive marketing comms via Email.</description>
    <label>Email Opt In DateTime</label>
    <type>DateTime</type>
</CustomField>

src/core-crm/objects/Contact/fields/hed__SMS_Opt_Out__c.field-meta.xml
<CustomField>
    <fullName>hed__SMS_Opt_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether a person wants to receive SMS communications.</description>
    <inlineHelpText>Indicates whether a person wants to receive SMS communications.</inlineHelpText>
    <label>SMS Opt Out</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Contact/fields/Learner_Email_Opt_In_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Learner_Email_Opt_In_DateTime__c</fullName>
    <description>The date and time that the email was opted in</description>
    <label>Learner Email Opt In DateTime</label>
    <type>DateTime</type>
</CustomField>

src/core-crm/objects/Contact/fields/Learner_Email_Opt_Out__c.field-meta.xml
<CustomField>
    <fullName>Learner_Email_Opt_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Marketing should not email this email address</description>
    <label>Learner Email Opt Out</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Contact/fields/Learner_Email_Opt_Out_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Learner_Email_Opt_Out_DateTime__c</fullName>
    <description>The date and time that the email was opted out</description>
    <label>Learner Email Opt Out DateTime</label>
    <type>DateTime</type>
</CustomField>

src/core-crm/objects/Contact/fields/SMS_Opt_In_DateTime__c.field-meta.xml
<CustomField>
    <fullName>SMS_Opt_In_DateTime__c</fullName>
    <description>The date/time the marketing person opted in to receive marketing comms via SMS.</description>
    <label>SMS Opt In DateTime</label>
    <type>DateTime</type>
</CustomField>

src/core-crm/objects/Contact/fields/Staff_Email_Opt_In_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Staff_Email_Opt_In_DateTime__c</fullName>
    <description>The date and time that the email was opted in</description>
    <label>Staff Email Opt In DateTime</label>
    <type>DateTime</type>
</CustomField>

src/core-crm/objects/Contact/fields/Staff_Email_Opt_Out__c.field-meta.xml
<CustomField>
    <fullName>Staff_Email_Opt_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Marketing should not email this email address</description>
    <label>Staff Email Opt Out</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Contact/fields/Staff_Email_Opt_Out_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Staff_Email_Opt_Out_DateTime__c</fullName>
    <description>The date and time that the email was opted out</description>
    <label>Staff Email Opt Out DateTime</label>
    <type>DateTime</type>
</CustomField>

src/core-crm/objects/Contact/fields/Work_Email_Opt_In_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Work_Email_Opt_In_DateTime__c</fullName>
    <description>The date and time that the email was opted in</description>
    <label>Work Email Opt In DateTime</label>
    <type>DateTime</type>
</CustomField>

src/core-crm/objects/Contact/fields/Work_Email_Opt_Out__c.field-meta.xml
<CustomField>
    <fullName>Work_Email_Opt_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Marketing should not email this email address</description>
    <label>Work Email Opt Out</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Contact/fields/Work_Email_Opt_Out_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Work_Email_Opt_Out_DateTime__c</fullName>
    <description>The date and time that the email was opted out</description>
    <label>Work Email Opt Out DateTime</label>
    <type>DateTime</type>
</CustomField>

src/core-crm/objects/Contact/fields/Work_SMS_Opt_In_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Work_SMS_Opt_In_DateTime__c</fullName>
    <description>The date and time that the mobile opted in</description>
    <label>Work SMS Opt In DateTime</label>
    <type>DateTime</type>
</CustomField>

src/core-crm/objects/Contact/fields/Work_SMS_Opt_Out__c.field-meta.xml
<CustomField>
    <fullName>Work_SMS_Opt_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Marketing should not sms this mobile number</description>
    <label>Work SMS Opt Out</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Contact/fields/Work_SMS_Opt_Out_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Work_SMS_Opt_Out_DateTime__c</fullName>
    <description>The date and time that the mobile opted out</description>
    <label>Work SMS Opt Out DateTime</label>
    <type>DateTime</type>
</CustomField>

src/core-crm/classes/MarketingServiceTest.cls
/**
 * @description Test Class for MarketingService
 * @see ..MarketingService
 *
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary                                 |
 *    |--------------------------------|-----------------------|------------------------|------------------------------------------------|
 *    | roy.nino.s.regala              | Nov 28, 2023          | DEPP-6979              | Created file                                   |
 */

 @isTest
 @SuppressWarnings('PMD.ApexUnitTestClassShouldHaveRunAs')
 //PMD ApexUnitTestClassShouldHaveRunAs is bypassed for service class methods 
 //because these methods are reusable, test method is mocked, and user access tests are performed on the caller
 public without sharing class MarketingServiceTest {
 
     @isTest
     public static void optInOrOutMarketingOptInTest(){
        Contact con = new Contact();
        MarketingService.optInOrOutMarketing(con, true);
        System.assertEquals(false, con.HasOptedOutOfEmail, 'Marketing field should be false');
        System.assertEquals(false, con.Learner_Email_Opt_Out__c, 'Marketing field should be false');
        System.assertEquals(false, con.Staff_Email_Opt_Out__c, 'Marketing field should be false');
        System.assertEquals(false, con.Work_Email_Opt_Out__c, 'Marketing field should be false');
        System.assertEquals(false, con.Work_SMS_Opt_Out__c, 'Marketing field should be false');
        System.assertEquals(false, con.hed__SMS_Opt_Out__c, 'Marketing field should be false');
        System.assertEquals(false, con.DoNotCall, 'Marketing field should be false');
        System.assertEquals(true, con.Sync_to_MC__c, 'Marketing field should be true');
        System.assertEquals(false, con.Do_Not_Sync_To_MC_Override__c, 'Marketing field should be false');
        System.assert(con.Dont_Market_Reason__c == null, 'Marketing field Dont_Market_Reason__c should be empty');
        System.assert(con.Email_Opt_In_DateTime__c != null, 'Marketing field should be populated');
        System.assert(con.Learner_Email_Opt_In_DateTime__c != null, 'Marketing field should be populated');
        System.assert(con.Staff_Email_Opt_In_DateTime__c != null, 'Marketing field should be populated');
        System.assert(con.Work_Email_Opt_In_DateTime__c != null, 'Marketing field should be populated');
        System.assert(con.Work_SMS_Opt_In_DateTime__c != null, 'Marketing field should be populated');
        System.assert(con.SMS_Opt_In_DateTime__c != null, 'Marketing field should be populated');
     }

     @isTest
     public static void optInOrOutMarketingOptOutTest(){
        Contact con = new Contact();
        MarketingService.optInOrOutMarketing(con, false);
        System.assertEquals(true, con.HasOptedOutOfEmail, 'Marketing field should be true');
        System.assertEquals(true, con.Learner_Email_Opt_Out__c, 'Marketing field should be true');
        System.assertEquals(true, con.Staff_Email_Opt_Out__c, 'Marketing field should be true');
        System.assertEquals(true, con.Work_Email_Opt_Out__c, 'Marketing field should be true');
        System.assertEquals(true, con.Work_SMS_Opt_Out__c, 'Marketing field should be true');
        System.assertEquals(true, con.hed__SMS_Opt_Out__c, 'Marketing field should be true');
        System.assertEquals(true, con.DoNotCall, 'Marketing field should be true');
        System.assertEquals(false, con.Sync_to_MC__c, 'Marketing field should be false');
        System.assertEquals(false, con.Do_Not_Sync_To_MC_Override__c, 'Marketing field should be false');
        System.assertEquals('QTAC Application QUT preferences withdrawn',con.Dont_Market_Reason__c, 'Marketing field Dont_Market_Reason__c should be QTAC Application QUT preferences withdrawn');
        System.assert(con.Email_Opt_Out_DateTime__c != null, 'Marketing field should be populated');
        System.assert(con.Learner_Email_Opt_Out_DateTime__c != null, 'Marketing field should be populated');
        System.assert(con.Staff_Email_Opt_Out_DateTime__c != null, 'Marketing field should be populated');
        System.assert(con.Work_Email_Opt_Out_DateTime__c != null, 'Marketing field should be populated');
        System.assert(con.Work_SMS_Opt_Out_DateTime__c != null, 'Marketing field should be populated');
        System.assert(con.SMS_Opt_Out_DateTime__c != null, 'Marketing field should be populated');
     }
 }