src/core-crm/objects/Contact/fields/Lead_Score_Detail__c.field-meta.xml
<CustomField>
    <fullName>Lead_Score_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The breakdown of lead scoring by category aggregates.</description>
    <label>Lead Score Detail</label>
    <referenceTo>Lead_Score_Detail__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Program_Enrollment__c/hed__Program_Enrollment__c.object-meta.xml
<CustomObject>
    <description>A student Contact&apos;s enrollment in an academic program offered by a Department or School (the degree-granting Account type for the educational institution).</description>
    <label>Program Enrollment</label>
    <nameField>
        <displayFormat>PE-{0000}</displayFormat>
        <label>Program Enrollment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Program_Enrollment__c/fields/Enrollment_Status__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Status__c</fullName>
    <description>The enrollment status as per SAMS status</description>
    <label>Enrollment Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Program_Enrollment__c/fields/hed__Contact__c.field-meta.xml
<CustomField>
    <fullName>hed__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student enrolled in this Program.</description>
    <inlineHelpText>The student enrolled in this Program.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Program Enrollments</relationshipLabel>
    <relationshipName>Program_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Lead/fields/Lead_Score_Detail__c.field-meta.xml
<CustomField>
    <fullName>Lead_Score_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The breakdown of lead scoring by category aggregates.</description>
    <label>Lead Score Detail</label>
    <referenceTo>Lead_Score_Detail__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Lead_Score_Detail__c/Lead_Score_Detail__c.object-meta.xml
<CustomObject>
    <label>Lead Score Detail</label>
    <nameField>
        <displayFormat>LSD-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Score Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/classes/ProgramEnrollmentTriggerHelper.cls
/**
 * @description Program Enrollment object trigger helper class
 * @see ProgramEnrollmentTriggerHandler
 *
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | roy.nino.s.regala		       | November 03, 2023     | DEPP-7145              | Created file                 |
 */

public with sharing class ProgramEnrollmentTriggerHelper {
    /**
     * @description reset the lead score of the linked contact
     * @param newItems  List of new hed__Program_Enrollment__c  records
     * @param oldItems  Map of old hed__Program_Enrollment__c  records
     */
    public static void resetLeadScore(
        List<hed__Program_Enrollment__c > newItems,
        Map<Id, hed__Program_Enrollment__c > oldItems
    ) {
        Set<Id> contactIdSet = new Set<Id>();
        for (hed__Program_Enrollment__c  enrolment : newItems) {

            Boolean isStudying =
                enrolment.Enrollment_Status__c ==
                ProgramEnrollmentsDAO.ENROLLMENT_STATUS_ADMITTED &&
                enrolment.Enrollment_Status__c != oldItems.get(enrolment.Id).Enrollment_Status__c;

            //if a program enrolment with a contact has its status updated to admitted
            //collect contact ids 
            //and set lead score reset to true
            if (enrolment.hed__Contact__c != null && isStudying) {
                contactIdSet.add(enrolment.hed__Contact__c);
                enrolment.Lead_Score_Reset__c = true;
            }
        }

        //enqueue lead score reset of contact's related records
        if (!contactIdSet.isEmpty()) {
            Boolean isAsyncProcess = System.isQueueable() || System.isFuture() || System.isBatch();
            if (isAsyncProcess) {
                updateLeadScoreRelatedRecords(contactIdSet);
            } else {
                QueueableCall executeQueueable = new QueueableCall(contactIdSet);
                System.enqueueJob(executeQueueable);
            }
        }
    }

    private static void updateLeadScoreRelatedRecords(Set<Id> contactIdSet){
        List<Lead_Score_Detail__c> leadScoreDetails = LeadScoreResetService.getLeadScoreDetailsToUpdate(contactIdSet);
        if(!leadScoreDetails.isEmpty()){
            LeadScoreDetailsDAO.newInstance().updateRecords(leadScoreDetails, false, AccessLevel.SYSTEM_MODE);
            LeadScoreResetService.updateLeadScoreResetForMktgInt(contactIdSet);
            LeadScoreResetService.updateLeadScoreResetForIndivEmail(contactIdSet);
            LeadScoreResetService.updateLeadScoreResetForCase(contactIdSet);
        }
    }

    private class QueueableCall implements Queueable {
        private Set<Id> contactIdSet;

        public QueueableCall(Set<Id> contactIdSet) {
            this.contactIdSet = contactIdSet;
        }
        public void execute(QueueableContext context) {
            updateLeadScoreRelatedRecords(contactIdSet);
        }
    }
}