src/core-crm/objects/Contact/fields/Lead_Score_Detail__c.field-meta.xml
<CustomField>
    <fullName>Lead_Score_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The breakdown of lead scoring by category aggregates.</description>
    <label>Lead Score Detail</label>
    <referenceTo>Lead_Score_Detail__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Lead/fields/Lead_Score_Detail__c.field-meta.xml
<CustomField>
    <fullName>Lead_Score_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The breakdown of lead scoring by category aggregates.</description>
    <label>Lead Score Detail</label>
    <referenceTo>Lead_Score_Detail__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Lead_Score_Detail__c/Lead_Score_Detail__c.object-meta.xml
<CustomObject>
    <label>Lead Score Detail</label>
    <nameField>
        <displayFormat>LSD-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Score Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Lead_Score_Detail__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to name of the contact the score belongs to.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Lead Score Details</relationshipLabel>
    <relationshipName>Lead_Score_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/classes/LeadScoreDetailTriggerHelper.cls
/**
 * @description helper for LeadScoreDetailTriggerHandler
 * @see LeadScoreDetailTriggerHandler
 *
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary                                   |
      |--------------------------------|-----------------------|------------------------|--------------------------------------------------|
      | julie.jane.alegre              | Sept 07, 2023         | DEPP-5965              | Created file                                     |
 */
public with sharing class LeadScoreDetailTriggerHelper {
    /**
     * @description process records to be set as current preference
     * @param newItems - List of Lead_Score_Detail__c new records
     * @param oldItems - Map<Id, Lead_Score_Detail__c> old records map
     */
    public static void linkLeadScoreDetailToContact(Map<Id, Lead_Score_Detail__c> newItems){
        Map<Id,Id> leadScoreDetailMap = new Map<Id,Id>();
        List<Contact> contactToUpdate = new List<Contact>();
        //Get contact id link to the newly created lead score detail
        for(Lead_Score_Detail__c leadScoreDetail:newItems.values()){
            if( leadScoreDetail.Contact__c != null ){
                leadScoreDetailMap.put(leadScoreDetail.Contact__c, leadScoreDetail.Id);
            }
        }
        List<Contact> contactList = ContactsDAO.newInstance().getContactsFromConvertedLead(leadScoreDetailMap.keySet(), 'SYSTEM_MODE');

        for(Contact contacts: contactList){
            if(leadScoreDetailMap.containsKey(contacts.Id)){
                contacts.Lead_Score_Detail__c = leadScoreDetailMap.get(contacts.Id);
                contactToUpdate.add(contacts);
            }
        }
        if(!contactToUpdate.isEmpty()){
            ContactsDAO.newInstance().updateRecords(contactToUpdate, false, AccessLevel.SYSTEM_MODE);
        }
    }
}