src/core-crm/objects/Contact/fields/Marketing_Segmentation__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Segmentation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Preferences</label>
    <referenceTo>Marketing_Segmentation__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Lead/fields/Marketing_Segmentation__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Segmentation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Segmentation</label>
    <referenceTo>Marketing_Segmentation__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Lead_Score_Configuration__c/Lead_Score_Configuration__c.object-meta.xml
<CustomObject>
    <label>Lead Score Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Score Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Lead_Score_Configuration__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>The description of the record and it’s usage in scoring</description>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

src/core-crm/objects/Lead_Score_Configuration__c/fields/Domestic_International__c.field-meta.xml
<CustomField>
    <fullName>Domestic_International__c</fullName>
    <description>Whether the configuration is related to Domestic or International scoring scheme</description>
    <label>Domestic or International</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Lead_Score_Configuration__c/fields/Max_Score__c.field-meta.xml
<CustomField>
    <fullName>Max_Score__c</fullName>
    <description>The max score a category is allowed to accumulate</description>
    <label>Max Score</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Lead_Score_Configuration__c/fields/Score_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Score_Allocation__c</fullName>
    <description>Score that should be allocated for each instance of the interaction</description>
    <label>Score Allocation</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Lead_Score_Configuration__c/fields/Study_Level__c.field-meta.xml
<CustomField>
    <fullName>Study_Level__c</fullName>
    <description>The level of education is used to determine the sub scheme the scoring configuration belongs.</description>
    <label>Study Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Undergraduate</fullName>
            </value>
            <value>
                <fullName>Postgraduate</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Lead_Score_Configuration__c/fields/Time_Limit_Months__c.field-meta.xml
<CustomField>
    <fullName>Time_Limit_Months__c</fullName>
    <description>The number months the calculation needs to consider activities for from current month</description>
    <label>Time Limit (Months)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Marketing_Segmentation__c/Marketing_Segmentation__c.object-meta.xml
<CustomObject>
    <label>Marketing Segmentation</label>
    <nameField>
        <displayFormat>MS - {000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Segmentations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Marketing_Segmentation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Marketing Segmentations</relationshipLabel>
    <relationshipName>Marketing_Segmentations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Marketing_Segmentation__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Marketing Segmentations</relationshipLabel>
    <relationshipName>Marketing_Segmentations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Marketing_Segmentation__c/fields/My_Primary_NSA__c.field-meta.xml
<CustomField>
    <fullName>My_Primary_NSA__c</fullName>
    <description>Profile Type = Myself

The primary NSA or NSAs (which are related to the primary BSA selected by the marketing person) that they have expressed interest in receiving marketing material about.

A person can select 1 or more NSAs where applicable.</description>
    <label>My Primary NSA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>I am not sure</fullName>
            </value>
            <value>
                <fullName>Accounting and Financial Planning</fullName>
            </value>
            <value>
                <fullName>Acting, Drama and Technical Production</fullName>
            </value>
            <value>
                <fullName>Advertising, Marketing and PR</fullName>
            </value>
            <value>
                <fullName>Architecture</fullName>
            </value>
            <value>
                <fullName>Behavioural Economics</fullName>
            </value>
            <value>
                <fullName>Biological Science</fullName>
            </value>
            <value>
                <fullName>Business Process Management</fullName>
            </value>
            <value>
                <fullName>Chemistry</fullName>
            </value>
            <value>
                <fullName>Communication</fullName>
            </value>
            <value>
                <fullName>Construction Management</fullName>
            </value>
            <value>
                <fullName>Creative Writing</fullName>
            </value>
            <value>
                <fullName>Dance</fullName>
            </value>
            <value>
                <fullName>Data Science and Analytics</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Digital Capability</fullName>
            </value>
            <value>
                <fullName>Digital MBA</fullName>
            </value>
            <value>
                <fullName>Early Childhood</fullName>
            </value>
            <value>
                <fullName>Earth Science</fullName>
            </value>
            <value>
                <fullName>Economics and Finance</fullName>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>Environmental Science</fullName>
            </value>
            <value>
                <fullName>Executive MBA</fullName>
            </value>
            <value>
                <fullName>Executive MBA (Canberra)</fullName>
            </value>
            <value>
                <fullName>Film and Animation</fullName>
            </value>
            <value>
                <fullName>Games and Interactive Environments</fullName>
            </value>
            <value>
                <fullName>Human Movement and Exercise</fullName>
            </value>
            <value>
                <fullName>Information Technology</fullName>
            </value>
            <value>
                <fullName>Interior Architecture</fullName>
            </value>
            <value>
                <fullName>International Business</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/classes/LeadScoreConfigPrimaryNSAServiceTest.cls
/**
 * @description Test class for LeadScoreConfigPrimaryNSAService
 * 
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | roy.nino.s.regala              | October 06, 2023      | DEPP-5866              | Created file                 |
      |                                |                       |                        |                              |
 */
@isTest
private class LeadScoreConfigPrimaryNSAServiceTest {
    @isTest
    private static void getLeadScoreConfigTest() {//NOPMD test class is mocked user is not needed

        ImplementationSelector.DAO.setMock(new LeadScoreConfigurationDAOMock());

        List<Lead_Score_Configuration__c> leadScoreConfigList = new List<Lead_Score_Configuration__c>();

        leadScoreConfigList.add(
            new Lead_Score_Configuration__c(
                Name = 'Primary NSA',
                RecordTypeId = LeadScoreConfigurationDAO.RECTYPE_ID_CATEGORY,
                Domestic_International__c = 'International',
                Study_Level__c = 'Postgraduate',
                Description__c = '',
                Score_Allocation__c = null,
                Time_Limit_Months__c = null,
                Max_Score__c = 5
            )
        );

        LeadScoreConfigurationDAO.newInstance()
            .insertRecords(leadScoreConfigList, true, AccessLevel.USER_MODE);

        List<Lead_Score_Configuration__c> leadScoreConfigChildList = TestDataFactory.createInlAndPostGradSubCategory(
            leadScoreConfigList[0].Id,
            new List<String>{
                'Is unsure',
                'Is not blank',
                'Is blank'
            },
            new List<Integer>{ 5, 5, 0}
        );

        LeadScoreConfigurationDAO.newInstance()
            .insertRecords(leadScoreConfigChildList, true, AccessLevel.USER_MODE);
        LeadScoreConfigPrimaryNSA leadScoreConfigData;

        for (
            Lead_Score_Configuration__c leadScoreConfig : LeadScoreConfigurationDAO.newInstance()
                .getLeadScoreConfigByRecordTypeIds(
                    AccessLevel.USER_MODE,
                    LeadScoreConfigurationDAO.RECTYPE_IDS_CATEGORY_AND_SUB_CATEGORY
                )
        ) {
            leadScoreConfigData = new LeadScoreConfigPrimaryNSA();
            LeadScoreConfigPrimaryNSAService.getLeadScoreConfig(
                leadScoreConfig,
                leadScoreConfigData
            );

            System.assert(leadScoreConfigData != null, 'leadScoreConfigData is not popualted');
        }
    }


    @isTest
    private static void calculateLeadScoreTest() {//NOPMD test class is mocked user is not needed

        ImplementationSelector.DAO.setMock(new MarketingSegmentationsDAOMock());
        ImplementationSelector.DAO.setMock(new ContactsDAOMock());
        ImplementationSelector.DAO.setMock(new LeadsDAOMock());

        List<Contact> contactList = TestDataFactory.createTestContactRecords(1);
        ContactsDAO.newInstance().insertRecords(contactList, true, AccessLevel.USER_MODE);

        List<Lead> leadList = TestDataFactory.createTestLeadRecords(1);
        LeadsDAO.newInstance().insertRecords(leadList, true, AccessLevel.USER_MODE);

        List<Marketing_Segmentation__c> marSegList = new List<Marketing_Segmentation__c>();
        marSegList.add(
            new Marketing_Segmentation__c(
                Contact__c = contactList[0].Id,
                My_Primary_NSA__c = 'I am not sure'
            )
        );
        marSegList.add(
            new Marketing_Segmentation__c(
                Contact__c = contactList[0].Id,
                My_Primary_NSA__c = ''
            )
        );
        marSegList.add(
            new Marketing_Segmentation__c(
                Contact__c = contactList[0].Id,
                My_Primary_NSA__c = null
            )
        );
        marSegList.add(
            new Marketing_Segmentation__c(
                Lead__c = leadList[0].Id,
                My_Primary_NSA__c = 'Is not blank'
            )
        );
        marSegList.add(
            new Marketing_Segmentation__c(
                Lead__c = leadList[0].Id,
                My_Primary_NSA__c = ''
            )
        );
        marSegList.add(
            new Marketing_Segmentation__c(
                Lead__c = leadList[0].Id,
                My_Primary_NSA__c = null
            )
        );

        MarketingSegmentationsDAO.newInstance()
        .insertRecords(marSegList, true, AccessLevel.USER_MODE);

        Map<Id, Marketing_Segmentation__c> marSegMap = new Map<Id, Marketing_Segmentation__c>(
            marSegList
        );
        
        LeadScoreConfigPrimaryNSA leadScoreConfig = new LeadScoreConfigPrimaryNSA();
        leadScoreConfig.setIsBlank(10);
        leadScoreConfig.setIsNotBlank(10);
        leadScoreConfig.setIsUnsure(10);

        System.assert(
            !LeadScoreConfigPrimaryNSAService.calculateLeadScore(
                    marSegMap,
                    leadScoreConfig
                )
                .isEmpty(),
            'score not calculated'
        );
    }
}