src/core-crm/objects/Contact/fields/Marketing_Segmentation__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Segmentation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Preferences</label>
    <referenceTo>Marketing_Segmentation__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/main/objects/Contact/fields/QUT_Learner_Email__c.field-meta.xml
<CustomField>
    <fullName>QUT_Learner_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>QUT Learner Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

src/core-crm/main/objects/Contact/fields/QUT_Staff_Email__c.field-meta.xml
<CustomField>
    <fullName>QUT_Staff_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>QUT Staff Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

src/core-crm/objects/Contact/fields/Work_Email__c.field-meta.xml
<CustomField>
    <fullName>Work_Email__c</fullName>
    <description>The work email for this person</description>
    <externalId>true</externalId>
    <inlineHelpText>This field captures the work email of the contact.</inlineHelpText>
    <label>Work Email</label>
    <type>Email</type>
</CustomField>

src/core-crm/objects/Marketing_Segmentation__c/Marketing_Segmentation__c.object-meta.xml
<CustomObject>
    <label>Marketing Segmentation</label>
    <nameField>
        <displayFormat>MS - {000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Segmentations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Marketing_Segmentation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Marketing Segmentations</relationshipLabel>
    <relationshipName>Marketing_Segmentations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Marketing_Segmentation__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Marketing Segmentations</relationshipLabel>
    <relationshipName>Marketing_Segmentations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/classes/MarketingSegmentationsDAOMock.cls
/* @description  Mock DAO Class for Marketing Segmentation 
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary                                     |
      |--------------------------------|-----------------------|------------------------|----------------------------------------------------|
      | julie.jane.alegre              | Sept 14, 2023         | DEPP-6679              | Created file                                       |
      | johanna.a.gibas                | Jan 04, 2024          | ApexCRUDViolationFix   | Added method for getExistingMarketingSegmentations |
 */
@isTest
public inherited sharing  class MarketingSegmentationsDAOMock extends DmlBaseMock implements IMarketingSegmentationsDAO{
    public Map<Id, Marketing_Segmentation__c> marketingSegmentationMap;

    public Schema.SObjectType getSObjectType() {
        return Marketing_Segmentation__c.SObjectType;
    }

    public MarketingSegmentationsDAOMock() {
        super(new Map<Id, Marketing_Segmentation__c>(), Schema.Marketing_Segmentation__c.SObjectType);
        this.marketingSegmentationMap = (Map<Id, Marketing_Segmentation__c>) super.records;
    }

    public List<Marketing_Segmentation__c> getMarketingSegmentationByContactIds(
        Set<Id> contactIds,
        AccessLevel accessLevel
    ) {
        List<Marketing_Segmentation__c> marketingSegmentationList = new List<Marketing_Segmentation__c>();

        for (Marketing_Segmentation__c record : marketingSegmentationMap.values()) {
            if (contactIds.contains(record.Contact__c)) {
                marketingSegmentationList.add(record);
            }
        }

        return marketingSegmentationList;
    }

    public List<Marketing_Segmentation__c> getMarketingSegmentationByLeadIds(
        Set<Id> leadIds,
        AccessLevel accessLevel
    ) {
        List<Marketing_Segmentation__c> marketingSegmentationList = new List<Marketing_Segmentation__c>();

        for (Marketing_Segmentation__c record : marketingSegmentationMap.values()) {
            if (leadIds.contains(record.Lead__c)) {
                marketingSegmentationList.add(record);
            }
        }

        return marketingSegmentationList;
    }

    public List<Marketing_Segmentation__c> getMarketingSegmentationByContactOrLead(
        Set<Id> contactIdSet, 
        Set<Id> leadIdSet,
        AccessLevel accessLevel
    ) {
        List<Marketing_Segmentation__c> marketingSegmentationList = new List<Marketing_Segmentation__c>();

        for (Marketing_Segmentation__c record : marketingSegmentationMap.values()) {
            if (leadIdSet.contains(record.Lead__c)) {
                marketingSegmentationList.add(record);
            }
            if (contactIdSet.contains(record.Contact__c)) {
                marketingSegmentationList.add(record);
            }
        }

        return marketingSegmentationList;
    }  

    public List<Marketing_Segmentation__c> getLinkedMarketingSegByContactOrLeadIds(
        Set<Id> recordIds,
        AccessLevel accessLevel
    ) {
        List<Marketing_Segmentation__c> msList = new List<Marketing_Segmentation__c>();
        for(Marketing_Segmentation__c ms : marketingSegmentationMap.values()) {
            if(recordIds.contains(ms.Contact__c) || recordIds.contains(ms.Lead__c)) {
                msList.add(ms);
            }
        }
        return msList;
    }

    public Database.QueryLocator queryLocatorGetMarketingSegmentationsByContactOrLeadIds(
        Set<Id> recordIds
    ){
        return null;
    }

    public List<Marketing_Segmentation__c> getExistingMarketingSegmentations(
        Map<String, Contact> emailToContactMap,
        AccessLevel accessLevel
    ) {
        List<Marketing_Segmentation__c> marketingSegmentationsList = new List<Marketing_Segmentation__c>();
        for (Marketing_Segmentation__c record : marketingSegmentationMap.values()) {
            if (emailToContactMap.containsKey(record.Contact__r.Email) || 
                emailToContactMap.containsKey(record.Contact__r.Work_Email__c) || 
                emailToContactMap.containsKey(record.Contact__r.QUT_Staff_Email__c) || 
                emailToContactMap.containsKey(record.Contact__r.QUT_Learner_Email__c)
                ){
                marketingSegmentationsList.add(record);
            }
        }
        return marketingSegmentationsList;
    }

}