src/core-crm/objects/Contact/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>Job Title</description>
    <label>Position</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Contact/fields/Preferred_Given_Name__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Given_Name__c</fullName>
    <description>This field holds the user&apos;s preferred given name.</description>
    <externalId>true</externalId>
    <label>Preferred Given Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/hed__Course_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Represents a connection to a Course Offering.</description>
    <label>Course Connection</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Course Connection ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Enrollment__c/fields/hed__Contact__c.field-meta.xml
<CustomField>
    <fullName>hed__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student or faculty member participating in this Course Offering.</description>
    <inlineHelpText>The student or faculty member participating in this Course Offering.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Connections</relationshipLabel>
    <relationshipName>Student_Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/hed__Course_Offering__c.field-meta.xml
<CustomField>
    <fullName>hed__Course_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Course Offering the student or faculty member is involved with.</description>
    <inlineHelpText>The Course Offering the student or faculty member is involved with.</inlineHelpText>
    <label>Course Offering ID</label>
    <referenceTo>hed__Course_Offering__c</referenceTo>
    <relationshipLabel>Course Connection</relationshipLabel>
    <relationshipName>Course_Enrollment</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <description>A Student Course Connection</description>
    <label>Student</label>
</RecordType>

src/core-crm/objects/hed__Course_Offering__c/hed__Course_Offering__c.object-meta.xml
<CustomObject>
    <description>Joins Courses and Terms to contain information related to a single occurrence of a Course.</description>
    <label>Course Offering</label>
    <nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/Questionnaire_Response_Summary__c/Questionnaire_Response_Summary__c.object-meta.xml
<CustomObject>
    <description>This will summarise the response of leaner to a questionnaire per offering.</description>
    <label>Questionnaire Response Summary</label>
    <nameField>
        <displayFormat>QRS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questionnaire Response Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Questionnaire_Response_Summary__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the contact answering the questionnaire.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Questionnaire Response Summaries</relationshipLabel>
    <relationshipName>Questionnaire_Response_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Questionnaire_Response_Summary__c/fields/Course_Offering__c.field-meta.xml
<CustomField>
    <fullName>Course_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the course offering the responses answered from.</description>
    <label>Course Offering</label>
    <referenceTo>hed__Course_Offering__c</referenceTo>
    <relationshipLabel>Questionnaire Response Summaries</relationshipLabel>
    <relationshipName>Questionnaire_Response_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Questionnaire_Response_Summary__c/fields/Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Registration_Status__c</fullName>
    <description>This will determine the eligibility status of the Registration.</description>
    <label>Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/classes/RegisteredLearnersCtrl.cls
/**
 * @description Controller Class for registeredLearnerRelatedList LWC
 * @see ../lwc/registeredLearnerRelatedList
 * 
 * @author Accenture
 * 
 * @history
 *    | Developer                 | Date                  | JIRA                 | Change Summary               |
      |---------------------------|-----------------------|----------------------|------------------------------|
      | adrian.c.habasa           | March 24, 2022        | DEPP-1481            | Created file                 |          | 
      |                           |                       |                      |                              | 
 */
public with sharing class RegisteredLearnersCtrl {
    private static Map <String,Schema.RecordTypeInfo> courseConnectionRecordTypes = hed__Course_Enrollment__c.sObjectType.getDescribe().getRecordTypeInfosByName();
    private static Id studentRTId = courseConnectionRecordTypes.get('Student').getRecordTypeId();

    @AuraEnabled(cacheable=true)
    public static List<RegisteredLearners> getRegisteredLearners(Id offeringId)
    {
       List<RegisteredLearners> learnerList = new List<RegisteredLearners>();
       List<hed__Course_Enrollment__c > courseConnections = [SELECT Id, hed__Contact__c
                                                            FROM hed__Course_Enrollment__c
                                                            WHERE hed__Course_Offering__c =: offeringId AND RecordTypeId =: studentRTId];

       List<Questionnaire_Response_Summary__c> questionnaireResponseList =[ SELECT Contact__c,Contact__r.Preferred_Given_Name__c, Contact__r.Company_Name__c, Contact__r.Position__c 
                                                                            FROM Questionnaire_Response_Summary__c 
                                                                            WHERE Course_Offering__c =: offeringId AND Registration_Status__c = 'Confirmed'];

        for(hed__Course_Enrollment__c student : courseConnections){
            for(Questionnaire_Response_Summary__c question : questionnaireResponseList)
            {
                if(question.Contact__c == student.hed__Contact__c){
                    RegisteredLearners rl = new RegisteredLearners();
                    rl.prefferedName = question.Contact__r.Preferred_Given_Name__c;
                    rl.companyName = question.Contact__r.Company_Name__c;
                    rl.positionName =  question.Contact__r.Position__c;
                    learnerList.add(rl);
                }
            }
        }

        return learnerList;
   }
   public class RegisteredLearners{
		@AuraEnabled
		public String prefferedName;
		@AuraEnabled
		public String companyName;
        @AuraEnabled
		public String positionName;
	}

}