src/core-crm/objects/Contact/fields/QUT_Student__c.field-meta.xml
<CustomField>
    <fullName>QUT_Student__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>A Student is a person registered to study a learning activity or academic offering the institution provides.</inlineHelpText>
    <label>QUT Student</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/hed__Address__c/hed__Address__c.object-meta.xml
<CustomObject>
    <description>Stores address information. To support multiple and seasonal addresses.</description>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Address__c/fields/hed__Address_Type__c.field-meta.xml
<CustomField>
    <fullName>hed__Address_Type__c</fullName>
    <description>Select what kind of address this is, for example, Home, Work, Vacation Residence, or Other.</description>
    <inlineHelpText>Select what kind of address this is, for example, Home, Work, Vacation Residence, or Other.</inlineHelpText>
    <label>Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Address__c/fields/hed__MailingCity__c.field-meta.xml
<CustomField>
    <fullName>hed__MailingCity__c</fullName>
    <label>Mailing City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Address__c/fields/hed__MailingCountry__c.field-meta.xml
<CustomField>
    <fullName>hed__MailingCountry__c</fullName>
    <label>Mailing Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Address__c/fields/hed__MailingPostalCode__c.field-meta.xml
<CustomField>
    <fullName>hed__MailingPostalCode__c</fullName>
    <label>Mailing Zip/Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Address__c/fields/hed__MailingState__c.field-meta.xml
<CustomField>
    <fullName>hed__MailingState__c</fullName>
    <label>Mailing State/Province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Address__c/fields/hed__MailingStreet2__c.field-meta.xml
<CustomField>
    <fullName>hed__MailingStreet2__c</fullName>
    <description>Additional street address detail for this Address, such as Suite or Apt.</description>
    <inlineHelpText>Additional street address detail for this Address, such as Suite or Apt.</inlineHelpText>
    <label>Mailing Street2</label>
    <type>TextArea</type>
</CustomField>

src/core-crm/objects/hed__Address__c/fields/hed__MailingStreet__c.field-meta.xml
<CustomField>
    <fullName>hed__MailingStreet__c</fullName>
    <label>Mailing Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Address__c/fields/hed__Parent_Contact__c.field-meta.xml
<CustomField>
    <fullName>hed__Parent_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The primary Contact for this Address.</description>
    <inlineHelpText>The primary Contact for this Address.</inlineHelpText>
    <label>Parent Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Address__c/fields/Meshblock_Id__c.field-meta.xml
<CustomField>
    <fullName>Meshblock_Id__c</fullName>
    <description>Meshblock identifier published by Australian Bureau of Statistics</description>
    <label>Meshblock ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Address__c/fields/Remoteness_Class__c.field-meta.xml
<CustomField>
    <fullName>Remoteness_Class__c</fullName>
    <description>The remoteness classification given to the meshblock</description>
    <label>Remoteness Class</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Address__c/fields/Socio_Economic_Percentile__c.field-meta.xml
<CustomField>
    <fullName>Socio_Economic_Percentile__c</fullName>
    <description>The socio-economic percentile published by Australian Bureau of Statistics for SA1</description>
    <label>Socio-Economic Percentile</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/hed__Address__c/fields/Statistical_Area_1_Id__c.field-meta.xml
<CustomField>
    <fullName>Statistical_Area_1_Id__c</fullName>
    <description>Statistical Area 1 identifier published by Australian Bureau of Statistics</description>
    <label>Statistical Area 1 ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Address__c/fields/Validated__c.field-meta.xml
<CustomField>
    <fullName>Validated__c</fullName>
    <description>Confirming that this has been validated from Loqate.</description>
    <label>Validated</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Loqate_Validation</valueSetName>
    </valueSet>
</CustomField>

src/core-crm/main/globalValueSets/Loqate_Validation.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>Valid</fullName>
    </customValue>
    <customValue>
        <fullName>Not Valid</fullName>
    </customValue>
    <description>Confirming that this has been validated from Loqate</description>
    <masterLabel>Loqate Validation</masterLabel>
</GlobalValueSet>

src/core-crm/classes/AddressValidationTest.cls
/**
 * @description Test class for AddressValidation
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | mark.j.mahilum                 | May 29, 2024          | DEPP-8954              | Created file                 |
 */
@isTest
private class AddressValidationTest {

    @testSetup
    static void testSetup() {
        Test.startTest();
        TestDataFactory.generateTestUsers(new List<String>{'QUT_ESB'});
        Test.stopTest();
    }

    @isTest
    static void processValidAddressesTest() {
        System.runAs(TestDataFactory.getESBIntegrationUser()) {
            String mockResponseBody = '{"statisticalArea1":"Test Area","meshBlockId":"12345","socioEconomicPercentile":80,"remotenessClass":"Urban","isValid":true}';
            Test.setMock(HTTPCalloutMock.class, new GenericHttpCalloutMock(200, 'Success', mockResponseBody));
            List<Contact> contactList = TestDataFactory.createTestContactRecords(3, '');          
            for(Contact con: contactList){
                con.RecordTypeId = ContactsDAO.PERSON_RECORDTYPE_ID;
                con.QUT_Student__c = true;
            }         
            ContactsDAO.newInstance().insertRecords(contactList, false, AccessLevel.USER_MODE);
            
            List<hed__Address__c> addresses = new List<hed__Address__c>();
            
            for (Integer i = 0; i < contactList.size(); i++) {
                hed__Address__c add = new hed__Address__c();
                add.hed__Parent_Contact__c = contactList[i].Id;
                add.hed__Address_Type__c = AddressesDAO.OTHER_ADDRESS;
                add.Validated__c = AddressesDAO.NOT_VALID_ADDRESS;
                add.hed__MailingCountry__c = 'Australia';
                add.hed__MailingState__c = 'QLD';
                add.hed__MailingCity__c = 'DALLARNIL';
                add.hed__MailingPostalCode__c = '12345';
                add.hed__MailingStreet__c = '1234 Test St';
                add.hed__MailingStreet2__c = '4321 Tester Street';
                addresses.add(add);
            }

            AddressesDAO.newInstance().insertRecords(addresses, false, AccessLevel.USER_MODE);
            
            Test.startTest();
            AddressValidation processAddressValidation = new AddressValidation(addresses);
            Map<Id, hed__address__c> contactAddressMap = processAddressValidation.validateAddresses();           
            Test.stopTest();

            System.Assert.areEqual(
                contactList.size(), 
                contactAddressMap.size(), 
			   'The contactAddressMap did not return the expected number of contact'
            );

            
            for(hed__Address__c address: contactAddressMap.values()){
                System.Assert.areEqual(AddressesDAO.VALID_ADDRESS, address.Validated__c , 'The address Validated field is not equal to "Valid"');
                System.Assert.areEqual('Test Area', address.Statistical_Area_1_Id__c , 'The address Statistical_Area_1_Id__c field is not the expected value');
                System.Assert.areEqual('12345', address.Meshblock_Id__c , 'The address Meshblock_Id__c field is not the expected value');                
                System.Assert.areEqual(80, address.Socio_Economic_Percentile__c , 'The address Socio_Economic_Percentile__c field is not the expected value');
				System.Assert.areEqual('Urban', address.Remoteness_Class__c , 'The address Remoteness_Class__c field is not the expected value');
            }


        }
    }
    
    @isTest
    static void processNotValidAddressesTest() {
        System.runAs(TestDataFactory.getESBIntegrationUser()) {
            String mockResponseBody = '{"statisticalArea1":"Test Area","meshBlockId":"12345","socioEconomicPercentile":80,"remotenessClass":"Urban","isValid":false}';
            Test.setMock(HTTPCalloutMock.class, new GenericHttpCalloutMock(200, 'Success', mockResponseBody));
            List<Contact> contactList = TestDataFactory.createTestContactRecords(3, '');          
            for(Contact con: contactList){
                con.RecordTypeId = ContactsDAO.PERSON_RECORDTYPE_ID;
                con.QUT_Student__c = true;
            }         
            ContactsDAO.newInstance().insertRecords(contactList, false, AccessLevel.USER_MODE);
            
            List<hed__Address__c> addresses = new List<hed__Address__c>();
            
            for (Integer i = 0; i < contactList.size(); i++) {
                hed__Address__c add = new hed__Address__c();
                add.hed__Parent_Contact__c = contactList[i].Id;
                add.hed__Address_Type__c = AddressesDAO.OTHER_ADDRESS;
                add.Validated__c = AddressesDAO.NOT_VALID_ADDRESS;
                add.hed__MailingCountry__c = 'Australia';
                add.hed__MailingState__c = 'QLD';
                add.hed__MailingCity__c = 'DALLARNIL';
                add.hed__MailingPostalCode__c = '12345';
                add.hed__MailingStreet__c = '1234 Test St';
                add.hed__MailingStreet2__c = '4321 Tester Street';
                addresses.add(add);
            }

            AddressesDAO.newInstance().insertRecords(addresses, false, AccessLevel.USER_MODE);
            
            Test.startTest();
            AddressValidation processAddressValidation = new AddressValidation(addresses);
            Map<Id, hed__address__c> contactAddressMap = processAddressValidation.validateAddresses();           
            Test.stopTest();

            System.Assert.areEqual(
                contactList.size(), 
                contactAddressMap.size(), 
			   'The contactAddressMap did not return the expected number of contact'
            );
            
            for(hed__Address__c address: contactAddressMap.values()){
                System.Assert.areEqual(AddressesDAO.NOT_VALID_ADDRESS, address.Validated__c , 'The address Validated field is not equal to "Not Valid"');
                System.Assert.areEqual(null, address.Statistical_Area_1_Id__c , 'The address Statistical_Area_1_Id__c field is not null');
                System.Assert.areEqual(null, address.Meshblock_Id__c , 'The address Meshblock_Id__c field is not null');                
                System.Assert.areEqual(null, address.Socio_Economic_Percentile__c , 'The address Socio_Economic_Percentile__c field is not null');
				System.Assert.areEqual(null, address.Remoteness_Class__c , 'The address Remoteness_Class__c field is not null');
            }
        }
    }
    
    @isTest
    static void processThrowExceptionAddressesTest() {
        System.runAs(TestDataFactory.getESBIntegrationUser()) {
            String mockResponseBody = '{"statisticalArea1":"Test Area","meshBlockId":"12345","socioEconomicPercentile":80,"remotenessClass":"Urban","isValid":false}';
            Test.setMock(HTTPCalloutMock.class, new GenericHttpCalloutMock(201, 'Fail', mockResponseBody));
            List<Contact> contactList = TestDataFactory.createTestContactRecords(3, '');          
            for(Contact con: contactList){
                con.RecordTypeId = ContactsDAO.PERSON_RECORDTYPE_ID;
                con.QUT_Student__c = true;
            }         
            ContactsDAO.newInstance().insertRecords(contactList, false, AccessLevel.USER_MODE);
            
            List<hed__Address__c> addresses = new List<hed__Address__c>();
            
            for (Integer i = 0; i < contactList.size(); i++) {
                hed__Address__c add = new hed__Address__c();
                add.hed__Parent_Contact__c = contactList[i].Id;
                add.hed__Address_Type__c = AddressesDAO.OTHER_ADDRESS;
                add.Validated__c = AddressesDAO.NOT_VALID_ADDRESS;
                add.hed__MailingCountry__c = 'Australia';
                add.hed__MailingState__c = 'QLD';
                add.hed__MailingCity__c = 'DALLARNIL';
                add.hed__MailingPostalCode__c = '12345';
                add.hed__MailingStreet__c = '1234 Test St';
                add.hed__MailingStreet2__c = '4321 Tester Street';
                addresses.add(add);
            }

            AddressesDAO.newInstance().insertRecords(addresses, false, AccessLevel.USER_MODE);
            
            Test.startTest();
            AddressValidation processAddressValidation = new AddressValidation(addresses);
            Map<Id, hed__address__c> contactAddressMap = processAddressValidation.validateAddresses();           
            Test.stopTest();

            System.Assert.areEqual(
                contactList.size(), 
                contactAddressMap.size(), 
			   'The contactAddressMap did not return the expected number of contact'
            );
			
            List<LogEntry__c> logEntries = LogEntriesDAO.newInstance().getLogEntriesByMessage(
                new Set<String>{'Exception caught in method loqateAddressValidation in Apex class AddressValidation.'},
                AccessLevel.USER_MODE
            );
            
            System.assert(!logEntries.isEmpty(),'there should be log entries');
            
            for(LogEntry__c logEntry: logEntries){
                System.assertEquals(
                    'Exception caught in method loqateAddressValidation in Apex class AddressValidation.',
                    logEntry.Message__c,
                    'Error message should be Exception caught in method loqateAddressValidation in Apex class AddressValidation'
                );                             
            }
                        
            for(hed__Address__c address: contactAddressMap.values()){
                System.Assert.areEqual(AddressesDAO.NOT_VALID_ADDRESS, address.Validated__c , 'The address Validated field is not equal to "Not Valid"');
                System.Assert.areEqual(null, address.Statistical_Area_1_Id__c , 'The address Statistical_Area_1_Id__c field is not null');
                System.Assert.areEqual(null, address.Meshblock_Id__c , 'The address Meshblock_Id__c field is not null');                
                System.Assert.areEqual(null, address.Socio_Economic_Percentile__c , 'The address Socio_Economic_Percentile__c field is not null');
				System.Assert.areEqual(null, address.Remoteness_Class__c , 'The address Remoteness_Class__c field is not null');
            }
        }
    }
}