src/core-crm/objects/Contact/fields/QUT_Student_Username__c.field-meta.xml
<CustomField>
    <fullName>QUT_Student_Username__c</fullName>
    <description>Username allocated to QUT Students for system access</description>
    <externalId>true</externalId>
    <label>QUT Student Username</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Contact/fields/Registered_Email__c.field-meta.xml
<CustomField>
    <fullName>Registered_Email__c</fullName>
    <description>All automated email communications will be sent to this email address.</description>
    <label>Registered Email</label>
    <type>Email</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/hed__Course_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Represents a connection to a Course Offering.</description>
    <label>Course Connection</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Course Connection ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Enrollment__c/fields/hed__Contact__c.field-meta.xml
<CustomField>
    <fullName>hed__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student or faculty member participating in this Course Offering.</description>
    <inlineHelpText>The student or faculty member participating in this Course Offering.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Connections</relationshipLabel>
    <relationshipName>Student_Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/hed__Course_Offering__c.field-meta.xml
<CustomField>
    <fullName>hed__Course_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Course Offering the student or faculty member is involved with.</description>
    <inlineHelpText>The Course Offering the student or faculty member is involved with.</inlineHelpText>
    <label>Course Offering ID</label>
    <referenceTo>hed__Course_Offering__c</referenceTo>
    <relationshipLabel>Course Connection</relationshipLabel>
    <relationshipName>Course_Enrollment</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/hed__Status__c.field-meta.xml
<CustomField>
    <fullName>hed__Status__c</fullName>
    <description>Indicates whether this is a current or former Course Connection.</description>
    <inlineHelpText>Indicates whether this is a current or former Course Connection.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/LMS_Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>LMS_Integration_Status__c</fullName>
    <label>LMS Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not-Ready</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <description>A Student Course Connection</description>
    <label>Student</label>
</RecordType>

src/core-crm/objects/hed__Course_Offering__c/hed__Course_Offering__c.object-meta.xml
<CustomObject>
    <description>Joins Courses and Terms to contain information related to a single occurrence of a Course.</description>
    <label>Course Offering</label>
    <nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>hed__Start_Date__c</fullName>
    <description>The date of the first session for this Course Offering.</description>
    <inlineHelpText>The date of the first session for this Course Offering.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/fields/LMS_Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>LMS_Integration_Status__c</fullName>
    <label>LMS Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/fields/Primary_Delivery_Platform__c.field-meta.xml
<CustomField>
    <fullName>Primary_Delivery_Platform__c</fullName>
    <description>Primary delivery platform of related course</description>
    <formula>TEXT(hed__Course__r.Primary_Delivery_Platform__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Delivery Platform</label>
    <type>Text</type>
</CustomField>

src/core-crm/classes/SendWelcomeEmailBatch.cls
/**
 * @description Batch class to send welcome email to contacts
 * 
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | roy.nino.s.regala              | July 30, 2022         | DEPP-3557              | Created file                 |
      | rhea.b.torres                  | November 25, 2022     | DEPP-4628              | 7-day window logic update    | 
      | kenneth.f.alsay                | December 6, 2023      | DEPP-7339              | Updated query as per AC3     |
 */
public class SendWelcomeEmailBatch implements Database.Batchable<sObject>
{

    /**
    * @description Method to course enrollments
    * @param bc - BatchableContext
    * @return query - filtered query of course enrollment records
    */
    public Database.QueryLocator start(Database.BatchableContext bc)
    {
        /**
         * startdate of offering starts 7 days from today
         * primary delivery platform is QUT Canvas
         * Student Username is available
         * and active enrollment
         * is student
         */
        Date sevenDaysBefore = Date.today() + 7; //NOPMD Used in string below for dynamic query
        String query = 
        'SELECT Id, hed__Contact__c ' + 
        'FROM hed__Course_Enrollment__c ' + 
    	'WHERE hed__Course_Offering__r.hed__Start_Date__c =:sevenDaysBefore ' +
        'AND hed__Course_Offering__r.Primary_Delivery_Platform__c = \'QUT Canvas\' ' + 
        'AND hed__Contact__r.QUT_Student_Username__c != null ' + 
        'AND hed__Contact__r.Registered_Email__c != null ' +
        'AND hed__Status__c  = \'Active\' ' + 
        'AND RecordType.DeveloperName = \'Student\' ' +
        'AND LMS_Integration_Status__c = \'Success\' ';
        return Database.getQueryLocator(query);
    }

    /**
    * @description Method to execute the batch
    * @param bc - BatchableContext
    * @param enrollmentList - List of course enrollments
    */
    public void execute(Database.BatchableContext bc, List<hed__Course_Enrollment__c> enrollmentList)
    {
        Set<Id> contactIds = new Set<Id>();
        try{
            //Loop through all courseconnections to get valid contacts to receive welcome email
            for(hed__Course_Enrollment__c courseEnrollnment: enrollmentList){
                contactIds.add(courseEnrollnment.hed__Contact__c);
            }
            if(!contactIds.isEmpty()){
                ContactUserNameCreatedHelper.sendEmailUsernameCreated(contactIds);
            }
        }catch(Exception e){
            Logger.error('Exception caught in method execute in class SendWelcomeEmailBatch.')
                .setExceptionDetails(e);
        } finally {
            if(Logger.getBufferSize() > 0) {
                Logger.saveLog();
            }
        }
    }  
    public void finish(Database.BatchableContext bc) {}//NOPMD
}