src/core-crm/objects/Contact/fields/QUT_Student__c.field-meta.xml
<CustomField>
    <fullName>QUT_Student__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>A Student is a person registered to study a learning activity or academic offering the institution provides.</inlineHelpText>
    <label>QUT Student</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/hed__Address__c/hed__Address__c.object-meta.xml
<CustomObject>
    <description>Stores address information. To support multiple and seasonal addresses.</description>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Address__c/fields/hed__Address_Type__c.field-meta.xml
<CustomField>
    <fullName>hed__Address_Type__c</fullName>
    <description>Select what kind of address this is, for example, Home, Work, Vacation Residence, or Other.</description>
    <inlineHelpText>Select what kind of address this is, for example, Home, Work, Vacation Residence, or Other.</inlineHelpText>
    <label>Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Address__c/fields/hed__Parent_Contact__c.field-meta.xml
<CustomField>
    <fullName>hed__Parent_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The primary Contact for this Address.</description>
    <inlineHelpText>The primary Contact for this Address.</inlineHelpText>
    <label>Parent Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/classes/AddressesDAO.cls
/**
 * @description DAO Class for hed__Address__c Object. Contains soql and constants related to the hed__Address__c object.
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | alexander.cadalin              | sep 22, 2023          | DEPP-6652              | Created file                 |
      | eccarius.munoz                 | May 29, 2024          | DEPP-8955              | added getQueryLocatorByIds   |
 */
public inherited sharing class AddressesDAO extends DmlBase implements IAddressesDAO {

    private static final String ADDRESS_TYPE_OTHER = 'Other';

    public Schema.SObjectType getSObjectType() {
        return hed__Address__c.SObjectType;
    }

    public static IAddressesDAO newInstance() {
        return (IAddressesDAO) ImplementationSelector.DAO.newInstance(hed__Address__c.sObjectType);
    }

    public List<hed__Address__c> getAddressesByContactIdsSet(
        Set<Id> contactIdsSet,
        AccessLevel accessLevel
    ) {
        if (contactIdsSet.isEmpty()) {
            return new List<hed__Address__c>();
        }

        return Database.query(
            'SELECT Id, hed__Parent_Contact__c, hed__Address_Type__c ' +
                'FROM hed__Address__c ' +
                'WHERE hed__Parent_Contact__c IN: contactIdsSet',
            accessLevel
        );
    }

    @SuppressWarnings('PMD.UnusedLocalVariable')
    public Database.QueryLocator getQueryLocatorByIds(Set<Id> addressIdSet){

        String personRecordTypeId = ContactsDAO.PERSON_RECORDTYPE_ID; 

        String query =
            'SELECT Id, hed__Parent_Contact__c ' + 
              'FROM hed__Address__c ' + 
             'WHERE Id IN: addressIdSet ' + 
               'AND hed__Parent_Contact__r.QUT_Student__c = true  ' + 
               'AND hed__Parent_Contact__r.RecordTypeId =: personRecordTypeId';

        return Database.getQueryLocator(query);
    }

}