src/core-crm/objects/Marketing_Course_Application__c/Marketing_Course_Application__c.object-meta.xml
<CustomObject>
    <label>Marketing Course Application</label>
    <nameField>
        <displayFormat>MCA - {000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Course Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Marketing_Course_Application__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Marketing Course Applications</relationshipLabel>
    <relationshipName>Marketing_Course_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Marketing_Course_Application__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Marketing Course Applications</relationshipLabel>
    <relationshipName>Marketing_Course_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/classes/MarketingCourseApplicationsDAO.cls
/**
 * @description DAO Class for Marketing Course Application Object. 
 * Contains soql and constants related to the Marketing Course Application object.
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | alexander.cadalin              | Jan 02, 2024          | n/a                    | Created file
 */
public inherited sharing class MarketingCourseApplicationsDAO extends DmlBase implements IMarketingCourseApplicationsDAO{

    public Schema.SObjectType getSObjectType()
    {
        return Marketing_Course_Application__c.SObjectType;
    } 

    public static IMarketingCourseApplicationsDAO newInstance()
    {
        return (IMarketingCourseApplicationsDAO) ImplementationSelector.DAO.newInstance(Marketing_Course_Application__c.SObjectType);
    }

    public List<Marketing_Course_Application__c> getMrktngCourseAppsByLeadIds(
        Set<Id> leadIds,
        AccessLevel accessLevel
    ) {
        if(!leadIds.isEmpty() && accessLevel != null) {
            return Database.query(
                'SELECT Id, Lead__c, Contact__c FROM Marketing_Course_Application__c WHERE Lead__c IN :leadIds',
                accessLevel
            );
        } else { return new List<Marketing_Course_Application__c>(); }
    }
}