src/core-crm/objects/Offering_Evaluation_Setting__mdt/Offering_Evaluation_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Custom metadata for setting of fields available per Evaluation Type of an Offering.</description>
    <label>Offering Evaluation Setting</label>
    <pluralLabel>Offering Evaluation Settings</pluralLabel>
</CustomObject>

src/core-crm/objects/Offering_Evaluation_Setting__mdt/fields/Fields__c.field-meta.xml
<CustomField>
    <fullName>Fields__c</fullName>
    <description>Fields to display for a particular Evaluation Type.</description>
    <inlineHelpText>Enter API name of fields, with each value separated by a new line.</inlineHelpText>
    <label>Fields</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/core-crm/classes/EvaluationSectionCtrl.cls
/**
 * @description Controller class for evaluationSection LWC
 *
 * @see ../lwc/evaluationSection
 * 
 * @author Accenture
 *      
 * @history
 *    | Developer                 | Date                  | JIRA                 | Change Summary                                         |
      |---------------------------|-----------------------|----------------------|--------------------------------------------------------|
      | angelika.j.s.galang       | March 22, 2022        | DEPP-1502            | Created file                                           |
      |                           |                       |                      |                                                        | 
*/
public with sharing class EvaluationSectionCtrl {

    /**
    * @description Method for getting the metadata of Evaluation fields
    * @return list of Offering Evalution Setting records
    */
    @AuraEnabled(cacheable=true)
    public static List<Offering_Evaluation_Setting__mdt> getEvaluationFields(){
        return [
            SELECT MasterLabel, Fields__c
            FROM Offering_Evaluation_Setting__mdt
        ];
    }
}