src/core-crm/objects/Opportunity_Outcome__c/Opportunity_Outcome__c.object-meta.xml
<CustomObject>
    <description>Opportunity Outcome captures the outcome of a given Opportunity. Each Opportunity can have many Opportunity Outcomes.</description>
    <label>Opportunity Outcome</label>
    <nameField>
        <displayFormat>OO-{00000}</displayFormat>
        <label>Opportunity Outcome Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Outcomes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/core-crm/objects/Opportunity_Outcome__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>A unique, business formatted code to identify a Project being managed under an Opportunity Outcome.</description>
    <label>Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Opportunity_Outcome__c/fields/Decommissioned_Date__c.field-meta.xml
<CustomField>
    <fullName>Decommissioned_Date__c</fullName>
    <description>The date the project is/was decommissioned.</description>
    <label>Decommissioned Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Opportunity_Outcome__c/fields/Decommissioned_Reason__c.field-meta.xml
<CustomField>
    <fullName>Decommissioned_Reason__c</fullName>
    <description>The business entered reason why the project was decommissioned.</description>
    <inlineHelpText>The business entered reason why the project was decommissioned.</inlineHelpText>
    <label>Decommissioned Reason</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

src/core-crm/objects/Opportunity_Outcome__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Project end date.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Opportunity_Outcome__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to associated Opportunity.</description>
    <inlineHelpText>Lookup to associated Opportunity.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Outcomes</relationshipLabel>
    <relationshipName>Opportunity_Outcomes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Opportunity_Outcome__c/fields/Stage_Name__c.field-meta.xml
<CustomField>
    <fullName>Stage_Name__c</fullName>
    <description>The business process stages that Opportunity Outcomes progress through.</description>
    <inlineHelpText>The business process stages that Opportunity Outcomes progress through.</inlineHelpText>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Deregistered</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Opportunity_Outcome__c/recordTypes/IPU_Project.recordType-meta.xml
<RecordType>
    <fullName>IPU_Project</fullName>
    <active>true</active>
    <description>Create and manage IPU Project.</description>
    <label>IPU Project</label>
</RecordType>

src/core-crm/objects/Opportunity_Outcome__c/recordTypes/Research_Commercialisation_Project.recordType-meta.xml
<RecordType>
    <fullName>Research_Commercialisation_Project</fullName>
    <active>true</active>
    <description>Create and manage Licence, Options and Assignment project.</description>
    <label>Research Commercialisation Project</label>
</RecordType>

src/core-crm/objects/Opportunity_Outcome__c/recordTypes/Research_Partnership_Project.recordType-meta.xml
<RecordType>
    <fullName>Research_Partnership_Project</fullName>
    <active>true</active>
    <description>Create and manage Research Partnership Project.</description>
    <label>Research Partnership Project</label>
</RecordType>

src/core-crm/objects/Opportunity_Outcome__c/recordTypes/Startup.recordType-meta.xml
<RecordType>
    <fullName>Startup</fullName>
    <active>true</active>
    <description>Create and manage a Startup Company.</description>
    <label>Startup</label>
</RecordType>

src/core-crm/classes/OpportunityOutcomesDAO.cls
/**
 * @description DAO Class for Opportunity Outcome Object. Contains soql and constants related to the Opportunity Outcome object.
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | alexander.cadalin              | May 17, 2023          | DEPP-5594              | Created file
      | carl.alvin.cabiles             | May 25, 2023          | DEPP-5410              | added methods
      | carl.alvin.cabiles             | June 13, 2023         | DEPP-5409              | added methods
 */
public inherited sharing class OpportunityOutcomesDAO extends DmlBase implements IOpportunityOutcomesDAO {
    public static final Id RESEARCHPARTNERSHIPPROJECT_RECTYPE_ID = Schema.SObjectType.Opportunity_Outcome__c.getRecordTypeInfosByDeveloperName()
        .get('Research_Partnership_Project')
        .getRecordTypeId();
    public static final Id IPUPROJECT_RECTYPE_ID = Schema.SObjectType.Opportunity_Outcome__c.getRecordTypeInfosByDeveloperName()
        .get('IPU_Project')
        .getRecordTypeId();
    public static final Id RESEARCHCOMMERCIALISATIONPROJECT_RECTYPE_ID = Schema.SObjectType.Opportunity_Outcome__c.getRecordTypeInfosByDeveloperName()
        .get('Research_Commercialisation_Project')
        .getRecordTypeId();
    public static final Id STARTUP_RECTYPE_ID = Schema.SObjectType.Opportunity_Outcome__c.getRecordTypeInfosByDeveloperName()
        .get('Startup')
        .getRecordTypeId();
    public static final String COMPLETED_STAGE = 'Completed';
    public static final String NEW_STAGE = 'New';
    public static final String DECOMMISSIONED_STAGE = 'Decommissioned';
    public Schema.SObjectType getSObjectType() {
        return Opportunity_Outcome__c.SObjectType;
    }

    public static IOpportunityOutcomesDAO newInstance() {
        return (IOpportunityOutcomesDAO) ImplementationSelector.DAO.newInstance(
            Opportunity_Outcome__c.SObjectType
        );
    }

    public static List<Opportunity_Outcome__c> getRecordsSortByCodeAsc() {
        return [
            SELECT Id, Code__c
            FROM Opportunity_Outcome__c
            WITH SYSTEM_MODE
            ORDER BY Code__c ASC
        ];
    }

    public static List<Opportunity_Outcome__c> getRecordsWithLikeCodeSortAsc(String codeIsLike) {
        return [
            SELECT Id, Code__c
            FROM Opportunity_Outcome__c
            WHERE Code__c LIKE :codeIsLike
            WITH SYSTEM_MODE
            ORDER BY Code__c ASC
        ];
    }

    public List<Opportunity_Outcome__c> getRecordsWithEqualEndDate(Date endDate) {
        return [
            SELECT Id, Stage_Name__c
            FROM Opportunity_Outcome__c
            WHERE End_Date__c = :endDate
            WITH USER_MODE
        ];
    }

    public List<Opportunity_Outcome__c> getRecordsWithNotEqualEndDate(Date endDate) {
        return [
            SELECT Id, Stage_Name__c
            FROM Opportunity_Outcome__c
            WHERE End_Date__c != :endDate
            WITH USER_MODE
        ];
    }

    public List<Opportunity_Outcome__c> getRecordsWithStartDate(Date startDate) {
        return [
            SELECT Id, Stage_Name__c
            FROM Opportunity_Outcome__c
            WHERE End_Date__c = :startDate
            WITH USER_MODE
        ];
    }

    public List<Opportunity_Outcome__c> getRecordsWithOpportunity(List<Id> opportunityList) {
        return [
            SELECT Id, Opportunity__c
            FROM Opportunity_Outcome__c
            WHERE Opportunity__c IN :opportunityList
            WITH USER_MODE
        ];
    }

    public List<Opportunity_Outcome__c> getRecordsWithPastDateAsDecommissionedDate() {
        return [
            SELECT Id, Stage_Name__c, End_Date__c, Decommissioned_Date__c, Decommissioned_Reason__c
            FROM Opportunity_Outcome__c
            WHERE Decommissioned_Date__c <= :System.today()
            WITH USER_MODE
        ];
    }

    public List<Opportunity_Outcome__c> getRecordsWithFutureDateAsDecommissionedDate() {
        return [
            SELECT Id, Stage_Name__c, End_Date__c, Decommissioned_Date__c, Decommissioned_Reason__c
            FROM Opportunity_Outcome__c
            WHERE Decommissioned_Date__c > :System.today()
            WITH USER_MODE
        ];
    }
}