src/core-crm/objects/Opportunity_Outcome__c/Opportunity_Outcome__c.object-meta.xml
<CustomObject>
    <description>Opportunity Outcome captures the outcome of a given Opportunity. Each Opportunity can have many Opportunity Outcomes.</description>
    <label>Opportunity Outcome</label>
    <nameField>
        <displayFormat>OO-{00000}</displayFormat>
        <label>Opportunity Outcome Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Outcomes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/core-crm/objects/Opportunity_Outcome_Code_Auto_Number__c/Opportunity_Outcome_Code_Auto_Number__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom setting contains the auto-numbers used for the Opportunity Outcome object&apos;s Code field.</description>
    <label>Opportunity Outcome Code Auto Number</label>
</CustomObject>

src/core-crm/objects/Opportunity_Outcome_Code_Auto_Number__c/fields/Start_Up__c.field-meta.xml
<CustomField>
    <fullName>Start_Up__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Auto-number used for Start-Up Opportunity Outcome records.</description>
    <label>Start-Up</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Risk__c/Risk__c.object-meta.xml
<CustomObject>
    <description>The Risk data object stores information about risks. Typically the risks captured are related to business opportunities and/or projects.</description>
    <label>Risk</label>
    <nameField>
        <displayFormat>Risk-{0000000}</displayFormat>
        <label>Risk Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Risk__c/fields/Opportunity_Outcome__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Outcome__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Opportunity Outcome object.</description>
    <label>Opportunity Outcome</label>
    <referenceTo>Opportunity_Outcome__c</referenceTo>
    <relationshipLabel>Risks</relationshipLabel>
    <relationshipName>Risks</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Risk__c/fields/Risk_Type__c.field-meta.xml
<CustomField>
    <fullName>Risk_Type__c</fullName>
    <description>The type of risk.</description>
    <label>Risk Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Health and Safety</fullName>
            </value>
            <value>
                <fullName>DFAT Travel Risks</fullName>
            </value>
            <value>
                <fullName>Logistical</fullName>
            </value>
            <value>
                <fullName>Political</fullName>
            </value>
            <value>
                <fullName>Economic</fullName>
            </value>
            <value>
                <fullName>Technological</fullName>
            </value>
            <value>
                <fullName>Environment</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/classes/RiskTriggerHandlerTest.cls
/**
 * @description Test Class for RiskTriggerHandler
 *
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
 *    |--------------------------------|-----------------------|------------------------|------------------------------|
 *    | ryan.j.a.dela.cruz             | August 08, 2023       | DEPP-6335              | Created file
 */
@isTest
private class RiskTriggerHandlerTest {
    @testSetup
    static void setup() {
        TestDataFactory.generateTestUsers(new List<String>{ 'QUT_Operations_Manager' });
        Opportunity_Outcome_Code_Auto_Number__c oppOutcomeCodeAutoNum = OpportunityOutcomeCodeAutoNumbersDAO.newInstance()
            .getOrganizationalDefaults();
        oppOutcomeCodeAutoNum.Start_Up__c = 1;
        OpportunityOutcomeCodeAutoNumbersDAO.newInstance()
            .insertRecords(
                new List<Opportunity_Outcome_Code_Auto_Number__c>{ oppOutcomeCodeAutoNum },
                false,
                AccessLevel.USER_MODE
            );
    }

    @isTest
    private static void testPlatformEventInsertAndUpdate() {
        System.runAs(testDataFactory.getOperationsManager()) {
            List<Opportunity_Outcome__c> oppOutcomes = TestDataFactory.createTestOpportunityOutcomeRecords(
                1,
                'Sample Company',
                OpportunityOutcomesDAO.STARTUP_RECTYPE_ID
            );

            OpportunityOutcomesDAO.newInstance()
                .insertRecords(oppOutcomes, false, AccessLevel.USER_MODE);

            Test.startTest();
            List<Risk__c> newRisks = TestDataFactory.createTestRiskRecords(
                1,
                oppOutcomes[0].Id,
                'Health and Safety	'
            );

            System.assert(
                RisksDAO.newInstance()
                        .insertRecords(newRisks, false, AccessLevel.USER_MODE)[0]
                    .isSuccess(),
                'Risk record should be created'
            );

            newRisks[0].Risk_Type__c = 'Logistical';

            System.assert(
                RisksDAO.newInstance()
                        .updateRecords(newRisks, false, AccessLevel.USER_MODE)[0]
                    .isSuccess(),
                'Risk record should be updated'
            );
            Test.stopTest();
        }
    }
}