src/core-crm/main/objects/Contact/fields/hed__Citizenship_Status__c.field-meta.xml
<CustomField>
    <fullName>hed__Citizenship_Status__c</fullName>
    <description>The Contact&apos;s citizenship status.</description>
    <inlineHelpText>The Contact&apos;s citizenship status.</inlineHelpText>
    <label>Citizenship Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>U.S. Citizen or U.S. National</fullName>
            </value>
            <value>
                <fullName>U.S. Dual Citizen</fullName>
            </value>
            <value>
                <fullName>U.S. Permanent Resident</fullName>
            </value>
            <value>
                <fullName>U.S. Refugee or Asylee</fullName>
            </value>
            <value>
                <fullName>Temporary Resident</fullName>
            </value>
            <value>
                <fullName>Other (Non-U.S.)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Contact/fields/Marketing_Segmentation__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Segmentation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Preferences</label>
    <referenceTo>Marketing_Segmentation__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Lead/fields/Marketing_Segmentation__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Segmentation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Segmentation</label>
    <referenceTo>Marketing_Segmentation__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Marketing_Segmentation__c/Marketing_Segmentation__c.object-meta.xml
<CustomObject>
    <label>Marketing Segmentation</label>
    <nameField>
        <displayFormat>MS - {000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Segmentations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Marketing_Segmentation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Marketing Segmentations</relationshipLabel>
    <relationshipName>Marketing_Segmentations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Marketing_Segmentation__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Marketing Segmentations</relationshipLabel>
    <relationshipName>Marketing_Segmentations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Marketing_Segmentation__c/fields/My_Country_Of_Citizenship__c.field-meta.xml
<CustomField>
    <fullName>My_Country_Of_Citizenship__c</fullName>
    <description>Profile Type = Myself

Indicates the country the international student is a citizen of.</description>
    <label>My Country Of Citizenship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

src/core-crm/objects/Marketing_Segmentation__c/fields/My_Country_Of_Residency__c.field-meta.xml
<CustomField>
    <fullName>My_Country_Of_Residency__c</fullName>
    <description>Profile Type = Myself

Indicates the country an international student is living in.</description>
    <label>My Country Of Residency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

src/core-crm/objects/Marketing_Segmentation__c/fields/My_Primary_NSA__c.field-meta.xml
<CustomField>
    <fullName>My_Primary_NSA__c</fullName>
    <description>Profile Type = Myself

The primary NSA or NSAs (which are related to the primary BSA selected by the marketing person) that they have expressed interest in receiving marketing material about.

A person can select 1 or more NSAs where applicable.</description>
    <label>My Primary NSA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>I am not sure</fullName>
            </value>
            <value>
                <fullName>Accounting and Financial Planning</fullName>
            </value>
            <value>
                <fullName>Acting, Drama and Technical Production</fullName>
            </value>
            <value>
                <fullName>Advertising, Marketing and PR</fullName>
            </value>
            <value>
                <fullName>Architecture</fullName>
            </value>
            <value>
                <fullName>Behavioural Economics</fullName>
            </value>
            <value>
                <fullName>Biological Science</fullName>
            </value>
            <value>
                <fullName>Business Process Management</fullName>
            </value>
            <value>
                <fullName>Chemistry</fullName>
            </value>
            <value>
                <fullName>Communication</fullName>
            </value>
            <value>
                <fullName>Construction Management</fullName>
            </value>
            <value>
                <fullName>Creative Writing</fullName>
            </value>
            <value>
                <fullName>Dance</fullName>
            </value>
            <value>
                <fullName>Data Science and Analytics</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Digital Capability</fullName>
            </value>
            <value>
                <fullName>Digital MBA</fullName>
            </value>
            <value>
                <fullName>Early Childhood</fullName>
            </value>
            <value>
                <fullName>Earth Science</fullName>
            </value>
            <value>
                <fullName>Economics and Finance</fullName>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>Environmental Science</fullName>
            </value>
            <value>
                <fullName>Executive MBA</fullName>
            </value>
            <value>
                <fullName>Executive MBA (Canberra)</fullName>
            </value>
            <value>
                <fullName>Film and Animation</fullName>
            </value>
            <value>
                <fullName>Games and Interactive Environments</fullName>
            </value>
            <value>
                <fullName>Human Movement and Exercise</fullName>
            </value>
            <value>
                <fullName>Information Technology</fullName>
            </value>
            <value>
                <fullName>Interior Architecture</fullName>
            </value>
            <value>
                <fullName>International Business</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Åland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas (the)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia (Plurinational State of)</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

src/core-crm/classes/MarketingSegmentationLeadScoreHelper.cls
/**
  * @description helper class to compute Lead Score for MarketingSegmentation
  * @see ..MarketingSegmentationTriggerHelper
  *
  * @author Accenture 
  *
  * @history
  *
  *    | Developer                      | Date                  | JIRA                   | Change Summary                                 |
  *    |--------------------------------|-----------------------|------------------------|------------------------------------------------|
  *    | eccarius.munoz                 | September 25, 2023    | DEPP-5866              | Created file to handle lead score calculation  |
  *    |                                |                       |                        | for marketing segmentation                     |
  */
  public with sharing class MarketingSegmentationLeadScoreHelper{    

    private static Map<Id,Marketing_Segmentation__c> domesticUnderGradMap = new Map<Id,Marketing_Segmentation__c>();
    private static Map<Id,Marketing_Segmentation__c> domesticPostGradMap = new Map<Id,Marketing_Segmentation__c>();
    private static Map<Id,Marketing_Segmentation__c> domesticUndeterminedMap = new Map<Id,Marketing_Segmentation__c>();
    private static Map<Id,Marketing_Segmentation__c> internationalUnderGradMap = new Map<Id,Marketing_Segmentation__c>();
    private static Map<Id,Marketing_Segmentation__c> internationalPostGradMap = new Map<Id,Marketing_Segmentation__c>();
    private static Map<Id,Marketing_Segmentation__c> internationalUndeterminedMap = new Map<Id,Marketing_Segmentation__c>();
    private static Map<Id,Marketing_Segmentation__c> undeterminedUndeterminedMap = new Map<Id,Marketing_Segmentation__c>();

    /**
     * Filter records to be processed
     */
    public static void processLeadScoreCalculation(List<Marketing_Segmentation__c> newItems, Map<Id, Marketing_Segmentation__c> oldItems){

        Map<Id,Marketing_Segmentation__c> marketingSegmentationMap = new Map<Id,Marketing_Segmentation__c>();
        Set<Id> contactIdSet = new Set<Id>();
        for(Marketing_Segmentation__c mktgSeg : newItems){
            if(
                checkIfForUpdate(oldItems, mktgSeg) || 
                checkIfForUpdatedToUndetermined(oldItems, mktgSeg) || 
                checkUndeterminedUndetermined(mktgSeg)
            ){
                if(mktgSeg.Contact__c != null){
                    contactIdSet.add(mktgSeg.Contact__c);
                    marketingSegmentationMap.put(mktgSeg.Contact__c, mktgSeg);
                }else if(mktgSeg.Lead__c != null){
                    marketingSegmentationMap.put(mktgSeg.Lead__c, mktgSeg);
                }
            }
        }

        callSyncOrAsyncCalculation(contactIdSet, marketingSegmentationMap);
    }    

    /**
     * Determines wether to run async or sync
     */
    private static void callSyncOrAsyncCalculation(Set<Id> contactIdSet, Map<Id,Marketing_Segmentation__c> marketingSegmentationMap){
        if(!marketingSegmentationMap.isEmpty()){
            if(System.isQueueable()){
                executeCalculation(contactIdSet, marketingSegmentationMap);
            }else{
                QueueableCall executeQueueable = new QueueableCall(contactIdSet, marketingSegmentationMap);
                System.enqueueJob(executeQueueable);   
            }
        }
    }

    /**
     * Maps Undergrad studylevel records to domesticUnderGradMap and internationalUnderGradMap
     */
    private static void mapUnderGradStudyLevel(Marketing_Segmentation__c markSeg, Map<Id,Contact> contactMap) {
        Boolean isUnderGrad = markSeg.My_Primary_Study_Level__c != null && markSeg.My_Primary_Study_Level__c == MarketingSegmentationsDAO.PRIMARY_STUDY_LEVEL_UNDERGRAD;
        Boolean isDomesticLead = isUnderGrad && markSeg.Lead__c != null && (markSeg.My_Citizenship_Status__c == MarketingSegmentationsDAO.CITIZENSHIP_STATUS_DOMESTIC_AU || markSeg.My_Citizenship_Status__c == MarketingSegmentationsDAO.CITIZENSHIP_STATUS_DOMESTIC_NZ);
        Boolean isInternationalLead = isUnderGrad && markSeg.Lead__c != null && markSeg.My_Citizenship_Status__c == MarketingSegmentationsDAO.CITIZENSHIP_STATUS_INTERNATIONAL;
        Boolean isDomesticContact = isUnderGrad && markSeg.Contact__c != null && contactMap.get(markSeg.Contact__c).hed__Citizenship_Status__c == ContactsDAO.CITIZENSHIP_STATUS_DOMESTIC;
        Boolean isInternationalContact = isUnderGrad && markSeg.Contact__c != null && contactMap.get(markSeg.Contact__c).hed__Citizenship_Status__c == ContactsDAO.CITIZENSHIP_STATUS_INTERNATIONAL;

        if(isDomesticContact){
            domesticUnderGradMap.put(markSeg.Contact__c, markSeg);
        }
        else if(isDomesticLead){
            domesticUnderGradMap.put(markSeg.Lead__c, markSeg);
        }
        else if(isInternationalContact){
            internationalUnderGradMap.put(markSeg.Contact__c, markSeg);
        }
        else if(isInternationalLead){
            internationalUnderGradMap.put(markSeg.Lead__c, markSeg);
        }
    }

    /**
     * Maps Postgrad studylevel records to domesticPostGradMap and internationalPostGradMap
     */
    private static void mapPostGradStudyLevel(Marketing_Segmentation__c markSeg, Map<Id,Contact> contactMap) {
        Boolean isPostGrad = markSeg.My_Primary_Study_Level__c == MarketingSegmentationsDAO.PRIMARY_STUDY_LEVEL_POSTGRAD;
        Boolean isDomesticLead = isPostGrad && markSeg.Lead__c != null &&  (markSeg.My_Citizenship_Status__c == MarketingSegmentationsDAO.CITIZENSHIP_STATUS_DOMESTIC_AU || markSeg.My_Citizenship_Status__c == MarketingSegmentationsDAO.CITIZENSHIP_STATUS_DOMESTIC_NZ);
        Boolean isInternationalLead = isPostGrad && markSeg.Lead__c != null && markSeg.My_Citizenship_Status__c == MarketingSegmentationsDAO.CITIZENSHIP_STATUS_INTERNATIONAL;
        Boolean isDomesticContact = isPostGrad && markSeg.Contact__c != null && contactMap.get(markSeg.Contact__c).hed__Citizenship_Status__c == ContactsDAO.CITIZENSHIP_STATUS_DOMESTIC;
        Boolean isInternationalContact = isPostGrad && markSeg.Contact__c != null && contactMap.get(markSeg.Contact__c).hed__Citizenship_Status__c == ContactsDAO.CITIZENSHIP_STATUS_INTERNATIONAL;

        if(isDomesticContact){
            domesticPostGradMap.put(markSeg.Contact__c, markSeg);
        }
        else if(isDomesticLead){
            domesticPostGradMap.put(markSeg.Lead__c, markSeg);
        }
        else if(isInternationalContact){
            internationalPostGradMap.put(markSeg.Contact__c, markSeg);
        }
        else if(isInternationalLead){
            internationalPostGradMap.put(markSeg.Lead__c, markSeg);
        }
    }

    /**
     * Maps Undergrad studylevel records to domesticUndeterminedMap and internationalUndeterminedMap
     */
    private static void mapUndeterminedStudyLevel(Marketing_Segmentation__c markSeg, Map<Id,Contact> contactMap) {
        Boolean isUndetermined = String.isBlank(markSeg.My_Primary_Study_Level__c);
        Boolean isDomesticLead = isUndetermined && markSeg.Lead__c != null && String.isNotBlank(markSeg.My_Citizenship_Status__c) && (markSeg.My_Citizenship_Status__c == MarketingSegmentationsDAO.CITIZENSHIP_STATUS_DOMESTIC_AU || markSeg.My_Citizenship_Status__c == MarketingSegmentationsDAO.CITIZENSHIP_STATUS_DOMESTIC_NZ);
        Boolean isInternationalLead = isUndetermined && markSeg.Lead__c != null && String.isNotBlank(markSeg.My_Citizenship_Status__c) && markSeg.My_Citizenship_Status__c == MarketingSegmentationsDAO.CITIZENSHIP_STATUS_INTERNATIONAL;
        Boolean isDomesticContact = isUndetermined && contactMap.containsKey(markSeg.Contact__c) && contactMap.get(markSeg.Contact__c).hed__Citizenship_Status__c == ContactsDAO.CITIZENSHIP_STATUS_DOMESTIC;
        Boolean isInternationalContact = isUndetermined && contactMap.containsKey(markSeg.Contact__c) && contactMap.get(markSeg.Contact__c).hed__Citizenship_Status__c == ContactsDAO.CITIZENSHIP_STATUS_INTERNATIONAL;
        Boolean isConCitizenshipUD = validateUndeterminedUDContact(isUndetermined, contactMap, markSeg);
        Boolean isLeadCitizenshipUD = validateUndeterminedUDLead(isUndetermined, markSeg);

        if(isDomesticContact){
            domesticUndeterminedMap.put(markSeg.Contact__c, markSeg);
        }
        else if(isDomesticLead){
            domesticUndeterminedMap.put(markSeg.Lead__c, markSeg);
        }
        else if(isInternationalContact){
            internationalUndeterminedMap.put(markSeg.Contact__c, markSeg);
        }
        else if(isInternationalLead){
            internationalUndeterminedMap.put(markSeg.Lead__c, markSeg);
        }
        else if(isConCitizenshipUD){
            undeterminedUndeterminedMap.put(markSeg.Contact__c, markSeg);
        }
        else if(isLeadCitizenshipUD){
            undeterminedUndeterminedMap.put(markSeg.Lead__c, markSeg);
        }
    }   

    /**
     * Queueable class to execute calculation of lead score for marketing segmentation records.
     */
    private class QueueableCall implements Queueable {
        private Set<Id> contactIdSet;
        private Map<Id,Marketing_Segmentation__c> marketingSegmentationMap;
        
        public QueueableCall(Set<Id> contactIdSet, Map<Id,Marketing_Segmentation__c> marketingSegmentationMap) {
            this.contactIdSet = contactIdSet;
            this.marketingSegmentationMap = marketingSegmentationMap;
        }

        public void execute(QueueableContext context) {
            executeCalculation(contactIdSet, marketingSegmentationMap);
        }
    }

    /**
     * Process that includes:
     * 1. Retrieval of lead score config
     * 2. Calculation of lead score per study level and citizenship status
     * 3. inserting/updating of lead score detail
     */
    public static void executeCalculation(Set<Id> contactIdSet, Map<Id,Marketing_Segmentation__c> marketingSegmentationMap){
        LeadScoreCalculatorService.ObjectMap objMap = setObjectMap(contactIdSet, marketingSegmentationMap);
        if(!marketingSegmentationMap.isEmpty()){
            LeadScoreCalculatorService.calculateLeadScore(objMap, marketingSegmentationMap.keySet(), Marketing_Segmentation__c.getSObjectType());
        }
    }

    /**
     * Sets the object map to be used in queueable job
     */
    public static LeadScoreCalculatorService.ObjectMap setObjectMap(Set<Id> contactIdSet, Map<Id,Marketing_Segmentation__c> marketingSegmentationMap){
         //Sort records per study level and citizenship status
         Map<Id,Contact> contactMap = new Map<Id,Contact>(ContactsDAO.newInstance().getPersonContactsBySetIds(contactIdSet, AccessLevel.SYSTEM_MODE));
         for(Marketing_Segmentation__c mktgSeg : marketingSegmentationMap.values()){
             mapUnderGradStudyLevel(mktgSeg, contactMap);
             mapPostGradStudyLevel(mktgSeg, contactMap);
             mapUndeterminedStudyLevel(mktgSeg, contactMap);
         }

        LeadScoreCalculatorService.ObjectMap objectMap = new LeadScoreCalculatorService.ObjectMap();
        objectMap.domesticUnderGradMap = domesticUnderGradMap;
        objectMap.domesticPostGradMap = domesticPostGradMap;
        objectMap.domesticUndeterminedMap = domesticUndeterminedMap;
        objectMap.internationalUnderGradMap = internationalUnderGradMap;
        objectMap.internationalPostGradMap = internationalPostGradMap;
        objectMap.internationalUndeterminedMap = internationalUndeterminedMap;
        objectMap.undeterminedUndeterminedMap = undeterminedUndeterminedMap;
        return objectMap;
    }

    /*** Methods for checking if for lead score calculation : Start ***/
    private static Boolean checkIfForUpdate(Map<Id,Marketing_Segmentation__c> oldMarkSegMap, Marketing_Segmentation__c markSeg){
        return 
            oldMarkSegMap != null && 
            markSeg.My_Primary_Study_Level__c != null &&
            (           
                (String.isNotBlank(markSeg.My_Citizenship_Status__c) && markSeg.My_Citizenship_Status__c != oldMarkSegMap.get(markSeg.Id).My_Citizenship_Status__c) ||
                (markSeg.My_Country_Of_Residency__c != oldMarkSegMap.get(markSeg.Id).My_Country_Of_Residency__c) ||
                (markSeg.My_Country_Of_Citizenship__c != oldMarkSegMap.get(markSeg.Id).My_Country_Of_Citizenship__c) ||
                (String.isNotBlank(markSeg.My_Funding_Source__c) && markSeg.My_Funding_Source__c != oldMarkSegMap.get(markSeg.Id).My_Funding_Source__c) ||
                (markSeg.My_Primary_BSA__c != oldMarkSegMap.get(markSeg.Id).My_Primary_BSA__c) ||
                (markSeg.My_Primary_NSA__c != oldMarkSegMap.get(markSeg.Id).My_Primary_NSA__c) ||
                (markSeg.My_Double_Degree__c != oldMarkSegMap.get(markSeg.Id).My_Double_Degree__c) ||
                (markSeg.My_Interested_English_Pathways__c != oldMarkSegMap.get(markSeg.Id).My_Interested_English_Pathways__c) ||
                (markSeg.My_Expected_Admission_Year__c != oldMarkSegMap.get(markSeg.Id).My_Expected_Admission_Year__c) ||
                (markSeg.My_Primary_Study_Level__c != oldMarkSegMap.get(markSeg.Id).My_Primary_Study_Level__c)
            );
    }

    private static Boolean checkIfForUpdatedToUndetermined(Map<Id,Marketing_Segmentation__c> oldMarkSegMap, Marketing_Segmentation__c markSeg){
        return 
            oldMarkSegMap != null &&             
            (                
                (String.isNotBlank(markSeg.My_Citizenship_Status__c) && markSeg.My_Citizenship_Status__c != oldMarkSegMap.get(markSeg.Id).My_Citizenship_Status__c) ||
                (markSeg.My_Country_Of_Residency__c != oldMarkSegMap.get(markSeg.Id).My_Country_Of_Residency__c) ||
                (markSeg.My_Country_Of_Citizenship__c != oldMarkSegMap.get(markSeg.Id).My_Country_Of_Citizenship__c) ||
                (String.isNotBlank(markSeg.My_Funding_Source__c) && markSeg.My_Funding_Source__c != oldMarkSegMap.get(markSeg.Id).My_Funding_Source__c) ||
                (markSeg.My_Primary_BSA__c != oldMarkSegMap.get(markSeg.Id).My_Primary_BSA__c) ||
                (markSeg.My_Primary_NSA__c != oldMarkSegMap.get(markSeg.Id).My_Primary_NSA__c) ||                
                (markSeg.My_Double_Degree__c != oldMarkSegMap.get(markSeg.Id).My_Double_Degree__c) ||
                (markSeg.My_Interested_English_Pathways__c != oldMarkSegMap.get(markSeg.Id).My_Interested_English_Pathways__c) ||
                (markSeg.My_Expected_Admission_Year__c != oldMarkSegMap.get(markSeg.Id).My_Expected_Admission_Year__c) ||
                (markSeg.My_Primary_Study_Level__c != oldMarkSegMap.get(markSeg.Id).My_Primary_Study_Level__c && markSeg.My_Primary_Study_Level__c == null)
            );
    }

    private static Boolean checkUndeterminedUndetermined(Marketing_Segmentation__c markSeg){
        return 
            String.isBlank(markSeg.My_Primary_Study_Level__c) && 
            String.isBlank(markSeg.My_Citizenship_Status__c);
    }

    private static Boolean validateUndeterminedUDContact(Boolean isUndetermined, Map<Id,Contact> contactMap, Marketing_Segmentation__c markSeg){
        return contactMap.containsKey(markSeg.Contact__c) && String.isBlank(contactMap.get(markSeg.Contact__c).hed__Citizenship_Status__c);
    }

    private static Boolean validateUndeterminedUDLead(Boolean isUndetermined, Marketing_Segmentation__c markSeg){
        return isUndetermined && String.isBlank(markSeg.My_Citizenship_Status__c);
    }

    /*** Methods for checking if for lead score calculation : End ***/

}