src/core-crm/main/objects/Contact/fields/QUT_Student_ID__c.field-meta.xml
<CustomField>
    <fullName>QUT_Student_ID__c</fullName>
    <externalId>true</externalId>
    <label>QUT Student ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Contact_Alternate_Id__c/Contact_Alternate_Id__c.object-meta.xml
<CustomObject>
    <description>Contains all alternative identifiers for a given contact</description>
    <label>Contact Alternate Id</label>
    <nameField>
        <displayFormat>CAI-{000000}</displayFormat>
        <label>Contact Alternate Id Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Alternate Ids</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/core-crm/objects/Contact_Alternate_Id__c/fields/Alternate_Id_Status__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Id_Status__c</fullName>
    <description>Indicating Contact Alternate Id’s status</description>
    <label>Alternate Id Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Superseded</fullName>
            </value>
            <value>
                <fullName>Duplicate Sanction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Contact_Alternate_Id__c/fields/Alternate_Id_Type__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Id_Type__c</fullName>
    <description>The Type Identity held IN the Contact_Alternate_ID__c</description>
    <label>Alternate Id Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>QUT Employee ID</fullName>
            </value>
            <value>
                <fullName>QUT Student ID</fullName>
            </value>
            <value>
                <fullName>StudyLink Applicant ID</fullName>
            </value>
            <value>
                <fullName>QTAC Applicant ID</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Contact_Alternate_Id__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Contact that the Alternate ID belongs to</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Alternate Ids</relationshipLabel>
    <relationshipName>Contact_Alternate_Ids</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Contact_Alternate_Id__c/fields/Contact_Alternate_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Alternate_Id__c</fullName>
    <description>The Contact Alternate ID Value</description>
    <label>Contact Alternate Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Contact_Alternate_Id__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>The Date System Received this Alternate ID</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Contact_Alternate_Id__c/fields/Succeeding_Id__c.field-meta.xml
<CustomField>
    <fullName>Succeeding_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The ID that caused current Id to supersede eg The new student Id</description>
    <label>Succeeding Id</label>
    <referenceTo>Contact_Alternate_Id__c</referenceTo>
    <relationshipLabel>Contact Alternate Ids</relationshipLabel>
    <relationshipName>Contact_Alternate_Ids</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Contact_Matching_Service_Configuration__mdt/Contact_Matching_Service_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>Contact Matching Service Configuration</label>
    <pluralLabel>Contact Matching Service Configurations</pluralLabel>
</CustomObject>

src/core-crm/objects/Contact_Matching_Service_Configuration__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To indicate the batch job is currently enabled</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Contact_Matching_Service_Configuration__mdt/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <description>Indicate batch size per job</description>
    <label>Size</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Student_Sanction__c/Student_Sanction__c.object-meta.xml
<CustomObject>
    <description>Contains Sanction data applied to student or student program</description>
    <label>Student Sanction</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student Sanction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Sanctions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/core-crm/objects/Student_Sanction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student the Sanction is issued to</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Sanctions</relationshipLabel>
    <relationshipName>Student_Sanctions</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Student_Sanction__c/fields/QUT_Student_ID__c.field-meta.xml
<CustomField>
    <fullName>QUT_Student_ID__c</fullName>
    <description>Unique student Id assigned by student administration system.</description>
    <label>QUT Student ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

src/core-crm/classes/DuplicateSanctionManagerTest.cls
/**
 * @description Test class for DuplicateSanctionManager
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | roy.nino.s.regala              | April 30, 2024        | DEPP-7984              | Created file                 |
 */
@isTest
private class DuplicateSanctionManagerTest {

    static {
        ImplementationSelector.DAO.setMock(new ConMatchingServiceConfigurationsDAOMock());
        String developerName = ConMatchingServiceConfigurationsDAO.STUDENT_SANCTION_BATCH;
        Contact_Matching_Service_Configuration__mdt customMetaData = (Contact_Matching_Service_Configuration__mdt) JSON.deserialize(
            '{"IsActive__c":"true","Size__c":"200","DeveloperName":"' + developerName + '"}',
            Contact_Matching_Service_Configuration__mdt.class
        );

        ConMatchingServiceConfigurationsDAO.newInstance()
            .insertRecords(
                new List<Contact_Matching_Service_Configuration__mdt>{ customMetaData },
                true,
                AccessLevel.SYSTEM_MODE
            );
    }

    @testSetup
    static void testSetup() {
        Test.startTest();
        TestDataFactoryUser.generateUserQUTESB();
        Test.stopTest();
        List<Contact_Alternate_Id__c> conAltIdList = new List<Contact_Alternate_Id__c>();
        List<Contact> contactList = TestDataFactory.createTestContactRecords(100);
        ContactsDAO.newInstance().insertRecords(contactList,true,AccessLevel.SYSTEM_MODE);
        for(Contact con: contactList){
            conAltIdList.add(TestDataFactory.createTestConAltIdRecordByContactAndType(
                con.Id,
                'QUT Student ID',
                String.valueOf(con.Id).subString(0,10))
            );
        }

        ContactAlternateIdsDAO.newInstance().insertRecords(conAltIdList,true,AccessLevel.SYSTEM_MODE);
    }

    @isTest
    static void processMissingQUTStudentIdTest() {
        System.runAs(TestDataFactoryUser.selectUserQUTESB) {
            Test.startTest();
            List<Student_Sanction__c> studentSanctionList = TestDataFactory.createStudentSanctionRecords(100);
            StudentSanctionsDAO.newInstance().insertRecords(studentSanctionList,true,AccessLevel.USER_MODE);
            Test.stopTest();

            List<LogEntry__c> logEntries = LogEntriesDAO.newInstance().getLogEntriesByRelatedRecordId(
                new Map<Id,Student_Sanction__c>(studentSanctionList).keySet(),
                AccessLevel.USER_MODE
            );

            System.assert(!logEntries.isEmpty(),'there should be log entries');

            for(LogEntry__c logEntry: logEntries){
                System.assertEquals(
                    'Missing QUT student Id',
                    logEntry.Message__c,
                    'Error message should be missing qut student id'
                );                             
            }
        }
    }

    @isTest
    static void processSanctionStudentNotFoundTest() {
        System.runAs(TestDataFactoryUser.selectUserQUTESB) {
            Test.startTest();
            List<Student_Sanction__c> studentSanctionList = TestDataFactory.createStudentSanctionRecords(100);
            Integer count = 0;
            for(Contact con: ContactsDAO.newInstance().getPersonContactsWithLimit(100)){
                studentSanctionList[count].QUT_Student_ID__c = String.valueOf(con.Id).subString(0,10);
                count ++;
            }
            StudentSanctionsDAO.newInstance().insertRecords(studentSanctionList,true,AccessLevel.USER_MODE);
            Test.stopTest();

            List<LogEntry__c> logEntries = LogEntriesDAO.newInstance().getLogEntriesByRelatedRecordId(
                new Map<Id,Student_Sanction__c>(studentSanctionList).keySet(),
                AccessLevel.USER_MODE
            );

            System.assert(!logEntries.isEmpty(),'there should be log entries');

            for(LogEntry__c logEntry: logEntries ){
                System.assertEquals(
                    'Sanction Student Not Found',
                    logEntry.Message__c,
                    'Error message should be sanction student not found'
                );                             
            }
        }
    }

    @isTest
    static void processDuplicateSanctionSuccessTest() {
        System.runAs(TestDataFactoryUser.selectUserQUTESB) {
            Test.startTest();
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
            List<Student_Sanction__c> studentSanctionList = TestDataFactory.createStudentSanctionRecords(100);
            Set<String> systemKeyIds = new Set<String>();
            Integer count = 0;
            Map<Id,Contact_Alternate_ID__c> newConAltIds = new Map<Id,Contact_Alternate_ID__c>();
            List<Contact_Alternate_ID__c> conAlIdToUpdate = new List<Contact_Alternate_ID__c>();

            for(Contact con: ContactsDAO.newInstance().getPersonContactsWithLimit(100)){
                studentSanctionList[count].QUT_Student_ID__c = String.valueOf(con.Id).subString(0,9);
                systemKeyIds.add(String.valueOf(con.Id).subString(0,10)); 
                newConAltIds.put(con.Id,new Contact_Alternate_ID__c(
                    Contact__c = con.Id,
                    Alternate_Id_Type__c = 'QUT Student ID',
                    Alternate_Id_Status__c = 'Active',
                    Start_Date__c = System.Today(),
                    Contact_Alternate_Id__c = String.valueOf(con.Id).subString(0,9)
                ));
                count ++;
            }
            
            ContactAlternateIdsDAO.newInstance().insertRecords(newConAltIds.values(),true,AccessLevel.USER_MODE);

            for(Contact_Alternate_ID__c conAlId: ContactAlternateIdsDAO.newInstance()
                                                .getContactAlternateIdsBySystemKeyIdSet(
                                                    systemKeyIds,
                                                    AccessLevel.USER_MODE
                                                )){
                conAlIdToUpdate.add(new Contact_Alternate_ID__c(
                    Id = conAlId.Id,
                    Alternate_Id_Status__c = 'Superseded',
                    Succeeding_Id__c = newConAltIds.get(conAlId.Contact__c).Id
                ));
            }

            ContactAlternateIdsDAO.newInstance().updateRecords(conAlIdToUpdate,true,AccessLevel.USER_MODE);
            StudentSanctionsDAO.newInstance().insertRecords(studentSanctionList,true,AccessLevel.USER_MODE);
            Test.stopTest(); 

            System.assert(!ContactAlternateIdsDAO.newInstance()
                            .getContactAlternateIdsBySystemKeyIdSet(
                                systemKeyIds,
                                AccessLevel.USER_MODE
                            ).isEmpty(),
                            'The superseded contact alternate ids should be active and be retrieved'
                        );
        }
    }

    @isTest
    static void processDuplicateSanctionSupersededTest() {
        System.runAs(TestDataFactoryUser.selectUserQUTESB) {
            Test.startTest();
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
            Set<Id> contactIds = new Set<Id>();
            List<Student_Sanction__c> studentSanctionList = TestDataFactory.createStudentSanctionRecords(100);
            Set<String> systemKeyIds = new Set<String>();
            Integer count = 0;
            Map<Id,Contact_Alternate_ID__c> newConAltIds = new Map<Id,Contact_Alternate_ID__c>();
            List<Contact_Alternate_ID__c> conAlIdToUpdate = new List<Contact_Alternate_ID__c>();

            for(Contact con: ContactsDAO.newInstance().getPersonContactsWithLimit(100)){
                systemKeyIds.add(String.valueOf(con.Id).subString(0,10)); 
                newConAltIds.put(con.Id,new Contact_Alternate_ID__c(
                    Contact__c = con.Id,
                    Alternate_Id_Type__c = 'QUT Student ID',
                    Alternate_Id_Status__c = 'Active',
                    Start_Date__c = System.Today(),
                    Contact_Alternate_Id__c = String.valueOf(con.Id).subString(0,9)
                ));
                count ++;
            }
            
            ContactAlternateIdsDAO.newInstance().insertRecords(newConAltIds.values(),true,AccessLevel.USER_MODE);

            count = 0;
            for(Contact_Alternate_ID__c conAlId: ContactAlternateIdsDAO.newInstance()
                                                .getContactAlternateIdsBySystemKeyIdSet(
                                                    systemKeyIds,
                                                    AccessLevel.USER_MODE
                                                )){
                studentSanctionList[count].QUT_Student_ID__c = String.valueOf(conAlId.Contact__c).subString(0,10);
                conAlIdToUpdate.add(new Contact_Alternate_ID__c(
                    Id = conAlId.Id,
                    Alternate_Id_Status__c = 'Superseded',
                    Succeeding_Id__c = newConAltIds.get(conAlId.Contact__c).Id
                ));
                contactIds.add(conAlId.Contact__c);
                count ++;
            }

            

            ContactAlternateIdsDAO.newInstance().updateRecords(conAlIdToUpdate,true,AccessLevel.USER_MODE);
            StudentSanctionsDAO.newInstance().insertRecords(studentSanctionList,true,AccessLevel.USER_MODE);
            Test.stopTest(); 

            System.assert(!ContactAlternateIdsDAO.newInstance()
                            .getContactAlternateIdsByContactIdSetAndStatus(
                                contactIds,
                                new Set<String>{'Duplicate Sanction'},
                                AccessLevel.USER_MODE
                            ).isEmpty(),
                            'The superseded contact alternate ids should be sanctioned and be retrieved'
                        );
        }
    }
}