src/core-crm/objects/Lead_Score_Configuration__c/Lead_Score_Configuration__c.object-meta.xml
<CustomObject>
    <label>Lead Score Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Score Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Lead_Score_Configuration__c/fields/Max_Score__c.field-meta.xml
<CustomField>
    <fullName>Max_Score__c</fullName>
    <description>The max score a category is allowed to accumulate</description>
    <label>Max Score</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Lead_Score_Configuration__c/fields/Parent_Category__c.field-meta.xml
<CustomField>
    <fullName>Parent_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Parent Category the sub category belongs to. This would be null for category record types</description>
    <inlineHelpText>The Category the scoring for this Sub Category will be added to</inlineHelpText>
    <label>Parent Category</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Lead_Score_Configuration__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Category</value>
        </filterItems>
        <filterItems>
            <field>Lead_Score_Configuration__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Configuration</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Lead_Score_Configuration__c</referenceTo>
    <relationshipLabel>Lead Score Configurations</relationshipLabel>
    <relationshipName>Lead_Score_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Lead_Score_Configuration__c/recordTypes/Category.recordType-meta.xml
<RecordType>
    <fullName>Category</fullName>
    <active>true</active>
    <label>Category</label>
</RecordType>

src/core-crm/objects/Lead_Score_Configuration__c/recordTypes/Configuration.recordType-meta.xml
<RecordType>
    <fullName>Configuration</fullName>
    <active>true</active>
    <label>Configuration</label>
</RecordType>

src/core-crm/classes/Lead_Score_Config_Max_Score_UpdateTest.cls
/**
 * @description Test Class for Update Product Code Flow
 *
 * @see ../flows/Update Max Score for Parent Lead Scoring Configuration

 *
 * @author Accenture
 *
 * @history
 *    | Developer                 | Date                  | JIRA         | Change Summary                              |
      |---------------------------|-----------------------|--------------|---------------------------------------------|
      | julie.jane.alegre         | August 29, 2023       | DEPP-6315    | Created file                                |
      |                           |                       |              |                                             |
      |                           |                       |              |                                             |
*/
@isTest
private class Lead_Score_Config_Max_Score_UpdateTest {

    private static final Id LEAD_SCORE_CONFIGURATION_REC_TYPE_CATEGORY = Schema.SObjectType.Lead_Score_Configuration__c.getRecordTypeInfosByName().get('Category').getRecordTypeId();
    private static final Id LEAD_SCORE_CONFIGURATION_REC_TYPE_CONFIGURATION = Schema.SObjectType.Lead_Score_Configuration__c.getRecordTypeInfosByName().get('Configuration').getRecordTypeId();
    
    @testSetup
    static void testSetup() {
        TestDataFactory.generateTestUsers(new List<String>{ 'QUT_System_Administrator' });
    }
    @isTest
    static void updateMaxScoreOnParentConfigurationTest() {
        System.runAs(TestDataFactory.getSystemAdminUser()){
            Test.startTest();
                Decimal totalMaxScore = 0;
                //Create Parent Record
                List<Lead_Score_Configuration__c> parentRecord = TestDataFactory.createLeadScoreConfigurationRecords(
                                                    null,
                                                    LEAD_SCORE_CONFIGURATION_REC_TYPE_CONFIGURATION,
                                                    1);
                insert parentRecord;
                //Create Child Record
                List<Lead_Score_Configuration__c> childRecord = TestDataFactory.createLeadScoreConfigurationRecords(
                                                    parentRecord[0].Id,
                                                    LEAD_SCORE_CONFIGURATION_REC_TYPE_CATEGORY,
                                                    100);
                insert childRecord;
                List<Lead_Score_Configuration__c> updatedParentRecord = [Select Id, Max_Score__c, RecordTypeId FROM Lead_Score_Configuration__c WHERE RecordTypeId =: LEAD_SCORE_CONFIGURATION_REC_TYPE_CONFIGURATION LIMIT 1];
                List<Lead_Score_Configuration__c> listOfChildRecords = [Select Id, Max_Score__c, RecordTypeId FROM Lead_Score_Configuration__c WHERE Parent_Category__c =: updatedParentRecord[0].Id LIMIT 100];
                for(Lead_Score_Configuration__c children: listOfChildRecords){
                    totalMaxScore += children.Max_Score__c;
                }
                Test.stopTest();
                
                System.assertEquals(totalMaxScore, updatedParentRecord[0].Max_Score__c, 'No data retrieved!');
        }
    }
}