src/core-crm/objects/Lead_Score_Configuration__c/Lead_Score_Configuration__c.object-meta.xml
<CustomObject>
    <label>Lead Score Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Score Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Lead_Score_Configuration__c/fields/Domestic_International__c.field-meta.xml
<CustomField>
    <fullName>Domestic_International__c</fullName>
    <description>Whether the configuration is related to Domestic or International scoring scheme</description>
    <label>Domestic or International</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Lead_Score_Configuration__c/fields/Max_Score__c.field-meta.xml
<CustomField>
    <fullName>Max_Score__c</fullName>
    <description>The max score a category is allowed to accumulate</description>
    <label>Max Score</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Lead_Score_Configuration__c/fields/Parent_Category__c.field-meta.xml
<CustomField>
    <fullName>Parent_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Parent Category the sub category belongs to. This would be null for category record types</description>
    <inlineHelpText>The Category the scoring for this Sub Category will be added to</inlineHelpText>
    <label>Parent Category</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Lead_Score_Configuration__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Category</value>
        </filterItems>
        <filterItems>
            <field>Lead_Score_Configuration__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Configuration</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Lead_Score_Configuration__c</referenceTo>
    <relationshipLabel>Lead Score Configurations</relationshipLabel>
    <relationshipName>Lead_Score_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Lead_Score_Configuration__c/fields/Score_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Score_Allocation__c</fullName>
    <description>Score that should be allocated for each instance of the interaction</description>
    <label>Score Allocation</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Lead_Score_Configuration__c/fields/Study_Level__c.field-meta.xml
<CustomField>
    <fullName>Study_Level__c</fullName>
    <description>The level of education is used to determine the sub scheme the scoring configuration belongs.</description>
    <label>Study Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Undergraduate</fullName>
            </value>
            <value>
                <fullName>Postgraduate</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Lead_Score_Configuration__c/fields/Time_Limit_Months__c.field-meta.xml
<CustomField>
    <fullName>Time_Limit_Months__c</fullName>
    <description>The number months the calculation needs to consider activities for from current month</description>
    <label>Time Limit (Months)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/classes/LeadScoreConfigTriggerHelper.cls
/**
 * @description Helper class for LeadScoreConfigTriggerHandler
 * @see LeadScoreConfigTriggerHandler
 *
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | eccarius.munoz                 | October 24, 2023      | DEPP-5866              | Created file                 |   
 */
public with sharing class LeadScoreConfigTriggerHelper {
    
    public static void processLeadScoreCalculation(List<Lead_Score_Configuration__c> newItems, Map<Id, Lead_Score_Configuration__c> oldItems){

        Set<Id> leadScoreConfigIds = new Set<Id>();
        Set<Id> parentCategoryIds = new Set<Id>();
        Map<Id, Lead_Score_Configuration__c> configMap = new Map<Id,Lead_Score_Configuration__c>();
        Set<String> citizenshipStatusSet = new Set<String>();
        Set<String> primaryStudyLevelSet = new Set<String>();

        for(Lead_Score_Configuration__c leadScoreConfig : newItems){
            Boolean isCategoryUpdated = validateIfForCategory(leadScoreConfig, oldItems);
            Boolean isSubCategUpdated = validateIfForSubCategory(leadScoreConfig, oldItems);

            if(isCategoryUpdated){
                configMap.put(leadScoreConfig.Id, leadScoreConfig);
                citizenshipStatusSet.add(leadScoreConfig.Domestic_International__c);
                primaryStudyLevelSet.add(leadScoreConfig.Study_Level__c);
                leadScoreConfigIds.add(leadScoreConfig.Id);
            }

            if(isSubCategUpdated){
                parentCategoryIds.add(leadScoreConfig.Parent_Category__c);
                leadScoreConfigIds.add(leadScoreConfig.Parent_Category__c);
            }
        }     
        
        if(!leadScoreConfigIds.isEmpty()){
            LeadScoreConfigRecalculationBatch batch = new LeadScoreConfigRecalculationBatch();
            batch.recalculateLeadScore(leadScoreConfigIds);
        }   
        
    }

    private static Boolean validateIfForSubCategory(Lead_Score_Configuration__c leadScoreConfig, Map<Id, Lead_Score_Configuration__c> oldItems){
        Boolean isSubCategUpdated = 
            leadScoreConfig.RecordTypeId == LeadScoreConfigurationDAO.RECTYPE_ID_SUB_CATEGORY && 
            leadScoreConfig.Score_Allocation__c != oldItems.get(leadScoreConfig.Id).Score_Allocation__c;
        return isSubCategUpdated;
    }

    private static Boolean validateIfForCategory(Lead_Score_Configuration__c leadScoreConfig, Map<Id, Lead_Score_Configuration__c> oldItems){
        Boolean isCategoryUpdated = 
                leadScoreConfig.RecordTypeId == LeadScoreConfigurationDAO.RECTYPE_ID_CATEGORY && 
                (
                    leadScoreConfig.Max_Score__c != oldItems.get(leadScoreConfig.Id).Max_Score__c ||
                    leadScoreConfig.Time_Limit_Months__c != oldItems.get(leadScoreConfig.Id).Time_Limit_Months__c
                );
        return isCategoryUpdated;
    }

}