src/core-crm/objects/ABS_Categorisation__c/ABS_Categorisation__c.object-meta.xml
<CustomObject>
    <description>Contains Australian Bureau of Statistics (ABS) classifications for assessing low socio-economic status and regional and/or remoteness of a location.</description>
    <label>ABS Categorisation</label>
    <nameField>
        <label>ABS Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ABS Categorisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/ABS_Categorisation__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicator denoting if configuration is in effect</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/ABS_Categorisation__c/fields/Low_SES_Lower_Boundary__c.field-meta.xml
<CustomField>
    <fullName>Low_SES_Lower_Boundary__c</fullName>
    <description>Lower boundary value for the defined low socio-economic status percentile</description>
    <label>Low SES Lower Boundary</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/ABS_Categorisation__c/fields/Low_SES_Upper_Boundary__c.field-meta.xml
<CustomField>
    <fullName>Low_SES_Upper_Boundary__c</fullName>
    <description>Upper boundary value for the defined low socio-economic status percentile</description>
    <label>Low SES Upper Boundary</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/ABS_Categorisation__c/fields/Remoteness_Inner_Regional__c.field-meta.xml
<CustomField>
    <fullName>Remoteness_Inner_Regional__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the remoteness class is to be included in remote and regional definition</description>
    <label>Remoteness Inner Regional</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/ABS_Categorisation__c/fields/Remoteness_Outer_Regional__c.field-meta.xml
<CustomField>
    <fullName>Remoteness_Outer_Regional__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the remoteness class is to be included in remote and regional definition</description>
    <label>Remoteness Outer Regional</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/ABS_Categorisation__c/fields/Remoteness_Remote__c.field-meta.xml
<CustomField>
    <fullName>Remoteness_Remote__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the remoteness class is to be included in remote and regional definition</description>
    <label>Remoteness Remote</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/ABS_Categorisation__c/fields/Remoteness_Very_Remote__c.field-meta.xml
<CustomField>
    <fullName>Remoteness_Very_Remote__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the remoteness class is to be included in remote and regional definition</description>
    <label>Remoteness Very Remote</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Contact/fields/Low_Socio_Economic_Status__c.field-meta.xml
<CustomField>
    <fullName>Low_Socio_Economic_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The student’s low socio-economic status as determined by SA1 measure based on first known address</description>
    <label>Low Socio-Economic Status</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Contact/fields/QUT_Student__c.field-meta.xml
<CustomField>
    <fullName>QUT_Student__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>A Student is a person registered to study a learning activity or academic offering the institution provides.</inlineHelpText>
    <label>QUT Student</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/hed__Address__c/hed__Address__c.object-meta.xml
<CustomObject>
    <description>Stores address information. To support multiple and seasonal addresses.</description>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Address__c/fields/ABS_Categorisation__c.field-meta.xml
<CustomField>
    <fullName>ABS_Categorisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to the ABS categorisation that the SA1, meshblock, socio-economic percentile and remoteness classed are based on</description>
    <label>ABS Categorisation</label>
    <referenceTo>ABS_Categorisation__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Address__c/fields/hed__Address_Type__c.field-meta.xml
<CustomField>
    <fullName>hed__Address_Type__c</fullName>
    <description>Select what kind of address this is, for example, Home, Work, Vacation Residence, or Other.</description>
    <inlineHelpText>Select what kind of address this is, for example, Home, Work, Vacation Residence, or Other.</inlineHelpText>
    <label>Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Address__c/fields/hed__MailingCity__c.field-meta.xml
<CustomField>
    <fullName>hed__MailingCity__c</fullName>
    <label>Mailing City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Address__c/fields/hed__MailingCountry__c.field-meta.xml
<CustomField>
    <fullName>hed__MailingCountry__c</fullName>
    <label>Mailing Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Address__c/fields/hed__MailingPostalCode__c.field-meta.xml
<CustomField>
    <fullName>hed__MailingPostalCode__c</fullName>
    <label>Mailing Zip/Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Address__c/fields/hed__MailingState__c.field-meta.xml
<CustomField>
    <fullName>hed__MailingState__c</fullName>
    <label>Mailing State/Province</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Address__c/fields/hed__MailingStreet2__c.field-meta.xml
<CustomField>
    <fullName>hed__MailingStreet2__c</fullName>
    <description>Additional street address detail for this Address, such as Suite or Apt.</description>
    <inlineHelpText>Additional street address detail for this Address, such as Suite or Apt.</inlineHelpText>
    <label>Mailing Street2</label>
    <type>TextArea</type>
</CustomField>

src/core-crm/objects/hed__Address__c/fields/hed__MailingStreet__c.field-meta.xml
<CustomField>
    <fullName>hed__MailingStreet__c</fullName>
    <label>Mailing Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Address__c/fields/hed__Parent_Contact__c.field-meta.xml
<CustomField>
    <fullName>hed__Parent_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The primary Contact for this Address.</description>
    <inlineHelpText>The primary Contact for this Address.</inlineHelpText>
    <label>Parent Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Address__c/fields/Validated__c.field-meta.xml
<CustomField>
    <fullName>Validated__c</fullName>
    <description>Confirming that this has been validated from Loqate.</description>
    <label>Validated</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Loqate_Validation</valueSetName>
    </valueSet>
</CustomField>

src/core-crm/main/globalValueSets/Loqate_Validation.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>Valid</fullName>
    </customValue>
    <customValue>
        <fullName>Not Valid</fullName>
    </customValue>
    <description>Confirming that this has been validated from Loqate</description>
    <masterLabel>Loqate Validation</masterLabel>
</GlobalValueSet>

src/core-crm/classes/AddressTriggerHelperTest.cls
/**
 * @description Test class for AddressTriggerHelper
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | eccarius.munoz                 | May 31, 2024          | DEPP-8955              | Created file                 |
 */
@isTest
public with sharing class AddressTriggerHelperTest {
    
    @testSetup
    static void testSetup() {
        Test.startTest();
        TestDataFactory.generateTestUsers(new List<String>{'QUT_ESB'});
        Test.stopTest();
    }

    @isTest
    static void testAddressValidation() {
        System.runAs(TestDataFactory.getESBIntegrationUser()) {

            String mockResponseBody = '{"statisticalArea1":"Test Area","meshBlockId":"12345","socioEconomicPercentile":80,"remotenessClass":"Urban","isValid":true}';
            Test.setMock(HTTPCalloutMock.class, new GenericHttpCalloutMock(200, 'Success', mockResponseBody));

            List<ABS_Categorisation__c> absCategorisationList = new List<ABS_Categorisation__c>();
            absCategorisationList.add(
                new ABS_Categorisation__c(
                    Name = 'Categorisation 1',
                    Is_Active__c = true,
                    Low_SES_Lower_Boundary__c = 70,
                    Low_SES_Upper_Boundary__c = 100,
                    Remoteness_Inner_Regional__c = true,
                    Remoteness_Outer_Regional__c = true,
                    Remoteness_Remote__c = true,
                    Remoteness_Very_Remote__c = true
                )
            );
            ABSCategorisationsDAO.newInstance().insertRecords(absCategorisationList, true, AccessLevel.SYSTEM_MODE);
            
            List<Contact> contactList = TestDataFactory.createTestContactRecords(1, ContactsDAO.CITIZENSHIP_STATUS_DOMESTIC);          
            for(Contact con: contactList){
                con.RecordTypeId = ContactsDAO.PERSON_RECORDTYPE_ID;
                con.QUT_Student__c = true;
            }         
            ContactsDAO.newInstance().insertRecords(contactList, true, AccessLevel.SYSTEM_MODE);
            
            Test.startTest();
            List<hed__Address__c> addresses = new List<hed__Address__c>();
            for (Integer i = 0; i < contactList.size(); i++) {
                hed__Address__c add = new hed__Address__c();
                add.hed__Parent_Contact__c = contactList[i].Id;
                add.hed__Address_Type__c = AddressesDAO.OTHER_ADDRESS;
                add.Validated__c = AddressesDAO.NOT_VALID_ADDRESS;
                add.hed__MailingCountry__c = 'Australia';
                add.hed__MailingState__c = 'QLD';
                add.hed__MailingCity__c = 'DALLARNIL';
                add.hed__MailingPostalCode__c = '12345';
                add.hed__MailingStreet__c = '1234 Test St';
                add.hed__MailingStreet2__c = '4321 Tester Street';
                addresses.add(add);
            }

            AddressesDAO.newInstance().insertRecords(addresses, false, AccessLevel.SYSTEM_MODE);
            Test.stopTest();

            String batchName = 'AddressesValidationBatch';
            AsyncApexJob job = AsyncApexJobsDAO.newInstance().findAsyncApexJobByApexName(batchName, AccessLevel.SYSTEM_MODE);
            System.Assert.areEqual(batchName, job.ApexClass.Name, 'AddressesValidationBatch should not be executed.');

            Map<Id, Contact> contactMap = new Map<Id, Contact>(contactList);
            List<Contact> contactsUpdated = ContactsDAO.newInstance().getPersonContactsBySetIds(contactMap.keySet(), AccessLevel.SYSTEM_MODE);            
            for(Contact contact: contactsUpdated){
                System.Assert.areEqual(ContactsDAO.LOW_SOCIO_ECONOMIC_STATUS_YES, contact.Low_Socio_Economic_Status__c , 'Incorrect value for Low_Socio_Economic_Status__c.');
            }

            List<hed__Address__c> addressesUpdated = AddressesDAO.newInstance().getAddressesByContactIdsAndAddressType(contactMap.keySet(), new Set<String>{AddressesDAO.OTHER_ADDRESS}, 'SYSTEM_MODE');
            for(hed__Address__c address: addressesUpdated){
                System.Assert.areEqual(absCategorisationList[0].Id, address.ABS_Categorisation__c , 'Incorrect value for ABS_Categorisation__c.');
            }

        }
    }

    @isTest
    static void testNotForValidationAddress() {
        System.runAs(TestDataFactory.getESBIntegrationUser()) {

            String mockResponseBody = '{"statisticalArea1":"Test Area","meshBlockId":"12345","socioEconomicPercentile":80,"remotenessClass":"Urban","isValid":true}';
            Test.setMock(HTTPCalloutMock.class, new GenericHttpCalloutMock(200, 'Success', mockResponseBody));

            List<ABS_Categorisation__c> absCategorisationList = new List<ABS_Categorisation__c>();
            absCategorisationList.add(
                new ABS_Categorisation__c(
                    Name = 'Categorisation 1',
                    Is_Active__c = true,
                    Low_SES_Lower_Boundary__c = 90,
                    Low_SES_Upper_Boundary__c = 100,
                    Remoteness_Inner_Regional__c = true,
                    Remoteness_Outer_Regional__c = true,
                    Remoteness_Remote__c = true,
                    Remoteness_Very_Remote__c = true
                )
            );
            ABSCategorisationsDAO.newInstance().insertRecords(absCategorisationList, true, AccessLevel.SYSTEM_MODE);
            
            List<Contact> contactList = TestDataFactory.createTestContactRecords(1, ContactsDAO.CITIZENSHIP_STATUS_DOMESTIC);          
            for(Contact con: contactList){
                con.RecordTypeId = ContactsDAO.PERSON_RECORDTYPE_ID;
            }         
            ContactsDAO.newInstance().insertRecords(contactList, true, AccessLevel.SYSTEM_MODE);
            
            Test.startTest();
            List<hed__Address__c> addresses = new List<hed__Address__c>();
            for (Integer i = 0; i < contactList.size(); i++) {
                hed__Address__c add = new hed__Address__c();
                add.hed__Parent_Contact__c = contactList[i].Id;
                add.hed__Address_Type__c = 'Mailing';
                add.Validated__c = AddressesDAO.NOT_VALID_ADDRESS;
                add.hed__MailingCountry__c = 'Australia';
                add.hed__MailingState__c = 'QLD';
                add.hed__MailingCity__c = 'DALLARNIL';
                add.hed__MailingPostalCode__c = '12345';
                add.hed__MailingStreet__c = '1234 Test St';
                add.hed__MailingStreet2__c = '4321 Tester Street';
                addresses.add(add);
            }
            
            AddressesDAO.newInstance().insertRecords(addresses, false, AccessLevel.SYSTEM_MODE);
            Test.stopTest();

            String batchName = 'AddressesValidationBatch';
            AsyncApexJob job = AsyncApexJobsDAO.newInstance().findAsyncApexJobByApexName(batchName, AccessLevel.SYSTEM_MODE);
            System.Assert.isTrue(job == null, 'AddressesValidationBatch should not be executed.');

            Map<Id, Contact> contactMap = new Map<Id, Contact>(contactList);
            List<Contact> contactsUpdated = ContactsDAO.newInstance().getPersonContactsBySetIds(contactMap.keySet(), AccessLevel.SYSTEM_MODE);            
            for(Contact contact: contactsUpdated){
                System.Assert.areEqual(ContactsDAO.LOW_SOCIO_ECONOMIC_STATUS_UNKNOWN, contact.Low_Socio_Economic_Status__c, 'Low_Socio_Economic_Status__c should be unknown.');
            }

            List<hed__Address__c> addressesUpdated = AddressesDAO.newInstance().getAddressesByContactIdsAndAddressType(contactMap.keySet(), new Set<String>{AddressesDAO.OTHER_ADDRESS}, 'SYSTEM_MODE');
            for(hed__Address__c address: addressesUpdated){
                System.Assert.isNull(address.ABS_Categorisation__c , 'ABS_Categorisation__c should not be set.');
            }

        }
    }

}