src/core-crm/objects/ABS_Categorisation__c/ABS_Categorisation__c.object-meta.xml
<CustomObject>
    <description>Contains Australian Bureau of Statistics (ABS) classifications for assessing low socio-economic status and regional and/or remoteness of a location.</description>
    <label>ABS Categorisation</label>
    <nameField>
        <label>ABS Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ABS Categorisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/ABS_Categorisation__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicator denoting if configuration is in effect</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/ABS_Categorisation__c/fields/Low_SES_Lower_Boundary__c.field-meta.xml
<CustomField>
    <fullName>Low_SES_Lower_Boundary__c</fullName>
    <description>Lower boundary value for the defined low socio-economic status percentile</description>
    <label>Low SES Lower Boundary</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/ABS_Categorisation__c/fields/Low_SES_Upper_Boundary__c.field-meta.xml
<CustomField>
    <fullName>Low_SES_Upper_Boundary__c</fullName>
    <description>Upper boundary value for the defined low socio-economic status percentile</description>
    <label>Low SES Upper Boundary</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/ABS_Categorisation__c/fields/Remoteness_Inner_Regional__c.field-meta.xml
<CustomField>
    <fullName>Remoteness_Inner_Regional__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the remoteness class is to be included in remote and regional definition</description>
    <label>Remoteness Inner Regional</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/ABS_Categorisation__c/fields/Remoteness_Outer_Regional__c.field-meta.xml
<CustomField>
    <fullName>Remoteness_Outer_Regional__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the remoteness class is to be included in remote and regional definition</description>
    <label>Remoteness Outer Regional</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/ABS_Categorisation__c/fields/Remoteness_Remote__c.field-meta.xml
<CustomField>
    <fullName>Remoteness_Remote__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the remoteness class is to be included in remote and regional definition</description>
    <label>Remoteness Remote</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/ABS_Categorisation__c/fields/Remoteness_Very_Remote__c.field-meta.xml
<CustomField>
    <fullName>Remoteness_Very_Remote__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the remoteness class is to be included in remote and regional definition</description>
    <label>Remoteness Very Remote</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Contact/fields/QUT_Student__c.field-meta.xml
<CustomField>
    <fullName>QUT_Student__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>A Student is a person registered to study a learning activity or academic offering the institution provides.</inlineHelpText>
    <label>QUT Student</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/hed__Address__c/hed__Address__c.object-meta.xml
<CustomObject>
    <description>Stores address information. To support multiple and seasonal addresses.</description>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Address__c/fields/ABS_Categorisation__c.field-meta.xml
<CustomField>
    <fullName>ABS_Categorisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to the ABS categorisation that the SA1, meshblock, socio-economic percentile and remoteness classed are based on</description>
    <label>ABS Categorisation</label>
    <referenceTo>ABS_Categorisation__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Address__c/fields/hed__Address_Type__c.field-meta.xml
<CustomField>
    <fullName>hed__Address_Type__c</fullName>
    <description>Select what kind of address this is, for example, Home, Work, Vacation Residence, or Other.</description>
    <inlineHelpText>Select what kind of address this is, for example, Home, Work, Vacation Residence, or Other.</inlineHelpText>
    <label>Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Mailing</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Address__c/fields/hed__Parent_Contact__c.field-meta.xml
<CustomField>
    <fullName>hed__Parent_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The primary Contact for this Address.</description>
    <inlineHelpText>The primary Contact for this Address.</inlineHelpText>
    <label>Parent Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Address__c/fields/Validated__c.field-meta.xml
<CustomField>
    <fullName>Validated__c</fullName>
    <description>Confirming that this has been validated from Loqate.</description>
    <label>Validated</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Loqate_Validation</valueSetName>
    </valueSet>
</CustomField>

src/core-crm/main/globalValueSets/Loqate_Validation.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>Valid</fullName>
    </customValue>
    <customValue>
        <fullName>Not Valid</fullName>
    </customValue>
    <description>Confirming that this has been validated from Loqate</description>
    <masterLabel>Loqate Validation</masterLabel>
</GlobalValueSet>

src/core-crm/classes/ContactAddressValidationBatchTest.cls
/**
 * @description Test class for ContactAddressValidationBatch
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | mark.j.mahilum                 | May 31, 2024          | DEPP-8956              | Created file                 |
 */
@isTest
private class ContactAddressValidationBatchTest {

    @testSetup
    static void testSetup() {
        Test.startTest();
        TestDataFactory.generateTestUsers(new List<String>{'QUT_ESB','QUT_Program_Administrator'});
        System.runAs(TestDataFactory.getESBIntegrationUser()) {
            List<ABS_Categorisation__c> absCategorisation = new List<ABS_Categorisation__c>();
            absCategorisation.add(
                new ABS_Categorisation__c(
                    Name = 'Categorisation 1',
                    Is_Active__c = true,
                    Low_SES_Lower_Boundary__c = 0,
                    Low_SES_Upper_Boundary__c = 80,
                    Remoteness_Inner_Regional__c = true,
                    Remoteness_Outer_Regional__c = true,
                    Remoteness_Remote__c = true,
                    Remoteness_Very_Remote__c = true
                )
            );
            
            ABSCategorisationsDAO.newInstance().insertRecords(absCategorisation, false, AccessLevel.USER_MODE);
        }
        Test.stopTest();
    }
    
    @isTest
    static void processEmptyAddressesTest() {
        System.runAs(TestDataFactory.getESBIntegrationUser()) {
			            
            Test.startTest();
            ContactAddressValidationBatch batch = new ContactAddressValidationBatch(new Set<Id>{});
            Id batchableId = Database.executeBatch(batch);
            Test.stopTest();
            
            System.Assert.isTrue(
                batchableId != null,
                'The batch job failed to execute.'
            );
        }
    }

    
    @isTest
    static void processNotValidatedAddressesTest() {
        System.runAs(TestDataFactory.getESBIntegrationUser()) {
            
            List<Contact> contactList = TestDataFactory.createTestContactRecords(3, '');          
            for(Contact con: contactList){
                con.RecordTypeId = ContactsDAO.PERSON_RECORDTYPE_ID;
                con.QUT_Student__c = true;
            }         
            ContactsDAO.newInstance().insertRecords(contactList, false, AccessLevel.USER_MODE);
            
            List<hed__Address__c> addresses = new List<hed__Address__c>();
            Set<Id> addressIdSet = new Set<Id>();
            
            for (Integer i = 0; i < contactList.size(); i++) {
                hed__Address__c add = new hed__Address__c();
                add.hed__Parent_Contact__c = contactList[0].Id;
                add.hed__Address_Type__c = AddressesDAO.OTHER_ADDRESS;
                add.Validated__c = AddressesDAO.NOT_VALID_ADDRESS;
                addresses.add(add);
                addressIdSet.add(add.Id);
            }

            AddressesDAO.newInstance().insertRecords(addresses, false, AccessLevel.USER_MODE);
            
            Test.startTest();
            ContactAddressValidationBatch batch = new ContactAddressValidationBatch(addressIdSet);
            Id batchableId = Database.executeBatch(batch);
            Test.stopTest();
            
            System.Assert.isTrue(
                batchableId != null,
                'The batch job failed to execute.'
            );

            List<LogEntry__c> logEntries = LogEntriesDAO.newInstance().getLogEntriesByRelatedRecordId(
                new Map<Id,Contact>(contactList).keySet(),
                AccessLevel.USER_MODE
            );

            System.assert(logEntries.isEmpty(),'error log entries should be empty');
        }
    }
    
    @isTest
    static void processContactWithFirstAdmittedAddressesTest() {
        System.runAs(TestDataFactory.getESBIntegrationUser()) {
            
            List<Contact> contactList = TestDataFactory.createTestContactRecords(3, '');          
            for(Contact con: contactList){
                con.RecordTypeId = ContactsDAO.PERSON_RECORDTYPE_ID;
            }         
            ContactsDAO.newInstance().insertRecords(contactList, false, AccessLevel.USER_MODE);
            List<hed__Address__c> addresses = new List<hed__Address__c>();
            Set<Id> addressIdSet = new Set<Id>();
            
            for (Integer i = 0; i < contactList.size(); i++) {
                hed__Address__c add = new hed__Address__c();
                add.hed__Parent_Contact__c = contactList[i].Id;
                add.hed__Address_Type__c = AddressesDAO.FIRST_ADMITTED_ADDRESS;
                add.Validated__c = AddressesDAO.NOT_VALID_ADDRESS;
                addresses.add(add);
                addressIdSet.add(add.Id);
            }

            AddressesDAO.newInstance().insertRecords(addresses, false, AccessLevel.USER_MODE);
            
            Test.startTest();
            ContactAddressValidationBatch batch = new ContactAddressValidationBatch(addressIdSet);
            Id batchableId = Database.executeBatch(batch);
            Test.stopTest();
            
            System.Assert.isTrue(
                batchableId != null,
                'The batch job failed to execute.'
            );

            List<LogEntry__c> logEntries = LogEntriesDAO.newInstance().getLogEntriesByRelatedRecordId(
                new Map<Id,Contact>(contactList).keySet(),
                AccessLevel.USER_MODE
            );

            System.assert(logEntries.isEmpty(),'error log entries should be empty');
        }
    }
}