src/core-crm/objects/ABS_Categorisation__c/ABS_Categorisation__c.object-meta.xml
<CustomObject>
    <description>Contains Australian Bureau of Statistics (ABS) classifications for assessing low socio-economic status and regional and/or remoteness of a location.</description>
    <label>ABS Categorisation</label>
    <nameField>
        <label>ABS Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ABS Categorisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Address__c/hed__Address__c.object-meta.xml
<CustomObject>
    <description>Stores address information. To support multiple and seasonal addresses.</description>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Address__c/fields/ABS_Categorisation__c.field-meta.xml
<CustomField>
    <fullName>ABS_Categorisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to the ABS categorisation that the SA1, meshblock, socio-economic percentile and remoteness classed are based on</description>
    <label>ABS Categorisation</label>
    <referenceTo>ABS_Categorisation__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Address__c/fields/GNAF_Id__c.field-meta.xml
<CustomField>
    <fullName>GNAF_Id__c</fullName>
    <description>The GNAF ID from Loqate</description>
    <label>GNAF ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Address__c/fields/Meshblock_Id__c.field-meta.xml
<CustomField>
    <fullName>Meshblock_Id__c</fullName>
    <description>Meshblock identifier published by Australian Bureau of Statistics</description>
    <label>Meshblock ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Address__c/fields/Remoteness_Class__c.field-meta.xml
<CustomField>
    <fullName>Remoteness_Class__c</fullName>
    <description>The remoteness classification given to the meshblock</description>
    <label>Remoteness Class</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Address__c/fields/Socio_Economic_Percentile__c.field-meta.xml
<CustomField>
    <fullName>Socio_Economic_Percentile__c</fullName>
    <description>The socio-economic percentile published by Australian Bureau of Statistics for SA1</description>
    <label>Socio-Economic Percentile</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/hed__Address__c/fields/Statistical_Area_1_Id__c.field-meta.xml
<CustomField>
    <fullName>Statistical_Area_1_Id__c</fullName>
    <description>Statistical Area 1 identifier published by Australian Bureau of Statistics</description>
    <label>Statistical Area 1 ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Address__c/fields/Validated__c.field-meta.xml
<CustomField>
    <fullName>Validated__c</fullName>
    <description>Confirming that this has been validated from Loqate.</description>
    <label>Validated</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Loqate_Validation</valueSetName>
    </valueSet>
</CustomField>

src/core-crm/main/globalValueSets/Loqate_Validation.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>None</fullName>
        <default>true</default>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>Valid</fullName>
    </customValue>
    <customValue>
        <fullName>Not Valid</fullName>
    </customValue>
    <description>Confirming that this has been validated from Loqate</description>
    <masterLabel>Loqate Validation</masterLabel>
</GlobalValueSet>

src/core-crm/classes/AddressesValidationBatch.cls
/**
 * @description Batch class to process address validation from hed__Address__c after insert trigger
 * @see AddressTriggerHelper
 *
 * @author Accenture
 *
 * @history
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | eccarius.karl.munoz            | May 29, 2024          | DEPP-8955              | Created file                 |
 */
public with sharing class AddressesValidationBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {
    
    private Set<Id> addressIds;
    private Map<Id, Contact> contactMap;
    private Boolean isUpdatedMailingAddress;

    public AddressesValidationBatch(Set<Id> addressIds){
        this.addressIds = addressIds;
    }

    public AddressesValidationBatch(Set<Id> addressIds, Map<Id, Contact> contactMap, Boolean isUpdatedMailingAddress){
        this.addressIds = addressIds;
        this.contactMap = contactMap;
        this.isUpdatedMailingAddress = isUpdatedMailingAddress;
    }
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return AddressesDAO.newInstance().getQueryLocatorByIds(addressIds);
    }    

    public void execute(Database.BatchableContext bc, List<hed__Address__c> addressList){
        AddressValidationManager addressValidation;
        if(contactMap != null){
            if(isUpdatedMailingAddress){
                for(hed__Address__c address : addressList){
                    address.Statistical_Area_1_Id__c = null;
                    address.Meshblock_Id__c = null;                
                    address.Socio_Economic_Percentile__c = null;
                    address.Remoteness_Class__c = null;
                    address.GNAF_Id__c = null;
                    address.Validated__c = null;
                    address.ABS_Categorisation__c = null;
                }
            }
            addressValidation = new AddressValidationManager(addressList, contactMap);
            addressValidation.processValidationForAddress();
        }else{
            addressValidation = new AddressValidationManager(addressList);
            addressValidation.processValidateAddress();
        }
    }  

    @SuppressWarnings('PMD.EmptyStatementBlock')
    public void finish(Database.BatchableContext bc) {}

}