src/core-crm/objects/Activity_Code_Generator__c/Activity_Code_Generator__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Will be used to store the latest code for course with activity record type.</description>
    <label>Activity Code Generator</label>
</CustomObject>

src/core-crm/objects/CCE_Activity_Code_Generator__c/CCE_Activity_Code_Generator__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CCE Activity Code Generator</label>
</CustomObject>

src/core-crm/objects/CCE_Coaching_Code_Generator__c/CCE_Coaching_Code_Generator__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CCE Coaching Code Generator</label>
</CustomObject>

src/core-crm/objects/CCE_Diagnostic_Tool_Code_Generator__c/CCE_Diagnostic_Tool_Code_Generator__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CCE Diagnostic Tool Code Generator</label>
</CustomObject>

src/core-crm/objects/CCE_Individual_Coaching_Code_Generator__c/CCE_Individual_Coaching_Code_Generator__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CCE Individual Coaching Code Generator</label>
</CustomObject>

src/core-crm/objects/CCE_Module_Code_Generator__c/CCE_Module_Code_Generator__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CCE Module Code Generator</label>
</CustomObject>

src/core-crm/objects/CCE_Program_Code_Generator__c/CCE_Program_Code_Generator__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CCE Program Code Generator</label>
</CustomObject>

src/core-crm/objects/CCE_PWP_Code_Generator__c/CCE_PWP_Code_Generator__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to store the last generated code for CCE Program Without Pathway Program records.</description>
    <label>CCE PWP Code Generator</label>
</CustomObject>

src/core-crm/objects/CCE_Short_Course_Code_Generator__c/CCE_Short_Course_Code_Generator__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CCE Short Course Code Generator</label>
</CustomObject>

src/core-crm/objects/CCE_Unit_Code_Generator__c/CCE_Unit_Code_Generator__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CCE Unit Code Generator</label>
</CustomObject>

src/core-crm/objects/hed__Course__c/hed__Course__c.object-meta.xml
<CustomObject>
    <description>Academic Course offered by a Department or School, for example, English 101 or Ancient History.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course__c/fields/Course_Code__c.field-meta.xml
<CustomField>
    <fullName>Course_Code__c</fullName>
    <description>Course code is the QUT unique business identifier assigned to a Course.

For SAMS units it is combination of Course Code and Course Version
Format &lt;Course_Code&gt;-&lt;Version no&gt;
eg MAB522-3</description>
    <inlineHelpText>Course code is the QUT unique business identifier assigned to a Course.

For SAMS units it is combination of Course Code and Course Version
Format &lt;Course_Code&gt;-&lt;Version no&gt;
eg MAB522-3</inlineHelpText>
    <label>Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/core-crm/objects/hed__Course__c/fields/ProductRequestID__c.field-meta.xml
<CustomField>
    <fullName>ProductRequestID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course__c/recordTypes/Activity.recordType-meta.xml
<RecordType>
    <fullName>Activity</fullName>
    <active>true</active>
    <label>Activity</label>
    <picklistValues>
        <!-- Renamed from Collaboation_External__c-->
        <picklist>Collaboration_with_External_Organisation__c</picklist>
        <values>
            <fullName>No</fullName>
        </values>
        <values>
            <fullName>Yes</fullName>
        </values>
    </picklistValues>
</RecordType>

src/core-crm/objects/hed__Course__c/recordTypes/Diagnostic_Tool.recordType-meta.xml
<RecordType>
    <fullName>Diagnostic_Tool</fullName>
    <active>true</active>
    <label>Diagnostic Tool</label>
</RecordType>

src/core-crm/objects/hed__Course__c/recordTypes/Group_Coaching.recordType-meta.xml
<RecordType>
    <fullName>Group_Coaching</fullName>
    <active>true</active>
    <label>Group Coaching</label>
    <picklistValues>
    <!-- Renamed from Collaboation_External__c-->
    <picklist>Collaboration_with_External_Organisation__c</picklist>
        <values>
            <fullName>No</fullName>
        </values>
        <values>
            <fullName>Yes</fullName>
        </values>
    </picklistValues>
</RecordType>

src/core-crm/objects/hed__Course__c/recordTypes/Individual_Coaching.recordType-meta.xml
<RecordType>
    <fullName>Individual_Coaching</fullName>
    <active>true</active>
    <label>Individual Coaching</label>
</RecordType>

src/core-crm/objects/hed__Course__c/recordTypes/Module.recordType-meta.xml
<RecordType>
    <fullName>Module</fullName>
    <active>true</active>
    <description>This record type will be used to create a Non-Award Unit or a Short Course with a learning pathway.</description>
    <label>Module</label>
   <picklistValues>
       <!-- Renamed from Collaboation_External__c-->
       <picklist>Collaboration_with_External_Organisation__c</picklist>
        <values>
            <fullName>No</fullName>
        </values>
        <values>
            <fullName>Yes</fullName>
        </values>
    </picklistValues>
</RecordType>

src/core-crm/objects/hed__Course__c/recordTypes/Short_Course.recordType-meta.xml
<RecordType>
    <fullName>Short_Course</fullName>
    <active>true</active>
    <label>Short Course</label>
</RecordType>

src/core-crm/objects/hed__Course__c/recordTypes/Unit.recordType-meta.xml
<RecordType>
    <fullName>Unit</fullName>
    <active>true</active>
    <description>This record type will be used to create an Award Unit with a learning pathway.</description>
    <label>Unit</label>
</RecordType>

src/core-crm/objects/hed__Program_Plan__c/hed__Program_Plan__c.object-meta.xml
<CustomObject>
    <description>Links Courses to an Academic Program to create a path for students to follow. An Academic Program can list multiple Courses, and a Course can be associated with multiple Academic Programs.</description>
    <label>Program Plan</label>
    <nameField>
        <label>Program Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Program_Plan__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <inlineHelpText>This is a code that uniquely identifies the QUTeX product/course. Codes are in the format @@@###, where @ is an alphabetic character and # is a numeric character.</inlineHelpText>
    <label>Code</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/core-crm/objects/hed__Program_Plan__c/fields/Product_Request__c.field-meta.xml
<CustomField>
    <fullName>Product_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the related Product Request record of the Program Plan.</description>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Program_Plan__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Doctorate by Research</fullName>
            </value>
            <value>
                <fullName>Doctorate by Coursework</fullName>
            </value>
            <value>
                <fullName>Masters by Research</fullName>
            </value>
            <value>
                <fullName>Masters by Coursework - Single</fullName>
            </value>
            <value>
                <fullName>Graduate Diploma - New Area</fullName>
            </value>
            <value>
                <fullName>Graduate Diploma - Exsiting Area</fullName>
            </value>
            <value>
                <fullName>Graduate Certificate</fullName>
            </value>
            <value>
                <fullName>Bachelor Pass Degree - Graduate Entry</fullName>
            </value>
            <value>
                <fullName>Bachelor Honours - Graduate Entry</fullName>
            </value>
            <value>
                <fullName>Bachelor Pass Single Degree</fullName>
            </value>
            <value>
                <fullName>Bachelor Pass Double Degree</fullName>
            </value>
            <value>
                <fullName>Masters by Coursework - Double Degree</fullName>
            </value>
            <value>
                <fullName>Certificate and University Certificate</fullName>
            </value>
            <value>
                <fullName>Diploma and University Diploma</fullName>
            </value>
            <value>
                <fullName>Non Award Course - Foundation</fullName>
            </value>
            <value>
                <fullName>Bachelor Honours Degree</fullName>
            </value>
            <value>
                <fullName>Bachelor Honours/Pass Double Degree</fullName>
            </value>
            <value>
                <fullName>Associate Degree</fullName>
            </value>
            <value>
                <fullName>Undergraduate Certificate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Program_Plan__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <description>This record type will be used to create a Program. This can be a combination of a Unit, a Module, a Short Course, or an Activity.</description>
    <label>Program</label>
</RecordType>

src/core-crm/objects/hed__Program_Plan__c/recordTypes/Program_Without_Pathway.recordType-meta.xml
<RecordType>
    <fullName>Program_Without_Pathway</fullName>
    <active>true</active>
    <description>This record type will be used to create a Program without Pathway that does not require CourseLoop approval. This can be a combination of a Module, a Short Course, or an Activity.</description>
    <label>Program Without Pathway</label>
</RecordType>

src/core-crm/objects/Module_Code_Generator__c/Module_Code_Generator__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Will be used to store the latest code for course with module record type.</description>
    <label>Module Code Generator</label>
</CustomObject>

src/core-crm/objects/Product_Request__c/Product_Request__c.object-meta.xml
<CustomObject>
    <label>Product Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Product Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Product_Request__c/fields/Product_Specification__c.field-meta.xml
<CustomField>
    <fullName>Product_Specification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Specification</label>
    <referenceTo>Product_Specification__c</referenceTo>
    <relationshipLabel>Product Requests</relationshipLabel>
    <relationshipName>Product_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Product_Request__c/recordTypes/Activity.recordType-meta.xml
<RecordType>
    <fullName>Activity</fullName>
    <active>true</active>
    <description>This record type will be used to create an Event, Discussion Forum, or workshop.</description>
    <label>Activity</label>
</RecordType>

src/core-crm/objects/Product_Request__c/recordTypes/Diagnostic_Tool.recordType-meta.xml
<RecordType>
    <fullName>Diagnostic_Tool</fullName>
    <active>true</active>
    <description>This record type will be used to request diagnostic tool which can be delivered in isolation or as part of a program.</description>
    <label>Diagnostic Tool</label>
</RecordType>

src/core-crm/objects/Product_Request__c/recordTypes/Group_Coaching.recordType-meta.xml
<RecordType>
    <fullName>Group_Coaching</fullName>
    <active>true</active>
    <description>This record type will be used to request group Coaching which can be delivered in isolation or as part of a program.</description>
    <label>Group Coaching</label>
</RecordType>

src/core-crm/objects/Product_Request__c/recordTypes/Individual_Coaching.recordType-meta.xml
<RecordType>
    <fullName>Individual_Coaching</fullName>
    <active>true</active>
    <description>This record type will be used to request individual Coaching which can be delivered in isolation or as part of a program.</description>
    <label>Individual Coaching</label>
</RecordType>

src/core-crm/objects/Product_Request__c/recordTypes/Module.recordType-meta.xml
<RecordType>
    <fullName>Module</fullName>
    <active>true</active>
    <description>This record type will be used to create a Non-Award Unit or a Short Course with a learning pathway.</description>
    <label>Module</label>
</RecordType>

src/core-crm/objects/Product_Request__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <description>This record type will be used to create a Program. This can be a combination of a Unit, a Module, a Short Course, or an Activity.</description>
    <label>Program</label>
</RecordType>

src/core-crm/objects/Product_Request__c/recordTypes/Program_Without_Pathway.recordType-meta.xml
<RecordType>
    <fullName>Program_Without_Pathway</fullName>
    <active>true</active>
    <description>This record type will be used to create a Program without Pathway that does not require CourseLoop approval. This can be a combination of a Module, a Short Course, or an Activity.</description>
    <label>Program Without Pathway</label>
</RecordType>

src/core-crm/objects/Product_Request__c/recordTypes/Short_Course.recordType-meta.xml
<RecordType>
    <fullName>Short_Course</fullName>
    <active>true</active>
    <description>This record type will be used to request a Product without learning outcomes.</description>
    <label>Short Course</label>
</RecordType>

src/core-crm/objects/Product_Request__c/recordTypes/Unit.recordType-meta.xml
<RecordType>
    <fullName>Unit</fullName>
    <active>true</active>
    <description>This record type will be used to create an Award Unit with a learning pathway.</description>
    <label>Unit</label>
</RecordType>

src/core-crm/objects/Product_Specification__c/Product_Specification__c.object-meta.xml
<CustomObject>
    <label>Product Specification</label>
    <nameField>
        <displayFormat>PS-{00000}</displayFormat>
        <label>Product Specification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Specifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Product_Specification__c/recordTypes/CCE.recordType-meta.xml
<RecordType>
    <fullName>CCE</fullName>
    <active>true</active>
    <description>Used to Design products which are the result of a closed won Opportunity in Salesforce.</description>
    <label>CCE</label>
</RecordType>

src/core-crm/objects/Product_Specification__c/recordTypes/OPE.recordType-meta.xml
<RecordType>
    <fullName>OPE</fullName>
    <active>true</active>
    <description>Used to Design products which are the result of an idea request from a faculty.</description>
    <label>OPE</label>
</RecordType>

src/core-crm/objects/Program_Code_Generator__c/Program_Code_Generator__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Will be used to store the latest code for program.</description>
    <label>Program Code Generator</label>
</CustomObject>

src/core-crm/objects/PWP_Code_Generator__c/PWP_Code_Generator__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to store the last generated code for OPE Program Without Pathway Program records.</description>
    <label>PWP Code Generator</label>
</CustomObject>

src/core-crm/objects/Short_Course_Code_Generator__c/Short_Course_Code_Generator__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Will be used to store the latest code for course with short course record type.</description>
    <label>Short Course Code Generator</label>
</CustomObject>

src/core-crm/classes/GenerateCodeCtrl.cls
/**
 * @description Controller Class for generateCode LWC
 * @see ../lwc/generateCode
 *
 * @author Accenture
 *
 * @history
 *    | Developer                 | Date                  | JIRA                 | Change Summary               |
      |---------------------------|-----------------------|----------------------|------------------------------|
      | eccarius.karl.munoz       | May 11, 2022          | DEPP-2336            | Created file                 |
      |                           |                       |                      |                              |
      | eccarius.karl.munoz       | June 28, 2022         | DEPP-3272            | Created Custom Settings per  |
      |                           |                       |                      | per record type.             |
      |                           |                       |                      |                              |
      |                           |                       |                      | Removed saving of multiple   |
      |                           |                       |                      | records into the custom      |
      |                           |                       |                      | settings.                    |
      | arsenio.jr.dayrit         | July 12, 2022         | DEPP-2337            | Added condition for CCE      |
      |                           |                       |                      | generate code                |
      | alexander.cadalin         | September 05, 2022    | DEPP-4094            | + OPE & CCE, PWP Code Gen    |
*/
public with sharing class GenerateCodeCtrl {

    /**
     * Retrieves Course or Program record based on product request.
     * @param String recordId
     * @return CourseProgramDetails
     */
    @AuraEnabled(cacheable=true)
    public static CourseProgramDetails getCourseAndProgDetails(String recordId){
        List<hed__Course__c> courses = [SELECT Id, Name, Course_Code__c, RecordType.DeveloperName, ProductRequestID__r.Name, ProductRequestID__r.Id, 
        ProductRequestID__r.Product_Specification__r.RecordType.DeveloperName FROM hed__Course__c WHERE ProductRequestID__c =: recordId LIMIT 1];
        
        List<hed__Program_Plan__c> programs = [SELECT Id, Name, Code__c, RecordType.DeveloperName, Product_Request__r.Name, Product_Request__r.Id, 
        Product_Request__r.Product_Specification__r.RecordType.DeveloperName FROM hed__Program_Plan__c WHERE Product_Request__c  =: recordId LIMIT 1];

        CourseProgramDetails response = new CourseProgramDetails();
        for(hed__Course__c course: courses){
            response.recordId = course.Id;
            response.recordCode = course.Course_Code__c;
            response.recordType = course.RecordType.DeveloperName;
            response.recordProgCourseName = course.Name;
            response.productSpecsRT = course.ProductRequestID__r.Product_Specification__r.RecordType.DeveloperName;
        }
        for(hed__Program_Plan__c program: programs){
            response.recordId = program.Id;
            response.recordCode = program.Code__c;
            response.recordType = program.RecordType.DeveloperName;
            response.recordProgCourseName = program.Name;
            response.productSpecsRT = program.Product_Request__r.Product_Specification__r.RecordType.DeveloperName;
        }        
        return response;
    }

    /**
     * Generates code with a specific format based on record type
     * @param String recordType
     * @param String prodSpecsRecordType
     * @return String codeGenerated
     */
    @AuraEnabled
    public static CourseProgramDetails generateCode(String recordType, String prodSpecsRecordType){
        CourseProgramDetails response = new CourseProgramDetails();
        String codeGenerated = '';
        String codePrefix = '';
        Decimal num;
        if(recordType == 'Activity'){  
            if(prodSpecsRecordType != 'OPE'){
                List<CCE_Activity_Code_Generator__c> codeGenList = [SELECT Id, Number__c FROM CCE_Activity_Code_Generator__c WHERE Type__c =: recordType LIMIT 1];  
                for(CCE_Activity_Code_Generator__c codeGen : codeGenList){
                    response.recordId = codeGen.Id;
                    response.recordNumber = Integer.valueOf(codeGen.Number__c) + 1;                
                    num = codeGen.Number__c;                
                }
                codePrefix = 'EXCA'; 
                
            }else{
                List<Activity_Code_Generator__c> codeGenList = [SELECT Id, Number__c FROM Activity_Code_Generator__c WHERE Type__c =: recordType LIMIT 1];  
                for(Activity_Code_Generator__c codeGen : codeGenList){
                    response.recordId = codeGen.Id;
                    response.recordNumber = Integer.valueOf(codeGen.Number__c) + 1;                
                    num = codeGen.Number__c;                
                }
                codePrefix = 'EXOA'; 
            }
            codeGenerated = getCode(codePrefix, num);   
            response.recordCode = codeGenerated;           
        } 
        
        if(recordType == 'Module'){
            if(prodSpecsRecordType != 'OPE'){
                List<CCE_Module_Code_Generator__c> codeGenList = [SELECT Id, Number__c FROM CCE_Module_Code_Generator__c WHERE Type__c =: recordType LIMIT 1];  
                for(CCE_Module_Code_Generator__c codeGen : codeGenList){
                response.recordId = codeGen.Id;
                response.recordNumber = Integer.valueOf(codeGen.Number__c) + 1;                
                num = codeGen.Number__c;                
            }
            codePrefix = 'EXCM'; 

            }else{
                List<Module_Code_Generator__c> codeGenList = [SELECT Id, Number__c FROM Module_Code_Generator__c WHERE Type__c =: recordType LIMIT 1];  
                for(Module_Code_Generator__c codeGen : codeGenList){
                    response.recordId = codeGen.Id;
                    response.recordNumber = Integer.valueOf(codeGen.Number__c) + 1;                
                    num = codeGen.Number__c;                
                }
                codePrefix = 'EXOM'; 
                
            }
            codeGenerated = getCode(codePrefix, num);    
            response.recordCode = codeGenerated;
        }
    

        if(recordType == 'Short_Course'){
            if(prodSpecsRecordType != 'OPE'){
                List<CCE_Short_Course_Code_Generator__c> codeGenList = [SELECT Id, Number__c FROM CCE_Short_Course_Code_Generator__c WHERE Type__c =: recordType LIMIT 1];  
                for(CCE_Short_Course_Code_Generator__c codeGen : codeGenList){
                    response.recordId = codeGen.Id;
                    response.recordNumber = Integer.valueOf(codeGen.Number__c) + 1;                
                    num = codeGen.Number__c;                
                }
                codePrefix = 'EXCS'; 
            }else{
                List<Short_Course_Code_Generator__c> codeGenList = [SELECT Id, Number__c FROM Short_Course_Code_Generator__c WHERE Type__c =: recordType LIMIT 1];  
                for(Short_Course_Code_Generator__c codeGen : codeGenList){
                    response.recordId = codeGen.Id;
                    response.recordNumber = Integer.valueOf(codeGen.Number__c) + 1;                
                    num = codeGen.Number__c;                
                }
                codePrefix = 'EXOS'; 
            }
            
            codeGenerated = getCode(codePrefix, num);   
            response.recordCode = codeGenerated;
        }
        
        if(recordType == 'Program'){  
            if(prodSpecsRecordType != 'OPE'){
                List<CCE_Program_Code_Generator__c> codeGenList = [SELECT Id, Number__c FROM CCE_Program_Code_Generator__c WHERE Type__c =: recordType LIMIT 1];  
                for(CCE_Program_Code_Generator__c codeGen : codeGenList){
                    response.recordId = codeGen.Id;
                    response.recordNumber = Integer.valueOf(codeGen.Number__c) + 1;                
                    num = codeGen.Number__c;                
                }
                codePrefix = 'EXCP'; 

            }else{
                List<Program_Code_Generator__c> codeGenList = [SELECT Id, Number__c FROM Program_Code_Generator__c WHERE Type__c =: recordType LIMIT 1];  
                for(Program_Code_Generator__c codeGen : codeGenList){
                    response.recordId = codeGen.Id;
                    response.recordNumber = Integer.valueOf(codeGen.Number__c) + 1;                
                    num = codeGen.Number__c;                
                }
                codePrefix = 'EXOP'; 
            }
            codeGenerated = getCode(codePrefix, num);    
            response.recordCode = codeGenerated;
        }

        if(recordType == 'Unit'){  
            List<CCE_Unit_Code_Generator__c> codeGenList = [SELECT Id, Number__c FROM CCE_Unit_Code_Generator__c WHERE Type__c =: recordType LIMIT 1];  
            for(CCE_Unit_Code_Generator__c codeGen : codeGenList){
                response.recordId = codeGen.Id;
                response.recordNumber = Integer.valueOf(codeGen.Number__c) + 1;                
                num = codeGen.Number__c;                
            }
            codePrefix = 'EXCU'; 
            codeGenerated = getCode(codePrefix, num);    
            response.recordCode = codeGenerated;
        }


        if(recordType == 'Group_Coaching'){  
            List<CCE_Coaching_Code_Generator__c> codeGenList = [SELECT Id, Number__c FROM CCE_Coaching_Code_Generator__c WHERE Type__c =: recordType LIMIT 1];  
            for(CCE_Coaching_Code_Generator__c codeGen : codeGenList){
                response.recordId = codeGen.Id;
                response.recordNumber = Integer.valueOf(codeGen.Number__c) + 1;                
                num = codeGen.Number__c;                
            }
            codePrefix = 'EXCG'; 
            codeGenerated = getCode(codePrefix, num);    
            response.recordCode = codeGenerated;
        } 

        if(recordType == 'Diagnostic_Tool'){  
            List<CCE_Diagnostic_Tool_Code_Generator__c> codeGenList = [SELECT Id, Number__c FROM CCE_Diagnostic_Tool_Code_Generator__c WHERE Type__c =: recordType LIMIT 1];  
            for(CCE_Diagnostic_Tool_Code_Generator__c codeGen : codeGenList){
                response.recordId = codeGen.Id;
                response.recordNumber = Integer.valueOf(codeGen.Number__c) + 1;                
                num = codeGen.Number__c;                
            }
            codePrefix = 'EXCD'; 
            codeGenerated = getCode(codePrefix, num);    
            response.recordCode = codeGenerated;
        }

        if(recordType == 'Individual_Coaching'){  
            List<CCE_Individual_Coaching_Code_Generator__c> codeGenList = [SELECT Id, Number__c FROM CCE_Individual_Coaching_Code_Generator__c WHERE Type__c =: recordType LIMIT 1];  
            for(CCE_Individual_Coaching_Code_Generator__c codeGen : codeGenList){
                response.recordId = codeGen.Id;
                response.recordNumber = Integer.valueOf(codeGen.Number__c) + 1;                
                num = codeGen.Number__c;                
            }
            codePrefix = 'EXCI'; 
            codeGenerated = getCode(codePrefix, num);    
            response.recordCode = codeGenerated;
        } 

        if(recordType == 'Program_Without_Pathway') {
            if(prodSpecsRecordType != 'OPE'){
                List<CCE_PWP_Code_Generator__c> codeGenList = [SELECT Id, Number__c FROM CCE_PWP_Code_Generator__c WHERE Type__c =: recordType LIMIT 1];
                for(CCE_PWP_Code_Generator__c codeGen : codeGenList) {
                    response.recordId = codeGen.Id;
                    response.recordNumber = Integer.valueOf(codeGen.Number__c) + 1;
                    num = codeGen.Number__c;
                }
                codePrefix = 'EXCPWP';
            } else {
                List<PWP_Code_Generator__c> codeGenList = [SELECT Id, Number__c FROM PWP_Code_Generator__c WHERE Type__c =: recordType LIMIT 1];
                for(PWP_Code_Generator__c codeGen : codeGenList) {
                    response.recordId = codeGen.Id;
                    response.recordNumber = Integer.valueOf(codeGen.Number__c) + 1;
                    num = codeGen.Number__c;
                }
                codePrefix = 'EXOPWP';
            }
            codeGenerated = getCode(codePrefix, num);
            response.recordCode = codeGenerated;
        }

        return response;
    }

    @AuraEnabled
    public static CourseProgramDetails getDuplicateDetails(String recordCode, String recordType){
        CourseProgramDetails response = new CourseProgramDetails();
        if(recordType != 'Program'){
            List<hed__Course__c> courses = [SELECT Name, ProductRequestID__r.Name, ProductRequestID__r.Id,ProductRequestID__r.Product_Specification__r.RecordType.DeveloperName  FROM hed__Course__c 
            WHERE Course_Code__c =: recordCode LIMIT 1];
            for(hed__Course__c course : courses){
                response.recordProdReqId = course.ProductRequestID__r.Id;       
                response.recordProdReqName = course.ProductRequestID__r.Name;
                response.recordProgCourseName = course.Name;                
            }
        }else{
            List<hed__Program_Plan__c> programs = [SELECT Name, Product_Request__r.Name, Product_Request__r.Id,  Product_Request__r.Product_Specification__r.RecordType.DeveloperName FROM hed__Program_Plan__c 
            WHERE Code__c =: recordCode LIMIT 1];
            for(hed__Program_Plan__c program : programs){
                response.recordProdReqId = program.Product_Request__r.Id;
                response.recordProdReqName = program.Product_Request__r.Name;
                response.recordProgCourseName = program.Name;    
            }
        }
        return response;
    }
    
    @AuraEnabled
    public static String updateCodeGenerator(String recordType, String recordId, Integer recordNumber, String recordCode, String prodSpecsRecordType){
        
        String response = '';
        if(recordType == 'Activity'){
            if(prodSpecsRecordType != 'OPE'){
              
                List<CCE_Activity_Code_Generator__c> codeGenList = new List<CCE_Activity_Code_Generator__c>();
                codeGenList.add(new CCE_Activity_Code_Generator__c(
                    Id = recordId,
                    Number__c = recordNumber,
                    Name = recordCode
                ));
                update codeGenList;
            }else{
                List<Activity_Code_Generator__c> codeGenList = new List<Activity_Code_Generator__c>();
                codeGenList.add(new Activity_Code_Generator__c(
                    Id = recordId,
                    Number__c = recordNumber,
                    Name = recordCode
                ));
                update codeGenList;
            }
        }

        if(recordType == 'Module'){
            if(prodSpecsRecordType != 'OPE'){
                List<CCE_Module_Code_Generator__c> codeGenList = new List<CCE_Module_Code_Generator__c>();
                codeGenList.add(new CCE_Module_Code_Generator__c(
                    Id = recordId, 
                    Number__c = recordNumber,
                    Name = recordCode
                ));
                update codeGenList;

            }else{

                List<Module_Code_Generator__c> codeGenList = new List<Module_Code_Generator__c>();
                codeGenList.add(new Module_Code_Generator__c(
                    Id = recordId, 
                    Number__c = recordNumber,
                    Name = recordCode
                ));
                update codeGenList;

            }
        }

        if(recordType == 'Short_Course'){
            if(prodSpecsRecordType != 'OPE'){
                List<CCE_Short_Course_Code_Generator__c> codeGenList = new List<CCE_Short_Course_Code_Generator__c>();
                codeGenList.add(new CCE_Short_Course_Code_Generator__c(
                    Id = recordId, 
                    Number__c = recordNumber,
                    Name = recordCode
                ));
                update codeGenList;

            }else{
                List<Short_Course_Code_Generator__c> codeGenList = new List<Short_Course_Code_Generator__c>();
                codeGenList.add(new Short_Course_Code_Generator__c(
                    Id = recordId, 
                    Number__c = recordNumber,
                    Name = recordCode
                ));
                update codeGenList;
            }
           
        }

        if(recordType == 'Program'){
            if(prodSpecsRecordType != 'OPE'){
                List<CCE_Program_Code_Generator__c> codeGenList = new List<CCE_Program_Code_Generator__c>();
                    codeGenList.add(new CCE_Program_Code_Generator__c(
                    Id = recordId, 
                    Number__c = recordNumber,
                    Name = recordCode
                ));
                update codeGenList;
            }else{
                List<Program_Code_Generator__c> codeGenList = new List<Program_Code_Generator__c>();
                codeGenList.add(new Program_Code_Generator__c(
                    Id = recordId, 
                    Number__c = recordNumber,
                    Name = recordCode
                ));
                update codeGenList;
            }
        }

        if(recordType == 'Unit'){
            List<CCE_Unit_Code_Generator__c> codeGenList = new List<CCE_Unit_Code_Generator__c>();
            codeGenList.add(new CCE_Unit_Code_Generator__c(
                Id = recordId, 
                Number__c = recordNumber,
                Name = recordCode
            ));
            update codeGenList;
        }  

        if(recordType == 'Group_Coaching'){
            List<CCE_Coaching_Code_Generator__c> codeGenList = new List<CCE_Coaching_Code_Generator__c>();
            codeGenList.add(new CCE_Coaching_Code_Generator__c(
                Id = recordId, 
                Number__c = recordNumber,
                Name = recordCode
            ));
            update codeGenList;
        }

        if(recordType == 'Diagnostic_Tool'){
            List<CCE_Diagnostic_Tool_Code_Generator__c> codeGenList = new List<CCE_Diagnostic_Tool_Code_Generator__c>();
            codeGenList.add(new CCE_Diagnostic_Tool_Code_Generator__c(
                Id = recordId, 
                Number__c = recordNumber,
                Name = recordCode
            ));
            update codeGenList;
        }
    
        if(recordType == 'Individual_Coaching'){
            List<CCE_Individual_Coaching_Code_Generator__c> codeGenList = new List<CCE_Individual_Coaching_Code_Generator__c>();
            codeGenList.add(new CCE_Individual_Coaching_Code_Generator__c(
                Id = recordId, 
                Number__c = recordNumber,
                Name = recordCode
            ));
            update codeGenList;
        }
        
        if(recordType == 'Program_Without_Pathway') {
            if(prodSpecsRecordType != 'OPE') {
                List<CCE_PWP_Code_Generator__c> codeGenList = new List<CCE_PWP_Code_Generator__c>();
                codeGenList.add(new CCE_PWP_Code_Generator__c(
                    Id = recordId,
                    Number__c = recordNumber,
                    Name = recordCode
                ));
                update codeGenList;
            } else {
                List<PWP_Code_Generator__c> codeGenList = new List<PWP_Code_Generator__c>();
                codeGenList.add(new PWP_Code_Generator__c(
                    Id = recordId,
                    Number__c = recordNumber,
                    Name = recordCode
                ));
                update codeGenList;
            }
        }

        response = 'Success';

        return response;
    }

    private static String getCode(String codePrefix, Decimal num){
        String numStr = '';
        Integer latestNum = Integer.valueOf(num);
        if(latestNum < 0){
            numStr = String.valueOf(1).leftPad(4,'0');
        }else{
            if(latestNum < 10000){  
                numStr = String.valueOf(latestNum + 1).leftPad(4,'0');    
            }else{
                numStr = String.valueOf(latestNum + 1);
            }   
        }
        return codePrefix + numStr; 
        
    }

    public class CourseProgramDetails{
        @AuraEnabled
        public String recordId;
        @AuraEnabled
        public String recordType;
        @AuraEnabled
        public String recordCode;
        @AuraEnabled
        public Decimal recordNumber;
        @AuraEnabled
        public String recordProgCourseName;
        @AuraEnabled
        public String recordProdReqName;
        @AuraEnabled
        public String recordProdReqId;
        @AuraEnabled
        public String productSpecsRT;
    } 
}