src/core-crm/objects/Cart_Payment__c/Cart_Payment__c.object-meta.xml
<CustomObject>
    <label>Cart Payment</label>
    <nameField>
        <label>Cart Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cart Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Cart_Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <description>Payment status returned from QUTPay</description>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled Payment</fullName>
            </value>
            <value>
                <fullName>Validation Failure</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/classes/CartPaymentTriggerHandler.cls
/**
 * @description Trigger handler for cart payment
 * @see CartPaymentTrigger
 *
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary                                                     |
      |--------------------------------|-----------------------|------------------------|--------------------------------------------------------------------|
      | roy.nino.s.regala              | June 24, 2022         | DEPP-3252              | Created file                                                       |
 */
public without sharing class CartPaymentTriggerHandler implements Disableable, AfterUpdate{



  /**
   * @description update counter for Cart Item
   * @param newItems - List of CartPayment.Trigger.new
   * @param oldItems - Map of CartPayment.Trigger.old
   */
  public void afterUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {

    Set<Id> approvedOrInvoiceCp = new Set<Id>();
    Map<Id, Cart_Payment__c> oldMap = (Map<Id,Cart_Payment__c>) oldItems;
    Map<Id, Cart_Payment__c> newMap = (Map<Id,Cart_Payment__c>) newItems;

    //loop through cartpayments and get ids that needs to be processed
    for(Id cartPayId: newItems.keySet()){
        //if payment status is updated
        // payment status is null -> Approved or Invoiced
        // payment status is Invoiced -> Approved
        if( newMap.get(cartPayId).Payment_Status__c != oldMap.get(cartPayId).Payment_Status__c && 
            ((   oldMap.get(cartPayId).Payment_Status__c == null && 
            (   newMap.get(cartPayId).Payment_Status__c == 'Approved' || 
                newMap.get(cartPayId).Payment_Status__c == 'Invoiced')) ||
                (   oldMap.get(cartPayId).Payment_Status__c == 'Invoiced' &&
                    newMap.get(cartPayId).Payment_Status__c == 'Approved'
                ))
        ){
            approvedOrInvoiceCp.add(cartPayId);
        }
    }
    if(!approvedOrInvoiceCp.isEmpty()){
        CartPaymentTriggerHelper.upsertCourseConnection(approvedOrInvoiceCp,newMap);
    }

  }

    
  /**
   * @description indicates it the trigger is disabled
   * @return disabled bypass
   */
  public Boolean isDisabled() {
    final TriggerBypassStrategy bypass = new TriggerBypassStrategy();
    return bypass.isDisabled();
  }

}