src/core-crm/objects/Associated_Products__c/Associated_Products__c.object-meta.xml
<CustomObject>
    <label>Associated Products</label>
    <nameField>
        <displayFormat>AP - {000000}</displayFormat>
        <label>Associated Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/Associated_Products__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Determine if the Associated Product is active or not.</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Associated_Products__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Associated Products</relationshipLabel>
    <relationshipName>Associated_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Associated_Products__c/fields/Product_Request__c.field-meta.xml
<CustomField>
    <fullName>Product_Request__c</fullName>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Associated Products</relationshipLabel>
    <relationshipName>Associated_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/core-crm/objects/BuyerGroup/fields/Product_Request__c.field-meta.xml
<CustomField>
    <fullName>Product_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the parent Standing Offer Arrangement Product request</description>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Buyer Groups</relationshipLabel>
    <relationshipName>Buyer_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/CartItem/fields/Program_Offering__c.field-meta.xml
<CustomField>
    <fullName>Program_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The associated program offering that’s added to the cart</description>
    <label>Program Offering</label>
    <referenceTo>Program_Offering__c</referenceTo>
    <relationshipLabel>Cart Items</relationshipLabel>
    <relationshipName>Cart_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course__c/hed__Course__c.object-meta.xml
<CustomObject>
    <description>Academic Course offered by a Department or School, for example, English 101 or Ancient History.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course__c/fields/ProductRequestID__c.field-meta.xml
<CustomField>
    <fullName>ProductRequestID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/hed__Course_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Represents a connection to a Course Offering.</description>
    <label>Course Connection</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Course Connection ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Enrollment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Cost of Product</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/Cart_Item__c.field-meta.xml
<CustomField>
    <fullName>Cart_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cart Item</label>
    <referenceTo>CartItem</referenceTo>
    <relationshipLabel>Course Connections</relationshipLabel>
    <relationshipName>Course_Connections</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The course that the student is enrolment is related to</description>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Course Connections</relationshipLabel>
    <relationshipName>Course_Connections</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/Course_Name__c.field-meta.xml
<CustomField>
    <fullName>Course_Name__c</fullName>
    <description>Course/Program Plan Name</description>
    <formula>IF(ISBLANK( hed__Course_Offering__r.hed__Course__r.Name ),Program_Offering__r.hed_Program_Plan__r.Name, hed__Course_Offering__r.hed__Course__r.Name)</formula>
    <label>Course Name</label>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/hed__Contact__c.field-meta.xml
<CustomField>
    <fullName>hed__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student or faculty member participating in this Course Offering.</description>
    <inlineHelpText>The student or faculty member participating in this Course Offering.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Connections</relationshipLabel>
    <relationshipName>Student_Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/hed__Course_Offering__c.field-meta.xml
<CustomField>
    <fullName>hed__Course_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Course Offering the student or faculty member is involved with.</description>
    <inlineHelpText>The Course Offering the student or faculty member is involved with.</inlineHelpText>
    <label>Course Offering ID</label>
    <referenceTo>hed__Course_Offering__c</referenceTo>
    <relationshipLabel>Course Connection</relationshipLabel>
    <relationshipName>Course_Enrollment</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/hed__Status__c.field-meta.xml
<CustomField>
    <fullName>hed__Status__c</fullName>
    <description>Indicates whether this is a current or former Course Connection.</description>
    <inlineHelpText>Indicates whether this is a current or former Course Connection.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This will be used to deactivate facilitators.</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/Program_Offering__c.field-meta.xml
<CustomField>
    <fullName>Program_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Offering</label>
    <referenceTo>Program_Offering__c</referenceTo>
    <relationshipLabel>Course Connections</relationshipLabel>
    <relationshipName>Course_Connections</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <description>A Student Course Connection</description>
    <label>Student</label>
</RecordType>

src/core-crm/objects/hed__Course_Enrollment__c/recordTypes/Student_Program.recordType-meta.xml
<RecordType>
    <fullName>Student_Program</fullName>
    <active>true</active>
    <description>Learners enroled in a Prescribed Program</description>
    <label>Student - Program</label>
</RecordType>

src/core-crm/objects/hed__Course_Offering__c/hed__Course_Offering__c.object-meta.xml
<CustomObject>
    <description>Joins Courses and Terms to contain information related to a single occurrence of a Course.</description>
    <label>Course Offering</label>
    <nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Course__c.field-meta.xml
<CustomField>
    <fullName>hed__Course__c</fullName>
    <description>Lookup to the Course record that this Course Offering is associated with.</description>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>
 

src/core-crm/objects/hed__Course_Offering__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This will be used to deactivate Offering.</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/hed__Program_Plan__c/hed__Program_Plan__c.object-meta.xml
<CustomObject>
    <description>Links Courses to an Academic Program to create a path for students to follow. An Academic Program can list multiple Courses, and a Course can be associated with multiple Academic Programs.</description>
    <label>Program Plan</label>
    <nameField>
        <label>Program Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Program_Plan__c/fields/hed__Status__c.field-meta.xml
<CustomField>
    <fullName>hed__Status__c</fullName>
    <description>Select &quot;Current&quot; if this Program Plan has students enrolled in it, or is eligible for students to enroll. Otherwise, select &quot;Archived.&quot;</description>
    <inlineHelpText>Select &quot;Current&quot; if this Program Plan has students enrolled in it, or is eligible for students to enroll. Otherwise, select &quot;Archived.&quot;</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Current</fullName>
                <default>true</default>
                <label>Current</label>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>Planned</fullName>
            </value>
            <value>
                <fullName>Phasing Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Program_Plan__c/fields/Product_Request__c.field-meta.xml
<CustomField>
    <fullName>Product_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the related Product Request record of the Program Plan.</description>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Product2/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Product2/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Plan</label>
    <referenceTo>hed__Program_Plan__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Program_Offering__c/Program_Offering__c.object-meta.xml
<CustomObject>
    <label>Program Offering</label>
    <nameField>
        <label>Program Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/Program_Offering__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This will be used to deactivate Offering.</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Related_Product_Request__c/Related_Product_Request__c.object-meta.xml
<CustomObject>
    <label>Related Product Request</label>
    <nameField>
        <label>Related Product Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Related Product Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Related_Product_Request__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Related Product Requests</relationshipLabel>
    <relationshipName>Course</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Related_Product_Request__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Related Product Requests</relationshipLabel>
    <relationshipName>Program</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/classes/CceManageRegistrationSectionCtrl.cls
/**
 * @description Controller Class for cceManageRegistrationSection LWC
 * @see ../lwc/cceManageRegistrationSection
 * 
 * @author Accenture
 * 
 * @history
 *  | Developer                 | Date                  | JIRA                 | Change Summary                  |
    |---------------------------|-----------------------|----------------------|---------------------------------|
    | roy.nino.s.regala         | Aug 01, 2022          | DEPP-2498            | Created file                    | 
    | kathy.cornejo             | Sept 28, 2022         | DEPP-4460            | Fixed Pricing for CCE           | 
*/
public without sharing class CceManageRegistrationSectionCtrl {

    /**
     * @description retrieves learners related to the child PRs
    * @param prodReqId - Record ID from record page
    * @return List of LearnerDetails
    */
    @AuraEnabled(cacheable=true)
    public static List<LearnerDetails> getLearnerDetails(String productReqId){
        Set<Id> childProdRequestIds = new Set<Id>();
        Set<String> pbEntryIds = new Set<String>();
        Set<String> pbIds = new Set<String>();
        List<LearnerDetails> learnerDetailsList = new List<LearnerDetails>();
        List<BuyerGroupPriceBook> buyerGroupPBList = new List<BuyerGroupPriceBook>([
            SELECT Id, Pricebook2Id FROM BuyerGroupPriceBook 
            WHERE BuyerGroup.Product_Request__c =: productReqId
        ]);

        for(BuyerGroupPriceBook bgPb:buyerGroupPBList){
            pbIds.add(bgPb.Pricebook2Id);
        }

        for(PriceBookEntry pbE: [SELECT Id FROM PricebookEntry WHERE Pricebook2Id IN:pbIds]){
            pbEntryIds.add(pbE.Id);
        }


        for(Related_Product_Request__c rpr: [   SELECT Course__c
                                                FROM Related_Product_Request__c
                                                WHERE Program__c =: productReqId]){
                                                childProdRequestIds.add(rpr.Course__c);
                                            }
        for(Associated_Products__c assocProd:[  SELECT Id,Product__r.Course__r.ProductRequestID__c, 
                                                Product__r.Program_Plan__r.Product_Request__c, IsActive__c
                                                FROM Associated_Products__c 
                                                WHERE Product_Request__c =: productReqId]){
                                                    if( assocProd.Product__c != null &&
                                                        assocProd.Product__r.Course__c != null &&
                                                        assocProd.Product__r.Course__r.ProductRequestID__c != null){
                                                            childProdRequestIds.add(assocProd.Product__r.Course__r.ProductRequestID__c);
                                                    }else if(
                                                        assocProd.Product__c != null &&
                                                        assocProd.Product__r.Program_Plan__c != null &&
                                                        assocProd.Product__r.Program_Plan__r.Product_Request__c != null){
                                                            childProdRequestIds.add(assocProd.Product__r.Program_Plan__r.Product_Request__c);
                                                    }
                                                }

        List<hed__Course_Enrollment__c> learnerList = new List<hed__Course_Enrollment__c>(
                [
                    SELECT Id, CreatedDate, Course_Name__c, hed__Contact__r.Name, Amount__c, Cart_Item__r.TotalPrice, hed__Status__c
                    FROM hed__Course_Enrollment__c
                    WHERE (hed__Course_Offering__r.hed__Course__r.ProductRequestID__c IN: childProdRequestIds 
                    OR Program_Offering__r.hed_Program_Plan__r.Product_Request__c IN: childProdRequestIds) 
                    AND ((RecordType.DeveloperName = 'Student' 
                    AND Program_Offering__c = null) 
                    OR (RecordType.DeveloperName = 'Student_Program' 
                    AND hed__Course_Offering__c = null)) 
                    AND Cart_Item__r.Pricebook_Entry_ID__c IN: pbEntryIds
                ]
        );

        for(hed__Course_Enrollment__c courseCon: learnerList){
            LearnerDetails learnerDetails = new LearnerDetails();

            learnerDetails.id = courseCon.Id;
            learnerDetails.status = courseCon.hed__Status__c;
            learnerDetails.contactName = courseCon.hed__Contact__r.Name;
            learnerDetails.productName = courseCon.Course_Name__c;
            learnerDetails.registrationDate = courseCon.CreatedDate;
            if (courseCon.Cart_Item__c != null && courseCon.Cart_Item__r.TotalPrice != null){
                learnerDetails.price = coursecon.Cart_Item__r.TotalPrice;
            }
            else {
                learnerDetails.price = courseCon.Amount__c;
            }

            learnerDetailsList.add(learnerDetails);
        }                                        

        return learnerDetailsList;
    }

    /**
     * @description updates learners
    * @param prodReqId - Record ID from record page
    * @return List of LearnerDetails
    */
    @AuraEnabled
    public static void updateLearners(List<hed__Course_Enrollment__c> learners){
        if(!learners.isEmpty()){
            update learners;
        }
    }

    /**
    * @description Wrapper class that holds data to be displayed
    */
    public class LearnerDetails{
         @AuraEnabled
         public String id;
         @AuraEnabled
         public String status;
         @AuraEnabled
         public String productName;
         @AuraEnabled
         public Datetime registrationDate;
         @AuraEnabled
         public Decimal price;
         @AuraEnabled
         public String contactName;
    }
}