src/core-crm/objects/Associated_Products__c/Associated_Products__c.object-meta.xml
<CustomObject>
    <label>Associated Products</label>
    <nameField>
        <displayFormat>AP - {000000}</displayFormat>
        <label>Associated Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/Associated_Products__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Determine if the Associated Product is active or not.</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/classes/AssociatedProductsService.cls
/**
 * @description Service class for associated products object
 * 
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | roy.nino.s.regala              | April 25, 2023        |DEPP-5567               | Created file
 */
public with sharing class AssociatedProductsService {
    public static List<Database.SaveResult> deactivateByProductRequest(
        Set<Id> parentProductRequestIds
    ) {
        List<Database.SaveResult> databaseResult;
        List<Associated_Products__c> activeAssociatedProducts = AssociatedProductsDAO.newInstance()
            .getActiveAssociatedProductsByProductRequest(parentProductRequestIds);

        for (Associated_Products__c associatedProduct : activeAssociatedProducts) {
            associatedProduct.IsActive__c = false;
        }

        if (!activeAssociatedProducts.isEmpty()) {
            databaseResult = AssociatedProductsDAO.newInstance()
                .updateRecords(activeAssociatedProducts, false, AccessLevel.USER_MODE);
        }

        return databaseResult;
    }

    public class AssociatedProductsServiceException extends Exception {
    }
}