src/core-crm/objects/Financial_Split__c/Financial_Split__c.object-meta.xml
<CustomObject>
    <label>Financial Split</label>
    <nameField>
        <displayFormat>FS-{00000}</displayFormat>
        <label>Financial Split Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Splits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Financial_Split__c/fields/Account_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Code__c</fullName>
    <label>Account Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Financial_Split__c/fields/Account_GL_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_GL_Code__c</fullName>
    <label>Account GL Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Financial_Split__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Financial_Split__c/fields/Funding_Body__c.field-meta.xml
<CustomField>
    <fullName>Funding_Body__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Funding Body Account record.</description>
    <label>Funding Body</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Splits (Funding Body)</relationshipLabel>
    <relationshipName>Financial_Splits1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Financial_Split__c/fields/Funding_Body_Contribution_Amount__c.field-meta.xml
<CustomField>
    <fullName>Funding_Body_Contribution_Amount__c</fullName>
    <description>The amount being contributed to an Opportunity or an Opportunity Outcome by a Funding Body.</description>
    <label>Funding Body Contribution Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

src/core-crm/objects/Financial_Split__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Determines if the Financial Split record is currently active.</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Financial_Split__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Provides a lookup to the Opportunity Object.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Financial Splits</relationshipLabel>
    <relationshipName>Financial_Splits</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Financial_Split__c/fields/Participating_School_Name__c.field-meta.xml
<CustomField>
    <fullName>Participating_School_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participating School Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3 OR 4</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>University_Department</value>
        </filterItems>
        <filterItems>
            <field>Account.Organization_Unit_Level__c</field>
            <operation>equals</operation>
            <value>3</value>
        </filterItems>
        <filterItems>
            <field>Account.Name</field>
            <operation>equals</operation>
            <value>QUTeX Products</value>
        </filterItems>
        <filterItems>
            <field>Account.Name</field>
            <operation>equals</operation>
            <value>QUT GSB &amp; QUTeX</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Splits</relationshipLabel>
    <relationshipName>Financial_Splits</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Financial_Split__c/fields/Percentage_split__c.field-meta.xml
<CustomField>
    <fullName>Percentage_split__c</fullName>
    <label>Percentage Split</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

src/core-crm/objects/Financial_Split__c/fields/Revenue_Split_Account__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Split_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Account that is the recipient of the revenue split.</description>
    <label>Revenue Split Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Splits (Revenue Split Account)</relationshipLabel>
    <relationshipName>Financial_Splits_Revenue_Split_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Financial_Split__c/fields/Revenue_Split_Contact__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Split_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Contact that is the recipient of the revenue split.</description>
    <label>Revenue Split Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Financial Splits</relationshipLabel>
    <relationshipName>Financial_Splits_Revenue_Split_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Financial_Split__c/recordTypes/Opportunity_Funding_Body.recordType-meta.xml
<RecordType>
    <fullName>Opportunity_Funding_Body</fullName>
    <active>true</active>
    <description>Capture the partner funding contribution details for an Opportunity.</description>
    <label>Opportunity Funding Body</label>
</RecordType>

src/core-crm/objects/Financial_Split__c/recordTypes/Opportunity_Outcome_Account_Revenue_Financial_Split.recordType-meta.xml
<RecordType>
    <fullName>Opportunity_Outcome_Account_Revenue_Financial_Split</fullName>
    <active>true</active>
    <description>Capture University Department revenue split percentage for an Opportunity Outcome.</description>
    <label>Opportunity Outcome Account Revenue Financial Split</label>
</RecordType>

src/core-crm/objects/Financial_Split__c/recordTypes/Opportunity_Outcome_Contact_Revenue_Financial_Split.recordType-meta.xml
<RecordType>
    <fullName>Opportunity_Outcome_Contact_Revenue_Financial_Split</fullName>
    <active>true</active>
    <description>Capture revenue split percentage of an Individual for an Opportunity Outcome.</description>
    <label>Opportunity Outcome Contact Revenue Financial Split</label>
</RecordType>

src/core-crm/objects/Financial_Split__c/recordTypes/Opportunity_Outcome_Funding_Body.recordType-meta.xml
<RecordType>
    <fullName>Opportunity_Outcome_Funding_Body</fullName>
    <active>true</active>
    <description>Capture the partner funding contribution details for a Project.</description>
    <label>Opportunity Outcome Funding Body</label>
</RecordType>

src/core-crm/classes/FinancialSplitsDAO.cls
/**
 * @description DAO Class for Financial Split Object. Contains soql and constants related to the Account object.
 *
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary                                             |
 *    |--------------------------------|-----------------------|------------------------|------------------------------------------------------------|
 *    | mark.j.mahilum                 | June 01, 2023         | DEPP-5687              | Created File                                               |
 *    | kenneth.f.alsay                | June 14, 2023         | DEPP-5434              | Added all other record types                               |
 *    | ryan.j.a.dela.cruz             | July 18, 2023         | DEPP-5457/DEPP-5468    | Added getActiveOpportunityFinancialSplitsRecords method    |
 */
public inherited sharing class FinancialSplitsDAO extends DmlBase implements IFinancialSplitsDAO {
    public static final String FINANCIAL_SPLIT_API_NAME = Financial_Split__c.SObjectType.getDescribe(
            SObjectDescribeOptions.DEFERRED
        )
        .getLocalName();
    public static final String FINANCIAL_SPLIT_FIELDS =
        'Id,Account_Code__c,Account_GL_Code__c,Account_Name__c,CreatedDate,RecordTypeId,' +
        'IsActive__c,Participating_School_Name__c,Participating_School_Name__r.Name,' +
        'Percentage_split__c';
    public static final String RECORDTYPE_DEVELOPERNAME = 'Course Financial Split';
    public static final String COURSE_FINANCIAL_SPLIT_RECORDTYPEID = Schema.SObjectType.Financial_Split__c.getRecordTypeInfosByName()
        .get(RECORDTYPE_DEVELOPERNAME)
        .getRecordTypeId();
    public static final String OPPORTUNITY_FUNDING_BODY_RECORDTYPEID = Schema.SObjectType.Financial_Split__c.getRecordTypeInfosByDeveloperName()
        .get('Opportunity_Funding_Body')
        .getRecordTypeId();
    public static final String OPPORTUNITY_OUTCOME_FUNDING_BODY_RECORDTYPEID = Schema.SObjectType.Financial_Split__c.getRecordTypeInfosByDeveloperName()
        .get('Opportunity_Outcome_Funding_Body')
        .getRecordTypeId();
    public static final String OPPORTUNITY_OUTCOME_CONTACT_REVENUE_FINANCIAL_SPLIT_RECORDTYPEID = Schema.SObjectType.Financial_Split__c.getRecordTypeInfosByDeveloperName()
        .get('Opportunity_Outcome_Contact_Revenue_Financial_Split')
        .getRecordTypeId();
    public static final String OPPORTUNITY_OUTCOME_ACCOUNT_REVENUE_FINANCIAL_SPLIT_RECORDTYPEID = Schema.SObjectType.Financial_Split__c.getRecordTypeInfosByDeveloperName()
        .get('Opportunity_Outcome_Account_Revenue_Financial_Split')
        .getRecordTypeId();
    public static final String RECORDTYPEID = 'RecordTypeId';

    public static IFinancialSplitsDAO newInstance() {
        return (IFinancialSplitsDAO) ImplementationSelector.DAO.newInstance(
            Financial_Split__c.SObjectType
        );
    }

    public Schema.SObjectType getSObjectType() {
        return Financial_Split__c.SObjectType;
    }

    public List<Financial_Split__c> getFinancialSplitsRecords(
        String relatedParentField,
        Id relatedParentId
    ) {
        return Database.query(
            'SELECT ' +
                String.escapeSingleQuotes(FINANCIAL_SPLIT_FIELDS) +
                ' FROM ' +
                String.escapeSingleQuotes(FINANCIAL_SPLIT_API_NAME) +
                ' WHERE ' +
                String.escapeSingleQuotes(relatedParentField) +
                ' = \'' +
                String.escapeSingleQuotes(relatedParentId) +
                '\' AND ' +
                String.escapeSingleQuotes(RECORDTYPEID) +
                ' = \'' +
                String.escapeSingleQuotes(COURSE_FINANCIAL_SPLIT_RECORDTYPEID) +
                '\' ORDER BY CreatedDate ASC'
        );
    }

    public List<Financial_Split__c> getActiveOpportunityFinancialSplitsRecords(
        Set<Id> opportunityIds
    ) {
        return [ // NO PMD
            SELECT Id, Opportunity__c, Funding_Body__c, Participating_School_Name__c, Percentage_split__c, Revenue_Split_Account__c, Revenue_Split_Contact__c, Funding_Body_Contribution_Amount__c
            FROM Financial_Split__c
            WHERE Opportunity__c IN :opportunityIds AND isActive__c = true
            WITH USER_MODE
        ];
    }
}