src/core-crm/objects/et4ae5__IndividualEmailResult__c/et4ae5__IndividualEmailResult__c.object-meta.xml
<CustomObject>
    <label>Individual Email Result</label>
    <nameField>
        <label>Email Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individual Email Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/et4ae5__IndividualEmailResult__c/fields/et4ae5__Contact__c.field-meta.xml
<CustomField>
    <fullName>et4ae5__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Individual Email Results</relationshipLabel>
    <relationshipName>IndividualEmailResults</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/et4ae5__IndividualEmailResult__c/fields/et4ae5__Lead__c.field-meta.xml
<CustomField>
    <fullName>et4ae5__Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Individual Email Results</relationshipLabel>
    <relationshipName>IndividualEmailResults</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/classes/IndividualEmailResultsDAOMock.cls
/**
 * @description Mock DAO Class for et4ae5__IndividualEmailResult__c Object
 *
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary                              |
 *    |--------------------------------|-----------------------|------------------------|---------------------------------------------|
 *    | eccarius.munoz                 | October 26, 2023      | DEPP-5866              | created file                                |
 */

@isTest
public inherited sharing class IndividualEmailResultsDAOMock extends DmlBaseMock implements IIndividualEmailResultsDAO{
    public Map<Id, et4ae5__IndividualEmailResult__c> indivEmailMap;

    public IndividualEmailResultsDAOMock() {
        super(new Map<Id, et4ae5__IndividualEmailResult__c>(), Schema.et4ae5__IndividualEmailResult__c.SObjectType);
        this.indivEmailMap = (Map<Id, et4ae5__IndividualEmailResult__c>) super.records;
    }

    public Schema.SObjectType getSObjectType() {
        return et4ae5__IndividualEmailResult__c.SObjectType;
    }

    public List<et4ae5__IndividualEmailResult__c> getIndivEmailResultsByContactOrLeadIds(
        Set<Id> contactLeadIds,
        AccessLevel accessLevel
    ) {
        List<et4ae5__IndividualEmailResult__c> indivEmailList = new List<et4ae5__IndividualEmailResult__c>();

        for (et4ae5__IndividualEmailResult__c record : indivEmailMap.values()) {
            if (contactLeadIds.contains(record.et4ae5__Contact__c) || contactLeadIds.contains(record.et4ae5__Lead__c)) {
                indivEmailList.add(record);
            }
        }

        return indivEmailList;
    }

    public Database.QueryLocator queryLocatorGetIndivEmailResultsByContactOrLeadIds(
        Set<Id> recordIds
    ){
        return null;
    }
}