src/core-crm/objects/et4ae5__IndividualEmailResult__c/et4ae5__IndividualEmailResult__c.object-meta.xml
<CustomObject>
    <label>Individual Email Result</label>
    <nameField>
        <label>Email Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individual Email Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/et4ae5__IndividualEmailResult__c/fields/et4ae5__SendDefinition__c.field-meta.xml
<CustomField>
    <fullName>et4ae5__SendDefinition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The unique identifier of the email send. You may be asked to reference this number when calling Marketing Cloud support if the need arises.</inlineHelpText>
    <label>Send Definition</label>
    <referenceTo>et4ae5__SendDefinition__c</referenceTo>
    <relationshipLabel>Individual Email Results</relationshipLabel>
    <relationshipName>IndividualEmailResults</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/classes/IndividualEmailResultTriggerHandlerTest.cls
/**
 * @description Test Class for Lead Scoring
 * @see ..
 *
 * @author Accenture
 *
 * @history
 *
 *    | Developer                | Date                  | JIRA                   | Change Summary               |
      |--------------------------|-----------------------|------------------------|------------------------------|
      | w.li                     | June 15, 2022         | DEPP-1058              | Created file                 |
      | alexander.cadalin        | February 20, 2023     | PMD                    | ApexUnitTestClassShouldHaveAsserts
 */

@isTest
public without sharing class IndividualEmailResultTriggerHandlerTest {

    @isTest
    public static void testInsertIER() {
        Test.startTest();
        et4ae5__SendDefinition__c sendDefinition = new et4ae5__SendDefinition__c();
        insert sendDefinition;

        et4ae5__IndividualEmailResult__c individualEmailResult = new et4ae5__IndividualEmailResult__c();
        individualEmailResult.Name = 'Test';
        individualEmailResult.et4ae5__SendDefinition__c = sendDefinition.Id;
        Database.SaveResult saveResult =  Database.insert(individualEmailResult);
        Test.stopTest();
        System.assert(saveResult.isSuccess(), 'The record was not successfully inserted.');
    }

    @isTest
    public static void testUpdateIER() {
        et4ae5__SendDefinition__c sendDefinition = new et4ae5__SendDefinition__c();
        insert sendDefinition;

        et4ae5__IndividualEmailResult__c individualEmailResult = new et4ae5__IndividualEmailResult__c();
        individualEmailResult.Name = 'Test';
        individualEmailResult.et4ae5__SendDefinition__c = sendDefinition.Id;
        insert individualEmailResult;

        Test.startTest();
		List<et4ae5__IndividualEmailResult__c> IER = [SELECT Id FROM et4ae5__IndividualEmailResult__c];
        Database.SaveResult[] saveResultList = Database.update(IER);
        Test.stopTest();
        for(Database.SaveResult saveResult : saveResultList) {
            System.assert(saveResult.isSuccess(), 'A record was not successfully updated.');
        }
    }
}