src/core-crm/objects/Engagement_Opportunity__c/Engagement_Opportunity__c.object-meta.xml
<CustomObject>
    <description>Engagement Opportunity captures information for Alumni Engagement and Corporate Engagement business processes.</description>
    <label>Engagement Opportunity</label>
    <nameField>
        <displayFormat>EO-{000000}</displayFormat>
        <label>Engagement Opportunity Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/core-crm/objects/List__c/List__c.object-meta.xml
<CustomObject>
    <description>List supports information capture about a request to compile a list of Contacts for a defined business reason.</description>
    <label>List</label>
    <nameField>
        <displayFormat>LIST-{000000}</displayFormat>
        <label>List Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/List__c/fields/Engagement_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to an Engagement Opportunity.</description>
    <inlineHelpText>Engagement Opportunity associated with the List.</inlineHelpText>
    <label>Engagement Opportunity</label>
    <referenceTo>Engagement_Opportunity__c</referenceTo>
    <relationshipLabel>Lists</relationshipLabel>
    <relationshipName>Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/List_Member__c/List_Member__c.object-meta.xml
<CustomObject>
    <description>List Member contains information about the Contacts who have been included in a Contact List and details about the staff member who contributed to compiling the list of contacts.</description>
    <label>List Member</label>
    <nameField>
        <displayFormat>LM-{0000000}</displayFormat>
        <label>List Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>List Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/List_Member__c/fields/List__c.field-meta.xml
<CustomField>
    <fullName>List__c</fullName>
    <description>Lookup to the List record.</description>
    <label>List Id</label>
    <referenceTo>List__c</referenceTo>
    <relationshipLabel>List Members</relationshipLabel>
    <relationshipName>List_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/core-crm/objects/List_Member__c/fields/List_Member__c.field-meta.xml
<CustomField>
    <fullName>List_Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A Contact who has met the criteria to be included in the list.</description>
    <inlineHelpText>Contact who has met criteria for inclusion in the list.</inlineHelpText>
    <label>List Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>List Members</relationshipLabel>
    <relationshipName>List_Members</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/core-crm/classes/CustomHeaderDatatableCtrlTest.cls
/**
 * @description Test class for CustomHeaderDatatableCtrl
 *
 * @see CustomHeaderDatatableCtrl
 *
 * @author Accenture
 *
 * @history
 *    | Developer                           | Date                  | JIRA                 | Change Summary                                         |
      |-------------------------------------|-----------------------|----------------------|--------------------------------------------------------|
      | neil.s.h.lesidan@accenture.com      | December 20, 2023     | DEPP-6963            | Created file                                           |
*/
@isTest
public with sharing class CustomHeaderDatatableCtrlTest {
    @testSetup
    static void testSetup() {
        TestDataFactory.generateTestUsers(new List<String>{ 'QUT_IE_Partnership_Manager','QUT_Alumni_Engagement_Manager' });

        List<Contact> newContacts = TestDataFactory.createTestContactRecords(1);
        List<List__c> newListRecords = TestDataFactory.createListRecords(1);

        ListsDAO.newInstance().insertRecords(newListRecords, false, AccessLevel.USER_MODE);
        ContactsDAO.newInstance().insertRecords(newContacts, false, AccessLevel.USER_MODE);

        List<List_Member__c> newListMemberRecords = TestDataFactory.createListMemberRecords(1,newListRecords[0].id,newContacts[0].id);
        ListMembersDAO.newInstance().insertRecords(newListMemberRecords, false, AccessLevel.USER_MODE);

        System.runAs(TestDataFactory.getQUTAlumniEngagementManager()) {
            List<Engagement_Opportunity__c> engagementOppList = TestDataFactory.createTestEngagementOpportunityRecords(1);
            for(Engagement_Opportunity__c enOpp : engagementOppList){
                enOpp.RecordTypeId = EngagementOpportunitiesDAO.ALUMNI_ENGAGEMENT_RECTYPE_ID;
            }
            EngagementOpportunitiesDAO.newInstance().insertRecords(engagementOppList, false, AccessLevel.USER_MODE);

            Engagement_Opportunity__c enOppRec = EngagementOpportunitiesDAO.newInstance().getEngagementOpportunityRecords(1,AccessLevel.USER_MODE).iterator().next();
            List<List__c> listRecords = TestDataFactory.createListRecords(1);
            for(List__c rec : listRecords){
                rec.Engagement_Opportunity__c = enOppRec.Id;
            }
            
            ListsDAO.newInstance().insertRecords(newListRecords, false, AccessLevel.USER_MODE);
        }
    }

    @isTest
    static void getListMembersTest(){
        Contact con = ContactsDAO.getPersonContactsWithLimit(1).iterator().next();
        List__c listRec = ListsDAO.newInstance().getListRecords(1).iterator().next();
        System.runAs(TestDataFactory.getQUTIEPartnershipManager()) {
            List<List_Member__c> newListMemberRecords = TestDataFactory.createListMemberRecords(10,con.Id,listRec.Id);
            Test.startTest();

            Database.SaveResult[] srList = ListMembersDAO.newInstance().insertRecords(newListMemberRecords, false, AccessLevel.USER_MODE);

            List<List_Member__c> listMemberRecord = CustomHeaderDatatableCtrl.getListMembers(listRec.Id);
            System.assert(!listMemberRecord.isEmpty(), 'No List Member found');

            Test.stopTest();
        }
    }

    @isTest
    static void getEngagementOpportunityListIdTest(){
        Engagement_Opportunity__c enOppRec = EngagementOpportunitiesDAO.newInstance().getEngagementOpportunityRecords(1,AccessLevel.USER_MODE).iterator().next();
        System.runAs(TestDataFactory.getQUTAlumniEngagementManager()) {
            Test.startTest();

            Id listId = CustomHeaderDatatableCtrl.getEngagementOpportunityListId(enOppRec.Id);
            System.assert(listId != null, 'No List record found');

            Test.stopTest();
        }
    }
}