src/core-crm/objects/Engagement_Opportunity__c/Engagement_Opportunity__c.object-meta.xml
<CustomObject>
    <description>Engagement Opportunity captures information for Alumni Engagement and Corporate Engagement business processes.</description>
    <label>Engagement Opportunity</label>
    <nameField>
        <displayFormat>EO-{000000}</displayFormat>
        <label>Engagement Opportunity Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/core-crm/objects/List__c/List__c.object-meta.xml
<CustomObject>
    <description>List supports information capture about a request to compile a list of Contacts for a defined business reason.</description>
    <label>List</label>
    <nameField>
        <displayFormat>LIST-{000000}</displayFormat>
        <label>List Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/List__c/fields/Engagement_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to an Engagement Opportunity.</description>
    <inlineHelpText>Engagement Opportunity associated with the List.</inlineHelpText>
    <label>Engagement Opportunity</label>
    <referenceTo>Engagement_Opportunity__c</referenceTo>
    <relationshipLabel>Lists</relationshipLabel>
    <relationshipName>Lists</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/classes/ListsDAOMock.cls
/**
 * @description Mock DAO Class for List Member Object.
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
 *    |--------------------------------|-----------------------|------------------------|------------------------------|
 *    |carl.alvin.cabiles              | September 18, 2023    | DEPP-6510              | Created file
 */
@isTest
public inherited sharing class ListsDAOMock extends DmlBaseMock implements IListsDAO {
    public Map<Id, List__c> listsMap;

    public Schema.SObjectType getSObjectType() {
        return List__c.SObjectType;
    } 

    public ListsDAOMock() {
        super(new Map<Id, List__c>(), Schema.List__c.SObjectType);
        this.listsMap = (Map<Id, List__c>) super.records;
    }

    public List<List__c> getListRecords(Integer recordscount) {
        List<List__c> listRecords = new List<List__c>();
        Integer count = 0;
        for (List__c record : listsMap.values()) {
            if(count <recordscount){
                listRecords.add(record);
                count+=1;
            }
        }
        return listRecords;
    }

    public List<List__c> getListRecordsByRelatedEngagementOpportunitySetIds(Set<Id> recordIds,
    AccessLevel accessLevel) {
        List<List__c> listRecList = new List<List__c>();

        for (List__c record : listsMap.values()) {
            if (recordIds.contains(record.Engagement_Opportunity__c)) {
                listRecList.add(record);
            }
        }

        return listRecList;
    }
}