src/core-crm/objects/Engagement_Opportunity__c/Engagement_Opportunity__c.object-meta.xml
<CustomObject>
    <description>Engagement Opportunity captures information for Alumni Engagement and Corporate Engagement business processes.</description>
    <label>Engagement Opportunity</label>
    <nameField>
        <displayFormat>EO-{000000}</displayFormat>
        <label>Engagement Opportunity Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/core-crm/objects/Engagement_Opportunity__c/fields/Engagement_Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Opportunity_Name__c</fullName>
    <description>The business-defined name for the Engagement.</description>
    <inlineHelpText>The business-defined name for the Engagement.</inlineHelpText>
    <label>Engagement Opportunity Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/core-crm/classes/EngagementOpportunitiesDAOMock.cls
/**
 * @description Mock DAO Class for Engagement Opportunity Object
 *
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary                             |
 *    |--------------------------------|-----------------------|------------------------|--------------------------------------------|
 *    | nicole.genon                   | December 18, 2023     | DEPP-6949              | Created File                               |
 *    | carl.alvin.cabiles             | February 12, 2024     | DEPP-7134              | Added getEngagementOpportunitiesBySetNames |

 */
@isTest
public inherited sharing class EngagementOpportunitiesDAOMock  extends DmlBaseMock implements IEngagementOpportunitiesDAO{
    public Map<Id, Engagement_Opportunity__c> engagementOpportunityMap;
 
    public EngagementOpportunitiesDAOMock() {
        super(new Map<Id, Engagement_Opportunity__c>(), Schema.Engagement_Opportunity__c.SObjectType);
        this.engagementOpportunityMap = (Map<Id, Engagement_Opportunity__c>) super.records;
    }

    public Schema.SObjectType getSObjectType() {
        return Engagement_Opportunity__c.SObjectType;
    }

    public List<Engagement_Opportunity__c> getEngagementOpportunitiesBySetIds(Set<Id> engagementOpportunityIds, AccessLevel accessLevel) {
        List<Engagement_Opportunity__c> engagementOpportunityList = new List<Engagement_Opportunity__c>();

        for (Engagement_Opportunity__c record : engagementOpportunityMap.values()) {
            if (engagementOpportunityIds.contains(record.Id)) {
                engagementOpportunityList.add(record);
            }
        }

        return engagementOpportunityList;
    }

    public List<Engagement_Opportunity__c> getEngagementOpportunitiesBySetNames(Set<String> engagementOpportunityNames, AccessLevel accessLevel) {
        List<Engagement_Opportunity__c> engagementOpportunityList = new List<Engagement_Opportunity__c>();

        for (Engagement_Opportunity__c record : engagementOpportunityMap.values()) {
            if (engagementOpportunityNames.contains(record.Engagement_Opportunity_Name__c)) {
                engagementOpportunityList.add(record);
            }
        }

        return engagementOpportunityList;
    }
}