src/core-crm/objects/Field_Layout_Setting__mdt/Field_Layout_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Manages usage of fields on custom UI development.</description>
    <label>Field Layout Setting</label>
    <pluralLabel>Field Layout Settings</pluralLabel>
</CustomObject>

src/core-crm/objects/Product_Request__c/Product_Request__c.object-meta.xml
<CustomObject>
    <label>Product Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Product Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <description>This will store the questions that will be added against a questionnaire.</description>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Questionnaire__c/Questionnaire__c.object-meta.xml
<CustomObject>
    <description>This will capture the list of questions/answers against a record.</description>
    <label>Questionnaire</label>
    <nameField>
        <displayFormat>QN-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Related_Answer__c/Related_Answer__c.object-meta.xml
<CustomObject>
    <description>This will be junction object to link Questionnaire and Question records.</description>
    <label>Related Answer</label>
    <nameField>
        <displayFormat>QQ-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Related_Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the question record.</description>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Related Answers</relationshipLabel>
    <relationshipName>Related_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Related_Answer__c/fields/Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the questionnaire.</description>
    <label>Questionnaire</label>
    <referenceTo>Questionnaire__c</referenceTo>
    <relationshipLabel>Related Answers</relationshipLabel>
    <relationshipName>Related_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/classes/SetupRegistrationCtrlTest.cls
/**
 * @description Tests the SetupRegistrationCtrl Class
 *
 * @see SetupRegistrationCtrl
 *
 * @author Accenture
 *
 * @history
 *    | Developer                 | Date                  | JIRA      | Change Summary                  |
      |---------------------------|-----------------------|-----------|---------------------------------|
      | angelika.j.s.galang       | Januar 25, 2022       | DEPP-1396 | Created file                    |
      | john.bo.a.pineda          | February 03, 2022     | DEPP-1532 | Update Answer to Related Answer |
      |                           |                       |           |                                 |
*/
@isTest
private class SetupRegistrationCtrlTest {
  private static final String PRODUCT_API_NAME = Product2.SObjectType.getDescribe(SObjectDescribeOptions.DEFERRED).getLocalName();
  private static final String QUESTION_API_NAME = Question__c.SObjectType.getDescribe(SObjectDescribeOptions.DEFERRED).getLocalName();

  @testSetup
  static void setupMethod() {
    TestDataFactoryUser.generateUserQUTeXProgramAdministrator();
    Product_Request__c prodReq = TestDataFactory.createTestProductRequestRecords(
        1
      )
      .iterator()
      .next();
    insert prodReq;
    Questionnaire__c questionnaire = TestDataFactory.createTestQuestionnaireRecords(
        1,
        prodReq?.Id,
        PRODUCT_API_NAME
      )
      .iterator()
      .next();
    insert questionnaire;

    List<Question__c> questions = TestDataFactory.createTestQuestionRecords(
      100
    );
    insert questions;
    List<Related_Answer__c> answers = TestDataFactory.createTestRelatedAnswerRecords(
      100,
      questionnaire?.Id,
      questions
    );
    insert answers;
  }

  @isTest
  private static void getRegistrationDataTest() {
    System.runAs(TestDataFactoryUser.selectUserQUTeXProgramAdministrator) {
      Product_Request__c prodReq = [SELECT Id FROM Product_Request__c LIMIT 1];
      Test.startTest();
      SetupRegistrationCtrl.RegistrationData regData = SetupRegistrationCtrl.getRegistrationData(
        prodReq?.Id
      );
      Test.stopTest();
      System.assertEquals(
        1,
        regData.questionnaireList.size(),
        'Number of expected questionnaires did not match'
      );
      System.assertEquals(
        100,
        regData.questionList.size(),
        'Number of expected questions did not match'
      );
    }
  }

  @isTest
  private static void getQuestionLayoutTest() {
    System.runAs(TestDataFactoryUser.selectUserQUTeXProgramAdministrator) {
      Test.startTest();
      List<Field_Layout_Setting__mdt> fls = SetupRegistrationCtrl.getQuestionLayout(
        QUESTION_API_NAME,
        true
      );
      Test.stopTest();
      System.assertEquals(
        1,
        fls.size(),
        'Number of expected layout setting did not match'
      );
    }
  }

  @isTest
  private static void updateAnswerSequencesTest() {
    System.runAs(TestDataFactoryUser.selectUserQUTeXProgramAdministrator) {
      List<Related_Answer__c> answers = [
        SELECT Sequence__c
        FROM Related_Answer__c
        LIMIT 100
      ];
      for (Integer i = 0; i < answers.size(); i++) {
        answers[i].Sequence__c = i;
      }
      Test.startTest();
      SetupRegistrationCtrl.updateAnswerSequences(answers);
      Test.stopTest();
      List<Related_Answer__c> updatedAnswers = [
        SELECT Sequence__c
        FROM Related_Answer__c
        LIMIT 100
      ];
      for (Integer i = 0; i < 100; i++) {
        System.assertEquals(
          i,
          updatedAnswers[i].Sequence__c,
          'Expected sequence did not match'
        );
      }
    }
  }
}