src/core-crm/objects/Field_Layout_Setting__mdt/Field_Layout_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Manages usage of fields on custom UI development.</description>
    <label>Field Layout Setting</label>
    <pluralLabel>Field Layout Settings</pluralLabel>
</CustomObject>

src/core-crm/objects/Field_Layout_Setting__mdt/fields/Left_Column_Long__c.field-meta.xml
<CustomField>
    <fullName>Left_Column_Long__c</fullName>
    <description>Fields that are on the left side column of the section.</description>
    <inlineHelpText>Must be in JSON format. With the following attributes: field,mandatory,isrecordtype. (attribute not needed when false) e.g
[{&quot;field&quot;:&quot;OwnerId&quot;},{&quot;field&quot;:&quot;Product_Request_Status__c&quot;,&quot;mandatory&quot;:true},{&quot;field&quot;:&quot;RecordTypeId&quot;,&quot;isrecordtype&quot;:true}]</inlineHelpText>
    <label>Left Column (Long)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/core-crm/objects/Field_Layout_Setting__mdt/fields/Left_Right_Column_Long__c.field-meta.xml
<CustomField>
    <fullName>Left_Right_Column_Long__c</fullName>
    <inlineHelpText>Must be in JSON format and even. Add Blank attribute to show blank space and to even out fields. 
e.g [{&quot;field&quot;:&quot;Certificate_Type__c&quot;,&quot;blank&quot;:true}
With the following attributes: field,mandatory,isrecordtype. (attribute not needed when false) e.g
[{&quot;field&quot;:&quot;OwnerId&quot;},{&quot;field&quot;:&quot;Product_Request_Status__c&quot;,&quot;mandatory&quot;:true},{&quot;field&quot;:&quot;RecordTypeId&quot;,&quot;isrecordtype&quot;:true}]</inlineHelpText>
    <label>Left_Right_Column_Long</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/core-crm/objects/Field_Layout_Setting__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>Order of section on the form.</description>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src-env-specific-pre/objects/Field_Layout_Setting__mdt/fields/Record_Type_Setting__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Setting__c</fullName>
    <description>Associated record type.</description>
    <label>Record Type Setting</label>
    <referenceTo>Record_Type_Setting__mdt</referenceTo>
    <relationshipLabel>Field Layout Settings</relationshipLabel>
    <relationshipName>Field_Layout_Settings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

src/core-crm/objects/Field_Layout_Setting__mdt/fields/Right_Column_Long__c.field-meta.xml
<CustomField>
    <fullName>Right_Column_Long__c</fullName>
    <description>Fields that are on the right side column of the section.</description>
    <inlineHelpText>Must be in JSON format. With the following attributes: field,mandatory,isrecordtype. (attribute not needed when false) e.g
[{&quot;field&quot;:&quot;OwnerId&quot;},{&quot;field&quot;:&quot;Product_Request_Status__c&quot;,&quot;mandatory&quot;:true},{&quot;field&quot;:&quot;RecordTypeId&quot;,&quot;isrecordtype&quot;:true}]</inlineHelpText>
    <label>Right Column (Long)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/core-crm/objects/Field_Layout_Setting__mdt/fields/Single_Column_Long__c.field-meta.xml
<CustomField>
    <fullName>Single_Column_Long__c</fullName>
    <description>Fields that are on a single column part of a section.</description>
    <inlineHelpText>Must be in JSON format. With the following attributes: field,mandatory,isrecordtype. (attribute not needed when false) e.g
[{&quot;field&quot;:&quot;OwnerId&quot;},{&quot;field&quot;:&quot;Product_Request_Status__c&quot;,&quot;mandatory&quot;:true},{&quot;field&quot;:&quot;RecordTypeId&quot;,&quot;isrecordtype&quot;:true}]</inlineHelpText>
    <label>Single Column (Long)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/core-crm/objects/Record_Type_Setting__mdt/Record_Type_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Manages usage of record types for custom UI developments.</description>
    <label>Record Type Setting</label>
    <pluralLabel>Record Type Settings</pluralLabel>
</CustomObject>

src/core-crm/objects/Record_Type_Setting__mdt/fields/For_OPE__c.field-meta.xml
<CustomField>
    <fullName>For_OPE__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if UI component is for OPE.</description>
    <label>For OPE?</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Record_Type_Setting__mdt/fields/Object_Type__c.field-meta.xml
<CustomField>
    <fullName>Object_Type__c</fullName>
    <description>Object of Record Type</description>
    <label>Object Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Record_Type_Setting__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>Order of which record type is displayed in custom selection</description>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/classes/CustomLayoutCtrl.cls
/**
 * @description Controller class for Custom Page and Section Layouts LWC
 *
 * @see ../lwc/customPageLayout
 * @see ../lwc/customSectionLayout
 * 
 * @author Accenture
 *      
 * @history
 *    | Developer                 | Date                  | JIRA                 | Change Summary                                         |
      |---------------------------|-----------------------|----------------------|--------------------------------------------------------|
      | angelika.j.s.galang       | January 26, 2022      | DEPP-838,1299,1407   | Created file                                           |
      |                           |                       |                      |                                                        | 
*/
public with sharing class CustomLayoutCtrl {

    private static final String ID = 'Id';
    /**
    * @description Method for getting the Id of related child of parent record
    * @param parentId - Id of Parent
    * @param parentField - parent field api name
    * @param childObjectType - object api name of child
    * @param grandChildInfo - map containing info of grandchild
    * @return Id of Child
    */
    @AuraEnabled(cacheable=true)
    public static Id getChildRecordId(
        String parentId,
        String parentField, 
        String childObjectType, 
        Map<String,String> grandChildInfo
    ){  
        Id currentRecord = queryRecord(ID, childObjectType, parentField, parentId);
        if(grandChildInfo.isEmpty()){
            return currentRecord;
        }else{
            Id parent = currentRecord;
            return queryRecord(
                ID,
                grandChildInfo.get('objectApiName'),
                grandChildInfo.get('conditionField'),
                parent
            );
        }
    }

    @AuraEnabled(cacheable=true)
    public static sObject getParentRecord(
        String parentId,
        String parentField, 
        String childObjectType, 
        String fields,
        Map<String,String> grandChildInfo
    ){  
        sObject currentRecord = queryRecordObject(fields, childObjectType, parentField, parentId);
        if(grandChildInfo.isEmpty()){
            return currentRecord;
        }else{
            Id parent = currentRecord.Id;
            return queryRecordObject(
                fields,
                grandChildInfo.get('objectApiName'),
                grandChildInfo.get('conditionField'),
                parent
            );
        }
    }
    

    /**
    * @description Method for getting the Id of an SObject
    * @param fields - fields to query
    * @param objectApiName - object to query from
    * @param conditionField - field api name for condition
    * @param conditionValue -value of condition
    * @return Id of SObject record
    */
    private static Id queryRecord(
        String fields,
        String objectApiName,
        String conditionField,
        String conditionValue
    ){
        Id record;
        List<SObject> records = Database.query( 
            'SELECT ' + String.escapeSingleQuotes(fields) + 
            ' FROM ' + String.escapeSingleQuotes(objectApiName) + 
            ' WHERE ' + String.escapeSingleQuotes(conditionField) +
            ' = \'' + String.escapeSingleQuotes(conditionValue) + 
            '\' LIMIT 1');
                
        if(!records.isEmpty()){
            record = (Id) records.iterator().next().get(ID);
        }

        return record;
    }

    /**
    * @description Method for getting the Id of an SObject
    * @param fields - fields to query
    * @param objectApiName - object to query from
    * @param conditionField - field api name for condition
    * @param conditionValue -value of condition
    * @return Id of SObject record
    */
    private static sObject queryRecordObject(
        String fields,
        String objectApiName,
        String conditionField,
        String conditionValue
    ){
        sObject record;
        List<SObject> records = Database.query(
            'SELECT ' + String.escapeSingleQuotes(fields) + 
            ' FROM ' + String.escapeSingleQuotes(objectApiName) + 
            ' WHERE ' + String.escapeSingleQuotes(conditionField) +
            ' = \'' + String.escapeSingleQuotes(conditionValue) + 
            '\' LIMIT 1');
                
        if(!records.isEmpty()){
            record = (sObject) records.iterator().next();
        }

        return record;
    }

    /**
    * @description Method for getting the metadata of given object api name set in Field Layout Setting
    * @param objApiName - API name of object passed from component
    * @param rtDevName - record type setting api name
    * @param isOpe - determines if layout is for an OPE feature
    * @return list of Field Layout Setting records
    */
    @AuraEnabled(cacheable=true)
    public static List<Field_Layout_Setting__mdt> getLayoutMapping(
        String objApiName, 
        String rtDevName, 
        Boolean isOpe
    ){
        return [
            SELECT  MasterLabel, Left_Right_Column_Long__c, Left_Column_Long__c, Right_Column_Long__c, Single_Column_Long__c, Order__c
            FROM Field_Layout_Setting__mdt
            WHERE Record_Type_Setting__r.Object_Type__c =: objApiName
            AND Record_Type_Setting__r.DeveloperName =: rtDevName
            AND Record_Type_Setting__r.For_OPE__c =: isOpe
            ORDER BY Order__c ASC
        ];
    }

}