src/core-crm/objects/BuyerGroup/fields/Product_Request__c.field-meta.xml
<CustomField>
    <fullName>Product_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the parent Standing Offer Arrangement Product request</description>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Buyer Groups</relationshipLabel>
    <relationshipName>Buyer_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Contact/fields/Accessibility_Requirement__c.field-meta.xml
<CustomField>
    <fullName>Accessibility_Requirement__c</fullName>
    <label>Accessibility Requirement</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

src/core-crm/objects/Contact/fields/Dietary_Requirement__c.field-meta.xml
<CustomField>
    <fullName>Dietary_Requirement__c</fullName>
    <description>Capture details for learner’s dietary requirements</description>
    <label>Dietary Requirement</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

src/core-crm/objects/Contact/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>Job Title</description>
    <label>Position</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Expression_of_Interest__c/Expression_of_Interest__c.object-meta.xml
<CustomObject>
    <description>Record will be created when learner clicks &apos;Register Interest&apos; button against a Product in OPE catalogue or nominations from corporate portal</description>
    <label>Expression of Interest</label>
    <nameField>
        <displayFormat>EI-{0000}</displayFormat>
        <label>Expression of Interest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expression of Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Expression_of_Interest__c/fields/Accessibility_Requirement__c.field-meta.xml
<CustomField>
    <fullName>Accessibility_Requirement__c</fullName>
    <label>Accessibility Requirement</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

src/core-crm/objects/Expression_of_Interest__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <label>Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField> 

src/core-crm/objects/Expression_of_Interest__c/fields/Course_Offering__c.field-meta.xml
<CustomField>
    <fullName>Course_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will link to course offering that the learner successfully registered to for &apos;Register Interest&apos; process OR a link to the nominated course offering.</description>
    <label>Course Offering</label>
    <referenceTo>hed__Course_Offering__c</referenceTo>
    <relationshipLabel>Expression of Interests</relationshipLabel>
    <relationshipName>Expression_of_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Expression_of_Interest__c/fields/Dietary_Requirement__c.field-meta.xml
<CustomField>
    <fullName>Dietary_Requirement__c</fullName>
    <label>Dietary Requirement</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

src/core-crm/objects/Expression_of_Interest__c/fields/Mobile_Locale__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Locale__c</fullName>
    <label>Mobile Locale</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Loqate_Locale</valueSetName>
    </valueSet>
</CustomField>

src/core-crm/objects/Expression_of_Interest__c/fields/Pricebook_Entry_ID__c.field-meta.xml
<CustomField>
    <fullName>Pricebook_Entry_ID__c</fullName>
    <label>Pricebook Entry ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Expression_of_Interest__c/fields/Program_Offering__c.field-meta.xml
<CustomField>
    <fullName>Program_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will link to program offering that the learner successfully registered to for &apos;Register Interest&apos; process OR a link to the nominated program offering.</description>
    <label>Program Offering</label>
    <referenceTo>Program_Offering__c</referenceTo>
    <relationshipLabel>Expression of Interests</relationshipLabel>
    <relationshipName>Expression_of_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Expression_of_Interest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of interest</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/hed__Course_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Represents a connection to a Course Offering.</description>
    <label>Course Connection</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Course Connection ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Enrollment__c/fields/Birthdate__c.field-meta.xml
<CustomField>
    <fullName>Birthdate__c</fullName>
    <formula>hed__Contact__r.Birthdate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Birthdate</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The course that the student is enrolment is related to</description>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Course Connections</relationshipLabel>
    <relationshipName>Course_Connections</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>hed__Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <formula>hed__Contact__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>First Name</label>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/hed__Course_Offering__c.field-meta.xml
<CustomField>
    <fullName>hed__Course_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Course Offering the student or faculty member is involved with.</description>
    <inlineHelpText>The Course Offering the student or faculty member is involved with.</inlineHelpText>
    <label>Course Offering ID</label>
    <referenceTo>hed__Course_Offering__c</referenceTo>
    <relationshipLabel>Course Connection</relationshipLabel>
    <relationshipName>Course_Enrollment</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <formula>hed__Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Name</label>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <formula>hed__Contact__r.MobilePhone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mobile</label>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/Program_Offering__c.field-meta.xml
<CustomField>
    <fullName>Program_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Offering</label>
    <referenceTo>Program_Offering__c</referenceTo>
    <relationshipLabel>Course Connections</relationshipLabel>
    <relationshipName>Course_Connections</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <description>A Student Course Connection</description>
    <label>Student</label>
</RecordType>

src/core-crm/objects/hed__Course_Offering__c/hed__Course_Offering__c.object-meta.xml
<CustomObject>
    <description>Joins Courses and Terms to contain information related to a single occurrence of a Course.</description>
    <label>Course Offering</label>
    <nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Course__c.field-meta.xml
<CustomField>
    <fullName>hed__Course__c</fullName>
    <description>Lookup to the Course record that this Course Offering is associated with.</description>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>
 

src/core-crm/objects/hed__Course_Offering__c/fields/Program_Offering__c.field-meta.xml
<CustomField>
    <fullName>Program_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Linked the course offering to the Program offering for Prescribed
    Program.</description>
    <label>Program Offering</label>
    <referenceTo>Program_Offering__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Client Approved</fullName>
            </value>
            <value>
                <fullName>Contract Created</fullName>
            </value>
            <value>
                <fullName>Contract Signed</fullName>
            </value>
            <value>
                <fullName>Drafter Review</fullName>
            </value>
            <value>
                <fullName>Drafting</fullName>
            </value>
            <value>
                <fullName>Drafting Complete</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Pending Contract Creation</fullName>
            </value>
            <value>
                <fullName>Pending Initial Proposal Approval</fullName>
            </value>
            <value>
                <fullName>Pending QUTeX Executive Approval</fullName>
            </value>
            <value>
                <fullName>QUTeX Executive Approved</fullName>
            </value>
            <value>
                <fullName>Under Client Review</fullName>
            </value>
            <value>
                <fullName>QUTeX Executive Proposal Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Product2/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Product_Request__c/Product_Request__c.object-meta.xml
<CustomObject>
    <label>Product Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Product Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Product_Request__c/fields/Product_Specification__c.field-meta.xml
<CustomField>
    <fullName>Product_Specification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Specification</label>
    <referenceTo>Product_Specification__c</referenceTo>
    <relationshipLabel>Product Requests</relationshipLabel>
    <relationshipName>Product_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/User/fields/Birthdate__c.field-meta.xml
<CustomField>
    <fullName>Birthdate__c</fullName>
    <label>Birthdate</label>
    <type>Date</type>
</CustomField>

src/core-crm/globalValueSets/Loqate_Locale.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Australia (+61)</fullName>
        <default>true</default>
        <label>Australia (+61)</label>
    </customValue>
    <customValue>
        <fullName>New Zealand (+64)</fullName>
    </customValue>
    <customValue>
        <fullName>International</fullName>
    </customValue>
    <customValue>
        <fullName>Afghanistan (93)</fullName>
    </customValue>
    <customValue>
        <fullName>Åland Islands (358)</fullName>
    </customValue>
    <customValue>
        <fullName>Albania (355)</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria (213)</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa (1-684)</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra (376)</fullName>
    </customValue>
    <customValue>
        <fullName>Angola (244)</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla (1-264)</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica (672)</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda (1-268)</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina (54)</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia (374)</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba (297)</fullName>
    </customValue>
    <customValue>
        <fullName>Austria (43)</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan (994)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas (the) (1-242)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain (973)</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh (880)</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados (1-246)</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus (375)</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium (32)</fullName>
    </customValue>
    <customValue>
        <fullName>Belize (501)</fullName>
    </customValue>
    <customValue>
        <fullName>Benin (229)</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda (1-441)</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan (975)</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia (Plurinational State of) (591)</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba (599)</fullName>
    </customValue>
    <masterLabel>Loqate Locale</masterLabel>
</GlobalValueSet>

src/core-crm/classes/ManageRegAndNomCtrlTest.cls
/**
 * @description Test Class for ManageRegAndNomCtrl
 * @see ../classes/ManageRegAndNomCtrl
 *
 * @author Accenture
 *
 * @history
 *    | Developer                 | Date                  | JIRA                 | Change Summary               |
      |---------------------------|-----------------------|----------------------|------------------------------|
      | eccarius.karl.munoz       | September 07, 2022    | DEPP-3747            | Created file to .            |
      | julie.jane.alegre         | October 05, 2023      | DEPP-4762            | Update test method           |
      |                           |                       |                      |                              |
*/

@isTest
public with sharing class ManageRegAndNomCtrlTest {

    private static final String CATEGORY_CCE = 'Corporate Portal';
    private final User PORTAL_SYS_ADMIN = TestDataFactoryUser.selectUserSystemAdministrator;
    private static final String ACCT_UNIV_DEP = System.Label.RT_Account_University_Department;
    private static final Id ACCT_UNIV_DEP_ID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(ACCT_UNIV_DEP).getRecordTypeId();

    private static final String ACCT_BUSINESS_ORG = System.Label.RT_Account_Business_Org;
    private static final Id ACCT_BUSINESS_ORG_ID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(ACCT_BUSINESS_ORG).getRecordTypeId();
    
    private static final string STUDENT_RT = System.Label.RT_CourseConnection_Student;
    private static final Id STUDENT_RT_ID = Schema.SObjectType.hed__Course_Enrollment__c.getRecordTypeInfosByDeveloperName().get(STUDENT_RT).getRecordTypeId();
    private static final String RT_ACTIVITY = System.Label.RT_ProductRequest_Activity;
    private static final Id RT_ACTIVITY_ID = Schema.SObjectType.Product_Request__c.getRecordTypeInfosByDeveloperName().get(RT_ACTIVITY).getRecordTypeId();
    
    private static final String RT_CONTACT_PERSON = System.Label.RT_Contact_Person;
    private static final Id RT_CONTACT_PERSON_ID = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get(RT_CONTACT_PERSON).getRecordTypeId();

    private static Id cceProdSpecId = Schema.SObjectType.Product_Specification__c.getRecordTypeInfosByDeveloperName().get('CCE').getRecordTypeId();
    
    private static final Integer NUMBER_OF_RECORDS = 100;

    @testSetup
    static void makeData(){
        BypassTriggers__c bypass = new BypassTriggers__c(Bypass__c = true, SetupOwnerId = UserInfo.getOrganizationId());
        insert bypass;
        Test.startTest();
        TestDataFactoryUser.generateUserSystemAdministrator();
        Test.stopTest();
        createRecord();
        
    }

    @isTest
    static void getNominationStatusValuesTest(){  
        final User PORTAL_SYS_ADMIN = TestDataFactoryUser.selectUserSystemAdministrator;      
        System.runAs(PORTAL_SYS_ADMIN){               
            Test.startTest();
            List<String> nominationStatusValues = ManageRegAndNomCtrl.getNominationStatusValues();
            Test.stopTest();
            System.assert(!nominationStatusValues.isEmpty(), 'Nomination Status Values must not be empty.');
        }
    }

    @isTest
    static void updateRegistrationOrNominationStatusTest(){  
        BypassTriggers__c bypass = [SELECT Id, Bypass__c FROM BypassTriggers__c WHERE SetupOwnerId =: UserInfo.getOrganizationId() WITH SECURITY_ENFORCED LIMIT 1];
        bypass.Bypass__c = false;
        update bypass;
        final User PORTAL_SYS_ADMIN = TestDataFactoryUser.selectUserSystemAdministrator;      
        System.runAs(PORTAL_SYS_ADMIN){     
            Id businessOrgAcctId = [SELECT Id FROM Account WHERE Name = 'Business Org Account' WITH SECURITY_ENFORCED].Id;
            Test.startTest();
            List<Expression_of_Interest__c> expOfInterestList = [SELECT Id, Name, Pricebook_Entry_ID__c, First_Name__c, Program_Offering__c, Course_Offering__c, Last_Name__c, Email__c, Position__c, Company_Name__c, Birthdate__c,Accessibility_Requirement__c, Dietary_Requirement__c,Mobile__c, Mobile_Locale__c FROM Expression_of_Interest__c WITH SECURITY_ENFORCED];
            ManageRegAndNomCtrl.StudentDetails details = new ManageRegAndNomCtrl.StudentDetails();
            details.id = expOfInterestList[0].Id;
            details.registrationStatus = 'Approved';
            details.isRegistrations = false;
            details.contactInfo = expOfInterestList[0];
            details.mobileNumber = '61412345678';
            details.businessOrgAccount = String.valueOf(businessOrgAcctId);
            ManageRegAndNomCtrl.RegistrationNominationUpdateResponse response = ManageRegAndNomCtrl.updateRegistrationOrNominationStatus(details);
            Test.stopTest();
            System.assert(response.isSuccess, 'Failed to Update Nomination status.');
        }
    }

    @isTest
    static void updateExistingContactNominationStatusTest(){  
        BypassTriggers__c bypass = [SELECT Id, Bypass__c FROM BypassTriggers__c WHERE SetupOwnerId =: UserInfo.getOrganizationId() WITH SECURITY_ENFORCED LIMIT 1];
        bypass.Bypass__c = false;
        update bypass;
        final User PORTAL_SYS_ADMIN = TestDataFactoryUser.selectUserSystemAdministrator;      
        System.runAs(PORTAL_SYS_ADMIN){    
            List<hed__Course_Offering__c> cList = [SELECT Id, hed__Course__c FROM hed__Course_Offering__c WITH SECURITY_ENFORCED];
            Expression_of_Interest__c eoi = new Expression_of_Interest__c();
            eoi.First_Name__c = 'Contact';
            eoi.Last_Name__c = 'Record';
            eoi.Birthdate__c = Date.newInstance(1991, 2, 17);
            eoi.Email__c = 'con@rec1.com';
            eoi.Status__c = 'Pending';
            eoi.Course_Offering__c = cList[0].Id;
            insert eoi;
            Id businessOrgAcctId = [SELECT Id FROM Account WHERE Name = 'Business Org Account' WITH SECURITY_ENFORCED].Id;
            ManageRegAndNomCtrl.StudentDetails details = new ManageRegAndNomCtrl.StudentDetails();
            details.id = eoi.Id;
            details.registrationStatus = 'Approved';
            details.isRegistrations = false;
            details.contactInfo = eoi;
            details.mobileNumber = '61412345678';
            details.businessOrgAccount = String.valueOf(businessOrgAcctId);
            Test.startTest();
            ManageRegAndNomCtrl.RegistrationNominationUpdateResponse response = ManageRegAndNomCtrl.updateRegistrationOrNominationStatus(details);
            Test.stopTest();
            System.assert(response.isSuccess, 'Failed to Update Nomination status.');
        }
    }

    @isTest
    static void updateStatusWithExceptionTest(){  
        BypassTriggers__c bypass = [SELECT Id, Bypass__c FROM BypassTriggers__c WHERE SetupOwnerId =: UserInfo.getOrganizationId() WITH SECURITY_ENFORCED LIMIT 1];
        bypass.Bypass__c = false;
        update bypass;
        final User PORTAL_SYS_ADMIN = TestDataFactoryUser.selectUserSystemAdministrator;      
        System.runAs(PORTAL_SYS_ADMIN){    
            Test.startTest();
            Id businessOrgAcctId = [SELECT Id FROM Account WHERE Name = 'Business Org Account' WITH SECURITY_ENFORCED].Id;
            List<Expression_of_Interest__c> expOfInterestList = [SELECT Id, Name, Pricebook_Entry_ID__c, First_Name__c, Program_Offering__c, Course_Offering__c, Last_Name__c, Email__c, Birthdate__c,Accessibility_Requirement__c, Dietary_Requirement__c,Mobile__c, Mobile_Locale__c FROM Expression_of_Interest__c WITH SECURITY_ENFORCED];
            ManageRegAndNomCtrl.StudentDetails details = new ManageRegAndNomCtrl.StudentDetails();
            details.id = expOfInterestList[0].Id;
            details.registrationStatus = 'InvalidStatus';
            details.isRegistrations = false;
            details.contactInfo = expOfInterestList[0];
            details.mobileNumber = '61412345678';
            details.businessOrgAccount = String.valueOf(businessOrgAcctId);
            ManageRegAndNomCtrl.RegistrationNominationUpdateResponse response = ManageRegAndNomCtrl.updateRegistrationOrNominationStatus(details);
            Test.stopTest();
            System.assert(!response.isSuccess, 'Should not be able to update record with invalid status.');
        }
    }

    @isTest
    static void updateNotApprovedNominationTest(){  
        final User PORTAL_SYS_ADMIN = TestDataFactoryUser.selectUserSystemAdministrator;      
        System.runAs(PORTAL_SYS_ADMIN){    
            Test.startTest();
            Id businessOrgAcctId = [SELECT Id FROM Account WHERE Name = 'Business Org Account' WITH SECURITY_ENFORCED].Id;
            List<Expression_of_Interest__c> expOfInterestList = [SELECT Id, Name, Pricebook_Entry_ID__c, First_Name__c, Program_Offering__c, Course_Offering__c, Last_Name__c, Email__c, Birthdate__c,Accessibility_Requirement__c, Dietary_Requirement__c,Mobile__c, Mobile_Locale__c FROM Expression_of_Interest__c WITH SECURITY_ENFORCED];
            ManageRegAndNomCtrl.StudentDetails details = new ManageRegAndNomCtrl.StudentDetails();
            details.id = expOfInterestList[0].Id;
            details.registrationStatus = 'Pending';
            details.isRegistrations = false;
            details.contactInfo = expOfInterestList[0];
            details.mobileNumber = '61412345678';
            details.businessOrgAccount = String.valueOf(businessOrgAcctId);
            ManageRegAndNomCtrl.RegistrationNominationUpdateResponse response = ManageRegAndNomCtrl.updateRegistrationOrNominationStatus(details);
            Test.stopTest();
            System.assert(response.isSuccess, 'Failed to Update Nomination status.');
        }
    } 
    
    @isTest
    static void updateExistingContactDiffDetailsTest(){  
        final User PORTAL_SYS_ADMIN = TestDataFactoryUser.selectUserSystemAdministrator;      
        System.runAs(PORTAL_SYS_ADMIN){    
            List<hed__Course_Offering__c> cList = [SELECT Id, hed__Course__c FROM hed__Course_Offering__c WITH SECURITY_ENFORCED];
            Expression_of_Interest__c eoi = new Expression_of_Interest__c();
            eoi.First_Name__c = 'Contact123';
            eoi.Last_Name__c = 'Record123';
            eoi.Birthdate__c = Date.newInstance(1991, 2, 17);
            eoi.Email__c = 'con@rec1.com';
            eoi.Status__c = 'Pending';
            eoi.Course_Offering__c = cList[0].Id;
            insert eoi;
            Id businessOrgAcctId = [SELECT Id FROM Account WHERE Name = 'Business Org Account' WITH SECURITY_ENFORCED].Id;
            ManageRegAndNomCtrl.StudentDetails details = new ManageRegAndNomCtrl.StudentDetails();
            details.id = eoi.Id;
            details.registrationStatus = 'Approved';
            details.isRegistrations = false;
            details.contactInfo = eoi;
            details.mobileNumber = '61412345678';
            details.businessOrgAccount = String.valueOf(businessOrgAcctId);
            Test.startTest();
            ManageRegAndNomCtrl.RegistrationNominationUpdateResponse response = ManageRegAndNomCtrl.updateRegistrationOrNominationStatus(details);
            Test.stopTest();
            System.assert(!response.isSuccess, 'Incorrect validation of contact information.');
        }
    }

    @isTest
    static void updateExistingContactDiffEmailTest(){  
        final User PORTAL_SYS_ADMIN = TestDataFactoryUser.selectUserSystemAdministrator;      
        System.runAs(PORTAL_SYS_ADMIN){    
            Expression_of_Interest__c eoi = new Expression_of_Interest__c();
            eoi.First_Name__c = 'Contact';
            eoi.Last_Name__c = 'Record';
            eoi.Birthdate__c = Date.newInstance(1991, 2, 17);
            eoi.Email__c = 'con@rec123.com';
            eoi.Status__c = 'Pending';
            insert eoi;
            Id businessOrgAcctId = [SELECT Id FROM Account WHERE Name = 'Business Org Account' WITH SECURITY_ENFORCED].Id;
            ManageRegAndNomCtrl.StudentDetails details = new ManageRegAndNomCtrl.StudentDetails();
            details.id = eoi.Id;
            details.registrationStatus = 'Approved';
            details.isRegistrations = false;
            details.contactInfo = eoi;
            details.mobileNumber = '61412345678';
            details.businessOrgAccount = String.valueOf(businessOrgAcctId);
            Test.startTest();
            ManageRegAndNomCtrl.RegistrationNominationUpdateResponse response = ManageRegAndNomCtrl.updateRegistrationOrNominationStatus(details);
            Test.stopTest();
            System.assert(!response.isSuccess, 'Incorrect validation of contact information.');
        }
    }
   

    @isTest
    static void updateRegistrationStatusTest(){  
        final User PORTAL_SYS_ADMIN = TestDataFactoryUser.selectUserSystemAdministrator;      
        System.runAs(PORTAL_SYS_ADMIN){     
            Id businessOrgAcctId = [SELECT Id FROM Account WHERE Name = 'Business Org Account' WITH SECURITY_ENFORCED].Id;
            hed__Course_Enrollment__c learner = [SELECT Id FROM hed__Course_Enrollment__c WITH SECURITY_ENFORCED LIMIT 1];
            ManageRegAndNomCtrl.StudentDetails details = new ManageRegAndNomCtrl.StudentDetails();
            details.id = learner.Id;
            details.registrationStatus = 'Active';
            details.isRegistrations = true;
            details.contactInfo = new Expression_of_Interest__c();
            details.mobileNumber = '';
            details.businessOrgAccount = String.valueOf(businessOrgAcctId);
            Test.startTest();
            ManageRegAndNomCtrl.RegistrationNominationUpdateResponse response = ManageRegAndNomCtrl.updateRegistrationOrNominationStatus(details);
            Test.stopTest();
            System.assert(response.isSuccess, 'Failed to update Registration status.');
        }
    }
    
    @isTest
    static void getRegistrationsAndNominationsTest(){
        Test.startTest();
        Contact contact = [SELECT Id, hed__Primary_Organization__c FROM Contact WHERE FirstName = 'cce contact' WITH SECURITY_ENFORCED LIMIT 1];

        BuyerGroup bg = new BuyerGroup();
        bg.Name = 'OPE BuyerGroup';
        insert bg;

        CCECorporateUserCtrl.CorporateUserDetails userDetails = CCECorporateUserCtrl.enablePortalUser(contact.Id, CATEGORY_CCE);   
        User user = [SELECT Id, Name FROM User WHERE Id =: userDetails.userId WITH SECURITY_ENFORCED LIMIT 1];

        System.runAs(user){
            ManageRegAndNomCtrl.RecordSearchParams params = new ManageRegAndNomCtrl.RecordSearchParams();
            params.isRegistrations = true;
            params.courseName = '';
            params.firstName = '';
            params.lastName = '';
            params.email = '';
            params.mobile = '';
            params.status = '';
            params.birthday = '';
        
            List<ManageRegAndNomCtrl.ManageRegistrationorNominationDetails> registrations = ManageRegAndNomCtrl.getRegistrationsAndNominations(params, contact.hed__Primary_Organization__c); 
            System.assertEquals(1, registrations.size(), 'Incorrect number of records retrieved.');
            params.isRegistrations = false;
            List<ManageRegAndNomCtrl.ManageRegistrationorNominationDetails> nominations = ManageRegAndNomCtrl.getRegistrationsAndNominations(params, contact.hed__Primary_Organization__c); 
            System.assertEquals(1, nominations.size(), 'Incorrect number of records retrieved.');
        }
        Test.stopTest();
    }

    @isTest
    static void formatDateTest(){
        final User PORTAL_SYS_ADMIN = TestDataFactoryUser.selectUserSystemAdministrator;      
        System.runAs(PORTAL_SYS_ADMIN){    
            Test.startTest(); 
            String formattedDateString = ManageRegAndNomCtrl.formatDate(Date.newInstance(1990, 2, 17));
            Test.stopTest();
            System.assert(formattedDateString != '', 'Invalid Date Format');
        }
    }

    @isTest
    static void validateRegistrationEndDate(){  
        BypassTriggers__c bypass = [SELECT Id, Bypass__c FROM BypassTriggers__c WHERE SetupOwnerId =: UserInfo.getOrganizationId() WITH SECURITY_ENFORCED LIMIT 1];
        bypass.Bypass__c = false;
        update bypass;
        final User PORTAL_SYS_ADMIN = TestDataFactoryUser.selectUserSystemAdministrator;      
        System.runAs(PORTAL_SYS_ADMIN){     
            Id businessOrgAcctId = [SELECT Id FROM Account WHERE Name = 'Business Org Account' WITH SECURITY_ENFORCED].Id;

            List<hed__Course_Offering__c> courseOfferings = [SELECT Id, Name, hed__Course__c, IsActive__c, Program_Offering__c, Registration_End_Date__c, hed__Capacity__c FROM hed__Course_Offering__c WITH SECURITY_ENFORCED];
            List<hed__Course_Offering__c> courseOfferingsToUpdate = new List<hed__Course_Offering__c>();
            for(hed__Course_Offering__c courseOffering : courseOfferings){
                hed__Course_Offering__c courseOfferingToUpdate = new hed__Course_Offering__c();
                courseOfferingToUpdate.id = courseOffering.id;
                courseOfferingToUpdate.Registration_End_Date__c = Date.today().addDays(-1);
                courseOfferingsToUpdate.add(courseOfferingToUpdate);
            }
            update courseOfferingsToUpdate;

            Test.startTest();
            List<Expression_of_Interest__c> expOfInterestList = [SELECT Id, Name, Pricebook_Entry_ID__c, First_Name__c, Program_Offering__c, Course_Offering__c, Last_Name__c, Email__c, Birthdate__c,Accessibility_Requirement__c, Dietary_Requirement__c,Mobile__c, Mobile_Locale__c FROM Expression_of_Interest__c WITH SECURITY_ENFORCED];
            ManageRegAndNomCtrl.StudentDetails details = new ManageRegAndNomCtrl.StudentDetails();
            details.id = expOfInterestList[0].Id;
            details.registrationStatus = 'Approved';
            details.isRegistrations = false;
            details.contactInfo = expOfInterestList[0];
            details.mobileNumber = '61412345678';
            details.businessOrgAccount = String.valueOf(businessOrgAcctId);
            ManageRegAndNomCtrl.RegistrationNominationUpdateResponse response = ManageRegAndNomCtrl.updateRegistrationOrNominationStatus(details);
            Test.stopTest();
            System.assert(!response.isSuccess, 'Registration should be closed.');
        }
    }

    @isTest
    static void validateCapacity(){  
        BypassTriggers__c bypass = [SELECT Id, Bypass__c FROM BypassTriggers__c WHERE SetupOwnerId =: UserInfo.getOrganizationId() WITH SECURITY_ENFORCED LIMIT 1];
        bypass.Bypass__c = false;
        update bypass;
        final User PORTAL_SYS_ADMIN = TestDataFactoryUser.selectUserSystemAdministrator;      
        System.runAs(PORTAL_SYS_ADMIN){     
            Id businessOrgAcctId = [SELECT Id FROM Account WHERE Name = 'Business Org Account' WITH SECURITY_ENFORCED].Id;

            List<hed__Course_Offering__c> courseOfferings = [SELECT Id, Name, hed__Course__c, IsActive__c, Program_Offering__c, Registration_End_Date__c, hed__Capacity__c FROM hed__Course_Offering__c];
            List<hed__Course_Offering__c> courseOfferingsToUpdate = new List<hed__Course_Offering__c>();
            for(hed__Course_Offering__c courseOffering : courseOfferings){
                hed__Course_Offering__c courseOfferingToUpdate = new hed__Course_Offering__c();
                courseOfferingToUpdate.id = courseOffering.id;
                courseOfferingToUpdate.hed__Capacity__c = 2;
                courseOfferingsToUpdate.add(courseOfferingToUpdate);
            }
            update courseOfferingsToUpdate;
            
            List<hed__Course_Enrollment__c> learners = new List<hed__Course_Enrollment__c>();
            for (Integer i = 0; i < 2; i++) {
                learners.add(new hed__Course_Enrollment__c(hed__Course_Offering__c = courseOfferings[0].Id, hed__Status__c  = 'Active'));
            }
            insert learners;

            Test.startTest();
            List<Expression_of_Interest__c> expOfInterestList = [SELECT Id, Name, Pricebook_Entry_ID__c, First_Name__c, Program_Offering__c, Course_Offering__c, Last_Name__c, Email__c, Birthdate__c,Accessibility_Requirement__c, Dietary_Requirement__c,Mobile__c, Mobile_Locale__c FROM Expression_of_Interest__c WITH SECURITY_ENFORCED];
            ManageRegAndNomCtrl.StudentDetails details = new ManageRegAndNomCtrl.StudentDetails();
            details.id = expOfInterestList[0].Id;
            details.registrationStatus = 'Approved';
            details.isRegistrations = false;
            details.contactInfo = expOfInterestList[0];
            details.mobileNumber = '61412345678';
            details.businessOrgAccount = String.valueOf(businessOrgAcctId);
            ManageRegAndNomCtrl.RegistrationNominationUpdateResponse response = ManageRegAndNomCtrl.updateRegistrationOrNominationStatus(details);
            
            Test.stopTest();
            System.assert(!response.isSuccess, 'Registration already full capacity.');
        }
    }

    private static void createRecord(){
        final User PORTAL_SYS_ADMIN = TestDataFactoryUser.selectUserSystemAdministrator;      
        System.runAs(PORTAL_SYS_ADMIN){ 
            Account univAccount = new Account(Name='PortalAccount', RecordTypeId = ACCT_UNIV_DEP_ID, Organization_Unit_Level__c = '2');
            Database.insert(univAccount);

            Account portalAccount = new Account(Name='Business Org Account', RecordTypeId = ACCT_BUSINESS_ORG_ID, Organization_Unit_Level__c = '2');
            Database.insert(portalAccount);

            Contact newContact = new Contact(   
            FirstName = 'cce contact', 
            LastName = 'test rec', 
            hed__Primary_Organization__c = portalAccount.Id,                
            Birthdate = Date.newInstance(1990, 2, 17), 
            MobilePhone ='0412345678', 
            ContactMobile_Locale__c = 'Australia (+61)',
            Work_Email__c = 'test@workemail.com',
            hed__Preferred_Email__c = 'Alternate Email',
            hed__AlternateEmail__c = 'testqtest@emailemail.com',
            Position__c = 'Position',
            Company_Name__c = 'Company Name'
            );
            
            insert newContact;
            List<Contact> contactList = new List<Contact>();
            contactList.add(newContact);
                   
            BuyerGroup bg = TestDataFactory.createTestBuyerGroup(true);
            TestDataFactory.createTestBuyerGroupMember(true, portalAccount.Id, bg.Id);
            CommerceEntitlementPolicy commerceEntl = new CommerceEntitlementPolicy(Name = 'Test Entitlement', CanViewProduct = true, CanViewPrice = true, IsActive = true);
            insert commerceEntl;
            CommerceEntitlementBuyerGroup commerceEntbg = new CommerceEntitlementBuyerGroup(BuyerGroupId = bg.Id, PolicyId =commerceEntl.Id);
            insert commerceEntbg;

            
            List<Opportunity> oppList = TestDataFactory.createClosedWonOpportunities(1,portalAccount.Id,newContact.Id);
            insert oppList;

            List<Product_Specification__c> prodSpecList = TestDataFactory.retrieveCCEProductSpecifications();
            
            List<Product_Request__c> productRequests = TestDataFactory.createTestProductRequestRecords(1,prodSpecList[0].Id);
            for(Product_Request__c productRequest : productRequests){
                productRequest.RecordTypeId = RT_ACTIVITY_ID;
            }
            insert productRequests;
            
            List<hed__Course__c> courses = TestDataFactory.createTestCourseRecords(1, univAccount.Id, productRequests[0].Id);
            insert courses;

            List<Product2> plist = [SELECT Id, Name, Course__c FROM Product2];

            CommerceEntitlementProduct commerceProduct = new CommerceEntitlementProduct(PolicyId = commerceEntl.Id, ProductId = plist[0].Id);
            insert commerceProduct;

            List<hed__Term__c> terms = TestDataFactory.createTestTermRecords(1, univAccount.Id);
            insert terms;
            
            List<hed__Course_Offering__c> courseOfferings = TestDataFactory.createTestCourseOfferingRecord(1, courses, terms);
            for(hed__Course_Offering__c c : courseOfferings){
                c.Registration_End_Date__c = Date.today().addDays(5);
            }
            insert courseOfferings;

            List<Contact> contacts = TestDataFactory.createTestContactRecords(1);
            for(Integer i =0;i<contacts.size();i++){
                contacts[i].Registered_Email__c = 'testIdeaFormUser'+i+'@maildrop.cc';
            }
            insert contacts;
            
            List<hed__Course_Enrollment__c> students = new List<hed__Course_Enrollment__c>();
            for(Contact contact : contacts){
                hed__Course_Enrollment__c student = new hed__Course_Enrollment__c();
                student.hed__Contact__c = contact.Id;
                student.RecordTypeId = STUDENT_RT_ID;
                student.Paid_in_Full__c = 'No';
                student.Payment_Method__c = 'Invoice';
                student.hed__Course_Offering__c = courseOfferings[0].Id;
                students.add(student);
            }
            insert students;

            Expression_of_Interest__c eoi =  new Expression_of_Interest__c(
                First_Name__c = 'test con 1',
                Last_Name__c = 'rec',
                Email__c = 'testcon1@email.com',
                Position__c = 'Position',
                Company_Name__c = 'Company Name',
                Birthdate__c = Date.newInstance(1990, 2, 17),
                Mobile__c = '0412345678',
                Mobile_Locale__c = 'Australia (+61)',
                Course_Offering__c = courseOfferings[0].Id,
                Type__c = 'Nomination',
                Status__c = 'Pending',
                Account__c = portalAccount.Id
            );

            insert eoi;

            Contact contact = new Contact();
            contact.FirstName = 'Contact';
            contact.LastName = 'Record';
            contact.Email = 'cone@rec1.com'; 
            contact.Work_Email__c = 'con@rec1.com'; 
            contact.Registered_Email__c ='con@rec1.com';
            contact.hed__Preferred_Email__c = 'Alternate Email';
            contact.hed__AlternateEmail__c = 'conpref@rec1.com';
            contact.Position__c = 'Position';
            contact.Company_Name__C = 'Company Name';
            contact.Birthdate = Date.newInstance(1991, 2, 17);
            contact.MobilePhone ='0412345678';
            contact.ContactMobile_Locale__c = 'Australia (+61)';
            contact.RecordTypeId = RT_CONTACT_PERSON_ID;
            insert contact;

            WebStore testWebStore = new WebStore(Name='CCE', DefaultLanguage='en_US');
            insert testWebStore;

            Pricebook2 priceBook;
            pricebook = new Pricebook2(isActive = true, id = Test.getStandardPricebookId());
            update pricebook;
        }
    } 
}