src/core-crm/objects/BuyerGroup/fields/Product_Request__c.field-meta.xml
<CustomField>
    <fullName>Product_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the parent Standing Offer Arrangement Product request</description>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Buyer Groups</relationshipLabel>
    <relationshipName>Buyer_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Address__c/hed__Address__c.object-meta.xml
<CustomObject>
    <description>Stores address information. To support multiple and seasonal addresses.</description>
    <label>Address</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course__c/hed__Course__c.object-meta.xml
<CustomObject>
    <description>Academic Course offered by a Department or School, for example, English 101 or Ancient History.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <description>The department (Account record) that offers this Course.</description>
    <inlineHelpText>The department (Account record) that offers this Course.</inlineHelpText>
    <label>Department</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/core-crm/objects/hed__Course__c/fields/Owning_School_Discipline_Area__c.field-meta.xml
<CustomField>
    <fullName>Owning_School_Discipline_Area__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owning School / Discipline / Area</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Courses (Owning School / Discipline / Area)</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course__c/fields/ProductRequestID__c.field-meta.xml
<CustomField>
    <fullName>ProductRequestID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Program_Plan__c/hed__Program_Plan__c.object-meta.xml
<CustomObject>
    <description>Links Courses to an Academic Program to create a path for students to follow. An Academic Program can list multiple Courses, and a Course can be associated with multiple Academic Programs.</description>
    <label>Program Plan</label>
    <nameField>
        <label>Program Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Program_Plan__c/fields/Associated_Standard_Award__c.field-meta.xml
<CustomField>
    <fullName>Associated_Standard_Award__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Associated Standard Award</label>
    <referenceTo>hed__Program_Plan__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Program_Plan__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Academic Program this Program Plan is for, for example, BA in Philosophy.</description>
    <inlineHelpText>The Academic Program this Program Plan is for, for example, BA in Philosophy.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Program_Plan__c/fields/Owning_Faculty__c.field-meta.xml
<CustomField>
    <fullName>Owning_Faculty__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the Program Plan&apos;s owning faculty.</description>
    <label>Owning Faculty</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Program Plans (Owning Faculty)</relationshipLabel>
    <relationshipName>Program_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Program_Plan__c/fields/Product_Request__c.field-meta.xml
<CustomField>
    <fullName>Product_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the related Product Request record of the Program Plan.</description>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Program_Plan__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <description>This record type will be used to create a Program. This can be a combination of a Unit, a Module, a Short Course, or an Activity.</description>
    <label>Program</label>
</RecordType>

src/core-crm/objects/Product2/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Product2/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Plan</label>
    <referenceTo>hed__Program_Plan__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Product_Request__c/Product_Request__c.object-meta.xml
<CustomObject>
    <label>Product Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Product Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Product_Request__c/fields/OPE_Program_Plan_Type__c.field-meta.xml
<CustomField>
    <fullName>OPE_Program_Plan_Type__c</fullName>
    <description>This is a hidden field that stores the Program Type of a Program Plan if the Product Request is Program. This will be used in tab visibilities of the flexipage.</description>
    <label>OPE Program Plan Type</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Product_Request__c/fields/Product_Specification__c.field-meta.xml
<CustomField>
    <fullName>Product_Specification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Specification</label>
    <referenceTo>Product_Specification__c</referenceTo>
    <relationshipLabel>Product Requests</relationshipLabel>
    <relationshipName>Product_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Product_Request__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <description>This record type will be used to create a Program. This can be a combination of a Unit, a Module, a Short Course, or an Activity.</description>
    <label>Program</label>
</RecordType>

src/core-crm/objects/Product_Specification__c/Product_Specification__c.object-meta.xml
<CustomObject>
    <label>Product Specification</label>
    <nameField>
        <displayFormat>PS-{00000}</displayFormat>
        <label>Product Specification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Specifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Product_Specification__c/recordTypes/CCE.recordType-meta.xml
<RecordType>
    <fullName>CCE</fullName>
    <active>true</active>
    <description>Used to Design products which are the result of a closed won Opportunity in Salesforce.</description>
    <label>CCE</label>
</RecordType>

src/core-crm/objects/Product_Specification__c/recordTypes/OPE.recordType-meta.xml
<RecordType>
    <fullName>OPE</fullName>
    <active>true</active>
    <description>Used to Design products which are the result of an idea request from a faculty.</description>
    <label>OPE</label>
</RecordType>

src/core-crm/objects/Related_Product_Request__c/Related_Product_Request__c.object-meta.xml
<CustomObject>
    <label>Related Product Request</label>
    <nameField>
        <label>Related Product Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Related Product Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Related_Product_Request__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Related Product Requests</relationshipLabel>
    <relationshipName>Course</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/classes/AddProductRequestCtrl.cls
/**
 * @description Controller Class for addProductRequest LWC
 * @see ../lwc/addProductRequest
 * @author Accenture
 * @history
 *    | Developer                 | Date                  | JIRA                 | Change Summary                       |
      |---------------------------|-----------------------|----------------------|--------------------------------------|
      | roy.nino.s.regala         | September 28, 2021    | DEPP-40,42           | Created file                         | 
      | angelika.j.s.galang       | December 17, 2021     | DEPP-1088,1096       | Modified to handle OPE records       | 
      | adrian.c.habasa           | January  20, 2022     | DEPP-1471            | Added method to get QUTeX Account Id | 
      | roy.nino.s.regala         | March 10, 2022        | DEPP-1747            | Added search method                  |
      | john.m.tambasen           | July 07, 2022         | DEPP-2590            | Added search method with Program     |
      | john.m.tambasen           | July 28, 2022         | DEPP-3480            | for creation of needed records       |
      | alexander.cadalin         | August 04, 2022       | DEPP-2498            | appened to above for SOA             |
 */
public with sharing class AddProductRequestCtrl {

    /**
     * @description get list of users searched 
     * @param filterString - search string for filter
     * @return list of users formatted for customSearch
     */
    @AuraEnabled(cacheable=true)
    public static List<Map<String,String>> getSearchedUsers(String filterString){
        filterString = '%' + filterString + '%';
        List<Map<String,String>> userMap = new List<Map<String,String>>();
        
        for(User usr : [
            SELECT Id, Name, Division
            FROM User
            WHERE (
                Name LIKE :filterString OR
                Name = :filterString
            )
        ]){
            userMap.add(new Map<String,String>{
                'id' => usr.Id,
                'label' => usr.Name,
                'meta' => usr.Division
            });
        }
        return userMap;
    }   

    /**
     * @description get record type settings and field layout settings 
     * @param filterString - search string for filter
     * @param filterPRList - all current children of program
     * @param prodSpecRecordType - recordtype of program
     * @return list product request
     */
    @AuraEnabled(cacheable=true)
    public static List<Product_Request__c> getSearchedProductRequests(String filterString, List<Product_Request__c> filterPRList, String prodSpecRecordType, Boolean isSOA){
        filterString = '%' + filterString + '%';
        
        List<Id> productRequestIds = new List<Id>();

        for(Product2 product: [ SELECT Id, Course__c, Course__r.ProductRequestID__c, IsActive
                                FROM Product2 
                                WHERE (Course__r.Name LIKE :filterString 
                                OR Course__r.Name =:filterString)
                                AND Course__r.ProductRequestID__c NOT IN: filterPRList
                                AND Course__r.ProductRequestID__r.Product_Specification__r.RecordType.DeveloperName =: prodSpecRecordType
                                AND Course__r.ProductRequestID__r.OPE_Program_Plan_Type__c != 'Prescribed Program'
                                AND IsActive = true
                                ]){

            productRequestIds.add(product.Course__r.ProductRequestID__c);
        }

        //add the programs only if searching for SOA
        if(isSOA){
            for(Product2 product: [ SELECT Id, Name, IsActive, Program_Plan__r.Product_Request__c, Program_Plan__r.Product_Request__r.Id, Program_Plan__r.Product_Request__r.Product_Specification__r.RecordType.DeveloperName
                                    FROM Product2 
                                    WHERE (Name LIKE :filterString 
                                    OR Name =:filterString)
                                    AND Program_Plan__r.Product_Request__r.Id NOT IN: filterPRList
                                    AND Program_Plan__r.Product_Request__r.Product_Specification__r.RecordType.DeveloperName =: prodSpecRecordType
                                    AND IsActive = true 
                                    ]){

                productRequestIds.add(product.Program_Plan__r.Product_Request__c);
            }
        }
        
        List<Product_Request__c> productRequestResults = new List<Product_Request__c>([SELECT ID,Name,
                                                                                        (SELECT Id, Name FROM Courses__r), 
                                                                                        (SELECT Id, Name FROM Program_Plans__r),
                                                                                        RecordType.Name 
                                                                                        FROM Product_Request__c 
                                                                                        WHERE ID IN: productRequestIds]);
        return productRequestResults;
    }

    /**
     * @description get record type settings and field layout settings 
     * @param objectType - object api name of the current record the lwc is at
     * @param filter - id of record types to query
     * @return list of record type mapping
     */
    @AuraEnabled(cacheable=true)
    public static List<Map<String,String>> getRecordTypes(String objectType){
        List<Map<String,String>> recordTypeMap = new List<Map<String,String>>();
        
        for(RecordType rec : [
            SELECT Id, Name, Description
            FROM RecordType
            WHERE SobjectType =: objectType
        ]){
            recordTypeMap.add(new Map<String,String>{
                'label' => rec.Name,
                'description' => rec.Description,
                'value' => rec.Id
            });
        }
        return recordTypeMap;
    }   

     /**
     * @description gets id of QUTeX Account
     */
    @AuraEnabled(cacheable=true)
    public static String getAccountId(){
      Account acct = [Select Id from Account WHERE Name ='QUTeX Products' LIMIT 1];
      return acct.Id;
   }

    /**
     * 
     *  @description upsert hed__address__c record
     * @param accountId - Primary account Id
     * @param accountName - Primary account name
     */
    @AuraEnabled
    public static void createBuyerGroupAndEntitlement(
        Id productRequestId,
        String accountId, 
        String accountName,
        Boolean isCorporateBundle,
        Boolean isSoa
    ){
        BuyerGroup bg = new BuyerGroup();

        if(isCorporateBundle) {
            //create BuyerGroup
            BuyerGroup bgInsert = new BuyerGroup();
            String accName = accountName;

            if(accName.length() > 80) {
                accName = accName.substring(0, 80);
            }

            bgInsert.Name = accName + ' ' + String.valueofGmt(System.now());
            bgInsert.Product_Request__c = productRequestId;
            insert bgInsert;
            bg = bgInsert;
        } else if(isSoa) {
            BuyerGroup bgQuery = [SELECT Id FROM BuyerGroup WHERE Product_Request__c = :productRequestId];
            bg = bgQuery;
        }

        List<BuyerGroupMember> currentBgMemberList =[SELECT 
                                                        Id, Name, BuyerGroupId, BuyerId
                                                    FROM 
                                                        BuyerGroupMember 
                                                    WHERE BuyerId =: accountId
                                                        AND BuyerGroupId = :bg.Id];
        //if BuyerGroupMember doesnt exist
        if(currentBgMemberList.size() == 0){
            //insert BuyerGroupMember
            BuyerGroupMember bgMemberInsert = new BuyerGroupMember();
            bgMemberInsert.BuyerGroupId = bg.Id;
            bgMemberInsert.BuyerId = accountId;
            insert bgMemberInsert;
        }

        //get the CCE store
        WebStore webStoreCCE = [SELECT Id From WebStore WHERE Name = 'CCE' LIMIT 1];

        //insert WebStoreBuyerGroup
        WebStoreBuyerGroup webStoreBgInsert = new WebStoreBuyerGroup();
        webStoreBgInsert.BuyerGroupId = bg.Id;
        webStoreBgInsert.WebStoreId = webStoreCCE.Id;
        insert webStoreBgInsert;

        //insert CommerceEntitlementPolicy
        CommerceEntitlementPolicy commerceEntitlementInsert = new CommerceEntitlementPolicy();
        commerceEntitlementInsert.CanViewPrice = true;
        commerceEntitlementInsert.CanViewProduct = true;
        commerceEntitlementInsert.IsActive = true;
        commerceEntitlementInsert.Name = accountName + ' ' + String.valueofGmt(System.now());
        insert commerceEntitlementInsert;

        //insert CommerceEntitlementBuyerGroup
        CommerceEntitlementBuyerGroup commerceEntitlementBgInsert = new CommerceEntitlementBuyerGroup();
        commerceEntitlementBgInsert.BuyerGroupId = bg.Id;
        commerceEntitlementBgInsert.PolicyId = commerceEntitlementInsert.Id;
        insert commerceEntitlementBgInsert;
    }
}