src/core-crm/objects/Lead/fields/Future_Student_Journey_Status__c.field-meta.xml
<CustomField>
    <fullName>Future_Student_Journey_Status__c</fullName>
    <label>Future Student Journey Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Future_Student_Journey_Status</valueSetName>
    </valueSet>
</CustomField>

src/core-crm/objects/Lead/fields/Marketing_Interaction_Score__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Interaction_Score__c</fullName>
    <label>Marketing Interaction Score</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Lead/fields/Work_Email__c.field-meta.xml
<CustomField>
    <fullName>Work_Email__c</fullName>
    <inlineHelpText>This field captures the work email of the contact.</inlineHelpText>
    <label>Work Email</label>
    <type>Email</type>
</CustomField>

src/core-crm/objects/Nurture_Track_Configuration__c/Nurture_Track_Configuration__c.object-meta.xml
<CustomObject>
    <label>Nurture Track Configuration</label>
    <nameField>
        <displayFormat>NTC-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nurture Track Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Nurture_Track_Configuration__c/fields/Lead_Score_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Lead_Score_Threshold__c</fullName>
    <description>The Lead Score Threshold for inclusion in the Track

Note: This value needs to be replicated to all cadences in the track</description>
    <label>Lead Score Threshold</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Nurture_Track_Configuration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Cadence Status is used to activate or deactivate the cadence</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/globalValueSets/Future_Student_Journey_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Explore</fullName>
        <default>true</default>
        <label>Explore</label>
    </customValue>
    <customValue>
        <fullName>Apply</fullName>
    </customValue>
    <customValue>
        <fullName>Offer</fullName>
    </customValue>
    <customValue>
        <fullName>Accept-Admit</fullName>
    </customValue>
    <customValue>
        <fullName>Study</fullName>
    </customValue>
    <masterLabel>Future Student Journey Status</masterLabel>
</GlobalValueSet>

src/core-crm/classes/LeadServiceTest.cls
/**
 * @description Test Class for LeadService
 *
 * @see LeadService
 *
 * @author Accenture
 *
 * @history
 *    | Developer                 | Date                  | JIRA         | Change Summary                               |
      |---------------------------|-----------------------|--------------|----------------------------------------------|
      | mark.j.mahilum            | June 13,2023          | DEPP-5798    | Created file                                 |
      | mark.j.mahilum            | July 28, 2023         | DEPP-6106    | Updated test class to cover can nurture logic|
*/
@isTest
private class LeadServiceTest {
    private static Integer recordsCount = 5;
    private static final String LASTNAME = 'Testlastname';
    private static final String EMAIL = 'testmail@mail.test';
    private static final String COMPANY = 'Testcompany';
    private static final String LEAD_TYPE = 'Learner';

    @testSetup
    static void testSetup() {
        TestDataFactory.generateTestUsers(new List<String>{ 'QUT_Program_Administrator','QUT_Domestic_Future_Student_Agent' });

        System.runAs(TestDataFactory.getProgramAdminUser()) {
            Test.startTest();
            LeadsDAO.newInstance()
                .insertRecords(
                    TestDataFactory.createTestLeadRecords(0, recordsCount),
                    false,
                    AccessLevel.USER_MODE
                );
            Test.stopTest();
        }
    }

    @isTest
    private static void testLeadBatchInsertLeadScoreBelowFifty() {
        System.runAs(TestDataFactory.getProgramAdminUser()) {
            Test.startTest();
            Database.SaveResult[] srList = LeadsDAO.newInstance()
                .insertRecords(
                    TestDataFactory.createTestLeadRecords(recordsCount, recordsCount),
                    false,
                    AccessLevel.USER_MODE
                );
            Test.stopTest();
            
			Set<Id> leadIds = new Set<Id>();             
            for (Database.SaveResult sr : srList) {
                System.assert(sr.isSuccess(), 'A record was not saved.');      
                if (sr.isSuccess()) { 
                    leadIds.add(sr.getId());
                }
            }
            
            for (Lead lead : LeadsDAO.newInstance().getLeadsWithLimit(recordsCount)) {  
                System.assertEquals('New', lead.Status,'Lead Status did not match');
                System.assert(String.isBlank(lead.Future_Student_Journey_Status__c),'Lead Future_Student_Journey_Status__c did not match');
            }
        }
    }
    
    @isTest
    private static void testLeadBatchUpdateLeadScoreAboveFifty() {
        System.runAs(TestDataFactory.getProgramAdminUser()) {
            List<Lead> ldList = LeadsDAO.newInstance().getLeadsWithLimit(recordsCount);
            for (Integer i = 0; i < recordsCount; i++) {
                ldList[i].Email = 'new' + i + EMAIL;
                ldList[i].Work_Email__c = 'newwork' + i + EMAIL;
                ldList[i].Marketing_Interaction_Score__c  = 256.00;
            }

            Test.startTest();
            Database.SaveResult[] srList = LeadsDAO.newInstance()
                .updateRecords(ldList, false, AccessLevel.SYSTEM_MODE);
            Test.stopTest();
			
            Set<Id> leadIds = new Set<Id>();  
            for (Database.SaveResult sr : srList) {
                System.assert(sr.isSuccess(), 'A record was not saved.');
                if (sr.isSuccess()) { 
                    leadIds.add(sr.getId());
                }
            }
            
            for (Lead lead : LeadsDAO.newInstance().getLeadsWithLimit(recordsCount)) {  
                System.assertEquals('Engaging', lead.Status,'Lead Status did not match');
                System.assertEquals('Explore', lead.Future_Student_Journey_Status__c,'Lead Future_Student_Journey_Status__c did not match');
            }
        }
    }
    
    @isTest
    private static void testLeadBatchUpdateLeadScoreAboveOneHundred() {
        System.runAs(TestDataFactory.getProgramAdminUser()) {
            List<Lead> ldList = LeadsDAO.newInstance().getLeadsWithLimit(recordsCount);
            for (Integer i = 0; i < recordsCount; i++) {
                ldList[i].Email = 'new' + i + EMAIL;
                ldList[i].Work_Email__c = 'newwork' + i + EMAIL;
                ldList[i].Marketing_Interaction_Score__c  = 300.00;
            }

            Test.startTest();
            Database.SaveResult[] srList = LeadsDAO.newInstance()
                .updateRecords(ldList, false, AccessLevel.SYSTEM_MODE);
            Test.stopTest();
			
            Set<Id> leadIds = new Set<Id>();  
            for (Database.SaveResult sr : srList) {
                System.assert(sr.isSuccess(), 'A record was not saved.');
                if (sr.isSuccess()) { 
                    leadIds.add(sr.getId());
                }
            }
            
            for (Lead lead :LeadsDAO.newInstance().getLeadsWithLimit(recordsCount)) {  
                System.assertEquals('Nurturing', lead.Status,'Lead Status did not match');
                System.assertEquals('Explore', lead.Future_Student_Journey_Status__c,'Lead Future_Student_Journey_Status__c did not match');
            }
        }
    }

    @isTest
    private static void testLeadBatchUpdateCanNurtureIsCheck() {
        System.runAs(TestDataFactory.getProgramAdminUser()) {
            
            List<Nurture_Track_Configuration__c> nurtureList = new List<Nurture_Track_Configuration__c>();
            Nurture_Track_Configuration__c nurtureConfig = new Nurture_Track_Configuration__c();
            nurtureConfig.Lead_Score_Threshold__c = 1;
            nurtureConfig.Status__c = 'Active';
            nurtureList.add(nurtureConfig);
            NurtureTrackConfigurationsDAO.newInstance().insertRecords(nurtureList, false, AccessLevel.SYSTEM_MODE);  
            
            List<Lead> ldList = LeadsDAO.newInstance().getLeadsWithLimit(recordsCount);
            for (Integer i = 0; i < recordsCount; i++) {
                ldList[i].Email = 'new' + i + EMAIL;
                ldList[i].Work_Email__c = 'newwork' + i + EMAIL;
                ldList[i].Marketing_Interaction_Score__c  = 300.00;
            }
            
            Test.startTest();
            Database.SaveResult[] srList = LeadsDAO.newInstance()
                .updateRecords(ldList, false, AccessLevel.SYSTEM_MODE);
            Test.stopTest();
            
            Set<Id> leadIds = new Set<Id>();  
            for (Database.SaveResult sr : srList) {
                System.assert(sr.isSuccess(), 'A record was not saved.');
                if (sr.isSuccess()) { 
                    leadIds.add(sr.getId());
                }
            }
            
            for (Lead lead :LeadsDAO.newInstance().getLeadsWithLimit(recordsCount)) {  
                System.assert(lead.Can_Nurture__c,'Can Nurture is not ticked');
            }
        }
    }

    @isTest
    private static void testGetLeadCalculatedCadence() {
        System.runAs(TestDataFactory.getProgramAdminUser()) {
            
            List<Lead> ldList = LeadsDAO.newInstance().getLeadsWithLimit(recordsCount);
            for (Integer i = 0; i < recordsCount; i++) {
                ldList[i].Email = 'new' + i + EMAIL;
                ldList[i].Work_Email__c = 'newwork' + i + EMAIL;
                ldList[i].Marketing_Interaction_Score__c  = 300.00;
                ldList[i].Calculated_Cadence__c = 'Test Cadences automated';
            }
            Test.startTest();
            LeadsDAO.newInstance().updateRecords(ldList, false, AccessLevel.SYSTEM_MODE);                
            Test.stopTest();
            System.assert(![SELECT Id FROM AsyncApexJob WHERE ApexClass.Name = 'SalesCadenceCalloutService'].isEmpty() , 'SalesCadenceCalloutService Queueable Job was not executed');
        }
    }    

}