src/core-crm/objects/Lead/fields/Marketing_Segmentation__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Segmentation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Segmentation</label>
    <referenceTo>Marketing_Segmentation__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Lead_Score_Configuration__c/Lead_Score_Configuration__c.object-meta.xml
<CustomObject>
    <label>Lead Score Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Score Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Lead_Score_Configuration__c/fields/Max_Score__c.field-meta.xml
<CustomField>
    <fullName>Max_Score__c</fullName>
    <description>The max score a category is allowed to accumulate</description>
    <label>Max Score</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Lead_Score_Configuration__c/fields/Parent_Category__c.field-meta.xml
<CustomField>
    <fullName>Parent_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Parent Category the sub category belongs to. This would be null for category record types</description>
    <inlineHelpText>The Category the scoring for this Sub Category will be added to</inlineHelpText>
    <label>Parent Category</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Lead_Score_Configuration__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Category</value>
        </filterItems>
        <filterItems>
            <field>Lead_Score_Configuration__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Configuration</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Lead_Score_Configuration__c</referenceTo>
    <relationshipLabel>Lead Score Configurations</relationshipLabel>
    <relationshipName>Lead_Score_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Lead_Score_Configuration__c/fields/Score_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Score_Allocation__c</fullName>
    <description>Score that should be allocated for each instance of the interaction</description>
    <label>Score Allocation</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Lead_Score_Configuration__c/fields/Time_Limit_Months__c.field-meta.xml
<CustomField>
    <fullName>Time_Limit_Months__c</fullName>
    <description>The number months the calculation needs to consider activities for from current month</description>
    <label>Time Limit (Months)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Lead_Score_Configuration__c/recordTypes/Category.recordType-meta.xml
<RecordType>
    <fullName>Category</fullName>
    <active>true</active>
    <label>Category</label>
</RecordType>

src/core-crm/objects/Lead_Score_Configuration__c/recordTypes/Configuration.recordType-meta.xml
<RecordType>
    <fullName>Configuration</fullName>
    <active>true</active>
    <label>Configuration</label>
</RecordType>

src/core-crm/objects/Marketing_Segmentation__c/Marketing_Segmentation__c.object-meta.xml
<CustomObject>
    <label>Marketing Segmentation</label>
    <nameField>
        <displayFormat>MS - {000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Segmentations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Marketing_Segmentation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Marketing Segmentations</relationshipLabel>
    <relationshipName>Marketing_Segmentations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Marketing_Segmentation__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Marketing Segmentations</relationshipLabel>
    <relationshipName>Marketing_Segmentations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/classes/LeadScoreConfigCourseLevelService.cls
/**
 * @description Service Class for Course Level Lead Score Configuration
 * 
 * @author Accenture
 *
 * @history
 *
 *    | Developer                      | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | eccarius.munoz                 | October 02, 2023      | DEPP-5866              | Created file                 |
      | arsenio.jr.dayrit              | November 13, 2023     | DEPP-7210              | Updated getLeadScore Method  |
      |                                |                       |                        |                              |
 */
public with sharing class LeadScoreConfigCourseLevelService {
    public static void getLeadScoreConfig(Lead_Score_Configuration__c leadScoreConfig, LeadScoreConfigCourseLevel leadScoreConfigCourseLevel){
        String category = 'Course Level';
        Boolean isForCourseLevel = validateIfForCourseLevel(leadScoreConfig, category);
        if(isForCourseLevel){ 
            leadScoreConfigCourseLevel.setTimeLimit(Integer.valueOf(leadScoreConfig.Time_Limit_Months__c));
            leadScoreConfigCourseLevel.setMaxScore(Integer.valueOf(leadScoreConfig.Max_Score__c));
        }

        Boolean isSubCategory = validateSubCategory(leadScoreConfig, category);
        if(isSubCategory){
            if(leadScoreConfig.Name == LeadScoreConfigurationDAO.CONFIG_SUB_CATEGORY_POSTGRAD){
                leadScoreConfigCourseLevel.setStudyLevelPostGrad(Integer.valueOf(leadScoreConfig.Score_Allocation__c));
            }
            else if(leadScoreConfig.Name == LeadScoreConfigurationDAO.CONFIG_SUB_CATEGORY_HIGHER_DEGREE){
                leadScoreConfigCourseLevel.setStudyLevelHigherDeg(Integer.valueOf(leadScoreConfig.Score_Allocation__c));
            }
            else if(leadScoreConfig.Name == LeadScoreConfigurationDAO.CONFIG_SUB_CATEGORY_SHORT_COURSES){
                leadScoreConfigCourseLevel.setStudyLevelShortCoursePD(Integer.valueOf(leadScoreConfig.Score_Allocation__c));
            }
            else if(leadScoreConfig.Name == LeadScoreConfigurationDAO.CONFIG_SUB_CATEGORY_EXCHANGE_AND_STUDY){
                leadScoreConfigCourseLevel.setStudyLevelExchange(Integer.valueOf(leadScoreConfig.Score_Allocation__c));
            }
            else if(leadScoreConfig.Name == LeadScoreConfigurationDAO.CONFIG_SUB_CATEGORY_IS_BLANK_UPPER){
                leadScoreConfigCourseLevel.setStudyLevelIsBlank(Integer.valueOf(leadScoreConfig.Score_Allocation__c));
            }
            else if(leadScoreConfig.Name == LeadScoreConfigurationDAO.CONFIG_SUB_CATEGORY_UNDERGRAD){
                leadScoreConfigCourseLevel.setStudyLevelUnderGrad(Integer.valueOf(leadScoreConfig.Score_Allocation__c));
            }
        }
    } 

    public static Map<Id, Integer> calculateLeadScore(Map<Id,Marketing_Segmentation__c> marketingSegmentationMap, LeadScoreConfigCourseLevel leadScoreConfigCourseLevel){
  
        Map<Id, Integer> courseLevelMap = new Map<Id, Integer>();

        Integer courseLevelScore = 0;
        for(Marketing_Segmentation__c marketingSeg : marketingSegmentationMap.values()){

            if(courseLevelMap.containsKey(marketingSeg.Contact__c)){
                courseLevelScore = courseLevelMap.get(marketingSeg.Contact__c);
            }else if(courseLevelMap.containsKey(marketingSeg.Lead__c)){
                courseLevelScore = courseLevelMap.get(marketingSeg.Lead__c);
            }else{
                courseLevelScore = 0;
            }

            if(String.isNotBlank(marketingSeg.My_Primary_Study_Level__c)){
                courseLevelScore = getLeadScore(marketingSeg, courseLevelScore, leadScoreConfigCourseLevel);
            }else{
                courseLevelScore = courseLevelScore + leadScoreConfigCourseLevel.getStudyLevelIsBlank();   
            }
            
            Integer score = LeadScoreCalculatorService.validateScore(courseLevelScore, leadScoreConfigCourseLevel.getMaxScore());
            if(marketingSeg.Contact__c != null){
                courseLevelMap.put(marketingSeg.Contact__c, score);
            }
            else if(marketingSeg.Lead__c != null){
                courseLevelMap.put(marketingSeg.Lead__c, score);
            }
        }

        return courseLevelMap;
    }

    private static Integer getLeadScore(Marketing_Segmentation__c marketingSeg, Integer courseLevelScore, LeadScoreConfigCourseLevel leadScoreConfigCourseLevel){
        if(marketingSeg.My_Primary_Study_Level__c == MarketingSegmentationsDAO.STUDY_LEVEL_UNDERGRAD){ 
            courseLevelScore = courseLevelScore + leadScoreConfigCourseLevel.getStudyLevelUnderGrad();
        }
        else if(marketingSeg.My_Primary_Study_Level__c == MarketingSegmentationsDAO.STUDY_LEVEL_POSTGRAD){ 
            courseLevelScore = courseLevelScore + leadScoreConfigCourseLevel.getStudyLevelPostGrad();
        }
        else if(marketingSeg.My_Primary_Study_Level__c == MarketingSegmentationsDAO.STUDY_LEVEL_HIGHER_DEGREE){ 
            courseLevelScore = courseLevelScore + leadScoreConfigCourseLevel.getStudyLevelHigherDeg();
        }
        else if(marketingSeg.My_Primary_Study_Level__c == MarketingSegmentationsDAO.STUDY_LEVEL_SHORT_COURSES){ 
            courseLevelScore = courseLevelScore + leadScoreConfigCourseLevel.getStudyLevelShortCoursePD();
        }
        else if(marketingSeg.My_Primary_Study_Level__c == MarketingSegmentationsDAO.STUDY_LEVEL_EXCHANGE_AND_STUDY){ 
            courseLevelScore = courseLevelScore + leadScoreConfigCourseLevel.getStudyLevelExchange();
        }

        return courseLevelScore;
    }

    private static Boolean validateIfForCourseLevel(Lead_Score_Configuration__c leadScoreConfig, String category) {
        return leadScoreConfig.Name == category && leadScoreConfig.RecordTypeId == LeadScoreConfigurationDAO.RECTYPE_ID_CATEGORY;
    }
    
    private static Boolean validateSubCategory(Lead_Score_Configuration__c leadScoreConfig, String category) {
        return leadScoreConfig.RecordTypeId == LeadScoreConfigurationDAO.RECTYPE_ID_SUB_CATEGORY && leadScoreConfig.Parent_Category__r.Name == category;
    }
}