src/core-crm/objects/Lead/fields/Marketing_Segmentation__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Segmentation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Segmentation</label>
    <referenceTo>Marketing_Segmentation__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Lead_Score_Configuration__c/Lead_Score_Configuration__c.object-meta.xml
<CustomObject>
    <label>Lead Score Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Score Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Lead_Score_Configuration__c/fields/Max_Score__c.field-meta.xml
<CustomField>
    <fullName>Max_Score__c</fullName>
    <description>The max score a category is allowed to accumulate</description>
    <label>Max Score</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Lead_Score_Configuration__c/fields/Parent_Category__c.field-meta.xml
<CustomField>
    <fullName>Parent_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Parent Category the sub category belongs to. This would be null for category record types</description>
    <inlineHelpText>The Category the scoring for this Sub Category will be added to</inlineHelpText>
    <label>Parent Category</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Lead_Score_Configuration__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Category</value>
        </filterItems>
        <filterItems>
            <field>Lead_Score_Configuration__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Configuration</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Lead_Score_Configuration__c</referenceTo>
    <relationshipLabel>Lead Score Configurations</relationshipLabel>
    <relationshipName>Lead_Score_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Lead_Score_Configuration__c/fields/Score_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Score_Allocation__c</fullName>
    <description>Score that should be allocated for each instance of the interaction</description>
    <label>Score Allocation</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Lead_Score_Configuration__c/fields/Time_Limit_Months__c.field-meta.xml
<CustomField>
    <fullName>Time_Limit_Months__c</fullName>
    <description>The number months the calculation needs to consider activities for from current month</description>
    <label>Time Limit (Months)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Lead_Score_Configuration__c/recordTypes/Category.recordType-meta.xml
<RecordType>
    <fullName>Category</fullName>
    <active>true</active>
    <label>Category</label>
</RecordType>

src/core-crm/objects/Lead_Score_Configuration__c/recordTypes/Configuration.recordType-meta.xml
<RecordType>
    <fullName>Configuration</fullName>
    <active>true</active>
    <label>Configuration</label>
</RecordType>

src/core-crm/objects/Marketing_Segmentation__c/Marketing_Segmentation__c.object-meta.xml
<CustomObject>
    <label>Marketing Segmentation</label>
    <nameField>
        <displayFormat>MS - {000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Segmentations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Marketing_Segmentation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Marketing Segmentations</relationshipLabel>
    <relationshipName>Marketing_Segmentations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Marketing_Segmentation__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Marketing Segmentations</relationshipLabel>
    <relationshipName>Marketing_Segmentations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/classes/LeadScoreConfigPrimaryBSAService.cls
/**
 * @description Service Class for Primary BSA Lead Score Configuration
 * 
 * @author Accenture
 *
 * @history
 *
 *    | Developer                      | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | eccarius.munoz                 | October 02, 2023      | DEPP-5866              | Created file                 |
      |                                |                       |                        |                              |
 */
public with sharing class LeadScoreConfigPrimaryBSAService {
    public static void getLeadScoreConfig(Lead_Score_Configuration__c leadScoreConfig, LeadScoreConfigPrimaryBSA leadScoreConfigPrimaryBSA){
        String category = LeadScoreConfigurationDAO.CONFIG_CATEGORY_PRIMARY_BSA;
        Boolean isForPrimaryBSA = leadScoreConfig.Name == category && leadScoreConfig.RecordTypeId == LeadScoreConfigurationDAO.RECTYPE_ID_CATEGORY;
        if(isForPrimaryBSA){ 
            leadScoreConfigPrimaryBSA.setTimeLimit(Integer.valueOf(leadScoreConfig.Time_Limit_Months__c));
            leadScoreConfigPrimaryBSA.setMaxScore(Integer.valueOf(leadScoreConfig.Max_Score__c));
        }

        Boolean isSubCategory = leadScoreConfig.RecordTypeId == LeadScoreConfigurationDAO.RECTYPE_ID_SUB_CATEGORY && leadScoreConfig.Parent_Category__r.Name == category;
        if(isSubCategory && leadScoreConfig.Name == LeadScoreConfigurationDAO.CONFIG_SUB_CATEGORY_IS_UNSURE){
            leadScoreConfigPrimaryBSA.setIsUnsure(Integer.valueOf(leadScoreConfig.Score_Allocation__c));
        }
        else if(isSubCategory && leadScoreConfig.Name == LeadScoreConfigurationDAO.CONFIG_SUB_CATEGORY_IS_NOT_BLANK){
            leadScoreConfigPrimaryBSA.setIsNotBlank(Integer.valueOf(leadScoreConfig.Score_Allocation__c));
        }
        else if(isSubCategory && leadScoreConfig.Name == LeadScoreConfigurationDAO.CONFIG_SUB_CATEGORY_IS_BLANK_UPPER){
            leadScoreConfigPrimaryBSA.setIsBlank(Integer.valueOf(leadScoreConfig.Score_Allocation__c));
        }
    } 

    public static Map<Id, Integer> calculateLeadScore(Map<Id,Marketing_Segmentation__c> marketingSegmentationMap, LeadScoreConfigPrimaryBSA leadScoreConfigPrimaryBSA){
        
        Map<Id, Integer> primaryBSAMap = new Map<Id, Integer>();

        Integer primaryBSACategoryScore = 0;
        for(Marketing_Segmentation__c marketingSeg : marketingSegmentationMap.values()){

            if(primaryBSAMap.containsKey(marketingSeg.Contact__c)){
                primaryBSACategoryScore = primaryBSAMap.get(marketingSeg.Contact__c);
            }else if(primaryBSAMap.containsKey(marketingSeg.Lead__c)){
                primaryBSACategoryScore = primaryBSAMap.get(marketingSeg.Lead__c);
            }else{
                primaryBSACategoryScore = 0;
            }

            if(String.isNotBlank(marketingSeg.My_Primary_BSA__c) && marketingSeg.My_Primary_BSA__c != MarketingSegmentationsDAO.PRIMARY_NSA_BSA_IM_NOT_SURE){ 
                primaryBSACategoryScore = primaryBSACategoryScore + leadScoreConfigPrimaryBSA.getIsNotBlank();
            }
            else if(String.isNotBlank(marketingSeg.My_Primary_BSA__c) && marketingSeg.My_Primary_BSA__c == MarketingSegmentationsDAO.PRIMARY_NSA_BSA_IM_NOT_SURE){ 
                primaryBSACategoryScore = primaryBSACategoryScore + leadScoreConfigPrimaryBSA.getIsUnsure();
            }
            else if(String.isBlank(marketingSeg.My_Primary_BSA__c)){ 
                primaryBSACategoryScore = primaryBSACategoryScore + leadScoreConfigPrimaryBSA.getIsBlank();
            }
            
            Integer score = LeadScoreCalculatorService.validateScore(primaryBSACategoryScore, leadScoreConfigPrimaryBSA.getMaxScore());
            if(marketingSeg.Contact__c != null){
                primaryBSAMap.put(marketingSeg.Contact__c, score);
            }
            else if(marketingSeg.Lead__c != null){
                primaryBSAMap.put(marketingSeg.Lead__c, score);
            }
        }

        return primaryBSAMap;
    }
    
}