src/core-crm/objects/CartItem/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cart Items</relationshipLabel>
    <relationshipName>Cart_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/CartItem/fields/Course_Offering__c.field-meta.xml
<CustomField>
    <fullName>Course_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The associated course offering that’s added to the cart</description>
    <label>Course Offering</label>
    <referenceTo>hed__Course_Offering__c</referenceTo>
    <relationshipLabel>Cart Items</relationshipLabel>
    <relationshipName>Cart_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/CartItem/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>Foreign Key for Integration and Data Migration</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/CartItem/fields/Program_Offering__c.field-meta.xml
<CustomField>
    <fullName>Program_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The associated program offering that’s added to the cart</description>
    <label>Program Offering</label>
    <referenceTo>Program_Offering__c</referenceTo>
    <relationshipLabel>Cart Items</relationshipLabel>
    <relationshipName>Cart_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Contact/fields/Accessibility_Requirement__c.field-meta.xml
<CustomField>
    <fullName>Accessibility_Requirement__c</fullName>
    <label>Accessibility Requirement</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

src/core-crm/objects/Contact/fields/Dietary_Requirement__c.field-meta.xml
<CustomField>
    <fullName>Dietary_Requirement__c</fullName>
    <description>Capture details for learner’s dietary requirements</description>
    <label>Dietary Requirement</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

src/core-crm/objects/Contact/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Foreign Key for Integration and Data Migration</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/core-crm/main/objects/Contact/fields/hed__Primary_Organization__c.field-meta.xml
<CustomField>
    <fullName>hed__Primary_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the main Organization (Account record) this Contact is associated with.</description>
    <inlineHelpText>Lookup to the main Organization (Account record) this Contact is associated with.</inlineHelpText>
    <label>Primary Business Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts (Primary Organization)</relationshipLabel>
    <relationshipName>Organization_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Contact/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>Job Title</description>
    <label>Position</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/hed__Course_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Represents a connection to a Course Offering.</description>
    <label>Course Connection</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Course Connection ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Enrollment__c/fields/Cart_ID__c.field-meta.xml
<CustomField>
    <fullName>Cart_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cart ID</label>
    <referenceTo>WebCart</referenceTo>
    <relationshipLabel>Course Connections</relationshipLabel>
    <relationshipName>Course_Connections</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/hed__Contact__c.field-meta.xml
<CustomField>
    <fullName>hed__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student or faculty member participating in this Course Offering.</description>
    <inlineHelpText>The student or faculty member participating in this Course Offering.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Connections</relationshipLabel>
    <relationshipName>Student_Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/hed__Course_Offering__c.field-meta.xml
<CustomField>
    <fullName>hed__Course_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Course Offering the student or faculty member is involved with.</description>
    <inlineHelpText>The Course Offering the student or faculty member is involved with.</inlineHelpText>
    <label>Course Offering ID</label>
    <referenceTo>hed__Course_Offering__c</referenceTo>
    <relationshipLabel>Course Connection</relationshipLabel>
    <relationshipName>Course_Enrollment</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/hed__Status__c.field-meta.xml
<CustomField>
    <fullName>hed__Status__c</fullName>
    <description>Indicates whether this is a current or former Course Connection.</description>
    <inlineHelpText>Indicates whether this is a current or former Course Connection.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/LMS_Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>LMS_Integration_Status__c</fullName>
    <label>LMS Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not-Ready</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/Paid_in_Full__c.field-meta.xml
<CustomField>
    <fullName>Paid_in_Full__c</fullName>
    <label>Paid in Full</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/Pricing_Validation__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Validation__c</fullName>
    <description>Validation status of learners basing from the pricebook selected when registered</description>
    <label>Pricing Validation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/Program_Offering__c.field-meta.xml
<CustomField>
    <fullName>Program_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Offering</label>
    <referenceTo>Program_Offering__c</referenceTo>
    <relationshipLabel>Course Connections</relationshipLabel>
    <relationshipName>Course_Connections</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <description>A Student Course Connection</description>
    <label>Student</label>
</RecordType>

src/core-crm/objects/hed__Course_Offering__c/hed__Course_Offering__c.object-meta.xml
<CustomObject>
    <description>Joins Courses and Terms to contain information related to a single occurrence of a Course.</description>
    <label>Course Offering</label>
    <nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Offering__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>External ID used for integration</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/fields/Program_Offering__c.field-meta.xml
<CustomField>
    <fullName>Program_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Linked the course offering to the Program offering for Prescribed
    Program.</description>
    <label>Program Offering</label>
    <referenceTo>Program_Offering__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Questionnaire__c/Questionnaire__c.object-meta.xml
<CustomObject>
    <description>This will capture the list of questions/answers against a record.</description>
    <label>Questionnaire</label>
    <nameField>
        <displayFormat>QN-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Questionnaire__c/fields/Questionnaire_Type__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire_Type__c</fullName>
    <description>Types of questionnaire the users can create.</description>
    <label>Questionnaire Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registration Criteria</fullName>
            </value>
            <value>
                <fullName>Registration Questions</fullName>
            </value>
            <value>
                <fullName>Application Questions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Questionnaire_Response_Summary__c/Questionnaire_Response_Summary__c.object-meta.xml
<CustomObject>
    <description>This will summarise the response of leaner to a questionnaire per offering.</description>
    <label>Questionnaire Response Summary</label>
    <nameField>
        <displayFormat>QRS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questionnaire Response Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Questionnaire_Response_Summary__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the contact answering the questionnaire.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Questionnaire Response Summaries</relationshipLabel>
    <relationshipName>Questionnaire_Response_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Questionnaire_Response_Summary__c/fields/Course_Offering__c.field-meta.xml
<CustomField>
    <fullName>Course_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the course offering the responses answered from.</description>
    <label>Course Offering</label>
    <referenceTo>hed__Course_Offering__c</referenceTo>
    <relationshipLabel>Questionnaire Response Summaries</relationshipLabel>
    <relationshipName>Questionnaire_Response_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Questionnaire_Response_Summary__c/fields/Program_Offering__c.field-meta.xml
<CustomField>
    <fullName>Program_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the program plan offering the responses answered from.</description>
    <label>Program Offering</label>
    <referenceTo>Program_Offering__c</referenceTo>
    <relationshipLabel>Questionnaire Response Summaries</relationshipLabel>
    <relationshipName>Questionnaire_Response_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Questionnaire_Response_Summary__c/fields/Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the questionnaire containing questions.</description>
    <label>Questionnaire</label>
    <referenceTo>Questionnaire__c</referenceTo>
    <relationshipLabel>Questionnaire Response Summaries</relationshipLabel>
    <relationshipName>Questionnaire_Response_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Questionnaire_Response_Summary__c/fields/Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Registration_Status__c</fullName>
    <description>This will determine the eligibility status of the Registration.</description>
    <label>Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/WebCart/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>Foreign Key for Integration and Data Migration</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/classes/ManageRegistrationLearnersListHelper.cls
/**
 * @description helper class for manageregistrationsectionctrl
 * @see ../manageregistrationsectionctrl
 *
 * @author Accenture
 *
 * @history
 *    | Developer                 | Date                  | JIRA                 | Change Summary               |
      |---------------------------|-----------------------|----------------------|------------------------------|
      | roy.nino.s.regala         | November 15, 2022     | DEPP-4721            | Created file                 |
*/

public without sharing class ManageRegistrationLearnersListHelper{

     private static string studentRT = System.Label.RT_CourseConnection_Student;
     private static Id studentRecTypeId = Schema.SObjectType.hed__Course_Enrollment__c.getRecordTypeInfosByDeveloperName().get(studentRT).getRecordTypeId();
     private static string studentProgramRT = System.Label.RT_CourseConnection_Student_Program;
     private static Id studentProgramRecTypeId = Schema.SObjectType.hed__Course_Enrollment__c.getRecordTypeInfosByDeveloperName().get(studentProgramRT).getRecordTypeId();
     private static List<hed__Course_Enrollment__c> registeredLearners;
     private static Map<Id,List<hed__Course_Enrollment__c>> relatedEnrollments;
     private static Map<Id, PricebookEntry> studentWithPricingMap;
     private static Map<Id,Questionnaire_Response_Summary__c> contactToQRSummary;

     /**
      * @description Retrieves list of Registration details of students for Non Program Plan
      * @param childRecordId - Record ID of course offering
      * @param prescribedProgram - checks if offering is a prescribed program
      * @return List of ManageRegistrationDetails
      */
      @AuraEnabled(cacheable=true)
      public static List<ManageRegistrationDetails> getRegistrations(String childRecordId, Boolean prescribedProgram){
 
           List<ManageRegistrationDetails> response = new List<ManageRegistrationDetails>();
           contactToQRSummary = new Map<Id,Questionnaire_Response_Summary__c>();
           registeredLearners = new List<hed__Course_Enrollment__c>();
           ManageRegistrationWrapper.PaymentUrlClass urlObj = new ManageRegistrationWrapper.PaymentUrlClass();
           relatedEnrollments = new Map<Id,List<hed__Course_Enrollment__c>>();
           Map<String, PricebookEntry> pbeList = new Map<String, PricebookEntry>();
 
           List<Questionnaire_Response_Summary__c> questionnaireResponseList = [
                SELECT Id, Name, Contact__c, Course_Offering__c, Questionnaire__c, Questionnaire__r.Questionnaire_Type__c, Registration_Status__c
                FROM Questionnaire_Response_Summary__c
                WHERE Questionnaire__r.Questionnaire_Type__c = 'Registration Questions' 
                AND (Course_Offering__c =: childRecordId OR Program_Offering__c  =: childRecordId)
                WITH SECURITY_ENFORCED
           ];
 
           for(Questionnaire_Response_Summary__c qResSummary: questionnaireResponseList){
                contactToQRSummary.put(qResSummary.Contact__c, qResSummary);
           }
 
           registeredLearners = [
                    SELECT Id, Name, hed__Contact__c, hed__Contact__r.Id, hed__Contact__r.Name, hed__Contact__r.Position__c, hed__Contact__r.hed__Primary_Organization__r.Name, 
                    hed__Contact__r.Dietary_Requirement__c, hed__Contact__r.Accessibility_Requirement__c, Pricing_Validation__c, hed__Course_Offering__c, Cart_ID__r.External_Id__c,
                    Cart_ID__r.TotalAmount, Paid_in_Full__c, hed__Status__c, LMS_Integration_Status__c, hed__Contact__r.FirstName, hed__Contact__r.LastName,
                    hed__Contact__r.Birthdate, Payment_Method__c, Cart_Item__r.Pricebook_Entry_ID__c, Is_Group_Registered__c, hed__Contact__r.Registered_Email__c,
                    CreatedDate, Paid_Amount__c, hed__Contact__r.QUT_Student_Id__c
                    FROM hed__Course_Enrollment__c
                    WHERE RecordTypeId IN (:studentRecTypeId, :studentProgramRecTypeId)
                    AND (hed__Course_Offering__c =: childRecordId OR (Program_Offering__c  =: childRecordId AND hed__Course_Offering__c = null ))
                    WITH SECURITY_ENFORCED
           ];      
 
           Product2 product = ManageRegistrationSectionHelper.getProduct(childRecordId, prescribedProgram);
 
           List<PricebookEntry> priceBookEntries = [
                SELECT Id, UnitPrice, Pricebook2.Name 
                FROM PricebookEntry 
                WHERE Product2Id =: product.Id 
                WITH SECURITY_ENFORCED
                ORDER BY CreatedDate
           ];
           
           for(PricebookEntry p : priceBookEntries){
                pbeList.put(p.Id, p);
           }
 
           studentWithPricingMap = new Map<Id, PricebookEntry>();
           for(hed__Course_Enrollment__c student : registeredLearners){
                if(pbeList.containsKey(student.Cart_Item__r.Pricebook_Entry_ID__c)){
                     studentWithPricingMap.put(student.Id, pbeList.get(student.Cart_Item__r.Pricebook_Entry_ID__c));
                }
                
                //store all cart ids of the course enrollments as key of the map
                if( !relatedEnrollments.containsKey(student.Cart_ID__c) && 
                     student.Cart_ID__c != null && 
                     student.hed__Status__c != 'Cancelled'){
 
                     relatedEnrollments.put(student.Cart_ID__c,new List<hed__Course_Enrollment__c>());
                }
           }
 
           //get all active related enrollments under the same cart of thecurrent offering's enrollments
           for(hed__Course_Enrollment__c relatedStudent: [
                SELECT Id, Name, 
                hed__Contact__r.Name, 
                hed__Contact__r.Registered_Email__c,
                Cart_Item__r.Promotion_Price__c, 
                Cart_Item__r.TotalPrice,
                Cart_ID__r.External_Id__c, 
                Cart_Item__r.Product2.Name,
                Cart_Item__r.Contact__r.Name
                FROM hed__Course_Enrollment__c
                WHERE Cart_ID__c IN: relatedEnrollments.keySet()
                AND hed__Status__c != 'Cancelled'
                WITH SECURITY_ENFORCED
           ]){
                //group all active enrollments by cart
                relatedEnrollments.get(relatedStudent.Cart_ID__c).add(relatedStudent);
           }
 
           response = buildRegistrationDetails();
 
           return response;
      }
 
      private static List<ManageRegistrationDetails> buildRegistrationDetails(){
 
           List<ManageRegistrationDetails> regDetailsList = new List<ManageRegistrationDetails>();
           ManageRegistrationDetails regDetails;
                
           Decimal amount = 0;
           Boolean isCCE = false;
           String selectedPricing = '';
 
           for(hed__Course_Enrollment__c student : registeredLearners){
 
                regDetails = new ManageRegistrationDetails();
 
                amount = 0;
                selectedPricing = '';
 
                regDetails.enrolmentDetails = student;
                regDetails.regenerateInvoiceURL = '';
                regDetails.applicationDetails = null;
                
                if(studentWithPricingMap.containsKey(student.Id)){
 
                     selectedPricing = studentWithPricingMap.get(student.Id).Pricebook2.Name;
                     amount = studentWithPricingMap.get(student.Id).UnitPrice;
                }
                
                if(contactToQRSummary.containsKey(student.hed__Contact__c)){
                     regDetails.applicationDetails = contactToQRSummary.get(student.hed__Contact__c);
                }
 
                //checker if enrollment is CCE
                isCCE = selectedPricing.startsWith('SOA')?true:false;
 
                //condition to create invoice url
                if(  student.Cart_ID__c != null && 
                     student.Paid_in_Full__c == 'No' && 
                     student.Payment_Method__c == 'Invoice' && 
                     student.hed__Contact__r.Registered_Email__c != null && 
                     student.hed__Status__c != 'Cancelled'){
                          
                          regDetails.regenerateInvoiceURL = ManageRegistrationEnrolmentHelper.paymentGatewayURLBuilder(
                          relatedEnrollments.get(student.Cart_Id__c), 
                          isCCE, 
                          student.hed__Contact__r.Registered_Email__c
                     );
                }
                regDetailsList.add(regDetails);
           }
 
           return regDetailsList;
 
     }

     /**
      * @description Updates Registration details of students
      * @param id - id of student selected
      * @param questionId - question id of student selected
      * @param registrationStatus - registration status of student selected
      * @param paidInFull - paid in full field of student selected
      * @param pricingValidation - pricing validation field of student selected
      * @return String
      */
      @AuraEnabled
      public static String updateRegistration(hed__Course_Enrollment__c studentRecord){
 
           try {
 
                List<hed__Course_Enrollment__c> studentsToUpdate = new List<hed__Course_Enrollment__c>();
                studentsToUpdate.add(studentRecord);
 
                if(studentRecord.Program_Offering__c != null){
 
                     List<hed__Course_Enrollment__c> students = [
                          SELECT Id, Paid_in_Full__c, Pricing_Validation__c, hed__Status__c
                          FROM hed__Course_Enrollment__c 
                          WHERE hed__Course_Offering__c != NULL 
                          AND Program_Offering__c =: studentRecord.Program_Offering__c
                          AND hed__Contact__c =: studentRecord.hed__Contact__c
                          WITH SECURITY_ENFORCED
                     ];
 
                     for(hed__Course_Enrollment__c student : students){
                          hed__Course_Enrollment__c learner = new hed__Course_Enrollment__c();
                          learner.Id = studentRecord.Id;
                          learner.Paid_in_Full__c = studentRecord.Paid_in_Full__c;
                          learner.Pricing_Validation__c = studentRecord.Pricing_Validation__c;
                          learner.hed__Status__c = studentRecord.hed__Status__c;
                          studentsToUpdate.add(learner);
                     }
                }
           
                if( studentsToUpdate.size() > 0 && 
                    Schema.sObjectType.hed__Course_Enrollment__c.fields.Paid_in_Full__c.isUpdateable() && 
                    Schema.sObjectType.hed__Course_Enrollment__c.fields.Pricing_Validation__c.isUpdateable() &&
                    Schema.sObjectType.hed__Course_Enrollment__c.fields.hed__Status__c.isUpdateable()){
                         
                    update studentsToUpdate;
                }else{
                    return 'The following exception has occurred: You have no right to update the record';
                }

                return 'Success';
           }
           catch (Exception e) {
                return 'The following exception has occurred: ' + e.getMessage();
           }
      }

     /**
      * @description Wrapper class that holds data to be displayed
      */
     public class ManageRegistrationDetails{
          @AuraEnabled
          public hed__Course_Enrollment__c enrolmentDetails;
          @AuraEnabled
          public Questionnaire_Response_Summary__c applicationDetails;
          @AuraEnabled
          public String regenerateInvoiceURL;
     }
}