src/core-crm/objects/CartItem/fields/Course_Offering__c.field-meta.xml
<CustomField>
    <fullName>Course_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The associated course offering that’s added to the cart</description>
    <label>Course Offering</label>
    <referenceTo>hed__Course_Offering__c</referenceTo>
    <relationshipLabel>Cart Items</relationshipLabel>
    <relationshipName>Cart_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/main/default/objects/CartItem/fields/Pricebook_entry_ID__c.field-meta.xml
<CustomField>
    <fullName>Pricebook_entry_ID__c</fullName>
    <inlineHelpText>The pricing chosen on checkout</inlineHelpText>
    <label>Pricebook entry ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/CartItem/fields/Program_Offering__c.field-meta.xml
<CustomField>
    <fullName>Program_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The associated program offering that’s added to the cart</description>
    <label>Program Offering</label>
    <referenceTo>Program_Offering__c</referenceTo>
    <relationshipLabel>Cart Items</relationshipLabel>
    <relationshipName>Cart_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Program_Offering__c/Program_Offering__c.object-meta.xml
<CustomObject>
    <label>Program Offering</label>
    <nameField>
        <label>Program Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/classes/CartItemsDAO.cls
/**
 * @description DAO Class for CartItem Object. Contains soql and constants related to the CartItem object.
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary                          |
 *    |--------------------------------|-----------------------|------------------------|-----------------------------------------|
 *    | roy.nino.s.regala              | April 25, 2023        | DEPP-5567              | Created file                            |
 *    | julie.jane.alegre              | January 03, 2024      | ApexCRUDViolationFix   | Add countCartItemsGroupByCourseOffering |
 *    |                                |                       |                        | Add countCartItemsGroupByProgramOffering|
 */
public inherited sharing class CartItemsDAO extends DmlBase implements ICartItemsDAO {
    public Schema.SObjectType getSObjectType() {
        return CartItem.SObjectType;
    }

    public static ICartItemsDAO newInstance() {
        return (ICartItemsDAO) ImplementationSelector.DAO.newInstance(CartItem.sObjectType);
    }

    public List<CartItem> getCartItemsWithPricebookEntryByRecordIds(
        Set<String> recordIds,
        AccessLevel accessLevel
    ) {
        return Database.query(
            'SELECT Id, Pricebook_Entry_ID__c ' +
                'FROM CartItem ' +
                'WHERE Id IN :recordIds ' +
                'AND Pricebook_Entry_ID__c != NULL ',
            accessLevel
        );
    }

    public List<CartItem> getCartItemsByCartItemName(
        Set<String> cartItemNames,
        AccessLevel accessLevel
    ) {
        return Database.query(
            'SELECT Id, Pricebook_Entry_ID__c ' +
                'FROM CartItem ' +
                'WHERE Name IN: cartItemNames ',
            accessLevel
        );
    }

    public List<AggregateResult> countCartItemsGroupByCourseOffering(
        Set<Id> courseOfferIdSet,
        AccessLevel accessLevel
    ) {
        if(courseOfferIdSet.isEmpty()){
            return new List<AggregateResult>();
        }
        return Database.query(
            'SELECT Course_Offering__c, COUNT(Id) counter ' +
                'FROM CartItem ' +
                'WHERE Course_Offering__c IN :courseOfferIdSet  ' +
                'AND Cart.Status__c = \'Checkout\' ' + 
                'GROUP BY Course_Offering__c',
            accessLevel
        );
    }
    public List<AggregateResult> countCartItemsGroupByProgramOffering(
        Set<Id> programOfferIdSet,
        AccessLevel accessLevel
    ) {
        if(programOfferIdSet.isEmpty()){
            return new List<AggregateResult>();
        }
        return Database.query(
            'SELECT Program_Offering__c, COUNT(Id) counter ' +
                'FROM CartItem ' +
                'WHERE Program_Offering__c IN :programOfferIdSet  ' +
                'AND Cart.Status__c = \'Checkout\' ' + 
                'GROUP BY Program_Offering__c',
            accessLevel
        );
    }

}