src/core-crm/objects/Expression_of_Interest__c/Expression_of_Interest__c.object-meta.xml
<CustomObject>
    <description>Record will be created when learner clicks &apos;Register Interest&apos; button against a Product in OPE catalogue or nominations from corporate portal</description>
    <label>Expression of Interest</label>
    <nameField>
        <displayFormat>EI-{0000}</displayFormat>
        <label>Expression of Interest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expression of Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Expression_of_Interest__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Linked to the learner that’s expressing interest to the product</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Expression of Interests</relationshipLabel>
    <relationshipName>Expression_of_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Expression_of_Interest__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Linked to the Product that the learner is interested in. Used for registration of interest.</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Expression of Interests</relationshipLabel>
    <relationshipName>Expression_of_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Expression_of_Interest__c/fields/Program_Offering__c.field-meta.xml
<CustomField>
    <fullName>Program_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will link to program offering that the learner successfully registered to for &apos;Register Interest&apos; process OR a link to the nominated program offering.</description>
    <label>Program Offering</label>
    <referenceTo>Program_Offering__c</referenceTo>
    <relationshipLabel>Expression of Interests</relationshipLabel>
    <relationshipName>Expression_of_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Expression_of_Interest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of interest</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Expression_of_Interest__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of interest process</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nomination</fullName>
            </value>
            <value>
                <fullName>Register Interest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Course__c/hed__Course__c.object-meta.xml
<CustomObject>
    <description>Academic Course offered by a Department or School, for example, English 101 or Ancient History.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/hed__Course_Offering__c.object-meta.xml
<CustomObject>
    <description>Joins Courses and Terms to contain information related to a single occurrence of a Course.</description>
    <label>Course Offering</label>
    <nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Offering__c/fields/Available_Seats__c.field-meta.xml
<CustomField>
    <fullName>Available_Seats__c</fullName>
    <formula>hed__Capacity__c -  Total_Number_of_Registered_Learners__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Course__c.field-meta.xml
<CustomField>
    <fullName>hed__Course__c</fullName>
    <description>Lookup to the Course record that this Course Offering is associated with.</description>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>
 

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>hed__Start_Date__c</fullName>
    <description>The date of the first session for this Course Offering.</description>
    <inlineHelpText>The date of the first session for this Course Offering.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/fields/On_Hold_Seat__c.field-meta.xml
<CustomField>
    <fullName>On_Hold_Seat__c</fullName>
    <description>This will hold the unpaid seat that’s been checked out in the product catalogue.</description>
    <label>On Hold Seat</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/fields/Program_Offering__c.field-meta.xml
<CustomField>
    <fullName>Program_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Linked the course offering to the Program offering for Prescribed
    Program.</description>
    <label>Program Offering</label>
    <referenceTo>Program_Offering__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Product2/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Product2/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Plan</label>
    <referenceTo>hed__Program_Plan__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of course to be used as filter in the product catalogue.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single Product</fullName>
            </value>
            <value>
                <fullName>Short Course</fullName>
            </value>
            <value>
                <fullName>Activity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Program_Offering__c/Program_Offering__c.object-meta.xml
<CustomObject>
    <label>Program Offering</label>
    <nameField>
        <label>Program Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/Program_Offering__c/fields/Available_Seats__c.field-meta.xml
<CustomField>
    <fullName>Available_Seats__c</fullName>
    <formula>hed_Capacity__c - Total_Course_Connections__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Program_Offering__c/fields/hed_Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>hed_Program_Plan__c</fullName>
    <description>Programs offered in a set structure for a particular cohort of learner</description>
    <label>Program Plan</label>
    <referenceTo>hed__Program_Plan__c</referenceTo>
    <relationshipLabel>Program Offering</relationshipLabel>
    <relationshipName>Program_Offering</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/core-crm/classes/B2BRegisterInterestBatch.cls
/**
 * @description Batch class that sends email to users that expressed there interest to courses
 *
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | roy.nino.s.regala              | February 03, 2022     | DEPP-213               | Created file                 | 
      |                                |                       |                        |                              | 
 */
global class B2BRegisterInterestBatch implements Database.Batchable<sObject>
{
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        String query = 'SELECT Id, Contact__c,Contact__r.Email, Contact__r.FirstName, Contact__r.LastName, '; 
               query += 'Product__c, Product__r.Course__c, Product__r.Name, Product__r.Program_Plan__c, ';
               query += 'Type__c, Status__c ';
               query += 'FROM Expression_of_interest__c ' ;
               query += 'WHERE Status__c = \'Active\' ';
               query += 'AND Contact__r.Email != NULL ';
               query += 'AND Type__c = \'Register Interest\' ';
               query += 'AND ( Product__r.Course__c != NULL ';
               query += 'OR Product__r.Program_Plan__c != NULL)';
        return Database.getQueryLocator(query);
    }
 
    global void execute(Database.BatchableContext BC, List<Expression_of_Interest__c> expresionOfInterestList)
    {
        Map<Id,List<Id>> mapOfCourseToInterests = new Map<Id,List<Id>>(); // map of course to expresion of interests 
        Map<Id,List<Id>> mapOfProgramPlanToInterests = new Map<Id,List<Id>>(); // map of course to expresion of interests 
        Set<Id> interestEmailRecipientsSet = new Set<Id>(); // Set of expression of interests Ids that would receive an email
        Map<Id, Expression_of_Interest__c> expresionOfInterestMap = new Map<Id, Expression_of_Interest__c>(expresionOfInterestList);

        for(Expression_of_Interest__c interest : expresionOfInterestMap.values()){
            //construct map, this relates and groups expression of interests for each course
            if(interest.Product__r.Course__c != NULL){
                if(!mapOfCourseToInterests.containsKey(interest.Product__r.Course__c)){
                    mapOfCourseToInterests.put(interest.Product__r.Course__c,new List<Id>());
                }
                mapOfCourseToInterests.get(interest.Product__r.Course__c).add(interest.Id);
            }
            //construct map, this relates and groups expression of interests for each course

            //construct map, this relates and groups expression of interests for each program plan
            if(interest.Product__r.Program_Plan__c != NULL){
                if(!mapOfProgramPlanToInterests.containsKey(interest.Product__r.Program_Plan__c)){
                    mapOfProgramPlanToInterests.put(interest.Product__r.Program_Plan__c,new List<Id>());
                }
                mapOfProgramPlanToInterests.get(interest.Product__r.Program_Plan__c).add(interest.Id);
            }
            //construct map, this relates and groups expression of interests for each program plan
        }

        if(!mapOfCourseToInterests.keySet().isEmpty()){
            List<hed__Course_Offering__c> relatedCourseOfferings = new List<hed__Course_Offering__c>([SELECT Id, hed__Course__c, Available_Seats__c, On_Hold_Seat__c
                                                                                                        FROM hed__Course_Offering__c 
                                                                                                        WHERE hed__Course__c IN:mapOfCourseToInterests.keySet()
                                                                                                        AND Available_Seats__c > 0
                                                                                                        AND hed__Start_Date__c >  TODAY]);
            for(hed__Course_Offering__c courseOffering: relatedCourseOfferings){

                //check if offering has available seats (available seats - on hold seats)
                Decimal availableSeatTemp = courseOffering.Available_Seats__c != null?courseOffering.Available_Seats__c:0;
                Decimal onHoldSeatTemp = courseOffering.On_Hold_Seat__c != null?courseOffering.On_Hold_Seat__c:0;
                Decimal finalSeats = availableSeatTemp - onHoldSeatTemp;
                //check if offering has available seats (available seats - on hold seats)

                if( finalSeats > 0){
                    //store all Interests that have available course offerings in a set to remove duplicates
                    interestEmailRecipientsSet.addAll(mapOfCourseToInterests.get(courseOffering.hed__Course__c));
                }
            }
        }

        if(!mapOfProgramPlanToInterests.keySet().isEmpty()){
            List<Program_Offering__c> relatedProgramOfferings = new List<Program_Offering__c>([SELECT Id, hed_Program_Plan__c, Available_Seats__c
                                                                                                        FROM Program_Offering__c 
                                                                                                        WHERE hed_Program_Plan__c IN:mapOfProgramPlanToInterests.keySet()
                                                                                                        AND Available_Seats__c > 0
                                                                                                        AND Start_Date__c >  TODAY]);
            for(Program_Offering__c programOffering: relatedProgramOfferings){
                //store all Interests that have available program offerings in a set to remove duplicates
                interestEmailRecipientsSet.addAll(mapOfProgramPlanToInterests.get(programOffering.hed_Program_Plan__c));
            }
        }

        if(!interestEmailRecipientsSet.isEmpty()){
            List<Domain> domain = new List<Domain>([SELECT Id, Domain FROM Domain]);
            List<EmailTemplate> emailTemplateList = new List<EmailTemplate>([SELECT Id, HTMLValue from EmailTemplate WHERE DeveloperName = 'Offering_Available_Email_Notification']);
            OrgWideEmailAddress owea = new OrgWideEmailAddress();
            owea = [SELECT Id, Address, DisplayName FROM OrgWideEmailAddress WHERE DisplayName='QUTeX'];

            String basePortalUrl ='';
            if(!domain.isEmpty()){
                basePortalUrl= 'https://' + domain[0].Domain + '/study/s/product/';
            }
            
            List<Messaging.SingleEmailMessage> lstEmails = new List<Messaging.SingleEmailMessage>();

            if(!emailTemplateList.isEmpty()){
                for(Id interestId : interestEmailRecipientsSet){
                    Messaging.SingleEmailMessage objEmail = new Messaging.SingleEmailMessage();

                    //Prepare SendToEmail List          
                    List<String> lstSendToEmails = new List<String>();

                    lstSendToEmails.add(expresionOfInterestMap.get(interestId).Contact__r.Email);
                
                    objEmail.setToAddresses(lstSendToEmails);

                    if(owea != null){
                        objEmail.setOrgWideEmailAddressId(owea.Id);
                    }

                    //Set Email Subject
                    objEmail.setSubject(expresionOfInterestMap.get(interestId).Product__r.Name);

                    //Set Email Body
                    String body = emailTemplateList[0].HTMLValue.replace('Contact_LastName',expresionOfInterestMap.get(interestId).Contact__r.LastName);

                    //To make sure that firstname is populated, it is not a required field 
                    if(expresionOfInterestMap.get(interestId).Contact__r.FirstName != null){ 
                        body = body.replace('Contact_FirstName', expresionOfInterestMap.get(interestId).Contact__r.FirstName);
                    }else{
                        body = body.replace('Contact_FirstName', '');
                    }
                    //To make sure that firstname is populated, it is not a required field 

                    body = body.replace('Product_Name', expresionOfInterestMap.get(interestId).Product__r.Name);
                    String productUrl = basePortalUrl + expresionOfInterestMap.get(interestId).Product__c;
                    body = body.replace('Product_URL', productUrl);
                    body = EmailHelper.addHeaderAndFooter(body);
                    
                    objEmail.setHtmlBody(body);
                    
                    lstEmails.add(objEmail);
                    //make sure email is not null
                }
            }

            if(!lstEmails.isEmpty()){
                Messaging.SendEmailResult[] results = Messaging.sendEmail(lstEmails);
                // To Check whether Email is sent or not
                if (results[0].success) {
                    System.debug('The email was sent successfully.');
                } else {
                    System.debug('The email failed to send: ' + results[0].errors[0].message);
                }
                // To Check whether Email is sent or not
            }else{
                System.debug('No emails to be sent');
            }
        }    
    
    }  
    global void finish(Database.BatchableContext BC) {}
}