src/core-crm/objects/Nurture_Track_Configuration__c/Nurture_Track_Configuration__c.object-meta.xml
<CustomObject>
    <label>Nurture Track Configuration</label>
    <nameField>
        <displayFormat>NTC-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nurture Track Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Nurture_Track_Configuration__c/fields/Cadence_Name__c.field-meta.xml
<CustomField>
    <fullName>Cadence_Name__c</fullName>
    <description>The Name of the Cadence the Configuration is for</description>
    <label>Cadence Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Nurture_Track_Configuration__c/fields/Lead_Score_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Lead_Score_Threshold__c</fullName>
    <description>The Lead Score Threshold for inclusion in the Track

Note: This value needs to be replicated to all cadences in the track</description>
    <label>Lead Score Threshold</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Nurture_Track_Configuration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Cadence Status is used to activate or deactivate the cadence</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/classes/NurtureTrackConfigurationsDAOMock.cls
/**
 * @description Mock DAO Class for Nurture Track Configuration Object. 
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | mark.j.mahilum                 | July 25, 2023         | DEPP-6106              | Created file                 |
 */
@isTest
public inherited sharing class NurtureTrackConfigurationsDAOMock extends DmlBaseMock implements INurtureTrackConfigurationsDAO {
    public Map<Id, Nurture_Track_Configuration__c> nurtureTrackConfigMap;

    public Schema.SObjectType getSObjectType() {
        return Nurture_Track_Configuration__c.SObjectType;
    }

    public NurtureTrackConfigurationsDAOMock() {
        super(new Map<Id, Nurture_Track_Configuration__c>(), Schema.Nurture_Track_Configuration__c.SObjectType);
        this.nurtureTrackConfigMap = (Map<Id, Nurture_Track_Configuration__c>) super.records;
    }

    public List<Nurture_Track_Configuration__c> getNurtureTrackLeadScoreThreshold(
        String accessLevel
    ) {
        List<Nurture_Track_Configuration__c> nurtureList = new List<Nurture_Track_Configuration__c>();
        
        for (Nurture_Track_Configuration__c record : nurtureTrackConfigMap.values()) {
            if (record.Status__c == 'Active' &&
                record.Lead_Score_Threshold__c !=NULL)
            {
                nurtureList.add(record);
            }
        }       
        return nurtureList;
    }

    public List<Nurture_Track_Configuration__c> getNurtureTrackByCadenceNames(
        Set<String> cadenceNames,
        String accessLevel
    ) {
        List<Nurture_Track_Configuration__c> nurtureList = new List<Nurture_Track_Configuration__c>();
        
        for (Nurture_Track_Configuration__c record : nurtureTrackConfigMap.values()) {
            if (cadenceNames.contains(record.Cadence_Name__c)){
                nurtureList.add(record);
            }
        }       
        return nurtureList;
    }  
    
    public List<Nurture_Track_Configuration__c> getNurtureTrack(
        String fieldsToQuery,
        String accessLevel
    ) {
        List<Nurture_Track_Configuration__c> nurtureList = new List<Nurture_Track_Configuration__c>();
        
        for (Nurture_Track_Configuration__c record : nurtureTrackConfigMap.values()) {
            if (record.Status__c == 'Active')
            {
                nurtureList.add(record);
            }
        }       
        return nurtureList;
    }
} 