src/core-crm/objects/Account/fields/Organization_Unit_Level__c.field-meta.xml
<CustomField>
    <fullName>Organization_Unit_Level__c</fullName>
    <description>The level (1,2,3) of the organizational unit within the QUT Organizational hierarchy.</description>
    <label>Organization Unit Level</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Account/recordTypes/University_Department.recordType-meta.xml
<RecordType>
    <fullName>University_Department</fullName>
    <active>true</active>
    <description>A department in the educational institution.</description>
    <label>University Department</label>
</RecordType>

src/core-crm/objects/hed__Course__c/hed__Course__c.object-meta.xml
<CustomObject>
    <description>Academic Course offered by a Department or School, for example, English 101 or Ancient History.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course__c/fields/LMS_Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>LMS_Integration_Status__c</fullName>
    <label>LMS Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Course__c/recordTypes/Activity.recordType-meta.xml
<RecordType>
    <fullName>Activity</fullName>
    <active>true</active>
    <label>Activity</label>
    <picklistValues>
        <!-- Renamed from Collaboation_External__c-->
        <picklist>Collaboration_with_External_Organisation__c</picklist>
        <values>
            <fullName>No</fullName>
        </values>
        <values>
            <fullName>Yes</fullName>
        </values>
    </picklistValues>
</RecordType>

src/core-crm/objects/hed__Course__c/recordTypes/Module.recordType-meta.xml
<RecordType>
    <fullName>Module</fullName>
    <active>true</active>
    <description>This record type will be used to create a Non-Award Unit or a Short Course with a learning pathway.</description>
    <label>Module</label>
   <picklistValues>
       <!-- Renamed from Collaboation_External__c-->
       <picklist>Collaboration_with_External_Organisation__c</picklist>
        <values>
            <fullName>No</fullName>
        </values>
        <values>
            <fullName>Yes</fullName>
        </values>
    </picklistValues>
</RecordType>

src/core-crm/objects/hed__Course_Offering__c/hed__Course_Offering__c.object-meta.xml
<CustomObject>
    <description>Joins Courses and Terms to contain information related to a single occurrence of a Course.</description>
    <label>Course Offering</label>
    <nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Course__c.field-meta.xml
<CustomField>
    <fullName>hed__Course__c</fullName>
    <description>Lookup to the Course record that this Course Offering is associated with.</description>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>
 

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>hed__Start_Date__c</fullName>
    <description>The date of the first session for this Course Offering.</description>
    <inlineHelpText>The date of the first session for this Course Offering.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Term__c.field-meta.xml
<CustomField>
    <fullName>hed__Term__c</fullName>
    <description>Lookup to the Term record that represents when this Course Offering takes place.</description>
    <label>Term</label>
    <referenceTo>hed__Term__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>
 

src/core-crm/objects/hed__Course_Offering__c/fields/LMS_Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>LMS_Integration_Status__c</fullName>
    <label>LMS Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Term__c/hed__Term__c.object-meta.xml
<CustomObject>
    <description>Unit of time in which academic activities are taking place.</description>
    <label>Term</label>
    <nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Term__c/fields/hed__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>hed__Start_Date__c</fullName>
    <description>The date this Term starts.</description>
    <inlineHelpText>The date this Term starts.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Product_Request__c/Product_Request__c.object-meta.xml
<CustomObject>
    <label>Product Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Product Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Product_Request__c/fields/Product_Request_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Request_Name__c</fullName>
    <label>Product Request Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Product_Request__c/fields/Product_Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Product_Request_Status__c</fullName>
    <label>Product Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Define</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Release</fullName>
            </value>
            <value>
                <fullName>In Delivery</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Product_Request__c/fields/Product_Specification__c.field-meta.xml
<CustomField>
    <fullName>Product_Specification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Specification</label>
    <referenceTo>Product_Specification__c</referenceTo>
    <relationshipLabel>Product Requests</relationshipLabel>
    <relationshipName>Product_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Product_Request__c/recordTypes/Activity.recordType-meta.xml
<RecordType>
    <fullName>Activity</fullName>
    <active>true</active>
    <description>This record type will be used to create an Event, Discussion Forum, or workshop.</description>
    <label>Activity</label>
</RecordType>

src/core-crm/objects/Product_Request__c/recordTypes/Module.recordType-meta.xml
<RecordType>
    <fullName>Module</fullName>
    <active>true</active>
    <description>This record type will be used to create a Non-Award Unit or a Short Course with a learning pathway.</description>
    <label>Module</label>
</RecordType>

src/core-crm/objects/Product_Request__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <description>This record type will be used to create a Program. This can be a combination of a Unit, a Module, a Short Course, or an Activity.</description>
    <label>Program</label>
</RecordType>

src/core-crm/objects/Product_Specification__c/Product_Specification__c.object-meta.xml
<CustomObject>
    <label>Product Specification</label>
    <nameField>
        <displayFormat>PS-{00000}</displayFormat>
        <label>Product Specification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Specifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Product_Specification__c/fields/Existing_Product__c.field-meta.xml
<CustomField>
    <fullName>Existing_Product__c</fullName>
    <label>Existing Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Not Sure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Product_Specification__c/fields/Financial_Viability__c.field-meta.xml
<CustomField>
    <fullName>Financial_Viability__c</fullName>
    <label>Financial Viability</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Not Sure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Product_Specification__c/fields/Market_Need__c.field-meta.xml
<CustomField>
    <fullName>Market_Need__c</fullName>
    <label>Market Need</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Not Sure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Product_Specification__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Program</fullName>
            </value>
            <value>
                <fullName>Unit</fullName>
                <isActive>false</isActive>
                <label>Unit</label>
            </value>
            <value>
                <fullName>Module</fullName>
            </value>
            <value>
                <fullName>Short Course</fullName>
            </value>
            <value>
                <fullName>Activity</fullName>
            </value>
            <value>
                <fullName>Single Product</fullName>
                <isActive>false</isActive>
                <label>Single Product</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Product_Specification__c/fields/QUT_Faculty_Capacity__c.field-meta.xml
<CustomField>
    <fullName>QUT_Faculty_Capacity__c</fullName>
    <label>QUT Faculty Capacity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Not Sure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Product_Specification__c/fields/QUTeX_Capacity__c.field-meta.xml
<CustomField>
    <fullName>QUTeX_Capacity__c</fullName>
    <label>QUTeX Capacity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Not Sure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Product_Specification__c/fields/Requestor_Name__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requestor Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Product Specifications (Requestor Name)</relationshipLabel>
    <relationshipName>Product_Specifications</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Product_Specification__c/fields/Requires_Director_Endorsement__c.field-meta.xml
<CustomField>
    <fullName>Requires_Director_Endorsement__c</fullName>
    <label>Requires Director Endorsement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Product_Specification__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Idea</fullName>
                <default>true</default>
                <label>Idea</label>
            </value>
            <value>
                <fullName>Define</fullName>
            </value>
            <value>
                <fullName>Qualify</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Not Proceeding</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Product_Specification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Stage__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Idea Sent</fullName>
            </value>
            <value>
                <fullName>Idea Received</fullName>
            </value>
            <value>
                <fullName>Qualification</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Does Not Meet Qualification</fullName>
            </value>
            <value>
                <fullName>Existing Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Product_Specification__c/fields/Supporting_Comments__c.field-meta.xml
<CustomField>
    <fullName>Supporting_Comments__c</fullName>
    <label>Supporting Comments</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

src/core-crm/objects/Product_Specification__c/recordTypes/OPE.recordType-meta.xml
<RecordType>
    <fullName>OPE</fullName>
    <active>true</active>
    <description>Used to Design products which are the result of an idea request from a faculty.</description>
    <label>OPE</label>
</RecordType>

src/core-crm/classes/NullifyLMSIntegrationStatusFlowTest.cls
@isTest
private class NullifyLMSIntegrationStatusFlowTest {
    private static final Id ID_RT_PRS_OPE = Schema.SObjectType.Product_Specification__c.getRecordTypeInfosByDeveloperName().get('OPE').getRecordTypeId();
    private static final Id ID_RT_ACC_BO = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('University_Department').getRecordTypeId();
    @TestSetup
    static void setup(){
        TestDataFactory.generateTestUsers();
    }

    @isTest
    static void nullLMSIntegration() {
        System.runAs(TestDataFactory.getProgramAdminUser()){
            Account acc = new Account(
                RecordTypeId = ID_RT_ACC_BO,
                Name = 'Tester Account',
                Organization_Unit_Level__c = '2'
            );
            insert acc;
            Contact con = TestDataFactory.createTestContact(true, acc.Id);
            Product_Specification__c prs = new Product_Specification__c(
                RecordTypeId = ID_RT_PRS_OPE,
                Requestor_Name__c = con.Id,
                Status__c = 'Design',
                Stage__c = 'Design',
                Existing_Product__c = 'No',
                Financial_Viability__c = 'No',
                Market_Need__c = 'No',
                QUTeX_Capacity__c = 'No',
                QUT_Faculty_Capacity__c = 'No',
                Supporting_Comments__c = 'You are amazing.',
                Product_Type__c = 'Program;Module;Short Course;Activity',
                Requires_Director_Endorsement__c = 'Not Required'
            );
            insert prs;
            Product_Request__c prr = new Product_Request__c(
                Product_Request_Name__c = 'Test Product',
                Product_Request_Status__c = 'Define',
                Product_Specification__c = prs.Id
            );
            insert prr;
            List<hed__Course__c> crss = TestDataFactory.createTestCourseRecords(
                1,
                acc.Id,
                prr.Id
            );
            insert crss;
            List<hed__Term__c> trms = TestDataFactory.createTestTermRecords(
                1,
                acc.Id
            );
            insert trms;
            List<hed__Course_Offering__c> ofrs = TestDataFactory.createTestCourseOfferingRecord(
                1,
                crss,
                trms
            );
            insert ofrs;
            Test.startTest();
            ofrs[0].hed__Start_Date__c += 2;
            update ofrs;
            Test.stopTest();
            Id ofrId = ofrs[0].Id;
            hed__Course_Offering__c ofrPost = [SELECT Id, LMS_Integration_Status__c FROM hed__Course_Offering__c WHERE Id = :ofrId LIMIT 1];
            System.assert(ofrPost.LMS_Integration_Status__c == null, 'LMS_Integration_Status was not cleared.');
        }
    }
}