src/core-crm/objects/Account/fields/Organization_Unit_Level__c.field-meta.xml
<CustomField>
    <fullName>Organization_Unit_Level__c</fullName>
    <description>The level (1,2,3) of the organizational unit within the QUT Organizational hierarchy.</description>
    <label>Organization Unit Level</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Course__c/hed__Course__c.object-meta.xml
<CustomObject>
    <description>Academic Course offered by a Department or School, for example, English 101 or Ancient History.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <description>The department (Account record) that offers this Course.</description>
    <inlineHelpText>The department (Account record) that offers this Course.</inlineHelpText>
    <label>Department</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/hed__Course_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Represents a connection to a Course Offering.</description>
    <label>Course Connection</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Course Connection ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Enrollment__c/fields/Enrollment_Status__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Status__c</fullName>
    <description>The status of the unit enrolment as per SAMS status (SSP_STTS_CD)</description>
    <label>Enrollment Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Academic Program that the student or faculty member is associated with.</description>
    <inlineHelpText>The Academic Program that the student or faculty member is associated with.</inlineHelpText>
    <label>Contact&apos;s Academic Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Course Connections</relationshipLabel>
    <relationshipName>Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/hed__Contact__c.field-meta.xml
<CustomField>
    <fullName>hed__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The student or faculty member participating in this Course Offering.</description>
    <inlineHelpText>The student or faculty member participating in this Course Offering.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Course Connections</relationshipLabel>
    <relationshipName>Student_Course_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/hed__Course_Offering__c.field-meta.xml
<CustomField>
    <fullName>hed__Course_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Course Offering the student or faculty member is involved with.</description>
    <inlineHelpText>The Course Offering the student or faculty member is involved with.</inlineHelpText>
    <label>Course Offering ID</label>
    <referenceTo>hed__Course_Offering__c</referenceTo>
    <relationshipLabel>Course Connection</relationshipLabel>
    <relationshipName>Course_Enrollment</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <description>A Student Course Connection</description>
    <label>Student</label>
</RecordType>

src/core-crm/objects/hed__Course_Offering__c/hed__Course_Offering__c.object-meta.xml
<CustomObject>
    <description>Joins Courses and Terms to contain information related to a single occurrence of a Course.</description>
    <label>Course Offering</label>
    <nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Capacity__c.field-meta.xml
<CustomField>
    <fullName>hed__Capacity__c</fullName>
    <description>The maximum number of students for this Course Offering.</description>
    <inlineHelpText>The maximum number of students for this Course Offering.</inlineHelpText>
    <label>Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Course__c.field-meta.xml
<CustomField>
    <fullName>hed__Course__c</fullName>
    <description>Lookup to the Course record that this Course Offering is associated with.</description>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>
 

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>hed__Start_Date__c</fullName>
    <description>The date of the first session for this Course Offering.</description>
    <inlineHelpText>The date of the first session for this Course Offering.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Term__c.field-meta.xml
<CustomField>
    <fullName>hed__Term__c</fullName>
    <description>Lookup to the Term record that represents when this Course Offering takes place.</description>
    <label>Term</label>
    <referenceTo>hed__Term__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>
 

src/core-crm/objects/hed__Term__c/hed__Term__c.object-meta.xml
<CustomObject>
    <description>Unit of time in which academic activities are taking place.</description>
    <label>Term</label>
    <nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Term__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <description>The Academic Program, Department, or entire Educational Institution this Term applies to. Select the Account that represents your Educational Institution if Terms are consistent across all Programs and Departments in your school.</description>
    <inlineHelpText>The Academic Program, Department, or entire Educational Institution this Term applies to. Select the Account that represents your Educational Institution if Terms are consistent across all Programs and Departments in your school.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Terms</relationshipLabel>
    <relationshipName>Terms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/core-crm/objects/hed__Term__c/fields/hed__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>hed__Start_Date__c</fullName>
    <description>The date this Term starts.</description>
    <inlineHelpText>The date this Term starts.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Integration_Settings__c/fields/Allow_ESB_Integration__c.field-meta.xml
<CustomField>
    <fullName>Allow_ESB_Integration__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow ESB Integration</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/MDM_Callout_Event__e/MDM_Callout_Event__e.object-meta.xml
<CustomObject>
    <label>MDM Callout Event</label>
    <pluralLabel>MDM Callouts Event</pluralLabel>
</CustomObject>

src/core-crm/objects/Product_Request__c/Product_Request__c.object-meta.xml
<CustomObject>
    <label>Product Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Product Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Product_Request__c/fields/Product_Request_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Request_Name__c</fullName>
    <label>Product Request Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Product_Request__c/fields/Product_Specification__c.field-meta.xml
<CustomField>
    <fullName>Product_Specification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Specification</label>
    <referenceTo>Product_Specification__c</referenceTo>
    <relationshipLabel>Product Requests</relationshipLabel>
    <relationshipName>Product_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Product_Specification__c/Product_Specification__c.object-meta.xml
<CustomObject>
    <label>Product Specification</label>
    <nameField>
        <displayFormat>PS-{00000}</displayFormat>
        <label>Product Specification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Specifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Product_Specification__c/recordTypes/OPE.recordType-meta.xml
<RecordType>
    <fullName>OPE</fullName>
    <active>true</active>
    <description>Used to Design products which are the result of an idea request from a faculty.</description>
    <label>OPE</label>
</RecordType>

src/core-crm/classes/ESBIntegrateOnCourseConnectionUpsertTest.cls
/**
 * @description Test class for ESBIntegrateOnCourseConnectionUpsert.cls
 * @see ESBIntegrateOnCourseConnectionUpsert
 * @author Accenture
 * @history
 * | Dev               | JIRA      | Date       | Change Summary
 * | alexander.cadalin | DEPP-4988 | 2023-02-13 | Created file
 * | eccarius.munoz    | DEPP-10490| 2024-08-13 | Updated methods for the platform event
 * |                   |           |            |               
 */
@isTest 
private class ESBIntegrateOnCourseConnectionUpsertTest {
    private static final String ACCT_UNIV_DEP = System.Label.RT_Account_University_Department;
    private static final Id ACCT_UNIV_DEP_ID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(ACCT_UNIV_DEP).getRecordTypeId();
    private static final Id PS_RT_OPE_ID = Schema.SObjectType.Product_Specification__c.getRecordTypeInfosByDeveloperName().get('OPE').getRecordTypeId();
    /**
     * @description Setup
     */

    @testSetup 
    static void setup() {
        // Generate test users.
        Test.startTest();

        TestDataFactoryUser.generateUserQUTeXProgramAdministrator();
        TestDataFactoryUser.generateUserSystemAdministrator();

        Integration_Settings__c integrationSettings = new Integration_Settings__c(Allow_ESB_Integration__c = true);
        insert integrationSettings;

        // Create an account.
        Account acco = new Account(
            Name = 'Account',
            RecordTypeId = ACCT_UNIV_DEP_ID,
            Organization_Unit_Level__c = '2'
        );
        insert acco;
        // Create contact.
        Contact cont = new Contact(
            LastName = 'Test'
        );
        insert cont;
        // Create a product specification.
        Product_Specification__c pros = TestDataFactory.createTestProductSpecsRecords(1, cont.Id)[0];
        pros.RecordTypeId = PS_RT_OPE_ID;
        insert pros;
        // Create a product request.
        Product_Request__c pror = new Product_Request__c(
            Product_Request_Name__c = 'Product Request',
            Product_Specification__c = pros.Id
        );
        insert pror;
        // Create a course.
        hed__Course__c cour = TestDataFactory.createTestCourseRecords(1, acco.Id, pror.Id)[0];
        insert cour;
        // Create a term.
        hed__Term__c term = new hed__Term__c(
            Name = 'Term',
            hed__Account__c = acco.Id
        );
        insert term;
        // Create a course offering.
        hed__Course_Offering__c coff = new hed__Course_Offering__c(
            Name = 'CourseOffering',
            hed__Course__c = cour.Id,
            hed__Term__c = term.Id,
            hed__Start_Date__c = System.today() + 2,
            hed__Capacity__c = 10
        );
        insert coff;
        // Create a course enrollment.
        hed__Course_Enrollment__c cenr = new hed__Course_Enrollment__c(
            hed__Contact__c = cont.Id,
            hed__Course_Offering__c = coff.Id
        );
        insert cenr;

        Test.stopTest();
    }
    
    @isTest
    private static void calloutToMDMAsNonESBUserTest(){        
        System.runAs(TestDataFactoryUser.selectUserQUTeXProgramAdministrator){
            Test.startTest();
            
            hed__Course_Enrollment__c cenr = [SELECT Id, Enrollment_Status__c FROM hed__Course_Enrollment__c LIMIT 1];
            cenr.Enrollment_Status__c = 'Admitted';
            update cenr;

            List<EventBusSubscriber> eventBusSubscriberList = [SELECT Position, Status FROM EventBusSubscriber WHERE Topic = 'MDM_Callout_Event__e' AND Type = 'ApexTrigger'];
            for(EventBusSubscriber eventBusSubscriber : eventBusSubscriberList){
                System.Assert.isTrue(eventBusSubscriber.Position > 0 && eventBusSubscriber.Status == 'Running', 'Student enrollments should be processed and handled by the event.');
            }

            Test.stopTest();
            
        }
    }

    @isTest
    private static void calloutToMDMAsESBUserTest(){       
        User esbIntegrationUser;
        System.runAs(TestDataFactoryUser.selectUserSystemAdministrator){
            Profile profile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
            esbIntegrationUser = new User(
                Username = 'testesbuser@test.com', 
                Email = 'testesbuser@test.com', 
                Alias = 'esbus', 
                ProfileId = profile.Id,
                TimeZoneSidKey = 'America/Los_Angeles', 
                LocaleSidKey = 'en_US', 
                EmailEncodingKey = 'UTF-8', 
                LanguageLocaleKey = 'en_US',
                FirstName = 'ESB',
                LastName = 'Integration User'
            );
            insert esbIntegrationUser;
        }

        System.runAs(esbIntegrationUser){
            Test.startTest();

            hed__Course_Enrollment__c cenr = [SELECT Id, Enrollment_Status__c FROM hed__Course_Enrollment__c LIMIT 1];
            cenr.Enrollment_Status__c = 'Admitted';
            update cenr;

            List<EventBusSubscriber> eventBusSubscriberList = [SELECT Position, Status FROM EventBusSubscriber WHERE Topic = 'MDM_Callout_Event__e' AND Type = 'ApexTrigger'];
            for(EventBusSubscriber eventBusSubscriber : eventBusSubscriberList){
                System.Assert.isTrue(eventBusSubscriber.Position == 0 && eventBusSubscriber.Status == 'Running', 'Student enrollments should not be processed and handled by the event.');
            }
            
            Test.stopTest();
        }
    }
    
}