src/core-crm/objects/Account/fields/Organization_Unit_Level__c.field-meta.xml
<CustomField>
    <fullName>Organization_Unit_Level__c</fullName>
    <description>The level (1,2,3) of the organizational unit within the QUT Organizational hierarchy.</description>
    <label>Organization Unit Level</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Course__c/hed__Course__c.object-meta.xml
<CustomObject>
    <description>Academic Course offered by a Department or School, for example, English 101 or Ancient History.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/Product_Request__c/Product_Request__c.object-meta.xml
<CustomObject>
    <label>Product Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Product Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Product_Request__c/fields/Product_Specification__c.field-meta.xml
<CustomField>
    <fullName>Product_Specification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Specification</label>
    <referenceTo>Product_Specification__c</referenceTo>
    <relationshipLabel>Product Requests</relationshipLabel>
    <relationshipName>Product_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Product_Specification__c/Product_Specification__c.object-meta.xml
<CustomObject>
    <label>Product Specification</label>
    <nameField>
        <displayFormat>PS-{00000}</displayFormat>
        <label>Product Specification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Specifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/classes/CreateCoursesCtrlTest.cls
/**
 * @description Tests the CreateCoursesCtrl class
 *
 * @see CreateCoursesCtrl
 *
 * @author Accenture
 *
 * @history
 *    | Developer                 | Date                  | JIRA     | Change Summary                  |
      |---------------------------|-----------------------|----------|---------------------------------|
      | angelika.j.s.galang       | October 25, 2021      | DEPP-383 | Created file                    |
      |                           |                       |          |                                 |
*/
@isTest
private class CreateCoursesCtrlTest {

    private static final String ACCT_UNIV_DEP = System.Label.RT_Account_University_Department;
    private static final Id ACCT_UNIV_DEP_ID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(ACCT_UNIV_DEP).getRecordTypeId();

    @testSetup static void setupMethod() {
        TestDataFactoryUser.generateUserQUTeXProgramAdministrator();
        Account acc = TestDataFactory.createTestAccountRecords(1).iterator().next();
        acc.RecordTypeId = ACCT_UNIV_DEP_ID;
        acc.Organization_Unit_Level__c = '2';
        insert acc;

        List<Contact> conList = TestDataFactory.createTestContactRecords(1);
        insert conList;

        List<Opportunity> oppList = TestDataFactory.createClosedWonOpportunities(1,acc?.Id,conList.iterator().next()?.Id);
        insert oppList;

        Product_Specification__c prodSpec = TestDataFactory.retrieveCCEProductSpecifications().iterator().next();

        Product_Request__c prodReq = TestDataFactory.createTestProductRequestRecords(1,prodSpec?.Id).iterator().next();
        insert prodReq;

        List<hed__Course__c> courseList = new List<hed__Course__c>();
        courseList.addAll(TestDataFactory.createTestCourseRecords(50,acc?.Id,null));
        courseList.addAll(TestDataFactory.createTestCourseRecords(50,acc?.Id,prodReq?.Id));

        Test.startTest();
        insert(courseList);
        Test.stopTest();
    }

    @isTest
    private static void getCoursesTest(){
        Test.startTest();
        System.runAs(TestDataFactoryUser.selectUserQUTeXProgramAdministrator){
            Id prodReqId = [SELECT Id FROM Product_Request__c LIMIT 1]?.Id;
            List<hed__Course__c> courseListToTest = CreateCoursesCtrl.getCourses(prodReqId);

            System.assertEquals(50, courseListToTest.size(), 'Course list did not match expected.');
        }
        Test.stopTest();
    }

}