src/core-crm/objects/Account/fields/Organization_Unit_Level__c.field-meta.xml
<CustomField>
    <fullName>Organization_Unit_Level__c</fullName>
    <description>The level (1,2,3) of the organizational unit within the QUT Organizational hierarchy.</description>
    <label>Organization Unit Level</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Account/recordTypes/Business_Organization.recordType-meta.xml
<RecordType>
    <fullName>Business_Organization</fullName>
    <active>true</active>
    <description>A business organization.</description>
    <label>Business Organization</label>
</RecordType>

src/core-crm/objects/Associated_Products__c/Associated_Products__c.object-meta.xml
<CustomObject>
    <label>Associated Products</label>
    <nameField>
        <displayFormat>AP - {000000}</displayFormat>
        <label>Associated Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/Associated_Products__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Determine if the Associated Product is active or not.</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Associated_Products__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Associated Products</relationshipLabel>
    <relationshipName>Associated_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Associated_Products__c/fields/Product_Request__c.field-meta.xml
<CustomField>
    <fullName>Product_Request__c</fullName>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Associated Products</relationshipLabel>
    <relationshipName>Associated_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/core-crm/objects/BuyerGroup/fields/Product_Request__c.field-meta.xml
<CustomField>
    <fullName>Product_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the parent Standing Offer Arrangement Product request</description>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Buyer Groups</relationshipLabel>
    <relationshipName>Buyer_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Cart_Payment__c/Cart_Payment__c.object-meta.xml
<CustomObject>
    <label>Cart Payment</label>
    <nameField>
        <label>Cart Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cart Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Cart_Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <description>Payment status returned from QUTPay</description>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled Payment</fullName>
            </value>
            <value>
                <fullName>Validation Failure</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Cart_Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Checkout</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/hed__Course_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Represents a connection to a Course Offering.</description>
    <label>Course Connection</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Course Connection ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Enrollment__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The course that the student is enrolment is related to</description>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Course Connections</relationshipLabel>
    <relationshipName>Course_Connections</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/hed__Course_Offering__c.field-meta.xml
<CustomField>
    <fullName>hed__Course_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Course Offering the student or faculty member is involved with.</description>
    <inlineHelpText>The Course Offering the student or faculty member is involved with.</inlineHelpText>
    <label>Course Offering ID</label>
    <referenceTo>hed__Course_Offering__c</referenceTo>
    <relationshipLabel>Course Connection</relationshipLabel>
    <relationshipName>Course_Enrollment</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This will be used to deactivate facilitators.</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/recordTypes/Default.recordType-meta.xml
<RecordType>
    <fullName>Default</fullName>
    <active>true</active>
    <description>A Default Record Type for use in testing. This Record Type should only be enabled and visible for System Administrators.</description>
    <label>Default</label>
</RecordType>

src/core-crm/objects/hed__Course_Offering__c/hed__Course_Offering__c.object-meta.xml
<CustomObject>
    <description>Joins Courses and Terms to contain information related to a single occurrence of a Course.</description>
    <label>Course Offering</label>
    <nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Course__c.field-meta.xml
<CustomField>
    <fullName>hed__Course__c</fullName>
    <description>Lookup to the Course record that this Course Offering is associated with.</description>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>
 

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Term__c.field-meta.xml
<CustomField>
    <fullName>hed__Term__c</fullName>
    <description>Lookup to the Term record that represents when this Course Offering takes place.</description>
    <label>Term</label>
    <referenceTo>hed__Term__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>
 

src/core-crm/objects/hed__Course_Offering__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This will be used to deactivate Offering.</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Client Approved</fullName>
            </value>
            <value>
                <fullName>Contract Created</fullName>
            </value>
            <value>
                <fullName>Contract Signed</fullName>
            </value>
            <value>
                <fullName>Drafter Review</fullName>
            </value>
            <value>
                <fullName>Drafting</fullName>
            </value>
            <value>
                <fullName>Drafting Complete</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Pending Contract Creation</fullName>
            </value>
            <value>
                <fullName>Pending Initial Proposal Approval</fullName>
            </value>
            <value>
                <fullName>Pending QUTeX Executive Approval</fullName>
            </value>
            <value>
                <fullName>QUTeX Executive Approved</fullName>
            </value>
            <value>
                <fullName>Under Client Review</fullName>
            </value>
            <value>
                <fullName>QUTeX Executive Proposal Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Product2/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Product_Request__c/Product_Request__c.object-meta.xml
<CustomObject>
    <label>Product Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Product Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Product_Request__c/fields/Product_Specification__c.field-meta.xml
<CustomField>
    <fullName>Product_Specification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Specification</label>
    <referenceTo>Product_Specification__c</referenceTo>
    <relationshipLabel>Product Requests</relationshipLabel>
    <relationshipName>Product_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Product_Request__c/recordTypes/Activity.recordType-meta.xml
<RecordType>
    <fullName>Activity</fullName>
    <active>true</active>
    <description>This record type will be used to create an Event, Discussion Forum, or workshop.</description>
    <label>Activity</label>
</RecordType>

src/core-crm/objects/Product_Request__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <description>This record type will be used to create a Program. This can be a combination of a Unit, a Module, a Short Course, or an Activity.</description>
    <label>Program</label>
</RecordType>

src/core-crm/objects/Product_Request__c/recordTypes/Standing_Offer_Arrangement.recordType-meta.xml
<RecordType>
    <fullName>Standing_Offer_Arrangement</fullName>
    <active>true</active>
    <description>This record type will be used to create Standing Offer Arrangement within Corporate Portal</description>
    <label>Standing Offer Arrangement</label>
</RecordType>

src/core-crm/objects/Product_Specification__c/Product_Specification__c.object-meta.xml
<CustomObject>
    <label>Product Specification</label>
    <nameField>
        <displayFormat>PS-{00000}</displayFormat>
        <label>Product Specification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Specifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Product_Specification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Stage__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Idea Sent</fullName>
            </value>
            <value>
                <fullName>Idea Received</fullName>
            </value>
            <value>
                <fullName>Qualification</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Does Not Meet Qualification</fullName>
            </value>
            <value>
                <fullName>Existing Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Product_Specification__c/recordTypes/CCE.recordType-meta.xml
<RecordType>
    <fullName>CCE</fullName>
    <active>true</active>
    <description>Used to Design products which are the result of a closed won Opportunity in Salesforce.</description>
    <label>CCE</label>
</RecordType>

src/core-crm/objects/WebCart/fields/Cart_Payment__c.field-meta.xml
<CustomField>
    <fullName>Cart_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cart Payment</label>
    <referenceTo>Cart_Payment__c</referenceTo>
    <relationshipLabel>Carts</relationshipLabel>
    <relationshipName>Carts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/WebCart/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <description>Payment status returned from QUTPay</description>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled Payment</fullName>
            </value>
            <value>
                <fullName>Validation Failure</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/WebCart/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Active = User in the process of adding items in cart

Checkout = User on checkout and prevents from updating cart

Closed = cart no longer available to the user</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Checkout</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/classes/CceManageRegistrationSectionCtrlTest.cls
/**
 * @description test class for CceManageRegistrationSectionCtrl
 * @see ../classes/CceManageRegistrationSectionCtrl
 * 
 * @author Accenture
 * 
 * @history
 *  | Developer                 | Date                  | JIRA                 | Change Summary               |
    |---------------------------|-----------------------|----------------------|------------------------------|
    | roy.nino.s.regala         | Aug 01, 2022          | DEPP-2498            | Created file                 | 
    |                           |                       |                      |                              | 
*/
@isTest
public with sharing class CceManageRegistrationSectionCtrlTest {

    private static final Id SOA_ID = Schema.SObjectType.Product_Request__c.getRecordTypeInfosByDeveloperName().get('Standing_Offer_Arrangement').getRecordTypeId();
    private static final Id ACTIVITY_ID = Schema.SObjectType.Product_Request__c.getRecordTypeInfosByDeveloperName().get('Activity').getRecordTypeId();
    private static final Id ACTIVITY_COURSE_ID = Schema.SObjectType.hed__Course__c.getRecordTypeInfosByDeveloperName().get('Activity').getRecordTypeId();
    private static final Id BUSINESS_ACC_RECTYPEID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Business_Organization').getRecordTypeId();
    private static Id cceProdSpecId = Schema.SObjectType.Product_Specification__c.getRecordTypeInfosByDeveloperName().get('CCE').getRecordTypeId();
    private static final String ACCT_UNIV_DEP = System.Label.RT_Account_University_Department;
    private static final Id ACCT_UNIV_DEP_ID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
        .get(ACCT_UNIV_DEP)
        .getRecordTypeId();
    private static final Id PROGRAM_ID = Schema.SObjectType.Product_Request__c.getRecordTypeInfosByDeveloperName().get('Program').getRecordTypeId();

    @testSetup 
    static void setupMethod() {
        Test.startTest();
        TestDataFactoryUser.generateUserSystemAdministrator();
        Test.stopTest();
        final User PORTAL_SYS_ADMIN = TestDataFactoryUser.selectUserSystemAdministrator;  
        System.runAs(PORTAL_SYS_ADMIN){

            List<Account> accounts = TestDataFactory.createTestAccountRecords(1);
            for(Account acc : accounts){
                acc.RecordTypeId = ACCT_UNIV_DEP_ID;
                acc.Organization_Unit_Level__c = '2';
            }

            List<Account> accountList = TestDataFactory.createTestAccountRecords(2);
    
            for(Account acc: accountList){
                acc.RecordTypeId = BUSINESS_ACC_RECTYPEID;
            }

            //Create account
            Account portalAccount1 = new Account(
            Name = 'TestAccount',
            OwnerId = PORTAL_SYS_ADMIN.Id
            );

            accountList.add(portalAccount1);
            accountList.addAll(accounts);
            insert accountList;

            List<Contact> conList;
            conList = TestDataFactory.createTestContactRecords(1);
            //Create contact
            Contact contact1 = new Contact(
            FirstName = 'portalUser',
            Lastname = 'Testing',
            AccountId = portalAccount1.Id,
            Email = System.now().millisecond() + 'portalUser@test.com'
            );
            conList.add(contact1);
            insert conList;

            WebStore testWebStore = new WebStore(
            Name = 'Study',
            DefaultLanguage = 'en_US'
            );
            insert testWebStore;

            //Create user
            User portalUser = TestDataFactory.createPortalUserRecords(
                1,
                'QUT Experience',
                contact1.Id
                )
                .iterator()
                .next();
            Database.insert(portalUser);
    
            List<Opportunity> oppList = TestDataFactory.createClosedWonOpportunities(1,accounts[0].Id,conList.iterator().next()?.Id);
            insert oppList;
    
            List<Product_Specification__c> prodSpecList = TestDataFactory.retrieveCCEProductSpecifications();
    
            List<Product_Request__c> soaRequest = TestDataFactory.createTestProductRequestRecords(1,prodSpecList[0].Id);
    
            Pricebook2 priceBook;
            pricebook = new Pricebook2(isActive = true, id = Test.getStandardPricebookId());
            update pricebook;
    
            for(Product_Request__c pr : soaRequest){
                pr.RecordTypeId = SOA_ID;        
            }
            insert soaRequest;
    
            List<BuyerGroup> bgToInsertList = new List<BuyerGroup>();
            List<PriceBook2> soaPBList = new List<PriceBook2>();
            List<Id> pbIds  = new List<Id>();
            for(Integer i = 0; i<soaRequest.size();i++){
            bgToInsertList.add(new BuyerGroup(Name ='SOA' + i, Product_Request__c = soaRequest[i].Id));
            }
            
            insert bgToInsertList;
            List<BuyerGroupPriceBook> bgPriceBookList = new List<BuyerGroupPriceBook>([
                SELECT Id, Pricebook2Id
                FROM BuyerGroupPriceBook
                WHERE BuyerGroupId IN: bgToInsertList
            ]);

            for(BuyerGroupPriceBook bgpb: bgPriceBookList){
                pbIds.add(bgPB.Pricebook2Id);
            }
            soaPBList = [SELECT Id FROM Pricebook2 WHERE Id IN: pbIds];

            List<Product_Request__c> courseRequest = TestDataFactory.createTestProductRequestRecords(1,prodSpecList[0].Id);
            for(Product_Request__c pr : courseRequest){
                pr.RecordTypeId = ACTIVITY_ID;        
            }
            insert courseRequest;
    
            List<hed__Course__c> courses = new List<hed__Course__c>();
            for(Product_Request__c prC: courseRequest){
            courses.addAll(TestDataFactory.createTestCourseRecords(1,accounts[0].Id,prC.Id));
            }
    
            for(hed__Course__c c: courses){
            c.RecordTypeId = ACTIVITY_COURSE_ID;
            }
            insert courses;
    
            List<Associated_Products__c> assocProdList = new List<Associated_Products__c>();
    
            List<Product2> prodList = new List<Product2>([SELECT Id From Product2 WHERE Course__c IN: courses]);
    
            for(Integer i = 0; i < prodList.size(); i ++){
            assocProdList.add(new Associated_Products__c(Product__c = prodList[i].Id, Product_Request__c = soaRequest[i].Id, IsActive__c = true));
            }
    
            insert assocProdList;
    
            List<PriceBookEntry> pbEToInsert = new List<PriceBookEntry>();
            List<PriceBookEntry> soaPBEToInsert = new List<PriceBookEntry>();
    
            for(Integer i = 0; i < prodList.size(); i ++){
            pbEToInsert.add(new PricebookEntry(Pricebook2Id = priceBook.Id, UnitPrice = 12, Product2Id = prodList[i].Id));
            soaPBEToInsert.add(new PricebookEntry(Pricebook2Id = soaPBList[0].Id, UnitPrice = 12, Product2Id = prodList[i].Id ));
            }
            insert pbEToInsert;
            insert soaPBEToInsert;
    
            List<hed__Term__c> terms = TestDataFactory.createTestTermRecords(1, accounts[0].Id);
    
            insert terms;
    
            List<hed__Course_Offering__c> courseOfferings = TestDataFactory.createTestCourseOfferingRecord(1, courses, terms);
            insert courseOfferings;
    
            Id offeringId = courseOfferings[0].Id;

            List<CartItem> cartItemsToInsert = new List<CartItem>();
            Cart_Payment__c cartPayment = new Cart_Payment__c();
            insert cartPayment;
            WebCart cart = new WebCart( Name = 'Cart', AccountId = portalAccount1.Id, Status = 'Active', Status__c = 'Active',
            WebStoreId = testWebStore.Id, OwnerId = portalUser.Id
            );
            insert cart;

            cart.Cart_Payment__c = cartPayment.Id;
            update cart;

            CartDeliveryGroup cartDeliveryGroup = new CartDeliveryGroup(
            CartId = cart.Id,
            Name = 'Default Delivery'
            );
            insert cartDeliveryGroup;

            CartItemHelper.CartItemDetails details = new CartItemHelper.CartItemDetails();
            details.offeringId = offeringId;
            details.newWebCartId = cart.Id;
            details.pbEntry = soaPBEToInsert[0];
            details.prescribedProgram = false;
            details.cartDeliveryGroupId = cartDeliveryGroup.Id;
            cartItemsToInsert.add(CartItemHelper.createCartItem(details));
            insert cartItemsToInsert;
            cartPayment.Payment_Status__c = 'Invoiced';
            update cartPayment;
        }
    }
    
    @isTest
    static void getLearnerDetailsTest(){
        Test.startTest();
        System.runAs(TestDataFactoryUser.selectUserSystemAdministrator){
            
            List<Product_Request__c> prList = new List<Product_Request__c>([
                SELECT Id 
                FROM Product_Request__c
                WHERE RecordTypeId =: SOA_ID
            ]);
            System.assert(!CceManageRegistrationSectionCtrl.getLearnerDetails(prList[0].Id).isEmpty(), 'no learners retrieved');
            
        }
        Test.stopTest();
    }

    @isTest
    static void updateLearnersTest(){
        Test.startTest();
        System.runAs(TestDataFactoryUser.selectUserSystemAdministrator){
            
            List<hed__Course_Enrollment__c> courseEnrollmentList = new List<hed__Course_Enrollment__c>([
                SELECT Id, hed__Status__c
                FROM hed__Course_Enrollment__c
                LIMIT 1
            ]);
            for(hed__Course_Enrollment__c courseEnrollment: courseEnrollmentList){
                courseEnrollment.hed__Status__c = 'Cancelled';
            }
            CceManageRegistrationSectionCtrl.updateLearners(courseEnrollmentList);
            System.assert(![SELECT Id FROM hed__Course_Enrollment__c WHERE hed__Status__c = 'Cancelled' LIMIT 1].isEmpty(), 'no learners updated');
            
        }
        Test.stopTest();
    }
}