src/core-crm/objects/Account/fields/Organization_Unit_Level__c.field-meta.xml
<CustomField>
    <fullName>Organization_Unit_Level__c</fullName>
    <description>The level (1,2,3) of the organizational unit within the QUT Organizational hierarchy.</description>
    <label>Organization Unit Level</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Contact/fields/Registered_Email__c.field-meta.xml
<CustomField>
    <fullName>Registered_Email__c</fullName>
    <description>All automated email communications will be sent to this email address.</description>
    <label>Registered Email</label>
    <type>Email</type>
</CustomField>

src/core-crm/objects/Expression_of_Interest__c/Expression_of_Interest__c.object-meta.xml
<CustomObject>
    <description>Record will be created when learner clicks &apos;Register Interest&apos; button against a Product in OPE catalogue or nominations from corporate portal</description>
    <label>Expression of Interest</label>
    <nameField>
        <displayFormat>EI-{0000}</displayFormat>
        <label>Expression of Interest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expression of Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Expression_of_Interest__c/fields/Program_Offering__c.field-meta.xml
<CustomField>
    <fullName>Program_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This will link to program offering that the learner successfully registered to for &apos;Register Interest&apos; process OR a link to the nominated program offering.</description>
    <label>Program Offering</label>
    <referenceTo>Program_Offering__c</referenceTo>
    <relationshipLabel>Expression of Interests</relationshipLabel>
    <relationshipName>Expression_of_Interests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Flow_Automation_Settings__c/Flow_Automation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Flow Automation Settings</label>
</CustomObject>

src/core-crm/objects/Flow_Automation_Settings__c/fields/New_Idea_To_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>New_Idea_To_Email_Address__c</fullName>
    <label>New Idea To Email Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Course__c/hed__Course__c.object-meta.xml
<CustomObject>
    <description>Academic Course offered by a Department or School, for example, English 101 or Ancient History.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Offering__c/hed__Course_Offering__c.object-meta.xml
<CustomObject>
    <description>Joins Courses and Terms to contain information related to a single occurrence of a Course.</description>
    <label>Course Offering</label>
    <nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Course__c.field-meta.xml
<CustomField>
    <fullName>hed__Course__c</fullName>
    <description>Lookup to the Course record that this Course Offering is associated with.</description>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>
 

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Term__c.field-meta.xml
<CustomField>
    <fullName>hed__Term__c</fullName>
    <description>Lookup to the Term record that represents when this Course Offering takes place.</description>
    <label>Term</label>
    <referenceTo>hed__Term__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>
 

src/core-crm/objects/hed__Course_Offering__c/fields/Program_Offering__c.field-meta.xml
<CustomField>
    <fullName>Program_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Linked the course offering to the Program offering for Prescribed
    Program.</description>
    <label>Program Offering</label>
    <referenceTo>Program_Offering__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Program_Plan__c/hed__Program_Plan__c.object-meta.xml
<CustomObject>
    <description>Links Courses to an Academic Program to create a path for students to follow. An Academic Program can list multiple Courses, and a Course can be associated with multiple Academic Programs.</description>
    <label>Program Plan</label>
    <nameField>
        <label>Program Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Program_Plan__c/fields/Product_Request__c.field-meta.xml
<CustomField>
    <fullName>Product_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the related Product Request record of the Program Plan.</description>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Term__c/hed__Term__c.object-meta.xml
<CustomObject>
    <description>Unit of time in which academic activities are taking place.</description>
    <label>Term</label>
    <nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/Product2/fields/Program_Plan__c.field-meta.xml
<CustomField>
    <fullName>Program_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Plan</label>
    <referenceTo>hed__Program_Plan__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Product_Request__c/Product_Request__c.object-meta.xml
<CustomObject>
    <label>Product Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Product Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Program_Offering__c/Program_Offering__c.object-meta.xml
<CustomObject>
    <label>Program Offering</label>
    <nameField>
        <label>Program Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/classes/B2BRegisterInterestBatchTest.cls
/**
 * @description Tests Batch Class for B2BRegisterInterestBatch
 * @see B2BRegisterInterestBatch
 *
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | roy.nino.s.regala              | February 03, 2022     | DEPP-213               | Created file                 |
      |                                |                       |                        |                              |
 */
@isTest
public class B2BRegisterInterestBatchTest {
    private static final String ACCT_UNIV_DEP = System.Label.RT_Account_University_Department;
    private static final Id ACCT_UNIV_DEP_ID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(ACCT_UNIV_DEP).getRecordTypeId();

    @testSetup static void setupMethod() {
        Flow_Automation_Settings__c customEmail = new Flow_Automation_Settings__c(Name='test',New_Idea_To_Email_Address__c = 'test-qutex@yopmail.com');
        insert customEmail;

        List<Account> accounts;
        List<Contact> contacts;
        List<hed__Term__c> terms;
        List<Product_Request__c> prodRequest;
        List<hed__Course_Offering__c> courseOfferings;
        List<hed__Course__c> courses;
        List<hed__Program_Plan__c> programPlans;
        List<Program_Offering__c> programOfferings;
        List<Product2> products;
        List<Expression_of_Interest__c> interests;
        Pricebook2 priceBook;
        PricebookEntry priceBookEntry;

        accounts = TestDataFactory.createTestAccountRecords(1);
        for(Account acc : accounts){
            acc.RecordTypeId = ACCT_UNIV_DEP_ID;
            acc.Organization_Unit_Level__c = '2';
        }
        insert accounts;
        contacts = TestDataFactory.createTestContactRecords(1);
        contacts[0].email ='testquttestqut@email.com';
        contacts[0].Registered_Email__c = 'registeredemail@email.com';
        insert Contacts;
        terms = TestDataFactory.createTestTermRecords(25,accounts[0].Id);
        insert terms;
        prodRequest = TestDataFactory.createTestProductRequestRecords(1);
        insert prodRequest;
        courses = TestDataFactory.createTestCourseRecords(25,accounts[0].Id,prodRequest[0].Id);
        insert courses;
        programPlans = TestDataFactory.createTestProgramPlanRecords(25);
        insert programPlans;
        programOfferings = TestDataFactory.createTestProgramOfferingRecords(25, programPlans);
        insert programOfferings;
        products = TestDataFactory.createTestProductRecords(25,courses);
        for (Integer i = 0; i < products.size(); i++) {
            products[i].Program_Plan__c = programPlans[i].Id;
        }
        insert products;
        pricebook = new Pricebook2(isActive = true, id = Test.getStandardPricebookId());
        update pricebook;
        priceBookEntry = new PricebookEntry(pricebook2id = pricebook.Id, UnitPrice = 12, product2Id = products[0].Id, isActive = true);
        insert priceBookEntry;
        courseOfferings = TestDataFactory.createTestCourseOfferingRecord(25,courses,terms);
        insert courseOfferings;
        interests = TestDataFactory.createExpressionOfInterest(25,contacts[0],products);
        insert interests;

        TestDataFactoryUser.generateUserSystemAdministrator();
    }


    @isTest
    public static void testRegisterInterest() {
    final User PORTAL_SYS_ADMIN = TestDataFactoryUser.selectUserSystemAdministrator;
        System.runAs(PORTAL_SYS_ADMIN) {
            String htmlValue = 'Contact_FirstName Contact_LastName Product_Name Product_URL';
            Id userId = UserInfo.getUserId();
            EmailTemplate e = new EmailTemplate(developerName = 'Offering_Available_Email_Notification',
                                                HtmlValue = htmlValue,
                                                TemplateType= 'Text',
                                                Name = 'Offering_Available_Email_Notification',
                                                folderId = userId
                                                );
            insert e;
            Test.startTest();
            Database.executeBatch(new B2BRegisterInterestBatch(), 200);
            system.assertEquals(0,
                                Limits.getEmailInvocations(),
                                'Number of email invocations not as expected'
                                );
            Test.stopTest();
        }
    }


}