src/core-crm/objects/Account/fields/Organization_Unit_Level__c.field-meta.xml
<CustomField>
    <fullName>Organization_Unit_Level__c</fullName>
    <description>The level (1,2,3) of the organizational unit within the QUT Organizational hierarchy.</description>
    <label>Organization Unit Level</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Communication_Schedule__c/Communication_Schedule__c.object-meta.xml
<CustomObject>
    <label>Communication Schedule</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Communication Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Communication_Schedule__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to related Course record.</description>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Communication Schedules</relationshipLabel>
    <relationshipName>Communication_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Field_Layout_Setting__mdt/Field_Layout_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Manages usage of fields on custom UI development.</description>
    <label>Field Layout Setting</label>
    <pluralLabel>Field Layout Settings</pluralLabel>
</CustomObject>

src/core-crm/objects/hed__Course__c/hed__Course__c.object-meta.xml
<CustomObject>
    <description>Academic Course offered by a Department or School, for example, English 101 or Ancient History.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course__c/fields/Diagnostic_Tool_Type__c.field-meta.xml
<CustomField>
    <fullName>Diagnostic_Tool_Type__c</fullName>
    <label>Diagnostic Tool Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual Diagnostic Tool</fullName>
            </value>
            <value>
                <fullName>Group Diagnostic Tool</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Course__c/fields/ProductRequestID__c.field-meta.xml
<CustomField>
    <fullName>ProductRequestID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course__c/recordTypes/Diagnostic_Tool.recordType-meta.xml
<RecordType>
    <fullName>Diagnostic_Tool</fullName>
    <active>true</active>
    <label>Diagnostic Tool</label>
</RecordType>

src/core-crm/objects/Product2/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Product_Request__c/Product_Request__c.object-meta.xml
<CustomObject>
    <label>Product Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Product Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/program-specification-management/main/objects/Product_Request__c/fields/Diagnostic_Tool_Type__c.field-meta.xml
<CustomField>
    <fullName>Diagnostic_Tool_Type__c</fullName>
    <label>Diagnostic Tool Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Self Rater Tool</fullName>
            </value>
            <value>
                <fullName>Multi Rater Tool</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Product_Request__c/recordTypes/Diagnostic_Tool.recordType-meta.xml
<RecordType>
    <fullName>Diagnostic_Tool</fullName>
    <active>true</active>
    <description>This record type will be used to request diagnostic tool which can be delivered in isolation or as part of a program.</description>
    <label>Diagnostic Tool</label>
</RecordType>

src/core-crm/classes/CustomLayoutCtrlTest.cls
/**
 * @description Test class for CustomLayoutCtrl
 *
 * @see CustomLayoutCtrl
 *
 * @author Accenture
 *
 * @history
 *    | Developer                 | Date                  | JIRA                 | Change Summary                                         |
      |---------------------------|-----------------------|----------------------|--------------------------------------------------------|
      | angelika.j.s.galang       | January 26, 2022      | DEPP-838,1299,1407   | Created file                                           |
*/
@isTest
private class CustomLayoutCtrlTest {

    private static final String COURSE_API_NAME = hed__Course__c.SObjectType.getDescribe(SObjectDescribeOptions.DEFERRED).getLocalName();
    private static final String COURSE_PR_FIELD = 'ProductRequestID__c';
    private static final String PRODUCT_API_NAME = Product2.SObjectType.getDescribe(SObjectDescribeOptions.DEFERRED).getLocalName();
    private static final String PRODUCT_COURSE_FIELD = 'Course__c';
    private static final String COMMUNICATION_SCHEDULE_API_NAME = Communication_Schedule__c.SObjectType.getDescribe(SObjectDescribeOptions.DEFERRED).getLocalName();
    private static final String MDT_COMMUNICATION_SCHEDULE = 'All_OPE_Communication_Schedules';
    private static User currentUser = TestDataFactory.createUserRecords(1, 'QUTeX').iterator().next();
    private static final String ACCT_UNIV_DEP = System.Label.RT_Account_University_Department;
    private static final Id ACCT_UNIV_DEP_ID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(ACCT_UNIV_DEP).getRecordTypeId();

    @testSetup static void setupMethod() {
        Account acc = TestDataFactory.createTestAccountRecords(1).iterator().next();
        acc.RecordTypeId = ACCT_UNIV_DEP_ID;
        acc.Organization_Unit_Level__c = '2';
        insert acc;
        Product_Request__c pr = TestDataFactory.createTestProductRequestRecords(1).iterator().next();
        insert pr;
        hed__Course__c course = TestDataFactory.createTestCourseRecords(1,acc?.Id,pr?.Id).iterator().next();
        course.Diagnostic_Tool_Type__c = 'Group Diagnostic Tool';
        insert course;
        Product2 product = TestDataFactory.createTestProductRecords(1, new List<hed__Course__c>{course}).iterator().next();
        insert product;
        TestDataFactoryUser.generateUserQUTeXProgramAdministrator();
    }

    @isTest
    private static void getChildRecordIdTest(){
        System.runAs(TestDataFactoryUser.selectUserQUTeXProgramAdministrator){
            Product_Request__c pr = [SELECT Id FROM Product_Request__c LIMIT 1];
            hed__Course__c course = [SELECT Id FROM hed__Course__c LIMIT 1];
            Test.startTest();
            CustomLayoutCtrl.GetRecordFilter filter = new CustomLayoutCtrl.GetRecordFilter();
            filter.parentId = pr?.Id;
            filter.parentField = COURSE_PR_FIELD;
            filter.childObjectType = COURSE_API_NAME;
            filter.grandChildInfo = new Map<String,String>();
            Id courseId = CustomLayoutCtrl.getChildRecordId(filter);
            Test.stopTest();
            System.assertEquals(course?.Id, courseId, 'Course Id did not match expected.');
        }
    }

    @isTest
    private static void getParentRecordTest(){
        System.runAs(TestDataFactoryUser.selectUserQUTeXProgramAdministrator){
            Product_Request__c pr = [SELECT Id FROM Product_Request__c LIMIT 1];
            hed__Course__c course = [SELECT Id FROM hed__Course__c LIMIT 1];
            Test.startTest();
            CustomLayoutCtrl.GetRecordFilter filter = new CustomLayoutCtrl.GetRecordFilter();
            filter.parentId = pr?.Id;
            filter.parentField = COURSE_PR_FIELD;
            filter.childObjectType = COURSE_API_NAME;
            filter.fields = 'Id ';
            filter.grandChildInfo = new Map<String,String>();
            sObject courseRecord = CustomLayoutCtrl.getParentRecord(filter);

            Test.stopTest();
            System.assertEquals(courseRecord?.Id, course.Id, 'Course did not match expected.');
        }
    }

    @isTest
    private static void getGrandChildRecordIdTest(){
        System.runAs(TestDataFactoryUser.selectUserQUTeXProgramAdministrator){
            Product_Request__c pr = [SELECT Id FROM Product_Request__c LIMIT 1];
            Product2 product = [SELECT Id FROM Product2 LIMIT 1];
            Map<String,String> grandChild = new Map<String,String>();
            grandChild.put('objectApiName',PRODUCT_API_NAME);
            grandChild.put('conditionField',PRODUCT_COURSE_FIELD);
            Test.startTest();
            CustomLayoutCtrl.GetRecordFilter filter = new CustomLayoutCtrl.GetRecordFilter();
            filter.parentId = pr?.Id;
            filter.parentField = COURSE_PR_FIELD;
            filter.childObjectType = COURSE_API_NAME;
            filter.grandChildInfo = grandChild;
            Id productId = CustomLayoutCtrl.getChildRecordId(filter);
            Test.stopTest();
            System.assertEquals(product?.Id, productId, 'Product Id did not match expected.');
        }
    }

    @isTest
    private static void getGrandParentRecordTest(){
        System.runAs(TestDataFactoryUser.selectUserQUTeXProgramAdministrator){
            Product_Request__c pr = [SELECT Id FROM Product_Request__c LIMIT 1];
            Product2 product = [SELECT Id FROM Product2 LIMIT 1];
            Map<String,String> grandChild = new Map<String,String>();
            grandChild.put('objectApiName',PRODUCT_API_NAME);
            grandChild.put('conditionField',PRODUCT_COURSE_FIELD);
            Test.startTest();
            CustomLayoutCtrl.GetRecordFilter filter = new CustomLayoutCtrl.GetRecordFilter();
            filter.parentId = pr?.Id;
            filter.parentField = COURSE_PR_FIELD;
            filter.childObjectType = COURSE_API_NAME;
            filter.fields = 'Id ';
            filter.grandChildInfo = grandChild;
            sObject productRecord = CustomLayoutCtrl.getParentRecord(filter);
            Test.stopTest();
            System.assertEquals(productRecord?.Id, product.Id, 'Product Id did not match expected.');
        }
    }

    @isTest
    private static void getLayoutMappingTest(){
        System.runAs(TestDataFactoryUser.selectUserQUTeXProgramAdministrator){
            Test.startTest();
            List<Field_Layout_Setting__mdt> fieldLayoutList = CustomLayoutCtrl.getLayoutMapping(COMMUNICATION_SCHEDULE_API_NAME,MDT_COMMUNICATION_SCHEDULE,true);
            Test.stopTest();
            System.assert(fieldLayoutList.size() == 1, 'Field Layout Setting list did not match expected.');
        }
    }

    @isTest
    private static void getLayoutMappingWithFieldTest(){


        System.runAs(TestDataFactoryUser.selectUserQUTeXProgramAdministrator){
            Test.startTest();
            Product_Request__c pr = [SELECT Id FROM Product_Request__c LIMIT 1];
            Map<String,String> objectMap = new Map<String,String>();
            objectMap.put('recordType','Diagnostic_Tool');
            objectMap.put('childObject','hed__Course__c');
            objectMap.put('fieldApiName','Diagnostic_Tool_Type__c');
            objectMap.put('parentField','ProductRequestID__c');
            List<Field_Layout_Setting__mdt> fieldLayoutList = CustomLayoutCtrl.getLayoutMappingWithField(objectMap,pr.Id);
            Test.stopTest();
            System.assert(!fieldLayoutList.isEmpty(), 'Field Layout Setting list did not match expected.');
        }
    }

}