src/core-crm/objects/Account/fields/Organization_Unit_Level__c.field-meta.xml
<CustomField>
    <fullName>Organization_Unit_Level__c</fullName>
    <description>The level (1,2,3) of the organizational unit within the QUT Organizational hierarchy.</description>
    <label>Organization Unit Level</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Account/recordTypes/Business_Organization.recordType-meta.xml
<RecordType>
    <fullName>Business_Organization</fullName>
    <active>true</active>
    <description>A business organization.</description>
    <label>Business Organization</label>
</RecordType>

src/core-crm/objects/Asset/fields/Product_Request__c.field-meta.xml
<CustomField>
    <fullName>Product_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/BuyerGroup/fields/Product_Request__c.field-meta.xml
<CustomField>
    <fullName>Product_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the parent Standing Offer Arrangement Product request</description>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Buyer Groups</relationshipLabel>
    <relationshipName>Buyer_Groups</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/main/objects/Contact/fields/hed__Primary_Organization__c.field-meta.xml
<CustomField>
    <fullName>hed__Primary_Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the main Organization (Account record) this Contact is associated with.</description>
    <inlineHelpText>Lookup to the main Organization (Account record) this Contact is associated with.</inlineHelpText>
    <label>Primary Business Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts (Primary Organization)</relationshipLabel>
    <relationshipName>Organization_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Contact/fields/Registered_Email__c.field-meta.xml
<CustomField>
    <fullName>Registered_Email__c</fullName>
    <description>All automated email communications will be sent to this email address.</description>
    <label>Registered Email</label>
    <type>Email</type>
</CustomField>

src/core-crm/objects/hed__Affiliation__c/hed__Affiliation__c.object-meta.xml
<CustomObject>
    <description>Connection between a Contact and an Account.</description>
    <label>Affiliation</label>
    <nameField>
        <displayFormat>AF-{000000}</displayFormat>
        <label>Affiliation Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course__c/hed__Course__c.object-meta.xml
<CustomObject>
    <description>Academic Course offered by a Department or School, for example, English 101 or Ancient History.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course__c/recordTypes/Activity.recordType-meta.xml
<RecordType>
    <fullName>Activity</fullName>
    <active>true</active>
    <label>Activity</label>
    <picklistValues>
        <!-- Renamed from Collaboation_External__c-->
        <picklist>Collaboration_with_External_Organisation__c</picklist>
        <values>
            <fullName>No</fullName>
        </values>
        <values>
            <fullName>Yes</fullName>
        </values>
    </picklistValues>
</RecordType>

src/core-crm/objects/hed__Course_Enrollment__c/hed__Course_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Represents a connection to a Course Offering.</description>
    <label>Course Connection</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Course Connection ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Enrollment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Cost of Product</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/hed__Affiliation__c.field-meta.xml
<CustomField>
    <fullName>hed__Affiliation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If this Contact is affiliated with an Academic Program through an existing Program Enrollment record, and that Program Enrollment is related to this Course Connection, this Affiliation field is auto-populated with the Program Enrollment&apos;s Affiliation. If both conditions aren&apos;t true, then this Affiliation field is left blank.</description>
    <inlineHelpText>The Academic Program associated with this Course Connection. Represents a Contact-Account Affiliation.</inlineHelpText>
    <label>Affiliation</label>
    <referenceTo>hed__Affiliation__c</referenceTo>
    <relationshipLabel>Course Connection</relationshipLabel>
    <relationshipName>Course_Enrollment</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/hed__Course_Offering__c.field-meta.xml
<CustomField>
    <fullName>hed__Course_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Course Offering the student or faculty member is involved with.</description>
    <inlineHelpText>The Course Offering the student or faculty member is involved with.</inlineHelpText>
    <label>Course Offering ID</label>
    <referenceTo>hed__Course_Offering__c</referenceTo>
    <relationshipLabel>Course Connection</relationshipLabel>
    <relationshipName>Course_Enrollment</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/hed__Course_Offering__c.object-meta.xml
<CustomObject>
    <description>Joins Courses and Terms to contain information related to a single occurrence of a Course.</description>
    <label>Course Offering</label>
    <nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Course__c.field-meta.xml
<CustomField>
    <fullName>hed__Course__c</fullName>
    <description>Lookup to the Course record that this Course Offering is associated with.</description>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>
 

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Term__c.field-meta.xml
<CustomField>
    <fullName>hed__Term__c</fullName>
    <description>Lookup to the Term record that represents when this Course Offering takes place.</description>
    <label>Term</label>
    <referenceTo>hed__Term__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>
 

src/core-crm/objects/hed__Term__c/hed__Term__c.object-meta.xml
<CustomObject>
    <description>Unit of time in which academic activities are taking place.</description>
    <label>Term</label>
    <nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/Product_Ledger__c/Product_Ledger__c.object-meta.xml
<CustomObject>
    <label>Product Ledger</label>
    <nameField>
        <displayFormat>PL-{00000000}</displayFormat>
        <label>Product Ledger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Ledgers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/Product_Request__c/Product_Request__c.object-meta.xml
<CustomObject>
    <label>Product Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Product Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Product_Request__c/fields/Product_Specification__c.field-meta.xml
<CustomField>
    <fullName>Product_Specification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Specification</label>
    <referenceTo>Product_Specification__c</referenceTo>
    <relationshipLabel>Product Requests</relationshipLabel>
    <relationshipName>Product_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Product_Request__c/recordTypes/Activity.recordType-meta.xml
<RecordType>
    <fullName>Activity</fullName>
    <active>true</active>
    <description>This record type will be used to create an Event, Discussion Forum, or workshop.</description>
    <label>Activity</label>
</RecordType>

src/core-crm/objects/Product_Request__c/recordTypes/Corporate_Bundle.recordType-meta.xml
<RecordType>
    <fullName>Corporate_Bundle</fullName>
    <active>true</active>
    <description>This record type will be used to set up the Corporate Bundle for the client in the corporate portal. This will include assigning courses to the customer that can be used for Corporate Bundle as well as setting up the product that they can use.</description>
    <label>Corporate Bundle</label>
</RecordType>

src/core-crm/objects/Product_Request__c/recordTypes/Standing_Offer_Arrangement.recordType-meta.xml
<RecordType>
    <fullName>Standing_Offer_Arrangement</fullName>
    <active>true</active>
    <description>This record type will be used to create Standing Offer Arrangement within Corporate Portal</description>
    <label>Standing Offer Arrangement</label>
</RecordType>

src/core-crm/objects/Product_Specification__c/Product_Specification__c.object-meta.xml
<CustomObject>
    <label>Product Specification</label>
    <nameField>
        <displayFormat>PS-{00000}</displayFormat>
        <label>Product Specification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Specifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Product_Specification__c/recordTypes/CCE.recordType-meta.xml
<RecordType>
    <fullName>CCE</fullName>
    <active>true</active>
    <description>Used to Design products which are the result of a closed won Opportunity in Salesforce.</description>
    <label>CCE</label>
</RecordType>

src/core-crm/classes/CorporateBundleAndSOAHelperTest.cls
/**
 * @description Test Class for ContactWithMatchingLeadHelper
 * @see ..ContactWithMatchingLeadHelper
 *
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | roy.nino.s.regala              | Sep 9, 2022           | DEPP-3770              | creates test class           |
 */
@isTest
public with sharing class CorporateBundleAndSOAHelperTest {

     public static final String CCE_CATALOG = 'CCE Catalog';
    public static final String CCE_CATEGORY_QLS = 'QUTeX Learning Solutions'; 
    public static final String CCE_CATEGORY_CB = 'Corporate Bundle';
    private static final String PRODUCT_SPEC_RT = System.Label.RT_ProductSpecification_OPEProgramSpecification;
    private static Id opeProdSpecId = Schema.SObjectType.Product_Specification__c.getRecordTypeInfosByDeveloperName().get(PRODUCT_SPEC_RT).getRecordTypeId();
    private static Id cceProdSpecId = Schema.SObjectType.Product_Specification__c.getRecordTypeInfosByDeveloperName().get('CCE').getRecordTypeId();

    private static final Id ACTIVITY_ID = Schema.SObjectType.Product_Request__c.getRecordTypeInfosByDeveloperName().get('Activity').getRecordTypeId();
    private static final Id ACTIVITY_COURSE_ID = Schema.SObjectType.hed__Course__c.getRecordTypeInfosByDeveloperName().get('Activity').getRecordTypeId();

    private static final Id BUSINESS_ACC_RECTYPEID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
        .get('Business_Organization')
        .getRecordTypeId();

    private static final String ACCT_UNIV_DEP = System.Label.RT_Account_University_Department;
    private static final Id ACCT_UNIV_DEP_ID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
        .get(ACCT_UNIV_DEP)
        .getRecordTypeId();

    private static final Id PR_CORPBUNDLE_RECTYPEID = Schema.SObjectType.Product_Request__c.getRecordTypeInfosByDeveloperName()
        .get('Corporate_Bundle')
        .getRecordTypeId();

    public static final Id PR_STANDOFFERARRANGE_RECTYPEID = Schema.SObjectType.Product_Request__c.getRecordTypeInfosByDeveloperName()
        .get('Standing_Offer_Arrangement')
        .getRecordTypeId(); 

     @testSetup
     static void testSetup() {
          Test.startTest();
          TestDataFactoryUser.generateUserQUTeXProgramAdministrator();
          TestDataFactoryUser.generateUserSystemAdministrator();
          Test.stopTest();
          System.runAs(TestDataFactoryUser.selectUserQUTeXProgramAdministrator){

               WebStore testWebStore = new WebStore(Name='CCE', DefaultLanguage='en_US');
               insert testWebStore;
     
               ProductCatalog prodCatalog = new ProductCatalog(Name = 'CCE Catalog');
               insert prodCatalog;
     
               ProductCategory prodCategCB = new ProductCategory(
               Name = CCE_CATEGORY_CB,
               CatalogId = prodCatalog.Id
               );
               insert prodCategCB;

               Account account = new Account();
               account.Name = 'Test Business Org Account';
               account.RecordTypeId = BUSINESS_ACC_RECTYPEID;
               insert account;

               List<Account> offeringAccount = TestDataFactory.createTestAccountRecords(1);
               for(Account acc : offeringAccount){
                    acc.RecordTypeId = ACCT_UNIV_DEP_ID;
                    acc.Organization_Unit_Level__c = '2';
               }
               insert offeringAccount;

               Contact contact = new Contact();
               contact.FirstName = 'Test Partner User Contact';
               contact.LastName = 'Test Lname';
               contact.email = 'testcorporateuser@email.com';
               contact.Registered_Email__c = 'registeredtest@email.com';
               contact.AccountId = account.Id;
               insert contact;
               
               List<AccountContactRelation> acrList = new List<AccountContactRelation>([
                    SELECT ContactId 
                    FROM AccountContactRelation 
                    WHERE AccountId =: account.Id
                    AND IsActive = true
                    LIMIT 1
               ]);

               if(acrList.isEmpty()){
                    AccountContactRelation acr = new AccountContactRelation(
                         ContactId = contact.Id,
                         AccountId = account.Id
                    );

                    insert acr;
               }

               List<Contact> conList = new List<Contact>();
               conList.add(contact);

               List<Opportunity> opp = TestDataFactory.createClosedWonOpportunities(1,account.Id,contact.Id);
               insert opp;

               Pricebook2 priceBook;
               pricebook = new Pricebook2(isActive = true, id = Test.getStandardPricebookId());
               update pricebook;

               List<Product_Specification__c> prodSpecList = TestDataFactory.retrieveCCEProductSpecifications();

               List<Product_Request__c> cbRequest = TestDataFactory.createTestProductRequestRecords(1,prodSpecList[0].Id);
               for(Product_Request__c pr : cbRequest){
                    pr.RecordTypeId = PR_CORPBUNDLE_RECTYPEID;        
               }
               insert cbRequest;
               
               List<Asset> assetInsert = new List<Asset>();
               assetInsert.add(new Asset(
                    Name='Corporate Bundle',
                    AccountId = account.Id,
                    Product_Request__c = cbRequest[0].Id
               ));
               insert assetInsert;
               
               List<BuyerGroup> bgToInsertList = new List<BuyerGroup>();
               bgToInsertList.add(new BuyerGroup(
                    Name = 'Corporate Bundle - ' + account.Name,
                    Product_Request__c = cbRequest[0].Id
               ));
               insert bgToInsertList;

               List<Product_Request__c> courseRequest = TestDataFactory.createTestProductRequestRecords(1,prodSpecList[0].Id);
               for(Product_Request__c pr : courseRequest){
                    pr.RecordTypeId = ACTIVITY_ID;        
               }
               insert courseRequest;

               List<hed__Course__c> courses = new List<hed__Course__c>();
               for(Product_Request__c prC: courseRequest){
               courses.addAll(TestDataFactory.createTestCourseRecords(1,offeringAccount[0].Id,prC.Id));
               }
     
               for(hed__Course__c c: courses){
               c.RecordTypeId = ACTIVITY_COURSE_ID;
               }
               insert courses;

               List<hed__Term__c> terms = TestDataFactory.createTestTermRecords(1, offeringAccount[0].Id);
    
               insert terms;
     
               List<hed__Course_Offering__c> courseOfferings = TestDataFactory.createTestCourseOfferingRecord(1, courses, terms);
               insert courseOfferings;
          }

          System.runAs(TestDataFactoryUser.selectUserSystemAdministrator){
               Contact con = [SELECT Id,Registered_Email__c,LastName,FirstName FROM Contact WHERE Registered_Email__c =: 'registeredtest@email.com' Limit 1];
               Profile profile = [SELECT Id FROM Profile WHERE Name = 'Corporate Partner' LIMIT 1];
               User commerceUser = new User();
               commerceUser.IsActive = true;
               commerceUser.Username = contact.Registered_Email__c + '.cce';
               commerceUser.Email = con.Registered_Email__c;
               commerceUser.LastName = con.LastName;
               commerceUser.FirstName = con.FirstName;
               commerceUser.ContactId = con.Id;
               commerceUser.alias = con.FirstName.substring(0, 1) + con.LastName.substring(0, 2);
               commerceUser.LanguageLocaleKey = 'en_US';
               commerceUser.localesidkey = 'en_AU';
               commerceUser.emailEncodingKey = 'UTF-8';
               commerceUser.timeZoneSidKey = 'Australia/Brisbane';
               commerceUser.profileId = profile.Id;

               insert commerceUser;
          }
     }

     @isTest
     private static void getCorporateUserTest(){
          System.runAs(TestDataFactoryUser.selectUserQUTeXProgramAdministrator){
               Pricebook2 pricebookRecord = [
                    SELECT Id 
                    FROM Pricebook2
                    WHERE Name LIKE 'Corporate Bundle%'
                    LIMIT 1
               ];

               Test.startTest();
               System.assert(!CorporateBundleAndSOAHelper.getCorporateUser(pricebookRecord.Id).isEmpty(), 'No Corporate user retrieved');
               Test.stopTest();
          }
     }

     @isTest
     private static void createCCEWebCartTest(){
          System.runAs(TestDataFactoryUser.selectUserQUTeXProgramAdministrator){
               User corporateUser = [
                    SELECT Id, AccountId, Contact.hed__Primary_Organization__c
                    FROM User 
                    WHERE Contact.FirstName = 'Test Partner User Contact' 
               ];

               Test.startTest();
               System.assert(CorporateBundleAndSOAHelper.createCCEWebCart(corporateUser) != null, 'No Web Cart record partially created');
               Test.stopTest();
          }
     }

     @isTest
     private static void checkCreditAvailabilityTest(){
          System.runAs(TestDataFactoryUser.selectUserQUTeXProgramAdministrator){

               Pricebook2 pricebookRecord = [
                    SELECT Id
                    FROM Pricebook2
                    WHERE Name Like 'Corporate%'
               ];

               Product2 productToInsert = new Product2(
                    IsActive = true,
                    Name = 'Test Asset Product'
               );

               insert productToInsert;

               List<PricebookEntry> pbEToInsert = new List<PricebookEntry>();

               Pricebook2 standardPriceBook = [
                    SELECT Id
                    FROM Pricebook2
                    WHERE IsStandard = true
               ];
               pbEToInsert.add(new PricebookEntry(Pricebook2Id = standardPriceBook.Id, UnitPrice = 12, Product2Id = productToInsert.Id));
               pbEToInsert.add(new PricebookEntry(Pricebook2Id = pricebookRecord.Id, UnitPrice = 12, Product2Id = productToInsert.Id ));

               insert pbEToInsert;
               Test.startTest();
               System.assert(!CorporateBundleAndSOAHelper.checkCreditAvailability(
                    String.valueOf(pbEToInsert[1].Id),
                    String.valueOf([SELECT Id FROM Asset LIMIT 1].Id)),'Asset is available');
               Test.stopTest();
          }
     }


     @isTest
     private static void getAssetTest(){
          System.runAs(TestDataFactoryUser.selectUserQUTeXProgramAdministrator){

               Pricebook2 pricebookRecord = [
                    SELECT Id
                    FROM Pricebook2
                    WHERE Name Like 'Corporate%'
               ];

               Product2 productToInsert = new Product2(
                    IsActive = true,
                    Name = 'Test Asset Product'
               );

               insert productToInsert;

               List<PricebookEntry> pbEToInsert = new List<PricebookEntry>();

               Pricebook2 standardPriceBook = [
                    SELECT Id
                    FROM Pricebook2
                    WHERE IsStandard = true
               ];
               pbEToInsert.add(new PricebookEntry(Pricebook2Id = standardPriceBook.Id, UnitPrice = 12, Product2Id = productToInsert.Id));
               pbEToInsert.add(new PricebookEntry(Pricebook2Id = pricebookRecord.Id, UnitPrice = 12, Product2Id = productToInsert.Id ));

               insert pbEToInsert;

               List<String> pbEntryIds = new List<String>();
               for(PricebookEntry pbe: pbEToInsert){
                    pbEntryIds.add(pbe.Id);
               }
               Test.startTest();
               System.assert(!CorporateBundleAndSOAHelper.getAsset(pbEntryIds).keySet().isEmpty(), 'no asset against the pricebook retrieved');
               Test.stopTest();
          }
     }

     @isTest
     private static void createProductLedgerRecordsTest(){
          System.runAs(TestDataFactoryUser.selectUserQUTeXProgramAdministrator){
               
               hed__Course_Offering__c courseOffering = [
                    SELECT Id 
                    FROM hed__Course_Offering__c
                    LIMIT 1
               ];

               List<hed__Course_Enrollment__c> courseConList = new List<hed__Course_Enrollment__c>();
               hed__Course_Enrollment__c courseCon = new hed__Course_Enrollment__c(
                    Amount__c = 123,
                    hed__Course_Offering__c = courseOffering.Id
               );

               insert courseCon;

               courseConList.add(courseCon);

               Test.startTest();
               CorporateBundleAndSOAHelper.createProductLedgerRecords([SELECT Id FROM Asset LIMIT 1].Id,courseConList);
               System.assert(![SELECT Id FROM Product_Ledger__c LIMIT 1].isEmpty(), 'no ledger created against the course connection');
               Test.stopTest();
          }
          
     }

     @isTest
     private static void createAffiliationRecordsWithoutCartTest(){
          System.runAs(TestDataFactoryUser.selectUserQUTeXProgramAdministrator){

               hed__Course_Offering__c courseOffering = [
                    SELECT Id 
                    FROM hed__Course_Offering__c
                    LIMIT 1
               ];

               List<hed__Course_Enrollment__c> courseConList = new List<hed__Course_Enrollment__c>();
               hed__Course_Enrollment__c courseCon = new hed__Course_Enrollment__c(
                    Amount__c = 123,
                    hed__Course_Offering__c = courseOffering.Id
               );

               insert courseCon;

               courseConList.add(courseCon);

               Test.startTest();
               CorporateBundleAndSOAHelper.createAffiliationRecords(courseConList);
               System.assert(![SELECT Id FROM hed__Affiliation__c LIMIT 1].isEmpty(), 'no affiliation created');
               Test.stopTest();
          }
     }

}