src/core-crm/objects/Account/fields/Organization_Unit_Level__c.field-meta.xml
<CustomField>
    <fullName>Organization_Unit_Level__c</fullName>
    <description>The level (1,2,3) of the organizational unit within the QUT Organizational hierarchy.</description>
    <label>Organization Unit Level</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Communication_Schedule__c/Communication_Schedule__c.object-meta.xml
<CustomObject>
    <label>Communication Schedule</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Communication Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Communication_Schedule__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to related Course record.</description>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Communication Schedules</relationshipLabel>
    <relationshipName>Communication_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Communication_Schedule__c/fields/Email_on_final_confirmation__c.field-meta.xml
<CustomField>
    <fullName>Email_on_final_confirmation__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Upon selection of the email template for use, the learner will receive an email prior to the start of the product. Set the number of days prior that the email should be sent to the registered learner.</inlineHelpText>
    <label>Send Email on final confirmation</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Communication_Schedule__c/fields/Email_on_Registration__c.field-meta.xml
<CustomField>
    <fullName>Email_on_Registration__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>The email will be automatically sent to the learner upon their registration into the product.</inlineHelpText>
    <label>Send Email on Registration</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Communication_Schedule__c/fields/Send_email_before_session__c.field-meta.xml
<CustomField>
    <fullName>Send_email_before_session__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Email Notification before Session</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/hed__Course__c/hed__Course__c.object-meta.xml
<CustomObject>
    <description>Academic Course offered by a Department or School, for example, English 101 or Ancient History.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course__c/fields/Delivery_Type__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Type__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Face to Face</fullName>
            </value>
            <value>
                <fullName>Virtual Classroom</fullName>
            </value>
            <value>
                <fullName>Blended</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Course__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>hed__Facility__c.Name</field>
            <operation>contains</operation>
            <value>&apos;QUT Kelvin Grove&apos;, &apos;QUT Gardens Point&apos;, &apos;QUT Canberra&apos;, &apos;QUT Sydney&apos;, &apos;QUT Melbourne&apos;, &apos;Web Conference&apos;, &apos;Externals&apos;, &apos;QUT Cairns&apos;, &apos;QUT NSW Classroom&apos;</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>hed__Facility__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/hed__Course_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Represents a connection to a Course Offering.</description>
    <label>Course Connection</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Course Connection ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Enrollment__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The course that the student is enrolment is related to</description>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Course Connections</relationshipLabel>
    <relationshipName>Course_Connections</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/hed__Course_Offering__c.field-meta.xml
<CustomField>
    <fullName>hed__Course_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Course Offering the student or faculty member is involved with.</description>
    <inlineHelpText>The Course Offering the student or faculty member is involved with.</inlineHelpText>
    <label>Course Offering ID</label>
    <referenceTo>hed__Course_Offering__c</referenceTo>
    <relationshipLabel>Course Connection</relationshipLabel>
    <relationshipName>Course_Enrollment</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/recordTypes/Student.recordType-meta.xml
<RecordType>
    <fullName>Student</fullName>
    <active>true</active>
    <description>A Student Course Connection</description>
    <label>Student</label>
</RecordType>

src/core-crm/objects/hed__Course_Offering__c/hed__Course_Offering__c.object-meta.xml
<CustomObject>
    <description>Joins Courses and Terms to contain information related to a single occurrence of a Course.</description>
    <label>Course Offering</label>
    <nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Offering__c/fields/Delivery_Type__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Type__c</fullName>
    <description>This will be how the course will be delivered and location for face-to-face.</description>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online Classroom</fullName>
            </value>
            <value>
                <fullName>Online Self-paced</fullName>
            </value>
            <value>
                <fullName>Brisbane Classroom</fullName>
            </value>
            <value>
                <fullName>Canberra Classroom</fullName>
            </value>
            <value>
                <fullName>Melbourne Classroom</fullName>
            </value>
            <value>
                <fullName>Sydney Classroom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Course__c.field-meta.xml
<CustomField>
    <fullName>hed__Course__c</fullName>
    <description>Lookup to the Course record that this Course Offering is associated with.</description>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>
 

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Facility__c.field-meta.xml
<CustomField>
    <fullName>hed__Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Facility associated with the Course Offering.</description>
    <inlineHelpText>The Facility where this Course Offering will take place.</inlineHelpText>
    <label>Facility</label>
    <referenceTo>hed__Facility__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Term__c.field-meta.xml
<CustomField>
    <fullName>hed__Term__c</fullName>
    <description>Lookup to the Term record that represents when this Course Offering takes place.</description>
    <label>Term</label>
    <referenceTo>hed__Term__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>
 

src/core-crm/objects/hed__Program_Plan__c/hed__Program_Plan__c.object-meta.xml
<CustomObject>
    <description>Links Courses to an Academic Program to create a path for students to follow. An Academic Program can list multiple Courses, and a Course can be associated with multiple Academic Programs.</description>
    <label>Program Plan</label>
    <nameField>
        <label>Program Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Program_Plan__c/fields/Delivery_Type__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Type__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Face To Face</fullName>
            </value>
            <value>
                <fullName>Virtual Classroom</fullName>
            </value>
            <value>
                <fullName>Blended</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Program_Plan__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>hed__Facility__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Program_Plan__c/fields/Product_Request__c.field-meta.xml
<CustomField>
    <fullName>Product_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the related Product Request record of the Program Plan.</description>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Term__c/hed__Term__c.object-meta.xml
<CustomObject>
    <description>Unit of time in which academic activities are taking place.</description>
    <label>Term</label>
    <nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Term__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Location the Term(Period) applies to</description>
    <label>Location</label>
    <referenceTo>Location</referenceTo>
    <relationshipLabel>Terms</relationshipLabel>
    <relationshipName>Terms</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Related_Product_Request__c/Related_Product_Request__c.object-meta.xml
<CustomObject>
    <label>Related Product Request</label>
    <nameField>
        <label>Related Product Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Related Product Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Related_Product_Request__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Related Product Requests</relationshipLabel>
    <relationshipName>Course</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <displayFormat>CL-{0000000}</displayFormat>
        <label>Session ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Session__c/fields/Course_Offering__c.field-meta.xml
<CustomField>
    <fullName>Course_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Course Offering this Session relates to</description>
    <label>Course Offering</label>
    <referenceTo>hed__Course_Offering__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Session__c/fields/End_Time_v2__c.field-meta.xml
<CustomField>
    <fullName>End_Time_v2__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

src/core-crm/objects/Session__c/fields/Facilitator__c.field-meta.xml
<CustomField>
    <fullName>Facilitator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facilitator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Session__c/fields/Start_Time_v2__c.field-meta.xml
<CustomField>
    <fullName>Start_Time_v2__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

src/core-crm/classes/EmailTriggerPreSessionBatchTest.cls
@isTest
public with sharing class EmailTriggerPreSessionBatchTest {
    private static final Id STUDENT_RECTYPEID = Schema.SObjectType.hed__Course_Enrollment__c.getRecordTypeInfosByDeveloperName()
    .get('Student')
    .getRecordTypeId();
    private static final String ACCT_UNIV_DEP = System.Label.RT_Account_University_Department;
    private static final Id ACCT_UNIV_DEP_ID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(ACCT_UNIV_DEP).getRecordTypeId();

    private static User currentUser = TestDataFactory.createUserRecords(
        1,
        'QUTeX'
    )
    .iterator()
    .next();

	@isTest
    public static void testEmailTriggerPreSessionBatch() {
        System.runAs(currentUser) {
            List<Account> accounts = TestDataFactory.createTestAccountRecords(1);
            for(Account acc : accounts){
              acc.RecordTypeId = ACCT_UNIV_DEP_ID;
              acc.Organization_Unit_Level__c = '2';
            }
            insert accounts;
      
            List<Contact> contacts = TestDataFactory.createTestContactRecords(1);
            contacts[0].email = 'testContact@testmail.com';
            insert contacts;
      
            List<hed__Term__c> terms = TestDataFactory.createTestTermRecords(
              10,
              accounts[0].Id
            );
            insert terms;
      
            List<Product_Request__c> prodRequest = TestDataFactory.createTestProductRequestRecords(
              1
            );
            insert prodRequest;
      
            List<hed__Course__c> courses = TestDataFactory.createTestCourseRecords(
              10,
              accounts[0].Id,
              prodRequest[0].Id
            );
            insert courses;
      
            List<hed__Course_Offering__c> courseOfferings = TestDataFactory.createTestCourseOfferingRecord(
              10,
              courses,
              terms
            );
            for(hed__Course_Offering__c course: courseOfferings){
                
                course.Delivery_Type__c = 'Face-to-Face';
            }
           
            insert courseOfferings;
      
            List<hed__Program_Plan__c> programPlans = TestDataFactory.createTestProgramPlanRecords(
              10
            );
          
            insert programPlans;
      
            List<Communication_Schedule__c> commSchedules = TestDataFactory.createTestCommunicationScheduleRecords(
              10,
              courses,
              programPlans
            );
      
            for (Communication_Schedule__c commSchedule : commSchedules) {
             // commSchedule.Course__c = courseOfferings[0].hed__Course__r.Id;
              commSchedule.Email_on_Registration__c = true;
              commSchedule.Email_on_final_confirmation__c = true;
              commSchedule.Send_email_before_session__c = true;
            }
            insert commSchedules;
          
           hed__Facility__c facility = new hed__Facility__c();
           facility.Name = 'Facility 1';
           insert facility;
            
           List<Session__c> session = TestDataFactory.createTestSessionRecords(1);
           session[0].Course_Offering__c = courseOfferings[0].Id;
           session[0].End_Time_v2__c = Time.newInstance(11, 0, 0, 0);
           session[0].Start_Time_v2__c = Time.newInstance(10, 0, 0, 0);
           session[0].Facilitator__c = contacts[0].Id;
           session[0].Location__c = facility.Id;
           session[0].Date__c = Date.today() + 1;
            
           insert session;

            Test.startTest();
            List<hed__Course_Enrollment__c> courseConnections = TestDataFactory.createTestCourseConnectionRecord(
              10,
              contacts[0].Id,
              courseOfferings
            );
      
            for (hed__Course_Enrollment__c courseConnection : courseConnections) {
              courseConnection.RecordTypeId = STUDENT_RECTYPEID;
              courseConnection.Amount__c = 100;
              courseConnection.Paid_in_Full__c = '';
            }
            insert courseConnections;

            EmailTriggerPreSessionBatch emailBatch = new EmailTriggerPreSessionBatch();
            Database.executebatch(emailBatch);
            System.assert(![SELECT Id FROM AsyncApexJob WHERE ApexClass.Name = 'EmailTriggerPreSessionBatch'].isEmpty() , 'EmailTriggerPreSessionBatch Job was not executed');

        }
    }
}