src/core-crm/objects/Account/fields/Organization_Unit_Level__c.field-meta.xml
<CustomField>
    <fullName>Organization_Unit_Level__c</fullName>
    <description>The level (1,2,3) of the organizational unit within the QUT Organizational hierarchy.</description>
    <label>Organization Unit Level</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Communication_Schedule__c/Communication_Schedule__c.object-meta.xml
<CustomObject>
    <label>Communication Schedule</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Communication Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Communication_Schedule__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to related Course record.</description>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Communication Schedules</relationshipLabel>
    <relationshipName>Communication_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course__c/hed__Course__c.object-meta.xml
<CustomObject>
    <description>Academic Course offered by a Department or School, for example, English 101 or Ancient History.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course__c/fields/Delivery_Type__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Type__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Face to Face</fullName>
            </value>
            <value>
                <fullName>Virtual Classroom</fullName>
            </value>
            <value>
                <fullName>Blended</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Program_Plan__c/hed__Program_Plan__c.object-meta.xml
<CustomObject>
    <description>Links Courses to an Academic Program to create a path for students to follow. An Academic Program can list multiple Courses, and a Course can be associated with multiple Academic Programs.</description>
    <label>Program Plan</label>
    <nameField>
        <label>Program Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Program_Plan__c/fields/Delivery_Type__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Type__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Face To Face</fullName>
            </value>
            <value>
                <fullName>Virtual Classroom</fullName>
            </value>
            <value>
                <fullName>Blended</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/hed__Program_Plan__c/fields/Product_Request__c.field-meta.xml
<CustomField>
    <fullName>Product_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the related Product Request record of the Program Plan.</description>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Program_Plan__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <description>This record type will be used to create a Program. This can be a combination of a Unit, a Module, a Short Course, or an Activity.</description>
    <label>Program</label>
</RecordType>

src/core-crm/objects/Product_Request__c/Product_Request__c.object-meta.xml
<CustomObject>
    <label>Product Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Product Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Product_Request__c/fields/Product_Request_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Request_Name__c</fullName>
    <label>Product Request Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Product_Request__c/recordTypes/Program.recordType-meta.xml
<RecordType>
    <fullName>Program</fullName>
    <active>true</active>
    <description>This record type will be used to create a Program. This can be a combination of a Unit, a Module, a Short Course, or an Activity.</description>
    <label>Program</label>
</RecordType>

src/core-crm/classes/EmailTemplateCtrlTest.cls
@isTest
public with sharing class EmailTemplateCtrlTest {
    private static final String PR_PROGRAM = System.Label.RT_ProductRequest_Program;
    private static final String PR_MODULE = System.Label.RT_ProductRequest_MODULE;
    private static User currentUser = TestDataFactory.createUserRecords(1,'QUTeX').iterator().next();
    private static Id opeProgProdReqId = Schema.SObjectType.Product_Request__c.getRecordTypeInfosByDeveloperName().get(PR_PROGRAM).getRecordTypeId();
    private static Id opeModuleReqId = Schema.SObjectType.Product_Request__c.getRecordTypeInfosByDeveloperName().get(PR_MODULE).getRecordTypeId();
    private static final String ACCT_UNIV_DEP = System.Label.RT_Account_University_Department;
    private static final Id ACCT_UNIV_DEP_ID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(ACCT_UNIV_DEP).getRecordTypeId();

    @testSetup static void setupMethod() {
        TestDataFactoryUser.generateUserQUTeXProgramAdministrator();
        List<Account> accounts;
        accounts = TestDataFactory.createTestAccountRecords(1);
        for(Account acc : accounts){
            acc.RecordTypeId = ACCT_UNIV_DEP_ID;
            acc.Organization_Unit_Level__c = '2';
        }
        insert accounts;

        List<Product_Request__c> prodRequestOPEProgramRequest;
        prodRequestOPEProgramRequest = TestDataFactory.createTestProductRequestRecords(1);
        prodRequestOPEProgramRequest[0].Product_Request_Name__c = 'Program Request';
        prodRequestOPEProgramRequest[0].RecordTypeId = opeProgProdReqId;
        insert prodRequestOPEProgramRequest;

        List<hed__Program_Plan__c> programPlanList;
        programPlanList = TestDataFactory.createTestProgramPlanRecords(1);
        programPlanList[0].Product_Request__c = prodRequestOPEProgramRequest[0].Id;
        insert programPlanList;

        List<Product_Request__c> prodRequest;
        prodRequest = TestDataFactory.createTestProductRequestRecords(1);
        prodRequest[0].RecordTypeId = opeModuleReqId;
        insert prodRequest;

        List<hed__Course__c> courses;
        courses = TestDataFactory.createTestCourseRecords(1,accounts[0].Id,prodRequest[0].Id);
        for(hed__Course__c c : courses){
            c.Delivery_Type__c = 'Face to Face';
        }
        insert courses;

        Communication_Schedule__c communicationSchedule = new Communication_Schedule__c(Course__c = courses[0].Id);
        insert communicationSchedule;


     }

    @isTest
    static void getEmailTemplateTest(){
        System.runAs(TestDataFactoryUser.selectUserQUTeXProgramAdministrator) {
            EmailTemplate e = new EmailTemplate (developerName = 'testEmail', TemplateType= 'Text', Name = 'testEmail');
            e.FolderId = UserInfo.getUserId();
            insert e;
            Test.startTest();
                List<Map<String,String>> emailTemplate = EmailTemplateCtrl.getEmailTemplate('testEmail');
                System.assertEquals('testEmail', emailTemplate[0].get('label'),'Email Name did not match as expected');
            Test.stopTest();
        }
    }

    @isTest
    static void getCommunicationDataModuleTest(){
        Id programId;
		Id moduleId;
        EmailTemplate e = new EmailTemplate (developerName = 'testEmail', TemplateType= 'Text', Name = 'testEmail');
        e.FolderId = UserInfo.getUserId();
        insert e;

        List<EmailTemplate> email = new List<EmailTemplate>();
        email = [SELECT Id, Name FROM EmailTemplate LIMIT 10];
        List<String> emailNames = new List <String>();
        for (EmailTemplate em : email){
            emailNames.add(em.Name);
        }

        List<Product_Request__c> programPR  = new List<Product_Request__c>();
        programPR =[SELECT Id FROM Product_Request__c WHERE RecordTypeId =:opeProgProdReqId];
        for(Product_Request__c pr : programPR){
            programId = pr.Id;
        }

        List<Product_Request__c> opePR  = new List<Product_Request__c>();
        opePR =[SELECT Id FROM Product_Request__c WHERE RecordTypeId =:opeModuleReqId];
        for(Product_Request__c pr : opePR){
            moduleId = pr.Id;
        }

        Test.startTest();
        System.runAs(currentUser){
            EmailTemplateCtrl.CommunicationSchedData getComSchedData = new EmailTemplateCtrl.CommunicationSchedData();
            getComSchedData = EmailTemplateCtrl.getCommunicationData(emailNames, String.valueOf(moduleId), String.valueOf(programId));
            System.Assert(!getComSchedData.defaultEmail.isEmpty(),'Error while getting default email');
            System.AssertEquals(getComSchedData.deliveryType, 'Face to Face','Error while getting delivery type');

        }
        Test.stopTest();

    }

    @isTest
    static void getCommunicationDataProgramTest(){
        Id programId;
		Id moduleId;
        EmailTemplate e = new EmailTemplate (developerName = 'testEmail', TemplateType= 'Text', Name = 'testEmail');
        e.FolderId = UserInfo.getUserId();
        insert e;

        List<EmailTemplate> email = new List<EmailTemplate>();
        email = [SELECT Id, Name FROM EmailTemplate LIMIT 10];
        List<String> emailNames = new List <String>();
        for (EmailTemplate em : email){
            emailNames.add(em.Name);
        }

        List<Product_Request__c> programPR  = new List<Product_Request__c>();
        programPR =[SELECT Id FROM Product_Request__c WHERE RecordTypeId =:opeProgProdReqId];
        for(Product_Request__c pr : programPR){
            programId = pr.Id;
        }

        List<Product_Request__c> opePR  = new List<Product_Request__c>();
        opePR =[SELECT Id FROM Product_Request__c WHERE RecordTypeId =:opeModuleReqId];
        for(Product_Request__c pr : opePR){
            moduleId = pr.Id;
        }

        Test.startTest();
        System.runAs(currentUser){
            EmailTemplateCtrl.CommunicationSchedData getComSchedData = new EmailTemplateCtrl.CommunicationSchedData();
            getComSchedData = EmailTemplateCtrl.getCommunicationData(emailNames, String.valueOf(programId), 'Program');
            System.Assert(!getComSchedData.defaultEmail.isEmpty(),'Error while getting default email');
            //System.AssertEquals(getComSchedData.deliveryType, 'Face to Face','Error while getting delivery type');

        }
        Test.stopTest();

    }
}