src/core-crm/objects/Account/fields/Organization_Unit_Level__c.field-meta.xml
<CustomField>
    <fullName>Organization_Unit_Level__c</fullName>
    <description>The level (1,2,3) of the organizational unit within the QUT Organizational hierarchy.</description>
    <label>Organization Unit Level</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Course__c/hed__Course__c.object-meta.xml
<CustomObject>
    <description>Academic Course offered by a Department or School, for example, English 101 or Ancient History.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Program_Plan__c/hed__Program_Plan__c.object-meta.xml
<CustomObject>
    <description>Links Courses to an Academic Program to create a path for students to follow. An Academic Program can list multiple Courses, and a Course can be associated with multiple Academic Programs.</description>
    <label>Program Plan</label>
    <nameField>
        <label>Program Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Program_Plan__c/fields/Product_Request__c.field-meta.xml
<CustomField>
    <fullName>Product_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the related Product Request record of the Program Plan.</description>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Product2/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Product2/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <label>Product Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/core-crm/objects/Product_Request__c/Product_Request__c.object-meta.xml
<CustomObject>
    <label>Product Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Product Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Product_Request__c/fields/Product_Specification__c.field-meta.xml
<CustomField>
    <fullName>Product_Specification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Specification</label>
    <referenceTo>Product_Specification__c</referenceTo>
    <relationshipLabel>Product Requests</relationshipLabel>
    <relationshipName>Product_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Product_Specification__c/Product_Specification__c.object-meta.xml
<CustomObject>
    <label>Product Specification</label>
    <nameField>
        <displayFormat>PS-{00000}</displayFormat>
        <label>Product Specification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Specifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/classes/UpdateProductCodeFlowTest.cls
/**
 * @description Test Class for Update Product Code Flow
 *
 * @see ../flows/Update_Product_Code_Flow
 *
 * @author Accenture
 *
 * @history
 *    | Developer                 | Date                  | JIRA         | Change Summary                              |
      |---------------------------|-----------------------|--------------|---------------------------------------------|
      | arsenio.jr.dayrit         | April 07, 2022        | DEPP-2057    | Created file                                |
      |                           |                       |              |                                             |
      |                           |                       |              |                                             |
*/
@isTest
private class UpdateProductCodeFlowTest{
    private static Integer numberOfRecords = 10;
    private static final String ACCT_UNIV_DEP = System.Label.RT_Account_University_Department;
    private static final Id ACCT_UNIV_DEP_ID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(ACCT_UNIV_DEP).getRecordTypeId();

    @TestSetup
    static void makeData(){
        TestDataFactoryUser.generateUserQUTeXProgramAdministrator();
    }

    @isTest
    private static void updateProductCodeTest(){
        System.runAs(TestDataFactoryUser.selectUserQUTeXProgramAdministrator){

            List<Account> accounts;
            accounts = TestDataFactory.createTestAccountRecords(1);
            for(Account acc : accounts){
                acc.RecordTypeId = ACCT_UNIV_DEP_ID;
                acc.Organization_Unit_Level__c = '2';
            }
            insert accounts;

            List<Contact> contacts;
            contacts = TestDataFactory.createTestContactRecords(1);
            insert contacts;

            List<Opportunity> opps;
            opps = TestDataFactory.createClosedWonOpportunities(1,accounts[0].Id,contacts[0].Id);
            insert opps;

            List<Product_Specification__c> productSpecs = TestDataFactory.retrieveCCEProductSpecifications();

            List<Product_Request__c> prodRequestOPEProgramRequest;
            prodRequestOPEProgramRequest = TestDataFactory.createTestProductRequestRecords(1,productSpecs[0].Id);
            insert prodRequestOPEProgramRequest;

            List<hed__Program_Plan__c> programPlanList;
            programPlanList = TestDataFactory.createTestProgramPlanRecords(1);
            insert programPlanList;

            List<Product_Request__c> prodRequest;
            prodRequest = TestDataFactory.createTestProductRequestRecords(1,productSpecs[0].Id);
            insert prodRequest;


            List<hed__Course__c> courses;
            courses = TestDataFactory.createTestCourseRecords(numberOfRecords,accounts[0].Id,prodRequest[0].Id);
            insert courses;


           List<Product2> products = TestDataFactory.createTestProductRecords(numberOfRecords, courses);
           for(Integer i = 0 ; i > products.size() ; i++){
                products[i].Course__c = courses[i].id;
                products[i].ProductCode = 'Test'+i;
           }

           Test.startTest();
           insert products;
           Test.stopTest();

           List<Product2> prodRec = [SELECT Id, Name, Product_Code__c, ProductCode FROM Product2 LIMIT 100];
           for(Product2 checkProd : prodRec){
           System.assertEquals(checkProd.Product_Code__c, checkProd.ProductCode, 'custom product code must be the same with standard product code');
           }


        }
    }
}