src/core-crm/objects/Account/fields/Organization_Unit_Level__c.field-meta.xml
<CustomField>
    <fullName>Organization_Unit_Level__c</fullName>
    <description>The level (1,2,3) of the organizational unit within the QUT Organizational hierarchy.</description>
    <label>Organization Unit Level</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Opportunity/fields/Client_Budget__c.field-meta.xml
<CustomField>
    <fullName>Client_Budget__c</fullName>
    <label>Client Budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

src/core-crm/objects/Opportunity/fields/Existing_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Existing_Relationship__c</fullName>
    <inlineHelpText>Are there existing relationships within the organisation</inlineHelpText>
    <label>Existing Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Opportunity/fields/Faculty_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Faculty_Capacity__c</fullName>
    <inlineHelpText>Do we have Faculty capacity?</inlineHelpText>
    <label>Faculty Capacity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Opportunity/fields/Lead_School__c.field-meta.xml
<CustomField>
    <fullName>Lead_School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead School</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>OpportunitiesLead</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Opportunity/fields/Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Name__c</fullName>
    <label>Program Name</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Opportunity/fields/QUTeX_Capacity__c.field-meta.xml
<CustomField>
    <fullName>QUTeX_Capacity__c</fullName>
    <inlineHelpText>Do we have QUTeX capacity?</inlineHelpText>
    <label>QUTeX Capacity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Opportunity/fields/Self_Evaluation__c.field-meta.xml
<CustomField>
    <fullName>Self_Evaluation__c</fullName>
    <inlineHelpText>If applicable, self-evaluation against criteria is strong?</inlineHelpText>
    <label>Self Evaluation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Client Approved</fullName>
            </value>
            <value>
                <fullName>Contract Created</fullName>
            </value>
            <value>
                <fullName>Contract Signed</fullName>
            </value>
            <value>
                <fullName>Drafter Review</fullName>
            </value>
            <value>
                <fullName>Drafting</fullName>
            </value>
            <value>
                <fullName>Drafting Complete</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Pending Contract Creation</fullName>
            </value>
            <value>
                <fullName>Pending Initial Proposal Approval</fullName>
            </value>
            <value>
                <fullName>Pending QUTeX Executive Approval</fullName>
            </value>
            <value>
                <fullName>QUTeX Executive Approved</fullName>
            </value>
            <value>
                <fullName>Under Client Review</fullName>
            </value>
            <value>
                <fullName>QUTeX Executive Proposal Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/classes/OpportunityContactRoleTriggerHandlerTest.cls
/**
 * @description Test Class for OpportunityContactRoleTriggerHandler
 *
 * @see OpportunityContactRoleTriggerHandler
 *
 * @author Accenture
 *
 * @history
 *    | Developer                 | Date                  | JIRA         | Change Summary                              |
      |---------------------------|-----------------------|--------------|---------------------------------------------|
      | mark.j.mahilum            | Aug 24, 2023          | DEPP-6367    | Created file                                |
*/
@isTest
private class OpportunityContactRoleTriggerHandlerTest {
    
    @testSetup static void setupMethod() {
        TestDataFactory.generateTestUsers(new List<String>{'QUT_Program_Administrator'});
        System.runAs(TestDataFactory.getProgramAdminUser()) {

            Account acc = TestDataFactory.createTestAccountRecords(1).iterator().next();
            acc.Organization_Unit_Level__c = '3';
            insert acc;

            Contact con = TestDataFactory.createTestContactRecords(1).iterator().next();
            insert con;

            Contact conProgramLead = TestDataFactory.createTestContactRecords(1).iterator().next();
            conProgramLead.FirstName = 'Program Lead';
            insert conProgramLead;

            Contact conClientDecisionMaker = TestDataFactory.createTestContactRecords(1).iterator().next();
            conClientDecisionMaker.FirstName = 'Client Decision Maker';
            insert conClientDecisionMaker;

            List<Opportunity> oppList = TestDataFactory.createTestOpportunityRecords(50,acc?.Id,con?.Id);
            
            for(Integer i=0;i<oppList.size();i++){
                oppList[i].Lead_School__c = acc?.Id;
                oppList[i].Program_Name__c = 'Test Program Name' + i;
                oppList[i].Description = 'Test Description' + i;
                oppList[i].Amount = 123;
                oppList[i].Client_Budget__c = 123;
                oppList[i].Self_Evaluation__c = 'Yes';
                oppList[i].QUTeX_Capacity__c = 'Yes';
                oppList[i].Faculty_Capacity__c = 'Yes';
                oppList[i].Existing_Relationship__c = 'Yes';
            }
            Test.startTest();
            insert(oppList);

            List<OpportunityContactRole> programLeadRole = TestDataFactory.createTestOpportunityContactRolesRecords(conProgramLead?.Id,oppList);
            for(OpportunityContactRole role: programLeadRole){
                role.Role = 'Program Lead';
                role.IsPrimary = false;
            }
            insert(programLeadRole);

            List<OpportunityContactRole> clientDecisionMakerRole = TestDataFactory.createTestOpportunityContactRolesRecords(conClientDecisionMaker?.Id,oppList);
            for(OpportunityContactRole role: clientDecisionMakerRole){
                role.Role = 'Client Decision-Maker';
                role.IsPrimary = true;
            }
            insert(clientDecisionMakerRole);

            for(Integer i=0;i<oppList.size();i++){
                oppList[i].StageName = 'Proposal';
                oppList[i].Status__c = 'Drafting';
            }

            update(oppList);
            Test.stopTest();
        }
    }  
    
    @isTest
    private static void testOpportunityContactRoleWithContact() {
        System.runAs(TestDataFactory.getProgramAdminUser()) {

            Test.startTest();
            List<OpportunityContactRole> clientDecisionMakerRole = [SELECT Id FROM OpportunityContactRole WHERE Role = 'Program Lead' limit 1];
            clientDecisionMakerRole[0].Role = 'Client Decision-Maker';
            
            Database.SaveResult[] srList = Database.update(clientDecisionMakerRole);
            Test.stopTest();
            
            for (Database.SaveResult sr : srList) {
                System.assert(sr.isSuccess(), 'A record was not updated.');
            }
        }
    }
    
    @isTest
    private static void testOpportunityContactRoleChangeRoleContact() {
        System.runAs(TestDataFactory.getProgramAdminUser()) {

            Test.startTest();
            List<OpportunityContactRole> clientDecisionMakerRole = [SELECT Id FROM OpportunityContactRole WHERE Role = 'Client Decision-Maker' limit 1];
            clientDecisionMakerRole[0].Role = 'Program Lead';
            
            Database.SaveResult[] srList = Database.update(clientDecisionMakerRole);
            Test.stopTest();
            
            for (Database.SaveResult sr : srList) {
                System.assert(sr.isSuccess(), 'A record was not updated.');
            }
        }
    }  
}