src/core-crm/objects/Account/fields/Program_Code__c.field-meta.xml
<CustomField>
    <fullName>Program_Code__c</fullName>
    <description>The 4 Character code assigned to a Course populated by Integration form SAMS (Originating from Courseloop)

Study link may contain composit course codes for pathway packages.</description>
    <label>Program Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>The type of Case being tracked.</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Student_LifeCycle_Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acceptance process</fullName>
            </value>
            <value>
                <fullName>Agent matters</fullName>
            </value>
            <value>
                <fullName>Application process</fullName>
            </value>
            <value>
                <fullName>Application status</fullName>
            </value>
            <value>
                <fullName>Change application</fullName>
            </value>
            <value>
                <fullName>Compliance documentation</fullName>
            </value>
            <value>
                <fullName>Course information</fullName>
            </value>
            <value>
                <fullName>Enrolment</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>Orientation and onboarding</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Progression</fullName>
            </value>
            <value>
                <fullName>Scholarships</fullName>
            </value>
            <value>
                <fullName>Student life</fullName>
            </value>
            <value>
                <fullName>Technical issues</fullName>
            </value>
            <value>
                <fullName>Why QUT</fullName>
            </value>
            <value>
                <fullName>School Code of Conduct</fullName>
                <isActive>false</isActive>
                <label>School Code of Conduct</label>
            </value>
            <value>
                <fullName>School Violation</fullName>
                <isActive>false</isActive>
                <label>School Violation</label>
            </value>
            <value>
                <fullName>State Offense</fullName>
                <isActive>false</isActive>
                <label>State Offense</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Case/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Lead.</description>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Case/fields/My_Country_of_Residency__c.field-meta.xml
<CustomField>
    <fullName>My_Country_of_Residency__c</fullName>
    <description>The country the enquirer currently resides in</description>
    <label>My Country of Residency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

src/core-crm/objects/Contact/fields/Email_Opt_In_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Email_Opt_In_DateTime__c</fullName>
    <description>The date/time the marketing person opted in to receive marketing comms via Email.</description>
    <label>Email Opt In DateTime</label>
    <type>DateTime</type>
</CustomField>

src/core-crm/objects/Contact/fields/Lead_Score_Detail__c.field-meta.xml
<CustomField>
    <fullName>Lead_Score_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The breakdown of lead scoring by category aggregates.</description>
    <label>Lead Score Detail</label>
    <referenceTo>Lead_Score_Detail__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Contact/fields/Marketing_Segmentation__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Segmentation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Preferences</label>
    <referenceTo>Marketing_Segmentation__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Lead/fields/Lead_Score_Detail__c.field-meta.xml
<CustomField>
    <fullName>Lead_Score_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The breakdown of lead scoring by category aggregates.</description>
    <label>Lead Score Detail</label>
    <referenceTo>Lead_Score_Detail__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Lead/fields/Marketing_Segmentation__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Segmentation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Segmentation</label>
    <referenceTo>Marketing_Segmentation__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Lead_Score_Configuration__c/Lead_Score_Configuration__c.object-meta.xml
<CustomObject>
    <label>Lead Score Configuration</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Score Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Lead_Score_Configuration__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>The description of the record and it’s usage in scoring</description>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

src/core-crm/objects/Lead_Score_Configuration__c/fields/Domestic_International__c.field-meta.xml
<CustomField>
    <fullName>Domestic_International__c</fullName>
    <description>Whether the configuration is related to Domestic or International scoring scheme</description>
    <label>Domestic or International</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Lead_Score_Configuration__c/fields/Max_Score__c.field-meta.xml
<CustomField>
    <fullName>Max_Score__c</fullName>
    <description>The max score a category is allowed to accumulate</description>
    <label>Max Score</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Lead_Score_Configuration__c/fields/Score_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Score_Allocation__c</fullName>
    <description>Score that should be allocated for each instance of the interaction</description>
    <label>Score Allocation</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Lead_Score_Configuration__c/fields/Study_Level__c.field-meta.xml
<CustomField>
    <fullName>Study_Level__c</fullName>
    <description>The level of education is used to determine the sub scheme the scoring configuration belongs.</description>
    <label>Study Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Undergraduate</fullName>
            </value>
            <value>
                <fullName>Postgraduate</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Lead_Score_Configuration__c/fields/Time_Limit_Months__c.field-meta.xml
<CustomField>
    <fullName>Time_Limit_Months__c</fullName>
    <description>The number months the calculation needs to consider activities for from current month</description>
    <label>Time Limit (Months)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Lead_Score_Detail__c/Lead_Score_Detail__c.object-meta.xml
<CustomObject>
    <label>Lead Score Detail</label>
    <nameField>
        <displayFormat>LSD-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Score Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Lead_Score_Detail__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to name of the contact the score belongs to.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Lead Score Details</relationshipLabel>
    <relationshipName>Lead_Score_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Lead_Score_Detail__c/fields/Domestic_International__c.field-meta.xml
<CustomField>
    <fullName>Domestic_International__c</fullName>
    <description>Whether the scoring is based on Domestic or international configuration scheme</description>
    <label>Domestic or International</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Lead_Score_Detail__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to name of the lead the score belongs to.</description>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Lead Score Details</relationshipLabel>
    <relationshipName>Lead_Score_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Marketing_Interaction__c/Marketing_Interaction__c.object-meta.xml
<CustomObject>
    <label>Marketing Interaction</label>
    <nameField>
        <displayFormat>MI - {000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Marketing_Interaction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Marketing Interactions</relationshipLabel>
    <relationshipName>Marketing_Interactions</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Marketing_Interaction__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Marketing Interactions</relationshipLabel>
    <relationshipName>Marketing_Interactions</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Marketing_Interaction__c/fields/Marketing_Segmentation__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Segmentation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Segmentation</label>
    <referenceTo>Marketing_Segmentation__c</referenceTo>
    <relationshipLabel>Marketing Interactions</relationshipLabel>
    <relationshipName>Marketing_Interactions</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Marketing_Segmentation__c/Marketing_Segmentation__c.object-meta.xml
<CustomObject>
    <label>Marketing Segmentation</label>
    <nameField>
        <displayFormat>MS - {000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Segmentations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Marketing_Segmentation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Marketing Segmentations</relationshipLabel>
    <relationshipName>Marketing_Segmentations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Marketing_Segmentation__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Marketing Segmentations</relationshipLabel>
    <relationshipName>Marketing_Segmentations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Marketing_Segmentation__c/fields/My_Country_Of_Residency__c.field-meta.xml
<CustomField>
    <fullName>My_Country_Of_Residency__c</fullName>
    <description>Profile Type = Myself

Indicates the country an international student is living in.</description>
    <label>My Country Of Residency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

src/core-crm/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Åland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas (the)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia (Plurinational State of)</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

src/core-crm/classes/LeadScoreUndergradIntCmdTest.cls
/**
 * @description Test class for LeadScoreUndergradIntCmd
 * 
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | roy.nino.s.regala              | October 06, 2023      | DEPP-5866              | Created file                 |
      |                                |                       |                        |                              |
 */
@isTest
private class LeadScoreUndergradIntCmdTest {
    @isTest
    private static void processStudyLevelForCaseTest() {//NOPMD test class is mocked user is not needed

        ImplementationSelector.DAO.setMock(new LeadScoreConfigurationDAOMock());
        ImplementationSelector.DAO.setMock(new CasesDAOMock());
        ImplementationSelector.DAO.setMock(new ContactsDAOMock());
        ImplementationSelector.DAO.setMock(new LeadsDAOMock());
        ImplementationSelector.DAO.setMock(new LeadScoreDetailsDAOMock());
        ImplementationSelector.DAO.setMock(new MarketingSegmentationsDAOMock());

        List<Lead_Score_Configuration__c> leadScoreConfigList = new List<Lead_Score_Configuration__c>();

        leadScoreConfigList.add(
            new Lead_Score_Configuration__c(
                Name = 'Enquiries',
                RecordTypeId = LeadScoreConfigurationDAO.RECTYPE_ID_CATEGORY,
                Domestic_International__c = 'International',
                Study_Level__c = 'Undergraduate',
                Description__c = '',
                Score_Allocation__c = null,
                Time_Limit_Months__c = 36,
                Max_Score__c = 15
            )
        );

        LeadScoreConfigurationDAO.newInstance()
            .insertRecords(leadScoreConfigList, true, AccessLevel.USER_MODE);

        List<Lead_Score_Configuration__c> leadScoreConfigChildList = new List<Lead_Score_Configuration__c>();
        leadScoreConfigChildList.addAll(
            TestDataFactory.createIntlAndUnderGradSubCategory(
                leadScoreConfigList[0].Id,
                new List<String>{
                    'Applying for a course',
                    'Entry requirements & study pathways',
                    'Fees, costs and scholarships',
                    'Course information',
                    'Course application & offers',
                    'Preparing to Study',
                    'Student Life'
                },
                new List<Integer>{ 10, 10, 5, 5, 5, 5, 5 }
            )
        );

        LeadScoreConfigurationDAO.newInstance()
            .insertRecords(leadScoreConfigChildList, true, AccessLevel.USER_MODE);

        List<Contact> contactList = TestDataFactory.createTestContactRecords(1);
        ContactsDAO.newInstance().insertRecords(contactList, true, AccessLevel.USER_MODE);

        List<Lead> leadList = TestDataFactory.createTestLeadRecords(1);
        LeadsDAO.newInstance().insertRecords(leadList, true, AccessLevel.USER_MODE);

        List<Case> caseList = new List<Case>();
        caseList.add(
            new Case(ContactId = contactList[0].Id, Category__c = 'Applying for a course')
        );
        caseList.add(new Case(Lead__c = leadList[0].Id, Category__c = 'Course information'));

        CasesDAO.newInstance().insertRecords(caseList, true, AccessLevel.USER_MODE);

        LeadScoreDetailsDAO.newInstance()
            .insertRecords(
                new List<Lead_Score_Detail__c>{
                    new Lead_Score_Detail__c(Contact__c = contactList[0].Id)
                },
                false,
                AccessLevel.USER_MODE
            );

        Set<Id> contactAndLeadIds = new Set<Id>{ contactList[0].Id, leadList[0].Id };

        LeadScoreCalculatorService.LeadScoreCalculatorParams leadScoreCalcParams = new LeadScoreCalculatorService.LeadScoreCalculatorParams(
            Case.sObjectType,
            new Map<Id, Case>(CasesDAO.newInstance().getCasesByContactOrLeadIds(contactAndLeadIds, AccessLevel.SYSTEM_MODE)),
            LeadScoreConfigurationDAO.newInstance()
                .getLeadScoreConfigByRecordTypeIds(
                    AccessLevel.USER_MODE,
                    LeadScoreConfigurationDAO.RECTYPE_IDS_CATEGORY_AND_SUB_CATEGORY
                ),
            contactAndLeadIds
        );

        System.assert(
            !LeadScoreUndergradIntCmd.processStudyLevel(leadScoreCalcParams).isEmpty(),
            'Was not able to calcualte lead score details'
        );
    }

    @isTest
    private static void processStudyLevelForMarSegTest() {//NOPMD test class is mocked user is not needed
        
        ImplementationSelector.DAO.setMock(new LeadScoreConfigurationDAOMock());
        ImplementationSelector.DAO.setMock(new MarketingSegmentationsDAOMock());
        ImplementationSelector.DAO.setMock(new ContactsDAOMock());
        ImplementationSelector.DAO.setMock(new LeadsDAOMock());
        ImplementationSelector.DAO.setMock(new LeadScoreDetailsDAOMock());
        ImplementationSelector.DAO.setMock(new InternationalTiersDAOMock());

        List<Lead_Score_Configuration__c> leadScoreConfigList = new List<Lead_Score_Configuration__c>();

        leadScoreConfigList.add(
            new Lead_Score_Configuration__c(
                Name = 'Residence',
                RecordTypeId = LeadScoreConfigurationDAO.RECTYPE_ID_CATEGORY,
                Domestic_International__c = 'International',
                Study_Level__c = 'Undergraduate',
                Description__c = '',
                Score_Allocation__c = null,
                Time_Limit_Months__c = 36,
                Max_Score__c = 15
            )
        );

        LeadScoreConfigurationDAO.newInstance()
            .insertRecords(leadScoreConfigList, true, AccessLevel.USER_MODE);

        List<Lead_Score_Configuration__c> leadScoreConfigChildList = new List<Lead_Score_Configuration__c>();
        leadScoreConfigChildList.addAll(
            TestDataFactory.createIntlAndUnderGradSubCategory(
                leadScoreConfigList[0].Id,
                new List<String>{ 'Australia (Onshore)', 'Non-Australia (offshore)' },
                new List<Integer>{ 10, 5 }
            )
        );

        LeadScoreConfigurationDAO.newInstance()
            .insertRecords(leadScoreConfigChildList, true, AccessLevel.USER_MODE);

        List<Contact> contactList = TestDataFactory.createTestContactRecords(1);
        ContactsDAO.newInstance().insertRecords(contactList, true, AccessLevel.USER_MODE);

        List<Lead> leadList = TestDataFactory.createTestLeadRecords(1);
        LeadsDAO.newInstance().insertRecords(leadList, true, AccessLevel.USER_MODE);

        List<Marketing_Segmentation__c> marSegList = new List<Marketing_Segmentation__c>();
        marSegList.add(
            new Marketing_Segmentation__c(
                Contact__c = contactList[0].Id,
                My_Country_Of_Residency__c = 'Australia',
                My_Funding_Source__c = 'I need a full scholarship'
            )
        );
        marSegList.add(
            new Marketing_Segmentation__c(
                Lead__c = leadList[0].Id,
                My_Country_Of_Residency__c = 'New Zealand'
            )
        );

        LeadScoreDetailsDAO.newInstance()
            .insertRecords(
                new List<Lead_Score_Detail__c>{
                    new Lead_Score_Detail__c(Contact__c = contactList[0].Id),
                    new Lead_Score_Detail__c(Lead__c = leadList[0].Id)
                },
                false,
                AccessLevel.USER_MODE
            );

        MarketingSegmentationsDAO.newInstance()
            .insertRecords(marSegList, true, AccessLevel.USER_MODE);

        Set<Id> contactAndLeadIds = new Set<Id>{ contactList[0].Id, leadList[0].Id };

        Map<Id, Marketing_Segmentation__c> marSegMap = new Map<Id, Marketing_Segmentation__c>();

        for (Marketing_Segmentation__c marSeg : marSegList) {
            marSegMap.put(marSeg.Lead__c, marSeg);
            if (marSeg.Contact__c != null) {
                marSegMap.put(marSeg.Contact__c, marSeg);
            }
        }

        LeadScoreCalculatorService.LeadScoreCalculatorParams leadScoreCalcParams = new LeadScoreCalculatorService.LeadScoreCalculatorParams(
            Marketing_Segmentation__c.sObjectType,
            marSegMap,
            LeadScoreConfigurationDAO.newInstance()
                .getLeadScoreConfigByRecordTypeIds(
                    AccessLevel.USER_MODE,
                    LeadScoreConfigurationDAO.RECTYPE_IDS_CATEGORY_AND_SUB_CATEGORY
                ),
            contactAndLeadIds
        );

        System.assert(
            !LeadScoreUndergradIntCmd.processStudyLevel(leadScoreCalcParams).isEmpty(),
            'Was not able to calcualte lead score details'
        );
    }

    @isTest
    private static void processStudyLevelForContactAndLeadTest() {//NOPMD test class is mocked user is not needed
        
        ImplementationSelector.DAO.setMock(new LeadScoreConfigurationDAOMock());
        ImplementationSelector.DAO.setMock(new ContactsDAOMock());
        ImplementationSelector.DAO.setMock(new LeadsDAOMock());
        ImplementationSelector.DAO.setMock(new LeadScoreDetailsDAOMock());
        ImplementationSelector.DAO.setMock(new MarketingSegmentationsDAOMock());

        List<Lead_Score_Configuration__c> leadScoreConfigList = new List<Lead_Score_Configuration__c>();

        leadScoreConfigList.add(
            new Lead_Score_Configuration__c(
                Name = 'Marketing Consent',
                RecordTypeId = LeadScoreConfigurationDAO.RECTYPE_ID_CATEGORY,
                Domestic_International__c = 'International',
                Study_Level__c = 'Undergraduate',
                Description__c = '',
                Score_Allocation__c = null,
                Time_Limit_Months__c = null,
                Max_Score__c = 0
            )
        );

        LeadScoreConfigurationDAO.newInstance()
            .insertRecords(leadScoreConfigList, true, AccessLevel.USER_MODE);

        List<Lead_Score_Configuration__c> leadScoreConfigChildList = new List<Lead_Score_Configuration__c>();
        leadScoreConfigChildList.addAll(
            TestDataFactory.createIntlAndUnderGradSubCategory(
                leadScoreConfigList[0].Id,
                new List<String>{ 'Yes', 'Is blank' },
                new List<Integer>{ 10, 0 }
            )
        );

        LeadScoreConfigurationDAO.newInstance()
            .insertRecords(leadScoreConfigChildList, true, AccessLevel.USER_MODE);

        List<Contact> contactList = new List<Contact>();

        contactList.add(new Contact(Email_Opt_In_DateTime__c = System.Today()));
        contactList.add(new Contact());

        ContactsDAO.newInstance().insertRecords(contactList, true, AccessLevel.USER_MODE);

        List<Lead> leadList = new List<Lead>();

        leadList.add(new Lead(Email_Opt_In_DateTime__c = System.Today()));
        leadList.add(new Lead());

        LeadsDAO.newInstance().insertRecords(leadList, true, AccessLevel.USER_MODE);

        LeadScoreDetailsDAO.newInstance()
            .insertRecords(
                new List<Lead_Score_Detail__c>{
                    new Lead_Score_Detail__c(Contact__c = contactList[0].Id),
                    new Lead_Score_Detail__c(Lead__c = leadList[0].Id)
                },
                false,
                AccessLevel.USER_MODE
            );

        Set<Id> contactIds = new Set<Id>{ contactList[0].Id, contactList[1].Id };

        LeadScoreCalculatorService.LeadScoreCalculatorParams leadScoreCalcParams = new LeadScoreCalculatorService.LeadScoreCalculatorParams(
            Contact.sObjectType,
            new Map<Id, Contact>(contactList),
            LeadScoreConfigurationDAO.newInstance()
                .getLeadScoreConfigByRecordTypeIds(
                    AccessLevel.USER_MODE,
                    LeadScoreConfigurationDAO.RECTYPE_IDS_CATEGORY_AND_SUB_CATEGORY
                ),
            contactIds
        );

        System.assert(
            !LeadScoreUndergradIntCmd.processStudyLevel(leadScoreCalcParams).isEmpty(),
            'Was not able to calcualte lead score details'
        );

        Set<Id> leadIds = new Set<Id>{ leadList[0].Id, leadList[1].Id };

        leadScoreCalcParams = new LeadScoreCalculatorService.LeadScoreCalculatorParams(
            Lead.sObjectType,
            new Map<Id, Lead>(leadList),
            LeadScoreConfigurationDAO.newInstance()
                .getLeadScoreConfigByRecordTypeIds(
                    AccessLevel.USER_MODE,
                    LeadScoreConfigurationDAO.RECTYPE_IDS_CATEGORY_AND_SUB_CATEGORY
                ),
            leadIds
        );

        System.assert(
            !LeadScoreUndergradIntCmd.processStudyLevel(leadScoreCalcParams).isEmpty(),
            'Was not able to calcualte lead score details'
        );
    }

    @isTest
    private static void processStudyLevelForMarInteractionTest() {//NOPMD test class is mocked user is not needed

        ImplementationSelector.DAO.setMock(new LeadScoreConfigurationDAOMock());
        ImplementationSelector.DAO.setMock(new ContactsDAOMock());
        ImplementationSelector.DAO.setMock(new LeadsDAOMock());
        ImplementationSelector.DAO.setMock(new LeadScoreDetailsDAOMock());
        ImplementationSelector.DAO.setMock(new MarketingSegmentationsDAOMock());
        ImplementationSelector.DAO.setMock(new MarketingInteractionsDAOMock());

        List<Lead_Score_Configuration__c> leadScoreConfigList = new List<Lead_Score_Configuration__c>();

        leadScoreConfigList.add(
            new Lead_Score_Configuration__c(
                Name = 'Downloaded PDF',
                RecordTypeId = LeadScoreConfigurationDAO.RECTYPE_ID_CATEGORY,
                Domestic_International__c = 'International',
                Study_Level__c = 'Undergraduate',
                Description__c = '',
                Score_Allocation__c = null,
                Time_Limit_Months__c = null,
                Max_Score__c = 0
            )
        );

        LeadScoreConfigurationDAO.newInstance()
            .insertRecords(leadScoreConfigList, true, AccessLevel.USER_MODE);

        List<Lead_Score_Configuration__c> leadScoreConfigChildList = new List<Lead_Score_Configuration__c>();
        leadScoreConfigChildList.addAll(
            TestDataFactory.createIntlAndUnderGradSubCategory(
                leadScoreConfigList[0].Id,
                new List<String>{ 'Course Page PDF', 'Welcome Guide' },
                new List<Integer>{ 5, 5 }
            )
        );

        LeadScoreConfigurationDAO.newInstance()
            .insertRecords(leadScoreConfigChildList, true, AccessLevel.USER_MODE);

        List<Contact> contactList = TestDataFactory.createTestContactRecords(1);
        ContactsDAO.newInstance().insertRecords(contactList, true, AccessLevel.USER_MODE);

        List<Lead> leadList = TestDataFactory.createTestLeadRecords(1);
        LeadsDAO.newInstance().insertRecords(leadList, true, AccessLevel.USER_MODE);

        Set<Id> contactAndLeadIds = new Set<Id>{ contactList[0].Id, leadList[0].Id };

        List<Marketing_Interaction__c> marInteractionList = new List<Marketing_Interaction__c>();
        marInteractionList.add(
            new Marketing_Interaction__c(
                Contact__c = contactList[0].Id,
                Lead_Source__c = 'Course Page PDF Download'
            )
        );
        marInteractionList.add(
            new Marketing_Interaction__c(
                Lead__c = leadList[0].Id,
                Lead_Source__c = 'Welcome Guide Download'
            )
        );

        MarketingInteractionsDAO.newInstance()
            .insertRecords(marInteractionList, true, AccessLevel.USER_MODE);

        LeadScoreDetailsDAO.newInstance()
            .insertRecords(
                new List<Lead_Score_Detail__c>{
                    new Lead_Score_Detail__c(Contact__c = contactList[0].Id)
                },
                false,
                AccessLevel.USER_MODE
            );

        LeadScoreCalculatorService.LeadScoreCalculatorParams leadScoreCalcParams = new LeadScoreCalculatorService.LeadScoreCalculatorParams(
            Marketing_Interaction__c.sObjectType,
            new Map<Id, Marketing_Interaction__c>(marInteractionList),
            LeadScoreConfigurationDAO.newInstance()
                .getLeadScoreConfigByRecordTypeIds(
                    AccessLevel.USER_MODE,
                    LeadScoreConfigurationDAO.RECTYPE_IDS_CATEGORY_AND_SUB_CATEGORY
                ),
            contactAndLeadIds
        );

        System.assert(
            !LeadScoreUndergradIntCmd.processStudyLevel(leadScoreCalcParams).isEmpty(),
            'Was not able to calcualte lead score details'
        );
    }

    @isTest
    private static void processStudyLevelForProgramEnrolmentTest() {//NOPMD test class is mocked user is not needed

        ImplementationSelector.DAO.setMock(new LeadScoreConfigurationDAOMock());
        ImplementationSelector.DAO.setMock(new LeadScoreDetailsDAOMock());
        ImplementationSelector.DAO.setMock(new AccountsDAOMock());
        ImplementationSelector.DAO.setMock(new ContactsDAOMock());
        ImplementationSelector.DAO.setMock(new ProgramEnrollmentsDAOMock());

        List<Lead_Score_Configuration__c> leadScoreConfigList = new List<Lead_Score_Configuration__c>();

        leadScoreConfigList.add(
            new Lead_Score_Configuration__c(
                Name = 'Program Engagement',
                RecordTypeId = LeadScoreConfigurationDAO.RECTYPE_ID_CATEGORY,
                Domestic_International__c = 'International',
                Study_Level__c = 'Undergraduate',
                Description__c = '',
                Score_Allocation__c = null,
                Time_Limit_Months__c = null,
                Max_Score__c = 0
            )
        );

        LeadScoreConfigurationDAO.newInstance()
            .insertRecords(leadScoreConfigList, true, AccessLevel.USER_MODE);

        List<Lead_Score_Configuration__c> leadScoreConfigChildList = new List<Lead_Score_Configuration__c>();
        leadScoreConfigChildList.addAll(
            TestDataFactory.createIntlAndUnderGradSubCategory(
                leadScoreConfigList[0].Id,
                new List<String>{ 'Program Engagement attendance' },
                new List<Integer>{ 30 }
            )
        );

        LeadScoreConfigurationDAO.newInstance()
            .insertRecords(leadScoreConfigChildList, true, AccessLevel.USER_MODE);

        List<Contact> contactList = TestDataFactory.createTestContactRecords(1);
        ContactsDAO.newInstance().insertRecords(contactList, true, AccessLevel.USER_MODE);

        List<Account> accountList = new List<Account>();
        accountList.add(
            new Account(
                Name = 'Test',
                Program_Code__c = 'QC19',
                RecordTypeId = AccountsDAO.ACCT_ACADEMIC_PROGRAM_ID
            )
        );

        AccountsDAO.newInstance().insertRecords(accountList, false, AccessLevel.USER_MODE);

        List<hed__Program_Enrollment__c> progEnrolmentList = new List<hed__Program_Enrollment__c>();
        progEnrolmentList.add(
            new hed__Program_Enrollment__c(
                hed__Account__c = accountList[0].Id,
                hed__Contact__c = contactList[0].Id
            )
        );

        ProgramEnrollmentsDAO.newInstance()
            .insertRecords(progEnrolmentList, true, AccessLevel.USER_MODE);

        LeadScoreDetailsDAO.newInstance()
            .insertRecords(
                new List<Lead_Score_Detail__c>{
                    new Lead_Score_Detail__c(Contact__c = contactList[0].Id)
                },
                false,
                AccessLevel.USER_MODE
            );

        Set<Id> contactAndLeadIds = new Set<Id>{ contactList[0].Id };

        LeadScoreCalculatorService.LeadScoreCalculatorParams leadScoreCalcParams = new LeadScoreCalculatorService.LeadScoreCalculatorParams(
            hed__Program_Enrollment__c.sObjectType,
            new Map<Id, hed__Program_Enrollment__c>(progEnrolmentList),
            LeadScoreConfigurationDAO.newInstance()
                .getLeadScoreConfigByRecordTypeIds(
                    AccessLevel.USER_MODE,
                    LeadScoreConfigurationDAO.RECTYPE_IDS_CATEGORY_AND_SUB_CATEGORY
                ),
            contactAndLeadIds
        );

        System.assert(
            !LeadScoreUndergradIntCmd.processStudyLevel(leadScoreCalcParams).isEmpty(),
            'Was not able to calcualte lead score details'
        );
    }

    @isTest
    private static void processIndividualEmailTest() { //NOPMD test class is mocked, user is not needed
        
        ImplementationSelector.DAO.setMock(new LeadScoreConfigurationDAOMock());
        ImplementationSelector.DAO.setMock(new IndividualEmailResultsDAOMock());
        ImplementationSelector.DAO.setMock(new ContactsDAOMock());
        ImplementationSelector.DAO.setMock(new LeadsDAOMock());
        ImplementationSelector.DAO.setMock(new LeadScoreDetailsDAOMock());
        ImplementationSelector.DAO.setMock(new MarketingSegmentationsDAOMock());

        List<Lead_Score_Configuration__c> leadScoreConfigList = new List<Lead_Score_Configuration__c>();

        leadScoreConfigList.add(
            new Lead_Score_Configuration__c(
                Name = 'Email Interaction',
                RecordTypeId = LeadScoreConfigurationDAO.RECTYPE_ID_CATEGORY,
                Domestic_International__c = 'International',
                Study_Level__c = 'Undergraduate',
                Description__c = '',
                Score_Allocation__c = null,
                Time_Limit_Months__c = 3,
                Max_Score__c = 10
            )
        );

        LeadScoreConfigurationDAO.newInstance()
            .insertRecords(leadScoreConfigList, true, AccessLevel.USER_MODE);

        List<Lead_Score_Configuration__c> leadScoreConfigChildList = new List<Lead_Score_Configuration__c>();
        leadScoreConfigChildList.addAll(
            TestDataFactory.createIntlAndUnderGradSubCategory(
                leadScoreConfigList[0].Id,
                new List<String>{ 'Has Clicked Email' },
                new List<Integer>{ 5 }
            )
        );

        LeadScoreConfigurationDAO.newInstance()
            .insertRecords(leadScoreConfigChildList, true, AccessLevel.USER_MODE);

        List<Contact> contactList = TestDataFactory.createTestContactRecords(1, ContactsDAO.CITIZENSHIP_STATUS_INTERNATIONAL);
        ContactsDAO.newInstance().insertRecords(contactList, true, AccessLevel.USER_MODE);

        List<Lead> leadList = TestDataFactory.createTestLeadRecords(1);
        LeadsDAO.newInstance().insertRecords(leadList, true, AccessLevel.USER_MODE);

        List<et4ae5__IndividualEmailResult__c> indivEmailList = new List<et4ae5__IndividualEmailResult__c>();
        indivEmailList.add(
            new et4ae5__IndividualEmailResult__c(
                et4ae5__Contact__c = contactList[0].Id, 
                et4ae5__Opened__c = true,
                et4ae5__NumberOfUniqueClicks__c	= 5,
                et4ae5__DateOpened__c = System.Today()
            )
        );

        indivEmailList.add(
            new et4ae5__IndividualEmailResult__c(
                et4ae5__Lead__c = leadList[0].Id, 
                et4ae5__Opened__c = true,
                et4ae5__NumberOfUniqueClicks__c	= 2,
                et4ae5__DateOpened__c = System.Today()
            )
        );

        IndividualEmailResultsDAO.newInstance().insertRecords(indivEmailList, true, AccessLevel.USER_MODE);

        LeadScoreDetailsDAO.newInstance()
            .insertRecords(
                new List<Lead_Score_Detail__c>{
                    new Lead_Score_Detail__c(Contact__c = contactList[0].Id)
                },
                false,
                AccessLevel.USER_MODE
            );

        Set<Id> contactAndLeadIds = new Set<Id>{ contactList[0].Id, leadList[0].Id };

        LeadScoreCalculatorService.LeadScoreCalculatorParams leadScoreCalcParams = new LeadScoreCalculatorService.LeadScoreCalculatorParams(
            et4ae5__IndividualEmailResult__c.sObjectType,
            new Map<Id, et4ae5__IndividualEmailResult__c>(indivEmailList),
            LeadScoreConfigurationDAO.newInstance()
                .getLeadScoreConfigByRecordTypeIds(
                    AccessLevel.USER_MODE,
                    LeadScoreConfigurationDAO.RECTYPE_IDS_CATEGORY_AND_SUB_CATEGORY
                ),
            contactAndLeadIds
        );

        System.assert(
            !LeadScoreUndergradIntCmd.processStudyLevel(leadScoreCalcParams).isEmpty(),
            'Was not able to calcualte lead score details'
        );
    }
}