src/core-crm/objects/Account/fields/Sync_to_MC__c.field-meta.xml
<CustomField>
    <fullName>Sync_to_MC__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When this is true, this record will be synchronised with Marketing Cloud</description>
    <label>Sync to MC</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Contact/fields/Agency_Country__c.field-meta.xml
<CustomField>
    <fullName>Agency_Country__c</fullName>
    <description>The country that the agency resides in.</description>
    <label>Agency Country</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Contact/fields/Agency_Email__c.field-meta.xml
<CustomField>
    <fullName>Agency_Email__c</fullName>
    <description>The agency email address.</description>
    <label>Agency Email</label>
    <type>Email</type>
</CustomField>

src/core-crm/objects/Contact/fields/Agency_Name__c.field-meta.xml
<CustomField>
    <fullName>Agency_Name__c</fullName>
    <description>The Name of the Agency.</description>
    <label>Agency Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Contact/fields/Do_Not_Sync_To_MC_Override__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Sync_To_MC_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When this is true, this will mark Sync to MC as false and this will not be synced to Marketing Cloud</description>
    <label>Do Not Sync To MC (Override)</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Contact/fields/Education_Disruption_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Education_Disruption_Applicant__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Recent Application by contact has flagged Education Disruption applicant.</description>
    <label>Education Disruption Applicant</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Contact/fields/Elite_Athlete_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Elite_Athlete_Applicant__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Recent Application by contact has flagged Elite Athlete Applicant.</description>
    <label>Elite Athlete Applicant</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Contact/fields/Financial_Hardship_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Financial_Hardship_Applicant__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Recent Application by contact has flagged Financial Hardship applicant.</description>
    <label>Financial Hardship Applicant</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Contact/fields/First_in_Family_Applicant__c.field-meta.xml
<CustomField>
    <fullName>First_in_Family_Applicant__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Recent Application by contact has flagged First in Family applicant.</description>
    <label>First in Family Applicant</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Contact/fields/hed__SMS_Opt_Out__c.field-meta.xml
<CustomField>
    <fullName>hed__SMS_Opt_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates whether a person wants to receive SMS communications.</description>
    <inlineHelpText>Indicates whether a person wants to receive SMS communications.</inlineHelpText>
    <label>SMS Opt Out</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Contact/fields/Is_Agent_Assisted__c.field-meta.xml
<CustomField>
    <fullName>Is_Agent_Assisted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the applicant has been assisted by an agency in their application.</description>
    <label>Is Agent Assisted</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Contact/fields/Is_International_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Is_International_Applicant__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Has the contact submitted an International Application recently?</description>
    <label>Is International Applicant</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Contact/fields/Learner_Email_Opt_Out__c.field-meta.xml
<CustomField>
    <fullName>Learner_Email_Opt_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Marketing should not email this email address</description>
    <label>Learner Email Opt Out</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Contact/fields/Personal_Illness_Disability_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Personal_Illness_Disability_Applicant__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Recent application by Contact has flagged Personal Illness Disability applicant.</description>
    <label>Personal Illness Disability Applicant</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/main/objects/Contact/fields/QUT_Learner_Email__c.field-meta.xml
<CustomField>
    <fullName>QUT_Learner_Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>QUT Learner Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

src/core-crm/objects/Contact/fields/Staff_Email_Opt_Out__c.field-meta.xml
<CustomField>
    <fullName>Staff_Email_Opt_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Marketing should not email this email address</description>
    <label>Staff Email Opt Out</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Contact/fields/Work_Email_Opt_Out__c.field-meta.xml
<CustomField>
    <fullName>Work_Email_Opt_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Marketing should not email this email address</description>
    <label>Work Email Opt Out</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Contact/fields/Work_SMS_Opt_Out__c.field-meta.xml
<CustomField>
    <fullName>Work_SMS_Opt_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Marketing should not sms this mobile number</description>
    <label>Work SMS Opt Out</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/hed__Application__c/hed__Application__c.object-meta.xml
<CustomObject>
    <description>Stores information about a student&apos;s application to an educational institution or program.</description>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Application__c/fields/Agency_Country__c.field-meta.xml
<CustomField>
    <fullName>Agency_Country__c</fullName>
    <description>The country that the agency resides in</description>
    <label>Agency Country</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Application__c/fields/Agency_Email__c.field-meta.xml
<CustomField>
    <fullName>Agency_Email__c</fullName>
    <description>The agency email address</description>
    <label>Agency Email</label>
    <type>Email</type>
</CustomField>

src/core-crm/objects/hed__Application__c/fields/Agency_Name__c.field-meta.xml
<CustomField>
    <fullName>Agency_Name__c</fullName>
    <description>The Name of the agency</description>
    <label>Agency Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <description>The status given to the application by the application source.</description>
    <label>Application Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Application__c/fields/Applied_Intake_Study_Period__c.field-meta.xml
<CustomField>
    <fullName>Applied_Intake_Study_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The starting study period applied for.</description>
    <label>Applied Intake Study Period</label>
    <referenceTo>hed__Term__c</referenceTo>
    <relationshipLabel>Applications (Applied Intake Study Period)</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Application__c/fields/BirthDate__c.field-meta.xml
<CustomField>
    <fullName>BirthDate__c</fullName>
    <description>The applicant’s date of birth</description>
    <label>BirthDate</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/hed__Application__c/fields/Calculated_Intake_Date__c.field-meta.xml
<CustomField>
    <fullName>Calculated_Intake_Date__c</fullName>
    <description>Calculated date as the latest intake date based on logic corresponding to the application record type.</description>
    <label>Calculated Intake Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/hed__Application__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>The applicant’s email address on application</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

src/core-crm/objects/hed__Application__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>The applicant’s first name</description>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Application__c/fields/hed__Applicant__c.field-meta.xml
<CustomField>
    <fullName>hed__Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Contact applying to the institution or program.</description>
    <inlineHelpText>The Contact applying to the institution or program.</inlineHelpText>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications (Applicant)</relationshipLabel>
    <relationshipName>Applications_Applicant</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Application__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>The QTAC application is still active.</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/hed__Application__c/fields/Is_Agent_Assisted__c.field-meta.xml
<CustomField>
    <fullName>Is_Agent_Assisted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicating if the applicant is being assisted with thier application to study by an agent</description>
    <label>Agent Assisted</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/hed__Application__c/fields/Is_Education_Disruption_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Is_Education_Disruption_Applicant__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicating if applicant is qualified for EAS due to education being disrupted</description>
    <label>Education Disruption Applicant</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/hed__Application__c/fields/Is_Elite_Athlete_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Is_Elite_Athlete_Applicant__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicating if applicant is qualified for EAS due to participation in elite sport or atheletics</description>
    <label>Elite Athlete Applicant</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/hed__Application__c/fields/Is_Financial_Hardship_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Is_Financial_Hardship_Applicant__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicating if applicant is qualified for EAS due financial hardship.</description>
    <label>Financial Hardship Applicant</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/hed__Application__c/fields/Is_First_In_Family_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Is_First_In_Family_Applicant__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicating if applicant is qualified for EAS due to being the first member of the family to study at tertiary education.</description>
    <label>First In Family Applicant</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/hed__Application__c/fields/Is_International_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Is_International_Applicant__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicating if the applicant is an international applicant</description>
    <label>Is International Applicant</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/hed__Application__c/fields/Is_Personal_Illness_Disability_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Is_Personal_Illness_Disability_Applicant__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicating if applicant is qualified for EAS due to Illness or disability</description>
    <label>Pesonal Illness Disability Applicant</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/hed__Application__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>The applicant’s last name</description>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Application__c/recordTypes/QTAC.recordType-meta.xml
<RecordType>
    <fullName>QTAC</fullName>
    <active>true</active>
    <label>QTAC</label>
</RecordType>

src/core-crm/objects/hed__Term__c/hed__Term__c.object-meta.xml
<CustomObject>
    <description>Unit of time in which academic activities are taking place.</description>
    <label>Term</label>
    <nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Term__c/fields/hed__Account__c.field-meta.xml
<CustomField>
    <fullName>hed__Account__c</fullName>
    <description>The Academic Program, Department, or entire Educational Institution this Term applies to. Select the Account that represents your Educational Institution if Terms are consistent across all Programs and Departments in your school.</description>
    <inlineHelpText>The Academic Program, Department, or entire Educational Institution this Term applies to. Select the Account that represents your Educational Institution if Terms are consistent across all Programs and Departments in your school.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Terms</relationshipLabel>
    <relationshipName>Terms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/core-crm/objects/hed__Term__c/fields/hed__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>hed__Start_Date__c</fullName>
    <description>The date this Term starts.</description>
    <inlineHelpText>The date this Term starts.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/classes/ApplicationTriggerHelperTest.cls
/**
 * @description Test Class for ApplicationTriggerHelper
 *
 * @see ApplicationTriggerHelper
 *
 * @author Accenture
 *
 * @history
 *    | Developer                 | Date                  | JIRA         | Change Summary                              |
      |---------------------------|-----------------------|--------------|---------------------------------------------|
      | mark.j.mahilum            | July 18,2023          | DEPP-5799    | Created file                                |
      | alexander.cadalin         | Aug 16, 2023          | DEPP-6124    | Refactor to consider multiple field updates |
      | julie.jane.alegre         | September 20, 2023    | DEPP-6667    | Added testUpdateContactWhenQTACAppIsInactive|
*/
@isTest
private class ApplicationTriggerHelperTest {
    private static final String FIRSTNAME = 'TestfirstName';
    private static final String LASTNAME = 'Testlastname';
    private static final String EMAIL = 'testmail@mail.test';
    private static final String BIRTHDAY = '2000-06-28';
    private static Integer recordsCount = 20;
    
    @testSetup
    static void testSetup() {
        TestDataFactory.generateTestUsers(new List<String>{ 'QUT_Program_Administrator', 'QUT_ESB' });
        System.runAs(TestDataFactory.getProgramAdminUser()) {
            List<Account> newAccounts = new List<Account>();
            newAccounts.add(TestDataFactory.createTestAccount(false));
            newAccounts[0].RecordTypeId = AccountsDAO.ACCT_UNIV_DEP_ID;
            AccountsDAO.newInstance().insertRecords(newAccounts, false, AccessLevel.SYSTEM_MODE);

            List<Contact> newContacts = createTestContactRecords(0, 1);            
            ContactsDAO.newInstance().insertRecords(newContacts, false, AccessLevel.SYSTEM_MODE);
            
            ApplicationsDAO.newInstance().insertRecords(
                createTestApplicationRecords(newContacts,'Existing',ApplicationsDAO.STUDYLINK_RECTYPE_ID),
                false,
                AccessLevel.SYSTEM_MODE
            );    

            List<Marketing_Interaction__c> marketingInteractionList = TestDataFactory.createMarketingInteractionRecords(newContacts[0].Id, 1, 'QTAC');
            MarketingInteractionsDAO.newInstance().insertRecords(marketingInteractionList, false, AccessLevel.SYSTEM_MODE);
        }
    }

    @isTest
    private static void testApplicationInsertWithContact() {
        System.runAs(TestDataFactory.getProgramAdminUser()) {
            List<Contact> newContacts = createTestContactRecords(0, 1);            
            ContactsDAO.newInstance().insertRecords(newContacts, false, AccessLevel.SYSTEM_MODE);
            
            Test.startTest();
            Database.SaveResult[] srList = ApplicationsDAO.newInstance()
                .insertRecords(
                    createTestApplicationRecords(newContacts,'Existing',ApplicationsDAO.STUDYLINK_RECTYPE_ID),
                    false,
                    AccessLevel.SYSTEM_MODE
                );
            Test.stopTest();
            for (Database.SaveResult sr : srList) {
                System.assert(sr.isSuccess(), 'A record was not saved.');
            }
        }
    }
    
    @isTest
    private static void testApplicationUpdateRemoveContact() {
        System.runAs(TestDataFactory.getProgramAdminUser()) {
            
            Id contactId = ContactsDAO.newInstance().getPersonContactsWithLimit(1).iterator().next()?.Id;                
            List<hed__Application__c> existingApplicationList = ApplicationsDAO.newInstance().getApplicationsByContactIds(new Set<Id>{contactId},'SYSTEM_MODE');   
            
            for(hed__Application__c app: existingApplicationList){            
                
				app.Application_Status__c = 'Accepted';  
                app.hed__Applicant__c = null;
            }
            
            Test.startTest();
            Database.SaveResult[] srList = ApplicationsDAO.newInstance()
                .updateRecords(
                    existingApplicationList,
                    false,
                    AccessLevel.SYSTEM_MODE
                );
            Test.stopTest();
            for (Database.SaveResult sr : srList) {
                System.assert(sr.isSuccess(), 'A record was not updated.');
            }
        }
    }
    
    @isTest
    private static void testApplicationWithLeadApplicationStatusWithdrawn() {
        System.runAs(TestDataFactory.getESBIntegrationUser()) {
            Id contactId = ContactsDAO.newInstance().getPersonContactsWithLimit(1).iterator().next()?.Id;                
            List<hed__Application__c> existingApplicationList = ApplicationsDAO.newInstance().getApplicationsByContactIds(new Set<Id>{contactId},'USER_MODE');   
            List<hed__Application__c> applicationToUpdateList = new List<hed__Application__c>();
            for(hed__Application__c app: existingApplicationList){                           
                applicationToUpdateList.add(new hed__Application__c(Id = app.Id ,Application_Status__c = 'Withdrawn'));
            }
            
            Test.startTest();
            Database.SaveResult[] srList = ApplicationsDAO.newInstance()
                .updateRecords(
                    applicationToUpdateList,
                    false,
                    AccessLevel.USER_MODE
                );
            Test.stopTest();
            for (Database.SaveResult sr : srList) {
                System.assert(sr.isSuccess(), 'A record was not updated.');
            }
        }
    } 

    @isTest
    private static void updateCalculatedDateOnSamsApplicationRecordsTest() {
        System.runAs(TestDataFactory.getESBIntegrationUser()) {
            Test.startTest();
            List<Contact> newContacts = createTestContactRecords(0, 1);
            ContactsDAO.newInstance().insertRecords(newContacts, false, AccessLevel.SYSTEM_MODE);

            // create term
            List<Account> accountList = AccountsDAO.newInstance()
                .getAccountsBySetNames(new Set<String>{'Test Account'});
            hed__Term__c appliedIntakeTerm = new hed__Term__c(
                hed__Start_Date__c = System.today(),
                hed__Account__c = accountList[0].Id
            );
            insert appliedIntakeTerm;
            // create application
            List<hed__Application__c> newApplications = createTestApplicationRecords(newContacts,'New', ApplicationsDAO.SAMS_LEGACY_RECTYPE_ID);
            newApplications[0].Applied_Intake_Study_Period__c = appliedIntakeTerm.Id;
            ApplicationsDAO.newInstance().insertRecords(newApplications, false, AccessLevel.SYSTEM_MODE);
            
            Test.stopTest();

            List<hed__Application__c> updatedApplicationList = [SELECT Id, Calculated_Intake_Date__c,Applied_Intake_Study_Period__c FROM hed__Application__c WHERE Applied_Intake_Study_Period__c =: appliedIntakeTerm.Id];
            // assert
            System.assertEquals(
                Date.today(),
                updatedApplicationList[0].Calculated_Intake_Date__c, 
                'Error, Should be equal to term start date.'
            );
        }
    } 
    
    @isTest
    private static void testUpdateRelatedContacts() {
        System.runAs(TestDataFactory.getESBIntegrationUser()) {
            List<hed__Application__c> applicationsToUpdate = [
                SELECT Id, Is_Agent_Assisted__c, Is_International_Applicant__c,
                Is_Personal_Illness_Disability_Applicant__c, Is_Elite_Athlete_Applicant__c, 
                Is_Education_Disruption_Applicant__c, Is_First_In_Family_Applicant__c, 
                Is_Financial_Hardship_Applicant__c, Agency_Name__c, Agency_Country__c, Agency_Email__c,
                hed__Applicant__c
                FROM hed__Application__c
                WHERE hed__Applicant__c != null
                WITH SYSTEM_MODE
                LIMIT 1
            ];
            for(hed__Application__c app : applicationsToUpdate) {
                app.Is_Agent_Assisted__c = true;
                app.Is_International_Applicant__c = true;
                app.Is_Personal_Illness_Disability_Applicant__c = true;
                app.Is_Elite_Athlete_Applicant__c = true;
                app.Is_Education_Disruption_Applicant__c = true;
                app.Is_First_In_Family_Applicant__c = true;
                app.Is_Financial_Hardship_Applicant__c = true;
                app.Agency_Name__c = 'Agency Name';
                app.Agency_Country__c = 'Agency Country';
                app.Agency_Email__c = 'agency@email.test';
            }
            Test.startTest();
            ApplicationsDAO.newInstance().updateRecords(applicationsToUpdate, false, AccessLevel.SYSTEM_MODE);
            Contact updatedContact = [
                SELECT Id, Is_Agent_Assisted__c, 
                Is_International_Applicant__c, 
                Personal_Illness_Disability_Applicant__c,
                Elite_Athlete_Applicant__c,
                Education_Disruption_Applicant__c,
                First_In_Family_Applicant__c,
                Financial_Hardship_Applicant__c,
                Agency_Name__c,
                Agency_Country__c,
                Agency_Email__c
                FROM Contact
                WHERE Id = :applicationsToUpdate[0].hed__Applicant__c
                WITH SYSTEM_MODE
                LIMIT 1
            ];
            Test.stopTest();
            System.assert(applicationsToUpdate[0].Is_Agent_Assisted__c == updatedContact.Is_Agent_Assisted__c, 'Is_Agent_Assisted__c not updated correctly.');
            System.assert(applicationsToUpdate[0].Is_International_Applicant__c == updatedContact.Is_International_Applicant__c, 'Is_International_Applicant__c not updated correctly.');
            System.assert(applicationsToUpdate[0].Is_Personal_Illness_Disability_Applicant__c == updatedContact.Personal_Illness_Disability_Applicant__c, 'Personal_Illness_Disability_Applicant__c not updated correctly.');
            System.assert(applicationsToUpdate[0].Is_Elite_Athlete_Applicant__c == updatedContact.Elite_Athlete_Applicant__c, 'Elite_Athlete_Applicant__c not updated correctly.');
            System.assert(applicationsToUpdate[0].Is_Education_Disruption_Applicant__c == updatedContact.Education_Disruption_Applicant__c, 'Education_Disruption_Applicant__c not updated correctly.');
            System.assert(applicationsToUpdate[0].Is_First_In_Family_Applicant__c == updatedContact.First_In_Family_Applicant__c, 'First_In_Family_Applicant__c not updated correctly.');
            System.assert(applicationsToUpdate[0].Is_Financial_Hardship_Applicant__c == updatedContact.Financial_Hardship_Applicant__c, 'Financial_Hardship_Applicant__c not updated correctly.');
            System.assert(applicationsToUpdate[0].Agency_Name__c == updatedContact.Agency_Name__c, 'Agency_Name__c not updated correctly.');
            System.assert(applicationsToUpdate[0].Agency_Country__c == updatedContact.Agency_Country__c, 'Agency_Country__c not updated correctly.');
            System.assert(applicationsToUpdate[0].Agency_Email__c == updatedContact.Agency_Email__c, 'Agency_Email__c not updated correctly.');
        }
    }

    @isTest
    private static void testUpdateContactWhenQTACAppIsInactive(){
        System.runAs(TestDataFactory.getESBIntegrationUser()) {
            Id contactId = ContactsDAO.newInstance().getPersonContactsWithLimit(1).iterator().next()?.Id;                
            List<hed__Application__c> applicationToUpdate = ApplicationsDAO.newInstance().getApplicationsByContactIds(new Set<Id>{contactId},'USER_MODE');   
            for(hed__Application__c app : applicationToUpdate){
                app.RecordTypeId = ApplicationsDAO.QTAC_RECTYPE_ID;
                app.Is_Active__c = false;
            }
            Test.startTest();
            ApplicationsDAO.newInstance().updateRecords(applicationToUpdate, false, AccessLevel.SYSTEM_MODE);
            List<Contact> contactUpdated = ContactsDAO.newInstance().getPersonContactsBySetIds(new Set<Id>{contactId}, AccessLevel.USER_MODE);
            Test.stopTest();
            System.assert(contactUpdated[0].HasOptedOutOfEmail == true, 'HasOptedOutOfEmail should be updated to true.');
            System.assert(contactUpdated[0].HasOptedOutOfEmail == true, 'Learner_Email_Opt_Out__c should be updated to true.');
            System.assert(contactUpdated[0].Staff_Email_Opt_Out__c == true, 'Staff_Email_Opt_Out__c should be updated to true.');
            System.assert(contactUpdated[0].Work_Email_Opt_Out__c == true, 'Work_Email_Opt_Out__c should be updated to true.');
            System.assert(contactUpdated[0].Work_SMS_Opt_Out__c == true, 'Work_SMS_Opt_Out__c should be updated to true.');
            System.assert(contactUpdated[0].hed__SMS_Opt_Out__c == true, 'hed__SMS_Opt_Out__c should be updated to true.');
            System.assert(contactUpdated[0].DoNotCall == true, 'DoNotCall should be updated to true.');
            System.assert(contactUpdated[0].Sync_to_MC__c == false, 'Sync_to_MC__c should be updated to false.');
            System.assert(contactUpdated[0].Do_Not_Sync_To_MC_Override__c == false, 'Do_Not_Sync_To_MC_Override__c should be updated to false.');
            System.assert(contactUpdated[0].Dont_Market_Reason__c == 'QTAC Application QUT preferences withdrawn', 'Dont_Market_Reason__c does not have the correct value.');
        }
    }
    
    private static List<hed__Application__c> createTestApplicationRecords(List<Contact> conList, String applicationStatus,String recordType) {
        List<hed__Application__c> newApplications = new List<hed__Application__c>();
        for (Contact con: conList) {
            newApplications.add(
                new hed__Application__c(
                    FirstName__c = 'Test First' + FIRSTNAME,
                    LastName__c = 'Test Last' + LASTNAME,
                    BirthDate__c = Date.valueOf(BIRTHDAY),
                    Email__c = 'workTest' + EMAIL,
                    Application_Status__c = applicationStatus,
                    hed__Applicant__c = con.Id,
                    RecordTypeId = recordType
    
                )
            );
        }
        return newApplications;
    }
    
    private static List<Contact> createTestContactRecords(
        Integer startAtCount,
        Integer endBeforeCount
    ) {
        List<Contact> newContacts = new List<Contact>();
        for (Integer i = startAtCount; i < endBeforeCount; i++) {
            newContacts.add(
                new Contact(
                    FirstName = FIRSTNAME + i,
                    LastName = i + LASTNAME,
                    BirthDate = Date.valueOf(BIRTHDAY),
                    Email = i + EMAIL,
                    QUT_Learner_Email__c = 'learner' + i + EMAIL,
                    QUT_Staff_Email__c = 'staff' + i + EMAIL,
                    Work_Email__c = 'work' + i + EMAIL,
                    hed__Preferred_Email__c = 'Alternate Email',
                    hed__AlternateEmail__c = i + EMAIL,
                    RecordTypeId = ContactsDAO.PERSON_RECORDTYPE_ID 
                )
            );
        }
        return newContacts;
    }

}