src/core-crm/objects/Application_Preference__c/Application_Preference__c.object-meta.xml
<CustomObject>
    <label>Application Preference</label>
    <nameField>
        <displayFormat>A-{000000000}</displayFormat>
        <label>Preference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Application_Preference__c/fields/Is_Current_Preference__c.field-meta.xml
<CustomField>
    <fullName>Is_Current_Preference__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The Preference being currently processed for admission</description>
    <label>Is Current Preference</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Application_Preference__c/fields/Preference_Number__c.field-meta.xml
<CustomField>
    <fullName>Preference_Number__c</fullName>
    <description>The Preference Order assigned to the Program by applicant</description>
    <label>Preference Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Application_Preference__c/fields/Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Name__c</fullName>
    <description>The Name given to the Course</description>
    <label>Program Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Application_Preference__c/recordTypes/QTAC.recordType-meta.xml
<RecordType>
    <fullName>QTAC</fullName>
    <active>true</active>
    <label>QTAC</label>
</RecordType>

src/core-crm/objects/hed__Application__c/hed__Application__c.object-meta.xml
<CustomObject>
    <description>Stores information about a student&apos;s application to an educational institution or program.</description>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Application__c/recordTypes/QTAC.recordType-meta.xml
<RecordType>
    <fullName>QTAC</fullName>
    <active>true</active>
    <label>QTAC</label>
</RecordType>

src/core-crm/classes/ApplicationPreferenceTriggerHandlerTest.cls
/**
 * @description Test Class for ApplicationPreferenceTriggerHandler
 *
 * @see ApplicationPreferenceTriggerHandler
 *
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary                                   |
      |--------------------------------|-----------------------|------------------------|--------------------------------------------------|
      | julie.jane.alegre              | August 21, 2023       | DEPP-6252              | Created file                                     |
 */
@isTest
private class ApplicationPreferenceTriggerHandlerTest {
    
    @testSetup
    static void testSetup() {
        Test.startTest();
        TestDataFactoryUser.generateUserQUTESB();
        Test.stopTest();
        System.runAs(TestDataFactoryUser.selectUserQUTESB) {

            List<Contact> contactList = TestDataFactory.createTestContactRecords(1);
            ContactsDAO.newInstance().insertRecords(contactList, false, AccessLevel.USER_MODE);

            Integer numOfPrefRec = 2;
            List<hed__Application__c> qtacApplicationList = TestDataFactory.createApplicationRecords(contactList[0].Id, ApplicationsDAO.QTAC_RECTYPE_ID, 1);
            ApplicationsDAO.newInstance().insertRecords(qtacApplicationList, false, AccessLevel.USER_MODE);
            List<Application_Preference__c> qtacAppPrefList = TestDataFactory.createApplicationPreferenceRecords(qtacApplicationList[0].Id, ApplicationPreferencesDAO.QTAC_RECTYPE_ID, numOfPrefRec);
            ApplicationPreferencesDAO.newInstance().insertRecords(qtacAppPrefList, false, AccessLevel.USER_MODE);

        }
    }

    @isTest
    private static void insertTest() {
        System.runAs(TestDataFactoryUser.selectUserQUTESB) {
            List<hed__Application__c> applicationList = [SELECT Id, RecordTypeId FROM hed__Application__c WHERE RecordTypeId =: ApplicationsDAO.QTAC_RECTYPE_ID WITH USER_MODE LIMIT 1];
            Test.startTest();
            List<Application_Preference__c> qtacAppPrefList = TestDataFactory.createApplicationPreferenceRecords(applicationList[0].Id, ApplicationPreferencesDAO.QTAC_RECTYPE_ID, 1);
            for(Application_Preference__c ap : qtacAppPrefList){
                ap.Program_Name__c = 'QTAC App Pref';
                ap.Preference_Number__c = 1;
            }
            ApplicationPreferencesDAO.newInstance().insertRecords(qtacAppPrefList, false, AccessLevel.USER_MODE);
            Test.stopTest();

            List<Application_Preference__c> updatedAppPrefList = [SELECT Id, Is_Current_Preference__c FROM Application_Preference__c WHERE Program_Name__c = 'QTAC App Pref' WITH USER_MODE LIMIT 1];
            System.assert(updatedAppPrefList[0].Is_Current_Preference__c, 'Is current preference field must be true.');
        }
    }

    @isTest
    private static void updateTest() {
        System.runAs(TestDataFactoryUser.selectUserQUTESB) {
            Test.startTest();
            List<Application_Preference__c> appPrefListToUpdate = new List<Application_Preference__c>();
            List<Application_Preference__c> appPrefList = [SELECT Id, Preference_Number__c, Program_Name__c, Is_Current_Preference__c FROM Application_Preference__c WHERE Program_Name__c = 'App Pref 1' WITH USER_MODE LIMIT 1];    
            for(Application_Preference__c ap : appPrefList){
                ap.Preference_Number__c = 5;
                appPrefListToUpdate.add(ap);
            }
            ApplicationPreferencesDAO.newInstance().updateRecords(appPrefListToUpdate, false, AccessLevel.USER_MODE);
            
            List<Application_Preference__c> appPrefToAssertList = [SELECT Id, Program_Name__c, Preference_Number__c, Is_Current_Preference__c FROM Application_Preference__c WHERE Program_Name__c = 'App Pref 2' WITH USER_MODE LIMIT 1];
            Test.stopTest();
            System.assert(appPrefToAssertList[0].Is_Current_Preference__c, 'Is current preference field must be true.');
        }
    }

}