src/core-crm/objects/Engagement_List_Criteria__c/Engagement_List_Criteria__c.object-meta.xml
<CustomObject>
    <description>Contains the entry or exit criteria or ad hoc import information for an engagement list configuration.</description>
    <label>Engagement List Criteria</label>
    <nameField>
        <label>Engagement List Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement List Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/Engagement_List_Criteria__c/fields/Course_Grade__c.field-meta.xml
<CustomField>
    <fullName>Course_Grade__c</fullName>
    <description>The course grade used to filter for criteria</description>
    <label>Course Grade</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

src/core-crm/classes/ELCCourseConnectionParser.cls
/**
 * @description Class to be used in parsing Engagement_List_Criteria__c to Course Connection criteria
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary                                              |
      |--------------------------------|-----------------------|------------------------|-------------------------------------------------------------|
      | eccarius.munoz                 | May 2, 2024           | DEPP-8041              | Created file                                                |
*/
public with sharing class ELCCourseConnectionParser {

    private Engagement_List_Criteria__c engagementListCriteria;
    private Date executionDate;

    private CourseConnectionsDAO.Criteria courseConnectionCriteria;

    public ELCCourseConnectionParser(Engagement_List_Criteria__c engagementListCriteria, Date executionDate) {
        this.engagementListCriteria = engagementListCriteria;
        this.executionDate = executionDate;
        parse();
    }

    private void parse() {
        courseConnectionCriteria = processCourseConnectionCourseGrade(engagementListCriteria, courseConnectionCriteria);
        courseConnectionCriteria = applyCourseConnectionHiddenCriteria(courseConnectionCriteria);
    }

    private CourseConnectionsDAO.Criteria processCourseConnectionCourseGrade(Engagement_List_Criteria__c engagementListCriteria, CourseConnectionsDAO.Criteria courseGradeCriteria) {
        if (engagementListCriteria.Course_Grade__c != null) {
            if (courseGradeCriteria == null) {
                courseGradeCriteria = new CourseConnectionsDAO.Criteria();
            }
            courseGradeCriteria.courseGrade = engagementListCriteria.Course_Grade__c;
        }
        return courseGradeCriteria;
    }

    private CourseConnectionsDAO.Criteria applyCourseConnectionHiddenCriteria(CourseConnectionsDAO.Criteria courseConnectionCriteria) {
        if (courseConnectionCriteria == null) {
            courseConnectionCriteria = new CourseConnectionsDAO.Criteria();
        }
        courseConnectionCriteria.status = CourseConnectionsDAO.ENROLLMENT_STATUS_FOR_OUTREACH;

        return courseConnectionCriteria;
    }

    public CourseConnectionsDAO.Criteria getCourseConnectionCriteria() {
        return courseConnectionCriteria;
    }
}