src/core-crm/objects/Engagement_List_Criteria__c/Engagement_List_Criteria__c.object-meta.xml
<CustomObject>
    <description>Contains the entry or exit criteria or ad hoc import information for an engagement list configuration.</description>
    <label>Engagement List Criteria</label>
    <nameField>
        <label>Engagement List Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement List Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/Engagement_List_Criteria__c/fields/Citizenship_Status__c.field-meta.xml
<CustomField>
    <fullName>Citizenship_Status__c</fullName>
    <description>Citizenship status to filter contact for criteria</description>
    <label>Citizenship Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Citizenship_Status</valueSetName>
    </valueSet>
</CustomField>

src/core-crm/globalValueSets/Citizenship_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Domestic</fullName>
    </customValue>
    <customValue>
        <fullName>International</fullName>
    </customValue>
    <masterLabel>Citizenship Status</masterLabel>
</GlobalValueSet>

src/core-crm/classes/ELCContactParserTest.cls
/**
 * @description Test class for ELCContactParser
 * @ELCContactParser
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | eccarius.munoz                 | May 2, 2024           | DEPP-7528              | Created file                 |
 */
@isTest
public with sharing class ELCContactParserTest {
    
    @TestSetup
    static void setupMethod(){
        TestDataFactory.generateTestUsers(new List<String>{ 'QUT_ESB' });
    }

    @isTest
    static void parseContactCitizenshipStatusTest() {
        System.runAs(TestDataFactory.getESBIntegrationUser()) {

            Test.startTest();
            String citizenshipStatus = ContactsDAO.CITIZENSHIP_STATUS_INTERNATIONAL;
            Date executionDate = Date.today();
            Engagement_List_Criteria__c engagementListCriteria = new Engagement_List_Criteria__c();
            engagementListCriteria.Citizenship_Status__c = citizenshipStatus;

            ELCContactParser parser = new ELCContactParser(engagementListCriteria, executionDate);
            Test.stopTest();

            System.assertEquals(parser.getContactCriteria().getCitizenshipStatus(), citizenshipStatus, 'Incorrect Citizenship Status.');

        }
    }

    @isTest
    static void parseContactHiddenCriteriaTest() {
        System.runAs(TestDataFactory.getESBIntegrationUser()) {

            Test.startTest();
            Date executionDate = Date.today();
            Engagement_List_Criteria__c engagementListCriteria = new Engagement_List_Criteria__c();
            String citizenshipStatus = ContactsDAO.CITIZENSHIP_STATUS_INTERNATIONAL;

            ELCContactParser parser = new ELCContactParser(engagementListCriteria, executionDate);
            Test.stopTest();

            System.assertEquals(parser.getContactCriteria().getRecordType(), ContactsDAO.PERSON_RECORDTYPE , 'Incorrect Contact record type'); 
            System.assertEquals(parser.getContactCriteria().getIsQUTStudent(), true, 'Contact is not set as QUT student');

        }
    }
}