src/core-crm/objects/Engagement_List_Criteria__c/Engagement_List_Criteria__c.object-meta.xml
<CustomObject>
    <description>Contains the entry or exit criteria or ad hoc import information for an engagement list configuration.</description>
    <label>Engagement List Criteria</label>
    <nameField>
        <label>Engagement List Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement List Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/Engagement_List_Criteria__c/fields/Academic_Status__c.field-meta.xml
<CustomField>
    <fullName>Academic_Status__c</fullName>
    <description>The academic status of the student to include in the criteria</description>
    <label>Academic Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Academic_Status</valueSetName>
    </valueSet>
</CustomField>

src/core-crm/objects/Engagement_List_Criteria__c/fields/Category_Type__c.field-meta.xml
<CustomField>
    <fullName>Category_Type__c</fullName>
    <description>The setting to filter by the category of the program that student is enrolled in</description>
    <label>Category Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Graduate Certificate</fullName>
            </value>
            <value>
                <fullName>Graduate Diploma - Existing Area</fullName>
            </value>
            <value>
                <fullName>Graduate Diploma - New Area</fullName>
            </value>
            <value>
                <fullName>Masters by Coursework - Double Degree</fullName>
            </value>
            <value>
                <fullName>Masters by Coursework - Single</fullName>
            </value>
            <value>
                <fullName>Masters by Research</fullName>
            </value>
            <value>
                <fullName>Bachelor Honours - Graduate Entry</fullName>
            </value>
            <value>
                <fullName>Bachelor Honours Degree</fullName>
            </value>
            <value>
                <fullName>Bachelor Honours/Masters by Coursework Double Degree</fullName>
            </value>
            <value>
                <fullName>Bachelor Honours/Pass Double Degree</fullName>
            </value>
            <value>
                <fullName>Bachelor Pass Degree - Graduate Entry</fullName>
            </value>
            <value>
                <fullName>Bachelor Pass Double Degree</fullName>
            </value>
            <value>
                <fullName>Bachelor Pass Single Degree</fullName>
            </value>
            <value>
                <fullName>Bachelor Pass/Masters by Coursework Double Degree</fullName>
            </value>
            <value>
                <fullName>Undergraduate Certificate</fullName>
            </value>
            <value>
                <fullName>Associate Degree</fullName>
            </value>
            <value>
                <fullName>Certificate and University Certificate</fullName>
            </value>
            <value>
                <fullName>Diploma and University Diploma</fullName>
            </value>
            <value>
                <fullName>Advanced Dip (AQF Term)/Diploma (Pre-AQF Term) (Hist Only)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField> 

src/core-crm/objects/Engagement_List_Criteria__c/fields/Key_Date__c.field-meta.xml
<CustomField>
    <fullName>Key_Date__c</fullName>
    <description>The name of the key date field used to offset from to define a time period</description>
    <label>Key Date</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enrollment Date</fullName>
            </value>
            <value>
                <fullName>Leave Of Absence End Date</fullName>
            </value>
            <value>
                <fullName>Completed Cadence Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Engagement_List_Criteria__c/fields/Key_Date_Offset_Lower_Boundary__c.field-meta.xml
<CustomField>
    <fullName>Key_Date_Offset_Lower_Boundary__c</fullName>
    <description>The number of days to offset from key date field. Positive numbers indicate days after while the negative indicate days prior to date in Key date field.</description>
    <label>Key Date Offset Lower Boundary</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Engagement_List_Criteria__c/fields/Key_Date_Offset_Upper_Boundary__c.field-meta.xml
<CustomField>
    <fullName>Key_Date_Offset_Upper_Boundary__c</fullName>
    <description>The number of days to offset from key date field. Positive numbers indicate days after while the negative indicate days prior to date in Key date field.</description>
    <label>Key Date Offset Upper Boundary</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Engagement_List_Criteria__c/fields/Previous_Academic_Status__c.field-meta.xml
<CustomField>
    <fullName>Previous_Academic_Status__c</fullName>
    <description>The previous academic status of the student to include in the criteria</description>
    <label>Previous Academic Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Academic_Status</valueSetName>
    </valueSet>
</CustomField>

src/core-crm/globalValueSets/Academic_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Excluded</fullName>
    </customValue>
    <customValue>
        <fullName>Under consideration</fullName>
    </customValue>
    <customValue>
        <fullName>Intern&apos;l Exclusion</fullName>
    </customValue>
    <customValue>
        <fullName>Conditional</fullName>
    </customValue>
    <customValue>
        <fullName>Good Standing</fullName>
    </customValue>
    <customValue>
        <fullName>Showcause</fullName>
    </customValue>
    <customValue>
        <fullName>Probation</fullName>
    </customValue>
    <customValue>
        <fullName>At Risk</fullName>
    </customValue>
    <customValue>
        <fullName>Probation Conversion</fullName>
    </customValue>
    <customValue>
        <fullName>Held Show cause</fullName>
    </customValue>
    <customValue>
        <fullName>Intern&apos;l Ext Appeal</fullName>
    </customValue>
    <description>The student’s current academic status</description>
    <masterLabel>Academic Status</masterLabel>
</GlobalValueSet>

src/core-crm/classes/ELCProgramEnrollmentParserTest.cls
/**
 * @description Test class for ELCProgramEnrollmentParser
 * @ELCProgramEnrollmentParser
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | eccarius.munoz                 | May 2, 2024           | DEPP-7528              | Created file                 |
 */
@isTest
public with sharing class ELCProgramEnrollmentParserTest {
    
    @TestSetup
    static void setupMethod(){
        TestDataFactoryUser.generateUserQUTESB();
    }

    @isTest
    static void parseProgramEnrollmentAcademicStatusTest() {
        System.runAs(TestDataFactoryUser.selectUserQUTESB) {            
            
            Test.startTest();
            String academicStatus = 'Showcause';
            Date executionDate = Date.today();
            Engagement_List_Criteria__c engagementListCriteria = new Engagement_List_Criteria__c();
            engagementListCriteria.Academic_Status__c = academicStatus;
            
            ELCProgramEnrollmentParser parser = new ELCProgramEnrollmentParser(engagementListCriteria, executionDate);
            Test.stopTest();

            System.assertEquals(parser.getProgramEnrollmentCriteria().getAcademicStatus(), academicStatus, 'Incorrect Academic Status');
            System.assertEquals(parser.getProgramEnrollmentCriteria().getEnrollmentStage(), ProgramEnrollmentsDAO.ENROLLMENT_STAGE_ADMITTED, 'Enrollment Stage should be set to Admitted');
            System.assertEquals(parser.getProgramEnrollmentCriteria().getEnrollmentStatus(), ELCProgramEnrollmentParser.ENROLLMENT_STATUS_FOR_OUTREACH, 'Enrollment Status should be set to Outreach');
        }
    }

    @isTest
    static void parseProgramEnrollmentPreviousAcademicStatusTest() {
        System.runAs(TestDataFactoryUser.selectUserQUTESB) {            
            
            Test.startTest();
            String academicStatus = 'Showcause';
            Date executionDate = Date.today();
            Engagement_List_Criteria__c engagementListCriteria = new Engagement_List_Criteria__c();
            engagementListCriteria.Previous_Academic_Status__c = academicStatus;
            
            ELCProgramEnrollmentParser parser = new ELCProgramEnrollmentParser(engagementListCriteria, executionDate);
            Test.stopTest();

            System.assertEquals(parser.getProgramEnrollmentCriteria().getPreviousAcademicStatus(), academicStatus, 'Incorrect Previous Academic Status');
            System.assertEquals(parser.getProgramEnrollmentCriteria().getEnrollmentStage(), ProgramEnrollmentsDAO.ENROLLMENT_STAGE_ADMITTED, 'Enrollment Stage should be set to Admitted');
            System.assertEquals(parser.getProgramEnrollmentCriteria().getEnrollmentStatus(), ELCProgramEnrollmentParser.ENROLLMENT_STATUS_FOR_OUTREACH, 'Enrollment Status should be set to Outreach');
        }
    }

    @isTest
    static void parseProgramEnrollmentCategoryTypeTest() {
        System.runAs(TestDataFactoryUser.selectUserQUTESB) {

            Test.startTest();
            Date executionDate = Date.today();
            Engagement_List_Criteria__c engagementListCriteria = new Engagement_List_Criteria__c();
            engagementListCriteria.Category_Type__c = 'Graduate Certificate';

            ELCProgramEnrollmentParser parser = new ELCProgramEnrollmentParser(engagementListCriteria, executionDate);
            Test.stopTest();

            System.assertEquals(parser.getProgramEnrollmentCriteria().getCategoryType(), new List<String>{'Graduate Certificate'}, 'Incorrect Category Type');       
            System.assertEquals(parser.getProgramEnrollmentCriteria().getEnrollmentStage(), ProgramEnrollmentsDAO.ENROLLMENT_STAGE_ADMITTED, 'Enrollment Stage should be set to Admitted');
            System.assertEquals(parser.getProgramEnrollmentCriteria().getEnrollmentStatus(), ELCProgramEnrollmentParser.ENROLLMENT_STATUS_FOR_OUTREACH, 'Enrollment Status should be set to Outreach');
 
        }
    }

    @isTest
    static void parseNoProgramEnrollmentCriteriaTest() {
        System.runAs(TestDataFactoryUser.selectUserQUTESB) {

            Test.startTest();
            ELCProgramEnrollmentParser parser = new ELCProgramEnrollmentParser(new Engagement_List_Criteria__c(), Date.today());
            Test.stopTest();

            System.assert(parser.getProgramEnrollmentCriteria().isEmpty(), 'No Criteria should be parsed.'); 

        }
    }

    @isTest
    static void parseprocessKeyDateOffsetsTest() {
        System.runAs(TestDataFactoryUser.selectUserQUTESB) {
            Date executionDate = Date.today();
            Date execDateLower = executionDate.addDays(-1);
            Date execDateUpper = executionDate.addDays(-10);

            Test.startTest();
            Engagement_List_Criteria__c engagementListCriteria = new Engagement_List_Criteria__c();
            engagementListCriteria.Key_Date__c = 'Academic Status Date';
            engagementListCriteria.Key_Date_Offset_Lower_Boundary__c = 1;
            engagementListCriteria.Key_Date_Offset_Upper_Boundary__c = 10;

            ELCProgramEnrollmentParser parser = new ELCProgramEnrollmentParser(engagementListCriteria, executionDate);
            Test.stopTest();

            System.assertEquals(
                DateTime.newInstance(execDateLower.year(), execDateLower.month(), execDateLower.day()).format('YYYY-MM-dd'),
                DynamicQueryService.convertDatetoDateString(parser.getProgramEnrollmentCriteria().getAcademicStatusDateFrom()), 
                'Incorrect Key Date Offset Lower'
            );

            System.assertEquals(
                DateTime.newInstance(execDateUpper.year(), execDateUpper.month(), execDateUpper.day()).format('YYYY-MM-dd'),
                DynamicQueryService.convertDatetoDateString(parser.getProgramEnrollmentCriteria().getAcademicStatusDateTo()), 
                'Incorrect Key Date Offset Lower'
            );
        }
    }
}