src/core-crm/objects/Engagement_List_Criteria__c/Engagement_List_Criteria__c.object-meta.xml
<CustomObject>
    <description>Contains the entry or exit criteria or ad hoc import information for an engagement list configuration.</description>
    <label>Engagement List Criteria</label>
    <nameField>
        <label>Engagement List Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engagement List Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/Engagement_List_Criteria__c/recordTypes/Imported.recordType-meta.xml
<RecordType>
    <fullName>Imported</fullName>
    <active>true</active>
    <label>Imported</label>
</RecordType>

src/core-crm/objects/Engagement_List_Event__c/Engagement_List_Event__c.object-meta.xml
<CustomObject>
    <description>Contains a list of events that show the criteria in which a case was created based on the related Engagement List Criteria.</description>
    <label>Engagement List Event</label>
    <nameField>
        <displayFormat>ELE-{000000}</displayFormat>
        <label>Engagement List Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engagement List Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/Engagement_List_Event__c/fields/Engagement_List_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Engagement_List_Criteria__c</fullName>
    <description>The Engagement List Criteria that generated the event</description>
    <label>Engagement List Criteria</label>
    <referenceTo>Engagement_List_Criteria__c</referenceTo>
    <relationshipLabel>Engagement List Events</relationshipLabel>
    <relationshipName>Engagement_List_Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/core-crm/objects/Outreach_Case__e/Outreach_Case__e.object-meta.xml
<CustomObject>
    <label>Outreach Case Batch Complete</label>
    <pluralLabel>Outreach Case Batch Completes</pluralLabel>
</CustomObject>

src/core-crm/objects/Outreach_Case__e/fields/Existing_Outreach_Case_Ids__c.field-meta.xml
<CustomField>
    <fullName>Existing_Outreach_Case_Ids__c</fullName>
    <label>Existing Outreach Case Ids</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/core-crm/objects/Outreach_Case__e/fields/New_Outreach_Case_Ids__c.field-meta.xml
<CustomField>
    <fullName>New_Outreach_Case_Ids__c</fullName>
    <label>New Outreach Case Ids</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/core-crm/classes/AdhocImportOutreachCaseBatch.cls
/**
 * @description Batch Class for Manual Import of outreach cases based from qut students imported
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | eccarius.munoz                 | June 28, 2024         | DEPP-9499              | Created file                 |
 */
public with sharing class AdhocImportOutreachCaseBatch implements Database.Batchable<sObject>, Database.Stateful {

    private List<String> newOutreachCaseIdsString = new List<String>();
    private List<String> existingOutreachCaseIdsString = new List<String>();

    private List<String> qutStudentIds;
    private Engagement_List_Criteria__c engagementCriteria;
    private Id configurationId;

    public AdhocImportOutreachCaseBatch(List<String> qutStudentIds, Engagement_List_Criteria__c engagementCriteria, Id configurationId) {
        this.qutStudentIds = qutStudentIds;
        this.engagementCriteria = engagementCriteria;
        this.configurationId = configurationId;
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {  
        return ContactsDAO.newInstance().getQueryLocatorContactByStudentId(qutStudentIds, AccessLevel.USER_MODE);
    } 

    public void execute(Database.BatchableContext bc, List<Contact> contacts){
        try {
            Date executionDate = Date.today();
            ELCParser parser = new ELCParser(engagementCriteria, executionDate);
            List<ELECandidateIngredient> ingredientList = new List<ELECandidateIngredient>();
            Map<List<ELECandidateIngredient>, Contact> ingredientByContactMap = new Map<List<ELECandidateIngredient>, Contact>();
            for(Contact con : contacts){
                ELECandidateIngredient ingredient = new ELECandidateIngredient();
                ingredient.setELCParser(parser);
                ingredient.setContact(con);
                ingredientList.add(ingredient);
                ingredientByContactMap.put(ingredientList, con);
            }

            Map<Id, List<Engagement_List_Event__c>> eventsByContactMap = new Map<Id, List<Engagement_List_Event__c>>();
            for(ELECandidateIngredient ingredient : ingredientList){
                ELECandidateGenerator generator = new ELECandidateGenerator();
                List<Engagement_List_Event__c> events = generator.generate(ingredient);
                eventsByContactMap.put(ingredient.getContact().Id, events);
            }
            
            ELECandidateProcessor processor = new ELECandidateProcessor();
            List<ELECandidateProcessResult> processResult = processor.process(eventsByContactMap, engagementCriteria);
            for (ELECandidateProcessResult result : processResult){
                if(result.getResult() == ELECandidateProcessResult.Outcome.CASE_CREATED){
                    newOutreachCaseIdsString.add(result.getCase().Id);
                }else if(result.getResult() == ELECandidateProcessResult.Outcome.EVENT_CREATED){
                    existingOutreachCaseIdsString.add(result.getCase().Id);
                }
            }
            
        } catch (Exception e) {
            Logger.error(
                'Exception caught in method finish in class AdhocImportOutreachCaseBatch.'
            )
            .setExceptionDetails(e);
        } finally {
            if(Logger.getBufferSize() > 0) {
                Logger.saveLog();
            }
        }
    }

    public void finish(Database.BatchableContext bc) {
        
        String newCaseIdsString = String.join(newOutreachCaseIdsString, ','); 
        String existingCaseIdsString = String.join(existingOutreachCaseIdsString, ','); 

        List<Outreach_Case__e> outreachCaseEvents = new List<Outreach_Case__e>();
        outreachCaseEvents.add(
            new Outreach_Case__e(
                Existing_Outreach_Case_Ids__c = existingCaseIdsString,
                New_Outreach_Case_Ids__c = newCaseIdsString
            )
        );
        
        if (!outreachCaseEvents.isEmpty()) {
            try {
                EventBus.publish(outreachCaseEvents);
            } catch (Exception e) {
                // prettier-ignore
                NebulaLoggerService.logExceptionDetails('Exception caught in AdhocImportOutreachCaseBatch', e);
            }
        }
    }
}