src/core-crm/objects/hed__Application__c/hed__Application__c.object-meta.xml
<CustomObject>
    <description>Stores information about a student&apos;s application to an educational institution or program.</description>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Application__c/fields/Calculated_Intake_Date__c.field-meta.xml
<CustomField>
    <fullName>Calculated_Intake_Date__c</fullName>
    <description>Calculated date as the latest intake date based on logic corresponding to the application record type.</description>
    <label>Calculated Intake Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/hed__Application__c/fields/hed__Applicant__c.field-meta.xml
<CustomField>
    <fullName>hed__Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Contact applying to the institution or program.</description>
    <inlineHelpText>The Contact applying to the institution or program.</inlineHelpText>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Applications (Applicant)</relationshipLabel>
    <relationshipName>Applications_Applicant</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Application__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Pre submission applications that do not have sufficient details for contact matching</description>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/classes/ApplicationsDAOMock.cls
/**
 * @description Mock DAO Class for Application Object
 *
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary                                                      |
 *    |--------------------------------|-----------------------|------------------------|---------------------------------------------------------------------|
 *    | mark.j.mahilum                 | June 19, 2023         | DEPP-5846              | Created File                                                        |
 *    | mark.j.mahilum                 | July 03, 2023         | DEPP-5961              | Added method getApplicationsByLeadIds                               |
 *    | mark.j.mahilum                 | July 14, 2023         | DEPP-5799              | Added method getApplicationsByContactIds                            |
 *    | mark.j.mahilum                 | Aug 31, 2023          | DEPP-6455              | Added method getApplicationsActiveApplicants                        |
 *    | mark.j.mahilum                 | Oct 11, 2023          | DEPP-6852              | Added method getApplicationsByLeadOrContaIds                        |
 *    | sebastianne.k.trias            | March 28, 2024        | DEPP-8382              | Added method queryApplicationsByPastIntakeDateAndActiveApplicants   |
 */
@isTest
public inherited sharing class ApplicationsDAOMock extends DmlBaseMock implements IApplicationsDAO {
    
    public Map<Id, hed__Application__c> applicationMap;

    public ApplicationsDAOMock() {
        super(new Map<Id, hed__Application__c>(), Schema.hed__Application__c.SObjectType);
        this.applicationMap = (Map<Id, hed__Application__c>) super.records;
    }

    public Schema.SObjectType getSObjectType() {
        return hed__Application__c.SObjectType;
    }

    public List<hed__Application__c> getApplicationsBySetIds(
        Set<Id> applicationIds,
        AccessLevel accessLevel
    ) {
        List<hed__Application__c> applicationList = new List<hed__Application__c>();

        for (hed__Application__c record : applicationMap.values()) {
            if (applicationIds.contains(record.Id)) {
                applicationList.add(record);
            }
        }

        return applicationList;
    }

    public List<hed__Application__c> getApplicationsByLeadIds(
        Set<Id> leadIds,
        String accessLevel
    ) {
        List<hed__Application__c> applicationList = new List<hed__Application__c>();

        for (hed__Application__c record : applicationMap.values()) {
            if (leadIds.contains(record.Lead__c)) {
                applicationList.add(record);
            }
        }

        return applicationList;
    }

    public List<hed__Application__c> getApplicationsByContactIds(
        Set<Id> contactIds,
        String accessLevel
    ) {
        List<hed__Application__c> applicationList = new List<hed__Application__c>();

        for (hed__Application__c record : applicationMap.values()) {
            if (contactIds.contains(record.hed__Applicant__c)) {
                applicationList.add(record);
            }
        }

        return applicationList;
    }

    public List<hed__Application__c> getQtacApplicationsWithQtacApplicantId(
        List<String> qtacApplicantId,
        String accessLevel
    ) {
        List<hed__Application__c> applicationList = new List<hed__Application__c>();

        for (hed__Application__c record : applicationMap.values()) {
            if (qtacApplicantId.contains(record.hed__Applicant__c)) {
                applicationList.add(record);
            }
        }

        return applicationList;
    }

    public List<hed__Application__c> getApplicationsActiveApplicants(
        Set<Id> contactIds,
        String accessLevel
    ) {
        List<hed__Application__c> applicationList = new List<hed__Application__c>();

        for (hed__Application__c record : applicationMap.values()) {
            if (contactIds.contains(record.hed__Applicant__c)) {
                applicationList.add(record);
            }
        }

        return applicationList;
    }

    public List<hed__Application__c> getApplicationsByLeadOrContactIds(
        Set<String> recordIds,
        Set<String> cadenceNames,
        String accessLevel
    ) {
        List<hed__Application__c> applicationList = new List<hed__Application__c>();

        for (hed__Application__c record : applicationMap.values()) {
            if (recordIds.contains(record.hed__Applicant__c) || recordIds.contains(record.Lead__c)) {
                applicationList.add(record);
            }
        }

        return applicationList;
    }

    public List<hed__Application__c> getAppsWithLatestCalculatedIntakeDateByApplicantIds(
        Set<Id> recordIds,
        String accessLevel
    ) {
        List<hed__Application__c> applicationList = new List<hed__Application__c>();

        for (hed__Application__c record : applicationMap.values()) {
            if (recordIds.contains(record.hed__Applicant__c) && record.Calculated_Intake_Date__c != null) {
                applicationList.add(record);
            }
        }

        return applicationList;
    }

    public Database.QueryLocator queryApplicationsByPastIntakeDateAndActiveApplicants(
        String accessLevel
    ) {
        return null;
    }

}