src/core-crm/objects/hed__Application__c/hed__Application__c.object-meta.xml
<CustomObject>
    <description>Stores information about a student&apos;s application to an educational institution or program.</description>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Application__c/fields/Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Application_Status__c</fullName>
    <description>The status given to the application by the application source.</description>
    <label>Application Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Application__c/fields/BirthDate__c.field-meta.xml
<CustomField>
    <fullName>BirthDate__c</fullName>
    <description>The applicant’s date of birth</description>
    <label>BirthDate</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/hed__Application__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>The applicant’s email address on application</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

src/core-crm/objects/hed__Application__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <description>The applicant’s first name</description>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/hed__Application__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <description>The applicant’s last name</description>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Lead/fields/Work_Email__c.field-meta.xml
<CustomField>
    <fullName>Work_Email__c</fullName>
    <inlineHelpText>This field captures the work email of the contact.</inlineHelpText>
    <label>Work Email</label>
    <type>Email</type>
</CustomField>

src/core-crm/objects/Nurture_Track_Configuration__c/Nurture_Track_Configuration__c.object-meta.xml
<CustomObject>
    <label>Nurture Track Configuration</label>
    <nameField>
        <displayFormat>NTC-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Nurture Track Configuration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Nurture_Track_Configuration__c/fields/Cadence_Name__c.field-meta.xml
<CustomField>
    <fullName>Cadence_Name__c</fullName>
    <description>The Name of the Cadence the Configuration is for</description>
    <label>Cadence Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Nurture_Track_Configuration__c/fields/Lead_Score_Threshold__c.field-meta.xml
<CustomField>
    <fullName>Lead_Score_Threshold__c</fullName>
    <description>The Lead Score Threshold for inclusion in the Track

Note: This value needs to be replicated to all cadences in the track</description>
    <label>Lead Score Threshold</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Nurture_Track_Configuration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Cadence Status is used to activate or deactivate the cadence</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/classes/NurturingTrackLeadServiceTest.cls
/**
 * @description Test class for NurturingTrackLeadService
 * 
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | mark.j.mahilum       	       | July 25, 2023         | DEPP-6105              | Created file                 | 
 */
@isTest
public with sharing class NurturingTrackLeadServiceTest {
    private static final String FIRSTNAME = 'TestfirstName';
    private static final String LASTNAME = 'Testlastname';
    private static final String EMAIL = 'testmail@mail.test';
    private static final String BIRTHDAY = '2000-06-28';
    private static Integer recordsCount = 20;
    
    @testSetup
    static void testSetup() {
        TestDataFactory.generateTestUsers(new List<String>{ 'QUT_Program_Administrator' });
        System.runAs(TestDataFactory.getProgramAdminUser()) {            
            List<Lead> newLeads = createTestLeadRecords(0, 3);    
            LeadsDAO.newInstance().insertRecords(newLeads, false, AccessLevel.SYSTEM_MODE);
            
            ApplicationsDAO.newInstance().insertRecords(
                createTestApplicationStudyLinkRecords(0, recordsCount,'New'),
                false,
                AccessLevel.SYSTEM_MODE
            );
            
            List<Nurture_Track_Configuration__c> nurtureList = new List<Nurture_Track_Configuration__c>();
            Nurture_Track_Configuration__c nurtureConfig = new Nurture_Track_Configuration__c();
            nurtureConfig.Cadence_Name__c = 'TEST 1';
            nurtureConfig.Lead_Score_Threshold__c = 3;
            nurtureConfig.Status__c = 'Active';
            nurtureList.add(nurtureConfig);
            NurtureTrackConfigurationsDAO.newInstance().insertRecords(nurtureList, false, AccessLevel.SYSTEM_MODE);       
        }
    }

    @isTest
    private static void testNurturingTrackLeadServiceMethod() {
        System.runAs(TestDataFactory.getProgramAdminUser()) {
            
            Map<Id,Lead> leadToProcess = new Map<Id,Lead>();    
            List<Lead> leadList = [SELECT Id, Can_Nurture__c, Lead_Score__c, Calculated_Cadence__c FROM Lead LIMIT 1];
            for(Lead lead: leadList){
                leadToProcess.put(lead.Id,lead);
            }
            
            Test.startTest();       
            NurturingTrackLeadService.processLeadForEntryAndExit(leadToProcess);
            Test.stopTest();  
        }
    }
    
    private static List<hed__Application__c> createTestApplicationStudyLinkRecords(Integer startAtCount, Integer endBeforeCount, String applicationStatus) {
        List<hed__Application__c> newApplications = new List<hed__Application__c>();
        for (Integer i = startAtCount; i < endBeforeCount; i++) {
            newApplications.add(
                new hed__Application__c(
                    FirstName__c = FIRSTNAME + i,
                    LastName__c = i + LASTNAME,
                    BirthDate__c = Date.valueOf(BIRTHDAY),
                    Email__c = 'work' + i + EMAIL,
                    Application_Status__c = applicationStatus,
                    RecordTypeId = ApplicationsDAO.STUDYLINK_RECTYPE_ID
                )
            );
        }
        return newApplications;
    }
    
    private static List<Lead> createTestLeadRecords(Integer startAtCount, Integer endBeforeCount) {
        List<Lead> newLeads = new List<Lead>();
        for (Integer i = startAtCount; i < endBeforeCount; i++) {
            newLeads.add(
                new Lead(
                    FirstName = FIRSTNAME,
                    LastName = LASTNAME + i,
                    Email = i + EMAIL,
                    Can_Nurture__c = TRUE,
                    Calculated_Cadence__c = 'Test',
                    Work_Email__c = 'work' + i + EMAIL,
                    Company = 'Learner' + i
                )
            );
        }
        return newLeads;
    }

}