src/core-crm/objects/List_Contributor__c/List_Contributor__c.object-meta.xml
<CustomObject>
    <description>List Contributor contains information about the staff members who contributed to compiling a list of contacts.</description>
    <label>List Contributor</label>
    <nameField>
        <displayFormat>LC-{000000}</displayFormat>
        <label>List Contributor Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>List Contributors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/List_Contributor__c/fields/List_Contributor__c.field-meta.xml
<CustomField>
    <fullName>List_Contributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The DEP User who is contributing to the list.</description>
    <inlineHelpText>The DEP User who is contributing to the list.</inlineHelpText>
    <label>List Contributor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRoleId</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>notEqual</operation>
            <value>System Administrator</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>List_Contributors</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/List_Member__c/List_Member__c.object-meta.xml
<CustomObject>
    <description>List Member contains information about the Contacts who have been included in a Contact List and details about the staff member who contributed to compiling the list of contacts.</description>
    <label>List Member</label>
    <nameField>
        <displayFormat>LM-{0000000}</displayFormat>
        <label>List Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>List Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/List_Member__c/fields/List_Contributor__c.field-meta.xml
<CustomField>
    <fullName>List_Contributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>QUT staff member who included, or requested to include the Contact in the list.</description>
    <inlineHelpText>QUT staff member who included, or requested to include the Contact in the list.</inlineHelpText>
    <label>List Contributor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>List_Contributor__c.CreatedBy.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>List_Contributor__c</referenceTo>
    <relationshipLabel>List Members</relationshipLabel>
    <relationshipName>List_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/List_Member__c/fields/List_Member__c.field-meta.xml
<CustomField>
    <fullName>List_Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A Contact who has met the criteria to be included in the list.</description>
    <inlineHelpText>Contact who has met criteria for inclusion in the list.</inlineHelpText>
    <label>List Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>List Members</relationshipLabel>
    <relationshipName>List_Members</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/core-crm/classes/ListMemberImportModalCtrl.cls
/**
 * @description Controller Class for LWC listMemberImportModal
 * @see ../lwc/listMemberImportModal
 *
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary                                    |
      |--------------------------------|-----------------------|------------------------|---------------------------------------------------|
      | neil.s.h.lesidan               | Jan 23, 2024          | DEPP-7005              | Created file                                      |
 */
public with sharing class ListMemberImportModalCtrl {

    /**
     * @description Fetches Contact Object by Ids
     * @param ids Contact Ids
     * @return Records of List<Contact>
    */
    @AuraEnabled
    public static List<Contact> getContactById(String ids) {
        List<String> idList = ids.split(',');
        Set<Id> idSet = new Set<Id>();
        for (String idString : idList) {
            idSet.add((Id)idString.trim());
        }

        List<Contact> contacts = ContactsDAO.newInstance().getAlumniPersonContactsBySetIds(idSet, AccessLevel.USER_MODE);

        return contacts;
    }

    /**
     * @description Fetches the List Contributor Object by Ids
     * @param ids List Contributor Ids
     * @return Records of List<List_Contributor__c>
     */
    @AuraEnabled
    public static List<List_Contributor__c> getListContributorByIds(Id listId, String contributorIds) {
        List<String> idList = contributorIds.split(',');
        Set<Id> idSet = new Set<Id>();
        for (String idString : idList) {
            idSet.add((Id)idString.trim());
        }

        List<List_Contributor__c> listContributorRecord = ListContributorsDAO.newInstance().getRecordIdListContributorByListID(idSet, new Set<Id>{listId}, AccessLevel.USER_MODE);

        return listContributorRecord;
    }

    /**
     * @description bulk save list member
     * @param listId, record list members
     * @return Records success
    */
    @AuraEnabled
    public static Boolean bulkSaveListMember(List<List_Member__c> record) {
        ListMembersDAO.newInstance().insertRecords(record, false, AccessLevel.USER_MODE);
        return true;
    }
}