src/core-crm/objects/Designation__c/Designation__c.object-meta.xml
<CustomObject>
    <description>Designation stores the ‘Cause’ data that a donor can donate to as well as data relating to setting up a new donation cause and publishing the cause on the QUT website.</description>
    <label>Designation</label>
    <nameField>
        <label>Designation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Designations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Designation__c/fields/Activation_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Activation_End_Date__c</fullName>
    <description>The date the Designation stops being able to receive donations.</description>
    <inlineHelpText>The date the Designation stops being able to receive donations.</inlineHelpText>
    <label>Activation End Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Designation__c/fields/Public_Giving_Publish_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Public_Giving_Publish_End_Date__c</fullName>
    <description>The date from when the Designation should stop being published on the Giving Portal.</description>
    <inlineHelpText>The date from when the Designation should stop being published on the Giving Portal.</inlineHelpText>
    <label>Public Giving Publish End Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Designation__c/fields/Public_Giving_Publish_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Public_Giving_Publish_Start_Date__c</fullName>
    <description>The date from when the Designation should be published on the Giving Portal.</description>
    <inlineHelpText>The date from when the Designation should be published on the Giving Portal.</inlineHelpText>
    <label>Public Giving Publish Start Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Designation__c/fields/Ready_For_Publishing__c.field-meta.xml
<CustomField>
    <fullName>Ready_For_Publishing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the new Designation is ready to be published online.</description>
    <inlineHelpText>Indicates if the new Designation is ready to be published online.</inlineHelpText>
    <label>Ready For Publishing</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Designation__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>The stage the request is at in its lifecycle.</description>
    <inlineHelpText>The stage the request is at in its lifecycle.</inlineHelpText>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Define</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/classes/Designation_Stage_Update_Test.cls
/**
 * @description test class for Designation_Stage_Update Flow
 * 
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | roy.nino.s.regala              | March 15, 2024        | DEPP-8210              | Created file                 |
      | eugene.andrew.abuan            | March 19, 2024        | DEPP-8211              | Added Active Stage           | 

 */
@isTest
private class Designation_Stage_Update_Test {
    @testSetup
    static void setupData() {
        Test.startTest();
        TestDataFactory.generateTestUsers(new List<String>{ 'QUT_Donor_Engagement_Manager' });
        Test.stopTest();
    }

    @isTest
    private static void forPublishedBatchTest() {
        System.runAs(TestDataFactory.getDonorEngagementManager()) {
            List<Designation__c> designationList = TestDataFactory.createDesignationRecords(
                100
            );

            DesignationsDAO.newInstance()
                .insertRecords(designationList, false, AccessLevel.USER_MODE);

            for (Designation__c dc : designationList) {
                dc.Ready_For_Publishing__c = true;
                dc.Public_Giving_Publish_Start_Date__c = System.Today();
                dc.Public_Giving_Publish_End_Date__c = System.Today() + 1;
            }

            Test.startTest();
            DesignationsDAO.newInstance()
                .updateRecords(designationList, false, AccessLevel.USER_MODE);
            Test.stopTest();

            for (
                Designation__c dc : DesignationsDAO.newInstance()
                    .getDesignationsBySetRecordIds(
                        (new Map<Id, Designation__c>(designationList)).keySet(),
                        AccessLevel.USER_MODE
                    )
            ) {
                System.assertEquals(
                    DesignationsDAO.DC_PUBLISHED,
                    dc.Stage__c,
                    'Stage should be published'
                );
            }
        }
    }

    @isTest
    private static void forNotPublishedBatchTest() {
        System.runAs(TestDataFactory.getDonorEngagementManager()) {
            List<Designation__c> designationList = TestDataFactory.createDesignationRecords(
                100
            );

            DesignationsDAO.newInstance()
                .insertRecords(designationList, false, AccessLevel.USER_MODE);

            for (Designation__c dc : designationList) {
                dc.Stage__c = DesignationsDAO.DC_ARCHIVED;
                dc.Ready_For_Publishing__c = true;
                dc.Public_Giving_Publish_Start_Date__c = System.Today();
                dc.Public_Giving_Publish_End_Date__c = System.Today() + 1;
            }

            Test.startTest();
            DesignationsDAO.newInstance()
                .updateRecords(designationList, false, AccessLevel.USER_MODE);
            Test.stopTest();

            for (
                Designation__c dc : DesignationsDAO.newInstance()
                    .getDesignationsBySetRecordIds(
                        (new Map<Id, Designation__c>(designationList)).keySet(),
                        AccessLevel.USER_MODE
                    )
            ) {
                System.assertNotEquals(
                    DesignationsDAO.DC_PUBLISHED,
                    dc.Stage__c,
                    'Stage should be published'
                );
            }
        }
    }

    @isTest
    private static void forActiveBatchTest() {
        System.runAs(TestDataFactory.getDonorEngagementManager()) {
            List<Designation__c> designationList = TestDataFactory.createDesignationRecords(
                100
            );

            DesignationsDAO.newInstance()
                .insertRecords(designationList, false, AccessLevel.USER_MODE);

            for (Designation__c dc : designationList) {
                dc.Ready_For_Publishing__c = false;
                dc.Activation_End_Date__c = System.Today() + 1;
            }

            Test.startTest();
            DesignationsDAO.newInstance()
                .updateRecords(designationList, false, AccessLevel.USER_MODE);
            Test.stopTest();

            for (
                Designation__c dc : DesignationsDAO.newInstance()
                    .getDesignationsBySetRecordIds(
                        (new Map<Id, Designation__c>(designationList)).keySet(),
                        AccessLevel.USER_MODE
                    )
            ) {
                System.assertEquals(
                    DesignationsDAO.DC_ACTIVE,
                    dc.Stage__c,
                    'Stage should be Active'
                );
            }
        }
    }

    @isTest
    private static void forNotActiveBatchTest() {
        System.runAs(TestDataFactory.getDonorEngagementManager()) {
            List<Designation__c> designationList = TestDataFactory.createDesignationRecords(
                100
            );

            DesignationsDAO.newInstance()
                .insertRecords(designationList, false, AccessLevel.USER_MODE);

            for (Designation__c dc : designationList) {
                dc.Stage__c = DesignationsDAO.DC_ARCHIVED;
                dc.Ready_For_Publishing__c = false;
                dc.Activation_End_Date__c = System.Today() + 1;
            }

            Test.startTest();
            DesignationsDAO.newInstance()
                .updateRecords(designationList, false, AccessLevel.USER_MODE);
            Test.stopTest();

            for (
                Designation__c dc : DesignationsDAO.newInstance()
                    .getDesignationsBySetRecordIds(
                        (new Map<Id, Designation__c>(designationList)).keySet(),
                        AccessLevel.USER_MODE
                    )
            ) {
                System.assertNotEquals(
                    DesignationsDAO.DC_ACTIVE,
                    dc.Stage__c,
                    'Stage should not be Active'
                );
            }
        }
    }
}