src/core-crm/objects/Designation__c/Designation__c.object-meta.xml
<CustomObject>
    <description>Designation stores the ‘Cause’ data that a donor can donate to as well as data relating to setting up a new donation cause and publishing the cause on the QUT website.</description>
    <label>Designation</label>
    <nameField>
        <label>Designation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Designations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Designation__c/fields/Designation_Code__c.field-meta.xml
<CustomField>
    <fullName>Designation_Code__c</fullName>
    <description>The Designation code.</description>
    <inlineHelpText>The Designation code.</inlineHelpText>
    <label>Designation Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Designation__c/fields/Endowment_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Endowment_Account_Type__c</fullName>
    <description>Indicates whether the GL Account setup to receive funds from the Endowment is Perpetual or Non-Perpetual.</description>
    <inlineHelpText>Indicates whether the GL Account setup to receive funds from the Endowment is Perpetual or Non-Perpetual.</inlineHelpText>
    <label>Endowment Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Perpetual</fullName>
            </value>
            <value>
                <fullName>Non-Perpetual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Designation__c/recordTypes/Endowment.recordType-meta.xml
<RecordType>
    <fullName>Endowment</fullName>
    <active>true</active>
    <description>Create a Designation for an Endowment Fund.</description>
    <label>Endowment</label>
</RecordType>

src/core-crm/objects/Designation_Code_Auto_Number__c/Designation_Code_Auto_Number__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Designation Code Auto Number</label>
</CustomObject>

src/core-crm/objects/Designation_Code_Auto_Number__c/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Designation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Designation_Code_Auto_Number__c/fields/Endowment__c.field-meta.xml
<CustomField>
    <fullName>Endowment__c</fullName>
    <description>Designation Endowment Auto Number</description>
    <label>Endowment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Designation_Code_Auto_Number__c/fields/Giving_To_Cause__c.field-meta.xml
<CustomField>
    <fullName>Giving_To_Cause__c</fullName>
    <description>Designation Giving to Cause Auto Number</description>
    <label>Giving To Cause</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/core-crm/classes/DesignationTriggerHandlerTest.cls
/**
 * @description Test class for DesignationTriggerHandler.cls
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | eugene.andrew.abuan            | March 20, 2023        | DEPP-8200              | Created file                 |
      | eugene.andrew.abuan            | April 17, 2024        | DEPP-8340              | Added Designation Endowment  |

 */

@isTest
public with sharing class DesignationTriggerHandlerTest {
	@testSetup
    static void setup() {
        TestDataFactoryUser.generateUserAdvancementManager();
        Designation_Code_Auto_Number__c designationCodeAutoNum = DesignationCodeAutoNumbersDAO.newInstance().getOrganizationalDefaults();
        designationCodeAutoNum.Giving_To_Cause__c = 1;
        designationCodeAutoNum.Endowment__c = 1;

        DesignationCodeAutoNumbersDAO.newInstance().upsertRecords(
            new List<Designation_Code_Auto_Number__c>{designationCodeAutoNum}, 
            false, 
            AccessLevel.USER_MODE
            );
    }
    
    @isTest
    private static void createDesignationCodeGivingToCauseTest() {
        System.runAs(TestDataFactoryUser.selectUserAdvancementManager) {
            Test.startTest();
            List<Designation__c> designationList = TestDataFactory.createDesignationRecords(100, DesignationsDAO.GIVING_TO_CAUSE_RECTYPE_ID);

            DesignationsDAO.newInstance().insertRecords(designationList, false, AccessLevel.USER_MODE);

            Designation_Code_Auto_Number__c designationCodeAutoNum = DesignationCodeAutoNumbersDAO.newInstance().getOrganizationalDefaults();
            Test.stopTest();

            Integer count = 1;

            for (Designation__c dc : DesignationsDAO.newInstance().getDesignationsBySetRecordIds(
                        (new Map<Id, Designation__c>(designationList)).keySet(),AccessLevel.USER_MODE)
            ) {
                System.assert(String.isNotBlank(dc.Designation_Code__c), 'Blank ADVGC code on record.');
                System.assertEquals('ADVGC:' + String.valueOf(count).leftPad(5, '0'), dc.Designation_Code__c,'Incorrect ADVGC Code');
                count++;
            }
            System.assertEquals(101, designationCodeAutoNum.Giving_To_Cause__c, 'Incorrect latest ADVGC code auto-number value.');

        }
    }


    @isTest
    private static void createDesignationCodeEndowmentTest() {
        System.runAs(TestDataFactoryUser.selectUserAdvancementManager) {
            Test.startTest();
            List<Designation__c> designationList = TestDataFactory.createDesignationRecords(100, DesignationsDAO.ENDOWNMENT_RECTYPE_ID);
            for(Designation__c d : designationList){
                d.Endowment_Account_Type__c = DesignationsDAO.ENDOWMENT_ACCOUNT_TYPE_PERPETUAL;
            }
            DesignationsDAO.newInstance().insertRecords(designationList, false, AccessLevel.USER_MODE);

            Designation_Code_Auto_Number__c designationCodeAutoNum = DesignationCodeAutoNumbersDAO.newInstance().getOrganizationalDefaults();
            Test.stopTest();

            Integer count = 1;

            for (Designation__c dc : DesignationsDAO.newInstance().getDesignationsBySetRecordIds(
                        (new Map<Id, Designation__c>(designationList)).keySet(),AccessLevel.USER_MODE)
            ) {
                System.assert(String.isNotBlank(dc.Designation_Code__c), 'Blank ADVEDW code on record.');
                System.assertEquals('ADVEDW:' + String.valueOf(count).leftPad(5, '0'), dc.Designation_Code__c,'Incorrect ADVEDW Code');
                count++;
            }
            System.assertEquals(101, designationCodeAutoNum.Endowment__c, 'Incorrect latest ADVEDW code auto-number value.');

        }
    }
}