src/core-crm/objects/Stewardship__c/Stewardship__c.object-meta.xml
<CustomObject>
    <description>Stewardship captures data around donors who have been identified to be stewarded, by entering into a Stewardship Plan.</description>
    <label>Stewardship</label>
    <nameField>
        <displayFormat>STW-{000000}</displayFormat>
        <label>Stewardship Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stewardships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Stewardship__c/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <description>The business objective for the Plan.</description>
    <inlineHelpText>The business objective for the Plan.</inlineHelpText>
    <label>Objective</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

src/core-crm/classes/StewardshipTriggerHandlerTest.cls
/**
 * @description Test Class for StewardshipTriggerHandler. 
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | kenneth.f.alsay                | May 17, 2024          | DEPP-8789              | Created file                 |
 */
@isTest
public with sharing class StewardshipTriggerHandlerTest {
    @testSetup
    static void setup() {
        TestDataFactoryUser.generateUserDonorEngagementManager();
    }
    
    @isTest
    private static void testPlatformEventInsertAndUpdate() {
        System.runAs(TestDataFactoryUser.selectUserDonorEngagementManager) {
            List<Stewardship__c> stewardshipList = TestDataFactory.createStewardshipRecords(StewardshipsDAO.INDIVIDUAL_STEWARDSHIP_RECTYPE_ID,1);
            
            Test.startTest();
            System.assert(
                StewardshipsDAO.newInstance()
                    .insertRecords(stewardshipList, false, AccessLevel.USER_MODE)[0]
                    .isSuccess(),
                'Stewardship is not created'
            );
            
            stewardshipList[0].Objective__c = 'test update title';
            
            System.assert(
                StewardshipsDAO.newInstance()
                    .updateRecords(stewardshipList, false, AccessLevel.USER_MODE)[0]
                    .isSuccess(),
                'Stewardship is not updated'
            );
            Test.stopTest();
        }
    }
}