src/core-crm/objects/Product_Ledger__c/Product_Ledger__c.object-meta.xml
<CustomObject>
    <label>Product Ledger</label>
    <nameField>
        <displayFormat>PL-{00000000}</displayFormat>
        <label>Product Ledger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Ledgers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/Product_Ledger__c/fields/Offering_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Offering_End_Date__c</fullName>
    <description>End date of the Course/Program offering of the course enrollment.</description>
    <formula>Course_Connection__r.Offering_End_Date__c</formula>
    <label>Offering End Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Product_Ledger__c/fields/Offering_Ended__c.field-meta.xml
<CustomField>
    <fullName>Offering_Ended__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Offering Ended</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/classes/ProductLedgerEndedBatch.cls
/**
 * @description Batch class to check product ledgers that offering has ended
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | roy.nino.s.regala   	       | Aug 23, 2022          | DEPP-3482              | Created file                 | 
 */
public class ProductLedgerEndedBatch implements Database.Batchable<sObject> {

    /**
    * @description to end product ledgers that offering has passed
    * @param bc - BatchableContext
    * @return query - filtered query of product ledger records
    */
    public Database.QueryLocator start(Database.BatchableContext bc){
        String queryFilter = 
            'SELECT Id, Offering_Ended__c ' + 
            'FROM Product_Ledger__c ' + 
            'WHERE Offering_Ended__c = False ' + 
            'AND Offering_End_Date__c < TODAY';
        return Database.getQueryLocator(queryFilter);
    }

    /**
    * @description Method to execute the batch
    * @param bc - BatchableContext
    * @param assetList - List of assets
    */
    public void execute(Database.BatchableContext bc, List<Product_Ledger__c> productLedgerList){
        try{ 

            for(Product_Ledger__c prodLedger : productLedgerList){
                prodLedger.Offering_Ended__c= true;
            }

           update productLedgerList;

        }catch(Exception e){
            Logger.error('Exception caught in method execute in class ProductLedgerEndedBatch.').setExceptionDetails(e);
            Logger.saveLog();
        }
       
    } 

    public void finish(Database.BatchableContext bc) {}//NOPMD
}