src/core-crm/objects/Contact_Matching_Configuration__c/Contact_Matching_Configuration__c.object-meta.xml
<CustomObject>
    <label>Contact Matching Configuration</label>
    <nameField>
        <displayFormat>CMC-{000000}</displayFormat>
        <label>Contact Matching Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Matching Configurations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/core-crm/objects/Contact_Matching_Configuration__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <description>The Name of the field to remove noise string from.</description>
    <label>Field Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>FirstName</fullName>
            </value>
            <value>
                <fullName>LastName</fullName>
            </value>
            <value>
                <fullName>BirthDate</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Mobile Number</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Contact_Matching_Configuration__c/fields/Noise_String__c.field-meta.xml
<CustomField>
    <fullName>Noise_String__c</fullName>
    <description>The String value to be removed before the field is matched.</description>
    <label>Noise String</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/classes/ContactMatchingConfigurationServiceTest.cls
/**
* @description Tests the ContactMatchingConfigurationService
*
* @see ContactMatchingConfigurationService
*
* @author Accenture
*
* @history
*    | Developer Email           | Date                  | JIRA       | Change Summary                  |
     |---------------------------|-----------------------|------------|---------------------------------|
     | roy.nino.s.regala         | April 18, 2024        | DEPP-7986  | Created file                    |  
*/

@isTest
private class ContactMatchingConfigurationServiceTest {

    @isTest
    @SuppressWarnings('PMD.ApexUnitTestClassShouldHaveRunAs')
    // Service class is mocked, user will never create/update records. 
    //With this user access cannot be tested
    private static void processNoiseRemovalTest(){
        ImplementationSelector.DAO.setMock(new ContactMatchingConfigurationsDAOMock());
        ContactMatchingConfigurationsDAO.newInstance().insertRecords(new List<Contact_Matching_Configuration__c>{
            new Contact_Matching_Configuration__c(
                Field_Name__c = 'BirthDate',
                Noise_String__c ='1000-01-01'
            ),
            new Contact_Matching_Configuration__c(
                Field_Name__c = 'LastName',
                Noise_String__c ='+'
            ),
            new Contact_Matching_Configuration__c(
                Field_Name__c = 'All',
                Noise_String__c ='$'
            )
        },true,AccessLevel.SYSTEM_MODE);


        List<ContactMatchingService.MatchingAttributes> matchingRecords = new List<ContactMatchingService.MatchingAttributes>{ 
                new ContactMatchingService.MatchingAttributes(
                    new Map<String,String>{
                        'firstName' => 'firstname$',
                        'lastName' => 'lastname+',
                        'birthDate' => '1000-01-01',
                        'mobilePhone' => '65654+'
                }
            ) 
        };

        // generate a matching attributes map where the key is the concatenated attributes with the noise
        Map<String, ContactMatchingService.MatchingAttributes> matchingRecordsMap = ContactMatchingService.generateMatchingAttributeMap(matchingRecords);

        ContactMatchingConfigurationService.processNoiseRemoval(matchingRecordsMap);

        for(ContactMatchingService.MatchingAttributes matchingRecord : matchingRecordsMap.values()){
            System.assertEquals('',matchingRecord.get('birthDate'),'birthdate should be blank');
            System.assertEquals('',matchingRecord.get('mobilePhone'),'mobile should be blank');
            System.assertEquals('firstname',matchingRecord.get('firstName'),'firstName should be firstname');
            System.assertEquals('lastname',matchingRecord.get('lastName'),'lastName should be lastname');
        }
    }


}