src/core-crm/objects/List_Member__c/List_Member__c.object-meta.xml
<CustomObject>
    <description>List Member contains information about the Contacts who have been included in a Contact List and details about the staff member who contributed to compiling the list of contacts.</description>
    <label>List Member</label>
    <nameField>
        <displayFormat>LM-{0000000}</displayFormat>
        <label>List Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>List Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/List_Member__c/fields/List_Member__c.field-meta.xml
<CustomField>
    <fullName>List_Member__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>A Contact who has met the criteria to be included in the list.</description>
    <inlineHelpText>Contact who has met criteria for inclusion in the list.</inlineHelpText>
    <label>List Member</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>List Members</relationshipLabel>
    <relationshipName>List_Members</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/List_Member__c/fields/List_Member_Status__c.field-meta.xml
<CustomField>
    <fullName>List_Member_Status__c</fullName>
    <description>Indicates whether the prospective Contact has been qualified to move to the next Engagement stage.

Users can select ‘Not Applicable’ to mark a Contact who is not proceeding to the next stage but has not been officially ‘qualified’. For example, where a Contact has been mistakenly added to the list.</description>
    <inlineHelpText>Indicates whether the prospective Contact has been qualified to move to the next Engagement stage.</inlineHelpText>
    <label>List Member Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Qualified</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/classes/ListMemberCtrl.cls
/**
 * @description Controller Class for ListMemberCtrlTest LWC
 * @see ../lwc/ListMemberCtrlTest
 *
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary                                    |
 *    |--------------------------------|-----------------------|------------------------|---------------------------------------------------|
 *    | kenneth.f.alsay                | January 12, 2024      | DEPP-6964              | Created file                                      |
 *    |                                |                       |                        |                                                   |
 */
public class ListMemberCtrl {
	/**
    * @description Updates the List_Member_Status__c of the selected List Members from customHeaderDatatable
    * @param listMembers - List of List Members selected
    * @param status - New List Member Status 
    */
    @AuraEnabled
    public static void updateListMemberStatus(List<List_Member__c> listMembers, String status){        
        for(List_Member__c listMember : listMembers){
            listMember.List_Member_Status__c = status;
        }
        ListMembersDAO.newInstance().updateRecords(listMembers, false, AccessLevel.SYSTEM_MODE);       
    }
}