src/core-crm/objects/Action__c/Action__c.object-meta.xml
<CustomObject>
    <label>Action</label>
    <nameField>
        <label>Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Action__c/fields/Activity_Method__c.field-meta.xml
<CustomField>
    <fullName>Activity_Method__c</fullName>
    <label>Activity Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Meeting</fullName>
            </value>
            <value>
                <fullName>Survey</fullName>
            </value>
            <value>
                <fullName>Interview</fullName>
            </value>
            <value>
                <fullName>Workshops</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Action__c/fields/Activity_Name__c.field-meta.xml
<CustomField>
    <fullName>Activity_Name__c</fullName>
    <description>Name of the activity</description>
    <label>Activity Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Action__c/fields/Consultancy__c.field-meta.xml
<CustomField>
    <fullName>Consultancy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consultancy</label>
    <referenceTo>Consultancy__c</referenceTo>
    <relationshipLabel>Actions</relationshipLabel>
    <relationshipName>Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Action__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Date when the activity ends</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Action__c/fields/Investigation_Method__c.field-meta.xml
<CustomField>
    <fullName>Investigation_Method__c</fullName>
    <label>Investigation Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Meeting</fullName>
            </value>
            <value>
                <fullName>Survey</fullName>
            </value>
            <value>
                <fullName>Interview</fullName>
            </value>
            <value>
                <fullName>Workshops</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Action__c/fields/Investigation_Name__c.field-meta.xml
<CustomField>
    <fullName>Investigation_Name__c</fullName>
    <label>Investigation Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Action__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Date when the activity starts</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Action__c/fields/Summary__c.field-meta.xml
<CustomField>
    <fullName>Summary__c</fullName>
    <label>Summary</label>
    <length>75000</length>
    <type>LongTextArea</type>
</CustomField>

src/core-crm/objects/Consultancy__c/Consultancy__c.object-meta.xml
<CustomObject>
    <label>Consultancy</label>
    <nameField>
        <label>Consultancy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consultancies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Consultancy__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Consultancy End Date</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Consultancy__c/fields/Product_Request__c.field-meta.xml
<CustomField>
    <fullName>Product_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Consultancies</relationshipLabel>
    <relationshipName>Consultancies</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Consultancy__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>Consultancy Start date</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Product_Request__c/Product_Request__c.object-meta.xml
<CustomObject>
    <label>Product Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Product Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/classes/ActionsDAO.cls
/**
 * @description DAO Class for Action Object. Contains soql and constants related to the Action object.
 *
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | roy.nino.s.regala              | April 24, 2023        | DEPP-5567              | Created File                 | 
 */
public inherited sharing class ActionsDAO extends DmlBase implements IActionsDAO {
    /**
     * Action__c Constants
     */
    public static final String ACTIVITY_RECORDTYPE = System.Label.RT_Action_Activity;
    public static final Id ACTIVITY_RECORDTYPE_ID = Schema.SObjectType.Action__c.getRecordTypeInfosByDeveloperName()
        .get(ACTIVITY_RECORDTYPE)
        .getRecordTypeId();
    public static final String INVESTIGATION_RECORDTYPE = System.Label.RT_Action_Investigation;
    public static final Id INVESTIGATION_RECORDTYPE_ID = Schema.SObjectType.Action__c.getRecordTypeInfosByDeveloperName()
        .get(INVESTIGATION_RECORDTYPE)
        .getRecordTypeId();

    public static IActionsDAO newInstance() {
        return (IActionsDAO) ImplementationSelector.DAO.newInstance(Action__c.SObjectType);
    }

    public Schema.SObjectType getSObjectType() {
        return Action__c.SObjectType;
    }

    public List<Action__c> getActionsByProductRequestAndRecordType(
        Set<Id> productRequestIds,
        Id recordTypeId
    ) {
        return [
            SELECT
                Consultancy__r.Id,
                Name,
                Activity_Name__c,
                Activity_Method__c,
                Start_Date__c,
                End_Date__c,
                Investigation_Name__c,
                Investigation_Method__c,
                Is_Complete__c,
                Summary__c
            FROM Action__c
            WHERE
                Consultancy__r.Product_Request__r.Id IN :productRequestIds
                AND RecordTypeId = :recordTypeId
            WITH USER_MODE
        ];
    }
}