src/core-crm/objects/Asset/fields/Product_Request__c.field-meta.xml
<CustomField>
    <fullName>Product_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course__c/hed__Course__c.object-meta.xml
<CustomObject>
    <description>Academic Course offered by a Department or School, for example, English 101 or Ancient History.</description>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Enrollment__c/hed__Course_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Represents a connection to a Course Offering.</description>
    <label>Course Connection</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Course Connection ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Enrollment__c/fields/Course_Offering_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Course_Offering_End_Date__c</fullName>
    <formula>hed__Course_Offering__r.hed__End_Date__c</formula>
    <label>Course Offering End Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/hed__Course_Offering__c.field-meta.xml
<CustomField>
    <fullName>hed__Course_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Course Offering the student or faculty member is involved with.</description>
    <inlineHelpText>The Course Offering the student or faculty member is involved with.</inlineHelpText>
    <label>Course Offering ID</label>
    <referenceTo>hed__Course_Offering__c</referenceTo>
    <relationshipLabel>Course Connection</relationshipLabel>
    <relationshipName>Course_Enrollment</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Enrollment__c/fields/Program_Offering__c.field-meta.xml
<CustomField>
    <fullName>Program_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Offering</label>
    <referenceTo>Program_Offering__c</referenceTo>
    <relationshipLabel>Course Connections</relationshipLabel>
    <relationshipName>Course_Connections</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/hed__Course_Offering__c.object-meta.xml
<CustomObject>
    <description>Joins Courses and Terms to contain information related to a single occurrence of a Course.</description>
    <label>Course Offering</label>
    <nameField>
        <label>Course Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Course__c.field-meta.xml
<CustomField>
    <fullName>hed__Course__c</fullName>
    <description>Lookup to the Course record that this Course Offering is associated with.</description>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>
 

src/core-crm/objects/hed__Course_Offering__c/fields/hed__End_Date__c.field-meta.xml
<CustomField>
    <fullName>hed__End_Date__c</fullName>
    <description>The date of the last session for this Course Offering.</description>
    <inlineHelpText>The date of the last session for this Course Offering.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/hed__Course_Offering__c/fields/hed__Term__c.field-meta.xml
<CustomField>
    <fullName>hed__Term__c</fullName>
    <description>Lookup to the Term record that represents when this Course Offering takes place.</description>
    <label>Term</label>
    <referenceTo>hed__Term__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>
 

src/core-crm/objects/hed__Course_Offering__c/fields/Program_Offering__c.field-meta.xml
<CustomField>
    <fullName>Program_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Linked the course offering to the Program offering for Prescribed
    Program.</description>
    <label>Program Offering</label>
    <referenceTo>Program_Offering__c</referenceTo>
    <relationshipLabel>Course Offerings</relationshipLabel>
    <relationshipName>Course_Offerings</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Program_Plan__c/hed__Program_Plan__c.object-meta.xml
<CustomObject>
    <description>Links Courses to an Academic Program to create a path for students to follow. An Academic Program can list multiple Courses, and a Course can be associated with multiple Academic Programs.</description>
    <label>Program Plan</label>
    <nameField>
        <label>Program Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Program_Plan__c/fields/hed__End_Date__c.field-meta.xml
<CustomField>
    <fullName>hed__End_Date__c</fullName>
    <description>The end date for the Program Plan.</description>
    <inlineHelpText>The end date for the Program Plan.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/hed__Program_Plan__c/fields/Product_Request__c.field-meta.xml
<CustomField>
    <fullName>Product_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to store the related Product Request record of the Program Plan.</description>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Program Plans</relationshipLabel>
    <relationshipName>Program_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/hed__Term__c/hed__Term__c.object-meta.xml
<CustomObject>
    <description>Unit of time in which academic activities are taking place.</description>
    <label>Term</label>
    <nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/hed__Term__c/fields/hed__End_Date__c.field-meta.xml
<CustomField>
    <fullName>hed__End_Date__c</fullName>
    <description>The date this Term ends.</description>
    <inlineHelpText>The date this Term ends.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Product_Ledger__c/Product_Ledger__c.object-meta.xml
<CustomObject>
    <label>Product Ledger</label>
    <nameField>
        <displayFormat>PL-{00000000}</displayFormat>
        <label>Product Ledger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Ledgers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/Product_Ledger__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Product Ledgers</relationshipLabel>
    <relationshipName>Product_Ledgers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/core-crm/objects/Product_Ledger__c/fields/Course_Connection__c.field-meta.xml
<CustomField>
    <fullName>Course_Connection__c</fullName>
    <label>Course Connection</label>
    <referenceTo>hed__Course_Enrollment__c</referenceTo>
    <relationshipLabel>Product Ledgers</relationshipLabel>
    <relationshipName>Product_Ledgers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/core-crm/objects/Product_Ledger__c/fields/Course_Offering_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Course_Offering_End_Date__c</fullName>
    <description>Value from Course Offering End Date. Used for roll up summary in Asset object.</description>
    <formula>Course_Connection__r.hed__Course_Offering__r.hed__End_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Course Offering End Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Product_Ledger__c/fields/Course_Offering_End_Date_Checker__c.field-meta.xml
<CustomField>
    <fullName>Course_Offering_End_Date_Checker__c</fullName>
    <description>Used in flow to check if Course_Offering_End_Date is today, in the future, or in the past.</description>
    <label>Course Offering End Date Checker</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Product_Request__c/Product_Request__c.object-meta.xml
<CustomObject>
    <label>Product Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Product Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Program_Offering__c/Program_Offering__c.object-meta.xml
<CustomObject>
    <label>Program Offering</label>
    <nameField>
        <label>Program Offering ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Offerings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/classes/Course_Offering_End_Dt_Filter_FlowTest.cls
/**
 * @description Test Class for Course Offering End Date Filter Flow
 *
 * @see ../flows/Course_Offering_End_Date_Filter_Flow
 *
 * @author Accenture
 *
 * @history
 *    | Developer                 | Date                  | JIRA         | Change Summary                                                                           |
      |---------------------------|-----------------------|--------------|------------------------------------------------------------------------------------------|
      | eccarius.munoz            | December 24, 2021     | DEPP-1109    | Created file                                                                             |
      | johnbo.pineda@qut.edu.au  | January 05, 2022      | DEPP-1382    | Modified to accommodate changes to TestDataFactory for createTestCourseConnectionRecord. |
      | justine.javier@qut.edu.au | February 25, 2022     | DEPP-1819    | Removed Program_Offering__c logic       													|                                                                                          |

*/
@IsTest(SeeAllData = false)
private class Course_Offering_End_Dt_Filter_FlowTest{

    private static User  currentUser = TestDataFactory.createUserRecords(1, 'QUTeX').iterator().next();
    private static Integer numberOfRecords = 100;

    @IsTest
    private static void courseOfferingFilterEndDateFlowTest(){
        System.runAs(currentUser){
            List<Account> accounts = TestDataFactory.createTestAccountRecords(1);
            insert accounts;

            List<hed__Term__c> terms = TestDataFactory.createTestTermRecords(numberOfRecords, accounts[0].Id);
            insert terms;

            List<Product_Request__c> prodRequest = TestDataFactory.createTestProductRequestRecords(1);
            insert prodRequest;

            List<hed__Course__c> courses = TestDataFactory.createTestCourseRecords(numberOfRecords, accounts[0].Id, prodRequest[0].Id);
            insert courses;

            List<hed__Course_Offering__c> courseOfferings = TestDataFactory.createTestCourseOfferingRecord(numberOfRecords, courses, terms);
            insert courseOfferings;

            List<Contact> contacts = TestDataFactory.createTestContactRecords(1);
            insert contacts;

            List<hed__Program_Plan__c> programPlans = TestDataFactory.createTestProgramPlanRecords(1);
            insert programPlans;

            List<hed__Course_Enrollment__c> courseConnections = TestDataFactory.createTestCourseConnectionRecord(1, contacts[0].Id, courseOfferings);
            insert courseConnections;

            List<Asset> assets = TestDataFactory.createTestAssetRecords(10, accounts[0].Id, prodRequest[0].Id);
            insert assets;

            List<Product_Ledger__c> productLedgers = new List<Product_Ledger__c>();
            Product_Ledger__c productLedger = new Product_Ledger__c();
            productLedger.Course_Connection__c = courseConnections[0].Id;
            productLedger.Asset__c = assets[0].Id;
            productLedgers.add(productLedger);
            insert productLedgers;

            Test.startTest();
            Integer todayOrFutureResp = updateCourseOfferingEndDate(10, '2');
            Integer pastResp = updateCourseOfferingEndDate(-10, '1');
            Test.stopTest();

            System.assertEquals(0, todayOrFutureResp, 'End date of course offering must be filtered as today or in the future.');
            System.assertEquals(0, pastResp, 'End date of course offering must be filtered as past.');
        }
    }

    private static Integer updateCourseOfferingEndDate(Integer numberOfDays, String checker){
        List<hed__Course_Offering__c> courseOfferingList = [SELECT Id, hed__End_Date__c FROM hed__Course_Offering__c];

        Date newDate2 = Date.today().AddDays(numberOfDays);
        for(hed__Course_Offering__c courseOffering : courseOfferingList){
            courseOffering.hed__End_Date__c = newDate2;
        }
        update courseOfferingList;

        List<Product_Ledger__c> productLedgerList = [SELECT Id, Course_Connection__c, Course_Offering_End_Date__c, Course_Offering_End_Date_Checker__c FROM Product_Ledger__c];

        Integer checkerCounter = 0;
        for(Product_Ledger__c productLedger: productLedgerList){
            if(productLedger.Course_Offering_End_Date_Checker__c == checker){
                checkerCounter ++ ;
            }
        }
        return checkerCounter;
    }
}