src/core-crm/objects/Asset/fields/Product_Request__c.field-meta.xml
<CustomField>
    <fullName>Product_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Asset/fields/Publishing_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Publishing_End_Date__c</fullName>
    <label>Publishing End Date</label>
    <type>Date</type>
</CustomField>

src/core-crm/objects/Associated_Products__c/Associated_Products__c.object-meta.xml
<CustomObject>
    <label>Associated Products</label>
    <nameField>
        <displayFormat>AP - {000000}</displayFormat>
        <label>Associated Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associated Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/core-crm/objects/Associated_Products__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Determine if the Associated Product is active or not.</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

src/core-crm/objects/Associated_Products__c/fields/Product_Request__c.field-meta.xml
<CustomField>
    <fullName>Product_Request__c</fullName>
    <label>Product Request</label>
    <referenceTo>Product_Request__c</referenceTo>
    <relationshipLabel>Associated Products</relationshipLabel>
    <relationshipName>Associated_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/core-crm/objects/Product_Request__c/Product_Request__c.object-meta.xml
<CustomObject>
    <label>Product Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Product Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Product_Request__c/fields/Product_Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Product_Request_Status__c</fullName>
    <label>Product Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Define</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Release</fullName>
            </value>
            <value>
                <fullName>In Delivery</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/classes/AssetToCompleteBatch.cls
/**
 * @description Batch class to complete related product requests of assets
 * 
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | alexander.cadalin   	       | Aug. 11, 2022         | DEPP-3481              | Created file                 | 
 */
public class AssetToCompleteBatch implements Database.Batchable<sObject>
{

    private static final String PR_COMPLETED = System.Label.PL_ProductRequest_Completed;
    private static final String PR_NOT_PROCEEDING = System.Label.PL_ProductRequest_Not_Proceeding;
    

    /**
    * @description to complete SOA product request
    * @param bc - BatchableContext
    * @return query - filtered query of Asset records
    */
    public Database.QueryLocator start(Database.BatchableContext bc)
    {

        String query = 
        'SELECT Id, Product_Request__c ' + 
        'FROM Asset ' + 
    	'WHERE (End_Date__c <= TODAY  OR Publishing_End_Date__c <= TODAY)' + 
        'AND Product_Request__r.Product_Request_Status__c != \' ' + PR_COMPLETED + '\' ' +
        'AND Product_Request__r.Product_Request_Status__c != \' ' + PR_NOT_PROCEEDING + '\'';
        return Database.getQueryLocator(query);
    }
    /**
    * @description Method to execute the batch
    * @param bc - BatchableContext
    * @param assetList - List of assets
    */
    public void execute(Database.BatchableContext bc, List<Asset> assetList)
    {
        try{ 
            Set<Id> corporateBundleProductRequestIds = new Set<Id>();
            Map<Id, Product_Request__c> productRequestToComplete = new Map<Id, Product_Request__c>();
            Map<Id, Associated_Products__c> ascProductsToInactive = new Map<Id, Associated_Products__c>();

            for(Asset a: assetList){
                corporateBundleProductRequestIds.add(a.Product_Request__c);
                productRequestToComplete.put(   
                    a.Product_Request__c, 
                    new Product_Request__c( 
                        Id = a.Product_Request__c, 
                        Product_Request_Status__c = PR_COMPLETED
                    ) 
                );
            }

            //deactivate OPE product request linkage
            for(Associated_Products__c ascProd: [
                SELECT Id, IsActive__c
                FROM Associated_Products__c
                WHERE Product_Request__c IN: corporateBundleProductRequestIds
                AND IsActive__c = true
            ]){
                ascProd.IsActive__c = false;
                ascProductsToInactive.put(ascProd.Id,ascProd);
            }

            if(!ascProductsToInactive.keySet().isEmpty()){
                update ascProductsToInactive.values();
            }

            if(!productRequestToComplete.keySet().isEmpty()){
                update productRequestToComplete.values();
            }

        }catch(Exception e){
           Logger.error('Exception caught in AssetToCompleteBatch.cls').setExceptionDetails(e);
        } finally {
            if(Logger.getBufferSize() > 0) {
                Logger.saveLog();
            }
        }
    }  
    public void finish(Database.BatchableContext bc) {} //NOPMD
}