src/core-crm/objects/Answer__c/Answer__c.object-meta.xml
<CustomObject>
    <description>This will store the answers to each questions presented in a questionnaire.</description>
    <label>Answer</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Answer__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the contact answering the questionnaire.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Answer__c/fields/Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the questionnaire.</description>
    <label>Questionnaire</label>
    <referenceTo>Questionnaire__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Answer__c/fields/Questionnaire_Response_Summary__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire_Response_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links the answer to the Questionnaire Response Summary.</description>
    <label>Questionnaire Response Summary</label>
    <referenceTo>Questionnaire_Response_Summary__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Answer__c/fields/Related_Answer__c.field-meta.xml
<CustomField>
    <fullName>Related_Answer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to related answer that link Questionnaire and Question records.</description>
    <label>Related Answer</label>
    <referenceTo>Related_Answer__c</referenceTo>
    <relationshipLabel>Answers</relationshipLabel>
    <relationshipName>Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Cart_Payment__c/Cart_Payment__c.object-meta.xml
<CustomObject>
    <label>Cart Payment</label>
    <nameField>
        <label>Cart Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cart Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Cart_Payment__c/fields/Discount_Applied__c.field-meta.xml
<CustomField>
    <fullName>Discount_Applied__c</fullName>
    <description>The discount subtracted to the cart total using the coupon</description>
    <label>Discount Applied</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/Cart_Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <description>Payment status returned from QUTPay</description>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled Payment</fullName>
            </value>
            <value>
                <fullName>Validation Failure</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Cart_Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Checkout</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/CartItem/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cart Items</relationshipLabel>
    <relationshipName>Cart_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/CartItem/fields/Course_Offering__c.field-meta.xml
<CustomField>
    <fullName>Course_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The associated course offering that’s added to the cart</description>
    <label>Course Offering</label>
    <referenceTo>hed__Course_Offering__c</referenceTo>
    <relationshipLabel>Cart Items</relationshipLabel>
    <relationshipName>Cart_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/CartItem/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>Foreign Key for Integration and Data Migration</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/CartItem/fields/Program_Offering__c.field-meta.xml
<CustomField>
    <fullName>Program_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The associated program offering that’s added to the cart</description>
    <label>Program Offering</label>
    <referenceTo>Program_Offering__c</referenceTo>
    <relationshipLabel>Cart Items</relationshipLabel>
    <relationshipName>Cart_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/CartItem/fields/Promotion__c.field-meta.xml
<CustomField>
    <fullName>Promotion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID reference of the details of the promotion used in the registration</description>
    <label>Promotion</label>
    <referenceTo>Promotion</referenceTo>
    <relationshipLabel>Cart Items</relationshipLabel>
    <relationshipName>Cart_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/CartItem/fields/Promotion_Price__c.field-meta.xml
<CustomField>
    <fullName>Promotion_Price__c</fullName>
    <description>The actual discount deducted from the list/actual price.</description>
    <label>Promotion Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/core-crm/objects/Contact/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Foreign Key for Integration and Data Migration</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/core-crm/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tailored Executive Program</fullName>
            </value>
            <value>
                <fullName>Corporate Bundle</fullName>
            </value>
            <value>
                <fullName>QUTeX Learning Solutions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/Questionnaire_Response_Summary__c/Questionnaire_Response_Summary__c.object-meta.xml
<CustomObject>
    <description>This will summarise the response of leaner to a questionnaire per offering.</description>
    <label>Questionnaire Response Summary</label>
    <nameField>
        <displayFormat>QRS-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questionnaire Response Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Questionnaire_Response_Summary__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the contact answering the questionnaire.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Questionnaire Response Summaries</relationshipLabel>
    <relationshipName>Questionnaire_Response_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Questionnaire_Response_Summary__c/fields/Course_Offering__c.field-meta.xml
<CustomField>
    <fullName>Course_Offering__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the course offering the responses answered from.</description>
    <label>Course Offering</label>
    <referenceTo>hed__Course_Offering__c</referenceTo>
    <relationshipLabel>Questionnaire Response Summaries</relationshipLabel>
    <relationshipName>Questionnaire_Response_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Questionnaire_Response_Summary__c/fields/Payment_URL__c.field-meta.xml
<CustomField>
    <fullName>Payment_URL__c</fullName>
    <description>Whole payment URL that redirects to QUT Pay</description>
    <label>Payment URL</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

src/core-crm/objects/Questionnaire_Response_Summary__c/fields/Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the questionnaire containing questions.</description>
    <label>Questionnaire</label>
    <referenceTo>Questionnaire__c</referenceTo>
    <relationshipLabel>Questionnaire Response Summaries</relationshipLabel>
    <relationshipName>Questionnaire_Response_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/Related_Answer__c/Related_Answer__c.object-meta.xml
<CustomObject>
    <description>This will be junction object to link Questionnaire and Question records.</description>
    <label>Related Answer</label>
    <nameField>
        <displayFormat>QQ-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/core-crm/objects/Related_Answer__c/fields/Questionnaire__c.field-meta.xml
<CustomField>
    <fullName>Questionnaire__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the questionnaire.</description>
    <label>Questionnaire</label>
    <referenceTo>Questionnaire__c</referenceTo>
    <relationshipLabel>Related Answers</relationshipLabel>
    <relationshipName>Related_Answers</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/WebCart/fields/Cart_Payment__c.field-meta.xml
<CustomField>
    <fullName>Cart_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cart Payment</label>
    <referenceTo>Cart_Payment__c</referenceTo>
    <relationshipLabel>Carts</relationshipLabel>
    <relationshipName>Carts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/core-crm/objects/WebCart/fields/Discount_Applied__c.field-meta.xml
<CustomField>
    <fullName>Discount_Applied__c</fullName>
    <description>The discount subtracted to the cart total using the coupon</description>
    <label>Discount Applied</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/core-crm/objects/WebCart/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>Foreign Key for Integration and Data Migration</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/WebCart/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <description>Payment status returned from QUTPay</description>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled Payment</fullName>
            </value>
            <value>
                <fullName>Validation Failure</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/objects/WebCart/fields/Payment_URL__c.field-meta.xml
<CustomField>
    <fullName>Payment_URL__c</fullName>
    <description>Whole payment URL that redirects to QUT Pay</description>
    <label>Payment URL</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

src/core-crm/objects/WebCart/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Active = User in the process of adding items in cart

Checkout = User on checkout and prevents from updating cart

Closed = cart no longer available to the user</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Checkout</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/core-crm/classes/ManageRegistrationSectionHelper.cls
/**
 * @description helper class for manageregistrationsectionctrl
 * @see ../manageregistrationsectionctrl
 *
 * @author Accenture
 *
 * @history
 *    | Developer                 | Date                  | JIRA                 | Change Summary               |
      |---------------------------|-----------------------|----------------------|------------------------------|
      | roy.nino.s.regala         | November 15, 2022     | DEPP-4721            | Created file                 |
*/

public with sharing class ManageRegistrationSectionHelper extends ManageRegistrationEnrolmentHelper{

     private static final String TAILORED_EXECUTIVE_PROGRAM = 'Tailored Executive Program';

     public static EnrolmentResultClass processEnrollmentWithPricing(RegistrationData parsedRegistrationData, Contact finalContactRecord, String contactRecName, Product2 product){
          
          EnrolmentResultClass enrollmentProcessingReturn = new EnrolmentResultClass();
          EnrolmentCreationParamClass enrolmentParam;
          Map<String,Asset> assetRecord = new Map<String,Asset>();

          Boolean isTailored = product != null && product.Product_Category__c == TAILORED_EXECUTIVE_PROGRAM?true:false;
          Id commerceUser;
                    
          Id priceBookEntryId = parsedRegistrationData.priceBookEntryId;
          Decimal discountAmount = parsedRegistrationData.discountAmount;
          Contact contactRecord = parsedRegistrationData.contactRecord;
          String offeringId = parsedRegistrationData.offeringId;
          Boolean prescribedProgram = parsedRegistrationData.prescribedProgram;
          Id promotionId = parsedRegistrationData.promotionId;
          Boolean isProceedNoInvoice = parsedRegistrationData.isProceedNoInvoice;
          


          PricebookEntry pbe = new PricebookEntry();
          Boolean isCorporateBundlePricing = false;
          Boolean isSOAPricing = false;
          Decimal amount;
          List<PricebookEntry> pbList = [SELECT Id, UnitPrice, Product2Id, PriceBook2Id, PriceBook2.Name FROM PricebookEntry WHERE Id =: priceBookEntryId LIMIT 1];

          for(PricebookEntry pb : pbList){
               isCorporateBundlePricing = pb.PriceBook2.Name.startsWith('Corporate Bundle');
               isSOAPricing = pb.PriceBook2.Name.startsWith('SOA');
               pbe = pb;
               amount = pb.UnitPrice - discountAmount;
          }

          List<User> corporateUser = new List<User>();
          WebCart newWebCart = new WebCart();
          //only try to get corporate user if selected pricing is SOA or Corporate Bundle
          if((isCorporateBundlePricing == true || isSOAPricing == true)){
               //get corporate user linked to the pricebookentry selected
               corporateUser = CorporateBundleAndSOAHelper.getCorporateUser(pbe.PriceBook2Id);
          }

          if(!corporateUser.isEmpty()){
               newWebCart = CorporateBundleAndSOAHelper.createCCEWebCart(corporateUser[0]);
               commerceUser = corporateUser[0].Id;
          }else if(corporateUser.isEmpty() && (isCorporateBundlePricing == true || isSOAPricing == true)){
               throw new AuraHandledException('Please make sure to enable the contact as Partner User');
          }else{
               commerceUser = ManageRegistrationEnrolmentHelper.createUser(finalContactRecord.Email, finalContactRecord.LastName, finalContactRecord.FirstName, contactRecord.Id);
               newWebCart = ManageRegistrationEnrolmentHelper.createWebCart(commerceUser, contactRecord.Id);
          }
          
          insert newWebCart;                    

          CartDeliveryGroup cartDeliveryGroup = new CartDeliveryGroup(
               CartId = newWebCart.Id,
               Name = 'Default Delivery'
          );
          insert cartDeliveryGroup;

          enrolmentParam = new EnrolmentCreationParamClass();
                    
          enrolmentParam.offeringId = offeringId;
          enrolmentParam.prescribedProgram = prescribedProgram;
          enrolmentParam.newWebCartId = newWebCart.Id;
          enrolmentParam.priceBookEntry = pbe;
          enrolmentParam.product = product;
          enrolmentParam.cartDeliveryGroupId = cartDeliveryGroup.Id;
          
          CartItem newCartItem = ManageRegistrationEnrolmentHelper.createCartItem(enrolmentParam);
          newCartItem.Contact__c = contactRecord.Id;
          newCartItem.Promotion__c = promotionId;
          newCartItem.Promotion_Price__c = discountAmount;
          insert newCartItem;

          if(!isProceedNoInvoice){
               Cart_Payment__c cartPayment = new Cart_Payment__c(
                    Status__c = 'Invoiced', 
                    Discount_Applied__c = discountAmount
               );
               insert cartPayment;

               String externalId = [    SELECT Id, External_Id__c 
                                        FROM WebCart 
                                        WHERE OwnerId =: commerceUser 
                                        AND Status = 'Active' 
                                        LIMIT 1].External_Id__c; 

               PaymentUrlClass urlObj = new PaymentUrlClass();

               urlObj.CartExternalId = externalId;
               urlObj.Email = finalContactRecord.Email;
               urlObj.Name = contactRecName;
               urlObj.Amount = amount;
               urlObj.ProductName = product.Name;
               urlObj.IsCCE = isSOAPricing;

               String paymentURL = ManageRegistrationEnrolmentHelper.paymentGatewayURLBuilder(urlObj);
     
               WebCart webCartToClose = new WebCart(
                    Id = newWebCart.Id,
                    Status__c = 'Closed',
                    Status = 'Closed',
                    Cart_Payment__c = cartPayment.Id,
                    Payment_URL__c = paymentURL
               );
               update webCartToClose;

               //update cart payment to invoiced after linking the webcart
               //so that the cart payment trigger can check related cartitems
               cartPayment.Payment_Status__c = 'Invoiced';
               update cartPayment;                   

               enrollmentProcessingReturn.contactId = contactRecord.Id;
               enrollmentProcessingReturn.paymentURL = paymentURL;
               enrollmentProcessingReturn.contactName = contactRecName;

          }else{
               String externalId;
               List<WebCart> carts = [SELECT External_Id__c FROM WebCart WHERE OwnerId =: commerceUser LIMIT 1];
               for(WebCart webCart : carts){ externalId = webCart.External_Id__c; }
      
               WebCart webCartToClose = new WebCart(
                   Id = newWebCart.Id,
                   Status__c = 'Closed',
                   Status = 'Closed'
               );
               update webCartToClose;

               enrolmentParam = new ManageRegistrationEnrolmentHelper.EnrolmentCreationParamClass();
                    
               enrolmentParam.contactId = contactRecord.Id;
               enrolmentParam.offeringId = offeringId;
               enrolmentParam.prescribedProgram = prescribedProgram;
               enrolmentParam.isTailored = isTailored;
               enrolmentParam.amount = amount;
               enrolmentParam.newWebCartId = newWebCart.Id;
               enrolmentParam.newCartItemId = newCartItem.Id;
               
               List<hed__Course_Enrollment__c> courseConnectionList = ManageRegistrationEnrolmentHelper.createCourseConnectionList(enrolmentParam);                               
               insert courseConnectionList;
               
               enrollmentProcessingReturn.contactId = contactRecord.Id;
               enrollmentProcessingReturn.contactName = contactRecName;

               //if corporate pricing is selected
               if(isCorporateBundlePricing == true){
                    //get asset record related to corporate bundle
                    List<String> pbEntryIds = new List<String>();
                    pbEntryIds.add(priceBookEntryId);
                    assetRecord = CorporateBundleAndSOAHelper.getAsset(pbEntryIds);
                    
               }

               if(assetRecord.containsKey(priceBookentryId)){
                    CorporateBundleAndSOAHelper.createProductLedgerRecords(assetRecord.get(priceBookentryId).Id, courseConnectionList);
               }
          }
          
          return enrollmentProcessingReturn;
     }

     public static void processQuestionnaireData(RegistrationData parsedRegistrationData, String fileUpload){

          //set registration data into separate readable variables
          List<Related_Answer__c> relatedAnswerList = parsedRegistrationData.relatedAnswerList;
          Boolean prescribedProgram = parsedRegistrationData.prescribedProgram;
          List<Answer__c> answerList = parsedRegistrationData.answerList;
          String offeringId = parsedRegistrationData.offeringId;
          Contact contactRecord = parsedRegistrationData.contactRecord; 
          
          
          Set<Id> questionnaireIds = new Set<Id>();
          Map<Id,Id> relatedAnswerToQuestionnaireMap = new Map<Id,Id>();
          List<Questionnaire_Response_Summary__c> questionnaireSummaryToInsert = new List<Questionnaire_Response_Summary__c>();
          Map<Id,Id> questionnaireToqResSummaryMap = new Map<Id,Id>();
          List<Answer__c> answersToInsert = new List<Answer__c>();

          List<FileUpload> parsedFileUpload = new List<FileUpload>();

          if(fileUpload != ''){
               parsedFileUpload = (List<FileUpload>) JSON.deserialize(fileUpload, List<FileUpload>.class);
          }
          
          for(Related_Answer__c relatedA: relatedAnswerList){
               questionnaireIds.add(relatedA.Questionnaire__c);
               relatedAnswerToQuestionnaireMap.put(relatedA.Id,relatedA.Questionnaire__c);
          }

          Questionnaire_Response_Summary__c qResSummary;

          for(Id qId:questionnaireIds){
               qResSummary = new Questionnaire_Response_Summary__c();
               qResSummary.Questionnaire__c = qId;
               if(!prescribedProgram){
                    qResSummary.Course_Offering__c = offeringId;
               }else{
                    qResSummary.Program_Offering__c = offeringId;
               }
               qResSummary.Registration_Status__c = 'Confirmed';
               qResSummary.Contact__c = contactRecord.Id;
               questionnaireSummaryToInsert.add(qResSummary);
          }

          if(!questionnaireSummaryToInsert.isEmpty()){
               insert questionnaireSummaryToInsert;
          }

          for(Questionnaire_Response_Summary__c questionResSummary: questionnaireSummaryToInsert){
               questionnaireToqResSummaryMap.put(questionResSummary.Questionnaire__c,questionResSummary.Id);
          }

          if(!answerList.isEmpty()){
               for(Answer__c a: answerList){
                    a.Questionnaire_Response_Summary__c = questionnaireToqResSummaryMap.get(relatedAnswerToQuestionnaireMap.get(a.Related_Answer__c));
                    answersToInsert.add(a);
               }
               insert answersToInsert;

               processFileUpload(answersToInsert,parsedFileUpload);
          }

          
     }

     private static void processFileUpload(List<Answer__c> answersToInsert, List<FileUpload> parsedFileUpload){

          Map<Id,Id> relatedAnswerToAnswerMap = new Map<Id,Id>();
          Map<String,String> cvToRelatedAnswerMap = new Map<String,String>();
          List<ContentVersion> cvListToInsertList = new List<ContentVersion>();
          List<ContentVersion> newContentVersionList = new List<ContentVersion>();
          ContentDocumentLink cdl;
          Answer__c updateAnswer;
          List<ContentDocumentLink> contentDocLinkListToInsert = new List<ContentDocumentLink>();
          Map<Id,Answer__c> answersToUpdate = new Map<Id,Answer__c>();

          for(Answer__c ans :answersToInsert){
               relatedAnswerToAnswerMap.put(ans.Related_Answer__c,ans.Id);
          }

          for(FileUpload file: parsedFileUpload){
               if(relatedAnswerToAnswerMap.containsKey(file.RelatedAnswerId)){
                    ContentVersion cv = createContentVersion(file.Base64, file.FileName);
                    cvToRelatedAnswerMap.put(cv.Title,file.RelatedAnswerId);
                    cvListToInsertList.add(cv);
               }
          }

          if(!cvListToInsertList.isEmpty()){
               insert cvListToInsertList;

               newContentVersionList = new List<ContentVersion>([ 
                    SELECT ContentDocumentId, Title
                    FROM ContentVersion
                    WHERE Id IN:cvListToInsertList]);


               for(ContentVersion cv:newContentVersionList){
                    cdl = new ContentDocumentLink(
                         ContentDocumentId = cv.ContentDocumentId,
                         LinkedEntityId = relatedAnswerToAnswerMap.get(cvToRelatedAnswerMap.get(cv.Title)),
                         ShareType = 'V'
                    );
                    updateAnswer = new Answer__c(
                         Id = cdl.LinkedEntityId,
                         Response__c = cv.ContentDocumentId
                    );
                    answersToUpdate.put(updateAnswer.Id,updateAnswer);
                    contentDocLinkListToInsert.add(cdl);
               }

               insert contentDocLinkListToInsert;
               update answersToUpdate.values();
          }
     }

     private static ContentVersion createContentVersion(String base64, String filename) {
          ContentVersion cv = new ContentVersion();
          cv.VersionData = EncodingUtil.base64Decode(base64);
          cv.Title = filename;
          cv.PathOnClient = filename;
          return cv;
     }

     /**
      * @description Wrapper class that holds the file uploaded by user
      */
      public class FileUpload{
          @AuraEnabled
          public String base64;
          @AuraEnabled
          public String fileName;
          @AuraEnabled
          public String relatedAnswerId;
      }
     
}