src/core-crm/objects/Student_Sanction__c/Student_Sanction__c.object-meta.xml
<CustomObject>
    <description>Contains Sanction data applied to student or student program</description>
    <label>Student Sanction</label>
    <nameField>
        <displayFormat>SS-{000000}</displayFormat>
        <label>Student Sanction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Sanctions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/core-crm/objects/Student_Sanction__c/fields/Batch_Process__c.field-meta.xml
<CustomField>
    <fullName>Batch_Process__c</fullName>
    <description>Indicating the record&apos;s state whether to be actioned with insert, update or processed</description>
    <label>Batch Process</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Batch_Process</valueSetName>
    </valueSet>
</CustomField>

src/core-crm/objects/Student_Sanction__c/fields/QUT_Student_ID__c.field-meta.xml
<CustomField>
    <fullName>QUT_Student_ID__c</fullName>
    <description>Unique student Id assigned by student administration system.</description>
    <label>QUT Student ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

src/core-crm/objects/Student_Sanction__c/fields/Sanction_Code__c.field-meta.xml
<CustomField>
    <fullName>Sanction_Code__c</fullName>
    <description>The Sanction Code for the associated Sanction</description>
    <label>Sanction Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

src/core-crm/globalValueSets/Batch_Process.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Processed</fullName>
    </customValue>
    <customValue>
        <fullName>Insert</fullName>
    </customValue>
    <customValue>
        <fullName>Update</fullName>
    </customValue>
    <description>Indicating the record&apos;s state whether to be actioned with insert, update or processed</description>
    <masterLabel>Batch Process</masterLabel>
</GlobalValueSet>

src/core-crm/classes/StudentSanctionsDAO.cls
/**
 * @description DAO Class for Student Sanction Object. Contains soql and constants related to the Student Sanction object.
 * @author Accenture
 *
 * @history
 *
 *    | Developer Email                | Date                  | JIRA                   | Change Summary               |
      |--------------------------------|-----------------------|------------------------|------------------------------|
      | roy.nino.s.regala              | April 24, 2024        | DEPP-7984              | Created file
 */
public inherited sharing class StudentSanctionsDAO extends DmlBase implements IStudentSanctionsDAO{

	public static final String INSERT_PROCESS = 'Insert';
	public static final String PROCESSED = 'Processed';

    public Schema.SObjectType getSObjectType()
	{
		return Student_Sanction__c.SObjectType;
	}

    public static IStudentSanctionsDAO newInstance()
	{
		return (IStudentSanctionsDAO) ImplementationSelector.DAO.newInstance(Student_Sanction__c.SObjectType);
	}
	
	public Database.QueryLocator queryLocatorGetStudentSanctionsByBatchProcess(Set<String> batchProcessSet, AccessLevel accessLevel){
        String query =
		' SELECT Id, Sanction_Code__c, QUT_Student_ID__c ' +
		' FROM Student_Sanction__c ' +
		' WHERE Batch_Process__c IN: batchProcessSet ';
        return Database.getQueryLocator(query,accessLevel);
    }

	public List<Student_Sanction__c> getStudentSanctionsByBatchProcess(Set<String> batchProcessSet, AccessLevel accessLevel){

		if(batchProcessSet.isEmpty()){
			return new List<Student_Sanction__c>();
		}
		
        String query =
		' SELECT Id, Sanction_Code__c, QUT_Student_ID__c ' +
		' FROM Student_Sanction__c ' +
		' WHERE Batch_Process__c IN: batchProcessSet ' +
		' LIMIT 1 ';
        return Database.query(query,accessLevel);
    }

}